### ISSUE TITLE
Nodes lagging behind on schema sync can be overloaded with schema pulls 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#10042]
If table schema version is absent in cache, it will be fetched from the coordinator. This is not expensive, but if the version is not known, it must be also "synced". It means that the node will do a full schema pull from the coordinator. This pull is expensive and can take seconds.

If the coordinator we pull from is at an old version, the pull will do nothing and current node will soon forget the old version, initiating another pull next time.

If some nodes stay at an old version for a long time for some reason, this will make new coordinators initiate pulls frequently. This has two negative consequences:
  1) nodes which are still at an old version will be overloaded with pull requests
  2) request latency will be impacted for a prolonged period because requests which initiate pulls will wait for pulls to complete

**Comment by eliransin** [comment]
We can give "long life" only to the information about the synced schemas.
Just save some kind of a cache like list of the schemas that have already been synced into the node's main schema.
This will ensure that for the "hot" schemas the sync will only occur once.
@tgrabiec WDYT?

**Comment by tgrabiec** [comment]
@eliransin That would be cheaper than storing full schemas. But if  we get a sync request for a given version, it means we also need the schema. So it makes sense to cache schemas for the same duration as we cache the "synced schema versions". 

We could evict expired schemas when schema agreement is reached to save on space.

**Comment by kbr-scylla** [comment]
> If the coordinator we pull from is at an old version, the pull will do nothing and current node will soon forget the old version, initiating another pull next time.

> If some nodes stay at an old version for a long time for some reason, this will make new coordinators initiate pulls frequently. 

In 5.4+ the pulls were replaced with group 0 barriers, which guarantee that we obtain the latest schema version, so this particular problem won't occur.


It's still arguable that barrier is not in general faster, in fact, there is only a single node in the cluster that replicates group 0 to other nodes, and that is the current Raft group 0 leader. This is a bottleneck; all nodes must wait for replication from this single leader. If the leader is slow, it will take a long time, and increase latency significantly. However:
- there's a large chance that the group 0 command is already replicated to all nodes at the moment we apply it on any node: there's a guarantee that the command was replicated to at least a quorum
- if the command was already replicated to some follower, the only thing that the leader needs to replicate to that follower is the commit index, which is a small piece of data
- OTOH if there are other commands that follow our schema change, the leader will not try to replicate the commit index by itself, but it will try to send a single "append entry" message that contains both the new entries and the new commit index. Which might slow down replication.

Anyway, since the original problem discussed in the issue is gone in newer releases, I think we can close this issue. @tgrabiec WDYT?

**Comment by tgrabiec** [comment]
> Anyway, since the original problem discussed in the issue is gone in newer releases, I think we can close this issue.

Yes, just quote a commit which fixes it.

**Comment by kbr-scylla** [comment]
Fixed in 5.4+ by a91e83fad6a105318920175208fddc9f2b2d3596
