### ISSUE TITLE
Missing validation in INSERT JSON of simple_date, time, uuid, inet_addr

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla#10115]
Scylla version (or git commit hash): f292d3d679e4f4715c437a976f585a7e3043b20b

When using `INSERT JSON` and inserting values to columns with types represented by `simple_date_type_impl`, `time_type_impl`, `uuid_type_impl`, `inet_addr_type_impl`, you are supposed to specify those values as JSON string values. However, this condition is not validated:

```
cqlsh:ks> CREATE TABLE t(pk int primary key, v uuid);
cqlsh:ks> INSERT INTO t JSON '{"pk": 1, "v": 123.456}';
ServerError: JSON error: condition not met: IsString()
```

The error is not that bad, but it doesn't originate from Scylla code, but from RapidJSON assertion. The error message does not include which value caused the problem, which makes debugging the problem more difficult.

**Comment by nyh** [comment]
Good catch. I believe I don't have a test for this yet in test_json.py (as if there aren't already enough open bugs listed there ;-)).

A small comment: In Alternator, we catch those RapidJSON errors (this "JSON error" here) and wrap them into a syntax error response - so the application knows the problem was an error in the query so it is pointless to retry it (even if the string of the message is not too descriptive), not some sort of internal server error which can be retried.

But you're right that it's even better to print a special error in each case (e.g., here say that "uuid must be a string" or something like that). The generic JSON-error-into-syntax-error thing is just in case we forgot those special error messages.
