### ISSUE TITLE
prepared_statements_cache / loading_cache load vs invalidate race can result in stale prepared statements

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#10117]
loading_cache::get_ptr():

```c++
    template <typename LoadFunc>
    future<value_ptr> get_ptr(const Key& k, LoadFunc&& load) {
        static_assert(std::is_same<future<value_type>, std::result_of_t<LoadFunc(const key_type&)>>::value, "Bad LoadFunc signature");
        // We shouldn't be here if caching is disabled
        assert(caching_enabled());

        return _loading_values.get_or_load(k, [this, load = std::forward<LoadFunc>(load)] (const Key& k) mutable {
            return load(k).then([this] (value_type val) {
                return timestamped_val(std::move(val));
            });
        }).then([this, k] (timestamped_val_ptr ts_val_ptr) {
            // check again since it could have already been inserted and initialized
            if (!ts_val_ptr->ready()) {
                _logger.trace("{}: storing the value for the first time", k);

                if (ts_val_ptr->size() > _max_size) {
                    return make_exception_future<value_ptr>(entry_is_too_big());
                }

                ts_value_lru_entry* new_lru_entry = Alloc().template allocate_object<ts_value_lru_entry>();

                // Remove the least recently used items if map is too big.
                shrink();

                new(new_lru_entry) ts_value_lru_entry(std::move(ts_val_ptr), *this);

                // This will "touch" the entry and add it to the LRU list - we must do this before the shrink() call.
                value_ptr vp(new_lru_entry->timestamped_value_ptr());

                return make_ready_future<value_ptr>(std::move(vp));
            }

            return make_ready_future<value_ptr>(std::move(ts_val_ptr));
        });
    }
```

Notice the lru entry is allocated after the new value is computed.

invalidate:

```c++
    template <typename Pred>
    void remove_if(Pred&& pred) {
        static_assert(std::is_same<bool, std::result_of_t<Pred(const value_type&)>>::value, "Bad Pred signature");

        auto cond_pred = [this, &pred] (const ts_value_lru_entry& v) {
            return pred(v.timestamped_value().value());
        };
        auto value_destroyer = [this] (ts_value_lru_entry* p) {
            loading_cache::destroy_ts_value(p);
        };

        _unprivileged_lru_list.remove_and_dispose_if(cond_pred, value_destroyer);
        _lru_list.remove_and_dispose_if(cond_pred, value_destroyer);
    }
```

We're iterating over the lru entries.

Scenario:

t=0 get_ptr() misses cache, starts computing value using existing state
t=1 value (prepared statement) computed using existing state
t=2 state updated
t=3 cache invalidated (no-op since the item is not in the lru entry)
t=4 value from t=2 is installed in new lru entry, using stale state

**Comment by vladzcloudius** [comment]
Right. We need to be able to wait for completions of all outstanding `get_ptr()` continuations before applying a change to the state and then invalidating the cache. And the last two steps need to be executed under a lock.

**Comment by vladzcloudius** [comment]
Another, probably better, option it to implement a "polling" in a `remove_if()` (and other cache manipulating APIs). This way the caller can simply do:
1) Prevent new requests from being processed (take a lock)
2) Change a schema state
3) Call for cache.remove_if(...)
4) Release a lock from (1).

**Comment by vladzcloudius** [comment]
The interesting part is that all `loading_cache::removeXXX()` APIs are synchronous and loading_cache::get_ptr() is async. 
And the straight forward solution described https://github.com/scylladb/scylla/issues/10117#issuecomment-1047265153 would have to make all `loading_cache::removeXXX()` async.

This would be quite a rework (a lot of lines to touch).

And this brings us back to the original proposal: have a separate async API to "take a lock and wait" for all outstanding `get_ptr()` calls and another to "unlock".

The only place where it should be called is in schema change callbacks.

**Comment by tgrabiec** [comment]
I don't think we have to lock. We only want from invalidate() to make sure that any entries loaded prior to invalidate() will be invalidated. So it's enough to wait for entries which are loaded concurrently with invalidate(). We don't need to prevent new insertions.

utils::phased_barrier can be used for that.

**Comment by avikivity** [comment]
We don't need barriers either. We need remove_if to operate on the main cache map, not the LRU. The main cache map contains an entry for values being established  (see loading_shared_values::get_or_load()), and invalidate could just set a flag there saying the entry was invalidating while being computed. get_or_load() would notice the entry was invalidated, and compute it again.

**Comment by denesb** [comment]
Couldn't this lead to quasi infinite loop? Imagine many invalidations racing with many get_or_load(). An unlucky get_or_load() might fined it was again-and-again invalidated, having to keep retrying. I think the barrier approach is cleaner and fairer.

**Comment by avikivity** [comment]
Barriers are more complicated IMO (making invalidate block). It's true invalidates could starve prepares, but in practice schema changes are rare AND slow, so prepares would quickly win one of the races.

**Comment by tgrabiec** [comment]
> We don't need barriers either. We need remove_if to operate on the main cache map, not the LRU. 

Yes

> It's true invalidates could starve prepares, but in practice schema changes are rare AND slow, so prepares would quickly win one of the races.

This data structure is general-purpose, we probably shouldn't make assumptions like this on this level.

**Comment by vladzcloudius** [comment]
> We don't need barriers either. We need remove_if to operate on the main cache map, not the LRU. The main cache map contains an entry for values being established (see loading_shared_values::get_or_load()), and invalidate could just set a flag there saying the entry was invalidating while being computed. get_or_load() would notice the entry was invalidated, and compute it again.

@avikivity This would require breaking layers of abstractions since "set" (more specifically `boost_intrusive::unordered_set` is an internal structure used by `loading_values` which in line is used by a `loading_cache` and the flag you are willing to set should be set in the internal `loading_value::entry` structure which is not supposed to be visible in any way from the external code. 

Using a phased_barrier or read-write lock is going to be a much cleaner way to tackle this IMO.

> I don't think we have to lock. We only want from invalidate() to make sure that any entries loaded prior to invalidate() will be invalidated. So it's enough to wait for entries which are loaded concurrently with invalidate(). We don't need to prevent new insertions.

@tgrabiec and how you are planning to prevent following races?

1. Invalidate prepared
2. New prepare comes in (uses old schema).
3. Schema changed.

Or if you swap 3 and 1:
1. Schema is changed.
2. Old prepared statement is used.
3. Invalidate.

**Comment by tgrabiec** [comment]
On Tue, Feb 22, 2022 at 11:09 PM Vladislav Zolotarov <
***@***.***> wrote:

> We don't need barriers either. We need remove_if to operate on the main
> cache map, not the LRU. The main cache map contains an entry for values
> being established (see loading_shared_values::get_or_load()), and
> invalidate could just set a flag there saying the entry was invalidating
> while being computed. get_or_load() would notice the entry was invalidated,
> and compute it again.
>
> @avikivity <https://github.com/avikivity> This would require breaking
> layers of abstractions since "set" (more specifically
> boost_intrusive::unordered_set is an internal structure used by
> loading_values which in line is used by a loading_cache and the flag you
> are willing to set should be set in the internal loading_value::entry
> structure which is not supposed to be visible in any way from the external
> code.
>
> Using a phased_barrier or read-write lock is going to be a much cleaner
> way to tackle this IMO.
>
> I don't think we have to lock. We only want from invalidate() to make sure
> that any entries loaded prior to invalidate() will be invalidated. So it's
> enough to wait for entries which are loaded concurrently with invalidate().
> We don't need to prevent new insertions.
>
> @tgrabiec <https://github.com/tgrabiec> and how you are planning to
> prevent following races?
>
>    1. Invalidate prepared
>    2. New prepare comes in (uses old schema).
>    3. Schema changed.
>
> Each schema change must be followed by invalidation, so this scenario is
incomplete. What's the problem here?


>
>
> Or if you swap 3 and 1:
>
>    1. Schema is changed.
>    2. Old prepared statement is used.
>    3. Invalidate.
>
>
What's the problem here? It's not different from:


   1. Old prepared statement is used.
   2. Schema is changed.
   3. Invalidate.

**Comment by vladzcloudius** [comment]
> On Tue, Feb 22, 2022 at 11:09 PM Vladislav Zolotarov < ***@***.***> wrote: We don't need barriers either. We need remove_if to operate on the main cache map, not the LRU. The main cache map contains an entry for values being established (see loading_shared_values::get_or_load()), and invalidate could just set a flag there saying the entry was invalidating while being computed. get_or_load() would notice the entry was invalidated, and compute it again. @avikivity <https://github.com/avikivity> This would require breaking layers of abstractions since "set" (more specifically boost_intrusive::unordered_set is an internal structure used by loading_values which in line is used by a loading_cache and the flag you are willing to set should be set in the internal loading_value::entry structure which is not supposed to be visible in any way from the external code. Using a phased_barrier or read-write lock is going to be a much cleaner way to tackle this IMO. I don't think we have to lock. We only want from invalidate() to make sure that any entries loaded prior to invalidate() will be invalidated. So it's enough to wait for entries which are loaded concurrently with invalidate(). We don't need to prevent new insertions. @tgrabiec <https://github.com/tgrabiec> and how you are planning to prevent following races? 1. Invalidate prepared 2. New prepare comes in (uses old schema). 3. Schema changed. Each schema change must be followed by invalidation, so this scenario is
> incomplete. What's the problem here?
> Or if you swap 3 and 1: 1. Schema is changed. 2. Old prepared statement is used. 3. Invalidate.
> What's the problem here? It's not different from: 1. Old prepared statement is used. 2. Schema is changed. 3. Invalidate. 

@tgrabiec See the enterprise issue referenced above to see a detailed description of what the problem is.

Unless I'm missing something, in gist, the problem is that a prepared statement that is used doesn't match the current (updated) schema. That's why you need a lock.

**Comment by avikivity** [comment]
> > We don't need barriers either. We need remove_if to operate on the main cache map, not the LRU. The main cache map contains an entry for values being established (see loading_shared_values::get_or_load()), and invalidate could just set a flag there saying the entry was invalidating while being computed. get_or_load() would notice the entry was invalidated, and compute it again.
> 
> @avikivity This would require breaking layers of abstraction since "set" (more specifically `boost_intrusive::unordered_set` is an internal structure used by `loading_values` which in line is used by a `loading_cache` and your proposal assumes a certain knowledge of the order in which loading_values calls a `loader` function and inserts the new value into the internal set.
> 

loading_values must establish the lookup entry before calling loader, because it uses the lookup entry as a synchronization point to know whether two concurrent loads are happening on the same key. This is part of its specification.


> This can make some sense IF we would copy the loading_values code into loading_cache code.
> 

loading_shared_values was split in the past from loading_cache. They can be regarded as part of a family.

> However this seems very wrong to me.
> 
> Using a phased_barrier or read-write lock is going to be a much cleaner way to tackle this IMO.
> 

IMO that's overengineered, it doesn't solve a real problem and is quite complicated. Invalidates are rare, and we should make them simple and reliable, and not affect the lookup path.

btw, it is common for cache invalidates to use the lookup table, not the LRU, since it's also common to remove an entry from the LRU while it's being used by users and insert it again when it stops being used, preventing eviction of an item it use.

**Comment by tgrabiec** [comment]
On Wed, Feb 23, 2022 at 2:51 AM Vladislav Zolotarov <
***@***.***> wrote:

> On Tue, Feb 22, 2022 at 11:09 PM Vladislav Zolotarov < *@*.***> wrote: We
> don't need barriers either. We need remove_if to operate on the main cache
> map, not the LRU. The main cache map contains an entry for values being
> established (see loading_shared_values::get_or_load()), and invalidate
> could just set a flag there saying the entry was invalidating while being
> computed. get_or_load() would notice the entry was invalidated, and compute
> it again. @avikivity <https://github.com/avikivity>
> https://github.com/avikivity This would require breaking layers of
> abstractions since "set" (more specifically boost_intrusive::unordered_set
> is an internal structure used by loading_values which in line is used by a
> loading_cache and the flag you are willing to set should be set in the
> internal loading_value::entry structure which is not supposed to be visible
> in any way from the external code. Using a phased_barrier or read-write
> lock is going to be a much cleaner way to tackle this IMO. I don't think we
> have to lock. We only want from invalidate() to make sure that any entries
> loaded prior to invalidate() will be invalidated. So it's enough to wait
> for entries which are loaded concurrently with invalidate(). We don't need
> to prevent new insertions. @tgrabiec <https://github.com/tgrabiec>
> https://github.com/tgrabiec and how you are planning to prevent following
> races? 1. Invalidate prepared 2. New prepare comes in (uses old schema). 3.
> Schema changed. Each schema change must be followed by invalidation, so
> this scenario is
> incomplete. What's the problem here?
> Or if you swap 3 and 1: 1. Schema is changed. 2. Old prepared statement is
> used. 3. Invalidate.
> What's the problem here? It's not different from: 1. Old prepared
> statement is used. 2. Schema is changed. 3. Invalidate.
>
> @tgrabiec <https://github.com/tgrabiec> See the enterprise issue
> referenced above to see a detailed description of what the problem is.
>
> Unless I'm missing something, in gist, the problem is that a prepared
> statement that is used doesn't match the current (updated) schema. That's
> why you need a lock.
>

It's fine to execute prepared statements which use a different schema than
the current schema.
What's problematic is if the driver uses a new schema on its side when
executing an old prepared statement. Adding locking here is not sufficient
to fix this, and not necessary.

**Comment by eliransin** [comment]
> What's problematic is if the driver uses a new schema on its side when
executing an old prepared statement.

@tgrabiec as I said before the driver's schema is not relevant here, the problem is that the driver is using new *prepared statement* on a node/shard where the prepared statement is old.
In addition to the race we have a problem where the only thing that determines the prepared statement ID is the query text, this
results in the ID not being unique. Two different prepared statements (different in the sense that they have been prepared on two different schemas) will end up having the same ID as long as you don't change the text of the query.
I would also like to say that this race can become insignificant if the ID was unique (for example by concatenating the table's version as @avikivity already suggested). If the ID is changed or is approximately unique (hash probability) per schema then the worse that can happen is that some caches will contain prepared statements that are based on old schema which as you said before is perfectly fine.

**Comment by tgrabiec** [comment]
On Wed, Feb 23, 2022 at 1:18 PM Eliran Sinvani ***@***.***>
wrote:

> What's problematic is if the driver uses a new schema on its side when
> executing an old prepared statement.
>
> @tgrabiec <https://github.com/tgrabiec> as I said before the driver's
> schema is not relevant here, the problem is that the driver is using new *prepared
> statement* on a node/shard where the prepared statement is old.
>
Yes, that's what I meant (new prepared statement = new schema).

**Comment by vladzcloudius** [comment]
> loading_values must establish the lookup entry before calling loader, because it uses the lookup entry as a synchronization point to know whether two concurrent loads are happening on the same key. This is part of its specification.

I don't see how you could come to a conclusion that this is a part of it's specialization.
This *could have been* a detail of its implementation but it definitely doesn't have to.

The specification only defines that the value for a given key is going to be populated using a given asynchronous callback if not populated before and if it wasn't evicted since then.

And unless the callback was successful (for any of possibly concurrent get_ptr() calls) the corresponding value won't be available.

How this is achieved is not a matter of a specification.

And what you are talking about is completely related to a specific implementation and, more importantly, not even the loading_cache implementation but rather an implementation of another class *used* by `loading_cache` as I already explained before.

> loading_shared_values was split in the past from loading_cache. They can be regarded as part of a family.

Not true. `loading_shared_values` existed before `loading_values` and `loading_values` used it from a beginning. It was and still is used explicitly in gossiper.hh (see `endpoint_locks_map`).


> IMO that's overengineered, it doesn't solve a real problem and is quite complicated. Invalidates are rare, and we should make them simple and reliable, and not affect the lookup path.

How wouldn't it solve a "real problem"? What do I (and Tomek) miss?

> btw, it is common for cache invalidates to use the lookup table, not the LRU, since it's also common to remove an entry from the LRU while it's being used by users and insert it again when it stops being used, preventing eviction of an item it use.

I don't see how this is relevant to the current discussion. You welcome to create a separate GH issue with a new API proposal and we can discuss it there.

**Comment by vladzcloudius** [comment]
> > What's problematic is if the driver uses a new schema on its side when
> > executing an old prepared statement.
> 
> @tgrabiec as I said before the driver's schema is not relevant here, the problem is that the driver is using new **prepared statement** (not schema) on a node/shard where the prepared statement is old. In addition to the race we have a problem where the only thing that determines the prepared statement ID is the query text, this results in the ID not being unique. Two different prepared statements (different in the sense that they have been prepared on two different schemas) will end up having the same ID as long as you don't change the text of the query. I would also like to say that this race can become insignificant if the ID was unique (for example by concatenating the table's version as @avikivity already suggested). If the ID is changed or is approximately unique (hash probability) per schema then the worse that can happen is that some caches will contain prepared statements that are based on old schema which as you said before is perfectly fine. If we do this the race will stay but I am pretty convinced that it will become insignificant.

This is a much simpler but I don't see how hashing a schema into a prepared statement ID is going to solve anything.

We need to store the schema version in the prepared statement object and verify it during the execution against the current schema version.

If we don't do that then one can execute the prepared statement generated for an old schema against the new schema due to a race described here or due to some other race you seem to refer - and this is regardless of the ID value. We don't calculate the ID every time we execute - the driver sends a prepared statement ID and a list of parameters and then DB fetches the prepared statement object for that ID and executes it by feeding it the provided parameters values.

Having a schema version hashed into the prepared statement ID won't help to resolve the race. Checking the actual schema version to a current schema DURING the execution - will.

In general the fact that we prepared statements prepared against different schema have the same hash should not be a problem as long as statements are properly invalidated during a schema change. However this race shows that there is a possibility for a race and I think it should be solved regardless whether we will or will not add the check for a schema version during the execution.

However only adding the schema version check IS going to be enough to resolve any possible races in the prepared_statement execution flow.

@eliransin @tgrabiec

**Comment by tgrabiec** [comment]
On Thu, Feb 24, 2022 at 9:12 PM Vladislav Zolotarov <
***@***.***> wrote:

> What's problematic is if the driver uses a new schema on its side when
> executing an old prepared statement.
>
> @tgrabiec <https://github.com/tgrabiec> as I said before the driver's
> schema is not relevant here, the problem is that the driver is using new *prepared
> statement* (not schema) on a node/shard where the prepared statement is
> old. In addition to the race we have a problem where the only thing that
> determines the prepared statement ID is the query text, this results in the
> ID not being unique. Two different prepared statements (different in the
> sense that they have been prepared on two different schemas) will end up
> having the same ID as long as you don't change the text of the query. I
> would also like to say that this race can become insignificant if the ID
> was unique (for example by concatenating the table's version as @avikivity
> <https://github.com/avikivity> already suggested). If the ID is changed
> or is approximately unique (hash probability) per schema then the worse
> that can happen is that some caches will contain prepared statements that
> are based on old schema which as you said before is perfectly fine. If we
> do this the race will stay but I am pretty convinced that it will become
> insignificant.
>
> This is a much simpler but I don't see how hashing a schema into a
> prepared statement ID is going to solve anything.
>
> We need to store the schema version in the prepared statement object and
> verify it during the execution against the current schema version.
>
> If we don't do that then one can execute the prepared statement generated
> for an old schema against the new schema due to a race described here or
> due to some other race you seem to refer - and this is regardless of the ID
> value. We don't calculate the ID every time we execute - the driver sends a
> prepared statement ID and a list of parameters and then DB fetches the
> prepared statement object for that ID and executes it by feeding it the
> provided parameters values.
>

It's ok to execute a prepared statement generated for an old schema against
the new schema. Replicas can take mutations which use older schema, and can
handle read requests which request older schema (the read will return
mutations conforming to the old schema).

**Comment by vladzcloudius** [comment]
> It's ok to execute a prepared statement generated for an old schema against
the new schema. Replicas can take mutations which use older schema, and can
handle read requests which request older schema (the read will return
mutations conforming to the old schema).

But we don't this to continue for long, don't we? And we need a way to overcome a race described here.
So, one way to solve this is to actually avoid this using any of approaches proposed so far by me, you and Avi earlier.
However another option is to accept that the race is possible and add a protection as I suggested in my last post. The moment we detect that we are attempting to execute a prepared statement generated for an older schema we can evict it from the prepared statement on a spot and return an error we return when a prepared statement for a given key is not available and re-prepare is required (e.g. this is going to happen when schema is changed today).

I think that the later approach is both simpler and cleaner.

**Comment by avikivity** [comment]
> > loading_values must establish the lookup entry before calling loader, because it uses the lookup entry as a synchronization point to know whether two concurrent loads are happening on the same key. This is part of its specification.
> 
> @avikivity I don't see how you could come to a conclusion that this is a part of it's specialization. This _could have been_ a detail of its implementation but it definitely doesn't have to.

commit ec3fed5c4dd281f610c63709b35c37ff518eafdc
Author: Vlad Zolotarov <vladz@scylladb.com>
Date:   Mon Jul 10 14:36:05 2017 -0400

    utils: introduce loading_shared_values
    
    This class implements an key-value container that is populated
    using the provided asynchronous callback.
    
    The value is loaded when there are active references to the value for the given key.
    
    Container ensures that only one entry is loaded per key at any given time.
    


> 
> The specification only defines that the value for a given key is going to be populated using a given asynchronous callback if not populated before and if it wasn't evicted since then.

No, it explicitly calls out that loads on a particular key are not concurrrent.

> 
> And unless the callback was successful (for any of possibly concurrent get_ptr() calls) the corresponding value won't be available.
> 
> How this is achieved is not a matter of a specification.
> 
> And since `get_ptr()` is an asynchronous call it provides no promise whatsoever as to a particular point when `loader` callback is going to be called or complete relatively to other external events that can happen since it's called and till the returned future resolves, e.g. a schema change.
> 
> This is definitely beyond the scope of a container's specification.
> 
> And what you are talking about is completely related to a specific implementation and, more importantly, not even the loading_cache implementation but rather an implementation of another class _used_ by `loading_cache` as I already explained before.
> 
> You should also keep in mind that `loading_cache` is used in many other places in addition to `prepared_cache` so I don't think it makes sense to change a generic container while we have a race at caller site.
> 

The race is in loading_cache. Its invalidate method is not safe if a load is in progress.

<snip>

**Comment by vladzcloudius** [comment]
> No, it explicitly calls out that loads on a particular key are not concurrrent.

That's true but how this is achieved - that's a matter of an internal implementation. It could have been a lock for instance.

> The race is in loading_cache. Its invalidate method is not safe if a load is in progress.

It is absolutely safe and doesn't break any specification.
The entry can not be thought to be *in* the cache till the future returned from get_ptr() resolves.
And remove_if removes every entry which *is in the cache* by the time it's called.

It's the responsibility of a caller to make sure there are no in-progress get_ptr() requests when `remove_if` is called if it's important to resolve this race.

**Comment by tgrabiec** [comment]
_loading_values will keep the entry present and alive as long as there is any value_ptr returned by loading_cache::get_ptr() alive. remove_if() only removes the value_ptr held by the LRU, which will remove it from _loading_values only if there are no other users. So if there is constant use of the prepared statement, it will stay forever in the cache even if we don't hit the race mentioned in the introduction.

If this is true, then adding a barrier is not enough. I think we should do Avi's proposal to detach entries from _loading_values. 
Locking above loading_values seems like a worse idea, because it would stall user requests.

**Comment by vladzcloudius** [comment]
> _loading_values will keep the entry present and alive as long as there is any value_ptr returned by loading_cache::get_ptr() alive. remove_if() only removes the value_ptr held by the LRU, which will remove it from _loading_values only if there are no other users. 

Incorrect. The statement is going to be destroyed the moment the last currently help reference is released, which will happen the moment the lust currently executed CQL statement that uses this statement object completes.

Look at the ~lru_entry().
It releases the "anchor".


> So if there is constant use of the prepared statement, it will stay forever in the cache even if we don't hit the race mentioned in the introduction.

No, it won't see above.

**Comment by vladzcloudius** [comment]
Oh, I think I see the scenario, @tgrabiec. Meaning there is a `get` while there are active references.

> If this is true, then adding a barrier is not enough. I think we should do Avi's proposal to detach entries from _loading_values.
> Locking above loading_values seems like a worse idea, because it would stall user requests.

How about my idea of storing and checking the schema version during EXECUTE?

**Comment by vladzcloudius** [comment]
To address the race you described, @tgrabiec we can expose a "remove" call for `loading_shared_values` that would remove the entry from the hash table (_set). 
And then add a call: 
```
bool loading_shared_values::is_linked(entry_ptr) {
if (!entry_ptr) { return false; }
return entry_ptr->is_linked();
}
```

And then `get_ptr()` can call it in the continuation of get_or_load(...) before inserting it into the LRU.

**Comment by avikivity** [comment]
> > No, it explicitly calls out that loads on a particular key are not concurrrent.
> 
> That's true but how this is achieved - that's a matter of an internal implementation. It could have been a lock for instance.

It's true that mutual exclusion on all keys could achieve it too. But if we avoid splitting hairs and acknowledge that the goal of the thing is to allow concurrency on distinct keys, but serialize on the same keys, then it's established that we must have a lock per key (or a lock per hash(key) if we're okay with being inaccurate).

And in any case, it does establish the entry for the key before loading begins. So we should at least consider using that if it simplifies the solution (which it does).

And again, that's how most caches that I'm familiar with operate, they invalidate by operating on the lookup table not the LRU.



> 
> > The race is in loading_cache. Its invalidate method is not safe if a load is in progress.
> 
> It is absolutely safe and doesn't break any specification. The entry can not be thought to be _in_ the cache till the future returned from get_ptr() resolves. And remove_if removes every entry which _is in the cache_ by the time it's called.

The combination of the two means it's unsafe, without additional changes. We now have a bug. Can we agree on that?

If we do, we need to consider how to fix the bug. One option is to add more locking. Another option is to reuse the locking system already in place. I think the latter is simpler.

> 
> It's the responsibility of a caller to make sure there are no in-progress get_ptr() requests when `remove_if` is called if it's important to resolve this race.

That's a good way to make sure the bug proliferates. Caches should self-synchronize their invalidate and lookup methods, rather than requiring every caller to provide this locking. And every caller that uses invalidation will need that synchronization.

**Comment by vladzcloudius** [comment]
> That's a good way to make sure the bug proliferates. Caches should self-synchronize their invalidate and lookup methods, rather than requiring every caller to provide this locking. And every caller that uses invalidation will need that synchronization.

@avikivity Please, see my last proposal here: https://github.com/scylladb/scylla/issues/10117#issuecomment-1051097056

It addresses both the race reported by Tomek (which is a much more likely than the one you've described BTW) and, accidentally, the one you reported.
And it also allows to keep APIs abstract and not break any abstraction. 

We agree that we have a bug (we can think of different things when we say it though).
If we implement my proposal all "arguing parties" should be satisfied. So, let's just do it.

I saw @tgrabiec self-assigned himself to this. So, I assume he's on it.
Otherwise I can write these 4 lines myself and send a PR.

@tgrabiec Please, let me know where it stands?

**Comment by tgrabiec** [comment]
@vladzcloudius I'm on it. The fix is more complicated than these four lines though.

**Comment by eliransin** [comment]
> The execution goes as follows: the driver sends a prepared statement ID and a list of parameters values and then DB fetches the prepared statement object from the prepared statements cache for that ID and executes it by feeding it the provided parameters values.
> 
> Therefore having a schema version hashed into the prepared statement ID won't help to resolve the race. Checking the actual schema version used when the statement has been prepared to a current schema DURING the execution - will.

@vladzcloudius just for completeness, here is why mixing the schema into the hash can solve or at least mitigate the problem. 
Hashing the schema into the prepared statement ID will prevent a driver to send "unknown" / unexpected parameters to a still 
not caught up node (generating the "Too many fields" error).
Lets start by assuming the race have happened, therefore there are some nodes/shards that contains prepared statements
that uses old schema, however, those prepared statements has the exact same ID as before. So when the driver executes the
prepared statement, it is found but it is not the same prepared statement the driver prepared (against a different, newer 
schema).The node with the old prepared statement is surprised to find out that it has an extra field that it doesn't recognize.
A similar thing can happen in the client side, again, consider "SELECT * FROM XXX;" when the schema changes, the prepared
statement is invalidated but gets the same ID even though the returned set can change, now you have two groups of clients, 
the ones that noticed the invalidation and the ones that didn't since another client re-prepared the statement and it got the 
exact same ID, now a client with the old ID runs the query and is surprised to find out that there is an extra column in the set, 
moreover, the order of field could have changed since regular columns are ordered in an lexicographic order so even if the 
client side driver chooses to drop the extra field it can end up presenting wrong results (this issue is known 
and handled in Cassandra already - https://issues.apache.org/jira/browse/CASSANDRA-10786

So the case of two many fields is similar in that sense, they both stem from the wrong assumption that textually identical 
queries, are semantically identical and this leads to the assumption that using the text as an ID distinguishes semantically 
different queries.
The main difference here from a classic CPU cache is that the key is assumed to capture the uniqueness of the entry (or at 
least with a neglected probability of a clash) while in other caches you need as you said to validate that the entry is indeed
what you think (by comparing the last address bits that are not part of the key and are saved in the entry). Here the culprit is 
that you can't know what is the prepared statement from the id, when receiving the cache key from the client software you don't 
have any extra information to go on so you don't know when did this client prepared this statement or in other words what is the semantic meaning of the query that the client holds. Mixing the schema version into the hash will do the trick because text+schema_version does make a semantically unique query.

Here are possible cases (assuming we do mix the hash into the ID), new ID - after invalidation old ID - before invalidation:
1. A client with a new ID runs against a node with an old id - OK, the client will re-prepare the statement and will get depending on the case:
 a. if it is a race (which is what this issue is about) it will get the new ID and the node will now know also the "new" prepared statement.
 b. if it is the common transition time (the node still haven't caught up with the new shcema) it will get the old ID and will execute
 it and get correct results.
2. A client with a new ID runs against a node with new ID  - All is OK as before.
3. A client with an old ID runs against a node with a new ID - the node will re-prepare the statement and run it and all is OK as before.
4. a client with an old ID runs against a node with the old ID  - All is OK as before.
5. This is unique to having both the race condition and the schema in the ID, a node with either ID running agains a node that has both of the IDs in the cache:
 a. If it is a client with an old ID it is OK because running queries with old schema against nodes with new schema is OK.
 b. If it is a client with a new ID it is OK because this is the current node's schema.

Then the only bad event is when all nodes experience the race condition, in any other situation, the clients will eventually 
converge and the cache also since the LRU table will eventually evict the old prepared statement (cache entry expiry period after the clients converge).

**Comment by vladzcloudius** [comment]
On 3/6/22 3:48 AM, Eliran Sinvani wrote:
>
>     The execution goes as follows: the driver sends a prepared
>     statement ID and a list of parameters values and then DB fetches
>     the prepared statement object from the prepared statements cache
>     for that ID and executes it by feeding it the provided parameters
>     values.
>
>     Therefore having a schema version hashed into the prepared
>     statement ID won't help to resolve the race. Checking the actual
>     schema version used when the statement has been prepared to a
>     current schema DURING the execution - will.
>
> @vladzcloudius <https://github.com/vladzcloudius> just for 
> completeness, here is why mixing the schema into the hash can solve or 
> at least mitigate the problem.
> Hashing the schema into the prepared statement ID will prevent a 
> driver to send "unknown" / unexpected parameters to a still
> not caught up node (generating the "Too many fields" error).
> Lets start by assuming the race have happened, therefore there are 
> some nodes/shards that contains prepared statements
> that uses old schema, however, those prepared statements has the exact 
> same ID as before. So when the driver executes the
> prepared statement, it is found but it is not the same prepared 
> statement the driver prepared (against a different, newer
> schema).The node with the old prepared statement is surprised to find 
> out that it has an extra field that it doesn't recognize.
> A similar thing can happen in the client side, again, consider "SELECT 
> * FROM XXX;" when the schema changes, the prepared
> statement is invalidated but gets the same ID even though the returned 
> set can change, now you have two groups of clients,
> the ones that noticed the invalidation and the ones that didn't since 
> another client re-prepared the statement and it got the
> exact same ID, now a client with the old ID runs the query and is 
> surprised to find out that there is an extra column in the set,
> moreover, the order of field could have changed since regular columns 
> are ordered in an lexicographic order so even if the
> client side driver chooses to drop the extra field it can end up 
> presenting wrong results (this issue is known
> and handled in Cassandra already - 
> https://issues.apache.org/jira/browse/CASSANDRA-10786
>

The issue above is about a client side metadata that needs to be updated 
and indeed hashing the schema version would be an easy solution.
We should definitely look at it, however encoding a schema into a 
prepared statement ID is dangerous until we completely avoid schema 
getting out of sync situations.
Other than that encoding a schema into an ID should solve races you have 
described.
See more on this below.


I was referring the situation when the prepared statement was not 
updated/invalidated on a Scylla (!!) side at all (due to all kinds of 
races we were discussing).
Meaning that the currently cached prepared statement was prepared 
against the old schema while the schema has been updated since then.
And the client doesn't know that there schema has been updated and/or 
there is anything wrong with the prepared statement which ID it has.

In this case just hashing a schema is not going to help us much as I've 
explained earlier.

> So the case of two many fields is similar in that sense, they both 
> stem from the wrong assumption that textually identical
> queries, are semantically identical and this leads to the assumption 
> that using the text as an ID distinguishes semantically
> different queries.
> The main difference here from a classic CPU cache is that the key is 
> assumed to capture the uniqueness of the entry (or at
> least with a neglected probability of a clash) while in other caches 
> you need as you said to validate that the entry is indeed
> what you think (by comparing the last address bits that are not part 
> of the key and are saved in the entry). Here the culprit is
> that you can't know what is the prepared statement from the id, when 
> receiving the cache key from the client software you don't
> have any extra information to go on so you don't know when did this 
> client prepared this statement or in other words what is the semantic 
> meaning of the query that the client holds. Mixing the schema version 
> into the hash will do the trick because text+schema_version does make 
> a semantically unique query.
>
> Here are possible cases (assuming we do mix the hash into the ID), new 
> ID - after invalidation old ID - before invalidation:
>
>  1. A client with a new ID runs against a node with an old id - OK,
>     the client will re-prepare the statement and will get depending on
>     the case:
>     a. if it is a race (which is what this issue is about) it will get
>     the new ID and the node will now know also the "new" prepared
>     statement.
>
>  1. b. if it is the common transition time (the node still haven't
>     caught up with the new shcema) it will get the old ID and will execute
>     it and get correct results.
>

AFAIKT if some of the nodes haven't caught up with the new schema then 
this will create an endless (till all nodes catch up with the new 
schema) loop of invalidating and re-preparing the statement depending on 
which node the PREPARE statement lands - with old or with the new schema.

>  1. A client with a new ID runs against a node with new ID - All is OK
>     as before.
>  2. A client with an old ID runs against a node with a new ID - the
>     node will re-prepare the statement and run it and all is OK as before.
>  3. a client with an old ID runs against a node with the old ID - All
>     is OK as before.
>  4. This is unique to having both the race condition and the schema in
>     the ID, a node with either ID running agains a node that has both
>     of the IDs in the cache:
>     a. If it is a client with an old ID it is OK because running
>     queries with old schema against nodes with new schema is OK.
>     b. If it is a client with a new ID it is OK because this is the
>     current node's schema.
>
> Then the only bad event is when all nodes experience the race 
> condition, in any other situation, the clients will eventually
> converge and the cache also since the LRU table will eventually evict 
> the old prepared statement (cache entry expiry period after the 
> clients converge).
>

...or if scylla would not invalidate old prepared statements for 
whatever reason.

**Comment by slivne** [comment]
@avikivity backport ping

**Comment by avikivity** [comment]
Backported to 4.5, 4.6, 5.0.
