### ISSUE TITLE
Alternator: New features we need

### ISSUE THREAD

**Issue by pyuriy** [scylladb/scylla#10202]
Hello Scylla team!

Please advice if you have any plans to add the following feature? 
It is critical for our application to migrate from AWS DynamoDB to Scylla.

1. DynamoDB’s TTL (per-item expiration)
2. Multi-item transaction feature (TransactWriteItems, TransactGetItems)
3. The ScanIndexForward=false of the Query operation - to read a partition in reverse order - is currently implemented inefficiently 

Thanks,
Yuriy.

**Comment by tzach** [comment]
Mapping this to existing alternator issues:

- [ ] TTL #5060
- [ ] Transactions #5064
- [ ] ScanIndexForward=false #7586

**Comment by nyh** [comment]
Hi Yuriy,

For `ScanIndexForward=false` - this feature is completely done (see issue #7586). However again, since this is relatively new fix, you won't find it on old versions. If you want to know if the fix was backported to a specific version you want to use, please ask on #7586.

For TTL (#5060), we actually already have working - but experimental - code. The [compatibility.md](https://github.com/scylladb/scylla/blob/master/docs/alternator/compatibility.md#unimplemented-api-features) explains the current status of this feature (and a few other unimplemented features), and how to enable the experimental support. Note that to enable the experimental TTL code you should use a nightly image of Scylla - not an old release which won't have this code.

The Transactions feature (#5064) is still unimplemented and is not likely to be implemented in the near future because the underlying Scylla database doesn't support multi-item transactions.

Anyway, I'll close this issue. Feel free to add comments on specific issues on their own issue pages linked above, or discuss Alternator in general on the scylladb-dev mailing list on googlegroups. Good luck!
