### ISSUE TITLE
Scylla-CI: adjust pull_github_pr script to check tests status

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla#10263]
The `pull_github_pr.sh` script used for merging PRs should be adjusted to take tests status into account before merging

We can use something like:
```bash
# Check PR tests status
PR_HEAD_SHA=$(jq -r .head.sha <<< $PR_DATA)
PR_TESTS_STATUS=$(curl -s "https://api.github.com/repos/$PROJECT/commits/$PR_HEAD_SHA/status" | jq -r .state)
if [ "$PR_TESTS_STATUS" != "success" ]; then
  echo "Some of the tests that ran for PR $PR_NUM were not completed successfully," \
        "please make sure all tests are done successfully before merge this PR."
  exit 1
fi
```
As described on github commit API docs [0], the `state` field will return success only if the latest status for all contexts is success,

/cc @avikivity @slivne

[0] https://docs.github.com/en/rest/reference/commits#get-the-combined-status-for-a-specific-reference

**Comment by nyh** [comment]
Personally, I'm not yet comfortable enough with the new CI workflow and its (lack of) speed for making it **mandatory** for merging a PR. As an extreme example, if someone sent a documentation-only patch, why should it be necessary to wait many hours for the testing to complete? Also, I sometimes use pull_github_pr to test out the branch myself. I may want to do that even if the CI tests haven't completed yet - or even if they outright failed.

It seems to me that pull_github_pr can simply **warn** me that the tests didn't pass, instead of making it into an error that aborts the process in the middle. It can do everything exactly as it did in the past (including the merge), and just end with a warning. The maintainer will simply avoid the "git push" that they normally do at that point.
