### ISSUE TITLE
Couldn't install Scylla 0.17 && 0.19 on Ubuntu 14.04 baremetal

### ISSUE THREAD

**Issue by s905060** [scylladb/scylla#1028]
`$ sudo apt-get install scylla-server -y`

start: Job failed to start
invoke-rc.d: initscript scylla-server, action "start" failed.
dpkg: error processing package scylla-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up libhwloc-plugins (1.8-1ubuntu1.14.04.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Errors were encountered while processing:
 scylla-server
E: Sub-process /usr/bin/dpkg returned an error code (1)

`$sudo dpkg --configure -a`

Setting up scylla-server (0.17-20160207.b2eb081-ubuntu1) ...
start: Job failed to start
invoke-rc.d: initscript scylla-server, action "start" failed.
dpkg: error processing package scylla-server (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of scylla-jmx:
 scylla-jmx depends on scylla-server; however:
  Package scylla-server is not configured yet.

dpkg: error processing package scylla-jmx (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of scylla-tools:
 scylla-tools depends on scylla-server; however:
  Package scylla-server is not configured yet.

dpkg: error processing package scylla-tools (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 scylla-server
 scylla-jmx
 scylla-tool

--------------------------------------------------------

Package: scylla-jmx
Version: 0.17-20160207.02991cf-ubuntu1

Package: scylla-server
Version: 0.17-20160207.b2eb081-ubuntu1

Package: scylla-tools
Version: 0.17-20160207.f50f2f6-ubuntu1

Baremetal: Ubuntu14.04
Kernel: 3.16.0-37-generic

--------------------------------------------------------

**Comment by tzach** [comment]
@s905060 in reason you are not using the latest version (0.19)?

**Comment by s905060** [comment]
I only found 0.17 in our internal-repo. So I did the following experiment but still no luck.

**Same issues on version 0.19**
`sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla.list`
`sudo apt-get update`
`sudo apt-get install scylla-server scylla-jmx scylla-tools`

Setting up scylla-server (0.19-20160308.4e3b98f-ubuntu1) ...
start: Job failed to start
invoke-rc.d: initscript scylla-server, action "start" failed.
dpkg: error processing package scylla-server (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of scylla-jmx:
 scylla-jmx depends on scylla-server; however:
  Package scylla-server is not configured yet.

dpkg: error processing package scylla-jmx (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of scylla-tools:
 scylla-tools depends on scylla-server; however:
  Package scylla-server is not configured yet.

dpkg: error processing package scylla-tools (--configure):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libnss3-nssdb (2:3.17.4-0ubuntu0.14.04.1) ...
Setting up libnss3:amd64 (2:3.17.4-0ubuntu0.14.04.1) ...
No apport report written because the error message indicates its a followup error from a previous failure. No apport report written because the error message indicates its a followup error from a previous failure.

-------------------------------------------------------------

Errors were encountered while processing:
 scylla-server
 scylla-jmx
 scylla-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by s905060** [comment]
Found errors `sudo: no tty present and no askpass program specified`  in `/var/log/upstart/scylla-server.log`

The scylla-server has finally been installed once I added `scylla ALL=(ALL) NOPASSWD: ALL` in `/etc/sudoers`

Any suggestions?

**Comment by tzach** [comment]
Failed to reproduce this install issue on EC2, with instances r3.xlarge, m3.xlarge
The following works for me:
```
sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla.list
sudo apt-get update
sudo apt-get install scylla-server scylla-jmx scylla-tools
```
Ubuntu 14.04.2 LTS.

@s905060 can you please share your `lsb_release -a`  and `uname -r` ?

**Comment by s905060** [comment]
FYI.

TEST ENV 1
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

$ uname -r
3.16.0-37-generic

------------------------

TEST ENV 2
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

$ uname -r
3.13.0-44-generic

**Comment by tzach** [comment]
@s905060 same as what I have, so the cause is elsewhere

**Comment by s905060** [comment]
I have found some other users have the same issues:
https://groups.google.com/forum/#!msg/scylladb-users/Im_OV6RFw3E/khmjh8XbBAAJ

**Comment by nyh** [comment]
On Sun, Mar 13, 2016 at 2:05 PM, Tzach Livyatan <notifications@github.com>
wrote:

> Failed to reproduce this install issue on EC2, with instances r3.xlarge,
> m3.xlarge
> The following works for me:
>
> sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla.list
> sudo apt-get update
> sudo apt-get install scylla-server scylla-jmx scylla-tools
>
> It  seems we are running "sudo /usr/lib/scylla/scylla_prepare" in
dist/ubuntu/debian/scylla-server.upstart.
But the same file specifies "setuid scylla", meaning that this script will
try to run "sudo" as the user "scylla".

Depending on the machine's setup on who can run "sudo" and how, this may
NOT work: For example, many installations require users to type in their
own password when using "sudo", even when allowed to use "sudo". The
message the original poster mentioned says that "sudo" tried to ask the
user for the password, but couldn't, because the script didn't have an
attached terminal (it was running during boot).

Apparently, not being able to run pre-run script as root and the script
itself as root is a known upstart deficiency: The following page describes
an alternative solution, of not using the "setuid" upstart parameter, and
instead use an external program to downgrade the permissions:

http://superuser.com/questions/722215/upstart-run-service-as-unprivileged-user-and-pre-start-script-as-root

The specific tool he recommends ("setuidgid") is not anything I heard of,
but I think you can just use the normal "su" for that?

P.S. Here is an idea which could be a working, but *wrong* way to fix this
bug:
Our installation could include a configuration file in /etc/sudoers.d to
allow the "scylla" user to always use sudo without a password, regardless
of the default sudo configuration.
Doing this is wrong (and so is using "sudo" in our script, by the way) -
look back as to why we have this "scylla" user in the first place - it's
supposedly a security feature for not giving the program root permissions.
But if we then go and give the "scylla" user the permission to freely run
"sudo", we nullify any security advantages! (maybe "any" is a bit strong
here, but we nullify most security advantages).

Ubuntu 14.04.2 LTS.

**Comment by nyh** [comment]
On Sun, Mar 13, 2016 at 2:58 PM, Nadav Har'El <nyh@scylladb.com> wrote:

>
> On Sun, Mar 13, 2016 at 2:05 PM, Tzach Livyatan <notifications@github.com>
> wrote:
>
> P.S. Here is an idea which could be a working, but *wrong* way to fix this
> bug:
> Our installation could include a configuration file in /etc/sudoers.d to
> allow the "scylla" user to always use sudo without a password, regardless
> of the default sudo configuration.
> Doing this is wrong (and so is using "sudo" in our script, by the way) -
> look back as to why we have this "scylla" user in the first place - it's
> supposedly a security feature for not giving the program root permissions.
> But if we then go and give the "scylla" user the permission to freely run
> "sudo", we nullify any security advantages! (maybe "any" is a bit strong
> here, but we nullify most security advantages).
>

After I wrote the above, I noticed this commit:

https://github.com/scylladb/scylla/commit/6ae41a71c9d1c7c8f206d8f8cbb4ec7cd85abe83
<https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fscylladb%2Fscylla%2Fcommit%2F6ae41a71c9d1c7c8f206d8f8cbb4ec7cd85abe83&sa=D&sntz=1&usg=AFQjCNHN6KUc-dAX22mIhqrNImRKHaTvWw>

So apparently, we do have exactly that fix I didn't like (a file in
/etc/sudoers.d/...) but made it less a security hole by allowing running
specific scripts only (I'm still worried about the security implications of
this, by the way).

So this bug has actually been fixed already, and this issue can be closed?

**Comment by tzach** [comment]
> So this bug has actually been fixed already, and this issue can be closed?

@nyh The commit you pointed to is part of 0.19, but @s905060 report the issue still exist in this version

**Comment by s905060** [comment]
I am able to see `scylla ALL=(ALL) NOPASSWD:SETENV: /usr/lib/scylla/scylla_prepare,/usr/lib/scylla/scylla_stop,/usr/lib/scylla/scylla_io_setup` in `/etc/sudoers.d/scylla`, however, the installation is still failed.

I did another try with official 0.19 on fresh VM:

After this operation, 0 B of additional disk space will be used.
Setting up scylla-server (0.19-20160308.4e3b98f-ubuntu1) ...
start: Job failed to start
invoke-rc.d: initscript scylla-server, action "start" failed.
dpkg: error processing package scylla-server (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of scylla-jmx:
 scylla-jmx depends on scylla-server; however:
  Package scylla-server is not configured yet.

dpkg: error processing package scylla-jmx (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of scylla-tools:
 scylla-tools depends on scylla-server; however:
  Package scylla-server is not configured yet.

dpkg: error processing package scylla-tools (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
Errors were encountered while processing:
 scylla-server
 scylla-jmx
 scylla-tools

**Comment by s905060** [comment]
It turns out that our `/etc/sudoers` does not have `#includedir /etc/sudoers.d` inside. Once I added this into `/etc/sudoers` everything works as expected.

**Comment by syuu1228** [comment]
This looks like caused by https://github.com/scylladb/scylla/issues/1017, because package installation is aborted by "invoke-rc.d: initscript scylla-server, action "start" failed.".
It may cause when you are not using XFS rootfs and haven't setup RAID partition for /var/lib/scylla, etc.
There are number of reason scylla failing startup, and we require configuration to prepare running it, but Ubuntu package manager launch scylla unconditionally before we complete configuration, and aborts package installation.

**Comment by nyh** [comment]
On Sun, Mar 13, 2016 at 11:10 PM, Cheng-Hsiu (Jash) Lee <
notifications@github.com> wrote:

> I am able to see scylla ALL=(ALL) NOPASSWD:SETENV:
> /usr/lib/scylla/scylla_prepare,/usr/lib/scylla/scylla_stop,/usr/lib/scylla/scylla_io_setup
> in /etc/sudoers.d/scylla, however, the installation is still failed.
>
With great power, comes great responsibility. With use of "sudo", come
great security holes. Especially if used incorrectly.

In particular, what was the thinking behind adding the "SETENV" option
above?
Let's walk through *one concrete security hole*, which will let anyone
breaking into the "scylla" account escalate permissions to root:

"/usr/lib/scylla/scylla_stop" is a shell script, which uses the command
"ip" without a full path.
Now, an attacker who broke into the "scylla" user can create a script
"/tmp/ip" which does anything he wants, and then run:
     /usr/bin/sudo PATH=/tmp /usr/lib/scylla/scylla_stop
This will be allowed, because of the sudoers which allows running
scylla_stop without a password, and allows setting any environment
including PATH. Now, when scylla_stop runs "ip" it will find "/tmp/ip" and
run it, with superuser permissions!

An easy fix for this specific hole is to drop the "SETENV" option, and then
if the attacker will run the above command he will get (with sudo's default
security options)
 sudo: sorry, you are not allowed to set the following environment
variables: PATH

But I'm still worried about what other holes sudo might open. Better not to
use it at all, and use another method like I described in a previous mail.

**Comment by syuu1228** [comment]
@nyh SETENV was for /usr/bin/sudo -E on https://github.com/scylladb/scylla/blob/master/dist/redhat/systemd/scylla-server.service#L16.
Without this scylla_prepare and scylla_stop won't work because it's depends on EnvironmentFile variables passed through environment variables, but we still can do ". /etc/sysconfig/scylla-server" in the script instead of using environment variables.

And why we have to sudo from scylla is, initially the script was able to run without sudo because uid was root at that time, but we changed User=scylla on systemd unit file, then we need to get root permission on ExecStartPre and ExecStopPost.

ExecStartPre may able to implement as separated systemd unit, ExecStopPost can be dropped for a while since our systemd unit file already broke dpdk support, and scylla_stop doesn't need for posix stack. (As I mentioned before, DPDK supported systemd unit should provide separately, something like 'scylla-server-dpdk.service')
In that way we can drop sudoers.d/scylla completely.

**Comment by nyh** [comment]
On Mon, Mar 14, 2016 at 12:19 PM, Takuya ASADA <notifications@github.com>
wrote:

> @nyh <https://github.com/nyh> SETENV was for /usr/bin/sudo -E on
> https://github.com/scylladb/scylla/blob/master/dist/redhat/systemd/scylla-server.service#L16
> .
> Without this scylla_prepare and scylla_stop won't work because it's
> depends on EnvironmentFile variables passed through environment variables,
> but we still can do ". /etc/sysconfig/scylla-server" in the script instead
> of using environment variables.
>

I see, but this "SETENV" setting is still a security faux-pas (the
sudoers(5) manuals says "only trusted users should be allowed to set
variables in this manner."). If you want to pass *certain* environment
variables, there is also a way to do that (I think "env_check", but I don't
remember the details) and you don't need to allow all the variables
including PATH.

The exploit I shared in my previous mail (maybe I shouldn't have done this
;-)) mostly negates the security advantage of the separate "scylla" user,
so I think this situation needs to be solved.

And why we have to sudo from scylla is, initially the script was able to
> run without sudo because uid was root at that time, but we changed
> User=scylla on systemd unit file, then we need to get root permission on
> ExecStartPre and ExecStopPost.
>

Yes, although there may be are other ways to do this without "sudo".
One suggestion I saw in a website I linked to in an earlier comment was to
keep the uid=root, but on the "exec" line, use "su scylla ..." to run the
scylla server under the "scylla" user.


> ExecStartPre may able to implement as separated systemd unit, ExecStopPost
> can be dropped for a while since our systemd unit file already broke dpdk
> support, and scylla_stop doesn't need for posix stack. (As I mentioned
> before, DPDK supported systemd unit should provide separately, something
> like 'scylla-server-dpdk.service')
> In that way we can drop sudoers.d/scylla completely.
>
I'm not familiar with all the context here, so I don't know which solution
would be best.

If you wouldn't use "sudo" at all, the original poster's problem would not
exist in the first place.

**Comment by avikivity** [comment]
Need to check which version of sudo added sudoers.d, and add a dependency on that version. This will refuse to install on too old versions.

**Comment by slivne** [comment]
@syuu1228 can you please fix this

**Comment by syuu1228** [comment]
@avikivity I installed 14.04LTS without any update, checked sudo package, it already supported /etc/sudoers.d
So I don't think we may have such version on 14.04LTS. If installed Ubuntu is more older, we won't support it so it won't be a problem.

**Comment by penberg** [comment]
The Ubuntu packaging issue is fixed now: https://github.com/scylladb/scylla/issues/1017

Is there anything else that needs to be addressed before we can close this?

**Comment by avikivity** [comment]
Looks like it was a local configuration issue in @s905060 setup.
