### ISSUE TITLE
schema update write path unnecessarily freezes-unfreezes mutations

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#10307]
When merging schema mutations, they are written to local node with `storage_proxy::apply(std::vector<mutation>)`, which calls `database::apply(schema_ptr, const frozen_mutations&)` for each mutation. Since `frozen_mutation` has an implicit constructor taking a `mutation`, this in effect freezes (serializes) the mutation, just so it is un-serialized immediately on the other side. Schema mutations can be big and there is many of them so this cost might be significant and certainly unnecessary.

**Comment by bhalevy** [comment]
Ref 16246d1c99e38d0b5562718f16bd066eefbeb202

**Comment by bhalevy** [comment]
@denesb do you mean the following call?
https://github.com/scylladb/scylla/blob/18be2e9fafdd682ae6420baba7eb249effac485b/service/storage_proxy.cc#L1869-L1879

**Comment by bhalevy** [comment]
For reference, this `freeze` call was there from inception (4ab66de0ae51b19660c7fef76106af2c246633f7)

**Comment by bhalevy** [comment]
Note that we do need to freeze the mutation at least for `commitlog_entry_writer` in `database::do_apply`.
I think that other than that we can pass a `const mutation&` around instead of a `const frozen_mutation&`.
So even if we'll need to freeze it for writing the commitlog entry it would still be worth passing a `mutation&` down to `table::apply` (via `apply_in_memory`) and `table::push_view_replica_updates` to avoid the unneeded deserialization eventually in `memtable::apply`.

https://github.com/scylladb/scylla/blob/18be2e9fafdd682ae6420baba7eb249effac485b/replica/memtable.cc#L794

**Comment by denesb** [comment]
Yes, that is the one. I think we should pass in something like this:
```
struct some_descriptive_yet_short_name {
    frozen_mutation frozen_mut; // always set, this is what we get from network
    mutation_opt mut; // optional -- if engaged, memtable will use this instead of unfreezing
};
```

**Comment by bhalevy** [comment]
I'm working on a RFC that defines a `frozen_mutation_or_mutation_wrapper` that can be passed around and will unfreeze a frozen_mutation (and maybe freeze) only when needed.

**Comment by bhalevy** [comment]
something along these lines:
```c++
class frozen_mutation_or_mutation_wrapper {
private:
    schema_ptr _schema;
    std::variant<const frozen_mutation*, const mutation*> _underlying;
    std::unique_ptr<mutation> _mutation;
    std::optional<dht::decorated_key> _dk;
    const dht::decorated_key& _decorated_key;

public:
    frozen_mutation_or_mutation_wrapper(const mutation& m) noexcept;

    frozen_mutation_or_mutation_wrapper(schema_ptr schema, const frozen_mutation& fm);

    frozen_mutation_or_mutation_wrapper(frozen_mutation_or_mutation_wrapper&&) = default;
    frozen_mutation_or_mutation_wrapper& operator=(frozen_mutation_or_mutation_wrapper&&) = default;

    utils::UUID column_family_id() const;

    const dht::decorated_key& decorated_key(const schema& s) const {
        return _decorated_key;
    }

    // unfreeze once if necessary
    const mutation& mutation() const;
};
```

**Comment by bhalevy** [comment]
I came to the conclusion that the following are pretty much inevitable:
- unfreeze in `table::push_view_replica_updates` is needed since the apply path to the database requires a frozen_mutation (since it is applied across shards) and do_push_view_replica_updates upgrades the mutation schema so it requires a mutation to upgrade.
- apply_with_commilog(const mutation&) freezes the mutation since the commitlog apply path also requires a frozen_mutation.
  - it is a private method of the database layer and is called only from `do_apply_counter_update` which also upgrades the frozen_mutation is gets and then uses it to compute static and regular comlumns.  Maybe there is potential there to avoid unfreezing the frozen_mutation and then freezing it again, but I'm not sure if it's possible, and if it's worth the effort just for counter updates.

**Comment by denesb** [comment]
I agree, this is not worth the effort, closing.
