### ISSUE TITLE
io_tune limit execution time

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1047]
We need to limit io_tune execution time to make sure that on slow disks we are not stalling boot for a very long time. 

Lets limit the whole run of io_tune to 5 minutes (can be additional command line flag with default time limit of 300s) - if we need to abort run before it ends lets right the "best educated" guess.

@glommer - I would rather have you handle other items - yetgetting th best educated guess is hard - so please provide input here and I'll assign this tom someone else (unless you can finish this in less then an hour

**Comment by slivne** [comment]
we also need to handle the case in which io_tune can not create the 10GB file - should we also write a default value in this case ?

**Comment by avikivity** [comment]
It can be the same fix.  Write data until a timeout, ENOSPC, or 10GB is 
reached (whichever is earliest) and run the test on the resulting file.

**Comment by slivne** [comment]
If we do not complete to write the file

should we provide a default or should we force the user to take action
(enable developer-mode) ?

**Comment by avikivity** [comment]
eof or timeout mean a small or slow disk, so it should work.

Any other error should result in a failure.

**Comment by glommer** [comment]
a timeout of 5 minutes may be too little. I don't think it makes sense for an usability point of view to limit the amount of time we spend on file creation. That's an internal detail.

It makes sense to limit the total amount of time, and then we limit the file creation to a fraction of that (1/3 ?)

Each of the iotune passes is limited by time, not IOPS, so I am less concerned about those. Still, the number of iterations is not fixed, and can vary.

phase1 will always run for around 50s, as it runs a fixed amount of sparse points
phase2 is also variable but bounded, and should take around 10 s, giving is around a minute total.
phase3 is the one that we don't know. It spends 2.1s per point, and a smarter way to bind this to a specific timeframe would be to limit the amount of points we run. How many points we run has less to do with the speed of the disk, and more with its variance. 30 points takes us to a minute, and from my accounts, i2 would resolve in less than that - and a good, stable SSD, with as little as 10 points. Still, I don't think it is unreasonable in practice to have a bad disk taking 2 minutes here.

So that leaves the file creation with either 2 or 3 minutes to run.

A single EC2 disk (not in a RAID) ticks at around 100MB/s (rounding down for simplicity), and below that we're almost talking HDD. However, we may not be able to achieve maximum parallelism here, because we are driving this phase from a single CPU (although we could change that). So if we assume we'll be doing 80MB/s, 2 minutes should buy us 9.6GB.

The scenario I have described above is not by any means good hardware, but it is still a far-from-uncommon scenario. 5 minutes would be enough, but barely. I propose then a 6 minutes timeout, with 40 % allocated to file creation and 60 % allocated for the test run.

**Comment by glommer** [comment]
A patch to seastar was just merged, that allows us to use timeouts with iotune.
