### ISSUE TITLE
OEL 76: scylla_setup fails due to an authentication issue: PAM account management error: Authentication service cannot retrieve authentication info

### ISSUE THREAD

**Issue by rayakurl** [scylladb/scylla#10483]
## Installation details

Cluster size: 1 nodes (i3.large)

Scylla Nodes used in this run:
- artifacts-oel76-jenkins-db-node-63f05ebe-1 (54.216.87.45 | 10.0.2.86) (shards: -1)

OS / Image: `ami-0d6a24fe35fdf5dc4` (aws: eu-west-1)

Test: `artifacts-oel76-test`
Test id: `63f05ebe-42b3-49f6-a194-dce457d7c912`
Test name: `scylla-master/artifacts/artifacts-oel76-test`
Test config file(s):

- [oel76.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3615a6c5d451a30d2929dd1593784ba7c643783f/test-cases/artifacts/oel76.yaml)

## Issue description

The same failure is constantly reproduced during EOL 76 artifacts test, seems like a permissions issue:
```
2022-05-01 08:33:32.494: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=76b34d6d-3827-4e53-a23a-d7faa335e506, source=ArtifactsTest.SetUp()
exception=[Node artifacts-oel76-jenkins-db-node-63f05ebe-1 [54.216.87.45 | 10.0.2.86] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
This is a supported kernel version.
Command 'sudo -u scylla /opt/scylladb/scripts/scylla-housekeeping --uuid-file /var/lib/scylla-housekeeping/housekeeping.uuid --repo-files '/etc/yum.repos.d/scylla*.repo' version --version 5.1.dev-0.20220501.7f1e368e92ce --mode i' returned non-zero exit status: 1
----------  stdout  ----------
------------------------------
----------  stderr  ----------
sudo: PAM account management error: Authentication service cannot retrieve authentication info
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 63f05ebe-42b3-49f6-a194-dce457d7c912`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=63f05ebe-42b3-49f6-a194-dce457d7c912)
- Show all stored logs command: `$ hydra investigate show-logs 63f05ebe-42b3-49f6-a194-dce457d7c912`

## Logs:
- **db-cluster-63f05ebe.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/63f05ebe-42b3-49f6-a194-dce457d7c912/20220501_083403/db-cluster-63f05ebe.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/63f05ebe-42b3-49f6-a194-dce457d7c912/20220501_083403/db-cluster-63f05ebe.tar.gz)
- **sct-runner-63f05ebe.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/63f05ebe-42b3-49f6-a194-dce457d7c912/20220501_083403/sct-runner-63f05ebe.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/63f05ebe-42b3-49f6-a194-dce457d7c912/20220501_083403/sct-runner-63f05ebe.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-oel76-test/513/)

**Comment by fruch** [comment]
@syuu1228 

seems like it's too related to https://github.com/scylladb/scylla/commit/48b6aec16a76f8cd60babf97cede99e7c0e50db1, since before that the return value from those commands weren't checked.

**Comment by syuu1228** [comment]
I guess it occurs on previous versions too, but never realized because we have executed scylla-housekeeping without `check=True`:
https://github.com/scylladb/scylla/commit/48b6aec16a76f8cd60babf97cede99e7c0e50db1#diff-50a6af38badc886bac68b8724c68cab0a3de945c91331d22da73be9428b67b45L374
After https://github.com/scylladb/scylla/commit/48b6aec16a76f8cd60babf97cede99e7c0e50db1 we changed the code to throw exception when the process returns non-zero, so we realized this error.

The error is 100% reproducible on "Oracle Enterprise Linux 7.6 supported by Navisite" AMI but never happens on CentOS7 AMI, so I guess the difference comes from system configuration, probably /etc/sudoers settings.

**Comment by fruch** [comment]
My guess we don't have scylla user in this case..., Why not plain sudo ? or why do we need sudo here in the first place ?

**Comment by syuu1228** [comment]
> I guess it occurs on previous versions too, but never realized because we have executed scylla-housekeeping without `check=True`: [48b6aec#diff-50a6af38badc886bac68b8724c68cab0a3de945c91331d22da73be9428b67b45L374](https://github.com/scylladb/scylla/commit/48b6aec16a76f8cd60babf97cede99e7c0e50db1#diff-50a6af38badc886bac68b8724c68cab0a3de945c91331d22da73be9428b67b45L374) After [48b6aec](https://github.com/scylladb/scylla/commit/48b6aec16a76f8cd60babf97cede99e7c0e50db1) we changed the code to throw exception when the process returns non-zero, so we realized this error.
> 
> The error is 100% reproducible on "Oracle Enterprise Linux 7.6 supported by Navisite" AMI but never happens on CentOS7 AMI, so I guess the difference comes from system configuration, probably /etc/sudoers settings.

Looks like it is related root user's entry of /etc/shadow, the error disappear when we set root password.

But I found that we don't have to use "sudo -u" to switch user to scylla, subprocess module actually supports switching user/group since Python 3.9:
https://docs.python.org/3/library/subprocess.html#popen-constructor
All we need is just pass user / group parameters to subprocess.run(), and I verified we don't get PAM error when we switch user via subprocess module.

**Comment by rayakurl** [comment]
Added the "master/high" label since this issue is reproduced on all EOL artifacts tests (online and ofline)

**Comment by avikivity** [comment]
@syuu1228 I'm evaluating for backport. On the one hand, it's an old bug that exists everywhere and was just uncovered by more strict error checks. On the other hand, nobody complained, so it's probably not a big problem.

I'll remove the backport candidate label, let me know if you disagree.
