### ISSUE TITLE
Wrong auth opcode crashes node

### ISSUE THREAD

**Issue by jul-stas** [scylladb/scylla#10487]
A faulty or malicious client can crash a node by sending wrong opcode while in `AUTHENTICATION` state:
```
Assertion `cqlop == cql_binary_opcode::AUTH_RESPONSE || cqlop == cql_binary_opcode::CREDENTIALS' failed.
```
To get to this point some race between two connections and/or reusing of stream ID might need to occur. Anyway, we should drop the connection instead of firing assertion.

**Comment by fee-mendes** [comment]
For the record, trying to naively craft a client to send a wrong opcode is not enough to trigger the assertion error. We validate that early on the process and drop the connection with:

```shell
Unable to connect: 'Underlying connection error: Received error response 'Unexpected message 255, expecting SASL_RESPONSE' (0x0200000A)'
```

**Comment by psarna** [comment]
I think it's possible to race if a malicious/buggy client sends multiple opcodes concurrently.

Our code currently works like that:

1. Receive a frame
2. Verify that the opcode from that frame matches our "auth state"
3. \<possible yield point\>
4. Run the opcode assuming that it passed verification from (2.); this stage can modify auth state

Now, imagine two opcodes racing concurrently - STARTUP and OPTIONS.

1. STARTUP arrives. Auth state == UNINITIALIZED
2. STARTUP is verified - it's legal for UNINITIALIZED auth state
3. OPTIONS arrives. Auth state == UNINITIALIZED
4. OPTIONS is verified - it's legal for UNINITIALIZED auth state
5. STARTUP is processed and changes the auth state to AUTHENTICATION
6. OPTIONS is processed and fails on the assertion - it was supposed to only be legal for UNINITIALIZED state, but the state is now AUTHENTICATION

The above is possible because there's a yield point between validation and processing, and a single connection is capable of serving concurrent requests.

@jul-stas is working on trying to trigger the race by injecting sleeps into Scylla code.

**Comment by jul-stas** [comment]
Exactly this. Yielding in `cql_server::connection::process_options` fires this assert 100% under this load (OPTIONS + STARTUP):
```
echo -n -e "\x04\x00\x00\x02\x05\x00\x00\x00\x00\x04\x00\x00\x01\x01\x00\x00\x00\x16\x00\x01\x00\x0BCQL_VERSION\x00\x053.0.0" | nc 127.0.0.1 9042
```
Now I'm thinking what to do. We can drop the connection (ez, although the client is innocent here) or we can overhaul the request flow (somehow introduce a barrier around STARTUP so it doesn't reorder with other opcodes?).

**Comment by jul-stas** [comment]
Also, in practice, this must be an extremely unlucky event. I shot millions
of these CQL hanshakes at a Scylla node harassed by C-S. Didn't trigger a
single assertion.

czw., 5 maj 2022, 12:34 użytkownik Piotr Sarna ***@***.***>
napisał:

**Comment by psarna** [comment]
I think that downgrading the assert to an exception is good enough and easy to backport. And the client that lost the race can simply retry.

**Comment by psarna** [comment]
backported to 4.6, 5.0

**Comment by avikivity** [comment]
@psarna why not 4.5?

**Comment by psarna** [comment]
wasn't sure if 5.0 is out or not, and I wanted to stick to 2 latest releases. It's trivial, so I'll push to 4.5 in a minute

**Comment by psarna** [comment]
done
