### ISSUE TITLE
Consider allowing global materialized views and indexes to be synchronous

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#10545]
Right now, global view updates are sent asynchronously in order to preserve availability, which makes perfect sense, because a single base update may need to update different views and partitions on different nodes, so we may end up needing all nodes to be up in order to succeed.

However, perhaps we should allow global views (and thus also indexes) to enter "synchronous mode". In this mode, all view updates are also applied synchronously as if the view was local, <strike>which significantly reduces their availability, but also makes inconsistencies considerably less likely to happen.</strike> which may reduce their availability, but also makes sure that information about potential inconsistencies is propagated back to the user - who may decide to retry a write operation or fix the view at a later time.

E.g.:
```cql
ALTER MATERIALIZED VIEW ks.v WITH synchronous_updates = true;
```

With such a mechanism, users will be able to balance availability and consistency the way they prefer. And if it doesn't fit into their workload type, the view can simply be dropped and rebuilt, which is already an existing procedure for fixing inconsistencies anyway.

Opinions?

/cc @eliransin

**Comment by nyh** [comment]
Thanks for opening this issue. We had exactly this discussion six years ago, when we decided to translate the Materialized Views code from Cassandra. The consensus then was that we can't have our materialized view implementation have higher latency, or lower availability, than Cassandra, so we need to make the writes asynchronous exactly like Cassandra did.

But a lot of water has passed under the bridge since. Cassandra has "downgraded" their MV feature to "experimental", so users are less likely to compare our performance to Cassandra in that area. Moreover, the Cassandra people now consider the asynchronous view updates a mistake too - I remember Jonathan Ellis once said, in one of his talks, that asynchronous view updates were "one of his biggest regrets about Cassandra design". (For archaeologists, check out the "why don't you support sync updates" in the [original Cassandra materialized-Views design document](https://docs.google.com/document/d/1sK96wsE3uwFqzrLQju_spya6rOTxojOKR9N7W-rPwdw/edit) - where they made that decision in 2015).

However, before we offer synchronous writes as an option we need to understand - and document - **exactly** what the  downsides will be, especially regarding the often-touted (also in the above-linked Cassandra design document) availability loss. Because I have to admit - I forgot what this availability loss is, exactly. Because some availability guarantees are not lost: 

Today, when you have CL=QUORUM, writes will always succeed when just one node is down. I think this property actually remains true even with synchronous view writes and one or more materialized views. If just one node is down, there are two options:

1. The three base replicas are all alive, so they will all succeed. Each of them is paired to a view replica, so if only one node in the system is down, at most one of the replicas are down, so we can reach two, so CL=QUORUM will be reached for the view update as well.
2. If only two of the three base replicas are alive, we reached CL=QUORUM for the base. Each of them has a paired view replica. The important point is that both these view replicas _must_ be alive, because they can't be the dead base replica node: One of the guidelines we use to choose base-view pairs is that if one node is both a base replica and a view replica for the given data, then it is paired with itself. So if one of the three base replicas were to be paired to the dead node, it must have been the dead node itself - not one of the other two.

So if this simple example is not the kind of availability loss we are worried about, let's formulate what is.

**Comment by psarna** [comment]
But at the same time, you're absolutely right that a more real use case, when a user creates one or two views and uses quorum, sounds perfectly acceptable availability-wise. The other doubt is increased latency, because we need to wait for more network hops and one more replica-side I/O before we can return to the client. But I still think we should give users a choice in this matter, because otherwise we block perfectly reasonable use cases from working out due to consistency issues.

**Comment by nyh** [comment]
@psarna you're right about the probability of failure increasing, but I don't consider this a problem. If anything, I think "it's not a bug, it's a feature". Let me explain why:

First, I think it's not fair to compare a write to a regular table without views - against a write to a base table with views that causes 100 view updates (perhaps because it has 100 views, or because it's a collection). If Scylla didn't have the MV feature at all (like Cassandra didn't have prior to 2015), the user would have done 100 writes explicitly in the application. So we should compare the write-with-the-views to the 100 writes. Just like we expect the write-with-the-views to take the resources of 100 writes (and not just of one write), we can also expect it to have the _availability_ of 100 writes. So if your setup in such a sorry state that each write has a 1% chance of failing, a doing 100 writes is almost certain to fail something - and similarly should the single write with the 100 views.

Moreover, the same example shows why synchronous updates **failing** is a feature not a bug: Consider the asynchronous view updates we have today. In your example there is 99% chance that the base write will succeed, so the entire write will seem to succeed as far as the user is concerned. BUT, according to your calculation, there is a 64% chance that one of the view updates would be lost. So in 64% of the requests, one of the view updates is lost and the user doesn't know about it! How is this good? At least with synchronous writes, the write will fail, and the user will know they must repeat the write or parts of it will not have happened.

Another thing to consider is our **view hints** feature. In the example of the previous paragraph, a base replica whose view replica is not available can store a view hint and send the view update later when the dead node comes back up. When CL is `ANY` instead of `ONE`, we can decree that writing a view hint is considered a success - when CL=`ANY`, so the failure rate of synchronous view updates becomes the same as that of asynchronous view updates.

**Comment by fee-mendes** [comment]
> If Scylla didn't have the MV feature at all (like Cassandra didn't have prior to 2015), the user would have done 100 writes explicitly in the application. So we should compare the write-with-the-views to the 100 writes. Just like we expect the write-with-the-views to take the resources of 100 writes (and not just of one write), we can also expect it to have the availability of 100 writes. So if your setup in such a sorry state that each write has a 1% chance of failing, a doing 100 writes is almost certain to fail something - and similarly should the single write with the 100 views.

I think the main difference here is the fact that in this case the client is sending a single write against a coordinator and it will be up for a single coordinator to ensure all MVs receive the updates synchronously. On the other hand, without MVs, the client can simply send 100 writes which will likely end up not only in different coordinators but also nodes!

Think about the following scenario (which is more realistic, as 100 views is something that shouldn't be done even async as it is today :-) : 

1 base table, 5 Synchronous MVs, RF=3, 15 nodes. And now do a simple BATCH inserting 1K records. What are the likely chances that this will not timeout or fail due to high concurrency?

**Comment by nyh** [comment]
> 1 base table, 5 Synchronous MVs, RF=3, 15 nodes. And now do a simple BATCH inserting 1K records. What are the likely chances that this will not timeout or fail due to high concurrency?

Yes, MV writes are slower than regular writes. So if you want to wait for 1000 of those to finish, you can time out. But how is this specific to materialized views? If a materialized-view write is 10 times slower than a regular write, then 1,000 writes will take the same time as 10,000 regular writes - so you'll have with 1,000 MV writes the same problem that you'll have with 10,000 regular writes. It doesn't seem to me like a new problem, or an "availability" problem.
