### ISSUE TITLE
Invalid IN restriction is reported as a '=' restriction

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10631]
In the cql-pytest `cassandra_tests/validation/operations/select_single_column_relation_test.py::testInvalidCollectionNonEQRelation`
we have the query
```
SELECT * FROM %s WHERE c = 0 AND b IN (?)
```
Where b is a `set<int>`, Scylla reports the error:
>  Collection column 'b' (set<int>) cannot be restricted by a '=' relation

Obviously, this is a 'IN' relation, not a '=' relation. Cassandra prints 'IN' here and so did Scylla until very recently (when I translated this test, it used to pass).

**Comment by cvybhu** [comment]
It's because single element IN restrictions are converted to EQ restrictions here:
https://github.com/scylladb/scylla/blob/19316dee94bf9cef6bcf2ae5f82078da9d78434a/cql3/expr/to_restriction.cc#L328

This was the case already before my changes that removed the relation class, but the check must have happened before the conversion then.
I will fix this.

**Comment by avikivity** [comment]
I guess this is a very recent regression? What is the commit that started the failure? How does it pass next promotion?

**Comment by nyh** [comment]
@avikivity it is indeed a recent regression, but the test for it - which I translated from Cassandra a few days after the regression happened - is even newer, which is why we didn't notice it earlier.
