### ISSUE TITLE
Truncate command may timeout on loaded cluster

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1071]
When a loaded cluster receives a truncate command it may timeout.
Once the load decreases (under 50%) the command succeeds.
The keyspace truncated is the same one which the load (cassandra-stress) is using

```
cqlsh> CONSISTENCY all;
Consistency level set to ALL.
cqlsh> TRUNCATE test1.standard1 ;
OperationTimedOut: errors={}, last_host=10.240.0.4
```

**Comment by tzach** [comment]
Note that driver side timeout does not mean the truncate did not worked

**Comment by tzach** [comment]
scylla.yaml have an unused  configuration `truncate_request_timeout_in_ms`  with default value 10000, cassandra.yaml default is 60000
Maybe scylla should use the same value as cassandra?
(not a perfect solution for sure. truncate is a heavy operation)

**Comment by dorlaor** [comment]
I increased the timeout on the server side but it didn't help.
What did help is to increase the cqlsh timeout on the client by

vi ~/.cassandra/cqlshrc

Example to set a 40 second timeout:

[connection]
client_timeout=40

**Comment by avikivity** [comment]
So, close issue?

**Comment by dorlaor** [comment]
I'll close it but it is nice to know why it takes time to truncate

**Comment by tzach** [comment]
From C* list:
"Why truncate takes a long time? That because all memtables should be 
flushed to free up commit logs, then truncated sstables should be snapshotted 
All this takes time for a truncate."
This need to happened on all nodes, so a slow node will slow down the operation. 

http://mail-archives.apache.org/mod_mbox/cassandra-user/201203.mbox/%3C4F6AE949.5010109@free.fr%3E
