### ISSUE TITLE
Alternator tables with specifically crafted column names won't work properly with paging

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#10903]
Commit [3131cbe](https://github.com/scylladb/scylla/commit/3131cbea629d8ac416db592ccfb7a9f55e90c48a) introduced a regression to alternator, which is rather unlikely to happen, but it's nonetheless possible.

The newly introduced special fake columns, `:scylla:paging:region` and `:scylla:paging:weight` are used in order to be able to return a paging state which does not correspond to any existing keys, and can instead indicate a place in the middle of a long tombstone run. Thing is, while DynamoDB users are actively discouraged from using colons (`:`) in the column names, it's technically legal to do so:
```
Although DynamoDB allows you to use these reserved words and special characters for names, we recommend that you avoid doing so because you have to define placeholder variables whenever you use these names in an expression.
```
Source: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html

If we want to be 100% correct and keep our paging implementation intact, we should consider either reserving these two keywords and disallow naming columns with them, or go one step further and reserve the whole prefix, e.g. `:scylla:`.
Or, maybe we can work around this issue from a different perspective, with a specialized implementation that doesn't rely on the (region, weight) pair.

The identifiers are defined here:
https://github.com/scylladb/scylla/blob/d3c6e72c6934cb7b8f16231ea2fa7075d855202f/alternator/serialization.hh#L38-L39

/cc @nyh

**Comment by nyh** [comment]
@psarna I asked on the original PR but never got a response that satisfied me: Can you or @denesb or someone please explain to me why these "region/weight" per are necessary? Alternator's ExclusiveKeyStart can **already** be a non-existent (tombstone) clustering key. What more than that does this region/weight achieve? Can you give me an example? If the answer are "static columns" let me add that Alternator does not have those.

**Comment by psarna** [comment]
@nyh I have no clue why exactly we need region/weight for, but hopefully @denesb does. I mentioned "specialized implementation that doesn't rely on the (region, weight) pair" specifically hoping that it's the case, because then we won't need to reserve any names or prefixes.

**Comment by denesb** [comment]
I explained why we need these in https://github.com/scylladb/scylla/pull/10829#discussion_r904515911, I guess this was lost in the noise. To repeat, I wanted to expand our paging state from a fixed `after(key)` to the full `position_in_partition`. This represents arbitrary positions in a partition with three fields:
* clustering key (can be null)
* region (partition start, static row, clustering, partition end)
* weight (before, at, after)
Although it is very likely we won't be using the full range of possible values of a `position_in_partition`, it is better to have full support for it in all APIs, instead of supporting a different subset everywhere and having to cover all the corner cases of conversions.

**Comment by denesb** [comment]
Strictly speaking, `region` is probably not necessary, it is always going to be clustered. But we *do* need weight because tombstones can have positions of `before(key)`. And if we add one column, we might as well add both to cover the full `position_in_partition`, see above.

**Comment by nyh** [comment]
> Strictly speaking, `region` is probably not necessary, it is always going to be clustered.

Good, so I think we better get rid of it.

> But we _do_ need weight because tombstones can have positions of `before(key)`. And if we add one column, we might as well add both to cover the full `position_in_partition`, see above.

I don't understand what this means. A row tombstone has a position on a key, not before a key. Maybe you're thinking about some sort of exotic range tombstones (?) but those don't exist in Alternator either.

**Comment by denesb** [comment]
> > But we _do_ need weight because tombstones can have positions of `before(key)`. And if we add one column, we might as well add both to cover the full `position_in_partition`, see above.
> 
> I don't understand what this means. A row tombstone has a position on a key, not before a key. Maybe you're thinking about some sort of exotic range tombstones (?) but those don't exist in Alternator either.

Regular range tombstones have either before/after key positions, never at a position. If it is impossible alternator to have range tombstones, then we can get rid of these fields and just assume position is always after(key), like before.

**Comment by denesb** [comment]
The worst case I can think of is some rows not appearing in query result, or apparent (but not real) data loss. This can happen if the stop position was `before(key)` but after coming back from alternator, the position is reinterpreted as `after(key)`. If there is a row `at(key)`, it will not appear in the results.

**Comment by psarna** [comment]
Oh, that's an interesting edge case... We support reading system tables via an alternator extension, and I'd love to keep it working. Ref: https://github.com/scylladb/scylla/blob/master/test/alternator/test_system_tables.py . These tables are very specific though, and you don't even need to page their results.

So @denesb, perhaps we should disallow **paged** reading of CQL tables through alternator?

**Comment by denesb** [comment]
This check has to happen in the alternator layer, because we cannot tell where a query is coming from in the paging code.
Can one of you cook a patch for this? Reverting my changes + disallowing paged reads for non-alternator tables.

**Comment by nyh** [comment]
> So @denesb, perhaps we should disallow **paged** reading of CQL tables through alternator?

I don't think that's a good idea. We have system tables that can grow pretty large, and we might want to scan them.

What we can disallow is reading (or just paging?) in a table that has range tombstones. I don't think we really need to "disallow" this - just assume it doesn't happen - since we only allow reading system tables anyway, the question is - does any of those have range tombstones? I guess the answer is no. Tables with collection columns commonly use range tombstone (but does this range tombstone have the "before" problem?) but I believe we can't read such tables with Alternator anyway? (how will we represent them?)

**Comment by denesb** [comment]
Range tombstones have nothing to do with collections. Range tombstones are created by queries such as `DELETE FROM ks.tbl WHERE pk = ? AND ck > ? AND ck < ?`. I don't see how we can assume system tables won't have range tombstones. They might not have any today (I'm not even sure of that) but they might get some in the future. And remember, the administrator can write system tables as well. Another problem is that you don't know whether a table has range tombstones are not until you see one (actually, tables with no clustering columns **can't** have them at all).
I know that the chances of the above mentioned scenario is so minuscule that it is tempting to just ignore it, but  do we really want to leave a known bug like that in the code.
I see the following options (in no particular order):
1) Bite the bullet and leave the new fields in, providing full support for position-in-partition. It is the safest option but creates a previously nonexistent problem with reserved names.
2) Disallow paging system tables when read through alternator. Risky because we can't guarantee that all system tables stay small. Some tables might become impossible to read through alternator (due to the query paging when reaching a too large size).
3) Pass down a flag to replicas and avoid stopping at `before(key)` positions when reading on behalf of alternator. Adds complexity and creates an almost never-used poorly tested silo that can harbor bugs undetected.
4) Just assume system tables won't have range tombstones and even if they will, they won't be in a problematic arrangement. Only adding this for completeness. This is basically burying a land-mine and trying to remember not to step on it.
5) Disallow reading system tables altogether. Also only here for completeness, this would be a regression compared to today.

**Comment by denesb** [comment]
I of course favor option (1) because in my opinion it has the most manageable repercussions (and I don't have to undo my changes), but maybe I'm underestimating the complexity involved with introducing reserved names.

**Comment by nyh** [comment]
@denesb here is a 7th option I think is the best of all worlds and I recommend:

* Keep the code which can add the two new fields (region and weight), but in all normal Alternator cases, you shouldn't output them at all - a missing value will mean the default (region is clustering, weight is after). If we do this, 100% of the Alternator users will never see those extra fields in practice, and we won't even need to document them anywhere.
* In the extremely unlikely case where somebody uses Alternator to read a CQL system table which has a very large static row or has range tombstones (I don't think such system tables exist today!), we can output those extra fields.
* Finally, on read do not unconditionally look for ":scylla:*" keys in ExclusiveKeyStart - only look for those keys if the table being read is a CQL system table (the Alternator code knows that this is the case). This point means that these attribute names do not become reserved in normal Alternator tables, and assuming that these silly names are never used in system tables - we can't have a collision.

**Comment by denesb** [comment]
I think this can work. This means that now we have to make these new fields not collide with CQL columns names in turn :).

**Comment by psarna** [comment]
@nyh yup, sounds perfect. @denesb that's way easier, since system table columns are only ever defined in code, so that doesn't even need to be a runtime check.
