### ISSUE TITLE
alternator-write-isolation: only_rmw_uses_lwt can't guarantee overwrite put-item safe even there is no mix of read-modify-write and write-only updates

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylla#10966]
Hi~ I found that with alternator-write-isolation: only_rmw_uses_lwt， overwrite put-item cannot be guaranted safe even there is no mix of read-modify-write and write-only updates. I'm not sure if this is a problem.

Easy to reproduce this:
1.overwrite a item with a different flag , then 2. get item with consistent-read , loop 1, 2, you will find that the item is not guaranteed to be up-to-date, and sometimes read the old value. (I don't think that get item then overwrite item in two requests belongs to read-modify-write operation).

**Comment by nyh** [comment]
This is a very interesting issue:

In theory, since normal writes (non-LWT) use CL=QUORUM and consistent reads use CL=QUORUM, you should be able to read your own writes - it shouldn't be possible to read an older value.

But there is one snag here, which I mentioned in my blog post comparing Scylla (and Cassandra) and DynamoDB, https://www.scylladb.com/2020/05/12/comparing-cql-and-the-dynamodb-api/:

> Ordinary writes are not always serialized. They usually are: CQL assigns a timestamp (with microsecond resolution) to each write and the latest timestamp wins. However two concurrent writes which happen to receive exactly the same timestamp may get mixed up, with values from both writes being present in the result. For more information on this problem, see [this Jepsen post](https://aphyr.com/posts/294-call-me-maybe-cassandra).

In other words it is theoretically possible that you can send a write "a=1" and later, but very quickly, send a write "a=2". If these writes get sent to _different_ coordinators, they may happen to pick the same microsecond timestamp, and you don't know which one will "win" - it is possible that the earlier "a=1" would win. Even worse, if the clocks on the two coordinator nodes are not perfectly synchronized to the microsecond level by NTP (and it probably isn't!), you can get a reversal of who "wins" even if there is more than one microsecond between the two writes. 

LWT solves this problem by assigning **globally**-increasing timestamps to write. The second write is guaranteed to pick a timestamp higher than the first, regardless of the clocks on the different coordinator nodes. This increasing timestamp is picked as part of the Paxos protocol used to implement these writes. But non-LWT writes do not have this feature of globally-increasing timestamps.

The question I have for you now is whether it is possible that **this** is your problem. What I'm asking is:
1. Does your use case actually has two adjacent writes (with time difference less than NTP's jitter, I hope you're using NTP... Can you say something about your ntp setup?), and  you're are reading the first write instead of the second write? If your use case is the loop which you described, do you continuously write to the *same* item?
2. If you continue reading, do you continue to read the old value or does stay forever on the old value? (or does it eventually revert to the new value?)

If the answer to one of these questions is "no", then the problem I'm describing is **not** the bug you're seeing, so would need to make another guess.

**Comment by Felix-zhoux** [comment]
Thanks for your reply.

> The question I have for you now is whether it is possible that **this** is your problem. What I'm asking is:
> 
> 1. Does your use case actually has two adjacent writes (with time difference less than NTP's jitter, I hope you're using NTP... Can you say something about your ntp setup?), and  you're are reading the first write instead of the second write? If your use case is the loop which you described, do you continuously write to the _same_ item?

Yes, I do have  adjacent writes to the _same_item，and the `chronyd.service` stalled  due to some reason, the time synchronization between nodes reached the minute level.

> 2. If you continue reading, do you continue to read the old value or does stay forever on the old value? (or does it eventually revert to the new value?)
> 

Still old value, it doesn't revert to the new value.

> If the answer to one of these questions is "no", then the problem I'm describing is **not** the bug you're seeing, so would need to make another guess.

So, based on your detailed explanation above, I think that multiple write requests for the same item are sent to different coordinators, due to the asynchronous time, the value of the request sent later is overwritten by the value of the request sent first.
For example:
```
request 1, set name=dog reach coordinator c1 at time 10:08:30
request 2 , set name=cat reach coordinator c2 at time 10:07:55
```
Send request 1, then read this item with consist-read，then send request 2, then read this item with consist-read ，We always read `name=dog` and never update to `name=cat`.
What I am curious about is that in this case, the http status codes of request1 and request2 are both 200? Will request2 actually be executed?

**Comment by nyh** [comment]
> Yes, I do have adjacent writes to the _same_item，and the `chronyd.service` stalled due to some reason, the time synchronization between nodes reached the minute level.

So I think this ntp problem explains the entire problem that you saw: Scylla's conflict resolution is based on **timestamps** - the write with higher timestamps win. CQL clients have two options - client-provided timestamps and server-provided timestamps, but Alternator only has the second option (server-provided timestamps). This means that if two servers (nodes) have very un-synchronized clocks, an earlier write may overwrite a later write if they arrived at different nodes at local times that are in reverse order (the earlier write got a higher timestamp).

I'm not sure what we should, or can, do about this issue, except document it in docs/alternator/compatiblity.md (which I will, before closing this issue). The same issue exists in CQL, but there you also have an option to use client-side timestamps - although this theoretical option is rarely used in practice. Another workaround is to make sure that if you have two writes that you want to not be reordered (i.e. write and then overwrite), then you should send them to the same Scylla server otherwise you are risking reordering. Some of our load-balancing implementations (do you use them?) do not make this guarantee that two requests get sent to the same server.

If you fix NTP, the risk of this problem will be much lower, but it still won't be zero.

If you're wondering why the problem does _not_ exist when write LWT is used for writes, well, the thing is that LWT does trust NTP (which, even if probably configured, cannot really guarantee perfect synchronization) and has a distributed protocol (based on Paxos) for choosing a monotonically increasing timestamp, so the writes get an increasing timestamp and don't get reordered.

> So, based on your detailed explanation above, I think that multiple write requests for the same item are sent to different coordinators, due to the asynchronous time, the value of the request sent later is overwritten by the value of the request sent first. For example:
> 
> ```
> request 1, set name=dog reach coordinator c1 at time 10:08:30
> request 2 , set name=cat reach coordinator c2 at time 10:07:55
> ```
> 
> Send request 1, then read this item with consist-read，then send request 2, then read this item with consist-read ，We always read `name=dog` and never update to `name=cat`. What I am curious about is that in this case, the http status codes of request1 and request2 are both 200? Will request2 actually be executed?

request2 is indeed executed successfully - it writes "cat" to a new memtable and/or sstable. But when Scylla goes to read this item later - or when it does _compaction_ - it sees both dog and cat in different sstables, and believes that the "dog" is the newer one - because it only compares the timestamps - so "dog" is what gets read and returned.

**Comment by nyh** [comment]
@Felix-zhoux I sent a pull-request #11094 with documentation (in docs/alternator/compatibility.md) of this issue, what causes it and how to fix or at least improve the situation. Please take a look an let me know if you think this documentation is helpful, or you expected something else.

Right now, I believe that documentation is the most we can do for this issue - I don't think there's an appropriate patch to the code that we can do right now. The really optimal solution would have been to make `always_use_lwt` mode the default and always use it, and we will be able to do that once we switch the LWT implementation from Paxos to Raft and make it significantly faster. But this is a longer term plan that is out of scope for this issue.

**Comment by Felix-zhoux** [comment]
@nyh  Thank you! The doc expained very clearly.

**Comment by eliransin** [comment]
@nyh I know this issue is dead, however, we might be able to detect this and warn about this. Maybe even reject the writes by default (AKA scylla safe mode :slightly_smiling_face: ).
Here is a possible algo:
1. Save the max timestamp received by any write so far.
2. If the timestamp for the current write is more than X into the future relative to this node wall clock we know we have a drift.
3. else, if a write is more than X into the past from the value in 1. we have a drift.

2 means that we found a large deviation between some node and the node running the algorithm.
3 means that we found a large deviation between two other nodes in the system.

This is not a perfect solution but I think it has a large probability to detect a divergence. Once we do we can decide for example
to shut down all cluster or only the node that is known to deviate or just warn. But at least we can worn about it.
Next step might be, given that we detected this situation we can find a way to run a more expensive cluster wide procedure to detect such deviations and maybe fix it somehow (this is also not simple because you can fix it only forward).

**Comment by nyh** [comment]
> @nyh I know this issue is dead, however, we might be able to detect this and warn about this. Maybe even reject the writes by default (AKA scylla safe mode slightly_smiling_face ). Here is a possible algo:
> 
>     1. Save the max timestamp received by any write so far.
> 
>     2. If the timestamp for the current write is more than X into the future relative to this node wall clock we know we have a drift.
> 

When all writes use server-side timestamps, then indeed a replica can detect futuristic timestamp from a coordinator and complain that NTP is off.
The only problem is that in CQL, client-side timestamps **are** allowed. A client can, for any reason, do a write with timestamp 1 hour in the future, and Scylla is supposed to accept that.

That being said, we recently decided (I don't remember where this is documented, but see commit 2150c0f7a2d56b9ea2a5607a4066c4c1c3aba40f) that timestamps are supposed to be real timestamps in microseconds - not anything else - so maybe we can decide (again, this might require documentation changes) that client-side timestamps are expected to be close to the node's clock as well.

**Comment by eliransin** [comment]
I was reffering specifically to Alternator tables. Maybe we can include a flag that indicates that the write originated from the 
dynamoDB api and only do the sujested method on those calls. Or be more general then this and only work on server side 
timestamped writes.
The real question is, how big of a problem is it?
I think that users are not aware of this hidden assumption about time sync today and maybe the right way to go about this is to
detect it if possible and warn them (?)

**Comment by nyh** [comment]
The patch is already in branch 5.1. This is a documentation-only issue, so not backporting to the earlier 5.0.
