### ISSUE TITLE
golang integration?

### ISSUE THREAD

**Issue by hiqsociety** [scylladb/scylla#10999]
lots of people use golang, other than lua scripting, possible to consider some way golang can be used together too?

i dont mean golang binding.
thx

**Comment by nyh** [comment]
It's not clear what you're asking about. I'll try to guess, but please confirm my guess or explain yourself:
By "Lua scripting", do you mean the user-defined functions in Scylla, that you'd like to be in Golang instead of Lua?

We have rudimentary WASM support, so perhaps Golang could be supported using that route - maybe @psarna can comment if that's possible or even reasonable.

What do you mean by "I don't mean golang binding"?

**Comment by psarna** [comment]
A quick Internet search suggests that it is possible to set up Go to compile to WebAssembly, and if it's true (I haven't tried), then you could indeed write a user-defined function in Go and compile it to Wasm, which we already support.

In order to faciliate the WebAssembly-based user-defined functions development we're going to build helper libraries for a few popular languages, but right now we focus on Rust and C++. Once that's done, we can investigate Go support too.

**Comment by eliransin** [comment]
@psarna assigned you as WASM is in your teams's realm.

**Comment by avikivity** [comment]
We need first to understand what @hiqsociety meant by "golang integration", and then decide if we want to do it.

Closing until we have more information.
