### ISSUE TITLE
sstable: summary and statistics difference in size

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1104]
## Installation details
Scylla version (or git commit hash): 1.0-rc1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI):

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

I have created a table and inserted a single row and did a flush - 
- TOC, CRC, Digest, Data, Filter, Index have the same size
- Summary, Statistics differ in size.

It may be nothing but lets verify that

``` 
CREATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

insert into keyspace1.standard1 (key) values (0x01);
```

```
ccm create cas-1-1  --vnodes -n 1 --install-dir=<cas-dir>
ccm start
ccm node1 cqlsh -f create_tables
ccm node1 flush
```

* summary file : scylla 47 Bytes , cassandra 83 Bytes
* statistics file : scylla 4450 Bytes , 4434 Bytes

**Comment by raphaelsc** [comment]
Cassandra inserts garbage at the end of summary which is only relevant to it. I only remember that it has something to do with memory map. And yes, Cassandra can work with a summary that doesn't have the garbage at the end. And related to statistics file, it's probably that our cardinality information (which is of variable length) is generated in a different way. I would also like to verify that min_column_names and max_column_names of Statistics metadata is generated correctly by us (also of variable length).

**Comment by nyh** [comment]
As @raphaelsc said above, the Cassandra and Scylla start out identical, and then Cassandra adds something ("garbage", to use Raphael's nomenclature ;-)) additional at the end. I'll try to figure out what it is an explain it in https://github.com/scylladb/scylla/wiki/SSTables-Summary-File, which I already started to expand.

By the way, Raphael left the following comment in the code about the unknown stuff at the end

```c
   // NOTE4: There is a structure written by Cassandra into the end of the Summary
    // file, after the field last_key, that we haven't understand yet, but we know
    // that its content isn't related to the summary itself.
    // The structure is basically as follow:
    // struct { disk_string<uint16_t>; uint32_t; uint64_t; disk_string<uint16_t>; }
    // Another interesting fact about this structure is that it is apparently always
    // filled with the same data. It's too early to judge that the data is useless.
    // However, it was tested that Cassandra loads successfully a Summary file with
    // this structure removed from it. Anyway, let's pay attention to it.
```

**Comment by nyh** [comment]
As we might have guessed, the stuff at the end of the sstable is not quite "garbage", and has a meaning which I'll try to explain now.

Cassandra based on antediluvian programming languages and programming techniques, mmap()s sstable files, and is limited to doing that in 2 GB chunks. So it has the notion of a SegementedFile which is divided into 2 GB segments (I believe it makes an pick segment boundaries such that a single partition isn't split to two segments).

Each of the index and data files can be segmented in this way, and the summary file ends in a description of the segments of both these files:

The code that writes the summary file is in SSTableReader:
```java
    private void saveSummary(SegmentedFile.Builder ibuilder, SegmentedFile.Builder dbuilder, IndexSummary summary)
            // The stuff we are familar with:
            ...
            ByteBufferUtil.writeWithLength(first.getKey(), oStream);
            ByteBufferUtil.writeWithLength(last.getKey(), oStream);
            // This is what writes the alleged "garbage"
            ibuilder.serializeBounds(oStream);
            dbuilder.serializeBounds(oStream);
```
The base class SegmentedFile.Builder.serializeBounds() write the disk access mode, which is "mmap" (written as the two bytes \00 \04 and then mmap), and then MmappedSegmentedFile.Builder.serializeBounds writes the number of segments (32 bit) and the position of each of these segments.

When the files have size < 2 GB, we should always see at the end of the summary file the bytes "\0 \4 m m a p \0 \0 \0 \1 \0 \0 \0 \0 \0 \0 \0 \0" repeated twice (once for the index file, once for the data file).

The strange thing is that although @raphaelsc said he saw that Cassandra doesn't mind the missing end of the summary file, the code itself appears to be trying to deserialize these bound, and SegmentedFile.Builder.deserializeBounds() fails if the "mmap" stuff is missing. So I'm not sure where is the code that ignores this failure.

None of this appears important to scylla, but it might be important in the future if we want to take a scylla database and move back to Cassandra?

By the way, note that Cassandra apparently has code to rebuild the summary files from scratch when needed (when switching to or from mmap), so I believe that even if we both up the summary files, not all is lost and they can be rebuilt anyway.

**Comment by slivne** [comment]
Thanks nadav

What is not clear to me is if a file needs to be bigger then 2gb how does
it look at the fs level

Are there multile data files for a generation number without additional
other files (toc,summary etc.)

Are we able to cope with such files qhen we are migrating such latge files
will we read them corrwctly if thwy are copied over

**Comment by nyh** [comment]
If I understand correctly, there is just a single data file, and different segments of it are mmap'ed separately, and that "garbage" at the end of the summary file is what makes it easy to know which positions to map. I believe this "boundary" stuff assumes that both filesystem and mmap are 64 bit, but just Java is limited to mapping 2^31 byte chunks at a time (see for example http://nyeggen.com/post/2014-05-18-memory-mapping-%3E2gb-of-data-in-java/)

I think that for Scylla, we should have no problem reading an sstable - even a > 2 GB one - even without these "segment boundaries" information, because we won't use this silly information in any case. Whether or not Cassandra can read *our* files, missing these segment boundaries, is a different question... Did we ever try to migrate Scylla sstables to Cassandra?

**Comment by slivne** [comment]
Thanks

Yes we did try to migrate our files - yet never at this scale.

**Comment by nyh** [comment]
On Mon, Mar 28, 2016 at 1:06 AM, slivne <notifications@github.com> wrote:

> Thanks
>
> Yes we did try to migrate our files - yet never at this scale.
>

But looking at the Cassandra code, I got the impression that even at a
small scale, Cassandra should not be able to read our summary files because
it should complain that it can't read the disk access mode. If no such
error gets printed, I think I'm missing another piece of logic in Cassandra
which might make it ok not to have this part of the summary file.

**Comment by slivne** [comment]
I'll try to test this ... (or you can) it's simple

**Comment by nyh** [comment]
On Mon, Mar 28, 2016 at 1:12 AM, slivne <notifications@github.com> wrote:

> I'll try to test this ... (or you can) it's simple


I ran Cassandra on our (truncated) summary file, and it works.

But it works because the Summary file gets rewritten by Cassandra!

I didn't find this in the code yet, but apparently Cassandra either always
rewrites the summary file (based on the index fille) or only does this when
it fails to read the summary file. In any case, it doesn't work because we
wrote the summary file correctly - it works despite us having written it
incorrectly ;-)

In fact, even if I remove the summary file, everything works in Cassandra,
and it recreates the 83-byte file.

If Cassandra can recreate the Summary file then I'm fine with us not fixing
anything here, and let Cassandra worry about recreating the summary file if
needed.

**Comment by nyh** [comment]
@slivne I agree with your WONTFIX conclusion.
