### ISSUE TITLE
column_family::get_sstable_by key should be supported

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1166]
There should be an API for column_family::get_sstable_by_key.
Effected nodetool command:
nodetool getsstables

**Comment by nyh** [comment]
Can you please add a few more details for this issue, if you know the answers?
1. The function probably shouldn't be called get_sstable but rather get_sstables, because multiple sstables may contain this key. Right?
2. Is this function expected to get a quick approximate response (e.g., using the bloom filter), or an accurate response of which sstables *really* contain some data for this key, by actually checking the sstable's index file? I guess it's the latter, but I can't find any documentation of "nodetool getsstables" explaining what it actually does.

**Comment by amnonh** [comment]
Yes, it should be plural
The original java code:
Note that the code is of a specific column family.

public List<String> getSSTablesForKey(String key)
    {
        DecoratedKey dk = partitioner.decorateKey(metadata.getKeyValidator().fromString(key));
        try (OpOrder.Group op = readOrdering.start())
        {
            List<String> files = new ArrayList<>();
            for (SSTableReader sstr : select(viewFilter(dk)).sstables)
            {
                // check if the key actually exists in this sstable, without updating cache and stats
                if (sstr.getPosition(dk, SSTableReader.Operator.EQ, false) != null)
                    files.add(sstr.getFilename());
            }
            return files;
        }
    }

I'm no expert, but it looks like they are looking for the key position in the sstable (using the index I guess)

**Comment by benoit-canet** [comment]
@amnon: I wrote it. Just to be sure: is a key a collumn name ?

**Comment by nirmaayan** [comment]
@slivne do we have estimated 2.x version?

**Comment by tzach** [comment]
@amnonh any update on this issue?

**Comment by slivne** [comment]
@amnonh - is this fixed - I think you sent patches in the past - if it was merged can you reference the commit - if not can you please bring them back ... and lets fix this

**Comment by slivne** [comment]
@amnonh - is there a dtest for this ?

**Comment by amnonh** [comment]
No, just a unit test
