### ISSUE TITLE
Align metrics names: background_writes, background_reads, foreground_writes and foreground_reads

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1217]
Scylla have the following metric storage_proxy_queue_length types: 
- background_writes
- background_reads
- foreground_writes
- reads

reads metric should be "foreground_reads"

**Comment by vladzcloudius** [comment]
@tzach I'm not sure "reads" are only "foreground reads". AFAICT "reads" are all pending reads since it's incremented in the abstract_read_executor and decremented in its destructor. I'm also not sure that the semantics of foreground/background operations in read and write context is equivalent and thereby the differences in the metrics sets are rather expected. However, I admit that there is some similarity too. Therefore, unless I miss something the "foreground read" counter may be introduced, but, like I said, it would be a new metric. See below...

Let me explain the semantics of fore/background reads/writes as I understand it. However it would help if @gleb-cloudius would verify how much is what I'm saying close to the reality... ;)

For **writes**, the operation is considered to be in the foreground as long as it didn't reach the requested CL. Once it does - the response to the user is generated. If after that there are any replicas that are left to be written in order to reach the RF (which could be greater than CL) then the operation is considered to be in the background state until all replicas are written or until the corresponding timeouts/errors.

For **reads**, the operation is considered to be in the background state only after the CL has been reached (and digests were matching) but there were more target replicas (and it's not a simple "reach the RF" logic that defines the target replicas). In that case, as long as digests of the remaining replicas are being verified (and fixed if needed), the read query is considered to be in the background state. 
The response to the user is generated immediately after the CL is reached however.

So, like for write operations the "foreground_reads" == "reads" - "background_reads".

I guess this metric hasn't been added because it makes little sense to have all 3 of the counters above and AFAIR "reads" was the first that was added.

Having said all that and getting back to the opening post of this issue we'd rather align the semantics of read and write operations however the proposed solution is clearly not the right one.

I suggest we add the new "foreground_reads" metric and keep the "reads" metric in order not to break the already existing solutions that are using it.

@tzach, @gleb-cloudius, comment please.

**Comment by tgrabiec** [comment]
Refs scylladb/scylla-grafana-monitoring#75

**Comment by gleb-cloudius** [comment]
On Fri, Jan 27, 2017 at 11:14:05AM -0800, vladzcloudius wrote:
> I guess this metric hasn't been added because it makes little sense to have all 3 of the counters above and AFAIR "reads" was the first that was added.
> 
Initially writes also had "writes" and "background_writes" metrics, but
when I was adding write throttling code and had to use those counter a
lot I found out that often those two graphs are very close and thus not
very informative. Having "foreground_writes" counter instead of total
"writes" one was much more informative (049ae37d08f). I did not do the
same for reads, but it make sense to do so.

--
			Gleb.
