### ISSUE TITLE
Do not allow stop of Scylla AMI on EC2

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1229]
Instance which use ephemeral drive can not be stopped and start on EC2, as all of its data will be lost.
Scylla AMI should not allow it.
Only terminate should be allowed.

**Comment by syuu1228** [comment]
I think @tzach talking about EC2 dashboard, https://github.com/benoit-canet/scylla/commit/7c30fe399630c09ed07c281e25b46ebf300c0025 is not real solution.

There are two AMI image types, EBS-Backed AMI and Instance Store-Backed AMI.
Current one is EBS-Backed, it allows to run all instance types, and can Stop/Start on ephemeral instance types (such as c3/m3).
Other one is Instance Store-Backed AMI, it like root disk is also ephemeral. It is only allows to run on ephemeral instance types, and does not support to Stop/Start.

We can change our AMI type to Instance Store-Backed, but I think we've already decided to use EBS-Backed one, since it's convenient for developers.
We may able to have developer's AMI image and product AMI image, but we haven't decided to have two different types of AMI images yet (I think we have discussed it before, too).

**Comment by tzach** [comment]
thanks @syuu1228, you explained it better than I did.
The problem (and solution) is in the AMI not Scylla.

**Comment by benoit-canet** [comment]
So I don't see how I can make any progress on this one.

**Comment by syuu1228** [comment]
@benoit-canet We should discuss to provide two different AMI images or not. @tzach , is it what we want?
I think we didn't choose that option last time we discuss about it.
If we want keep single AMI image, which means we will not fix this issue.

**Comment by tzach** [comment]
@syuu1228 there is two type of AMI:
1. Amazon EBS-Backed
2. Amazon Instance Store-Backed
Which of them are we using to create Scylla AMI?

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ComponentsAMIs.html#storage-for-the-root-device

**Comment by tzach** [comment]
@slivne any idea how (and if we can) to implement this?

**Comment by slivne** [comment]
we are using the ebs backed one currently - to disable restart we need to use he instance store back one


datastax actually have both - I just checked 
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:
(search for datastax) 

yet at least for me the ebs one is not able to work - its older version and actullay probably something is broken in it.

what we can do is provide to users the instance store backed one - and also generate for our internal usage the ebs backed one (e.g. we will make the instance-store one plubi and the ebs one will be private)

**Comment by tzach** [comment]
Sounds good. 
Look like a Scylla AMI with instance store satisfy the requirement

**Comment by penberg** [comment]
The fix was reverted in https://github.com/scylladb/scylla/commit/11dd20d640d22161994867787dd5b2019b57fde8, so I am reopening the issue.

**Comment by benoit-canet** [comment]
The molly guart was not ok. Changing to instance type is not ok. That does not leave anything.

**Comment by slivne** [comment]
@benoit-canet  why changing to instance type is not ok ?

**Comment by benoit-canet** [comment]
avi said "The patch is wrong too.  Instance store takes 5 minutes to boot
compared to 1 minute for EBS."

and "EBS is persistent"

**Comment by slivne** [comment]
we did not find a way to impl this - AWS is limited
