### ISSUE TITLE
LeveledCompactionStrategy: L1 may overlap 

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1293]
After changing compaction manager to concurrently compact the same column family, level 1 (used by leveled compaction strategy) may overlap.

How the problem happens:
1) compaction id 0: ongoing compaction creating sstable with range a-b at level 1.
2) compaction id 1: ongoing compaction creating sstable with range a-b at level 1.
3) compaction id 0: finished
4) compaction id 1: finished
- After these events, there are 2 sstables at level 1 that overlap.

It doesn't affect correctness (from the system perspective). It's a performance issue because an overlapping sstable created at level 1 is eventually sent back to level 0. So yet another compaction is needed for merging this overlapping sstable into L1.

How to fix it:
Leveled strategy gets uncompacting sstables as candidates, but it's not aware of compacting sstables. 
There's a logic in leveled strategy that is disabled. It's about discarding a L0 candidate that overlaps with a L0 compacting sstable.

**Comment by nyh** [comment]
Interesting. The problem may not be limited to L0 - it might be possible (although unlikely in practice) that while we're compacting a few sstables from L1 to L2, a new sstable in L0 causes compaction into L1, and that new L1 causes another compaction into L2. And there may be another related problem: In leveled compaction, we need to compact several tables from level N with all the tables that intersect with them in level N+1. If some of the latter tables (in level N) are already a part of an ongoing compaction, we also cannot perform the second compaction in parallel.

But I have a doubt whether all of this is necessary: As far as I can see, the whole point of parallel compaction of the same CF was to allow small compactions to start while a very large one is in progress. However, with leveled compaction, we should not have very large compactions - the goal is to always do small compactions, and this is why the huge sstables are split into many sstables inside a "level". So perhaps we can, and even should, simply say that level-compacted CFs should not allow multiple parallel compactions?

**Comment by avikivity** [comment]
Should we have overlapping compactions targeting the same level at all?

**Comment by nyh** [comment]
@avikivity the decision on what to compact in parallel is not based on leveled-compaction "level", but rather on the size of the compaction (sum of input sstables' size).

Because our log base is fairly low (4), it is indeed possible that two compactions will have a 4x size difference and end up being done in parallel, although this should not happen frequently (in steady state, all of leveled compaction's compactions will have close to the same size). If this indeed does not happen frequently (it will happen even less frequently if we increase the base of 4) maybe this problem doesn't need fixing at all. Or perhaps the best fix is just not to do parallel compaction with leveled compaction (as I suggested above).

**Comment by avikivity** [comment]
For leveled compaction, we need  to compact 0->1 when nr_sstables(level = 0) >= k * nr_sstables(level = 1), otherwise the amount of work per user write grows as the amount of data grows.  The "log base" is meaningless for leveled compaction.

We can't disable parallel compaction, because then a compaction at a high level means that the number of sstables at level 0 grows without anything stopping it.  You don't want to wait for a multi-terabyte compaction.

**Comment by nyh** [comment]
On Sun, May 29, 2016 at 11:24 AM, Avi Kivity <notifications@github.com>
wrote:

> For leveled compaction, we need to compact 0->1 when nr_sstables(level =
> 0) >= k * nr_sstables(level = 1), otherwise the amount of work per user
> write grows as the amount of data grows.
>
I didn't understand this statement...
For leveled compaction, we can compact any number of L0 sstables with all
(10) in L1. That's the theory. I don't know what we have in the actual
code, though.

> The "log base" is meaningless for leveled compaction.
>
The "log base" which I mentioned is part of the new logic of deciding which
compactions should be done in parallel (Raphael's patch titled "compaction:
add support to parallel compaction on the same column family" - I don't
know if it went in yet or to which branch...). It has nothing to do with
the similar concept of size-tiered compaction.


> We can't disable parallel compaction, because then a compaction at a high
> level means that the number of sstables at level 0 grows without anything
> stopping it. You don't want to wait for a multi-terabyte compaction.
>
But my point was, that with leveled compaction, you do NOT have
multi-terabyte compactions: All compactions are fairly small, involving
around 14 (?) sstables of a fixed size. You do a lot of small compactions
instead of the huge compactions of size-tiered compaction. This is why I
claim that with leveled compaction we don't need parallelism. If the
current code can figure this out automatically (because the different
compactions are similarly sized) then great; But if it can't because the
base "4" is too low then we can disable the parallelism completely in the
leveled-compaction case.

**Comment by avikivity** [comment]
Well my statement was correct but meaningless.  I forgot some basic facts about lcs.  Since the number of sstables in L1 is fixed, we'll do a fixed about of work when mixing in L0->L1.

If compaction size is fixed, then yes, parallel compaction is the wrong thing to do.

**Comment by raphaelsc** [comment]
On Sun, May 29, 2016 at 6:06 AM, Avi Kivity <notifications@github.com>
wrote:

> Well my statement was correct but meaningless. I forgot some basic facts
> about lcs. Since the number of sstables in L1 is fixed, we'll do a fixed
> about of work when mixing in L0->L1.
>
> If compaction size is fixed, then yes, parallel compaction is the wrong
> thing to do.
>
SStables are fixed size, but compaction may have different size. Example:
L0 may fall behind, and so next L0 compaction may end up being very big.
Compaction of level > 0 is about compacting together one sstable from level
N and all overlapping sstables from level N+1.

For level > 0, compaction manager will probably not allow parallel
compaction because jobs will have similar size. Important to say that this
is decision is outside the scope of the compaction strategy. Compaction
strategy returns a job to compaction manager, and compaction manager checks
if it's good to run this job in parallel, based on its size.

If we decide not to disable parallel compaction for leveled strategy, we
need to filter out sstable that overlaps with a compacting sstable in its
level.


> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla/issues/1293#issuecomment-222350319>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABWAc1awc2ZyIccoNq9xW3Gl-CTsNmMXks5qGVcAgaJpZM4IoplZ>
> .
>



-- 
Raphael S. Carvalho

**Comment by avikivity** [comment]
[detailed-overlap.txt](https://github.com/scylladb/scylla/files/295094/detailed-overlap.txt)

Filtered log.  `pk{...}` was replaced by `pk{token[shard]/...}`, and some noise was removed.
