### ISSUE TITLE
Compaction shouldn't create hard links at backup dir if incremental backup is enabled.

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1308]
Sentence from http://docs.datastax.com/en/cassandra_win/2.2/cassandra/operations/opsBackupIncremental.html: "Compacted SSTables do not create hard links in the backup folder because a snapshot will include links to SSTables that can reconstitute any compacted SSTable."

As a result, no hard link should be created at backup as a result of compaction.

**Comment by raphaelsc** [comment]
@vladzcloudius What do you think?

**Comment by vladzcloudius** [comment]
@raphaelsc Well, first of all since we want to be compatible we have to implement stuff the same way it's defined in the Origin. 

Secondly, note that though it seems strange to backup SStables with tombstones and other crap inside the _incremental_ backup is meant to be fast and simple but not the _main_ backup mechanism. They put it quite clear in the description of the feature in a link u've provided above. The user is supposed to take proper snapshots from time to time, which would take compacted SStables, while incremental backups are only supposed to cover his/her ass during the time in between... ;)

**Comment by slivne** [comment]
@raphaelsc , @vladzcloudius  so what are we doing are we creating hard links to compacted sstables  in the backup directory ?

**Comment by slivne** [comment]
ping @raphaelsc @vladzcloudius

**Comment by raphaelsc** [comment]
On Tue, Jun 7, 2016 at 5:10 AM, Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> , @vladzcloudius
> <https://github.com/vladzcloudius> so what are we doing are we creating
> hard links to compacted sstables in the backup directory ?
>

We are. It's very easy to fix it. @vladzcloudius?


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla/issues/1308#issuecomment-224210079>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABWAc0doremyhlCLX_uG8BlYyjRPcI7Zks5qJSd8gaJpZM4It9TH>
> .
>



-- 
Raphael S. Carvalho

**Comment by vladzcloudius** [comment]
@raphaelsc , @slivne 
Yes, it looks like fixing it is a matter of simply not triggering a backup from a compact_sstables().
I'll send a patch.
