### ISSUE TITLE
Old sstables may be kept indefinitely

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1314]
Consider the following scenario:

1. SSTables are shared among shards (for example, due to an import from Cassandra)
2. Shards are badly imbalanced (for example, due to a low vnode count on the initial system)

In this scenario, the lightly loaded shards will compact very rarely (possibly never).  The heavily loaded shards will compact often, but the compacted sstables will not be released until all shards have compacted them, to prevent data resurrection (see `delete_atomically()`).

**Comment by avikivity** [comment]
Fix could be to initiate a cleanup job on any shared sstables as soon as they are loaded.  The job would run only on shards actually sharing the sstables, and avoid the ranges check that the regular cleanup job uses.

**Comment by nyh** [comment]
Avi, when you mentioned "cleanup", rather than "compaction", I wonder if you really wanted the extra work of a cleanup job, i.e., to remove not only data not belonging to this shard, but also data not belonging to this node? 
Is there a downside to do cleanup, not compaction? Does anyone reading this know why Cassandra doesn't do the "cleanup" work on every compaction - and if it doesn't, maybe we also shouldn't do a cleanup without a user's request?

**Comment by slivne** [comment]
From their blogpost - personally I really am not sure this has any hold in reality 

http://www.datastax.com/dev/blog/common-mistakes-and-misconceptions

_Cleanup’s job is to scan all the data on a node and throw out any data that is no longer owned by that node. “Why would a node have data that it doesn’t own?” you ask. Well this can happen when you change the topology of a cluster (add, move, or remove nodes). When this happens some nodes give up, or add to their range ownership. When ranges are given up the data is not automatically deleted. It sticks around until we explicitly tell Cassandra to clean itself up. **This omission is intentional, and can help to prevent data loss in the case that a newly introduced node fails soon after bootstrapping.**_

the biggest issue with that is that the data that is on the original node is obsolete may not be up to date and may have been updated already / removed.

**Comment by nyh** [comment]
So by this logic, we really do need to use regular compaction, not cleanup (i.e., not delete data not belonging to this *node*). The user will need to do an explicit "cleanup" operation, if and when he chooses - it shouldn't happen by default just because we happened to reboot in a machine with different number of cores.

**Comment by avikivity** [comment]
I think you are right, unfortunately.
