### ISSUE TITLE
Move logging command line parameters to seastar

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1326]
Since the logging framework is now part of seastar, it makes sense to add logging command line parameters to seastar's app_template.

**Comment by hakuch** [comment]
I'd like to try taking this on.

**Comment by hakuch** [comment]
One small problem is that if the logging CLI options are present in Seastar then they will be duplicated in Scylla. We cannot update both Seastar and Scylla atomically (since they're different repositories), so my plan is to add optional (default off) support for CLI parameters in Seastar, then remove Scylla's support and enable the Seastar CLI options, then finally make it default in Seastar.

**Comment by penberg** [comment]
https://github.com/scylladb/seastar/issues/292 is now closed so can we also close this, @tgrabiec?
