### ISSUE TITLE
Compaction not able to keep up with stress

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1369]
Scylla version (or git commit hash): scylla-server-1.2.0-20160614.c384b23.el7.centos.x86_64
Longevity setup

Load

```
cassandra-stress write duration=24h -mode cql3 native -pop dist=uniform(1..10000000) -schema compaction(strategy=LeveledCompactionStrategy) -node 10.0.4.131 -col size=FIXED(2048) n=FIXED(5)
```

please note threads was not set - so this workload was run more then once
2 servers centos
1 server ubuntu 

we ran out of disk space  (each with 1.5 T of disk in /var/lib/scylla) although the workload is 10M \* 10 K ~ 100G  (and since I had a mistake with replication - each should have only 30G)

is backpressure at fault ?

**Comment by avikivity** [comment]
Right now there is no feedback loop.  In addition, compaction and sstable writes have equal shares, but compaction has more work to do (it needs both reads and writes vs. just reads, and it needs to compact each mutation several times as it moves up the size tier).

The way it should work is:
 - compaction generates a measure of its backlog
 - its shares increase as the backlog increases

the backlog should be something like sum(tier N sstable/memtable input bytes - tier N sstable compaction consumed bytes), for all N, so that in a steady state, with memtable size increasing but compaction consumed bytes also increasing at the same rate, backlog is constant and shares need not adjusted.  If memtable bytes increase faster then sstables are consumed, then the backlog will increase and compaction will run faster.

**Comment by avikivity** [comment]
I've just seen another instance of this. 30 shards, >4400 sstables, compaction spends all its cpu time looking at those sstables.  So compaction is getting slower, because it's not keeping up, so it's even harder for it to keep up.  We must fix this soon.

**Comment by nirmaayan** [comment]
Issue happens also on EC2
3 * i2.8xlarge with 14 c4.large loaders.
Running large load using [test and deploy](https://github.com/scylladb/cassandra-test-and-deploy) ansible command:
./ec2-stress.sh 1 -e "server=Scylla" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_write" -e "threads=2500" -e "command_options='cl=QUORUM n=4000000000 -mode native cql3 -pop seq=1..4000000000'"

bloom filter reach 9-10%~
sstable count is 2500~
nodetool compactionstat disply 60-70 compaction in progress 
Load runs for 6~ hours

**Comment by tzach** [comment]
Is this issue a result #1322 ? and if so, can we close it?

**Comment by slivne** [comment]
I am sure #1322 - that is only partially resolved will help - yet the other
parts related to this are not resolved

The main item related to this is using dynamic shares instead of the static
shares we currently have between the io related components.

**Comment by tzach** [comment]
@slivne maybe you should open an issue for using dynamic shares so we can track and fix it

**Comment by slivne** [comment]
@glommer did you send a patch for this on the list ?

**Comment by glommer** [comment]
On Mon, Aug 29, 2016 at 8:16 AM, Shlomi Livne <notifications@github.com>
wrote:

> @glommer <https://github.com/glommer> did you send a patch for this on
> the list ?
>

No, I don't have working code for dynamic shares yet.

**Comment by glommer** [comment]
dynamic shares now work.
