### ISSUE TITLE
system tables should not be compared / repaired via repair

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1380]
The default of running repair without specifying keyspace / table is to run on all keyspace and tables. 

It seems that we do at least some steps toward running a repair (even if at the end nothing is done)

```
INFO  2016-06-22 17:43:12,820 [shard 0] repair - repair 2 completed sucessfully
INFO  2016-06-22 17:43:13,670 [shard 0] repair - starting user-requested repair for keyspace system, repair id 3, options {dataCenters=dc1, incremental=false, parallelism=0, primaryRange=false}
INFO  2016-06-22 17:43:13,671 [shard 0] repair - [repair #a5ea3970-3887-11e6-8171-000000000000] new session: will sync {} on range (-inf, -9140734797772826062] for system.{size_estimates, sstable_activity, compaction_history, compactions_in_progress, range_xfers, peer_events, peers, schema_columnfamilies, hints, schema_triggers, schema_keyspaces, schema_usertypes, schema_columns, batchlog, paxos, IndexInfo, local}
INFO  2016-06-22 17:43:13,671 [shard 0] repair - [repair #a5ea3971-3887-11e6-8171-000000000000] new session: will sync {} on range (-9140734797772826062, -9133808204713790199] for system.{size_estimates, sstable_activity, compaction_history, compactions_in_progress, range_xfers, peer_events, peers, schema_columnfamilies, hints, schema_triggers, schema_keyspaces, schema_usertypes, schema_columns, batchlog, paxos, IndexInfo, local}
INFO  2016-06-22 17:43:13,671 [shard 0] repair - [repair #a5ea3972-3887-11e6-8171-000000000000] new session: will sync {} on range (-9133808204713790199, -9078200486527824554] for system.{size_estimates, sstable_activity, compaction_history, compactions_in_progress, range_xfers, peer_events, peers, schema_columnfamilies, hints, schema_triggers, schema_keyspaces, schema_usertypes, schema_columns, batchlog, paxos, IndexInfo, local}
INFO  2016-06-22 17:43:13,671 [shard 0] repair - [repair #a5ea3973-3887-11e6-8171-000000000000] new session: will sync {} on range (-9078200486527824554, -9048320742900589363] for system.{size_estimates, sstable_activity, compaction_history, compactions_in_progress, range_xfers, peer_events, peers, schema_columnfamilies, hints, schema_triggers, schema_keyspaces, schema_usertypes, schema_columns, batchlog, paxos, IndexInfo, local}
INFO  2016-06-22 17:43:13,671 [shard 0] repair - [repair #a5ea3974-3887-11e6-8171-000000000000] new session: will sync {} on range (-9048320742900589363, -9023524321825930738] for system.{size_estimates, sstable_activity, compaction_history, compactions_in_progress, range_xfers, peer_events, peers, schema_columnfamilies, hints, schema_triggers, schema_keyspaces, schema_usertypes, schema_columns, batchlog, paxos, IndexInfo, local}
.
.
.

```

to be clear - system tables are local to each node and should not be compared/repaired like regular sstables.

**Comment by nyh** [comment]
This problem is benign (doesn't cause any harm) because they "system" keyspace has no replication, so repair would do nothing on it, but I agree it's interesting to check *why* in Cassandra the "system" keyspace is never repaired.

Scylla's repair code takes a specific keyspace to repair. The code which lists the keyspaces (and erroneously lists also "system") is in "nodetool repair" , which in Cassandra 2 calls (see tools/NodeTool.java) `nodeProbe.getNonSystemKeyspaces()`.

The bug is in the way we implement this JMX request, in the scylla-jmx project:
```java
    public List<String> getNonSystemKeyspaces() {
        log(" getNonSystemKeyspaces()");
        return c.getListStrValue("/storage_service/keyspaces");
    }
```

This is wrong: it lists all the keyspaces, and doesn't skip the "system" one.

@amnonh will fix this bug in scylla-jmx.

**Comment by nyh** [comment]
@amnonh discovered that in the NodeTool.java version that we're stuck on, the nodetool code is actually slightly different from what I mentioned above, and `parseOptionalKeyspace()` always calls nodeProbe.getKeyspaces(), **not** getNonSystremKeyspaces().

So with our nodetool, this bug cannot be fixed, and repair **will** be given the "system" keyspace, and will simply have to ignore it.

Since we're already ignoring it, we can perhaps close this issue. Alternatively, if you want me to skip non-replicated keyspaces more quickly (without bothering to iterate over tables, ranges, etc.) let me know and I can fix that.

**Comment by tzach** [comment]
This issue might be solved once we bump up the nodetool version

**Comment by elcallio** [comment]
As of cassandra 3.x, nodetool repair without KS will query all keyspaces with non-local strategy, which excludes "system".

**Comment by elcallio** [comment]
I.e. can close this.
