### ISSUE TITLE
Optimize leveled compaction

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1427]
_Installation details_
Scylla version (or git commit hash): 1.3

We can use sstable_set to construct a joining reader from sstables that are disjoint, so combining_reader needs to consider fewer sstables.

**Comment by nyh** [comment]
Good idea (I thought we already had such an issue, but apparently we did not).

Note that if I understand correctly, one of the main benefits of this idea (if not the only benefit) is reducing memory use during the compaction - because we will not need to keep in memory the first mutation of each of the (disjoint) sstables like we do now. This was mostly a problem in scenarios with very large partitions. However, once the compaction code uses mutation fragments (I believe it already does), we only keep in memory around one buffer (128 KB) per sstable, so the saving with this issue fixed will not be huge. But I guess every megabyte counts.

**Comment by avikivity** [comment]
It also changes compaction from O(log N) to O(log much smaller N)

**Comment by nyh** [comment]
Avi, I think you are overstating that last benefit:

1. The "N" in your formula isn't the size of the sstables or data or anything big - it is the number of sstables being compacted together. For leveled compaction strategy, this is normally around 12, so log N and log log N (your "log much smaller N") are not very different. We never compact thousands of sstables together!

2. The part your formula measures the complexity of is the performance of the heap used to chose the next partition to merge. This is probably the fastest part of the compaction anyway, so speeding only this part up will hardly be noticable.

**Comment by avikivity** [comment]
It's still nice to do 1 comparison instead of 4.  And if the partitions are small and simple (one column), it has more effect.  So it would be good for a key/value schema.

**Comment by avikivity** [comment]
Most sstables will be in L1+, so we save a lot.  We might have a few sstables in L0, and thousands elsewhere.

**Comment by slivne** [comment]
The issue is that L0 sstables can cover the complete range (min/max key)
with two inserts - they are not split not to overlap.

If we are using bloom filter info - prior to constructing the reader then
it may kmake sense since L0 files will probably be dropped by the bloom
filter.

**Comment by avikivity** [comment]
So L0 tables don't benefit; but L1+ do.

I don't understand the second comment.

**Comment by slivne** [comment]
On Tue, Jul 5, 2016 at 6:00 PM, Avi Kivity <notifications@github.com> wrote:

> So L0 tables don't benefit; but L1+ do.
>
I don't understand the second comment.
>

If we are creating the reader for a specific partition key (or range) - by
checking the bloom filter prior to creating the reader we will be able  to
shorten the list of sstables we are using to build the reader.

**Comment by denesb** [comment]
Isn't this the same as #1935? If yes shouldn't this be closed as well?

**Comment by avikivity** [comment]
Fixed by #1935 solution.
