### ISSUE TITLE
Reduce rate of segment heap reballancing in LSA by using approximate occupancy measure

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1442]
Segments in LSA are ordered in a heap by occupancy so that they are later compacted starting from sparsest segments, which is most effective. The occupancy changes on each free, forcing us to update the heap. Since the cost of segment compaction rises exponentially with occupancy, the order matters less for low occupancy segments. We could use approximate occupancy measure for ordering segments with increased precision towards higher occupancy. The measure would need to change less often and thus we would have to rebalance less.

**Comment by belliottsmith** [comment]
Why maintain a heap at all, instead of a histogram? Even 100 linearly spaced buckets would give you 1% accuracy for the decision, which is surely good enough?  The same approach to decaying accuracy could be imposed to reduce the number of buckets, or raise the accuracy where it counts.

It's possible to maintain a linked-list of the buckets that have entries, and the members of each bucket, in constant time.

This is how I dealt with it when I wrote a compacting LSA, anyway, which was admittedly much more primitive than yours.

**Comment by duarten** [comment]
We can do something like HdrHistogram does, where there's an initial bucket containing a number of sub buckets that are linearly spaced, and then a set of other buckets, representing a power-of-2 range, with a number of sub buckets each. This allows higher precision for the initial sub buckets and decaying precision for the remainder of them. In code:

```c++
#include <x86intrin.h>
#include <iostream>
#include <limits>

constexpr int segment_size_shift = 18; // 256K
constexpr size_t segment_size = 1 << segment_size_shift;
using size_type = uint32_t;

constexpr size_type initial_buckets_shift = 4;
constexpr size_type initial_buckets = 1 << initial_buckets_shift;

constexpr size_type sub_buckets_shift = 2;
constexpr size_type sub_buckets = 1 << sub_buckets_shift;

constexpr size_type number_of_buckets = ((segment_size_shift + 1) - initial_buckets_shift) * sub_buckets;

template<typename SizeType>
struct lzcnt {
    SizeType operator()(SizeType x);
};

template<>
struct lzcnt<uint32_t> final {
    uint32_t operator()(uint32_t x) {
        return __lzcnt32(x);
    }
};

template<>
struct lzcnt<uint16_t> final {
    uint16_t operator()(uint16_t x) {
        return __lzcnt16(x);
    }
};

size_type bucket_of(size_type free_space) {
    // Calculate the number of powers of 2 by which free_space is bigger than the biggest
    // value that fits in the initial set of buckets, given by the number of trailing zeros.
    // Each successive bucket can hold a value 2x greater than the previous one.
    constexpr size_type initial_mask = 1 << initial_buckets_shift; // To help do std::max(free_space, 2^initial) below.
    const auto bits = std::numeric_limits<size_type>::digits - 1 - lzcnt<size_type>()(free_space | initial_mask);
    const auto bucket_index = bits - initial_buckets_shift;

    const auto shift = bits - sub_buckets_shift; // Don't shift away top sub_buckets_shift bits.
    const auto sub_bucket_index = free_space >> shift;

    return (bucket_index << sub_buckets_shift) + sub_bucket_index;
}
```

For 16 initial buckets and 4 sub buckets for each power-of-2, we get a distribution like the following, which maps free space in bytes  to a particular bucket:

```
0 -> 0
4 -> 1
8 -> 2
12 -> 3
16 -> 4
20 -> 5
24 -> 6
28 -> 7
32 -> 8
40 -> 9
48 -> 10
56 -> 11
64 -> 12
80 -> 13
96 -> 14
112 -> 15 -- end initial sub buckets
128 -> 16
160 -> 17
192 -> 18
224 -> 19 -- end range with 4 sub buckets
...
1024 -> 28
1280 -> 29
1536 -> 30
1792 -> 31 -- end range with 4 sub buckets
...
32768 -> 48
40960 -> 49
49152 -> 50
57344 -> 51 -- end range with 4 sub buckets
...
131072 -> 56
163840 -> 57
196608 -> 58
229376 -> 59
```

We can vary the `initial_buckets_shift` parameter to add precision to the initial set of buckets, and decrease the `sub_buckets_shift` parameter to decrease precision for the remainder set of buckets.

Calculating the new bucket for a segment is plenty fast, and then we can just unlink from a bucket's intrinsic list into another's.

I can prepare a patch if you think this is worth it.

**Comment by belliottsmith** [comment]
It's worth bearing in mind that the histogram approach has a fixed cost of N for all segments (assuming all frees are smaller than (segment size)/N), so keeping the number of segments small is preferred.  

A heap has better best case costs - it could be that it never has to reorder the heap.  Obviously this is very unlikely.  Its worst case is much worse at {frees * lg (segment count)}

But, anyway, the point of this statement is that there are other variables to tradeoff not yet considered.  The most important is the cost per compaction (the whole point of maintaining the heap).  Since individual frees will likely be more common than compactions, sharing the burden between frees and compactions could be helpful.

There is the option of incrementally processing the state of the segments batch-wise when a compaction occurs.  As an example, say there were only a small number of buckets that were maintained on free.  This would make the cost per free extremely low.  It would also constrain the state space a compaction operation needs to consider, as it only cares about the smallest bucket.  

For sparse buckets it does not perhaps care about the order, and can process them as it encounters them.  

For dense buckets, it could look at a percentage of the head of the list (which, on average, would expect to be sparser than the tail which were added later) and either sort of bucket to a finer granularity this prefix.  Each new compaction can step forwards in the list a little, while also walking over the sparsest of these more granular buckets.  Each time the number of items to be consulted can be bounded, and the whole process terminated as soon as a sparse enough segment to process is found.

This would permit paying the higher costs only when necessary, i.e. when memory pressure is high, while also keeping those costs manageable at that time.

Of course another alternative (or, also, potentially usable in conjunction) is to dynamically change the granularity of your buckets as memory pressure / bucket occupancy increases.  But this might have a larger impact on the cost of free, which is frequent.

**Comment by duarten** [comment]
On Fri, Aug 5, 2016 at 11:28 AM, Benedict Elliott Smith <
notifications@github.com> wrote:

> It's worth bearing in mind that the histogram approach has a fixed cost of
> N for all segments (assuming all frees are smaller than (segment size)/N),
> so keeping the number of segments small is preferred.
>
> A heap has better best case costs - it could be that it never has to
> reorder the heap. Obviously this is very unlikely. Its worst case is much
> worse at {frees * lg (segment count)}
>
The approach I posted has a very small fixed cost; it doesn't even have
branching. I really think we can dispense with the heap.

> But, anyway, the point of this statement is that there are other variables
> to tradeoff not yet considered. The most important is the cost per
> compaction (the whole point of maintaining the heap). Since individual
> frees will likely be more common than compactions, sharing the burden
> between frees and compactions could be helpful.
>
The spectrum as I see it goes from incrementally compacting on free (which
is horrible, because of the cost and because we'd be moving objects around
too much and also compacting objects that would be freed right afterwards)
to free not doing anything, with all segments sitting on an unordered list.

> There is the option of incrementally processing the state of the segments
> batch-wise when a compaction occurs. As an example, say there were only a
> small number of buckets that were maintained on free. This would make the
> cost per free extremely low. It would also constrain the state space a
> compaction operation needs to consider, as it only cares about the smallest
> bucket.
>
I'm a bit weary of shifting too much of the cost towards compactions
though, which can be triggered in an emergency state. A free with a low
enough cost, but that is able to lay things nicely for compaction to not
have much extra work is a good compromise, I think.

For sparse buckets it does not perhaps care about the order, and can
> process them as it encounters them.
>
> For dense buckets, it could look at a percentage of the head of the list
> (which, on average, would expect to be sparser than the tail which were
> added later) and either sort of bucket to a finer granularity this prefix.
> Each new compaction can step forwards in the list a little, while also
> walking over the sparsest of these more granular buckets. Each time the
> number of items to be consulted can be bounded, and the whole process
> terminated as soon as a sparse enough segment to process is found.
>
I think this makes sense regardless of the number of buckets. If we
encounter a dense bucket mapping to an occupancy >= X%, we may wish to sort
them; maybe we could do it in strides of k segments, assuming that a) the
first batch will contain the segments from which we freed most recently;
and b) objects allocated together tend to be freed together, so these are
segments from which we've been freeing for a _while_.

> This would permit paying the higher costs only when necessary, i.e. when
> memory pressure is high, while also keeping those costs manageable at that
> time.
>
> Of course another alternative (or, also, potentially usable in
> conjunction) is to dynamically change the granularity of your buckets as
> memory pressure / bucket occupancy increases. But this might have a larger
> impact on the cost of free, which is frequent.
>
I think the granularity should be tuned for when there's memory pressure,
as that's when we'll want to compact the denser segments. If we're
compacting due to the system being idle, then I think we can spare some
more cycles.

**Comment by belliottsmith** [comment]
First I'd like to clarify that I don't mean to imply the approach is not ready to replace the heap.  With or without your specific suggestion for list segregation, I think it is likely superior.  However there is likely better, definitely better, and materially better.

> The approach I posted has a very small fixed cost

I'm not worrying about CPU costs here - it's pretty trivial to construct a number of segregations that are cheap to calculate.  The question is how likely are we to incur a random fetch from memory or TLB miss.  The larger the number of lists, the more likely this is - and also the more often we would incur them if they are (since we transition more often).  Now, you didn't specify how many lists you want, but it looked like in the region of the hundred or so I initially threw out there as a baseline.  Assuming this, we can definitely rule out an L2 hit for the data, and unless you have huge pages very likely a TLB miss as well.  If you can guarantee to encounter this 100 times per freed block, that might be material.

Of course, the heap incurs a more likely miss with every free.  So we're still better, so long as we have small allocations (allocations that are larger than our list granularity can be freed more cheaply).

Anyway, the intellectual exercise is if this can be avoided entirely.  Let's say instead we have two tiers of list, and by default a free updates only the top tier of this list - this would cut the number of updates on free to the sqrt of the total granularity, and more importantly cut the working set by the same amount.  This makes a L2 (even L1) and TLB hit quite likely.

Then, to improve our overall behaviour, we nominate one tier to be the sparsest tier, and this tier we inflate during compaction.  We *also* maintain *this tier only* during free.  This only doubles the working-set size, while keeping the frequent operations for those blocks that may actually be useful for.

> I'm a bit weary of shifting too much of the cost towards compactions
> though, which can be triggered in an emergency state.

If the system is faster at a steady state, the emergency should be harder to reach though (assuming no bugs)...?  Anyway, I'm not suggesting shifting the cost entirely, just that by spreading the cost the *overall* cost can be reduced, perhaps significantly.  These costs to be incurred by compaction will still be a fraction of the cost of actually compacting dense blocks, which are the emergency situation.  So if that fraction is ever the difference between success/failure, you've already lost 9 times out of 10.

**Comment by belliottsmith** [comment]
That said, I hadn't actually thought too much about the structure itself.  If the linked-list nodes were allocated inside of a struct, a single 4Mb page could manage 1Tb of 4Mb blocks of memory.  So TLB misses would not be an issue.  The prev pointer of any node we have to dereference and may be random, and that is unavoidable.  The head node is the only possibly random dereference we can avoid, but that will be less random than the prev pointer, so it is probably overkill to worry about it.
