### ISSUE TITLE
Heat weighted load balancing

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1455]
Load-balance read queries (with CL<ALL) among nodes based on their heat (recent cache hit rate).

This allows a node that is cache-cold (due to a restart) to gradually start shouldering more and more load, instead of taking a 100% load hit immediately after restart and giving poor service due to a cold cache.

Hit rate tracking might be done per node, per keyspace-node, per cf-node, and per prepared-statement-node.  Temperature updates can be piggy backed on read request responses.  A node that is disconnected gets its temperature adjusted to zero.

**Comment by vladzcloudius** [comment]
On Jul 13, 2016 23:54, "Avi Kivity" <notifications@github.com> wrote:
>
> Load-balance read queries (with CL<ALL) among nodes based on their heat
(recent cache hit rate).
>
> This allows a node that is cache-cold (due to a restart) to gradually
start shouldering more and more load, instead of taking a 100% load hit
immediately after restart and giving poor service due to a cold cache.
>
> Hit rate tracking might be done per node, per keyspace-node, per cf-node,
and per prepared-statement-node. Temperature updates can be piggy backed on
read request responses. A node that is disconnected gets its temperature
adjusted to zero.

I think this may be a heuristics to a dynamic snitch, while a dynamic
snitching should be able to achieve the ultimate goal described above even
without the "heat map", since the Node with a cold cache would serve the
requests slower thus would get a lower score.

**Comment by tzach** [comment]
@gleb-cloudius did this made it into 1.7?

**Comment by gleb-cloudius** [comment]
On Mon, Feb 13, 2017 at 10:44:16PM -0800, Tzach Livyatan wrote:
> @gleb-cloudius did this made it into 1.7?
> 
no.

--
			Gleb.

**Comment by avikivity** [comment]
Fixed by 87094849faa07f4ad93b43a4fc55a53009d27fbc
