### ISSUE TITLE
loosing mutation when node boots up and connects to a cluster 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1467]
*Installation details*
Scylla version (or git commit hash): 1.2.1

booting up a node while there is a load running will throw the following errors

```
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 20] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 14] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 15] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 10] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 19] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 15] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 10] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 4] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 17] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 7] rpc - client 172.30.0.12: unknown verb exception 1 ignored
11:43:36 DEBUG| [52.87.179.215] [stdout] Jul 17 08:43:36 ip-172-30-0-11 scylla[2783]:  [shard 7] rpc - client 172.30.0.12: unknown verb exception 1 ignored
.
.
```

according to @avikivity  "we should register the handlers and open rpc only afterwords"

(reproduce https://github.com/scylladb/scylla/issues/1466)

**Comment by gleb-cloudius** [comment]
It already supposed to be this way since we start listening in storage_service::init_server() [1] and it is called after registering storage proxy verbs. @asias did recent gossiper change broke it?

The question is if delaying listening is enough? Is it OK to process mutations before gossip brought the node up? 

[1] https://groups.google.com/forum/#!msg/scylladb-dev/KYBljPX32Xo/3LCe_KkxAgAJ

**Comment by asias** [comment]
Note: the patch delays ms listening is not backported in 1.2.1. You were testing scylla 1.2.1, no?

commit f27e5d2a68ead42031063a67722117bf992c7a60
Author: Asias He <asias@scylladb.com>
Date:   Thu May 26 09:20:44 2016 +0000

    messaging_service: Delay listening ms during boot up

**Comment by asias** [comment]
@gleb-cloudius I don't think recent gossip change will break this. We do gossip shadow round in more places for gossip feature check but it should not change the fact that ms starts to listen only after mutation verbs and gossip verbs are registered. Before gossip bring the node up, the other nodes are supposed not to see this node at all. One exception is that, the node was up and and it was down, before peer node notice the node was down, peer node sent mutation to this node.  At the very point, the node restarts. I think we are safe to ignore the mutation in this case (and indeed we are ignoring the verb since the ms is not listening ), as if this node was still down.

**Comment by slivne** [comment]
@asias yes I was testing 1.2.1 - ok when we run the tests for 1.3 - I'll try and see if this does not reproduce

**Comment by asias** [comment]
OK.

**Comment by asias** [comment]
@slive Can we close this issue now? I think "unknown verb exception" issue is already fixed and you just tested the old version 1.2.1 which did not have the fix.

**Comment by asias** [comment]
@slivne ping

**Comment by slivne** [comment]
verified on 1.4-rc2
