### ISSUE TITLE
incorrectly write  when commitlog_sync is 'batch'

### ISSUE THREAD

**Issue by yijiangnan23** [scylladb/scylla#1490]
when commitlog_sync mode is 'batch', we send more than one request to commitlog. we find that if commitlog-sync throws exception, only one request catch the exception, the other requests are return ok.
we think that if sync_commitlog throws exception,  all the write-request should catch the exception, when more than one requests are batch committed.

**Comment by elcallio** [comment]
If I understand the issue correctly, your are (correctly) pointing out that the (latest) commit log batch-mode code will propagate a disk write/flush exception to the mutator continuation chain that did the actual sync, but not the ones that might have added data to the buffer being written, but only get to wait for the IO to finish. 
I agree that this is less than perfect, but it might also be argued that in Origin, a disk write/flush error will not generate an exception in the mutator path at all, but only be visible in the commit log background thread, and propagate to "CommitLog.handleCommitError", which will most likely kill the process. 
So it could be argued that we should in fact not allow the exception to escape at all, but instead be consistent with origin. 
At the very least, a segment that gets a (non-recoverable) disk error should probably be immediately marked as bad and closed.

**Comment by avikivity** [comment]
If origin has a similar bug, that doesn't excuse us.

Won't a shared_future<> fix things up here? write the error once, it gets propagated to all callers.

**Comment by elcallio** [comment]
I would not say that the origin behaviour is a bug. It is a design decision. Bad or not, is beside the point, but what I'm saying is that a commit log disk error is, unless it is immediately recoverable, probably pretty bad and Origins default approach of handling it by stopping all transports and _not_ acknowledge the write as finished might be a better way to handle it. 

Or, as I also wrote, at least discard the segment from any further writes. 

Btw, propagating the error to all pending mutators might be wrong also, since a disk write _might_ be partially successful, and thus we could say to a writer "you failed", yet have the mutation in the commit log. Then, should a restart+replay happen, the mutation would be applied even though we said it was not. Of course, saying nothing does not particularly help, but at least it is not lying.

**Comment by gleb-cloudius** [comment]
On Tue, Jul 26, 2016 at 05:24:44AM -0700, Calle Wilund wrote:
> I would not say that the origin behaviour is a bug. It is a design decision. Bad or not, is beside the point, but what I'm saying is that a commit log disk error is, unless it is immediately recoverable, probably pretty bad and Origins default approach of handling it by stopping all transports and _not_ acknowledge the write as finished might be a better way to handle it. 
> 
> Or, as I also wrote, at least discard the segment from any further writes. 
> 
> Btw, propagating the error to all pending mutators might be wrong also, since a disk write _might_ be partially successful, and thus we could say to a writer "you failed", yet have the mutation in the commit log. Then, should a restart+replay happen, the mutation would be applied even though we said it was not. Of course, saying nothing does not particularly help, but at least it is not lying. 
> 
Applying mutation and saying we did not happens when CL is not achieved.
This is normal occurrence for C*/S*.

--
			Gleb.

**Comment by avikivity** [comment]
A failure in C* is "we can't guarantee it was committed", not "it was not committed".  For example, we might have hit one replica but failed on the others, so the operation failed, even the write will eventually be propagated to all nodes.

I think we should, in this case, have a "yes means yes" policy.

**Comment by elcallio** [comment]
Btw, if we (or Origin) is running in periodic mode, all bets are completely off regarding whether reporting a mutation successfully persisted in commit log was actually true, since we could have X writes going on at various disk positions and any of them could be the IO that broke the camels SSD. 

In batch mode, we could just truncate the segment file to last know good size and then signal disk error for all the pending mutators.

**Comment by avikivity** [comment]
Agree about periodic.  We should supply batch as an option to those who care more about their data (and maybe less about write latency.

**Comment by tzach** [comment]
@elcallio what is the status of this issue?

**Comment by elcallio** [comment]
Patches are on the list.
