### ISSUE TITLE
LSA compaction on idle may report there is more work but not make any progress

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1554]
Scylla version: >= 1.2.0

Noticed by @avikivity. If segments have objects (could be manged_bytes fragments) with sizes between ~`(1-max_occupancy_for_compaction_on_idle) * segment::size` and `max_managed_object_size` (17.9KiB - 25.6KiB), we may be closing segments with waste at the end resulting in occupancy below idle compaction threshold and cause compaction to think there is always some work to do although it may never be able to reclaim that free space.

**Comment by avikivity** [comment]
With my patch to make use of all available space in a segment for managed_bytes, and with additional logic to break up fragments if we're moving them to a segment with less free space than the fragment size, and with a magic way to prevent all that from fragmenting a managed_bytes object too much, this could work with a larger `max_occupancy_for_compaction_on_idle`.

Maybe we should just refuse to use less than (say) 1kB for a non-terminal chunk.  This would give relatively good packing.  Losses due to occupancy = 0.25%, losses due to chunk overhead = (lsa header) + (chunk overhead) =~ 24 bytes = 0.25%.

**Comment by avikivity** [comment]
compaction on idle was disabled, so this is outdated. We need to rethink on-idle work.
