### ISSUE TITLE
Unable to add node to cluster on AWS

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1584]
*Installation details* AWS 
Scylla version (or git commit hash): ami-09a63a1e -RC2
Cluster size: 3 + 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos t2.micro

Trying to add new node to cluster without GUI
Steps:
SSH to the new node
Stop scylla node
Delete /data/* and /commitlog/* folders
Edit seeds address 

> /etc/scylla/scylla.yaml

 with the cluster seed address
Start scylla node
After the service starts I can't access cqlsh 
Trying to cqlsh from the problematic node to other node in the cluster works
cqlsh 172.30.0.243 (for example)

Please change the extension from .txt to .pcap
[boot (copy).txt](https://github.com/scylladb/scylla/files/418062/boot.copy.txt)

**Comment by tzach** [comment]
@nirmaayan maybe its connectivity between the new nodes and the cluster, for example, different security group.
anything in journalctl?

**Comment by nirmaayan** [comment]
@tzach - first thing I checked, all of them in us-east-1b and with same security group

**Comment by slivne** [comment]
@asias ... feeling in the dots since I looked at this as well.

1. The test started from a 3 node cluster. on AWS using the AMI
2. 1 node was added succesfuly (boot ami, stop scylla, remove commitlog/data, edit scylla.yaml - place seed, boot scylla)
3. nodetool status shows 4 nodes UN
4. Trying add another node fails (in the same manner)
- checked connectivity
- openned debug logs on seed (nothing with the ip except for rpc connection closed when we stop the new node)
- disabled internode_compression in scylla.yaml
- stop node
- ran wireshark on both to check what is transferred 
- start node

capture is attached.

**Comment by nirmaayan** [comment]
Problem was that cluster name was different - cluster_name:

>  'scylla-cluster-test' /etc/scylla/scylla.yaml

Change it solved the problem
We need better warning message in journalctl

**Comment by dorlaor** [comment]
Please open a new issue (with the exact details and original logs) for it
and close this one

**Comment by penberg** [comment]
@dorlaor That's what he already did. See the referenced issue just above your comment :-)
