### ISSUE TITLE
repair streams data to nodes even when it shouldn't

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1617]
*Installation details*
Scylla version (or git commit hash): 1.3 

Scenario:
1. Cluster of 3 nodes 
2. Data is populated with RF=3 and CL=ALL
3. node3 is shutdown
4. node3 data & commitlog is erased
5. node3 start
6. node3 run nodetool repair

```
ccm create scylla-3 --scylla --vnodes -n 3 --install-dir=
ccm start
ccm node1 stress write n=100000 cl=all -mode cql3 native -schema "replication(strategy=SimpleStrategy,factor=3)" 
ccm node1 flush
ccm node2 flush
ccm node3 flush
ccm node3 stop
rm -Rf ~/.ccm/scylla-3/node3/data/*
rm -Rf ~/.ccm/scylla-3/node3/commitlogs/*
ccm node3 start
ls ~/.ccm/scylla-3/node1/data/keyspace1*/standard1*
ccm node3 nodetool repair
ls ~/.ccm/scylla-3/node1/data/keyspace1*/standard1*
```

found by @noamha

**Comment by nyh** [comment]
Can you please explain what the problem is? You removed all the data from a node, so obviously repair *should* need to send data.

If you're wondering about why the broken node is sending data to the other nodes, well, the thing is that repair works in node pairs: node3 compares its data in a particular range with both node1 and node2. It sees it differs in both. So it asks for data from both node1 and node2, and sends the combined data to both. The last step is necessary, because repair repairs not only the specific node asked to be repair (node3) but also all replicas of the data being repaired.

We could optimize things in this case if node 3 notices that the data on node 1 and node 2 have identical checksums - in which case we can fetch data only from one of them, and not send data back. This optimization won't work if node 1 and node 2 differ.  Was this the kind of optimization you expected?

By the way, I think right now an even more fundamental optimization is missing: Even if we have RF=2 and we copy data into an empty node, after receiving the data in the range, we send it back to the node that sent it to us. That is quite useless.

**Comment by slivne** [comment]
thanks @nyh 

1) In cassandra this does not happen - is that because they are using the merkle tree and only then ask - streem data if needed ? do they do the comparison

2) Yep I think we should do the comparison of the checksums and in case they are the same (currently in case of RF=3 and in the scenario I listed - each partition is sent 4 times)
- we can know not to send the info to other replica nodes (this will drop the count of sending each partition to 2)
- we can ask only one like you suggested (this will drop the count to 1 - we can do that as a second step - I am not sure cassandra has this optimization - do they ?).
