### ISSUE TITLE
Build with -O3

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1644]
@pdziepak saw misoptimizations at -O2 due to bad inlining decisions.  Rather than sprinkle `[[gnu::always_inline]]` everywhere we can level up and use -O3.

**Comment by pdziepak** [comment]
`-O3` alone might not help. True, it does add `-finline-functions`, but it doesn't appear to change inlining heuristics (at least according to gcc documentation) while the point of `always_inline` is to bypass these heuristics. We could add some flags that would tune the gcc willingness to inline functions, but that seems to be much more fragile solution that sprinkling attributes.

**Comment by pdziepak** [comment]
I did some quick tests with `perf_simple_query` using `-O3` and two flags that make GCC much more adventurous when it comes to inlining functions (`--param inline-unit-growth=1000 --param ipcp-unit-growth=1000`). I've also tried `-flto` but it took ages before the linking failed with a bunch of undefined symbols for various typeinfos, vtables and guards, so this will require more investigation. Maybe `-fwhopr` instead of `-flto` would make the linking time more acceptable.

All results are medians of 30 runs. Differences relative to "master".

|       | master    | inline           | `-O3`           | `-O3` + inline   |
|-------|-----------|------------------|-----------------|------------------|
| write | 101950.17 | 115419.91 (+13%) | 98589.17 (-3%)  | 121074.68 (+19%) |
| read  | 106512.15 | 125101.86 (+17%) | 108580.73 (+2%) | 129485.10 (+22%) |

Sizes of executables:

|                  | master | inline | `-O3` | `-O3` + inline |
|------------------|--------|--------|-------|----------------|
| w/ debug symbols | 1.1G   | 1.4G   | 1.1G  | 1.5G           |
| stripped         | 33M    | 58M    | 33M   | 61M            |

All in all it looks like the most promising way of action is to tweak the inlining heuristics.

**Comment by avikivity** [comment]
Interesting. Note there is a `size` command to display the size of the text segment.
