### ISSUE TITLE
start scylla-server does not return error to terminal

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1674]
*Installation details*
Scylla version (or git commit hash): 1.3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2 and Ubuntu 16

When running Scylla server **without** XFS, scylla do not start and write an error to log:
```
$ sudo systemctl start scylla-server
```

```
init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably bad.
To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.
```

It does **not** return an error to the terminal.
This used to work in previous Scylla releases.

**Comment by tzach** [comment]
@syuu1228 can you please take a look?

**Comment by syuu1228** [comment]
@tzach I want to reproduce 'previous version' error message at first, can I see it on 1.2.x AMI? Which one did you see the message?

**Comment by tzach** [comment]
@syuu1228 I'm not sure, I was hoping you will know.

**Comment by syuu1228** [comment]
It happens because scylla process is exit with 0, even it aborted startup.
And I found that Scylla forces to exit process with return code 0 before real return code passes from seastar:
https://github.com/scylladb/scylla/blob/master/main.cc#L441
So I think we need to get real exit code from reactor, then pass it to ::_exit().

**Comment by slivne** [comment]
patch is on mailing list
