### ISSUE TITLE
SSTABLE - Handling of error in corrupted Index/Data

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#168]
We will not boot if the meta files are corrupt - yet some files we will not know if they corrupt till we use them ... 

Does Origin verify files on boot (using CRC or something else)  ?

If we do not do any validation on Data/Index at boot - we need to decide what we will do when we hit this at runtime

**Comment by glommer** [comment]
We are failing reads when we touch the files, which seems acceptable in most times.
Also in the mean time we have merged a detector from @raphaelsc that can do post-write validation. I see very little value in boot time checks since corruption can happen after that and between reads anyway if the disk is at fault.

I am closing this, please reopen if you disagree.
