### ISSUE TITLE
very slow scylladb?

### ISSUE THREAD

**Issue by WeissGotsman** [scylladb/scylla#1769]
**HARDWARE**

![hw](https://cloud.githubusercontent.com/assets/22855561/19489961/d21e6776-959f-11e6-829c-b87ea1d66a28.png)

**STRESSTEST**
configured as in the following link: 
http://www.scylladb.com/doc/getting-started-rpm/

cassandra-stress write duration=1m -mode native cql3 -rate threads=700 -node $SERVER

Results:
op rate                   : 46000 [WRITE:46000]
partition rate            : 46000 [WRITE:46000]
row rate                  : 46000 [WRITE:46000]
latency mean              : 15.2 [WRITE:15.2]
latency median            : 13.8 [WRITE:13.8]
latency 95th percentile   : 26.1 [WRITE:26.1]
latency 99th percentile   : 38.0 [WRITE:38.0]
latency 99.9th percentile : 90.0 [WRITE:90.0]
latency max               : 290.4 [WRITE:290.4]
Total partitions          : 2760956 [WRITE:2760956]
Total errors              : 0 [WRITE:0]
total gc count            : 0
total gc mb               : 0
total gc time (s)         : 0
avg gc time(ms)           : NaN
stdev gc time(ms)         : 0
Total operation time      : 00:01:00
END

**QUESTIONS**
2x E52670 is around half the performance of 2x E5-2690 V3
http://www.cpubenchmark.net/high_end_cpus.html

My RIAD (where the vmware workstation machine resides) performance is, (yes, 4k is bad)
![hdd](https://cloud.githubusercontent.com/assets/22855561/19490178/bd4e0e04-95a0-11e6-8126-056c8f934756.png)

but why I only get 46,000 instead of 1,871,556 in the official benchmark? only 2.5%? simple bounded by the 4k performance of disk?

by the way a real comparison, cassandra 3.9.0 vs scylladb 1.4.0: 1.8M insert, 88s vs 134s; range query on primary key for 0.5M records, 17s vs 29s

DDL:
CREATE TABLE IF NOT exists tidata.t1 (
a text,
b int,
c decimal,
d int,
e bigint,
f bigint,
g int,
h1 decimal,
h2 decimal,
h3 decimal,
h4 decimal,
h5 decimal,
h6 decimal,
h7 decimal,
h8 decimal,
h9 decimal,
h10 decimal,
i1 int,
i2 int,
i3 int,
i4 int,
i5 int,
i6 int,
i7 int,
i8 int,
i9 int,
i10 int,
PRIMARY KEY (a, b));

**Comment by dorlaor** [comment]
On Tue, Oct 18, 2016 at 11:10 AM, Weiss <notifications@github.com> wrote:

> *HARDWARE*
>
> [image: hw]
> <https://cloud.githubusercontent.com/assets/22855561/19489961/d21e6776-959f-11e6-829c-b87ea1d66a28.png>
>
> *STRESSTEST*
> configured as in the following link:
> http://www.scylladb.com/doc/getting-started-rpm/
>
> cassandra-stress write duration=1m -mode native cql3 -rate threads=700
> -node $SERVER
>
Results:
> op rate : 46000 [WRITE:46000]
> partition rate : 46000 [WRITE:46000]
> row rate : 46000 [WRITE:46000]
> latency mean : 15.2 [WRITE:15.2]
> latency median : 13.8 [WRITE:13.8]
> latency 95th percentile : 26.1 [WRITE:26.1]
> latency 99th percentile : 38.0 [WRITE:38.0]
> latency 99.9th percentile : 90.0 [WRITE:90.0]
> latency max : 290.4 [WRITE:290.4]
> Total partitions : 2760956 [WRITE:2760956]
> Total errors : 0 [WRITE:0]
> total gc count : 0
> total gc mb : 0
> total gc time (s) : 0
> avg gc time(ms) : NaN
> stdev gc time(ms) : 0
> Total operation time : 00:01:00
> END
> ------------------------------
>
> 2x E52670 is around half the performance of 2x E5-2690 V3
> http://www.cpubenchmark.net/high_end_cpus.html
>
> My RIAD performance is, (yes, 4k is bad)
> [image: hdd]
> <https://cloud.githubusercontent.com/assets/22855561/19490178/bd4e0e04-95a0-11e6-8126-056c8f934756.png>
>
> but why I only get 46,000 instead of 1,871,556 in the official benchmark?
> only 2.5%?
>


I assume that's the default schema and not the one below? The more columns
you add, the harder
the database work. You seem to use a single socket (right?) and use VMware
with 16 vcpu which are actually
16 hyper threads driven by 8 cores. The benchmark had 24 real cores, 48
hyper threads.

What does the result of our iotune? Slow disk will slow things down.
If you can check the read by caching the data and workaround your disk.

Lastly, you use just one client. We used ~20 client VMs to drive 1.8M/s

> by the way a real comparison, cassandra 3.9.0 vs scylladb 1.4.0: 1.8M
> insert, 88s vs 134s; range query on primary key for 0.5M records, 17s vs 29s
>
You're right we need to update the performance. Our performance did degrade
since this benchmark. Mostly because we
added lots of mechanisms for automatic backpressure and large partition
streaming. The YCSB one (with
a different schema and different hardware) is more up-to-date.

Regarding your results, it would be good to figure out the bottleneck - is
that the cpu/net/client/disk?
My bet it's either the client or the disk. If you'll set our monitoring
docker image, we'll be able
to give a better answer.

Cheers,
Dor

**Comment by avikivity** [comment]
The main issue is that you are using a rotating disk rather than an SSD.  You won't get anywhere near 1M ops/sec with a spinning disk; for that kind of performance you need a high-end SSD (e.g. NVMe) or a RAID of several SATA SSDs.

A secondary issue is that you are running in a virtualized environment with a low core count.  To get maximum performance run on bare metal, and on a larger machine.  But nothing will work with that disk.

**Comment by WeissGotsman** [comment]
OK, I retested as follows:

1. I disabled the HT in the bios of the motherboard of computer that runs the CentOS virtual machine, now during the cassandra-stress test, the CPU utilization in the host shows 100%, and the op rate  goes from 46000 to 56000

2. I' moved the CentOS virtual to an SSD, with performance as follows: 
![ssd](https://cloud.githubusercontent.com/assets/22855561/19617962/ef8e3cc2-9870-11e6-8c1f-bfa7ef716c56.png)

then I do cassandra-stress again, the op rate is still 56000, this is expected, because during previous test, the cpu is already satuated. Raid od HHD is not the bottleneck, but CPU is.

3. Then I tried to "drive" the Scylla with 4 clients, within a 1000Mbps network, once one client is running the cassandra-stress, other cients timeouts to connect to Scylla in the CentOS

(com.datastax.driver.core.OperationTimedOutException: [192.168.48.109/192.168.48.109:9042] Operation timed out)

4. I do have questions on the testing config in the following link:
http://www.scylladb.com/technology/cassandra-vs-scylla-benchmark-2/

Scylla is installed on a single machine with two E5-2690 v3 CPUs?  
and connecting  from 15 clients with a E5-2683 v3 CPU?

**Comment by avikivity** [comment]
56k ops/sec for 8 cores is very slow.  Can you check in VMWare how much cpu is consumed by the hypervisor?  And in the guest, the user/system cpu loads?

The test in the link has one database server and fifteen loaders.

**Comment by WeissGotsman** [comment]
Cassandra-stress locally of the Scylla DB server:
[![guest.png](https://s11.postimg.org/j8b2dnmsj/guest.png)](https://postimg.org/image/mf5lxa78f/)
[![guest2.png](https://s13.postimg.org/c3bokbmbb/guest2.png)](https://postimg.org/image/6f5dtfhyr/)

Host OS always use 100% cpu (all of them are kernel time) but guest uses around 75% cpu
The guest has 16 cores from 2 Xeon E5-2670 CPUs (with HT disabled), not 8 cores.
Would it has something to do with the virtualized NIC?

**Comment by avikivity** [comment]
It could be.  For performance testing, use a non-virtualized server dedicated to scylladb for the test duration.
