### ISSUE TITLE
how to ensure the rp order when apply to memtable avoid 'replay_position_reordered_exception'?

### ISSUE THREAD

**Issue by duanshisan** [scylladb/scylla#1774]
when the config commitlog_sync be set to batch, the commitlog will use the 'flush_queue'  by the function run_with_ordered_post_op(...) mode,  if this time there are three write oprations enter the queue, and they have ordered rp (generated in the allocate(..) function in the file commitlog.cc), assuming they are rp1, rp2, rp3 small to large,  rp1 will do flush write to the file , rp2 and rp3 will wait the rp1 complete,  then  will apply data to memtable with rp, but how to ensure the rp1,rp2,rp3 oprations in ordered be performed in the funcition column_family::apply(...) in the code file database.cc, because the check_valid_rp(...) function will check the rp order, otherwise will throw replay_position_reordered_exception().

thanks

**Comment by elcallio** [comment]
I am not sure I understand the question fully, but I'll try to explain the ideas. Data in the commit log is by definition ordered by replay position, since rp is the actual file and file pos. A mutation written to the commit log gets this rp back, and propagates it to the memtable write. The memtable write in turn asserts that it enters mutations in rp order, and, as you write, if not, throws and exception which in turn leads to a re-try with a new write to the commit log. So data in the commit log _can_ (though it is extremely rare) be duplicated. Which is fine, because of how mutations works. 

Now, memtables keep the contract of monotonic rp positions, and so when we flush them, since we never write to more than one memtable at a time, as long as we _signal_ them having been written to disk in the same ascending rp order, we can eliminate rp regions from commitlog segments for a given column family (by uuid). Thus, eventually, commit log segments will become "clean", i.e. all data is marked as having been persisted to sstable, and this is when we can free it. 

Not sure if this helps or answers the question...

**Comment by duanshisan** [comment]
@elcallio 
Thanks ,your answers very useful to me, I am very clear now

**Comment by slivne** [comment]
@duanshisan can we close this ?

**Comment by duanshisan** [comment]
@slivne yes we can close this now, thank you.
