### ISSUE TITLE
AMI should use EC2Snitch and not SimpleSnitch 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1800]
related to #1760

**Comment by syuu1228** [comment]
I think I implemented to let AMI to use Ec2Snitch, log time ago..
https://github.com/scylladb/scylla-ami/commit/188781c17bde5d10b9ca23a68ea420cf41ab4e3f

Maybe it does not works correctly for some reason / in some condition.
I can see latest release of AMI uses Ec2Snitch, at least on single node configuration with no userdata:

```
[centos@ip-172-30-0-115 ~]$ grep Ec2Snitch /etc/scylla/scylla.yaml
#  - Ec2Snitch:
endpoint_snitch: Ec2Snitch
```

**Comment by slivne** [comment]
single node has Ec2Snitch - if you start a cluster it will change

**Comment by syuu1228** [comment]
On Tue, Nov 1, 2016 at 10:17 PM, Shlomi Livne <notifications@github.com>
wrote:

> single node has Ec2Snitch - if you start a cluster it will change
>

Do you have userdata at that time?

**Comment by amoskong** [comment]
@syuu1228 
`scylla-ami/ds2_configure.py` replaces 'SimpleSnitch' with 'Ec2Snitch' for 'Community' version.

How does the version be set to 'Community':
- We can assign 'Community' version by user-data  ' --version Community ....'
- If it fails to get(parse) ec2 user-data, it will force set version to 'Community'

I guess the 'Community' / 'Enterprise' concept was from C* (D*Stax), it doesn't related with our releases.
So we should use Ec2MultiRegionSnitch for multiregion case, otherwise, we should _always_ use Ec2Snitch (we don't care about the `version`).


```
diff --git a/ds2_configure.py b/ds2_configure.py
index eae938e..19ddc6f 100755
--- a/ds2_configure.py
+++ b/ds2_configure.py
@@ -425,9 +425,7 @@ def construct_yaml():
         instance_data['externalip'] = urllib2.urlopen(req).read()
         logger.info("meta-data:external-ipv4: %s" % instance_data['externalip'])
         yaml = p.sub('broadcast_address: {0}'.format(instance_data['externalip']), yaml)
-
-    # Uses the Ec2Snitch for Community Editions
-    if conf.get_config("AMI", "Type") == "Community":
+    else:
         yaml = yaml.replace('endpoint_snitch: org.apache.cassandra.locator.SimpleSnitch', 'endpoint_snitch: org.apache.cassandra.locator.Ec2Snitch')
         yaml = yaml.replace('endpoint_snitch: SimpleSnitch', 'endpoint_snitch: Ec2Snitch')
 
```

**Comment by tzach** [comment]
@amoskong you change make sense
We do not have the community AMI version
Lets add this change

**Comment by tzach** [comment]
@amoskong can you please send a patch?

**Comment by amoskong** [comment]
@tzach  Posted a patch to scylladb-dev maillist.
[PATCH scylla-ami] [ds2_configure.py: always use Ec2Snitch for single region case](https://groups.google.com/forum/#!topic/scylladb-dev/EK1nfn_OIB0)
