### ISSUE TITLE
commitlog may reorder elements

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1802]
Commitlog writes can reorder elements with respect to their replay position. We have code in database.cc that catches an exception in case that happens and tries to reinsert the element.

While this is fine for very small partitions, this is horrible for very large ones. That is because it can take us many hundreds of milliseconds to insert a partition depending on its size. If we have to do it again, we're sure to timeout.

Maybe the memtable code should be more resilient, maybe the commitlog should enforce strict ordering, and maybe a bit of both.

**Comment by elcallio** [comment]
The commit log does not really reorder anything. Order is defined as the order it was written to commit log. It is thus the execution following that "reorders" in-flight execution, i.e. fails (due to continuation reordering) to uphold that order. 

The point I am trying to make is that you cannot by definition order stuff "more" in the commit log, without doing _less_. The original code tried hard to not have any continuation delay points after acquiring a buffer position and writing to it, to minimize the chance of having code execution beyond this reordered. Now, at the very least there are  more opportunity for blocking ops post the salient parts of allocate with example more aggressive cycling.  

So your last point about making post-cl-code more resilient might be the best option.

**Comment by slivne** [comment]
@glommer do we have a reproducer / case that shows this really happening on the field and is a real issue.

**Comment by glommer** [comment]
Yes, this happens in my machine and is part of the work of reducing
timeouts for large writes.

It's one of the many issues involved in that problem.

**Comment by glommer** [comment]
Had some time today to work a bit on this (well, in reality I should have been sleeping).

Reorder happens in two places: one is the commitlog's fault, the other is on the memtable side. Patches sent to the list, reviews welcome.

**Comment by slivne** [comment]
@glommer - can we close this ?
