### ISSUE TITLE
master regression - cannot gracefully reboot if compactions are ongoing

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1851]
commit hash: f877be50b059bf2a7adbd6ce48d4de59088920ac

Started scylla, smp = 6, memory = 12 GB.
Disk approximately 400 MB/s

Started a moderately heavy load, with 64kB partitions with the following command:

```
cassandra-stress write duration=5m cl=ONE no-warmup \
    -mode native cql3 -rate threads=100 -col n=FIXED\(1\) size=FIXED\($((128 << 10))\) -node 127.0.0.1 \
    -pop seq=1..1000000000 
```

When compactions are running, send a SIGINT. The way it crashes varies, but it seems to crash all the time. Backtrace attached.

[gdb.txt](https://github.com/scylladb/scylla/files/593647/gdb.txt)

**Comment by glommer** [comment]
@slivne we need to verify that this doesn't happen with 1.5. I'll try myself if I have time

**Comment by raphaelsc** [comment]
backtrace:
Program received signal SIGSEGV, Segmentation fault.
0x00000000005407e4 in scollectd::impl::<lambda()>::operator() (__closure=0x600041b2fb20) at core/scollectd.cc:375
375	        while (i != values().end()) {
(gdb) bt
#0  0x00000000005407e4 in scollectd::impl::<lambda()>::operator() (__closure=0x600041b2fb20) at core/scollectd.cc:375
#1  do_until_continued<scollectd::impl::run()::<lambda()>&, scollectd::impl::run()::<lambda()>&>(scollectd::impl::<lambda()> &, scollectd::impl::<lambda()> &, promise<>) (
    stop_cond=..., action=..., p=...) at ./core/future-util.hh:148
#2  0x00000000005437a0 in <lambda(std::result_of_t<scollectd::impl::run()::<lambda()>&()>)>::operator() (fut=..., __closure=<optimized out>) at ./core/future-util.hh:153
#3  do_void_futurize_apply<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = scollectd::impl::run()::<lambda()>&; StopCondition = scollectd::impl::run()::<lambda()>&]::<lambda(std::result_of_t<scollectd::impl::run()::<lambda()>&()>)>, future<> >(<unknown type in /data/scylla/build/release/scylla, CU 0x727a18, DIE 0x824472>) (func=func@entry=<unknown type in /data/scylla/build/release/scylla, CU 0x727a18, DIE 0x824472>) at ./core/future.hh:1212
#4  0x00000000005438c4 in futurize<void>::apply<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = scollectd::impl::run()::<lambda()>&; StopCondition = scollectd::impl::run()::<lambda()>&]::<lambda(std::result_of_t<scollectd::impl::run()::<lambda()>&()>)>, future<> > (func=<optimized out>) at ./core/future.hh:1260
#5  future<>::<lambda(auto:2&&)>::operator()<future_state<> > (state=<unknown type in /data/scylla/build/release/scylla, CU 0x727a18, DIE 0x7e4197>, __closure=0x600041b2fb00)
    at ./core/future.hh:911
#6  continuation<future<T>::then_wrapped(Func&&) [with Func = do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = scollectd::impl::run()::<lambda()>&; StopCondition = scollectd::impl::run()::<lambda()>&]::<lambda(std::result_of_t<scollectd::impl::run()::<lambda()>&()>)>; Result = future<>; T = {}]::<lambda(auto:2&&)> >::run(void) (this=0x600041b2faf0) at ./core/future.hh:390
#7  0x000000000048b55f in reactor::run_tasks (this=this@entry=0x60000028b000, tasks=...) at core/reactor.cc:1969
#8  0x00000000004d32eb in reactor::run (this=0x60000028b000) at core/reactor.cc:2402
#9  0x0000000000550a6c in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffdab0, ac=ac@entry=26, av=av@entry=0x7fffffffdd28, 
    func=func@entry=<unknown type in /data/scylla/build/release/scylla, CU 0x8f7fbc, DIE 0x9e35d3>) at core/app-template.cc:131
#10 0x000000000041d361 in main (ac=26, av=0x7fffffffdd28) at main.cc:672

Turns out that this issue is related to collectd. 

using git blame, i found that the following seastar's commit is likely to be the one that introduced the problem: 83549367df6936fe844c8a6635baeeac0505a427

**Comment by glommer** [comment]
Saw that with 1.5, it's just a lot less common.

**Comment by amnonh** [comment]
The backtrace is from master (83549367df6936fe844c8a6635baeeac0505a427) and not relevant to 1.5
