### ISSUE TITLE
Use SIMD for caches

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#186]
Instead of a binary tree, use a b-tree with 5-way branching.

Nonleaf tree node can look like this:

```
  int64_t token[4]
  node* children[5];
```

so we can compare a token against four keys simultaneously.

**Comment by belliottsmith** [comment]
Why not 8-way branching? Memory bandwidth is likely to be the limiting factor in any cache lookup, for all but the top most levels surely? If 32-bits are enough to distinguish the tokens at those levels 11 children can be crammed in, which is likely quite achievable if tokens are normalised to the owned ranges (in the root) and to the parent's range in all children.

However, as I mentioned previously, I really recommend considering [a hash table](https://issues.apache.org/jira/browse/CASSANDRA-7282), with the skip-list enhancement I discussed on the ticket. This would absolutely require normalising the tokens (or a separate structure for each owned token range), but also can handle token and partition keys in the same structure, whereas a purely integer keyed structure needs some way to handle token collisions.  More importantly it has an expected cost of 2 cache misses.  Yes, it does support range queries.

**Comment by avikivity** [comment]
I remember a skiplist as being very memory intensive, you need to store a lot of links; it's also expensive to insert and remove.  But that is from ~13 years ago, so maybe I'm misremembering.

We could/should do 8-way branching, and even 16-way with AVX3.

**Comment by belliottsmith** [comment]
A pure skip list certainly has higher overheads than a tree, but in this instance it's got an expected cost of zero, as the skip-nodes are only necessary when ensuring the worst case complexity of any operation does not dip below O(lg N).  When the hashes are uniformly distributed there would be no skip list, just a list; the expected cost of any operation is O(1), with very low constant factors.

I recommend reading the linked Cassandra ticket and branch (the comments on the branch thoroughly explain the algorithm, although it is very simple).  There are many possible extensions not discussed that could further exploit AVX, such as associative buckets of items, that can be expanded to far more than 16 by storing fingerprints rather than full payloads, only consulting the full entries for those fingerprints that match (with on average 1.005 matches, say).

The hash table approach has the advantage of being perfectly suited to AVX, since values can easily be grouped to multiples of cache lines and/or AVX register sizes (helpfully the same thing in AVX-512).  I'm not sure for a tree the groupings should ever be decided by the size of the AVX registers, though.  Every lookup below a certain tree depth (or anywhere in a hash) can be assumed to be a cache miss, and we can happily run many AVX operations (or non-AVX) in the time for a fill from main memory, so two AVX-2, one AVX-512 or a hand-rolled snippet for a fixed number of elements is probably neither here nor there.

**Comment by avikivity** [comment]
@xemul let's close this 3-digit bug
