### ISSUE TITLE
Cache partially consumed range scan mutation readers 

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1865]
*Installation details*
Scylla version (or git commit hash): 1.5

A scanning mutation reader represents a considerable investment: we found out which sstables are involved, read their index to seek to the start, read one or more 128k data blocks into memory.  If we throw all of this away when we hit the page size, we'll have to redo all of it on the next page.

We should keep a cache of such opened mutation readers, so that when the next page is read, we continue where we left off.  The cache should age out so we don't keep unused memory if the user abandons the query, and should of course limit the amount of resources cached.

If a memtable is flushed into cache, it should invalidate previously cached readers (since the backing sstable set changes); or we may add the new sstable to the cached reader.  Similarly for compactions.

**Comment by tgrabiec** [comment]
Here are some notes on possible implementation.

We need to be able to associate mutation_readers globally with each client query. Current read_command is not enough, because two different queries may have the same restrictions (same page), but since they were started at different times, may need to see different set of writes. Also, mutation_reader can only be used by one process at a time. So we need a way to identify reads globally in the cluster. The ID could be generated by the coordinator and sent back in the paging_state to the CQL client and as a hint embedded in read_command sent to replicas. 

Replicas would cache the top-most mutation_reader used to serve the read request. The matching is done based on reader ID. If coordinator is stateless, we also need to do the matching between the last position of the reader and the lower bound of restrictions to catch the case of the same page being re-requested. In such case we have to recreate the reader. That wouldn't be needed if coordinator would keep track of the state for the query as well, we could assume it never re-requests the same page for the same ID.

Readers would be dropped from the reader cache when they're exhausted, inactive for certain amount of time, or memory consumed by all cached readers exceeds a threshold. In the latter case readers are invalidated in LRU order. 

The coordinator should use the same set of replicas across pages to keep the miss rate low. If coordinator is stateless, we'd have to embed the set of replicas used for reading inside paging_state. That has a potential disadvantage of increasing the size of the paging_state (depends on the number of nodes). If the coordinator is stateful, it could remember this on its own.

**Comment by avikivity** [comment]
> Readers would be dropped from the reader cache when they're exhausted

I think more natural is to remove a reader from the cache when you start using it, then reinsert it when you're done, if it's not exhausted.  This is because readers are single-user.

**Comment by tgrabiec** [comment]
2017-04-26 16:32 GMT+02:00 Avi Kivity <notifications@github.com>:

> Readers would be dropped from the reader cache when they're exhausted
>
> I think more natural is to remove a reader from the cache when you start
> using it, then reinsert it when you're done, if it's not exhausted. This is
> because readers are single-user.
>

Agreed.

**Comment by dorlaor** [comment]
@avikivity @slivne in case it is the customer issue we discussed, let's assign a person and a target release

**Comment by avikivity** [comment]
For very large promoted index, paging can induce quadratic behavior in the index read, since the index is a linear structure. The cache would optimize this quadratic behavior to O(number of rows) performance.

**Comment by glommer** [comment]
@avikivity did we make any progress here ?

**Comment by avikivity** [comment]
Yes.

**Comment by denesb** [comment]
As the first series addressing this was just merged I'd like to collect here the items raised during reviews that we decided to defer to be resolved by follow-up patches.

The first series (0698b5095f3fb8ef61822eba4a3bbdafec118437) only adds reader reuse support for single-partition queries, so multi-partition queries support still has to be done.
Additional items raised during reviews:
[ ] Use the same query-time on all the pages.
[ ] Make read-repair-chance apply to whole queries.
[ ] last-replicas needs to be shrunk on every page (only current replicas need to be left in).
[ ] Don't recalculate the list of replicas to send the requests to on every page if their status doesn't change.
[ ] Take HWLB into account when selecting preferred-replicas, we should sometimes prefer a node with a hot cache over one with a cached reader.

**Comment by avikivity** [comment]
Also need some driver work to prefer sending paged queries to the same coordinator.

For range queries, we might extend the protocol to tell the client where the next page is located (via a token).

**Comment by denesb** [comment]
For the java driver we already have [Piotr's cluster optizer](https://github.com/haaawk/scylla-java-driver-tools). When I have some time I will do quick latency measurements to see how much saving that hop helps us.

**Comment by avikivity** [comment]
Yeah, but to reduce friction it's better to have it in the driver proper.

**Comment by glommer** [comment]
most users will only be able to consume this if it is in the upstream driver.

**Comment by avikivity** [comment]
@haaawk's thing is not a fork, but an additional component. Still better upstream of course.

**Comment by denesb** [comment]
Support for range-scans was merged as e49a14e308ac82fa651c778e274d77bedae595e7.

This initial support optimizes for large tables filled with largish partitions, case (1) according to the following categorization:
1) A single shard-range on a single `vnode` fills a page.
2) A few shard-ranges (but less then the number of shards) on a single
`vnode` are needed to fill a page.
3) Many shard-ranges on a single `vnode` are needed to fill a page.
4) Two `vnode`s are needed to fill a page.
5) Many `vnode`s are needed to fill a page.

The other cases will be done in follow-ups which will be listed in this ticket so we can determine when this parent issue can be closed.
The following optimizations for cases (2)-(5) were raised during the design phase:
- [ ] [Allow the coordinator to over- or undershoot the page-size limits set by the client #3742](https://github.com/scylladb/scylla/issues/3742)
- [ ] [Set the `is_first_page` flag when moving to a new vnode #3743](https://github.com/scylladb/scylla/issues/3743)
