### ISSUE TITLE
Confusion if user mounts disk over /var/lib/scylla after installation

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1867]
*Installation details*
Scylla version (or git commit hash): 1.4

If the user first installs scylla, then mounts `/dev/foo` on `/var/lib/scylla`, then `/var/lib/scylla/conf` will be gone, as well as `/var/lib/scylla/data` and `/var/lib/scylla/commitlog`.  Scylla will fail to open `conf/scylla.yaml`; the error messages are very unfriendly.

**Comment by avikivity** [comment]
`scylla_io_setup` also crashes if `/var/lib/scylla/data` is missing.

**Comment by syuu1228** [comment]
We can handle it on scylla_prepare for scylla, scylla_io_setup for iotune, but isn't it better to handle in C++ code side? Otherwise the problem still can happen when user runs /usr/bin/scylla or /usr/bin/iotune directly (normally user shouldn't do that, but unfriendly error messages are still there).

Also, witch is more correct way to handle the problem, creating data/commitlog directories silently and continue running, or output more friendly error message and stop running?
I guess we shouldn't silently solve the problem, since user can specify custom path for data/commitlog directories, maybe why we couldn't access the directory was because of wrong path.

**Comment by syuu1228** [comment]
@avikivity ping

**Comment by avikivity** [comment]
I don't know what's the right thing to do here.  Maybe the following:

 - disable data/ and commitlog/ auto-creation (except in --developer-mode)
 - refuse to start if they don't exist (except in --developer-mode)
 - remove conf symlink, move it /etc/{sysconfig,default}/scylla-server as a separate variable
 - update everything (startup scripts, admin scripts) to use that variable (defaults to /var/lib/scylla/conf for compatibility)

So now:
 - if the filesystem isn't mounted, scylla won't start, even if the conf directory is available
 - mounting a new partition doesn't affect startability
 - iotune and friends work on the right partition

any bugs?

**Comment by syuu1228** [comment]
On Thu, Jan 5, 2017 at 11:38 PM, Avi Kivity <notifications@github.com>
wrote:

> I don't know what's the right thing to do here. Maybe the following:
>
>    - disable data/ and commitlog/ auto-creation (except in
>    --developer-mode)
>    - refuse to start if they don't exist (except in --developer-mode)
>
> These are looks good

>
>    - remove conf symlink, move it /etc/{sysconfig,default}/scylla-server
>    as a separate variable
>    - update everything (startup scripts, admin scripts) to use that
>    variable (defaults to /var/lib/scylla/conf for compatibility)
>
> To implement this, can we fix #2057 on same time?
https://github.com/scylladb/scylla/issues/2057

I think it's better to add "--config-directory" program argument, and set
it's default value to "/var/lib/scylla/conf" for compatibility.

**Comment by slivne** [comment]
@syuu1228 can we close this ?

**Comment by slivne** [comment]
@syuu1228 ping
