### ISSUE TITLE
Encounter storage_proxy error under high load

### ISSUE THREAD

**Issue by tommy351** [scylladb/scylla#1885]
*Installation details*
Scylla version (or git commit hash): 1.4.1
Cluster size: 6 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7

*Hardware details (for performance issues)*
Platform: GCE
Hardware: cores=8 memory=30GB
Disks: one 500GB SSD

Sometimes Scylla got these errors under high load:

```
storage_proxy - Exception when communicating with 10.140.0.59: std::bad_alloc
storage_proxy - Exception when communicating with 10.140.0.59: Semaphore timedout
```

I create a inverse table for faster query. For example:

``` sql
CREATE TABLE IF NOT EXISTS post_read_logs (
  post_id BIGINT,
  member_id BIGINT,
  created_at TIMESTAMP,
  PRIMARY KEY (post_id, member_id)
);

CREATE TABLE IF NOT EXISTS post_read_logs_r (
  post_id BIGINT,
  member_id BIGINT,
  created_at TIMESTAMP,
  PRIMARY KEY (member_id, post_id)
);
```

and there are some common queries:

``` sql
-- Insert
BEGIN UNLOGGED BATCH
INSERT INTO post_read_logs (post_id, member_id, created_at) VALUES (1, 2, now);
INSERT INTO post_read_logs_r (member_id, post_id, created_at) VALUES (2, 1, now);
APPLY BATCH;

-- Select
SELECT * FROM post_read_logs WHERE post_id = 1 AND member_id = 2;

-- Multi select
SELECT * FROM post_read_logs_r WHERE member_id = 2 AND post_id IN (...);
```

**Comment by tgrabiec** [comment]
@tommy351 To tell more I would need recording of Scylla telemetry. For that you need to setup prometheus as described here: https://github.com/scylladb/scylla-grafana-monitoring, and send us the prometheus database as described here: https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem#prometheus

**Comment by tgrabiec** [comment]
@tommy351 please make sure you use scrape_interval of 1s in prometheus/prometheus.yaml.

**Comment by slivne** [comment]
@tommy351 can you please collect and provide the additional information

**Comment by tommy351** [comment]
I have uploaded the reports to scylladb-users-upload.s3.amazonaws.com. The ID is `dbb2a6ae-b6aa-11e6-a359-5f65c4f38349`.

**Comment by tgrabiec** [comment]
@tommy351 Do you have scylla logs for this run?

**Comment by tgrabiec** [comment]
In the metrics recording I can see that there are read errors on one of the nodes, scylla-cluster-031i. The errors correlate with read timeouts. 

![errors](https://cloud.githubusercontent.com/assets/283695/21150294/cd472702-c15e-11e6-9bc2-345775047ec5.png)

That correlates with reactor load and CPU user time reaching 100% on one of the shards (shard 3), whereas it usually is quite low, and is low for other shards:

(reactor load below, it's actually per-shard for scylla-cluster-031i)
![load](https://cloud.githubusercontent.com/assets/283695/21150299/d20d8dee-c15e-11e6-9394-049a77d5184a.png)

@tommy351 Can you get a CPU utilization flame graph (https://github.com/brendangregg/FlameGraph) for the period when the CPU is saturated, for the CPU which is saturated? You can observe CPU utilization using `mpstat -P ALL 1`. Record using `sudo perf record --call-graph dwarf -C $busy_cpu sleep 4`.

You can also see periodic spikes in load occurring once per minute. That seem to span the whole test and don't seem correlated with the timeouts. Those spikes correlate with very high cache hit rate, but not read request rate. That looks like a range query. @tommy351 Are you running periodic range scans?

The high CPU utilization correlates with formation of sstable read queue:

![reads](https://cloud.githubusercontent.com/assets/283695/21150513/7ebf6d3c-c15f-11e6-9f5a-9323269a5c2d.png)

That correlates with formation of a queue of I/O requests in the "query" class, which also has a very high delay (40 s). That looks as if the disk got very slow:

![query_class](https://cloud.githubusercontent.com/assets/283695/21150545/afe9df50-c15f-11e6-948b-e897300f60f8.png)

The AIO utilization for the whole node looks very low. Rate is about 200 req/s and bandwidth stays a bit below 1MB/s most of the time, but it does spike some times to as high as 30MB/s. It looks similar before and during the timeouts.

![aio](https://cloud.githubusercontent.com/assets/283695/21150646/05e04732-c160-11e6-9625-abe8b4134297.png)

@tommy351 what's your `/etc/scylla.d/io.conf`? What's your disk capable of in terms of IOPS and bandwidth?

The memory utilization seems steady throughout the test, and cache occupies most of the memory on all shards. So if bad allocs happen, they don't seem to be due to running out of memory. If you're running in a test environment so that crashing a node is not a problem, you can run Scylla with `--abort-on-lsa-bad-alloc=1` and `--abort-on-seastar-bad-alloc`, which will create a coredump on bad_alloc which we can analyze.

**Comment by tommy351** [comment]
I removed the batch query and the problem seems to be solved.

Here's my `/etc/scylla.d/io.conf`. It's automatically generated by the setup script:

```
SEASTAR_IO="--max-io-requests=54"
```

GCE claimed the IOPS is 15000 and the bandwidth is 240MB/s.

**Comment by tgrabiec** [comment]
@tommy351 Can you say more about that batch query? How does it look like? How often is it run in this workload? How much data  is it expected to return?

**Comment by tzach** [comment]
@slivne can you assign

**Comment by tzach** [comment]
@tommy351 can you help us investigate by providing more info? See @tgrabiec questions above. Thanks

**Comment by slivne** [comment]
closing this issue - no response - will work on testing unlogged batches further and open a new issue
