### ISSUE TITLE
Use lowres_clock as a base for gc_clock

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1957]
gc_clock has precision of 1 second so we could use a cheaper lowres_clock instead of system_clock.

**Comment by hakuch** [comment]
The `gc_clock` is used, AFAICT, for two purposes:

- to compare the current system time to the expiry time of a column value, based on its configured time-to-live (TTL).
- to check how much time has elapsed when deciding whether it is time to garbage-collect data that have been marked with a tombstone. This duration of time is controlled by `gc_grace_seconds`.

Both use-cases require only 1 second granularity. This is reflected in the fixed period of `gc_clock` in its declaration.

## A little bit about the `chrono` library

A `std::chrono::duration` stores a relative quantity of time. This duration is independent of any particular clock. It consists of a count of ticks and a measure of the ratio of ticks to a second.

In contrast, a `std::chrono::time_point<Clock>` is a quantity of time relative to a fixed time reference ("epoch") that is particular to `Clock`. The epoch can be opaque. `std::chrono::time_point<Clock>::time_since_epoch` returns a `std::chrono::duration`.

The `std::chrono::system_clock` produces `time_point` instances which can be converted to `std::time_t` (from C). By popular convention (though not any standard), `std::time_t` are integral quantities which reflect offsets from the epoch defined in [Unix time](https://en.wikipedia.org/wiki/Unix_time).

In contrast, `std::chrono::steady_clock` (which produces monotonically-increasing values) produces `time_point` instances relative to an opaque epoch. A popular choice is the number of nanoseconds that have elapsed since the system booted. This particular choice of epoch is non-stable: time points from separate runs of the program cannot necessarily be compared directly because they're based on a changing reference.

## Seastar's low-resolution clock

`seastar::lowres_clock` is implemented in Seastar via timers that are controlled by the reactor for a shard. These timers, when triggered, atomically set storage in memory with the latest time-point from a steady clock. Unlike the standard steady clock, the resolution of `seastar::lowres_clock` is limited to 10 ms (this is the timer period) and reported as 1 ms.

## Conclusion

Because `seastar::lowres_clock` is backed by a clock with an opaque (non-stable) epoch, it's not suitable for backing `gc_clock`. If we were to switch, all time points  produced by `gc_clock` would have to converted to Unix times prior to being written to tables. I do not believe this is possible, though I'm very open to being corrected (on any of the above).

I believe this issue should be closed. @tgrabiec or @duarten, any thoughts?

**Comment by tgrabiec** [comment]
Right, lowres_clock is based on std::chrono::steady_clock. We could introduce `lowres_system_clock` though.

**Comment by hakuch** [comment]
Do you have an implementation technique in mind for a `lowres_system_clock`, @tgrabiec?

**Comment by tgrabiec** [comment]
@hakuch The mechanism would be the same, just with a different base clock. Perhaps we can avoid some code duplication, e.g. the two could share the same timer which updates both clocks.

**Comment by hakuch** [comment]
That seems reasonable. I assume this would be an addition to `core` of Seastar and then Scylla would be modified to use that clock as described in this task.
