### ISSUE TITLE
Question about H/W spec

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1966]
Hi..
Which of the following two cases is more suitable for Scylladb?
it depends on business use case, but I would appreciate your opinion in general situation.

Case1)
8Core, 32GB memory , 2node

Case2)
4Core, 32GB memory, 3node

**Comment by benoit-canet** [comment]
Hi,

Scylla is designed to benefit well from multicore thanks to it's sharded
design
and is cpu intensive.

It scale perfectly well on multicore.

Regarding memory usage it will depend if you have hyperthreading enabled
and the number of core you have on your machine.

See Avi's advices on
https://groups.google.com/forum/#!topic/scylladb-users/j_21dRCFflo as hint

Also look at the FAQ: http://docs.scylladb.com/faq/

Don't forget to use SSD or NVME since spinners would simply ruin the
performance.

Best regards

Benoît

**Comment by benoit-canet** [comment]
http://docs.scylladb.com/admin/

**Comment by infordb** [comment]
@benoit-canet  Thank you for your feedback..  Do you mean that case1 is better than case2 ? because of total core count

**Comment by benoit-canet** [comment]
Not an expert but one of our reasoning is favoring high end machine
because they lead to less nodes to maintains and scylla is cpu intenssive.

From the doc as a rule of thumb.


   - "Typical recommended for production: *16 GiB or 2GiB/lcore* (whichever
   is higher)"

Case1)
- 8 core * 2 for HT * 2Gig per logical core = 32GB ram used per node

total logical core count = 8 * 2 * 2 = 32

No ram left for other things this won't work as is.

Case2)

-4 core * 2 for HT * 2gig per logical core = 16 GB ram used per node

total logical core count = 4 * 2 * 3 = 24

So Case 1 is giving 8 extra logical core.

Despite that some ram must be reserved for the system and the other apps
running on the machine so  use only physical 7 core core on Case 1:

7 * 2 * 2 = 28 GB Used

logical core count = 7 * 2  * 2 =   28 core still 4 extra core for scylla

From
https://github.com/scylladb/scylla/wiki/Scylla-production-recommendation


--cpuset `hwloc-calc all ~core:0` --smp 14 -m 28g

**Comment by infordb** [comment]
@benoit-canet 
Our core is already hyper-threaded.
so case1)
 - 8core * 3Gig per logical core  = 24GB ram used per node
   8GB ram left for other things..

As a result, case1 could be  better than case2

**Comment by avikivity** [comment]
case 1 has 16 cores and 64 GB RAM spread across the cluster (and presumably 2 disks)
case 2 has 12 cores and 96 GB RAM spread across the cluster (and presumably 3 disks)

If your load is cpu bound, then case 1 is better; if it is I/O bound, then case 2 is better.
