### ISSUE TITLE
networking interrupt mitigation

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1974]
*Installation details*
Scylla version (or git commit hash): 1.5

I noticed that on aws ec2 i2.2xlarge enabling interrupt mitigation reduces interrupt processing load dramatically.

The command used was `ethtool -C eth0 rx-usecs 800`, but maybe adaptive would be better, or a different number,

**Comment by vladzcloudius** [comment]
@avikivity The above configuration is beneficial for a throughput-oriented load, when there is always a lot of received data to process and and one don't really care about the response latency. However it's most like going to hit a latency case, where you want to handle the packet as soon as possible. 
So, the command above is at least not good for a general case. 
The adaptive configuration would be the best, however I wonder if an EC2 Xen virtual networking driver has this option and if it does if it's not the default option.

As far as I know i2.2xlarge doesn't support Enhanced Networking and this is what I've got when I ran the coalescing related `ethtool` command on i2.2xlarge instance:

```
[centos@ip-10-30-36-173 ~]$ sudo ethtool -i eth0
driver: vif
version: 
firmware-version: 
bus-info: vif-0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
[centos@ip-10-30-36-173 ~]$ sudo ethtool -c eth0
Coalesce parameters for eth0:
Cannot get device coalesce settings: Operation not supported
[centos@ip-10-30-36-173 ~]$ sudo ethtool -C eth0
Cannot get device coalesce settings: Operation not supported
```

**Comment by avikivity** [comment]
It worked for me.  Did you enable enhanced networking when you launched the instance?  It was the ivxgbe or whatever driver.

**Comment by vladzcloudius** [comment]
AFAIK this type of instance doesn't support Enhanced Networking. I'm checking the above with the c3.8xlarge which do supports it.

**Comment by avikivity** [comment]
I'm sure I was on an i2.2xlarge.

```
# lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 01)
00:02.0 VGA compatible controller: Cirrus Logic GD 5446
00:03.0 Ethernet controller: Intel Corporation 82599 Ethernet Controller Virtual Function (rev 01)
00:1f.0 Unassigned class [ff80]: XenSource, Inc. Xen Platform Device (rev 01)
```

```
#  curl http://169.254.169.254/latest/meta-data/instance-type
i2.2xlarge
```

**Comment by vladzcloudius** [comment]
For ixgbevf driver the default interrupt coalescing configuration is as follows:
```
# sudo ethtool -c eth0
Coalesce parameters for eth0:
Adaptive RX: off  TX: off
stats-block-usecs: 0
sample-interval: 0
pkt-rate-low: 0
pkt-rate-high: 0

rx-usecs: 1
rx-frames: 0
rx-usecs-irq: 0
rx-frames-irq: 0

tx-usecs: 0
tx-frames: 0
tx-usecs-irq: 0
tx-frames-irq: 0

rx-usecs-low: 0
rx-frame-low: 0
tx-usecs-low: 0
tx-frame-low: 0

rx-usecs-high: 0
rx-frame-high: 0
tx-usecs-high: 0
tx-frame-high: 0

```

Which is effectively an adaptive interrupt coalescing. The relevant code in ixgbevf driver hasn't changed  since the official ixgbevf-2.15. Bellow are code snippets from the `net-next` tree:

```
ixgbevf_sw_init():

        /* Enable dynamic interrupt throttling rates */
	adapter->rx_itr_setting = 1;
	adapter->tx_itr_setting = 1;

ixgbevf_set_coalesce():

        if (ec->rx_coalesce_usecs > 1)
		adapter->rx_itr_setting = ec->rx_coalesce_usecs << 2;
	else
		adapter->rx_itr_setting = ec->rx_coalesce_usecs;

ixgbevf_poll():

        napi_complete_done(napi, work_done);
	if (adapter->rx_itr_setting == 1)
		ixgbevf_set_itr(q_vector);   <---- This is the adaptive coalescing invocation
	if (!test_bit(__IXGBEVF_DOWN, &adapter->state) &&

static void ixgbevf_set_itr(struct ixgbevf_q_vector *q_vector)
{
	u32 new_itr = q_vector->itr;
	u8 current_itr;

	ixgbevf_update_itr(q_vector, &q_vector->tx);
	ixgbevf_update_itr(q_vector, &q_vector->rx);

	current_itr = max(q_vector->rx.itr, q_vector->tx.itr);

	switch (current_itr) {
	/* counts and packets in update_itr are dependent on these numbers */
	case lowest_latency:
		new_itr = IXGBE_100K_ITR;
		break;
	case low_latency:
		new_itr = IXGBE_20K_ITR;
		break;
	case bulk_latency:
		new_itr = IXGBE_12K_ITR;
		break;
	default:
		break;
	}

	if (new_itr != q_vector->itr) {
		/* do an exponential smoothing */
		new_itr = (10 * new_itr * q_vector->itr) /
			  ((9 * new_itr) + q_vector->itr);

		/* save the algorithm value here */
		q_vector->itr = new_itr;

		ixgbevf_write_eitr(q_vector);
	}
}
```

So, like I suspected the dynamic coalescing is enabled by default and your configuration disabled it.
Like I already mentioned - the 800us interrupt latency may be good for one workload but not so good for another. 

To get the idea of the actual numbers: their adaptive algorithm defines the lowest latency ("bulk latency") as 12K interrupts/sec which is ~10 times higher than the value you configured.
For a 10Gbps rate with the 1500B packets your coalescing configuration would make each interrupt to handle ~600 packets. Considering their NAPI budget configuration (64) it would coalesce about 10 interrupts. But NAPI is actually not about that type of coalescing...
However for full RSC aggregations it would make handle ~32 "packets" every interrupt and thus coalesce no interrupts at all.

The main problem with the configuration you suggest is that it is going to increase the latency up to 800us for a case when there are two consecutive Rx packets in the same 800us frame. 
Another problem is that for the throughput case with a lot of data this configuration will generate bursts of Rx processing which is also not a good thing.

But for some special cases, e.g. when latency is not important or when data comes in big chunks that take less than 800us to process in the kernel but more than 800us in the application level; then this configuration may be justified.

**Comment by vladzcloudius** [comment]
@avikivity @slivne Could you clarify what's the idea behind this ticket? Enable the adaptive interrupt mitigation? If yes, then this issue may be closed.

**Comment by avikivity** [comment]
With the default configuration I saw very high load on core 0 (about 20-30%), and since the node progresses at the speed of the slowest core, the node was slowed down severely.  After setting the parameter and enabling rps/xps, performance was increased significantly.

800us is very high, but perhaps there is some middle ground which recovers most of the performance without sacrificing latency too much.  We can enable it wherever we don't dedicate a core for networking.

**Comment by vladzcloudius** [comment]
If `posix_net_conf.sh` was ever enabled then XPS should have been enabled. This is what I see when I boot the 1.5 AMI on this instance:
```
$ cat /sys/class/net/eth0/queues/*/xps_cpus
0033
00cc
```

Which seems like and expected XPS configuration:
```
$ hwloc-distrib 2
0x00000033
0x000000cc
```

The interrupts are also seem to be distributed as expected:
```
$ sudo cat /proc/interrupts | grep eth0
100:       1939          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-TxRx-0
101:       1559        340          0          0          0          0          0          0  xen-pirq-msi-x     eth0-TxRx-1
102:         16          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0

$ sudo cat /proc/irq/100/smp_affinity
0011
$ sudo cat /proc/irq/101/smp_affinity
0022
$ sudo cat /proc/irq/102/smp_affinity
00cc
$ 
```

There isn't such thing as a "common ground" - the best or good performance depends on the specific load type. Like I've described above 800us is good for one load and is very bad for other. The adaptive interrupt mitigation, which is enabled by default, is meant to address this.

Now to the picture you are describing: according to the default configuration above having ONLY core 0 overloaded due to networking doesn't make any sense because if it was overloaded due to networking then it would be due to either Rx0 or/and Tx0 HW queues and in this case other cores (according to masks above) should have been overloaded too. 
Having a single CPU core under the configuration above would make me suspect some imbalance on the application side. 

Note that this specific instance type falls exactly on the boundary between the instances configured with and without a dedicated core. In addition it accidentally gets hit hard with the known limitation of detecting which IRQ handles a fast path queue(s) and which one handles a slow path queue. 
In the example above IRQ 102 handles slow path interrupts and it gets 2 physical cores while each FP IRQ (100 and 101) gets a single  physical core. 
The best configuration for this instance would be using the -sq configuration with a dedicated core for IRQs and RPS enabled because having and IRQ affinity set to more than one core has its own problems nicely described here: [Why interrupt affinity with multiple cores is not such a good thing](http://www.alexonlinux.com/why-interrupt-affinity-with-multiple-cores-is-not-such-a-good-thing).

**Comment by vladzcloudius** [comment]
I'll think on how we can improve the MQ/SQ mode selection heuristics in order to overcome the SP IRQ glitch.

**Comment by vladzcloudius** [comment]
I think Linux kernel doesn't support the round-robit interrupt distribution mentioned in the link above, so effectively there will be a single core that would handle the interrupts of a specific IRQ despite the mask that has a few set bits. So, what you must have seen was that Rx0 or Tx0 queue was working hard creating a lot of interrupts and by setting the value above you cut the interrupt rate by a factor of 10. 
But getting back to the interrupts configuration I think it would make sense the reconsider the MQ/SQ heuristics in a way that would avoid setting IRQ affinity to more than a to a single HW core.

**Comment by vladzcloudius** [comment]
What I wrote above was wrong: Linux kernel not only supports the "round-robin" interrupt distribution - it's its default mode. 

Like Alex described in general in [Why interrupt affinity with multiple cores is not such a good thing](http://www.alexonlinux.com/why-interrupt-affinity-with-multiple-cores-is-not-such-a-good-thing) it's called the *Lowest Priority* mode (see its short description here: [IOAPIC - OSDev wiki](http://wiki.osdev.org/IOAPIC) and a bit more detailed description here: [I/O Advanced Programmable Interrupt Controller](http://wiki.xomb.org/index.php?title=I/O_Advanced_Programmable_Interrupt_Controller).

The actual technique of working against the IO-APIC is described here [Understanding Linux Kernel, 3d Edition](https://www.safaribooksonline.com/library/view/understanding-the-linux/0596005652/ch04s06.html) (look for "IRQ distribution in multiprocessor systems").

Apparently not all APICs/BIOSes support it. From what I could observe on the `i2.2xlarge` it doesn't work. It could be that Amazon doesn't run the vanilla Linux kernel and they could have configured IO-APIC to work in a static mode or it could be that the underlying HW doesn't support it.  Funnily it's works nicely on my laptop (Dell Latitude E7440) running Ubuntu 16.04.  :D

This is for a single IRQ interrupts distribution in general.

But even if it worked every time it would still be bad because of the things Alex describe in its blog. In short it would be bad because it could cause of the excessive cache misses in the context of handling the Rx path of a specific connection because they would arrive from different cores since *Lowest Priority* doesn't take TCP or any Networking context into an account when it schedules the incoming interrupt to a specific CPU, in consults only the CPU availability at that specific moment.

So, having the affinity of a specific IRQ configured to more than 1 CPU is going to be suboptimal if compared to RPS, which takes the packet stream info into an account when redirecting it to a specific core (it's actually a SW RSS). 

So, I think the logic should be as follows: if we have enough IRQs to bind each CPU core to a separate IRQ then we should use the SMP affinity for load distribution (`mq` mode of `posix_net_conf.sh`), otherwise we should use RPS (`sq` mode of `posix_net_conf.sh`).

As for binding a separate CPU core for IRQs handling in a `sq` mode, I think it would make sense to limit it for machines having more than 4 physical cores because cutting 25% from the server's processing power seems a little wasteful. For such machines I suggest we bind each IRQ to a single core **and** enable RPS (this would be a new mode).

@avikivity @gleb-cloudius @tgrabiec Comments?

**Comment by avikivity** [comment]
We do dedicate a core for networking with machines with >= 8 cores.  However, on a machines with 4 cores (i2.2xlarge), core 0 is overloaded with networking.  So we need to reduce its load somehow (without dedicating it to networking only).  I saw we needed all of (rps, xps, interrupt mitigation) to get reasonable loads on core 0, but maybe a different configuration can yield better results.

**Comment by vladzcloudius** [comment]
On Jan 8, 2017 7:17 AM, "Avi Kivity" <notifications@github.com> wrote:

We do dedicate a core for networking with machines with >= 8 cores.
However, on a machines with 4 cores (i2.2xlarge), core 0 is overloaded with
networking. So we need to reduce its load somehow (without dedicating it to
networking only). I saw we needed all of (rps, xps, interrupt mitigation)
to get reasonable loads on core 0, but maybe a different configuration can
yield better results.


I agree. I'm preparing an RFC with changes to posix_net_conf.sh and will
send it on Monday. It's going to address the small machines case as well.


—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/1974#issuecomment-271147446>,
or mute
the thread

**Comment by slivne** [comment]
@vladzcloudius can we close this ?

**Comment by vladzcloudius** [comment]
@slivne Yes. It's fixed in the master but it's still present in both 1.6 and partially on 1.7.
