### ISSUE TITLE
Writes to system keyspace tables are bypassing commitlog

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1986]
The commitlog is initialized after system tables are populated, so `database::_commitlog` is `nullptr` at that time, and all those tables will run without commitlog.

```c++
future<>
database::init_system_keyspace() {
    bool durable = _cfg->data_file_directories().size() > 0;
    db::system_keyspace::make(*this, durable, _cfg->volatile_system_keyspace_for_testing());

    // FIXME support multiple directories
    return io_check(touch_directory, _cfg->data_file_directories()[0] + "/" + db::system_keyspace::NAME).then([this] {
        return populate_keyspace(_cfg->data_file_directories()[0], db::system_keyspace::NAME).then([this]() {
            return init_commitlog();
        });
    }).then([this] {
```

```c++

void database::add_column_family(keyspace& ks, schema_ptr schema, column_family::config cfg) {
    schema = local_schema_registry().learn(schema);
    schema->registry_entry()->mark_synced();

    lw_shared_ptr<column_family> cf;
    if (cfg.enable_commitlog && _commitlog) {
       cf = make_lw_shared<column_family>(schema, std::move(cfg), *_commitlog, _compaction_manager);
    } else {
       cf = make_lw_shared<column_family>(schema, std::move(cfg), column_family::no_commitlog(), _compaction_manager);
    }
```

**Comment by slivne** [comment]
can this explain the issue we have with batchlog replay test following the
update of calle to 3.X

extract from "Build failed in Jenkins: scylla-master-dtest »
monster,release,1 #228"

* batch_test.TestBatch.replay_after_schema_change_test*

 - changes to scylla-tools-java (nodetool flush) are not flushing system
tables any more. Once a killed node is restarted the batchlog + commitlog
are replayed - yet we are missing some insertions.

-  we need to decide if we are changing the test and flushing system table
/ checking if batchlog should have survived the failures since commitlog
should have replayed that part etc.

*Tomek* I think you created this test - thoughts - does cassandra pass this
test on 3.X branch ?

**Comment by tgrabiec** [comment]
@slivne Yes.
