### ISSUE TITLE
doc: update Raft info in version 6.1

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla#19932]
The information about Raft needs to updated. There's what I THINK should be done.
@kbr-scylla Please confirm or provide corrections or answers.

**1. Schema Changes**

- [Verifying that the Raft upgrade procedure finished successfully](https://opensource.docs.scylladb.com/stable/architecture/raft.html#safe-schema-changes-with-raft) - It should be removed. This procedure was still valid in 6.0, because a user might have disabled Raft-based schema changes in 5.4. It was impossible to disable the feature in 6.0, so there's no Raft upgrade procedure in 6.1
- Remove the References to Raft upgrade procedure.

**2. Topology changes** - The feature is automatically enabled in new clusters, but how about upgraded clusters?

-The previous upgrade guide included instructions to [Enable Consistent Topology Updates](https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/enable-consistent-topology.html). I THINK we need the same instuctions - exclusively for users who did not enable the feature when upgrading to 6.0. Is that correct? Or is enabling consistent topology updates somehow automated now and the default for both new and existing clusters?

That information is critical to other updates, as the docs now include references the procedure, especially in the _After Upgrading from 5.4_ sections in the docs for procedures, like [here](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/remove-node.html#after-upgrading-from-5-4).

Or should we assume that all 6.0 users have consistent topology updates enabled (as instructed in the upgrade guide)? - @tzach 

**3. Other** - Do we need to update anything else on the [Raft page](https://opensource.docs.scylladb.com/stable/architecture/raft.html)?

**Comment by kbr-scylla** [comment]
> [Verifying that the Raft upgrade procedure finished successfully](https://opensource.docs.scylladb.com/stable/architecture/raft.html#safe-schema-changes-with-raft) - It should be removed. This procedure was still valid in 6.0, because a user might have disabled Raft-based schema changes in 5.4. It was impossible to disable the feature in 6.0, so there's no Raft upgrade procedure in 6.1

This procedure still applies if one goes through the manual Raft recovery procedure, which is still possible even in 6.1. The recovery procedure links to this verification step.
https://opensource.docs.scylladb.com/stable/troubleshooting/handling-node-failures.html#manual-recovery-procedure

But it will be no longer referenced from the rolling (version) upgrade procedure.

Perhaps the contents of this "Verify" step could be modified because it currently says "You may need to perform the following procedure on upgrade if you explicitly disabled the Raft-based schema changes feature in the previous ScyllaDB version. Please consult the upgrade guide." So it doesn't currently mention the path of manual recovery. In 6.1 this is the only path where this procedure is needed, so it may make sense to modify this paragraph.

> 2. Topology changes - The feature is automatically enabled in new clusters, but how about upgraded clusters?

Same as in 6.0. If upgrade-to-raft-based-topology wasn't performed in 6.0, they should perform it in 6.1.

> -The previous upgrade guide included instructions to [Enable Consistent Topology Updates](https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/enable-consistent-topology.html). I THINK we need the same instuctions - exclusively for users who did not enable the feature when upgrading to 6.0. Is that correct?

Correct. We didn't automate it.

> Or should we assume that all 6.0 users have consistent topology updates enabled (as instructed in the upgrade guide)? - @tzach

We should not assume, but we should probably recommend it.

> 3. Other - Do we need to update anything else on the [Raft page](https://opensource.docs.scylladb.com/stable/architecture/raft.html)?

Not that I know of.
