### ISSUE TITLE
Need to improve cache

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2011]
Installation details
version : scylla 1.5 / SSD / cetos / 3node / 16core 48GB / bare metal server
              cassandra 3.9

I tested performance comparison of scylla vs cassandra

test result..
![image](https://cloud.githubusercontent.com/assets/10610884/21925123/548b125a-d9bf-11e6-90ac-0d914194b2f4.png)

*1.2GB disk io is really amazing

scenario
 - read only
 - sql : select * from test_table where partition_key='aa'  limit 10;
 - partition size is about 13MB
   => sql will get a little data of partition..

now scylladb don't have key cache and  caches the entire data of partition.
so read performance is poor in this scenarios (reading a little part of data on large partition)
there seems to be no way for scylla to beat cassandra in this scenarios 

I think that Scylla have to improve cache 
  - key cache / caching some data on large partition...

Let me know if there is a way to beat cassandra in this scenario

![image](https://cloud.githubusercontent.com/assets/10610884/21918698/70b59572-d997-11e6-90cd-25543accd864.png)

![image](https://cloud.githubusercontent.com/assets/10610884/21918700/7a22f848-d997-11e6-81e0-171583a7a24c.png)

![image](https://cloud.githubusercontent.com/assets/10610884/21918707/82a63e62-d997-11e6-8704-b437c21d54be.png)

![image](https://cloud.githubusercontent.com/assets/10610884/21918708/8abe3d84-d997-11e6-809e-3f7a5a80ed62.png)

**Comment by penberg** [comment]
Are the read I/O numbers reversed for Scylla and Cassandra? That is, isn't it Scylla that's reading 1.2 GB? If I remember correctly, Scylla doesn't cache large partitions at all after a certain threshold.

/cc @avikivity

**Comment by infordb** [comment]
@penberg  you are right.  I mistyped I revised it
I remember that Scylla dicides a partition larger than 10M as a large partition 
and scylla doesn't cache large partitions at all
this scenario may be large partition...
By the way why does cache hit increase ? I think it is problem with metric..

**Comment by tgrabiec** [comment]
Refs #960

**Comment by slivne** [comment]
@infordb  - yes we are working to improve the cache - to have it in row level

- Is this the first scan of the partition or consecutive scans (we cache the info that a partition is large - so consecutive reads will have less io)

- Another item related to this is #1842 (that is also in progress) - if the partitions are very large you can modify the (min_index_interval / max_index_interval) - so that scylla will have less promoted-index (https://github.com/scylladb/scylla/wiki/SSTables-Index-File) when searching for the correct index entry of the partition.

**Comment by tzach** [comment]
duplicate with #960 and #1842
