### ISSUE TITLE
nodetool clearsnapshot not freeing space

### ISSUE THREAD

**Issue by dbathgate** [scylladb/scylla#2045]
*Installation details*
Scylla version (or git commit hash): 1.5
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

*Hardware details*
AWS: c4.2xlarge
Platform (physical/VM/cloud instance type/docker): AWS
Disks: (SSD/HDD, count): single 1TB EBS

I dropped and recreated a table with 25GB of sstable storage, which created a snapshot.
Running `nodetool clearsnapshot` did not free the 25 GB of storage.
I had also received a timeout error when dropping the table.

```
> drop table usertable ;
OperationTimedOut: errors={}, last_host=10.25.1.159

> create table usertable (     y_id varchar primary key,     field0 varchar,     field1 varchar,     field2 varchar,     field3 varchar,     field4 varchar,     field5 varchar,     field6 varchar,     field7 varchar,     field8 varchar,     field9 varchar);
```

````
$ nodetool clearsnapshot
Requested clearing snapshot(s) for [all keyspaces]

$ du -sh *
0	usertable-39fbe240e3ea11e6b3ee000000000000
25G	usertable-58721d50e3dd11e6953c000000000001

$ du -sh usertable-58721d50e3dd11e6953c000000000001/snapshots/1485450577674-usertable/
25G	usertable-58721d50e3dd11e6953c000000000001/snapshots/1485450577674-usertable/
````

**Comment by vladzcloudius** [comment]
I'll take a look.

**Comment by vladzcloudius** [comment]
@dbathgate The timeout you saw was a cqlsh timeout. It happened because the DROP operation actually took a long time: on my laptop it took about 3 minutes. 
You may control the cqlsh timeout using the `request_timeout` parameter in the `cqlshrc`.

The snapshot in your report is created as a result of the `DROP TABLE` command.
I noticed that the snapshots of dropped tables are not deleted by the `nodetool clearsnapshot` while it clears the snapshots of alive tables just fine. 

We need to fix that.
