### ISSUE TITLE
Recommended storage size per node

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2052]
What is the maximum storage capacity one hyperthreading core can handle?

dor said "A general rule of the thumb is 1TB of SSD per 4 cores or 10TB per node." at https://groups.google.com/forum/#!msg/scylladb-users/j_21dRCFflo/MhfDYRoABAAJ

Is this mean that machine with 32core with hyperthreading can handle 8Tera Data ? 

If this is correct,
Does the machine  need 12Tera(8tera + 4tera) disk considering compaction margin(50%)?

Please give me more advice about storage.

**Comment by dorlaor** [comment]
Well, it really depends how this data get accessed.
Data that get accessed (rd or wr) frequently needs more cpu power and the opposite.
That's why there is rule of the thumb but in practice it needs to match your usage pattern.
We have a user who managed to store 60TB (tera) on a medium server but they didn't
access the data that much. 

You'd need to leave enough space for the compaction margin if you use STCS (and less for the others). The rule is 50% (for your largest table, not all of the tables) but in practice it can be much lower since not all of the cores will compact the largest sstable at once. 

Hope it helps. If you need very accurate answer, I'd just produce the data with the right schema and access pattern using cassandra-stress
