### ISSUE TITLE
H/W Spec

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2054]
I think your H/W spec is very high

![image](https://cloud.githubusercontent.com/assets/10610884/22580847/284c7c36-ea1f-11e6-83de-28f13285000b.png)

In general, we use  8 , 16 cores
In particular, customers don't want to use high spec machine for nosql.

Could you provide a recommendation value in the form below?
Of course, I think it may be different by usecase.
However, standards are needed in general situations.

![image](https://cloud.githubusercontent.com/assets/10610884/22581026/6b1a0500-ea20-11e6-84e7-ac42a0ba1ead.png)

**Comment by dorlaor** [comment]
Some do need high end machines and some can settle for low end.
When a user has the option to chose and the cluster size is large, the rule
of the thumb is to reduce the number of machines as much as possible. This 
reduces any potential distributed computing effect and increases utilization.
Although Scylla (and Cassandra) scales out with the number of machines, the scaling
has some overhead and thus is better to shrink the number of machines.
It's good in terms of MTBF too.

It's good to maintain a ratio ram:core of 4GB:1. The storage ration is harder to say
since it depends on the workload a lot. 
I'll close this issue since this isn't a bug report nor a feature request.
