### ISSUE TITLE
scylla: database.cc:1003: future<> column_family::seal_active_memtable(memtable_list::flush_behavior): Assertion `_highest_flushed_rp < old->replay_position() || (_highest_flushed_rp == db::replay_position() && old->replay_position() == db::replay_position())' failed.

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2074]
*Installation details*
Scylla version (or git commit hash):  bb72425b612304f2586d8a9d64b25775f3ee3648

this does not reproduce easily but it does from time to time

it started happening wehn we enables runnig tests in parallel - maybe related to timing.

```
INFO  2017-02-12 14:45:00,984 [shard 0] gossip - InetAddress 127.0.7.2 is now UP, status = NORMAL
INFO  2017-02-12 14:45:00,984 [shard 0] storage_service - Node 127.0.7.2 state jump to normal
INFO  2017-02-12 14:45:01,049 [shard 0] compaction - Compacted 4 sstables to [/data2/jenkins/.dtest/dtest-jfVQVi/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-66-Data.db:level=0, ]. 13444 bytes to 12688 (~94% of original) in 109ms = 0.111011MB/s. ~1024 total partitions merged to 1.
INFO  2017-02-12 14:45:01,088 [shard 1] compaction - Compacting [/data2/jenkins/.dtest/dtest-jfVQVi/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-43-Data.db:level=0, /data2/jenkins/.dtest/dtest-jfVQVi/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-51-Data.db:level=0, /data2/jenkins/.dtest/dtest-jfVQVi/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-45-Data.db:level=0, /data2/jenkins/.dtest/dtest-jfVQVi/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-41-Data.db:level=0, ]
INFO  2017-02-12 14:45:01,130 [shard 0] gossip - InetAddress 127.0.7.3 is now UP, status = NORMAL
INFO  2017-02-12 14:45:01,130 [shard 0] storage_service - Node 127.0.7.3 state jump to normal
INFO  2017-02-12 14:45:01,146 [shard 1] compaction - Compacted 4 sstables to [/data2/jenkins/.dtest/dtest-jfVQVi/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-53-Data.db:level=0, ]. 37072 bytes to 12246 (~33% of original) in 58ms = 0.201357MB/s. ~1024 total partitions merged to 1.
INFO  2017-02-12 14:45:01,147 [shard 0] storage_service - Node 127.0.7.1 state jump to normal
scylla: database.cc:1003: future<> column_family::seal_active_memtable(memtable_list::flush_behavior): Assertion `_highest_flushed_rp < old->replay_position() || (_highest_flushed_rp == db::replay_position() && old->replay_position() == db::replay_position())' failed.
Aborting on shard 0.
Backtrace:
  0x000000000048ec02
  0x000000000048ed33
  0x00007f861dc635bf
  0x00007f861d8c191e
  0x00007f861d8c3519
  0x00007f861d8b9da6
  0x00007f861d8b9e51
  0x00000000007bbb7e
  0x00000000007bcd7d
  0x0000000000756b66
  0x000000000076b760
  0x000000000076bcef
  0x000000000076c54e
  0x0000000000490769
  0x00000000004dd2da
  0x000000000055d53e
  0x00000000004213d7
  0x00007f861d8ac400
  0x000000000048c739
```

**Comment by duarten** [comment]
@slivne Did you use a package or did you compile scylla by yourself? If so, can you decode the backtrace? If you don't have it anymore, any tips on how to reproduce this?

**Comment by duarten** [comment]
Nevermind, I just noticed the bug is old.

**Comment by duarten** [comment]
So far I have been unable to reproduce the issue, despite having some dtests looping for almost 3 days. But I read a bunch of code.

The only way I can make sense of the assertion triggering is if there isn't an actual guarantee that mutations will be written to memtables with a monotonically increasing `db::replay_position`.

If that is the case, then a flush in the wrong place can flush a memtable with `replay_position` `rp'`, while a previous write is applied to the new memtable with `replay_position` `rp''`, where `rp'' < rp'`.

Now, the question is whether writes could indeed be re-ordered after having obtained a `replay_position`. I suspect the commitlog itself can re-order replay positions if it is in batch mode, but I'm not yet sure. The dirty memory manager, however, seems like it can definitely reorder the requests when we call `run_when_memory_available()`: a fiber, having obtained a `replay_position` is blocked by the dirty manager and subsequently released; upon release, it is scheduled behind another fiber with a higher `replay_position`, which is not blocked by the dirty memory manager and thus applies the write in memory. A flush at this point can cause the aforementioned issue.

I wonder if we should schedule released fibers as urgent - it could make sense to avoid them being reordered with newer requests and increase their chances of being timed out. Thoughts, @avikivity & @glommer?

Anyway, the fix shouldn't rely on `schedule_urgent()`. Since `replay_position`s have been relaxed since 0dfe1ad43, we can simply issue monotonically increasing numbers to memtables themselves and use that for the `flush_queue`, and stop tracking `_highest_flushed_rp`.

**Comment by tgrabiec** [comment]
Looks like happens also with 1.7.2

**Comment by tgrabiec** [comment]
The problem I am hitting is due to some of the system tables (compaction_history in particular) being flushed concurrently with commitlog replay. Because replay is applying mutations with empty replay positions, it can happen that there will be a memtable created entirely by replay with no _replay_position, but _highest_replay_position will not be empty due to earlier flushes.

```
TRACE 2017-07-06 12:36:32,603 [shard 0] database - apply {system.compaction_history key {key: pk{0010fa59bab0623611e78d6b000000000000}, ...
DEBUG 2017-07-06 12:36:32,603 [shard 0] database - Sealing active memtable of compaction_history.system, partitions: 1, occupancy: 0.42%, 1104 / 262144 [B]

DEBUG 2017-07-06 12:36:32,611 [shard 0] commitlog_replayer - replaying at b4dbb7b4-dc49-3fb5-b3bf-ce6e434832ca v=b7ecaf8a-49da-3462-8d54-510a017926b7 system:compaction
_history at {0, 12848125, 157277}

DEBUG 2017-07-06 12:36:32,611 [shard 0] commitlog_replayer - replaying at b4dbb7b4-dc49-3fb5-b3bf-ce6e434832ca v=b7ecaf8a-49da-3462-8d54-510a017926b7 system:compaction
_history at {0, 12848125, 158328}


DEBUG 2017-07-06 12:36:33,729 [shard 0] database - Sealing active memtable of compaction_history.system, partitions: 5, occupancy: 2.13%, 5584 / 262144 [B]

```

**Comment by tgrabiec** [comment]
#2550 together with 0dfe1ad43142446121a1f0e327a92455e33ac11c and 9eb91bc30b44de6ed89146bca1249ba94732a39d make running into the problem much more likely on master.

**Comment by duarten** [comment]
@tgrabiec Thanks! I'm still failing to repro on master. Replay always goes well for me:

```
INFO  2017-07-06 13:27:55,914 [shard 0] commitlog_replayer - Replaying tmp/CommitLog-1-6616145.log, tmp/CommitLog-1-6616148.log, tmp/CommitLog-1-6616149.log, tmp/CommitLog-1-6616150.log, tmp/CommitLog-1-6616151.log
INFO  2017-07-06 13:27:57,164 [shard 0] commitlog_replayer - Log replay complete, 244747 replayed mutations (0 invalid, 0 skipped)
```

**Comment by duarten** [comment]
Well, try as I might, I can't get it to repro on master :( 

Anyway, I think the solution I proposed also fixes this case.

**Comment by tgrabiec** [comment]
@duarten I don't think the reorder due to `run_when_memory_available()` is possible. `region_group` runs all callbacks in-order. New callbacks block as long as there are any old callbacks, so they can't jump before them. Callbacks are run atomically with removal from _blocked_requests. There is no deferring point there.

**Comment by duarten** [comment]
@tgrabiec Oh, I see. You're right. Then I'm still at a loss as to how the reordering happens. I guess it must come from the commitlog itself.

**Comment by duarten** [comment]
In `apply_with_commitlog()` we do `cf.commitlog()->add_entry(...).then( /* apply in memory */)`. Is it possible that the continuations are reordered? For example, if one fiber allocates a new commit log segment, and when it finishes the continuation is schedule behind a new write, which is able to write to the commitlog without deferring?

**Comment by tgrabiec** [comment]
@duarten Yes, such cases were supposed to be guarded for by column_family::check_valid_rp(), which triggers retry on reordering. But after 0dfe1ad43142446121a1f0e327a92455e33ac11c, check_valid_rp() only guards against truncate low water mark. So perhaps this assert should only guard against that too?

I also suggested in the past that we could just drop mutations with timestamps below the truncate water mark, they raced with truncate, so could have been dropped anyway.

**Comment by duarten** [comment]
@tgrabiec Thanks! Your suggestion to drop mutations that race with a truncate makes sense; that's just treating `replay_position_reordered_exception` differently, right? That would ensure we can't flush memtables whose highest replay position is smaller than the truncate water mark, so the assert makes sense.

I also think the approach of ordering memtables with a different, monotonically increasing id, still stands, to be able to correctly implement `flush()`, no?

**Comment by tgrabiec** [comment]
@duarten I don't follow, can you describe the problem you want to solve with those monotonically increasing ids?

**Comment by duarten** [comment]
@tgrabiec Since now we don't ensure mutations are applied in memory following the order of their replay positions, then a memtable can be flushed with replay position `rp`, with the new one being at replay position `rp'`, where `rp' < rp`. Memtable flushes are ordered in a `memtable_flush_queue` by replay position. Now, waiting for `rp'` could give the wrong results, since the flush queue already saw the bigger `rp`. As far as I can tell, this can happen in `column_family::flush()`.

**Comment by tgrabiec** [comment]
Right, flush() needs to wait for all prior flushes. Perhaps we could simplify things by replacing flush_queue with a phased_barrier, where each flush would start an operation, and flush() would advance_and_wait().

**Comment by duarten** [comment]
Makes sense. I'll start preparing patches.

**Comment by slivne** [comment]
we need to backport this to 2.0

the master build was good and the failed dtests pass on master

http://jenkins.cloudius-systems.com:8080/view/scylla-master/job/scylla-master-dtest/label=monster,mode=release,smp=1/466/

**Comment by duarten** [comment]
@slivne It's already backported.
