### ISSUE TITLE
Support termination of repair jobs.

### ISSUE THREAD

**Issue by mdevan** [scylladb/scylla#2105]
```
$ curl -X POST 'http://localhost:10000/storage_service/force_terminate'
{"message": "API call is not supported yet", "code": 500}
```

```
    ss::force_terminate_all_repair_sessions.set(r, [](std::unique_ptr<request> req) {
        //TBD
        unimplemented();
        return make_ready_future<json::json_return_type>(json_void());
    });
```

Please support termination of running repair jobs.

**Comment by dorlaor** [comment]
@amnonh @asias can you have a look?

**Comment by tzach** [comment]
Some context: Its missing since we started with operations used by nodetool. Since there is no nodetool command to stop a repair[1], people use JMX endpoint forceTerminateAllRepairSessions, which mapped to the unimplemented REST  operation.
@amnonh please keep my honest on the JMX to REST mapping


[1] https://issues.apache.org/jira/browse/CASSANDRA-3486
