### ISSUE TITLE
grafana metric

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2106]
I have a question about grafana metric

we set the graph x axis unit to ms, why multiply by 1000000?
(Scylla Per-Server Disk I/O 1.6)

1000000*max(scylla_io_queue_delay_compaction{}) by (instance)

![image](https://cloud.githubusercontent.com/assets/10610884/23246230/74fe4288-f9d5-11e6-96d3-6c6146d87820.png)

![image](https://cloud.githubusercontent.com/assets/10610884/23246207/60328008-f9d5-11e6-9c57-5d150b85a9f9.png)

**Comment by tgrabiec** [comment]
@infordb Did you mean "Y axis to us" (that's what the screenshot says) instead of "X axis to ms"? 

The original value of scylla_io_queue_delay_compaction is in seconds (floating point). After we multiply by 10^6, it will be in microseconds. We do this for convenience of presentation. Grafana seems to be able to automatically switch to higher units on the scale, but not to lower units. So if the unit is "us", it can switch to "ms" and "s", but if it was "s", it would not scale down, you would see "0.00001 s" instead of "10 us".

**Comment by infordb** [comment]
What you say is right. Y axis to us
Thank you for feedback
It has helped a lot

**Comment by tzach** [comment]
>  Grafana seems to be able to automatically switch to higher units on the scale, but not to lower units.

@tgrabiec this issue was solved in Grafana https://github.com/grafana/grafana/issues/5955 (thanks to @glommer !)
and is part of Grafana 4.1.1 which is part of the latest https://github.com/scylladb/scylla-grafana-monitoring

**Comment by glommer** [comment]
On Thu, Feb 23, 2017 at 7:32 AM, Tzach Livyatan <notifications@github.com>
wrote:

> Grafana seems to be able to automatically switch to higher units on the
> scale, but not to lower units.
>
> @tgrabiec <https://github.com/tgrabiec> this issue was solved in Grafana
> grafana/grafana#5955 <https://github.com/grafana/grafana/issues/5955>
> (thanks to @glommer <https://github.com/glommer> !)
> and is part of Grafana 4.1.1 which is part of the latest
> https://github.com/scylladb/scylla-grafana-monitoring
>

If newer grafana can handle this, we can probably get rid of that now. It
definitely confuses people.
