### ISSUE TITLE
What are the factors that determine max-io-requests

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2140]
I think max-io-requests are proportional to IOPS
but under result is not ..
What are the factors that determine max-io-requests?

<server 1 / --smp 16 >
/usr/lib/scylla/scylla_io_setup
Generating evaluation file sized 10GB...10GB written in 6 seconds
Refining search for maximum. So far, 189,348 IOPS
Maximum throughput: 189348 IOPS
Recommended --max-io-requests: 60
Recommended --num-io-queues: 15

<server2 / --smp 8>
/usr/lib/scylla/scylla_io_setup
Generating evaluation file sized 10GB...10GB written in 11 seconds
Refining search for maximum. So far, 147188 IOPS
Maximum throughput: 147390 IOPS
Recommended --max-io-requests: 66

**Comment by glommer** [comment]
Hi

That measures the parallelism the disk can offer. After that parallelism is
reached, IOPS will not increase but latency will.

It is totally possible that a disk archives higher IOPS with lower
parallelism.

Also, note that this is a statistical process and is prone to errors. If
the errors are small relatively to the number of cores ( in this case they
are) it won't mean much.


On Mar 6, 2017 7:51 PM, "Junghyun Park" <notifications@github.com> wrote:

I think max-io-requests are proportional to IOPS
but under result is not ..
What are the factors that determine max-io-requests?

<server 1 / --smp 16 >
/usr/lib/scylla/scylla_io_setup
Generating evaluation file sized 10GB...10GB written in 6 seconds
Refining search for maximum. So far, 189,348 IOPS
Maximum throughput: 189348 IOPS
Recommended --max-io-requests: 60
Recommended --num-io-queues: 15

<server2 / --smp 8>
/usr/lib/scylla/scylla_io_setup
Generating evaluation file sized 10GB...10GB written in 11 seconds
Refining search for maximum. So far, 147188 IOPS
Maximum throughput: 147390 IOPS
Recommended --max-io-requests: 66

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/2140>, or mute the thread

**Comment by infordb** [comment]
@glommer 
I don't understand follow comments 
"If the errors are small relatively to the number of cores ( in this case they
are) it won't mean much."
Could you explain it more detail...

Is it currently best to use scylla_io_setup result?

**Comment by glommer** [comment]
What I meant is that a difference between 60 and 66 is not very
significant.

You can use those results just fine

On Mar 7, 2017 1:15 AM, "Junghyun Park" <notifications@github.com> wrote:

@glommer <https://github.com/glommer>
I don't understand follow comments

"If the errors are small relatively to the number of cores ( in this case
they
are) it won't mean much."
Could you explain it more detail...

Is it currently best to use scylla_io_setup result?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/2140#issuecomment-284632166>,
or mute
the thread

**Comment by infordb** [comment]
@glommer 
The servers below are very different
396 IOPS / max-io-requests: 129
The worst disk has the highest concurrent request count.
And,  The num-io-queues parameter is not set, what is default value ?
in this case, I think I need to manually modify it, are there any recommendations for this?


<server 3 / --smp 8 >
[root]fomstap02:/usr/lib/scylla>./scylla_io_setup
Generating evaluation file sized 10GB...10GB written in 82 seconds
Refining search for maximum. So far, 396 IOPS
Maximum throughput: 396 IOPS
Recommended --max-io-requests: 129
Written the above values to /etc/scylla.d/io.conf

**Comment by glommer** [comment]
On Tue, Mar 7, 2017 at 7:32 PM, Junghyun Park <notifications@github.com>
wrote:

> @glommer <https://github.com/glommer>
> The servers below are very different
> 396 IOPS / max-io-requests: 129
> The worst disk has the highest concurrent request count.
> And, The num-io-queues parameter is not set, what is default value ?
> in this case, I think I need to manually modify it, are there any
> recommendations for this?
>

The default number of io-queues is the same amount of cpus. Our
recommendation is to add at least 4 requests per I/O queue. So if you have,
for example, 20 cpus, and 40 --max-io-requests, you should set
--num-io-queues to 10 (40 / 4)

**Comment by infordb** [comment]
@glommer 
If max-io-requests is not a multiple of 4
How are concurrent requests per queue assigned?
--smp 4 --max_io_requests 17
I/O queue count : 4 , one of queues has 5 concurrent requests ..

**Comment by glommer** [comment]
On Tue, Mar 7, 2017 at 7:57 PM, Junghyun Park <notifications@github.com>
wrote:

> @glommer <https://github.com/glommer>
> If max-io-requests is not a multiple of 4
> How are concurrent requests per queue assigned?
> --smp 4 --max_io_requests 17
> I/O queue count : 4 , one of queues has 5 concurrent requests ..
>

All those measurements are statistical in nature. Seastar/Scylla should be
able to take all of that into account by rounding it up or down.

This setup with --num-io-queues 4 --max-io-requests is fine.

**Comment by infordb** [comment]
@glommer 
I think max-io-requests value is very high
Should I modifiy it manually ? 
396 IOPS / max-io-requests: 129

**Comment by glommer** [comment]
On Tue, Mar 7, 2017 at 8:13 PM, Junghyun Park <notifications@github.com>
wrote:

> @glommer <https://github.com/glommer>
> I think max-io-requests value is very high
> Should I modifiy it manually ?
> 396 IOPS / max-io-requests: 129
>

It does look high - and indeed a very low IOPS rate. What kind of disk is
that ?

**Comment by infordb** [comment]
@glommer 
this machine is desktop pc with low cost ssd
not a server

**Comment by glommer** [comment]
That still seems extremely slow. That's 1MB/s at 4kB requests, even HDDs
should be doing more than that.

maybe iotune has an issue that this particular setup is exposing.

If you can, my recommendation would be run diskplorer in this disk, which
don't do statistical sampling, but rather scans the entire disk range
(takes a long, long time). Then we can manually find out what's the best
for it.

Diskplorer can be found here:

https://github.com/avikivity/diskplorer

But I must ask: are you doing performance evaluations in this setup? If you
are not, you don't have to set up the I/O system at all. Just leave it
blank, and boot scylla with --developer-mode 1

**Comment by infordb** [comment]
@glommer 
I am currently in the operating environment setting.
My question is that  max-io-requests  is different for each server spec. Unlike what I expected
as you sad, I can boot scylla with --developer-mode in development environment, not operating 
Thank you for comment

**Comment by tzach** [comment]
@infordb if you got the answer to your question - can we close this ticket?
If not, please let us know
