### ISSUE TITLE
Allow filtering on clustering columns for queries without secondary indexes

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2200]
*Installation details*

Support filtering on clustering-columns:

```
CREATE TABLE emp_table2 (
empID int,
firstname text,
lastname text,
b_mon text,
b_day text,
b_yr text,
PRIMARY KEY (empID, b_yr, b_mon, b_day));

SELECT b_mon,b_day,b_yr,firstname,lastname FROM emp_table2
WHERE b_mon='oct' ALLOW FILTERING;
```

https://issues.apache.org/jira/browse/CASSANDRA-11310

**Comment by oiime** [comment]
any plans to implement this in the near future?

**Comment by tzach** [comment]
@oiime its on the roadmap, but not for the short term. `ALLOW FILTERING` means it's not efficient, and the right way is to use sec index, which will be available as experimental in 2.1
https://github.com/scylladb/scylla/issues/401

**Comment by oiime** [comment]
@tzach thanks, about it being inefficient, obviously, but there are a lot of reasonable use cases where you'd need ALLOW FILTERING and not secondary indexes, ultimately whenever you prefer to defer a full table scan to the db instead of doing it on the client side. or in my case state tables which are smaller and infrequently used so performance is not an issue but need to be queried from different perspectives including <> time ranges. there is a good reason why it's in cassandra, the alternative is requiring additional db software just to maintain such tables while the job can easily be done in same db solution (while being fully aware it is not supposed to be 'efficient')

**Comment by tzach** [comment]
Thanks, @oiime good inputs. We will look into expediting this.

**Comment by oiime** [comment]
@tzach thank you for the prompt response, it's a pretty impressive project and we are considering moving part of the operation to it as we're very latency-sensitive. this might be off-topic but do you have a more thorough compatibility grid beyond http://docs.scylladb.com/cassandra-compatibility ? there are a lot of minor differences and so far the only way to catch them is trial and error

**Comment by tzach** [comment]
No, unfortunately, we do not have more detailed compatibility matrix at the moment.
You can filter the github issues by compatibility labels for more info:
https://github.com/scylladb/scylla/issues?q=is%3Aopen+is%3Aissue+label%3A%22cassandra+2.2+compatibility%22
https://github.com/scylladb/scylla/issues?q=is%3Aopen+is%3Aissue+label%3A%22cassandra+3.x+compatibility%22
https://github.com/scylladb/scylla/issues?q=is%3Aopen+is%3Aissue+label%3A%22cassandra+4.x+compatibility%22

**Comment by penberg** [comment]
I tested @tzach's CQL query and it works with 3.0-rc3. @psarna, can you point us to the commit that implements the functionality so that we close this issue?

**Comment by psarna** [comment]
c126b0079 introduced filtering of both regular and primary key columns. There were also multiple fixes related to filtering that were merged later, but this one is a good reference.

**Comment by slivne** [comment]
this is supported on 3.0.X
