### ISSUE TITLE
Improve reporting of sstable corruption

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2347]
If an sstable is corrupted, we should report it together with its keyspace and table name.  The message catalog (`journalctl -x`) should contain a pointer to documentation about remedial action.

**Comment by slivne** [comment]
@psarna ping

**Comment by psarna** [comment]
I'm waiting for sstables 3.x first - these patches would be in collision with 3.x support, so I'll rebase and rewrite them once sstables 3.x are done.

**Comment by slivne** [comment]
@bhalevy please reuse what ever @psarna had once you handle this

**Comment by bhalevy** [comment]
@espindola please take it from here

**Comment by espindola** [comment]
As far as I can tell what is needed is

* Update every malformed_sstable_exception to know which file is corrupted
* Add support in seastar for using sd_journal_send instead of syslog (or just replace syslog?)
* Make sure we always catch and log malformed_sstable_exception.  So far only distributed_loader::probe_file seems to do it.
* Write a catalog entry pointing to https://docs.scylladb.com/troubleshooting/sstable_corruption/
* Install the catalog in /usr/lib/systemd/catalog/

**Comment by bhalevy** [comment]
@espindola the journal related items you mentioned above are in a broader scope of this particular issue.
Please discuss that on the mailing list so we get input from a broader forum.

**Comment by bhalevy** [comment]
Can this issue be put to rest?

**Comment by espindola** [comment]
I don't think so. There were two parts of this issue
* Including info in the journal
* Better handling of corrupted sstables and testing of that

I haven't been able to put any time on either

**Comment by bhalevy** [comment]
We can close the reporting part.
We have now better coverage of testing of corrupt sstables using the scrub compaction dtest that inserts random corruption into sstables and compacts them using scrub compaction.
let's open particular issues based on mid-handling of corrupt sstables as we identify them.
