### ISSUE TITLE
std::bad_alloc (std::bad_alloc)

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2359]
version : scylla-1.6.1-20170218.2ea4da2.el7.centos.x86_64

We have been doing long term write tests since 4/28
But, today(5/8) node#1 was down, other 2node was not working
now data size is about 2Tera

## node1 log
![image](https://cloud.githubusercontent.com/assets/10610884/25793379/1a4052d4-3407-11e7-84ea-f341d8df3f0f.png)

## node2 log
![image](https://cloud.githubusercontent.com/assets/10610884/25793387/269e0b70-3407-11e7-9f6c-8a5e08c3374f.png)

## node3 log
![image](https://cloud.githubusercontent.com/assets/10610884/25793396/35a947a6-3407-11e7-97fc-06034be68eac.png)

##metric-io-3hour
![metric-io-3h](https://cloud.githubusercontent.com/assets/10610884/25793501/c11f5eba-3407-11e7-8aad-53e42986a4aa.png)
##metric-io-full
![metric-io-all](https://cloud.githubusercontent.com/assets/10610884/25793503/c1260ba2-3407-11e7-957f-08d3222bb07d.png)

##metric-3hour
![metric-3h_1](https://cloud.githubusercontent.com/assets/10610884/25793504/c139220a-3407-11e7-9146-202e84de8871.png)

##metric-full
![metric-all](https://cloud.githubusercontent.com/assets/10610884/25793502/c1248426-3407-11e7-88d9-7357d1c13f94.png)

**Comment by tgrabiec** [comment]
Non-LSA memory is constantly growing, which it shouldn't, and eventually the node runs out of memory. 

Can you upload [1] the core dump to our S3 bucket for analysis? 

[1] https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem#send-the-core-dump

**Comment by tgrabiec** [comment]
It could be due to amount of sstable metadata.

@infordb Can you run this in your data directory (refs #2125):

```
find -type f -printf '%f %s\n' | awk '{ n = split($1, a, "-"); comp[a[n]] += $2 } END { for (c in comp) print comp[c], c }'  | sort -nr
```

**Comment by infordb** [comment]
@tgrabiec 
1942723410609 Data.db
13902380976 CompressionInfo.db
6294414814 Index.db
10724172 Summary.db
656656 Filter.db
358128 Statistics.db
8080 TOC.txt
3040 Scylla.db
808 TOC.txt.tmp
776 Digest.sha1
Unfortunately, the core dump file was not created because of coredump dir space shortage.

**Comment by infordb** [comment]
I think scylla can not sustain a 2Tera compaction load.
server spec
  --smp 8 -m 20G --max-io-requests=69
   (physical core 6core 32G memory)

**Comment by tgrabiec** [comment]
The total size of in-memory sstable components in your case is about 20 GiB (CompressionInfo, Index, Summary, Filter), which explains why we run out of memory.

Are you suggesting that most of that 2 TiB is not live data? After you stop the load, does the disk usage drop?

We currently don't throttle writes based on compaction backlog, there is an open issue about this #1369.

Scylla currently stores some metadata for each sstable in memory, so with increased disk usage comes increased RAM usage. For 20 GiB and 2 TiB, the memory to disk ratio is 1%.

Compression info is the biggest culprit here. There is a way to reduce this. Depending on your workload, you could either disable compression, or increase the compression chunk lengths. It is 4KiB by default for Scylla (larger on Cassandra). The larger the block size, the smaller the compression info, but uncached reads may suffer because the whole block needs to be decompressed.

Those parameters can be changed using [alter table](http://docs.datastax.com/en/cql/3.1/cql/cql_reference/alter_table_r.html#reference_ds_xqq_hpc_xj__alter-compression) CQL statement. Note that it will have effect for newly written sstables, so you would see the effect after old ones are compacted (you can force using `nodetool compact`).

**Comment by infordb** [comment]
@tgrabiec 
1. Our total live data is about 3.5 Tera
  
2.  Is the index file always cached in memory?
    The index file is also quite large.

3.  Does sstable meta (CompressionInfo, Index, Summary, Filter) use non-lsa memory ?

4. if I change chunk_length_kb from 4k to 64k,  Can the std :: bad_alloc problem be solved?

**Comment by dorlaor** [comment]
On Tue, May 9, 2017 at 5:14 PM, Junghyun Park <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec>
>
>    1.
>
>    Our total live data is about 3.5 Tera
>    2.
>
>    Is the index file always cached in memory?
>    The index file is also quite large.
>    3.
>
>    Does sstable meta (CompressionInfo, Index, Summary, Filter) use
>    non-lsa memory ?
>    4.
>
>    if I change chunk_length_kb from 4k to 64k, Can the std :: bad_alloc
>    problem be solved?
>
>
This is what we believe. Can you test it?

**Comment by tgrabiec** [comment]
2017-05-10 2:13 GMT+02:00 Junghyun Park <notifications@github.com>:

> @tgrabiec <https://github.com/tgrabiec>
>
>    1.
>
>    Our total live data is about 3.5 Tera
>
> When the node crashed, there was about 2 TB of data on disk. Was all of
that live? If it was, then compaction would not reduce the size of
sstables. I'm asking because you suggested that compaction not keeping up
could be the problem. It could if significant fraction of the data was no
longer live, that is overwritten, deleted or expired.

>
>    1.
>
>    Is the index file always cached in memory?
>    The index file is also quite large.
>
> No, index is not cached.

>
>    1. Does sstable meta (CompressionInfo, Index, Summary, Filter) use
>    non-lsa memory ?
>
> Yes.

>
>    1. if I change chunk_length_kb from 4k to 64k, Can the std ::
>    bad_alloc problem be solved?
>
> The memory requirements for CompresionInfo should be reduced by a factor
of 16, so instead of consuming 14 GB, they should use about 0.9 GB. That
should allow you to write more data before running out of memory.

Note that old sstables need to be compacted after the new setting was
applied for this to take effect. You can force this with nodetool compact.

**Comment by infordb** [comment]
@tgrabiec 
When the node crashed, there was about 2 TB of data on disk. All of that was live .
our test data is no overwritten, deleted or expired.
so all data is live.

data in product will be kept for 31 days using the ttl (time to live)
31 days data size is about 3.5TB
The larger the sstable size, the larger the compaction load, and I am concerned that scylla will handle 3.5TB in our machine spec

**Comment by avikivity** [comment]
@tgrabiec #1430  #1946 #1498 #2130

The STCS+LCS hybrid can also help.

**Comment by avikivity** [comment]
@infordb we are working to improve disk:memory ratio, but for now you can increase chunk_length_kb like @tgrabiec suggests or install more memory.

**Comment by infordb** [comment]
@avikivity @tgrabiec 
We can change chunk_length_kb from 4k to 64k, from -m 20G to -m 24G (max)
Is there any problem in scylla handling 3.5Tera data in product when setting up as above?
or does scylla need additional patches to improve disk:memory ratio ?

It is wise to patch scylla in advance even if we adjust the schedule, rather than having problems after applying scylla to the product.

**Comment by dorlaor** [comment]
On Wed, May 10, 2017 at 4:39 AM, Junghyun Park <notifications@github.com>
wrote:

> @avikivity <https://github.com/avikivity> @tgrabiec
> <https://github.com/tgrabiec>
> We can change chunk_length_kb from 4k to 64k, from -m 20G to -m 24G (max)
> Is there any problem in scylla handling 3.5Tera data in product when
> setting up as above?
> or does scylla need additional patches to improve disk:memory ratio ?
>
> It is wise to patch scylla in advance even if we adjust the schedule,
> rather than having problems after applying scylla to the product.
>

We have a long term improvement for it but for the short term no patch is
applicable because
different users have different memory/disk ratios and as we commented
before, the chunk length
has implications too.  Please test the above configuration and apply the
steps Tomek requested

**Comment by slivne** [comment]
@infordb you provided the following information above
>  --smp 8 -m 20G --max-io-requests=69
> (physical core 6core 32G memory)

why are you limiting the memory to 20 G if the machine has 32 G 

why are you limiting smp to be 8 if the machine has 6 physical cores (and 12 hyper threads?)

**Comment by infordb** [comment]
@slivne 
In scylladb, a summary batch program could be executed, so we did not assigned all resources
We are considering allocating 24G of memory.

**Comment by slivne** [comment]
@infordb AFAIK we have fixed issues related to this workload - if this issue still exists - please post and I'll reopen and we will further investigate.
