### ISSUE TITLE
Exception when communicating with xx.xx.xx.xx: Can't find a column family with UUID

### ISSUE THREAD

**Issue by cjquinon** [scylladb/scylla#2364]
*Installation details*
Scylla version (or git commit hash): 1.6.0
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04.5 LTS

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): LXC Container
Hardware: sockets= cores=16 (restricting to 2) hyperthreading=Yes memory=512MB
Disks: (SSD/HDD, count) SSD, 6

I have configured [JanusGraph](https://github.com/JanusGraph/janusgraph) to run against a 3-node Scylla cluster with the specs above.  While attempting to create a new graph (which translates to the creation of a new keyspace and several column families), I'm getting the error below intermittently:
```
ERROR 2017-05-03 13:56:14,420 [shard 0] storage_proxy - Exception when communicating with xx.xx.xx.xx: Can't find a column family with UUID 4589f470-3008-11e7-b7d4-000000000001
```

I've configured JanusGraph to use the [Cassandra Thrift Client](https://mvnrepository.com/artifact/org.apache.cassandra/cassandra-thrift/2.1.9) to communicate with ScyllaDB.  I've also configured my instance such that it only attempts to communicate with a single node in my cluster to avoid the symptoms of https://github.com/scylladb/scylla/issues/420

My ScyllaDB network timeouts are currently set to:
```
read_request_timeout_in_ms: 15000
range_request_timeout_in_ms: 30000
write_request_timeout_in_ms: 4000
counter_write_request_timeout_in_ms: 10000
cas_contention_timeout_in_ms: 2000
truncate_request_timeout_in_ms: 120000
request_timeout_in_ms: 30000
```

**Comment by duarten** [comment]
@cjquinon Could you please provide the Scylla logs containing an instance of the problem? If you can reproduce it consistently, maybe even set the log level to trace (run Scylla with `--default-log-level`, or use the [API](https://github.com/scylladb/scylla/blob/master/api/api-doc/system.json)) . On Ubuntu logs are kept in `/var/log/syslog`. Alternatively, you can follow the procedure [here](https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem) to report the problem.

**Comment by cjquinon** [comment]
@duarten: I've uploaded a tar file with TRACE logs for my three nodes into your dedicated s3 instance.  My UUID is B73C18F5-7586-4E43-8F4C-B6B601ED5BE0.

**Comment by duarten** [comment]
@cjquinon Thanks! I had a look at the logs and this still seems like a manifestation of #420.

It doesn't matter that you configured JanusGraph to communicate with just one node in the cluster, as long as the cluster contains more than one Scylla instance then the keyspace will be partitioned such that each node is responsible for only part of it. If one node receives a query for a key it is not responsible for and thus doesn't store, then it will act as a coordinator and forward the request to the correct replica(s).

Note that this is dependent on the replication factor. If the Janus keyspace has a replication factor of 3, then all nodes in a 3 node Scylla cluster will store all of the data. The [Janus default replication factor](https://github.com/JanusGraph/janusgraph/blob/4e1b92c22a6f2bcf2a097eb627efde2f49603fab/janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/AbstractCassandraStoreManager.java#L88) seems to be just one though.

You can see in the logs that node 1 creates the column family:
```
scylla625: scylla.22   | INFO  2017-05-08 19:31:34,866 [shard 1] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x60101100ee00[cfId=f26b1320-3424-11e7-ac91-000000000001,ksName=cjquinon3,cfName=system_properties [...]
```

In the logs you also see that nodes 2 and 3 pick up the new column family at times `19:31:35,003` and `19:31:34,977`, respectively.

Node 1, however, receives a query at 19:31:35,002, for which is attempts to contact node 2:

```
scylla625: scylla.22   | TRACE 2017-05-08 19:31:35,002 [shard 1] storage_proxy - query cjquinon3.system_properties cmd=read_command{cf_id=f26b1320-3424-11e7-ac91-000000000001, version=b10465ce-15b9-3d94-bf42-8882cd54c51f, slice={regular_cols=[0], static_cols=[], rows=[[ckp{000d68696464656e2e66726f7a656e}, ckp{000d68696464656e2e66726f7a656f}]], options=87, cql_format=3, partition_row_limit=2147483647}, limit=4294967295, timestamp=1494271895}, partition_limit=4294967295}, ranges={=={458357486248173206, pk{000d636f6e66696775726174696f6e}}}, id=12
scylla625: scylla.22   | ERROR 2017-05-08 19:31:35,005 [shard 1] storage_proxy - Exception when communicating with 10.92.39.131: Can't find a column family with UUID f26b1320-3424-11e7-ac91-000000000001
```

I'm assuming the query is made by Janus right after it creates the column family, although it is a little odd since no writes were made.

Do you know what the underlying thrift driver version is? In theory, it should wait until the cluster converges on the schema before attempting to use the column family.

**Comment by cjquinon** [comment]
@duarten -- thanks for the analysis.  We're bundling Thrift 0.9.0 with our application.

**Comment by duarten** [comment]
@cjquinon Does the problem still happen if you configure Janus to use Astyanax instead of the Cassandra Thrift Client? It seems to [wait for schema agreement](https://github.com/Netflix/astyanax/blob/4324ba7d133983ef93c5e7311bd5346adcc0bdf4/astyanax-thrift/src/main/java/com/netflix/astyanax/thrift/ThriftClusterImpl.java#L472), while the Cassandra Thrift Client [doesn't](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.cassandra/cassandra-thrift/2.1.8/org/apache/cassandra/thrift/Cassandra.java?av=f#1506).

**Comment by cjquinon** [comment]
@duarten -- the code you've pointed to in Astyanax doesn't wait.  It'll still throw an exception if there is a schema mismatch.

You mentioned that the underlying Thrift driver should wait for the schema to converge.  Do you know if that statement is version dependent?

**Comment by duarten** [comment]
@cjquinon The caller, [executeSchemaChangeOperation](https://github.com/Netflix/astyanax/blob/4324ba7d133983ef93c5e7311bd5346adcc0bdf4/astyanax-thrift/src/main/java/com/netflix/astyanax/thrift/ThriftClusterImpl.java#L141), does wait. Although it waits before the call, so I guess a subsequent read or write could cause the problem to happen.

I don't, I looked at version 2.1.8 of the Cassandra Thrift driver and didn't find any such code.

It's [documented](http://docs.datastax.com/en/developer/java-driver/3.1/manual/metadata/) that the CQL driver waits for schema agreement.

**Comment by cjquinon** [comment]
@duarten, Ah, was looking at the `precheckSchemaAgreement` function.  I'll give the astyanax client a try.  Similarly, it seems like we can add defensive code to the thrift libraries.

Will Scylla's CQL driver also wait for schema agreement?

**Comment by duarten** [comment]
@cjquinon I think the Janus Thrift backend could do the waiting for schema agreement, as I think the Cassandra Thrift driver has been deprecated. 

There is no Scylla-specific CQL driver. Since we implement the protocol, any driver can talk with Scylla.

**Comment by cjquinon** [comment]
@duarten -- thanks for your insight!  From our conversation, it looks like I'll need to workaround this problem for now.  I've subscribed to #1207.

**Comment by cjquinon** [comment]
@duarten -- I've confirmed switching to astyanax solves my problem as it will retry.  Since this issue is tracked in another issue, I'll close this as a duplicate.
