### ISSUE TITLE
CQL3: Delay restriction validation to better support MVs

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2367]
*Installation details*
Scylla version (or git commit hash): master

Restrictions on a Materialized View where clause are not subject to the same requirements that restrictions on normal select statements are. For example, we can restrict a clustering column without having restricted the previous ones.

The validation in `statement_restrictions` knows whether the restrictions apply to a view and can be relaxed accordingly, but early validation in, for example, `single_column_primary_key_restrictions::do_merge_with` or `single_column_relation::to_receivers`, doesn't know this and throws exceptions. 

To fix this we need to ensure all code deals with restrictions through the `statement_restrictions` API, and we can move most of the validation there. This would be similar to what the current code in Cassandra looks like.

**Comment by nyh** [comment]
I'm working on this issue. @duarten has already written a couple of tests for this case in view_schema_test.cc which fail so they are commented out - I'll make these tests pass, and think if more cases need to be tested.

**Comment by nyh** [comment]
I've managed to fix part of this issue, but there is one big problem I'm still struggling with.
Our code creates from the SELECT statement a "restrictions" object, and later validates it in, for example, statement_restrictions::process_clustering_columns_restrictions().
But while it is easy for me to remove the excessive validation from the code which builds the "restrictions" object, it is very hard to re-add these tests to the process_clustering_columns_restrictions() because at this point, I have a single "restrictions" object and I can't easily loop on the original single-column restrictions which made it up (@duarten do you know of a way to iterate over the individual restrictions?).
Some global conditions on the restrictions have been defined as a virtual function of the restrictions object (e.g., is_slice()) but I'm not able to test most conditions this way.

Cassandra 3's code is organized differently. Its StatementRestrictions and inside it, ClusteringColumnRestrictions, are constructed with an allowFiltering which can be set to true for view, so they can do the necessary tests (or not do them) while building the restrictions.

I think that reorganizing the code to what Cassandra 3 did will be messy. I think it makes more sense at this point to use the restrictions' API to get the list of ranges, and verify *those* ranges is allowed. I'll try this now.

**Comment by duarten** [comment]
I don't. 

I've proposed in the past that we move our structure closer to Cassandra's, or these types of issues might keep popping up :/

**Comment by avikivity** [comment]
IMO the best structure would be a neutral AST (no methods) with all of the operations done via visitors.
