### ISSUE TITLE
stdout/stderr are lost on systemd

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2408]
Writes to stdout or stderr are lost in the ether; bad since they may contain important information that is not properly logged for some reason (like assert fail).

**Comment by nyh** [comment]
I agree that we should cover all our bases, and also capture stdout/stderr.
But in paralle, I think it is probably a mistake that we are using std::assert which writes to stdout in the first place. I wonder if we should have a seastar::assert() which uses the Seastar logger to log the failure.
Also I wonder if seastar::assert() shouldn't use an exception instead of aborting to let at least some other parts of the server continue working - unless we believe that the core dumps from asserts are more useful than the damage done by the crash?

**Comment by pdziepak** [comment]
If a throwing `seastar::assert()` is used in a noexcept function (a destructor for example) we would get an abort anyway, except that in this case there won't be any useful message in any output.

**Comment by nyh** [comment]
@pdziepak - why no message? My idea is that a throwing seastar::assert() would log the assert failure message, and then throw an assertion-failure message. Yes, this can indeed abort if called in a noexcept function, but we won't lose the message. What we do lose is the core dump.
Anyway, if we don't want a throwing assert, we can still have seastar::assert() and keep it abort()ing as std::assert, just using the seastar logger.

**Comment by tgrabiec** [comment]
2017-05-24 10:53 GMT+02:00 nyh <notifications@github.com>:

> I agree that we should cover all our bases, and also capture stdout/stderr.
> But in paralle, I think it is probably a mistake that we are using
> std::assert which writes to stdout in the first place. I wonder if we
> should have a seastar::assert() which uses the Seastar logger to log the
> failure.
>
We can't replace uses of assert in libraries, e.g. in the standard library.

> Also I wonder if seastar::assert() shouldn't use an exception instead of
> aborting to let at least some other parts of the server continue working -
> unless we believe that the core dumps from asserts are more useful than the
> damage done by the crash?
>

**Comment by nyh** [comment]
@tgrabiec true, although had we really wanted, we could override __assert_fail(), just like we did for malloc().

**Comment by glommer** [comment]
Let's not make this about assert. The backtrace code - used in the task block detector, for instance, also writes to these file handles directly because it might not be safe to do otherwise.

Well, it may not be safe in general for the backtrace code. If we know for sure it is a task block detector backtrace, we could divert it to the logger. But that would require adapting it to be able to write to both, whereas now we just write to stdout/stderr

**Comment by glommer** [comment]
awesome.
