### ISSUE TITLE
scylla_setup: we can't assume selinux is activated before setup

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2411]
*Installation details*
Scylla version (or git commit hash):  666.development-0.20170507.9a1aa6c 
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Priority: low

`scylla_selinux_setup` will only disable selinux on Red Hat variants.

*Scylla_setup interaction:* 
- "Do you want to disable SELinux?"
- "Answer yes to disable SELinux and improve performance; answer no to keep it activated."

*Question:*
If original selinux is disabled, and user answers `no`, do we need to active selinux again?

*Suggested fixes:*
- %s/answer no to keep it activated./answer no to keep current status (enforced)./
- If original selinux is disabled, skip selinux setup/interaction, or note user "Currently SELinux is disabled, it improves performance."

@syuu1228 @tzach

**Comment by nyh** [comment]
I prefer the second option: if selinux is already disabled, the whole question can be skipped - it's silly to ask him if he wants to disable linux, or keep it disabled :-)

Of course, the user might **enable** selinux after scylla_setup, not knowing that this is counter-indicated because he never saw this question. But the user can similarly undo any other thing which scylla_setup does, and I don't think he can remember what scylla_setup did.
