### ISSUE TITLE
Separate I/O scheduling for data and commitlog devices

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2415]
We have a single I/O scheduler that gets confused if data and commitlog are on separate devices.

**Comment by avikivity** [comment]
Most of the fix would be in seastar, to have an instance of the I/O scheduler per disk rather global.  We'd also need to run iotune per device, a way to communicate iotune's findings to Scylla, and a way to migrate from a single-scheduler configuration to the multi-device configuration.

**Comment by bhalevy** [comment]
Looks like @glommer has done all of the required work in the following (merge) commits:
636424ccc482469001810f4a0725dc39f0af8991
3e7e47aa2e3394b01363e77393987eb9d88e0f39
d5ad5f84dede3a5a8abdaba4184c191b947d91d0
12f18ce06056978355f74f48c07c0286762f6523

Looking at this, other than trivial cleanups, I'm not sure if anything else needs to be done.
@glommer / @avikivity: please advise.

**Comment by avikivity** [comment]
Will scylla_setup iotune both disks and configure io-properties.yaml for both devices?

**Comment by bhalevy** [comment]
No, I see that scylla_io_setup runs iotune only on data_file_directories[0]

**Comment by glommer** [comment]
@bhalevy Indeed we need to patch scylla_setup to tune all the devices it needs (not just "both" -> we may have more than two).

I sent a patch once, but I didn't really found a good way to scan all devices in a future proof way. The problem was that scylla_setup will parse the configuration file, but some of the places that could be directories may not be mentioned, in which case we'll see defaults. We don't really have a good way to know what are the defaults (One such example is the hints directory, and tiered storage will make this pervasive)

Another pressing problem is that we have a single configuration for number of I/O queues, and we are forced to pick one of them to serve all devices (usually the lower `--num-io-queues`). There are plenty of situations in which this may lead to bad performance in the faster device. I tried a couple of approaches to fix that in an automatic way and they all failed (they worked extremely well in some cases and regressed in others). The safe fallback is just to allow each device to calculate its own independent number of I/O Queues. At this point, maybe we should take that route.

Once we have a solution for those two things, then I guess this is good enough.

**Comment by bhalevy** [comment]
> @bhalevy Indeed we need to patch scylla_setup to tune all the devices it needs (not just "both" -> we may have more than two).
> 
> I sent a patch once, but I didn't really found a good way to scan all devices in a future proof way. The problem was that scylla_setup will parse the configuration file, but some of the places that could be directories may not be mentioned, in which case we'll see defaults. We don't really have a good way to know what are the defaults (One such example is the hints directory, and tiered storage will make this pervasive)
> 

I suggest that for the time being we'll just hard code the default directories' location in scylla_io_setup.
That would be an improvement over the present state and can be improved further along the way by probing scylla.

> Another pressing problem is that we have a single configuration for number of I/O queues, and we are forced to pick one of them to serve all devices (usually the lower `--num-io-queues`). There are plenty of situations in which this may lead to bad performance in the faster device. I tried a couple of approaches to fix that in an automatic way and they all failed (they worked extremely well in some cases and regressed in others). The safe fallback is just to allow each device to calculate its own independent number of I/O Queues. At this point, maybe we should take that route.
> 

Is this captured in seastar#485?

> Once we have a solution for those two things, then I guess this is good enough.

**Comment by glommer** [comment]
@bhalevy I did not share my results in the issue tracker - my bad. I will do that today.

I am okay with hardcoding the directories for now, I am just afraid that once we do that the issue will be deprioritized and we'll never really do it right.

**Comment by bhalevy** [comment]
> I am okay with hardcoding the directories for now, I am just afraid that once we do that the issue will be deprioritized and we'll never really do it right.

@glommer not at all, I'm on it and will continue on to the next phase:
Probing the defaults by executing the scylla binary with a new option to dump the effective configuration.
If given a configuration file on the command line, it will apply it over the defaults and dump the results to the output file, otherwise, it will just dump the defaults to the output file.

**Comment by bhalevy** [comment]
As for independent number of I/O queues, we need infrastructure in seastar for that, and that's a terrific additional follow-on project.

**Comment by bhalevy** [comment]
@avikivity can we put this issue to rest?

**Comment by avikivity** [comment]
Fixed by 2dba8098444f9fce66111e743f437b36ede524dc
