### ISSUE TITLE
Streaming may send message bigger than rpc is capable of receiving.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2428]
*Installation details*
Scylla version (or git commit hash): c4faa1e20253608fe20b7155d662ee3c214288c4

PREPARE_MESSAGE verb sends list of streaming::stream_request and the list can be very large. It may result in a single RPC message bigger then RPC resource limit (currently configured by scylla to be third of 8% of shard's memory). If this happens such message will be dropped by a receiver and streaming will fail.

**Comment by asias** [comment]
Will the receiver silently drop the message,  so that the sender will get
RPC timeout error.

**Comment by gleb-cloudius** [comment]
On Mon, May 29, 2017 at 05:08:20AM -0700, Asias He wrote:
> Will the receiver silently drop the message,  so that the sender will get
> RPC timeout error.
> 
Yes, I will add logging.

--
			Gleb.

**Comment by nyh** [comment]
On Mon, May 29, 2017 at 3:10 PM, Gleb Natapov <notifications@github.com>
wrote:

> On Mon, May 29, 2017 at 05:08:20AM -0700, Asias He wrote:
> > Will the receiver silently drop the message, so that the sender will get
> > RPC timeout error.
> >
> Yes, I will add logging.
>

Why does the *receiver* drop the message? Why doesn't the sender check the
message size and fail the send instead??

As we (or at least I) realized today, it should not allowed to send one
single big RPC message because:

1. It needs the entire message in memory at once.
2. When compression of RPC is enabled, it needs all this memory to be
contiguous!
3. Some of the processing of this single message is done in one huge
continuation and can block the shard for a very long time.

So maybe we need to keep the limit at much less than 8%, and moreover we
should consider going over the limit a serious internal error, at the level
of an assert() - if we wrote our code correctly, it should not send one big
message in any circumstance.

**Comment by avikivity** [comment]
The limit is for the total memory consumed by in-flight requests, not for a single request.

**Comment by gleb-cloudius** [comment]
On Mon, May 29, 2017 at 05:25:30AM -0700, nyh wrote:
> On Mon, May 29, 2017 at 3:10 PM, Gleb Natapov <notifications@github.com>
> wrote:
> 
> > On Mon, May 29, 2017 at 05:08:20AM -0700, Asias He wrote:
> > > Will the receiver silently drop the message, so that the sender will get
> > > RPC timeout error.
> > >
> > Yes, I will add logging.
> >
> 
> Why does the *receiver* drop the message? Why doesn't the sender check the
> message size and fail the send instead??
> 
Sender does not know receiver's limit (may be negotiated, but not done
right now). The way message is dropped today is also more of a bug than
a feature. The code tries to allocate resources but fails with timeout
(because the message is large than available resource), only then it is
dropped. It is easy to check a message size against max resource limit
right away.

> As we (or at least I) realized today, it should not allowed to send one
> single big RPC message because:
> 
> 1. It needs the entire message in memory at once.
> 2. When compression of RPC is enabled, it needs all this memory to be
> contiguous!
That's a bug. Fixing it requires modification of lz4 library though.

> 3. Some of the processing of this single message is done in one huge
> continuation and can block the shard for a very long time.
> 
> So maybe we need to keep the limit at much less than 8%, and moreover we
> should consider going over the limit a serious internal error, at the level
> of an assert() - if we wrote our code correctly, it should not send one big
> message in any circumstance.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/2428#issuecomment-304649036

--
			Gleb.

**Comment by nyh** [comment]
On Mon, May 29, 2017 at 3:32 PM, Gleb Natapov <notifications@github.com>
wrote:

> On Mon, May 29, 2017 at 05:25:30AM -0700, nyh wrote:
> > Why does the *receiver* drop the message? Why doesn't the sender check
> the
> > message size and fail the send instead??
> >
> Sender does not know receiver's limit (may be negotiated, but not done
> right now).


The sender could also set its own limit. In the typical case, we will set
the same limit in both receive and sender (because, frankly, both sides are
the same code!), the sender will be the one rejecting the oversized
messages instead of the receiver.

By the way, is there a reason why we want to allow huge individual
messages? Linux's unix domain datagram socket limits a single message to be
the size of the socket's buffer - often 128 KB. UDP datagrams are limited
to 64 KB. (IPv6 allows 4 GB datagrams, but nobody is using that). Is there
a reason why we want a single message to exceed, say, 1 MB, given all the
downsides of allowing it?

As an example, if we have code which sends an entire partition as a
message, it will fail as the partition may grow arbitrarily large. Better
have it fail at 1MB, and find this bug earlier.

**Comment by gleb-cloudius** [comment]
On Mon, May 29, 2017 at 05:47:06AM -0700, nyh wrote:
> On Mon, May 29, 2017 at 3:32 PM, Gleb Natapov <notifications@github.com>
> wrote:
> 
> > On Mon, May 29, 2017 at 05:25:30AM -0700, nyh wrote:
> > > Why does the *receiver* drop the message? Why doesn't the sender check
> > the
> > > message size and fail the send instead??
> > >
> > Sender does not know receiver's limit (may be negotiated, but not done
> > right now).
> 
> 
> The sender could also set its own limit. In the typical case, we will set
> the same limit in both receive and sender (because, frankly, both sides are
> the same code!), the sender will be the one rejecting the oversized
> messages instead of the receiver.
> 
Same code, but not necessary same memory size. But I agree that sender
may define its own limits. After all receiver's limit is not for one
message but for many simultaneously processed messages.

> By the way, is there a reason why we want to allow huge individual
> messages? Linux's unix domain datagram socket limits a single message to be
> the size of the socket's buffer - often 128 KB. UDP datagrams are limited
> to 64 KB. (IPv6 allows 4 GB datagrams, but nobody is using that). Is there
> a reason why we want a single message to exceed, say, 1 MB, given all the
> downsides of allowing it?
> 
RPC serialization is transparent. A user does not have fine grained
control over serialized message size. It is one thing to say that you
cannot send an arrays of 1 million of 1K objects and another to limit
message size to be 128K.

> As an example, if we have code which sends an entire partition as a
> message, it will fail as the partition may grow arbitrarily large. Better
> have it fail at 1MB, and find this bug earlier.
> 
1MB is not big enough to fail, but some reasonable limit should be
applied.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Mon, Jul 03, 2017 at 12:58:30PM +0000, Shlomi Livne wrote:
> Assigned #2428 to @gleb-cloudius.
> 
What do you want me to do about it? The fix is in the streaming code
and I think @asias already fixed it.

--
			Gleb.

**Comment by slivne** [comment]
@asias - can you please confirm this is fixed

**Comment by asias** [comment]
I think the problem is fixed already.
