### ISSUE TITLE
Scylla tools should work with Scylla configuration

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2454]
Tools like sstabledump and sstableloader require cassandra.yaml matching our scylla.yaml to be present on classpath. That poses usability problems (extra manual step for configuring), but is also error-prone since scylla.yaml and cassandra.yaml can get out of sync. See scylladb/scylla-tools-java#25, #2450.

Our tools should work with Scylla configuration out of the box.

**Comment by slivne** [comment]
the issue was that cassandra code validates the yaml - which means that we need to embed the additional configurations we have in the configuration reader code just to make sure it will not fail because of our extra configs suash as api_address 

having said that we tried to avoid that - yet iots not complex in any manner, good idea +1

**Comment by benoit-canet** [comment]
@slivne: I found the ./tools/bin/filter_cassandra_attributes.py script which seems to reduce the attribute of a scylla configuration file to the available cassandra attribute.

Please confirm me you just want me to enable the extra scylla.yaml attributes on the java tools.

**Comment by benoit-canet** [comment]
slivne: ping

**Comment by haaawk** [comment]
Some previous work was posted here: https://groups.google.com/forum/#!searchin/scylladb-dev/benoit$20canet|sort:date/scylladb-dev/cIsnyG-9zcY/w_9iN1uoAQAJ
