### ISSUE TITLE
System/local table reads should have no timeouts

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2462]
Reads from system tables are not distributed and so cannot fail due to a failure of a remote resource, so there is no point in timing them out; and an error from a system read is often fatal.

During startup, system reads compete with user sstable loading and can cause a failure to boot. Perhaps system reads should use their own I/O priority class.

**Comment by avikivity** [comment]
As an implementation option, we can put system keyspaces in their own `database` instance, so they naturally inherit related settings (timeouts, scheduling groups, their own read queue and associated limits, etc.)

**Comment by duarten** [comment]
Refs #2006

**Comment by tgrabiec** [comment]
Even though local read shouldn't fail without us getting back an exception, it still may take arbitrary amount of time to complete and for some reads there is a remote client waiting for them (the driver), which can time out. Such case is not different from a CL=ONE read of a user table. One of the reasons behind the timeout is that we don't spend resources for operations which are no longer waited for. So if the client times out, the read should time out as well. So perhaps the read timeout should be a per-request thing, not a per-keyspace thing. It already is per-request for writes.

**Comment by gleb-cloudius** [comment]
Agree with Tomek. There is nothing wrong with batchlog reads timeouting
either (except that if a system works properly they should not).

--
			Gleb.

**Comment by slivne** [comment]
batchlog may be timing out for other reasons as well AFAIK they are not
paged - so if the query needs to return huge amount of data ... (we already
have a similar issue that amnon is fixing for compactions stats).

gleb - If batchlog may timeout and its ok for it to timeout - we should
remove the error emitted to the logs and change it to write errors to the
logs if it consistently fails (we have multiple users/customers complaining
about that).

**Comment by gleb-cloudius** [comment]
On Mon, Jun 12, 2017 at 12:46:49AM -0700, Shlomi Livne wrote:
> batchlog may be timing out for other reasons as well AFAIK they are not
> paged - so if the query needs to return huge amount of data ... (we already
> have a similar issue that amnon is fixing for compactions stats).
> 
Batchlog reads with limit. There is not reason for it to timeout if a
system is functioning.

> gleb - If batchlog may timeout and its ok for it to timeout - we should
It is _not_ ok for it to timeout. But removing the timeout will cause
overloaded system to become even more overloaded.

> remove the error emitted to the logs and change it to write errors to the
> logs if it consistently fails (we have multiple users/customers complaining
> about that).
> 
Batchlog timeout is the least of their problems then. It is like
complaining about not bing able to wear a hat when your head was
chopped off. It does give us an indication that other problems (which
they undoubtfully have at this point) are dues to IO been overloaded.


--
			Gleb.

**Comment by slivne** [comment]
Well, users are getting these exception:

scylla[3033]:  [shard 0] batchlog_manager - Exception in batch replay:
exceptions::read_timeout_exception (Operation timed out for system.batchlog
- received only 0 responses from 1 CL=ONE.) ....

on 1.6 (e.g. pre splitting the ranges on shards) even when they are not
using logged batches

If we need to provide an indication that timeouts are happening /io system
is overloaded in the log  lets find a different mechanism then "praying"
that system.batchlog will spit an error of query timing out.

Are the system.batchlog reads using the correct class ....

**Comment by gleb-cloudius** [comment]
On Mon, Jun 12, 2017 at 01:11:05AM -0700, Shlomi Livne wrote:
> Well, users are getting these exception:
> 
> scylla[3033]:  [shard 0] batchlog_manager - Exception in batch replay:
> exceptions::read_timeout_exception (Operation timed out for system.batchlog
> - received only 0 responses from 1 CL=ONE.) ....
> 
> on 1.6 (e.g. pre splitting the ranges on shards) even when they are not
> using logged batches
> 
Batchlog manager always try to read periodically. Nothing to do with
them using or not using logged batches.

> If we need to provide an indication that timeouts are happening /io system
> is overloaded in the log  lets find a different mechanism then "praying"
> that system.batchlog will spit an error of query timing out.
> 
We are not "praying" for anything. This is just additional indication
when problem is analyzed. I do not see any reason to silence any serious
problem and this problem is serious.

> Are the system.batchlog reads using the correct class ....
> 
It is regular query from system perspective. We can provide separate io
class for system tables btw to give them higher priority.

--
			Gleb.

**Comment by avikivity** [comment]
There's no reason to time out batchlog replay. You still have to do it, so you might as well do it now.

**Comment by gleb-cloudius** [comment]
On Mon, Jun 12, 2017 at 01:21:03AM -0700, Avi Kivity wrote:
> There's no reason to time out batchlog replay. You still have to do it, so you might as well do it now.
> 
The read takes resources, if it does not complete before next one runs
you have two reads that take resources and so on. May be batchlod is
smart enough to not do next read before previous one completes, but
since those reads are not cancellable what it will cause is non killable
process until read eventually completes.

--
			Gleb.

**Comment by avikivity** [comment]
Of course batchlog should not run two reads in parallel (whether they time out or not). If it does that's a bug.

When you time out, you waste the resources you already consumed (for example, if you actually started reading, all that I/O goes to waste). Timing out doesn't recover those resources.

**Comment by gleb-cloudius** [comment]
On Mon, Jun 12, 2017 at 01:29:43AM -0700, Avi Kivity wrote:
> When you time out, you waste the resources you already consumed (for example, if you actually started reading, all that I/O goes to waste). Timing out doesn't recover those resources.
> 
If you started reading then yes, resources are waisted already, but it is
rare (with our io scheduler) that this is the case. Most often than not
the read is seating in a queue and taking space.

Another thing is that currently low level read errors are not propagated
to high level queries, so if at a low level read fails (because of
bad_alloc for instance) batchlog will know about it by means of timeout
error. Without timeout it will hand and will never retry and will
prevent process from clear shutdown.

--
			Gleb.

**Comment by avikivity** [comment]
> If you started reading then yes, resources are waisted already, but it is
rare (with our io scheduler) that this is the case. Most often than not
the read is seating in a queue and taking space.

We don't cancel the read, so it will still take place. Just the result will be ignored.

**Comment by avikivity** [comment]
> Another thing is that currently low level read errors are not propagated
to high level queries, so if at a low level read fails (because of
bad_alloc for instance) batchlog will know about it by means of timeout
error. Without timeout it will hand and will never retry and will
prevent process from clear shutdown.

Well that needs to be fixed.

**Comment by gleb-cloudius** [comment]
On Mon, Jun 12, 2017 at 01:41:12AM -0700, Avi Kivity wrote:
> > If you started reading then yes, resources are waisted already, but it is
> rare (with our io scheduler) that this is the case. Most often than not
> the read is seating in a queue and taking space.
> 
> We don't cancel the read, so it will still take place. Just the result will be ignored.
> 
We do not cancel them, we timeout them at all levels. It will not take
place.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Mon, Jun 12, 2017 at 01:41:45AM -0700, Avi Kivity wrote:
> > Another thing is that currently low level read errors are not propagated
> to high level queries, so if at a low level read fails (because of
> bad_alloc for instance) batchlog will know about it by means of timeout
> error. Without timeout it will hand and will never retry and will
> prevent process from clear shutdown.
> 
> Well that needs to be fixed.
> 
I do not see a big impotence to fix this to be honest. The real error
cannot be propagated to a user because it will either not cause query to
timeout and has to be swallowed or (if sp figures out that dues to an
error CL cannot be reached) it will confuse user greatly (and by a user
I mean his application), so eventually it has to be translated to timeout
error.

--
			Gleb.

**Comment by glommer** [comment]
Those are symptoms of bigger problems, usually reactor stalls due to LSA,
Linux and whatnot.

Removing the batchlog timeout will only make those problems harder to debug.
