### ISSUE TITLE
Add counter for unpaged queries

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2478]
Unpaged queries can cause signficant performance impact, so we should have a counter for them.

If we observe the counter to be increasing, we can enable tracing to find the offending query.

**Comment by slivne** [comment]
unpaged queries that return few results are not a cause of concern - the
issue is usually unpagged queries that need to return more then a single
page results.

maybe we should track the size of the info we return in queries - that is
the real issue - no ?

**Comment by avikivity** [comment]
Unpaged queries that return small results can still be a time bomb for the future. But you are right that large responses are a bigger problem.

**Comment by gleb-cloudius** [comment]
On Mon, Jun 12, 2017 at 06:16:47AM -0700, Avi Kivity wrote:
> Unpaged queries that return small results can still be a time bomb for the future. But you are right that large responses are a bigger problem.
> 
Tracking unpaged range queries may be a start although I doubt anybody,
except us internally, issues those.
 
--
			Gleb.

**Comment by amnonh** [comment]
On Mon, Jun 12, 2017 at 4:19 PM, Gleb Natapov <notifications@github.com>
wrote:

> On Mon, Jun 12, 2017 at 06:16:47AM -0700, Avi Kivity wrote:
> > Unpaged queries that return small results can still be a time bomb for
> the future. But you are right that large responses are a bigger problem.
>
Maybe a histogram then?

**Comment by benoit-canet** [comment]
@avikivity: What do you mean by counter ? A variable couting those queries ? Or a seastar metrics exported variable couting those queries ? (Scylla could react automatically by enabling tracing by itself)

**Comment by benoit-canet** [comment]
@avikivity @slivne 

Shlomi and Avi both want something different I propose to implement the two things
		-> Can use query_options::get_page_size to implement what Avi want
		-> For Shlomi required histogram I could use _row_count in:
			class result {
    				bytes_ostream _w;
    				stdx::optional<result_digest> _digest;
    				stdx::optional<uint32_t> _row_count;

**Comment by slivne** [comment]
I think what we need is the overall size of the result in bytes - that the
biggest issue in my view.

**Comment by benoit-canet** [comment]
@slivne: I must confess I don't find immediatly a place where I could get this value. Moreover result can probably get streamed in pages if the total result if bigger than the ram size of the node. So this number probably need to be created out of nothing.

I will write Avi's metrics first tomorow because I don't like to feel stuck.

**Comment by benoit-canet** [comment]
@avikivity: Could you please settle on an agreement with shlomi on what must be done ?

**Comment by benoit-canet** [comment]
@slivne: I don't see how the total size of the result in byte could be provided because:

paged queries total result size can exceed the size of the ram -> they would need to be tracked from page to page and added.
What seems to hurt us is big unpacked queries -> So why not providing an histogram of the byte size of each page/result instead. It will be way simpler to code and still will provide a meanifull information on pathological case ?

**Comment by slivne** [comment]
thats what I meant the size of a page

**Comment by benoit-canet** [comment]
@slivne: If you want size in byte you will end up with two metrics: One of thrift and one for native CQL because it's the place where the CQLResult is serialized.

If you want something central then I cannot access to the serialized for and will probably end up with the size in byte of the memory representation of the result. Would it be better ?

**Comment by benoit-canet** [comment]
@slivne: Avi merged his version of the patch it was pretty straightforward to bake it in the code.

In contrast your would not be so easy. Do you still want it or do we close this issue ?

**Comment by benoit-canet** [comment]
slivne:b44ba11e4cdda4f21c94d9f94aac3c72aa027af6 implement Avi's version can you close this ?

**Comment by benoit-canet** [comment]
@slivne: I posted a new version to the list.

**Comment by eliransin** [comment]
After reviewing a little of the code, it turns out that that the counter exists but...
As in the remarks of benoit above, the current implementation doesn't take into account execute commands.
All in all, i suggest to implement it according to the result type and not the query type, which means, count every query which the server returns a result of type rows. as in the spec queries that results in rows are the only queries that has something to do with paging.
I will prepare a patch using this approach unless there is something i overlooked...
