### ISSUE TITLE
Kill lsa zones

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2480]
LSA uses zones to track contiguous chunks of segments. But zones are artificial objects, and managing them adds latency since they have to be added and removed as a unit.

Here's an idea from an email:

Again I think we should just kill zones.  We can have a bitmap a but set for each segment that lsa took over from stdalloc, and another for lsa segments that are free.

We should concentrate freeing from the lowest-numbered segments and allocation from the highest.  This will segregate memory into two arenas: stdalloc and lsa.  This will require some support from stdalloc - freeing a portion of allocated memory that is not all of the memory or something at the end, but in the beginning -- like munmap() can free a subset of a mapped area.  We may also want better integration with the std allocator so we can opportunistically allocate segments, rather than having an aligned_alloc loop.

(well, we can avoid the need for much of the integration by using aligned_alloc(256k) instead of allocating zones, maybe that by itself is already worthwhile).

**Comment by tgrabiec** [comment]
About using aligned_alloc, we used to do this, but switched in the following commit:

commit 5b5c0038e6c115caf97e120938ad7fe4290a8f1e
Author: Tomasz Grabiec <tgrabiec@cloudius-systems.com>
Date:   Fri Aug 7 20:55:06 2015 +0200

    lsa: Don't allocate aligned segments
    
    Requiring alignment means that there must be 64K of contiguous space
    to allocate each 32K segment. When memory is fragmented, we may fail
    to allocate such segment, even though there's plenty of free space.
    
    This especially hurts forward progress of compaction, which frees
    segments randomly and relies on the fact that freeing a segment will
    make it available to the next segment request.

**Comment by avikivity** [comment]
Perhaps we should stop pretending, and copy core/memory.cc into scylla. Then lsa+std could be tightly integrated. The scylla std allocator would manage std memory in terms of aligned 256k segments, and really large allocations would be satisfied by allocating a number of contiguous segments. A segment could have multiple roles:

 1. broken up for small_pool (maybe small_pool would allocate a complete segment?)
 2. used for lsa
 3. part of a large std allocation

We might drop the segment size to 128k to thread stacks and lsa segments are the same size.

Even before that, I think aligned_alloc would perform better if lsa->std freeing always happened at the lowest-numbered segments.

**Comment by gleb-cloudius** [comment]
On Tue, Jun 13, 2017 at 02:40:45AM -0700, Avi Kivity wrote:
> Perhaps we should stop pretending, and copy core/memory.cc into scylla.
> 
Why not lsa into seastar?

--
			Gleb.

**Comment by avikivity** [comment]
The change I proposed makes std allocation second class relative to lsa, so it would hurt applications that don't want lsa.

**Comment by nyh** [comment]
On Tue, Jun 13, 2017 at 12:43 PM, Gleb Natapov <notifications@github.com>
wrote:

> On Tue, Jun 13, 2017 at 02:40:45AM -0700, Avi Kivity wrote:
> > Perhaps we should stop pretending, and copy core/memory.cc into scylla.
> >
> Why not lsa into seastar?
>

+1

I too think LSA needs to be integrated into Seastar. I came to this
conclusion when Pawel presented it last year in the Scylla summit, and I
haven't changed my mind since, despite Avi's explanations to the contrary
:-)

Yes, it is more complicated and hard to understand and use LSA than regular
malloc() - but that just means it need to be *documented*. Having it, just
as undocumented, in Scylla, doesn't make it any easier to use. And LSA
isn't specific to Scylla, it could be used in any application which has
caches and similar concepts - which is most potential Seastar users.

**Comment by nyh** [comment]
On Tue, Jun 13, 2017 at 12:44 PM, Avi Kivity <notifications@github.com>
wrote:

> The change I proposed makes std allocation second class relative to lsa,
> so it would hurt applications that don't want lsa.
>

Two questions:
1. "Hurt" in what sense? What overheads are involved in your proposal? If
they are so hurtful, won't they hurt Scylla as well?
2. It seems to me that many, if not most, Seastar applications would need
LSA for the same reason that Scylla does.

**Comment by avikivity** [comment]
The changes I proposed assume that lsa will be used for most allocations. Large allocations outside LSA will be more wasteful, and perhaps small allocations sometimes (if the "maybe" is engaged).

A seastar-based file system or block device would not need lsa; neither would a database that caches btree nodes (Scylla is special in that it caches the result of merging several database files). LSA is useful when most objects' sizes have an unknown distribution.

**Comment by tgrabiec** [comment]
13.06.2017 11:40 AM "Avi Kivity" <notifications@github.com> napisał(a):

Perhaps we should stop pretending, and copy core/memory.cc into scylla.
Then lsa+std could be tightly integrated. The scylla std allocator would
manage std memory in terms of aligned 256k segments, and really large
allocations would be satisfied by allocating a number of contiguous
segments. A segment could have multiple roles:

   1. broken up for small_pool (maybe small_pool would allocate a complete
   segment?)
   2. used for lsa
   3. part of a large std allocation

Would that be more or less equivalent to configuring the seastar allocator
with page_size of 256k instead of 4k?

We might drop the segment size to 128k to thread stacks and lsa segments
are the same size.

Even before that, I think aligned_alloc would perform better if lsa->std
freeing always happened at the lowest-numbered segments.

**Comment by avikivity** [comment]
> Would that be more or less equivalent to configuring the seastar allocator
with page_size of 256k instead of 4k?

It would (if we engage the "maybe").

**Comment by avikivity** [comment]
We might make it a compile-time option.

**Comment by avikivity** [comment]
We would also want lsa and std to allocate from opposite ends, to reduce fragmentation; so std would become a first-fit allocator.

**Comment by glommer** [comment]
@avikivity isn't this done? please close if so.

**Comment by avikivity** [comment]
Fixed by 252c5dfa5209a9bd83cc55b9ea15fbd4f32f870b.
