### ISSUE TITLE
Migrating counter data from Cassandra 2.2.9 to Scylla 1.7 using sstableloader fails

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla#2527]
## Description
uploading an sstable generated on Cassandra 2.2.9 to Scylla 1.7 using sstableloader fails and returns:
```
QL: 'INSERT INTO ks.cf (cnt,first_name,last_name) values (?,?,?) USING TIMESTAMP ?;' [6, albert, einstein, 1498382915313000]
CQL: 'INSERT INTO ks.cf (cnt,first_name,last_name) values (?,?,?) USING TIMESTAMP ?;' [3, marie, curie, 1498382909653000]
CQL: 'INSERT INTO ks.cf (cnt,first_name,last_name) values (?,?,?) USING TIMESTAMP ?;' [1, albert, einstein, 1498382729474000]
com.datastax.driver.core.exceptions.InvalidQueryException: INSERT statement are not allowed on counter tables, use UPDATE instead
CQL: 'INSERT INTO ks.cf (cnt,first_name,last_name) values (?,?,?) USING TIMESTAMP ?;' [2, thomas, edison, 1498382752918000]
com.datastax.driver.core.exceptions.InvalidQueryException: INSERT statement are not allowed on counter tables, use UPDATE instead
com.datastax.driver.core.exceptions.InvalidQueryException: INSERT statement are not allowed on counter tables, use UPDATE instead
com.datastax.driver.core.exceptions.InvalidQueryException: INSERT statement are not allowed on counter tables, use UPDATE instead
```
### sstables used
[2-2-9-sstables.tar.txt](https://github.com/scylladb/scylla/files/1100396/2-2-9-sstables.tar.txt)
### CQL to generate tables
```
CREATE KEYSPACE ks WITH replication={'class':'SimpleStrategy', 'replication_factor':1};
CREATE TABLE ks.cf (first_name varchar, last_name varchar, cnt counter, PRIMARY KEY(first_name, last_name));
UPDATE ks.cf SET cnt = cnt + 1 WHERE first_name='albert' AND last_name='einstein';
UPDATE ks.cf SET cnt = cnt + 2 WHERE first_name='thomas' AND last_name='edison';
-- flush
UPDATE ks.cf SET cnt = cnt + 10 WHERE first_name='albert' AND last_name='einstein';
UPDATE ks.cf SET cnt = cnt + 3 WHERE first_name='marie' AND last_name='curie';
UPDATE ks.cf SET cnt = cnt - 5 WHERE first_name='albert' AND last_name='einstein';
-- flush
```

**Comment by slivne** [comment]
Can you please validate that you enabled counters via experimental flag


On Jun 25, 2017 6:05 PM, "harelassayag" <notifications@github.com> wrote:

Description

uploading an sstable generated on Cassandra 2.2.9 to Scylla 1.7 using
sstableloader fails and returns:

QL: 'INSERT INTO ks.cf (cnt,first_name,last_name) values (?,?,?) USING
TIMESTAMP ?;' [6, albert, einstein, 1498382915313000]
CQL: 'INSERT INTO ks.cf (cnt,first_name,last_name) values (?,?,?)
USING TIMESTAMP ?;' [3, marie, curie, 1498382909653000]
CQL: 'INSERT INTO ks.cf (cnt,first_name,last_name) values (?,?,?)
USING TIMESTAMP ?;' [1, albert, einstein, 1498382729474000]
com.datastax.driver.core.exceptions.InvalidQueryException: INSERT
statement are not allowed on counter tables, use UPDATE instead
CQL: 'INSERT INTO ks.cf (cnt,first_name,last_name) values (?,?,?)
USING TIMESTAMP ?;' [2, thomas, edison, 1498382752918000]
com.datastax.driver.core.exceptions.InvalidQueryException: INSERT
statement are not allowed on counter tables, use UPDATE instead
com.datastax.driver.core.exceptions.InvalidQueryException: INSERT
statement are not allowed on counter tables, use UPDATE instead
com.datastax.driver.core.exceptions.InvalidQueryException: INSERT
statement are not allowed on counter tables, use UPDATE instead

Reproduce sstables used

2-2-9-sstables.tar.txt
<https://github.com/scylladb/scylla/files/1100396/2-2-9-sstables.tar.txt>
CQL to generate tables

CREATE KEYSPACE ks WITH replication={'class':'SimpleStrategy',
'replication_factor':1};
CREATE TABLE ks.cf (first_name varchar, last_name varchar, cnt
counter, PRIMARY KEY(first_name, last_name));
UPDATE ks.cf SET cnt = cnt + 1 WHERE first_name='albert' AND
last_name='einstein';
UPDATE ks.cf SET cnt = cnt + 2 WHERE first_name='thomas' AND last_name='edison';
-- flush
UPDATE ks.cf SET cnt = cnt + 10 WHERE first_name='albert' AND
last_name='einstein';
UPDATE ks.cf SET cnt = cnt + 3 WHERE first_name='marie' AND last_name='curie';
UPDATE ks.cf SET cnt = cnt - 5 WHERE first_name='albert' AND
last_name='einstein';
-- flush

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/2527>, or mute the thread

**Comment by harelassayag** [comment]
confirmed

**Comment by elcallio** [comment]
1.7 sstableloader does not support counters. We added proprietary CQL syntax to handle writing counter data from sstables in 2.0. Simply issuing "UPDATE" calls for counters will not yield the correct results when interpreting sstables.

**Comment by slivne** [comment]
@harelassayag @roy we need to test this on 2.0 - according to @elcallio it should work on 2.0.

**Comment by slivne** [comment]
@harelassayag please test this on 2.0.rc2

**Comment by harelassayag** [comment]
ok

**Comment by harelassayag** [comment]
@slivne tested and works fine with 2.0 rc2.

**Comment by tzach** [comment]
Thanks @harelassayag
