### ISSUE TITLE
Removing node from cluster causes UnavailableException

### ISSUE THREAD

**Issue by mj-jadhav** [scylladb/scylla#2535]
*Installation details*
Scylla version (or git commit hash): 1.6.4
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu
Client Driver: DataStax Java Driver for Apache Cassandra

We have 4 node cluster, 2 in each rack with replication factor 2. One of the node went down from one rack, so we decided to remove dead node. As we removed the node it started throwing UnavaliableException at client side. At client side we have DowngradeRetry Policy, so ideally it should have worked but started throwing exception with message `"Not enough replicas available for query at consistency TWO (2 required but only 2 alive)"` which is weird.

**Comment by gleb-cloudius** [comment]
What "nodetool status" says when this happens?

--
			Gleb.

**Comment by mj-jadhav** [comment]
@gleb-cloudius Down And Leaving for the dead node. And UN for all other nodes

**Comment by gleb-cloudius** [comment]
Here is what is going on here: When a node is being removed its tokens get
re-assigned to other nodes in the cluster and replicas start to stream
data to new token owners. Those new owners becomes pending nodes for
the ranges they are now owners of, but the node that is been removed
is still listed as an original tokens owner in the ring. Since there is
a pending node CL is increased and writes with CL=TWO try to write
to three nodes instead, but since the node that is been removes is down
Unavailable exception is throw.

So why DowngradingConsistencyRetryPolicy did not work (it worked when one
node was down after all)? The exception Scylla throws on the first
glance looks strange. It says that 2 nodes are requests but only 2 are
alive. This is because the way Unavailable exception is defined in CQL
protocol does not have a ways to express that CL was temporary increased
due to token movement. When Cassandra faces such situations it
intentionally decrease amount or reported alive nodes by 1, so with the
same situation in Cassandra the error you would get would be "2 nodes
are requests but only 1 is alive" although 2 nodes are alive in reality.
We did not copy this behaviour because seeing "strange" message help to
identify that error happened during token movement which is useful, but
apparently DowngradingConsistencyRetryPolicy uses alive node count
returned by Unavailable exception to adjust consistency level for retry,
so when it sees that two nodes are alive it retries with CL=TWO which is
modified by Scylla to be three due to pending node and that fails
again.

There simple fix would be to do as Cassandra does and report only 1 live
node. The question is why a node that is been removed is reported as a
replica for a write. We know that it will never be up again and we already
re-assigned its tokens to other live nodes in the cluster. For
reads it still has to be reported until streaming is complete, so that
new token owner will not be contacted for read until streaming is done,
otherwise wrong data may be returned.

--
			Gleb.

**Comment by slivne** [comment]
@gleb-cloudius - is this the only case we differ - e.g. what happens when we add a node to a cluster and one of the write fails (RF=2 , CL=2) and one of the write fails - what will cassandra return back vs what will scylla return back ?

We need to fix this and allow DowngradingConsistencyRetryPolicy to work in this case - what I am trying to asses is if we differ from cassandra only in case of the current issue or in other cases as well - in which case we will probably need to change our code and align with cassandra.

**Comment by gleb-cloudius** [comment]
On Sun, Jul 02, 2017 at 01:50:37PM +0000, Shlomi Livne wrote:
> @gleb-cloudius - is this the only case we differ - e.g. what happens when we add a node to a cluster and one of the write fails (RF=2 , CL=2) and one of the write fails - what will cassandra return back vs what will scylla return back ?
> 
The code in question does not distinguish between different cases of why
pending node exists. The behaviour depend on pending node set not been
empty, nothing else.

--
			Gleb.

**Comment by slivne** [comment]
In this case - I don't think we have a choice and need to change our code
and align with cassandra to support other scenarios as well

for example:

there is an option to add a node to scylla/cassandra even if not all the
node are up "cassandra.consistent.rangemovement" - in cassandra's case if
this is done than DowngradingConsistencyRetryPolicy will be able to write -
while for us it will not.

**Comment by slivne** [comment]
@gleb-cloudius  in my view - if this is not the only case we need to align with cassandra - is there another option ?

**Comment by gleb-cloudius** [comment]
On Sun, Jul 09, 2017 at 12:28:41AM -0700, Shlomi Livne wrote:
> @gleb-cloudius  in my view - if this is not the only case we need to align with cassandra - is there another option ?
> 
> 
Since drivers use provided node counts to make decision we have to
unfortunately since drivers assume Cassandra behaviour.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
Comparing Cassandra with Scylla again I see that my previous explanation
is not entirely correct. Cassandra does not count pending modes towards
Unavailable at all, so with this scenario here Cassandra will not throw
Unavailable exception at all, it will try to write to pending node and
will through Timeout exception after 2 seconds (since there will be no
reply from a dead node).  DowngradingConsistencyRetryPolicy will ignore
the exception without even retrying since this is what it does when at
least one write succeeds.

The behaviour of Cassandra is bad here, there is no reason to try
a write when we know ahead of time the write will timeout. I will
amend information Scylla provides in Unavailable exception so that
DowngradingConsistencyRetryPolicy will work as expected.

--
			Gleb.

**Comment by slivne** [comment]
if this is simple we need to backport to 2.0 and 1.7 its a user case
