### ISSUE TITLE
Dropping a column family may leave behind data

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2562]
*Installation details*
Scylla version (or git commit hash): master, 2.0

When dropping a column family, we issue a truncate() followed by a call to stop(), which flushes the memtables. Any concurrent writes that snuck in between the two operations would be present on disk.

**Comment by baiwfg2** [comment]
@duarten Hi. I found that in `column_family::truncate`, first `discard_sstables()`, then  `db::system_keyspace::save_truncation_record()`. I wonder what if discard_sstables() is not fully completed because of exception or crash, then the truncation record hasn't been recorded. Would it be a problem when restarting ? How could you handle those unsuccesfully-deleted sstables files ?

**Comment by baiwfg2** [comment]
How could it know truncation should be retried when restarting ? Besides truncate record, is there other things that can indicate truncation occurred before ?
