### ISSUE TITLE
do not actually compact fully expired tables

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2620]
that will benefit time series worloads, which everything is eventually deleted through TTL. This can be done by not including fully expired sstable in set of mutation reader for compaction. Procedure to determine if sstable is fully expired uses metadata max_local_deletion_time, also taking into account if sstable's data doesn't  *possibly* shadow older data in an overlapping sstable. max_local_deletion_time was being incorrectly set before cc6c3832, so we need a way to do this check only on sstables created after that commit.

**Comment by slivne** [comment]
@raphaelsc - not clear to me - according to what you indicated we have a bug with setting max_local_deletion_time.  Prior to the fix did we set max_deletion_time to a static value that can be checked to identify such files - if not the mechanism I can think off to keep track of this is to use a different naming for sstables - e.g. use kb instead of ka, any other way to detect this, maybe internally in some manner ?

Does the current code in 2.0 / 1.7 / main use the incorrect max_deletion_time, specifically does DTCS use it in some manner ?

**Comment by raphaelsc** [comment]
On Mon, Jul 24, 2017 at 8:38 AM, Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> - not clear to me - according
> to what you indicated we have a bug with setting max_local_deletion_time.
> Prior to the fix did we set max_deletion_time to a static value that can be
> checked to identify such files - if not the mechanism I can think off to
> keep track of this is to use a different naming for sstables - e.g. use kb
> instead of ka, any other way to detect this, maybe internally in some
> manner ?
>
Does the current code in 2.0 / 1.7 / main use the incorrect
> max_deletion_time, specifically does DTCS use it in some manner ?
>
@slivne: the problem is that we weren't setting max_local_deletion_time
with a value that says the sstable will never be fully expired (for example
if one of its cell isn't set with a TTL). So a sstable that is partially
expired can be added to set of candidates as if it were fully expired (only
DTCS does that). Not harmful. It also only affect versions older than 1.3

**Comment by slivne** [comment]
So I think I have a solution for this, If the file has a Scylla component we know its a new file (1.7 forward) and know the max deletion time is correct 

Since files without a Scylla component should not exist anymore (it may only happen during refresh / loading of files  - and then we will reshard the files) I think that we effectively can implement this and not delay it because of some mistake in versions older than <= 1.3

It really matters for time series setups.

**Comment by raphaelsc** [comment]
@slivne completely agree.
