### ISSUE TITLE
Summaries way too small

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2711]
*Installation details*
Scylla version (or git commit hash): 2.1

```
-rw-r--r-- 1 avi avi 1181843288 Aug 19 17:14 /var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Data.db
-rw-r--r-- 1 avi avi     483856 Aug 19 17:14 /var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Filter.db
-rw-r--r-- 1 avi avi  100940352 Aug 19 17:14 /var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Index.db
-rw-r--r-- 1 avi avi      90128 Aug 19 17:14 /var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Scylla.db
-rw-r--r-- 1 avi avi       4462 Aug 19 17:14 /var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Statistics.db
-rw-r--r-- 1 avi avi      33954 Aug 19 17:14 /var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Summary.db
```

Instead of a 2000:1 ratio, we have a 34807:1 ratio, and very high cpu usage in index processing.

**Comment by avikivity** [comment]
This a default cassandra-stress write load, but with compression enabled.

**Comment by slivne** [comment]
What is the partition size are yoy uaing wide rows ?

Raphael is currently out on vacation if its his series lets revert

On Aug 19, 2017 8:37 PM, "Avi Kivity" <notifications@github.com> wrote:

*Installation details*
Scylla version (or git commit hash): 2.1

-rw-r--r-- 1 avi avi 1181843288 Aug 19 17:14
/var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Data.db
-rw-r--r-- 1 avi avi     483856 Aug 19 17:14
/var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Filter.db
-rw-r--r-- 1 avi avi  100940352 Aug 19 17:14
/var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Index.db
-rw-r--r-- 1 avi avi      90128 Aug 19 17:14
/var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Scylla.db
-rw-r--r-- 1 avi avi       4462 Aug 19 17:14
/var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Statistics.db
-rw-r--r-- 1 avi avi      33954 Aug 19 17:14
/var/lib/scylla/data/keyspace1/standard1-32d4bf0081b011e79a39000000000001/keyspace1-standard1-ka-840-Summary.db

Instead of a 2000:1 ratio, we have a 34807:1 ratio, and very high cpu usage
in index processing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/2711>, or mute the thread

**Comment by avikivity** [comment]
Culprit is emitting a summary only after 64k of index data was written. If an index entry size is 60 bytes, we get more than 1000 entries per summary entry.
