### ISSUE TITLE
nodetool toppartitions 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2811]
*Installation details*
Scylla version (or git commit hash): 2.0

`nodetool toppartitions` is used to identify hot partitions in a Scylla cluster

```
$ nodetool <options> toppartitions <keyspace>  <table> <duration>  ... 
```
Apache Cassandra example
http://cassandra.apache.org/doc/latest/tools/nodetool/toppartitions.html

**Comment by tzach** [comment]
@amnonh do we Scylla the REST API to support this nodetool command?

**Comment by tzach** [comment]
@amnonh ping

**Comment by slivne** [comment]
I think we discussed this in the past 
- the solution suggested was to use a counter in the cache 
- we need to check that we store info for partitions not found in sstables as well.

**Comment by slivne** [comment]
Additional items we discussed - provide top partition based on multiple filters
- top partition - by partition hit
- top partition - by row count 
- top partition - by bytes

**Comment by dorlaor** [comment]
There is a revolutionary github 'assignee' field, pls use it

**Comment by tzach** [comment]
> top partition - by row count
> top partition - by bytes

I think these will nicely fit into the existing large table, with a few extra fields.
Let's separate the usage to "top" and the size to "large"

**Comment by slivne** [comment]
@avikivity did we have any writeup about this - not sure @amnonh should handle it - if its tightly integd with the cache.

**Comment by slivne** [comment]
@tgrabiec will do an initial design and then we will do assignment

**Comment by tgrabiec** [comment]
We want to collect statistics about reads and writes which are concurrent with the invocation of toppartitions. 

We want to be able to get aggregate statistics for the whole node, or only for selected tables. This should be confiugrable on the command line.

We want to track events which happen on the replica-side of the node we attach to.

In the basic mode, toppartitions will run in one-shot mode, where it collects statistics for a given period, configurable on the command line, after which it prints the results and returns. Later we can add continuous mode, where it runs until interrupted, periodically dumping statistics for subsequent periods.

Here's how I see this implemented in Scylla. We will extend the `database` class with an ability to install data listeners, intercepting reads and writes going through given `database` instance:

```c++
class data_listener {
public:
    // Invoked for each write, with partition granularity.
    // The schema_ptr passed is the one which corresponds to the incoming mutaton, 
    // not the current schema of the table.
    virtual void on_write(const schema_ptr&, const frozen_mutation&) { }

    // Invoked for each query (both data query and mutation query) 
    // when a mutation reader is created.
    // Paging queries may invoke this once for a page, or less often, depending
    // on whether they hit in the querier cache or not.
    // 
    // The mutation_reader passed to this method is the reader
    // from which the query results are built (uncompacted).
    // This method replaces that reader with the one returned from this method. 
    // This allows the listener to install on-the-fly processing for the mutation stream.
    //
    // The schema_ptr passed is the one which corresponds to the reader,
    // not the current schema of the table.
    virtual mutation_reader on_read(const schema_ptr&, const partition_range&, const query::partition_slice&, mutation_reader&& rd) {
        return std::move(rd);
    }
};
```

Each toppartitions session will install their own listener. This allows many concurrent toppartitions sessions to coexist, using different filtering criteria, and collecting different properties of the workload.

Filtering criteria can be implemented using composition, where filters are wrappers around the collecting listeners, ignoring events which do not belong to the filter, and passing through the rest. toppartition would build a pipeline with filters at the front, and collectors in the back.

We may want to collect different aspects of the workload, e.g. hit count, or the number of bytes read and written. We can have different implementations of listeners depending on what needs to be collected, and insert appropriate collectors depending on configuration into the listener pipeline when monitoring is started.

To collect statistics about partition keys used in single-partition queries, one can install a listener which implements on_read() and looks at the partition_range, checking if it's singular, and extracting the partition key from it.

To collect statistics about partition keys returned in range scans, the on_read() callback would have to wrap the mutation reader it receives into a `filtering_reader`, which will be invoked for every partition key returned in the stream.

I think in the default mode, toppartitions should account for only single-partition queries. This could be made configurable.

*Keeping track of the statistics*

We cannot track every partition we see, because this may lead to OOM. We should use an approximated data structure, which would work well for a skewed distribution so that if there is an outlier, we will likely find it. We could implement the Space-Saving algorithm from [1], which uses bounded memory for its `Stream-Summary` data structure. The algorithm keeps a map between keys seen and their counts, keeping a bound on the number of tracked keys. Replacement policy evicts the key with the lowest count while inheriting the count of the last element, and recording an estimation of the error which results from that. This error estimation can be later used to prove if the distribution we arrived at corresponds to the real top-K, which we can display alongside the results.

Accuracy depends on the number of tracked keys. We should track more keys than the number of top keys we want to display at the end. Both parameters should be configurable.

We would use `tuple<schema_ptr, partition_key>` as the key in this data structure, using `schema::id()` for equality of the `schema_ptr` part.

[1] http://www.cse.ust.hk/~raywong/comp5331/References/EfficientComputationOfFrequentAndTop-kElementsInDataStreams.pdf

Cassandra is using this algorithm, provided by stream-lib: https://github.com/addthis/stream-lib/blob/master/src/main/java/com/clearspring/analytics/stream/StreamSummary.java

**Comment by avikivity** [comment]
@amnonh I think we need to add jmx support, no?

**Comment by tzach** [comment]
reopen since there is no nodetool command in place.

**Comment by amnonh** [comment]
I've looked at what it takes to wire the nodetool to the API.
There is a main difference in the implementation between cassandra and scylla.

In cassandra, sampler API contains two methods, one to start and one to complete (I found that implementation better API wise but the decision was against it).

there are multiple way of going around this:
* reimplement the scylla code - probably not going to happened.
* Add a new jmx call and change the nodetool implementation, it's not complicated, but it will break our nodetool compatibility, so far, the nodetool is fully JMX compatible.
* make the jmx mimic the desired behavior.

I'll continue with option 3, but leave this comment for future discussion

**Comment by avikivity** [comment]
start/stop is not resilient against failures of the caller.

**Comment by avikivity** [comment]
Ah, nodetool does not give jmx the measurement time up-front?

**Comment by amnonh** [comment]
Unfortunately, it doesn't

**Comment by amnonh** [comment]
While working on the jmx side of things, I've noticed we are missing #4089.
I'll continue with the implementation as is, returning knowingly wrong cardinality and we'll need to fill that gap.

**Comment by slivne** [comment]
jmx and nodetool integgration was added closing the issue
