### ISSUE TITLE
scylladb read timeout

### ISSUE THREAD

**Issue by chaipugao** [scylladb/scylla#2823]
*Installation details*
Scylla version (or git commit hash): 1.6.6
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):physical
Hardware: sockets= cores= 48 hyperthreading= memory=198G
Disks: (SSD/HDD, count) SSD, 24

I set the ConsistencyLevel = ONE, sometimes I got the Exception: ReadTimeOutException "Cassandra timeout during read query at consistency ONE(3 responses were requierd but only 2 replia responded)". is this exception normal?  I set the ConsistencyLevel = ONE, why the exception is "3 responses were requierd but only 2 replia responded"  ?

**Comment by chaipugao** [comment]
is this a bug ?

**Comment by gleb-cloudius** [comment]
Consistency level can be increased for a request due to probabilistic read repair.
If data mismatch is detected before reply is sent and repair fails it can result in
a kind of exception you see here.

--
			Gleb.

**Comment by chaipugao** [comment]
when read， I set the ConsistencyLevel=ONE,     why need 3 responses ？I think 1 responses enough。
and in 1.6.4 version， I got  the exception is (1responses were requierd but only 0 replia responded)

**Comment by gleb-cloudius** [comment]
If data from several nodes mismatch Scylla does not know which reply is
correct, so it tries to reconciliate between all replicas. If one replica
does not reply you get the kind of error you see. 1 reply need but 0
returned is essential the same error but for a read without read repair.
What happens is that you have one replica that is considered alive
but does not reply (real problem here). If this replica is chosen as a
coordinator and read is done without read repair you get 1/0 error. If
read repair kicks in you get 3/2 error.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
OTOH for CL=ONE we can just reply with a data that we already have even
though we know other nodes may have different data and reconcile in the
background. The consistency guaranties for CL=ONE is low anyway.

--
			Gleb.

**Comment by chaipugao** [comment]
ok，I understand，thank you for much  @gleb-cloudius
