### ISSUE TITLE
Mutation readers should take the partition_slice's selected columns into account

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#2885]
Currently mutation readers are (implicitly) assumed to return whole rows regardless of the contents of `query::partition_slice::static_columns` and `query::partition_slice::regular_columns`. This might be surprising especially for people unaware of the assumption.
As a first step we should rename `query::full_slice` to something more appropriate, as it's real meaning is `all_key_columns_in_all_rows_of_a_partition_slice` (© Avi).

**Comment by denesb** [comment]
Full discussion can be viewed [on this thread](https://groups.google.com/d/msg/scylladb-dev/uQfjeXDT-XY/2PDoA2rvAQAJ).

**Comment by tgrabiec** [comment]
I don't think we should rename full_slice to what you suggest, because "all rows and all columns" is the meaning which is expected by users of mutation readers. That meaning is currently respected because of the implicit requirement that mutation_readers created by a mutation_source should produce full rows. If we lift that requirement, then full_slice would have to be adjusted to really include the set of all columns. One way to achieve that is to store it in the schema object and have schema::full_slice().

**Comment by duarten** [comment]
I'm finishing a patch right now that adds schema::full_slice().

**Comment by denesb** [comment]
Duplicate of https://github.com/scylladb/scylla/issues/6393. Actually the former is a duplicate of this issue, but as that is more clearly formulated, I'll close this one instead.
