### ISSUE TITLE
Increase Limits: Lists and Maps

### ISSUE THREAD

**Issue by Ritaja** [scylladb/scylla#3007]
* Installation details * 
Scylla version : 2.0.1-0.20171115.7b19167
Cluster size: 1 (Single Node evaluation)
OS : Ubuntu 16.04.3 LTS (Xenial Xerus)

On trying to write using datastax-python sriver to the ScyllaDB cluster, we get the exception that our Lists are too long: 
`InvalidRequest: Error from server: code=2200 [Invalid query] message="List value is too long. List values are limited to 65535 bytes but 206731 bytes value provided"`

This, I believe, was increased in `Cassandra 2.1` as can be seen [here](https://stackoverflow.com/questions/28587390/big-values-in-cassandra-collections-types)

This blocks us currently as our data-points would need the limit increased for `Lists` and `Maps`

**Comment by slivne** [comment]
I tested it out - you can create a list with more than 64k elements - the limitation is on the size of a single element  - which is limited to 65535 bytes

**Comment by slivne** [comment]
The same limitation exists in Cassandra 2.1 / 2.2 
https://github.com/apache/cassandra/blob/cassandra-2.1/src/java/org/apache/cassandra/cql3/Lists.java#L222

The limitation was only lifted in Cassandra 3.1 / 3.0.1
https://issues.apache.org/jira/browse/CASSANDRA-10374

**Comment by Ritaja** [comment]
I was wrong about the limits correlating with Cassandra versions, thanks for correcting me. The problem is that we are planning to migrate our production cluster from C* 3.x to Scylla 2.0. 

We have lot of data-points where we have more than 65535 bytes. This will be a major roadblock for our move, any ideas when this will be incorporated in Scylla?

**Comment by slivne** [comment]
@avikivity - any input on lifting this limitation

**Comment by argenet** [comment]
It should be relatively easy to support this for CQL v3 by just removing the corresponding checks. 
The problems may arise with v2. This is basically why C* only supports it in 3.x but the fist has not been ported to 2.x - see https://issues.apache.org/jira/browse/CASSANDRA-10374?focusedCommentId=15037659&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15037659

From #584 it seems like v2 support has been implemented in full, however, the following is the relevant part here:

> |* The serialization format for collection has changed (both the
collection size and the length of each argument is now 4 bytes long).
See Section 6.|
the biggest issue

and nowhere do the comments say it has been fixed.
@elcallio @avikivity do you have any idea of whether this has been addressed for v2?
Or, more generally, do we need to care about v2 at all?

**Comment by avikivity** [comment]
Both v2 and v3 are supported. We can lift the checks in lists.cc and maps.cc.

However:
 - we need to check when serializing a too-large blob in v2 format (and return some exception)
 - we can't lift the limit on map keys and set values, because the current sstable format can't represent them

See write_collection_value(), where we currently truncate.

**Comment by argenet** [comment]
Thanks, that makes sense. The only note is that it appears our current CQL layer restrictions on map keys and set values are insufficient as they only prevent a single value of length > 64K to get in but don't help if we have, say, a set of multiple values with the serialized length exceeding 64K - see #3017.

We need to add validation similar to https://github.com/blerer/cassandra/blob/10374-2.2/src/java/org/apache/cassandra/cql3/QueryProcessor.java#L212 
Maybe we even don't need dedicated validations for sets and map keys once we have the one above applied.

**Comment by argenet** [comment]
It seems that if we remove current length checks, for clients using old protocols (v1/v2), we will be able to throw an exception if a collection with values exceeding 64K has been requested ('SELECT') but not if they attempt to insert it. 

This problem is same as the one that prevented the similar fix to be included into C* 2.x: https://issues.apache.org/jira/browse/CASSANDRA-10374?focusedCommentId=15037514&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15037514 

I will look further to see if we can do anything in that regard but given that our CQL layer implementation is similar, we may be hitting the same shortcoming.
