### ISSUE TITLE
CAST/SUM(CAST)/MIN(CAST)/MAX(CAST)/AVG(CAST) from float/smallint/int/tinyint/bigint/varint to  decimal : the result is trimmed

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3111]
*Installation details*
Scylla version (or git commit hash): master

CAST/SUM(CAST)/MIN(CAST)/MAX(CAST)/AVG(CAST) to  decimal from float/smallint/int/tinyint/bigint/varint: the result is trimmed.
Expected result is taken from Cassandra.

Scenario: **Smallint**
1. Create and pre-fill table:
    CREATE TABLE cast_smallint_test (k int PRIMARY KEY, smallint_clmn smallint);
    INSERT INTO cast_smallint_test (k, smallint_clmn) VALUES (0, 32767);
    INSERT INTO cast_smallint_test (k, smallint_clmn) VALUES (1, -32767);
    INSERT INTO cast_smallint_test (k, smallint_clmn) VALUES (2, -12876);  
    INSERT INTO cast_smallint_test (k, smallint_clmn) VALUES (3, 2654);

2. CAST(): SELECT cast(smallint_clmn as decimal) FROM cast_smallint_test WHERE k=0
    Expected result: '32767**.0**' Actual result: '32767'
3. SUM(CAST()): SELECT sum(cast(smallint_clmn as decimal)) FROM cast_smallint_test
     Expected result: '-10222**.0**'. Actual result: '-10222'
4. AVG(CAST): SELECT avg(cast(smallint_clmn as decimal)) FROM cast_smallint_test
    Expected result: '-2555**.5**'. Actual result: '-2556'

**Comment by hagrid-the-developer** [comment]
Short story: I should add one decimal place when converting integers to Decimal.

Long story:
It seems that it is a real issue and it is again caused by conversion to decimal through double. According to Java documentation, BigDecimal.valueOf(double) uses the string representation of double (https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#valueOf(double)) and it seems that one decimal point is printed for double that stores integer:

    class TestIntBigDecimal {
	    public static void main(String[] args) {
		    java.lang.Number numInt = new java.lang.Integer(12);
		    System.out.println("Double value: " + numInt.doubleValue());
	    }
    };

output:
    Double value: 12.0

**Comment by hagrid-the-developer** [comment]
I have yet another observation: When converting decimal to string, Scyla removes trailing zeroes after the decimal point, C* doesn't. Do we want to fix this? From the mathematical point of view the results are the same:

Scylla:

    cqlsh> SELECT decimal_clmn FROM cast_decimal_test;
    125.0

    cqlsh> select CAST(decimal_clmn AS text) from cast_decimal_test ;
    125

C*:
    cqlsh> SELECT decimal_clmn FROM cast_decimal_test;
    125.0

    cqlsh> select CAST(decimal_clmn AS text) from cast_decimal_test ;
    125.0

**Comment by hagrid-the-developer** [comment]
@juliayakovlev:
1. Is covered by https://github.com/scylladb/scylla/issues/3109. We wait for a decision whether to implement Java's algorithm for calculations of digits after decimal point. I would prefer to present all decimal digits (and .0 for floating points without decimal digits).

2. Is covered by https://github.com/scylladb/scylla/issues/3110. We created a Cassandra issue related to this and we wait for reaction from Cassandra. I really don't like the way Cassandra converts numbers here, they use it, because it can be easily implemented in Java.
