### ISSUE TITLE
Scylla Reflector Service

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#315]
add our own version of reflector service - need ability also to record information into logs so that we will have some stats on the usage

based on:

https://github.com/riptano/ComboAMI/blob/2.6/reflector.php

**Comment by slivne** [comment]
reflector.scylladb.com is up and running - we have change the ami to work with it

**Comment by vladzcloudius** [comment]
The AMI with fedora22 and nginx providing a reflector service is ami-fd99e798.
It has firewall, nginx, php, logrotate services and logs copying crons pre-installed and all them should run out of the box in the newly created instance.

In order to start receiving the nginx access.log logs (where the reflector access events are recorded) one has to create a new folder in s3://reflector-httpd-logs/httpd-logs/<reflector instance name, e.g. i-a91d6109>

Once created the already existing logs are going to be pushed to this folder every hour (at xx:01:00).
The logs are are rotated and compressed on a daily basis. Compressed logs are pushed to the above folder as well.

**Comment by vladzcloudius** [comment]
I've created a new AMI that doesn't have the testing leftovers (access-kaka.log to be more specific).
In order not restart the already created instance, simply login and delete /home/fedora/nginx_logs/access-kaka.log file.

**Comment by slivne** [comment]
we have one running

**Comment by vladzcloudius** [comment]
The AMI has been copied to Oregon and N. California regions. The AMI IDs there are  ami-67db0f07 and ami-ebbbf98b correspondingly.
