### ISSUE TITLE
Crash during wide-rows read workload

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#3189]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20180206.6919c7434
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): GCE/CentOS 7
report_uuid: 4bcaf29a-5467-4e7f-ab4e-a8fdba4e6284

Node crashed while running this command (roughly halfway through):
```
cassandra-stress user profile=./profile.yml no-warmup ops\(single_partition=1\) duration=10m -node 10.240.0.57 -rate threads=30
```
The table was populated by the following command:
```
cassandra-stress user profile=./profile.yml no-warmup ops\(insert=1\) -rate threads=16 -node 10.240.0.57
```
The profile used:
[profile.yml.txt](https://github.com/scylladb/scylla/files/1699410/profile.yml.txt)

Notes:
cache was disabled (`enable_cache: false` in scylla.yml)

**Comment by denesb** [comment]
Backtrace attached (too large to include inline):
[bt.txt](https://github.com/scylladb/scylla/files/1699519/bt.txt)

**Comment by argenet** [comment]
The root cause of this is the fact that `index_entry` items are shared within the same `shared_sstable`. This is mainly done to share them between `_lh_index` and `_rh_index` (see `sstable_mutation_reader`) but given that SSTable object is shared and it holds the current index lists, the same `index_entry` can be accessed from two different `_rh_index` readers that belong to different `sstable_mutation_reader`s.

Before changes introduced in #2981, this was not an issue as all the promoted index blocks were in place there. Now, however, any call to `advance_to(pos)/advance_past(pos)` within an `index_reader` is potentially changing the state of the `index_entry`.

What exactly happened here was the follows:
1. Two `index_reader`s from two different `sstable_mutation_reader`s got calls to `advance_past(pos)` on the same `index_entry`.
2. First reader R1 sees there are no blocks read yet and issues a call to `index_entry::get_next_pi_blocks()` which internally calls `input_stream::consume()`. It attempts to read the next buffer with `_fd.get()` and its continuation, which moves the read buffer to the internal `_buf` member of the stream, waits to be executed.
3. Second reader R2 also sees there are no blocks and issues another call to `index_entry::get_next_pi_blocks()` on the same `index_entry`. This call attempts to read another buffer, but as the data is all read, it gets an empty one, parses nothing out of it and returns.

In brief, calls to `input_stream::consume` within `index_entry` should be serialized.
Working on the fix.
