### ISSUE TITLE
Unable to drop keyspace or table if there are active secondary indexes

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#3202]
*Installation details*
Scylla version (or git commit hash): 2.1-rc3

Apache Cassandra lets users run `DROP KEYSPACE` and `DROP TABLE` even if there are secondary indexes but Scylla trips over materialized views validation (that SI uses under the hood) and refuses that.

**Comment by psarna** [comment]
There are two separate issues here, I think they should be split.
1. Dropping a table with secondary indexes - I'll send a patch series for that soon. The issue is that dropping a table should be allowed even if it has secondary indexes.

2. Dropping a keyspace with **any materialized views** present, not just secondary indexes.
Here's a reproduction:
~~~
CREATE KEYSPACE demodb WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
use demodb;
CREATE TABLE tbl (a int, b int, c float, PRIMARY KEY (a));
CREATE MATERIALIZED VIEW tbl_view AS SELECT c FROM tbl WHERE c IS NOT NULL PRIMARY KEY (c, a);

cqlsh:demodb> drop keyspace demodb;
ServerError: Can't find a column family with UUID 75728b10-5da8-11e8-9297-000000000000
cqlsh:demodb> drop keyspace demodb;
~~~

If any materialized views are present, first attempt to drop this keyspace will fail with `ServerError: Can't find a column family with UUID`. Still, all tables and views are dropped from it and the second attempt succeeds without any problems. I think it should be moved to a separate issue, it's not directly related to secondary indexes.
