### ISSUE TITLE
Scylla multiple nodes crash on cassandra-stress run

### ISSUE THREAD

**Issue by Kvikal** [scylladb/scylla#3296]
*Installation details*
Scylla version (or git commit hash): 2.1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

Running `cassandra-stress` on newly created cluster causes multiple nodes in the cluster to SEGFAULT after running for 0-2 minutes.

Log:

```
Segmentation fault on shard 3.
Backtrace:
  0x00000000004a2bdb
  0x00000000004a2cac
  0x00000000004a2d03
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
```

I can provide coredumps related to this issue, if they can be of any help. (let me know where I should upload them).

If you need more information regarding this issue, just let me know and I will try to provide them.

**Comment by slivne** [comment]
@Kvikal - please upload according to http://docs.scylladb.com/operating-scylla/troubleshooting/report_scylla_problem/

**Comment by Kvikal** [comment]
Report id is a18086be-8b3b-4895-a067-d6e0e7e85673. Health check uploaded, coredump should be up very soon.

**Comment by slivne** [comment]
@pdziepak can you please take a look

**Comment by hakuch** [comment]
Thanks for investigating, @pdziepak!

The body of `once_among_shards` only invokes its argument on shard 0. Is it possible something else is amiss?

**Comment by hakuch** [comment]
Thanks for the additional information, @pdziepak!

I think your analysis is correct.

There is a trick in `seastar::sharded<T>` that permits an argument of type `U` in the constructor of `T` to be passed to `seastar::shared<T>::start` as `sharded<U>`, and the local version will be passed to `T`'s constructor. A silly mistake on my part missaplied this pattern in this instance, because of course `*this` is not `sharded<auth::service>`.

Back-porting the commit should not be too challenging, and I can't think of any other similar problems in `auth` off the top of my head. I can do it, but likely tomorrow at the earliest.

**Comment by avikivity** [comment]
Not yet, was not promoted.

**Comment by hakuch** [comment]
D'oh! Forgot about that.

**Comment by avikivity** [comment]
Now promoted, let it rest in peace.
