### ISSUE TITLE
High data files amount during resharding

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3302]
Scenario example:
Cluster with 1 node
Compaction strategy - DateTieredCompactionStrategy
1. Run write Cassandra stress - prefill Db with 10000 rows
2. Check data files (DFs) amount. See attached files list:
![files_before_reshard](https://user-images.githubusercontent.com/34435448/37581330-cbcb6b24-2b50-11e8-9671-7cae91f85b31.png)

3. Restart the node with resharding: increase SMP from 4 to 7
4. Make sure the resharding was run
5. Check data files amount when node is up and compare with data files before restart . See attached files list:
![files_during_reshard](https://user-images.githubusercontent.com/34435448/37581342-da9dcc0a-2b50-11e8-8c0c-8bc808a78370.png)

It's expected that data files amount during resharding will be equal or less then data files amount before resharding multiplied by 3.

In my example I received 36 DFs before (it means 36*3=108) and 252 DFs during resharding.

System.log:
[system.log](https://github.com/scylladb/scylla/files/1824042/system.log)
There are errors in the log - issue https://github.com/scylladb/scylla/issues/3273

Same problem with SizeTieredCompactionStrategy

**Comment by raphaelsc** [comment]
with regards to #3273, please rebase and retry.

**Comment by raphaelsc** [comment]
252 DFS should be total number of sstables generated by resharding, because all the 36 sstables now became shared by all shards. I was having a discussion with Avi, and we think it's not good but not a terrible problem for CFs without leveled strategy. For leveled strategy, we need to reshard more sstables together to avoid it being actually terrible.

**Comment by raphaelsc** [comment]
There's a problem with resource usage though, which will be fixed by patch sent to mailing list as -> sstables: fix bloom filter size after resharding by properly estimating partition count

**Comment by slivne** [comment]
@juliayakovlev - why *3 ?

I would expect that each old file maybe resplit into 7 pieces - one for each shard 

so I endup with 36 * 7 = 252 - which is what you got

**Comment by juliayakovlev** [comment]
@slivne  
I told with Avi and he expects *2 , maximum *3.
If it should be split according to shard numbers (aka SMP?), I can change the test

**Comment by raphaelsc** [comment]
On Mon, Jul 16, 2018 at 5:30 AM, juliayakovlev <notifications@github.com>
wrote:

> @slivne <https://github.com/slivne>
> I told with Avi and he expects *2 , maximum *3.
> If it should be split according to shard numbers (aka SMP?), I can change
> the test
>
yes, 252 is expected. Because murmur3_partitioner_ignore_msb_bits 12 is
used, it's likely that all sstables which came from 4 shards now belong to
all 7 shards. Column family with leveled strategy will end up with less
files when resharding (but it also has naturally much more files) but
that's not possible with other strategies. Test needs a fix.

**Comment by juliayakovlev** [comment]
@raphaelsc @slivne 
If the SMP is changed from 4 to 2 (for example), I should expect files amount *2?

**Comment by juliayakovlev** [comment]
@raphaelsc @slivne 
So what is the way I should calculate expected files amount?

**Comment by slivne** [comment]
@juliayakovlev you should not have #of files greater than the "* shard number"

So lets use this as a start.

**Comment by tzach** [comment]
@juliayakovlev any update?

**Comment by juliayakovlev** [comment]
I changed it. It was merged. We did not received this problem in master and 2.3.

**Comment by tzach** [comment]
Thanks @juliayakovlev
