### ISSUE TITLE
Provide option to disable view building

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3329]
*Installation details*
Scylla version (or git commit hash): master

The view building process start on boot. If it is somehow causing an issue that causes the node to crash, it may not even allow enough time for an operator to do maintenance operations. As such, we should provide a simple configuration option to inhibit the view building process. We can make this switch dynamic, once we can change configuration options at runtime (#2689).

**Comment by glommer** [comment]
Had a big issue today trying to import data from a PoC. Since materialized views building were part of the reasons for the problems, a way to disable it temporarily would have been very helpful. A boot option is fine for that, and if it ties into the reloadable configuration options (once we have it) even better: we can boot with view building disabled, fix what we need to fix, and then enable it.
