### ISSUE TITLE
Rows in a secondary index should be ordered by token

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3423]
When indexing a column of a base table we create an underlying materialized view whose partition key is the indexed column, and the remainder of the base primary key columns appear as clustering columns.

This means that the base partition key will appear in lexicographical order in the view, but results should appear in token order to match base table order.

Due to paging and LIMIT clauses, it’s not a simple matter of reordering the results.

A solution to this problem would be to replace the base partition key columns for the token. The partition key columns themselves would still need to appear in the view’s primary key, possibly as the last columns, to ensure uniqueness of the row.

**Comment by nyh** [comment]
@duarten I thought about exactly this solution, but there's a catch... We will need the ability to create a materialized view which has a new clustering column - the token column - which did not exist in the original base table. Interestingly, ,CQL already has a syntax for SELECTing such a virtual column - the "token(...)" function can be used in SELECT - but do we support it in materialized view's SELECT? I haven't tested.

By the way, since everybody is using murmur3 tokenizer and don't expect any meaningful partition order from SELECT statements anyway, I wonder if it's really important that we do this order fix. It might be possible to make everything work even with the broken order - just have a different order than in the base table (i.e., when you select using an index, the result order is different). Though I agree even if we pull that off (and I'm not completely sure we can), it will be ugly.

**Comment by duarten** [comment]
I don’t think we support it, but it shouldn’t be too hard to add.

Maybe we can also live with this and wait for a user request.

**Comment by psarna** [comment]
An example will help me grasp the issue better, so here I go.
If I have a table with key:
~~~
PRIMARY KEY((A, B, C), D, E, F)
~~~
and create a secondary index on `E`, it will result in a materialized view with this key:
~~~
PRIMARY KEY((E), A, B, C, D, F)
~~~
but if it was instead
~~~
PRIMARY KEY((E), token(A, B, C), A, B, C, D, F)
~~~
where `token(A, B, C)` is an implicitly added invisible column, then order by token would be preserved for queries. Right?

**Comment by duarten** [comment]
Yeah. Since we don't really expose the materialized view underlying a secondary index, it doesn't really have to be an invisible column.

**Comment by nyh** [comment]
Yes, it doesn't need to be "invisible". Above I suggested that as part of the SELECT syntax you should theoretically be able to use a token() function in the SELECT for the view, but I'm guessing support for this doesn't really exist in the current code (it was certainly never tested) so we'll need to fix this in the materialized-view code, before using it in the secondary-index code.

**Comment by psarna** [comment]
Ok, more questions:

1. I thought that CQL function calls are applied *after* all the arguments are fetched, isn't it the case? Why would using a function on view fields behave differently? token() is yet another CQL function after all.

2. I get that having an actual column in view schema (like in the example above) would influence the order of results. But will it also be the case if I just used a function call in `SELECT`? Even if I internally selected `SELECT E, token(A, B, C), A, B, C, D, F` it will still be ordered by primary key fields, not by select values, right? I'm asking because shouldn't I be more interested in `INSERT` than `SELECT` when managing a view under a secondary index?

**Comment by nyh** [comment]
@psarna we're not talking about a normal SELECT query, but rather the SELECT used to **define** the materialized view, i.e., it defines which columns the view would have (secondary-indexing later uses this view to perform the search). This SELECT gets applied during updates - not during searches.

If you need a slightly longer introduction to how we do secondary indexing over views, please let me know over the mailing list and I'll reply there. Pekka also wrote an introduction that may be enough (or more than enough): https://www.scylladb.com/2017/11/03/secondary/

**Comment by duarten** [comment]
There is still a missing crucial part: the actual partition key columns should appear as the last clustering keys. As the code is now, two different keys mapping to the same token will have just a single view entry, which is wrong.

**Comment by psarna** [comment]
I don't follow... before this fix, all base partition key columns were put in the clustering key of the index table, for obvious reasons. Now,*additionally* to all these clustering columns, there's a token column added as a first clustering column, which ensures proper ordering. So, all base primary keys are still here, and they are last clustering keys, right? Or am I missing something...

**Comment by duarten** [comment]
That's right, they still appear there. However, they appear in the wrong position:

```
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE ks.cf (
    p int,
    c int,
    v int,
    PRIMARY KEY (p, c)

CREATE INDEX cf_v_idx ON ks.cf (v);

desc cf_v_idx_index;

CREATE MATERIALIZED VIEW ks.cf_v_idx_index AS
    SELECT v, idx_token, p, c
    FROM ks.cf
    WHERE v IS NOT NULL
    PRIMARY KEY (v, idx_token, p, c)
    WITH CLUSTERING ORDER BY (idx_token ASC, p ASC, c ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

The partition keys should appear last, so the order is token and then clustering keys.

**Comment by psarna** [comment]
Oook, thanks for the example, it's clear now!

**Comment by duarten** [comment]
Everything is correct the way it was, my bad 🤕

**Comment by avelanarius** [comment]
@nyh @psarna @haaawk I have a question regarding the decision to add `idx_token` as first clustering key column to global secondary index.

Added column `idx_token` is of type `bytes`. However tokens on ring are represented as **signed** `int64_t`. It seems that it causes a problem, because rows are sorted by `idx_token` - bytes, but the ordering of bytes is **unsigned** (-1 is larger than 1 when doing unsigned comparisons):

```
cqlsh> SELECT pk, ck, ck2, token(pk) FROM ks.t;

 pk | ck | ck2 | system.token(pk)
----+----+-----+----------------------
  1 |  1 |   1 | -4069959284402364209
  1 |  1 |   5 | -4069959284402364209
  2 |  1 |   3 | -3248873570005575792
  2 |  1 |   8 | -3248873570005575792
  4 |  1 |   5 | -2729420104000364805
  3 |  1 |   5 |  9010454139840013625

cqlsh> SELECT pk, ck, ck2, token(pk) FROM ks.t WHERE ck = 1;

 pk | ck | ck2 | system.token(pk)
----+----+-----+----------------------
  3 |  1 |   5 |  9010454139840013625
  1 |  1 |   1 | -4069959284402364209
  1 |  1 |   5 | -4069959284402364209
  2 |  1 |   3 | -3248873570005575792
  2 |  1 |   8 | -3248873570005575792
  4 |  1 |   5 | -2729420104000364805

cqlsh> select * from ks.t_ck_idx_index;

 ck | idx_token          | pk | ck2
----+--------------------+----+-----
  1 | 0x7d0b904cfe1ca539 |  3 |   5
  1 | 0xc78499982ae4e0cf |  1 |   1
  1 | 0xc78499982ae4e0cf |  1 |   5
  1 | 0xd2e9aeb38ba99790 |  2 |   3
  1 | 0xd2e9aeb38ba99790 |  2 |   8
  1 | 0xda1f26e0623f9efb |  4 |   5
```

When doing `SELECT` on base table without any filtering (it is not using secondary index in that case), `token(pk)` is correctly "sorted". However looking at `SELECT` with filtering (using secondary index), the order is not correct (it is ordered according to unsigned comparison). The same fact is true for the index view.

### Why is it a problem?
1. `idx_token` does not correctly do the job it was supposed to do.
2. I am now implementing support for queries on tables with global secondary index with `TOKEN` where clause (`SELECT * FROM table WHERE indexed_column = 5 AND token(pk) < 15`). Because of the ordering of `idx_token`, I can't just issue a query with `idx_token < 15`, because negative values (for example -10) are larger than 15 in unsigned comparison (but original `token(pk) < 15` operates on signed comparisons).

**Comment by haaawk** [comment]
> @nyh @psarna @haaawk I have a question regarding the decision to add `idx_token` as first clustering key column to global secondary index.
> 
> Added column `idx_token` is of type `bytes`. However tokens on ring are represented as **signed** `int64_t`. It seems that it causes a problem, because rows are sorted by `idx_token` - bytes, but the ordering of bytes is **unsigned** (-1 is larger than 1 when doing unsigned comparisons):
> 
> ```
> cqlsh> SELECT pk, ck, ck2, token(pk) FROM ks.t;
> 
>  pk | ck | ck2 | system.token(pk)
> ----+----+-----+----------------------
>   1 |  1 |   1 | -4069959284402364209
>   1 |  1 |   5 | -4069959284402364209
>   2 |  1 |   3 | -3248873570005575792
>   2 |  1 |   8 | -3248873570005575792
>   4 |  1 |   5 | -2729420104000364805
>   3 |  1 |   5 |  9010454139840013625
> 
> cqlsh> SELECT pk, ck, ck2, token(pk) FROM ks.t WHERE ck = 1;
> 
>  pk | ck | ck2 | system.token(pk)
> ----+----+-----+----------------------
>   3 |  1 |   5 |  9010454139840013625
>   1 |  1 |   1 | -4069959284402364209
>   1 |  1 |   5 | -4069959284402364209
>   2 |  1 |   3 | -3248873570005575792
>   2 |  1 |   8 | -3248873570005575792
>   4 |  1 |   5 | -2729420104000364805
> 
> cqlsh> select * from ks.t_ck_idx_index;
> 
>  ck | idx_token          | pk | ck2
> ----+--------------------+----+-----
>   1 | 0x7d0b904cfe1ca539 |  3 |   5
>   1 | 0xc78499982ae4e0cf |  1 |   1
>   1 | 0xc78499982ae4e0cf |  1 |   5
>   1 | 0xd2e9aeb38ba99790 |  2 |   3
>   1 | 0xd2e9aeb38ba99790 |  2 |   8
>   1 | 0xda1f26e0623f9efb |  4 |   5
> ```
> 
> When doing `SELECT` on base table without any filtering (it is not using secondary index in that case), `token(pk)` is correctly "sorted". However looking at `SELECT` with filtering (using secondary index), the order is not correct (it is ordered according to unsigned comparison). The same fact is true for the index view.
> 
> ### Why is it a problem?
> 1. `idx_token` does not correctly do the job it was supposed to do.
> 2. I am now implementing support for queries on tables with global secondary index with `TOKEN` where clause (`SELECT * FROM table WHERE indexed_column = 5 AND token(pk) < 15`). Because of the ordering of `idx_token`, I can't just issue a query with `idx_token < 15`, because negative values (for example -10) are larger than 15 in unsigned comparison (but original `token(pk) < 15` operates on signed comparisons).

Seems about right. Can't we just change the type of idx_token to int? Why was it bytes anyway?

**Comment by avelanarius** [comment]
> @avelanarius good catch, Looks like a bug :-( Can you please open a new issue with the same useful text you put here? Or I can do that too.

@nyh I'll open it.

**Comment by avelanarius** [comment]
Refs https://github.com/scylladb/scylla/issues/7443

**Comment by haaawk** [comment]
I chatted with @psarna and he reminded me that in the past we had tokens other than Murmur3Tokens and those other tokens were not ints. I removed all partitioners but Murmur3 some time ago. That explains why the type of the idx_token is bytes, not int. But it does not explain why the sorting is wrong for ints.
