### ISSUE TITLE
Improve nodetool listsnapshots command

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#3463]
Scylla version (or git commit hash): 2.1 / Enterprise 2018

Enable auto_snapshots in the scylla.yaml, deleted CF's are snapshot first.
With time this garbage tends to accumulate.
Unfortunately, nodetool has no way to show it or auto remove.

Possible options:

- add options to the command, e.g. nodetool listsnapshots -f
- add a new command, e.g. nodetool listallsnapshots

**Comment by yksdb** [comment]
@slivne hello. 
I understand this issue is about adding "listsnapshots -f" option or a new command "listallsnapshots" to be able to see in nodetool all of the snapshots including those for dropped tables. Current OSS 3.0.8 does not have this ability in nodetool yet. So is this feature included in some planned release?

**Comment by gnumoreno** [comment]
@eliransin @bhalevy I see this is tagged for 4.x any chance we can have this soon? 

Let me explain the use case I have in mind:

Scylla cloud is not aware when a customer truncate/drop a table. Because scylla has `auto_snapshot: true` by default a snapshot will be created but never listed by `nodetool snapshot` and can't be cleared by `nodetool clearsnapshot`. 

Users that do not use cloud have similar problems. They have to go to the filesystem and delete the snapshot manually. 

So this would be really nice to have.

Thanks in advance,

**Comment by noellymedina** [comment]
@bhalevy since 5.0 was released already, will this fix be available in the next minor 5.x release?

**Comment by bhalevy** [comment]
> @bhalevy since 5.0 was released already, will this fix be available in the next minor 5.x release?

@noellymedina, it's in 5.1.dev, but I think it should be backported to 2021.1 and to 2022.1 (via 5.0) too.

**Comment by noellymedina** [comment]
AFAIK it's backported to 2021.1 already (2021.1.9 more specific) 
Thanks @bhalevy!
