### ISSUE TITLE
Full scans of Leveled Compaction Strategy tables can skip some data

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#3513]
*Installation details*
Scylla version (or git commit hash): 2.1+

A full scan of a table using the Leveled Compaction Strategy can miss a small fraction of the data. This was observed in decommission, where some data (<1% in a test) was not streamed.

**Comment by raphaelsc** [comment]
Partitioned sstable set's incremental selector may be the one to blame.

**Comment by avikivity** [comment]
It's a candidate because https://groups.google.com/d/msg/scylladb-dev/9aixIHQAf2I/vjWOcD5WAQAJ "fixes" the problem.

**Comment by avikivity** [comment]
(it still uses combined_reader, so it's less of a candidate. of course it can be that combined_reader doesn't use the information from incremental_selector correctly, I'll let the authors of the two components to fight it out)

**Comment by avikivity** [comment]
Reproduced on master, so the bug wasn't accidentally fixed.

**Comment by denesb** [comment]
Root cause: the combined reader uses the key of the current partition to ask the incremental selector for new readers. But in some case the currently open sstables will have a huge gap between two partitions. In some cases this gap is so wide it includes some unselected sstables entirely. In this cases these sstables will be ignored from the read entirely.
Example:
```
sstable A: [a1                    a1]
sstable B:          [b1 b2]
sstable C:    [c1                           c2 c3 c4]
sstable D:                        [d1 d2 d3]
```
When the combined reader reads `d1` it polls the selector for new readers. At this point it will have readers for `A` and `C`. Since `d1` is after *all* keys in `B` and only intersects with `D`, `B` will ignored (jumped over) and `D` will be selected.

The solution is to use the `next_position` provided by the `partitioned_sstable_set`'s incremental selector to poll for new readers. This will guarantee that no intervals are jumped over.
