### ISSUE TITLE
Broken queries involving PK and secondary index

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3539]
Consider the following:

```
create keyspace ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
use ks;
create table cf (p int, c int, v int, primary key (p, c));
create index on cf (v);
insert into cf (p, c, v) values (1, 1, 1);
insert into cf (p, c, v) values (1, 2, 1);
insert into cf (p, c, v) values (2, 3, 1);
insert into cf (p, c, v) values (2, 4, 1);

select * from cf where v = 1;
 p | c | v
---+---+---
 1 | 1 | 1
 1 | 2 | 1
 2 | 3 | 1
 2 | 4 | 1

```

While restricting the indexed columns works correctly, further restrictions on the primary key columns are ignored:

``` 
select * from cf where p = 1 and v = 1;

 p | c | v
---+---+---
 1 | 1 | 1
 1 | 2 | 1
 2 | 3 | 1
 2 | 4 | 1

select * from cf where p = 1 and c = 1 and  v = 1;

 p | c | v
---+---+---
 1 | 1 | 1
 1 | 2 | 1
 2 | 3 | 1
 2 | 4 | 1
```

**Comment by duarten** [comment]
The issue is in `read_posting_list()`, in `select_statement.cc`. We should take the select restrictions and use it to build a `partition_slice`, while right now we just build an unrestricted one.

The algorithm should be something like:
- If there are partition key restrictions, obtain the token for each restriction bound, and use that as the first clustering bound (recall that the first CK in the view is the token);
- If there are partition key restrictions but there are no clustering key restrictions, we are saved because the token column defines `bottom` and `top` values, so we restrict the token with `dht::minimum_token` and `dht::maximum_token`;
- For each clustering key restriction, restrict the corresponding clustering column (in the absence of filtering, a restriction for column Cn+1 requires a restriction for column Cn);
- If there are partition key restrictions, now add the clustering bounds corresponding to the partition key columns (which should appear as the last CK columns of the MV, after #3423 is correctly fixed).

**Comment by nyh** [comment]
On Fri, Jun 22, 2018 at 1:19 AM, Duarte Nunes <notifications@github.com>
wrote:

> The algorithm should be something like:
>
>    - If there are partition key restrictions, now add the clustering
>    bounds corresponding to the partition key columns (which should appear as
>    the last CK columns of the MV, after #3423
>    <https://github.com/scylladb/scylla/issues/3423> is correctly fixed).
>
> Duarte, I'm stumped how reversing the order of partition and clustering
columns for #3423 (which I still don't understand) is necessary to solve
*this* patch. Can you please explain? Thanks.

**Comment by duarten** [comment]
@nyh I was updating my comment. I now think what we need is `allow filtering` support, which I wanted to avoid :(

**Comment by nyh** [comment]
@duarten yes, when I wrote this code I wasn't really sure what I was doing, so I left this FIXME. Unfortunately, I didn't continue to write more elaborate unit tests that involve multiple restrictions, so I didn't notice when this code comes into (foul) play :-(

**Comment by psarna** [comment]
Right now, with `ALLOW FILTERING` implemented, the example code from issue description will return
~~~
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"
~~~
, because the query wants to use **both** index and partition key and in this case filtering needs to be applied.
However, with `ALLOW FILTERING` appended, both queries that used to return wrong results are now returning exactly what they should:
~~~
cqlsh:ks> select * from cf where p = 1 and v = 1 allow filtering;

 p | c | v
---+---+---
 1 | 1 | 1
 1 | 2 | 1

cqlsh:ks> select * from cf where p = 1 and c = 1 and  v = 1 allow filtering;

 p | c | v
---+---+---
 1 | 1 | 1
~~~

So, it looks like this issue is solved and can be closed.

**Comment by duarten** [comment]
Nice. We have issues to track the missing work, right?

**Comment by psarna** [comment]
We do: https://github.com/scylladb/scylla/issues/3574, https://github.com/scylladb/scylla/issues/3573 and perhaps some more
