### ISSUE TITLE
indexed_table_select_statement should query the MV using a select statement

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3540]
The `indexed_table_select_statement` operates in two stages, the first obtaining from the underlying view the set of primary keys that are then used to query the base table, in the second stage.

We use the `storage_proxy` layer directly for the first stage.  An upcoming problem is that we want to execute `ALLOW FILTERING` queries against the MV, and using `storage_proxy` directly will cause code duplication. We can thus create an MV-specific `select_statement` when preparing the `indexed_table_select_statement`, which will take care of all the details without duplication. Also, we currently have an optimization for the this stage, which we carry out at execution time, which would be automatically applied to the select statement, and moved to prepare-time.

This can be done by calculating the select statement text, parsing and preparing it, or by creating the object graph directly (which should be easier, but I think is actually more painful).

**Comment by nyh** [comment]
By the way, I'm not sure why "ALLOW FILTERING" needs to happen implicitly. Maybe the user should need to specify it manually? For example consider an example simplified from the one which started this discussion:

Imagine we have a table with a partition key p, and a regular column r, for which we built an index. A search for r=7 yields, say, 100 results. Now somone searches for "r=7 AND p=1". You're suggesting that we take the r=7 result, use ALLOW FILTERING, and filter out just the p=1 results (because of the "token" clustering column we added, this will need ALLOW FILTERING). We can (and probably should in this case!) also do the opposite - read the partition p=1, and use "ALLOW FILTERING" to filter out only the rows with r=7. 
But in both cases, this may require inefficient filtering, which the user isn't aware of. Shouldn't he have to specify ALLOW FILTERING manually?

**Comment by duarten** [comment]
I think the user always needs to specify `ALLOW FILTERING` for queries we might do that use it (I didn't mention any implicit `ALLOW FILTERING`, but I also don't discard that we may need to do that in some case). 

The token column is not an issue, because it has natural bottom and top types, so we can add that as an additional restrictions always.

**Comment by duarten** [comment]
The only queries I can think of that need implicit `ALLOW FILTERING` are:

```
create table t (p int, c int, v int, primary key (p, c));
create index on t (v);
select * from t where token(p) > 0 and c = 1 and  v = 1;
```

In this case there aren't any partition key values to restrict the corresponding clustering columns in the view. Cassandra doesn't require `ALLOW FILTERING` for these queries, so we shouldn't either.

**Comment by duarten** [comment]
Outdated, so closing.
