### ISSUE TITLE
why so many sstables in low level

### ISSUE THREAD

**Issue by johnyannj** [scylladb/scylla#3600]
Version 2.1.4

CREATE TABLE sds.t_tableinfo (
    appid int,
    tablename text,
    createtime timestamp,
    fields text,
    frozen boolean,
    grantedapps map<int, text>,
    indexes text,
    indextype text,
    isautosync boolean,
    isdelete boolean,
    modifytime timestamp,
    options map<text, text>,
    primarykey list<text>,
    quota int,
    tabletype text,
    useraccessmode text,
    PRIMARY KEY (appid, tablename)
) WITH CLUSTERING ORDER BY (tablename ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

we see sstable level with nodetool cfstats

Keyspace: app108
        Read Count: 43013518
        Read Latency: 0.002555491322518656 ms.
        Write Count: 2783
        Write Latency: 2.8745957599712538E-5 ms.
        Pending Flushes: 0
                Table: testjvm
                SSTable count: 12762
                SSTables in each level: [49/4, 285/10, 2967/100, 9461/1000]
                Space used (live): 2021806566563
                Space used (total): 2021806566563
                Space used by snapshots (total): 0
                Off heap memory used (total): 18176388
                SSTable Compression Ratio: 0.659934
                Number of keys (estimate): 365554
                Memtable cell count: 95
                Memtable data size: 4761899
Why only 4 levels？ 

    SSTables in each level: [49/4, 285/10, 2967/100, 9461/1000]

**Comment by nyh** [comment]
The question of what "nodetool compact" does, or supposed to do, with leveled compaction, is a separate issue, a known issue: see issue #1431 and the more specific issue #3354.

@raphaelsc can we fix what you called "bad reporting"? Who (which code) prints the "285/10" number? If there are 28 shards, could we print "285/280" instead of "285/10"?

**Comment by raphaelsc** [comment]
On Fri, Jul 13, 2018 at 10:27 PM, zhaoyan <notifications@github.com> wrote:

> I dont know the "shard" in apache cassandra 2.x, it is the special of
> scylladb?
>

it correlates to each cpu assigned to a scylla instance. All cpus are used
by default, so you could just tell me the amount of cpus in your node.


> how to see the shard number and change it?

that's --smp parameter of scylla program.



> now I run nodetool compact.
>
> now all data go to level 0...... Completely incomprehensible
>

nodetool compact is about merging all sstable into one, and shouldn't be
used for this purpose. We need to improve its heuristic though for leveled
strategy.

**Comment by raphaelsc** [comment]
On Sun, Jul 15, 2018 at 9:38 AM, nyh <notifications@github.com> wrote:

> The question of what "nodetool compact" does, or supposed to do, with
> leveled compaction, is a separate issue, a known issue: see issue #1431
> <https://github.com/scylladb/scylla/issues/1431> and the more specific
> issue #3354 <https://github.com/scylladb/scylla/issues/3354>.
>
> @raphaelsc <https://github.com/raphaelsc> can we fix what you called "bad
> reporting"? Who (which code) prints the "285/10" number? If there are 28
> shards, could we print "285/280" instead of "285/10"?
>
Multiplying limit by number of shards isn't optimal either, because we can
have for example bad distribution among shards after an import for example.
The correct approach would be to report sstable per level per shard, but it
would be harder for regular user to parse. So perhaps what you suggest is
our best choice because of the trade-off.

**Comment by nyh** [comment]
@raphaelsc to be honest, I'm not even sure what is the goal of this printout. If it's just "to show something sensible in nodetool cfstats because Cassandra does it" then 285/280 may make sense (more than printing the scary-looking "285/10"). If the goal is to help the user determine when something *bad* is happening, we could report only the bad situation, e.g., "WARNING: leveled compaction strategy not keeping up: shard 3 level 2 has grown 972 sstables, expected 100.". I personally think it's not really helpful seeing the 20 different shards times 4 different levels where everything is just fine.

**Comment by johnyannj** [comment]
data split to many shards( we have 32cpus, so now we have 32 shards)

with the same amount of data.

I think this will cause Scylladb to have more ssatbles than Apache Cassandra.

if We have lot of random reading。

Scylladb will take too much IO than cassandra?

**Comment by johnyannj** [comment]
@raphaelsc  @nyh 
another question：
After I do "nodetool compact".  
Scylladb merging all sstable into one for every shard,  and xxxxx compaction task pending, but there is no compaction task running.

There is also no "nodetool enableautocompaction" command for scylla.

**Comment by dorlaor** [comment]
On Mon, Jul 16, 2018 at 6:49 AM, zhaoyan <notifications@github.com> wrote:

> data split to many shards( we have 32cpus, so now we have 32 shards)
>
> with the same amount of data.
>
> I think this will cause Scylladb to have more ssatbles than Apache
> Cassandra.
>
> if We have lot of random reading。
>
> Scylladb will take too much IO than cassandra?
>

It supposed to be less, not more. It's true we have more sstables but the
data
of those shards isn't linear anyway so it's not that fewer sstables allows
you to read
serially. Usually we manage compaction much better (read some of our blogs
about it)
and thus less sstables per read are required and there is no large
compaction backlog

**Comment by nyh** [comment]
@johnyannj let's move additional questions to the scylla mailing list (scylladb-dev@googlegroups.com) but as long as you asked here, I'll answer here:
Just like the cliche says, shards aren't a bug - they are a feature :-) On each nodes, Scylla divides the ownership of the partition key space between the different cores, each known as a "shard" and keeps separate sstables for its part. This sharding is one of the techniques which allows Scylla to be so efficient because different cores do not need to access the same data concurrently - which is very slow on modern multi-core machines. Reading of a single partition is not slowed down by sharding, because we know that only one shard holds data with that key - we don't need to do the reads on multiple shards.

Regarding the other nodetool commands, I'll leave @raphaelsc to answer those, but we should have separate bug tracker issues for each separate issues - not a mix like we have here.

You should also consider whether you really want to do some of these operations. I don't disagree that if someone does "nodetool compact" in a table with leveled compaction strategy, it should do something useful and not something weird. But why do you need to use "nodetool compact" in the first place? What were you trying to achieve with it? Leveled compaction already guarantees that at most 10% (currently more, unfortunately, see issue #2912) of the space is wasted, and around 90% of the reads are served from a single sstable. So what is "nodetool compact" supposed to achieve?

**Comment by johnyannj** [comment]
Hi @nyh

I'm sorry to mix the different issues together here.  sorry.  

At first I didn't know scylla have "shards",  and  I thought the background compact thread may be stopped。So I try to use "nodetool compact" to wake it up.

In Apache Cassandra， There is no major Compact for a table with leveled compaction strategy, "nodetool comapct" is just to trigger a next normal compact task.

I thought scylla was the same. In fact, it's not the same  :-)

**Comment by raphaelsc** [comment]
On Mon, Jul 16, 2018 at 11:44 PM, zhaoyan <notifications@github.com> wrote:

> Hi @nyh <https://github.com/nyh>
>
> I'm sorry to mix the different issues together here. sorry.
>
> At first I didn't know scylla have "shards", and I thought the background
> compact thread may be stopped。So I try to use "nodetool compact" to wake it
> up.
>
> In Apache Cassandra， There is no major Compact for a table with leveled
> compaction strategy, "nodetool comapct" is just to trigger a next normal
> compact task.
>
> I thought scylla was the same. In fact, it's not the same :-)
>
Actually leveled strategy gained a sort-of major compaction starting from
version 2.2, look at this issue for more details:
https://issues.apache.org/jira/browse/CASSANDRA-7272

So nodetool compaction against a table with leveled strategy isn't really
about triggering a regular compaction job.

**Comment by glommer** [comment]
@raphaelsc about reporting, the only sane way to report this in nodetool is reporting how many tables in total should be present in a level. Imbalance is something we should find out through other means.

Also the fact that major compaction is not strategy aware at this point is just a bug. It should be.

**Comment by raphaelsc** [comment]
On Tue, Jul 17, 2018 at 7:37 PM, Glauber Costa <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> about reporting, the only sane
> way to report this in nodetool is reporting how many tables in total should
> be present in a level. Imbalance is something we should find out through
> other means.
>

Agreed.


> Also the fact that major compaction is not strategy aware at this point is
> just a bug. It should be.
>
Yeah, it wasn't treated as such till now, but we definitely should. It's
only tagged as enhancement in https://github.com/scylladb/scylla/issues/1431

**Comment by raphaelsc** [comment]
The limits per level are unfortunately hardcoded in nodetool (not feeded by scylla): https://github.com/scylladb/scylla-tools-java/blob/master/src/java/org/apache/cassandra/tools/nodetool/TableStats.java#L145

So we'll need to either provide an average of # of sstables per level (coming from all shards), or patch nodetool to multiply limit by # of shards which would be feeded via external variable (not very viable option). Leaving it as is seems not to be an option because the current output confuse users.

**Comment by avikivity** [comment]
Closing, as there is no issue here. Follow #3612 for the fix to nodetool.
