### ISSUE TITLE
auth_test failure on Fedora 28

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3637]
On Fedora 28 and gcc 8.1.1-5, auth_test fails with
~~~
unknown location(0): fatal error: in "test_password_authenticator_operations": std::_Nested_exception<exceptions::authentication_exception>: authentication failed
~~~

fyi: @hakuch @denesb

**Comment by hakuch** [comment]
This is a small reproducer:

```c++
#include <cstring>
#include <iostream>
#include <string>

extern "C" {
#include <crypt.h>
#include <unistd.h>
}

static thread_local crypt_data crypt_state;

std::string hash_password(std::string const& cleartext, std::string const& salt) {
    auto* password = crypt_r(cleartext.c_str(), salt.c_str(), &crypt_state);
    // For debugging.
    std::cerr << "errno: " << std::strerror(errno) << '\n';
    return std::string(password);
}

int main() {
    std::string const salt = "$2y$aaaaaaaaaaaaaaaa";
    std::cout << hash_password("foobar", salt) << std::endl;
}
```

```bash
$ g++ -lcrypt -std=c++17 bug.cc -o bug
```

```bash
$ ./bug
errno: Invalid argument
*0
```

The man page for `crypt_r` documents extensions to the function (which is standardized as only supporting DES) for supporting other encryption algorithms. The choice of algorithm is indicated with a special prefix.

The `"$2y$"` salt prefix is not documented as being supported on my Fedora 28 machine, but the following prefixes are documented:

- `"$1"`: MD5
- `"$2a$"`: Blowfish
- `"$5$"`: SHA-256
- `"$6$"`: SHA-512

Changing the salt to use MD5 (`"$1"`) works:

```bash
$ ./bug
errno: Success
$1$aaaaaaaa$I/sLxCulG/lDT/WBm7v07/
```

So does SHA-256:

```bash
$ ./bug
errno: Success
$5$aaaaaaaaaaaaaaaa$3A90/6S8kjawgutNXEMfZQgjDFPfnVuWd/PPoYuY/K.
```
and SHA-512:

```bash
$ ./bug 
errno: Success
$6$aaaaaaaaaaaaaaaa$51aNB1ctv/yFkOHCGC41tz9dkZoTxMqWtuPA115AsVB0FxIKK81wmvyM3d4CDR.V8UoikpLQl/zBoymRd0/FH0
```
Interestingly, Blowfish (with the `"$2a$"` prefix) also doesn't work:

```bash
$ ./bug 
errno: Invalid argument
*0
```
I'm not clear if this is a Fedora bug, or a change that has not yet been documented. In either case, it's new behavior.

Secondly, I might have found a bug in the authenticator.

According to the man page for `crypt_r`, on error it returns `NULL`. However, even when `errno` is non-zero, the result is not `NULL`. The current code Scylla for choosing an encryption algorithm should be checking `errno` rather than for `NULL` to determine success.

**Comment by hakuch** [comment]
Pinging @elcallio  in case he has any insights about Blowfish support in glibc.

**Comment by hakuch** [comment]
Just to be sure, I checked `crypt` too. It's the same as `crypt_r` except re-entrant. Same failure of the Blowfish algorithm.

**Comment by avikivity** [comment]
It's probably this:

```
* Mon Jan 22 2018 Florian Weimer <fweimer@redhat.com> - 2.26.9000-47
- Unconditionally build without libcrypt

* Fri Jan 19 2018 Björn Esser <besser82@fedoraproject.org> - 2.26.9000-46
- Remove deprecated libcrypt, gets replaced by libxcrypt
- Add applicable Requires on libxcrypt
```

**Comment by avikivity** [comment]
Can you try linking with libxcrypt?

**Comment by avikivity** [comment]
Actually, libxcrypt installs itself as libcrypt, so it's what you're already using.

**Comment by avikivity** [comment]
You can't just check errno, because it's not guaranteed that it will be cleared if there is no error.

The documentation says:

     ‘crypt’ can fail.  Some implementations return ‘NULL’ on failure,
     and others return an _invalid_ hashed passphrase, which will begin
     with a ‘*’ and will not be the same as SALT.  In either case,
     ‘errno’ will be set to indicate the problem

So check for either NULL or '*'.

**Comment by nyh** [comment]
On Tue, Jul 31, 2018 at 9:38 AM, Avi Kivity <notifications@github.com>
wrote:

> You can't just check errno, because it's not guaranteed that it will be
> cleared if there is no error.
>
> The documentation says:
>
>  ‘crypt’ can fail.  Some implementations return ‘NULL’ on failure,
>  and others return an _invalid_ hashed passphrase, which will begin
>  with a ‘*’ and will not be the same as SALT.  In either case,
>  ‘errno’ will be set to indicate the problem
>
> So check for either NULL or '*'.
>

This is obviously true, but where did you find it written? On my Fedora 28,
crypt_r(3) says:

RETURN VALUE
       On success, a pointer to the encrypted password is returned.  On
error,
       NULL is returned.

Nothing about a "*".

**Comment by avikivity** [comment]
glibc is documented in info format.

**Comment by nyh** [comment]
On Tue, Jul 31, 2018 at 11:48 AM, Avi Kivity <notifications@github.com>
wrote:

> glibc is documented in info format.
>
> I forgot that Richard Stallman hates troff ;-)

Anyway, I don't see the text you quoted on the texinfo either, but it seems
the text you quoted, from whichever version it comes, is correct.

**Comment by hakuch** [comment]
The discrepency between the man page and the info pages is unfortunate. I'll prepare a patch.

I believe that Scylla running on an older Fedora release with authentication enabled will cease authenticating if the machine is upgraded to Fedora 28. This might be worth mentioning in release notes.

**Comment by avikivity** [comment]
What's our default auth cipher? We should switch away from blowfish/bcrypt if it's being deprecated.

**Comment by hakuch** [comment]
The default is `2y`, which is undocumented (in info and in man pages). Likely some variation of Blowfish. We could switch to SHA-256 (which some preliminary research suggests is a good choice).

Switching would necessitate existing users resetting their password, if I understand correctly.

**Comment by avikivity** [comment]
Why? isn't the cipher encoded with the hashed password?

We'd just be switching the default for new hashes.

**Comment by hakuch** [comment]
Wikipedia turned out to be more helpful here than Linux documentation.

Please see [this article](https://en.wikipedia.org/wiki/Crypt_(C)) and also this [Red Hat article](https://access.redhat.com/articles/1519843).

The `2y` scheme is bcrypt, which is a recommended algorithm for storing passwords based on Blowfish, and with dynamic "slow-down" factor that can be tweaked to ensure that the algorithm is sufficiently slow on current hardware to prevent brute-force attacks.

According to the articles above, glibc does not support bcrypt, but BSD variants like OpenBSD and FreeBSD do.

As an alternative to bcrypt, the maintainer of glibc introduced in version 2.7 a variation on SHA-256 and SHA-512 that allows for a configurable number of rounds (requiring more computing time). Up to 9 999 999 rounds on Fedora. These rounds slow down the algorithm and prevent brute-force attacks similar to the "work factor" of bcrypt.

@avikivity, suppose a user set a password with bcrypt (which, for some reason, was previously supported on Fedora). Their entry would be `$2y$SALT$PASSWORD`.

Having upgraded to Fedora 28, the algorithm would try to use the bcrypt scheme and produce `*0`. Since `*0` is not equal to `$2y$SALT$PASSWORD$`, authentication would fail.

Perhaps another option is that we could include the source code for bcrypt in a wrapper function over `crypt`.

**Comment by nyh** [comment]
On Wed, Aug 1, 2018 at 4:27 PM, Jesse Haber-Kucharsky <
notifications@github.com> wrote:

> Wikipedia turned out to be more helpful here than Linux documentation.
>
> Please see this article <https://en.wikipedia.org/wiki/Crypt_(C)> and
> also this Red Hat article <https://access.redhat.com/articles/1519843>.
>
> The 2y scheme is bcrypt, which is a recommended algorithm for storing
> passwords based on Blowfish, and with dynamic "slow-down" factor that can
> be tweaked to ensure that the algorithm is sufficiently slow on current
> hardware to prevent brute-force attacks.
>
> According to the articles above, glibc does not support bcrypt, but BSD
> variants like OpenBSD and FreeBSD do.
>

Fedora 28 switched to using "libxcrypt" instead of glibc, so I'm not sure
how what glibc supports is relevant.
I'm also not sure which texinfo document Avi viewed, as, again, glibc's
should not be relevant ;-) Although
clearly what Avi quoted was correct.

It turns out that Fedora 28 has a new manual page, crypt_rn(3), about the
actual crypt() implementations
they have (from libxcrypt). I opened on their bug tracker an issue,
https://bugzilla.redhat.com/show_bug.cgi?id=1610307
that the normal crypt(3) should be replaced by a copy of that, because
right now its content is irrelevant to
what Fedora actually has.

**Comment by hakuch** [comment]
@nyh, my experiments are consistent with Fedora man pages and info pages: bcrypt is not supported.

Avi may or may not be correct that libxcrypt installes itself as `libcrypt.so` (I have not checked this), and we can argue about the best language to describe the implementation of `crypt_r` on a system, but it's irrelevant: what matters is that invoking `crypt_r` on a Fedora 28 systems shows that the `2y` scheme is not supported.

**Comment by avikivity** [comment]
@hakuch few users are running Scylla on Fedora 28. Looking at non-Fedora 28 installations, switching from 2y to whatever the notation is for SHA-256 will mean that new passwords are in SHA-256 format and the old ones in bcrypt, and both are readable.

The only danger is when upgrading the underlying OS from one that supports bcrypt to one that doesn't. That will eventually happen when RHEL 8 is released (if it inherits Fedora 28's lack of bcrypt support), but the earlier we switch, the fewer users encounter that problem.

**Comment by hakuch** [comment]
> Yes, of course ;-) But the second thing that matters is that the existing
code didn't even realize there was a problem, because we thought that
crypt_r() should return NULL on error, which it no longer does.

Agreed.

> Of course the bigger problem is the issue that the specific algorithm is no
longer supported. I don't know if it was dropped deliberately, or by
accident.

I'll file a bug on Fedora's bug tracker. Maybe their response will inform a solution.

**Comment by hakuch** [comment]
@avi, I agree that's probably the best thing we can do at the moment.

**Comment by nyh** [comment]
On Wed, Aug 1, 2018 at 8:23 PM, Nadav Har'El <nyh@scylladb.com> wrote:

>
> Of course the bigger problem is the issue that the specific algorithm is
> no longer supported. I don't know if it was dropped deliberately, or by
> accident.
> I think it may have been missing in an older version of libxcrypt, and no
> longer missing, because in https://github.com/besser82/libxcrypt it
> *seems* that the bcrypt algorithm *is* supported in the current version.
> Maybe we just need to ask Fedora to upgrade libxcrypt and the missing 2y
> support is just temporary?
>

The mystery deepens:
According to libxcrypt's crypt(5) manual page installed on Fedora 28, the
2y method *is* supported.
It's also in the libxcrypt code, and I verified it is *not* a recent
addition to it.
So why doesn't it work?
Maybe we have another problem, such as a wrongly formatted salt or
something?

**Comment by hakuch** [comment]
I opened [this bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1611784).

**Comment by hakuch** [comment]
@nyh, @avi: I think I know the problem.

I set up some Docker images to run the following C reproducer:

```c
#define _GNU_SOURCE

#include <stdbool.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <crypt.h>

struct crypt_data* get_crypt_state(void) {
     static _Thread_local struct crypt_data* instance = NULL;

     if (instance) {
          return instance;
     }

     instance = malloc(sizeof(struct crypt_data));
     instance->initialized = 0;
     return instance;
}

#define NUM_ALGORITHMS 4

static char* const algorithms[] = {
     "$2y$", // bcrypt
     "$2a$",  // bcrypt
     "$5$", // SHA-256
     "$6$", // SHA-512
};

char* generate_random_salt(char* const algorithm) {
     // 16 bytes for the random part plus the algorithm, plus some extra.
     static _Thread_local char buffer[32];
     buffer[0] = '\0';
     // "Random".
     char const* random_part = "aaaabbbbccccdddd";
     strcat(buffer, algorithm);
     return strcat(buffer, random_part);
}

int main(void) {
     char* const cleartext = "super_secret";

     for (int i = 0; i < NUM_ALGORITHMS; ++i) {
          char* const salt = generate_random_salt(algorithms[i]);
          char* const e = crypt_r(cleartext, salt, get_crypt_state());

          printf("Got `%s`\n", e);

          if (!e || (e[0] == '*')) {
               printf("%5s: Failed with `%s`\n", algorithms[i], strerror(errno));
          } else {
               printf("%5s: Got `%s`\n", algorithms[i], e);
          }
     }

     return 0;
}
```
On Fedora 26:

```bash
Got `(null)`
 $2y$: Failed with `Invalid argument`
Got `(null)`
 $2a$: Failed with `Invalid argument`
Got `$5$aaaabbbbccccdddd$itDgeJQSL4W3BHZ2Bi0rQ1Igzi3C/qg9QauzcnYI8k5`
  $5$: Got `$5$aaaabbbbccccdddd$itDgeJQSL4W3BHZ2Bi0rQ1Igzi3C/qg9QauzcnYI8k5`
Got `$6$aaaabbbbccccdddd$wQh87anrgaL9BYj7EVzezHiMF/D1XJNeF1mnN8kh4jAwvtHI9GrGwzE8Hr./CcilCWTZkYeI0QcDuw6LYW5or1`
  $6$: Got `$6$aaaabbbbccccdddd$wQh87anrgaL9BYj7EVzezHiMF/D1XJNeF1mnN8kh4jAwvtHI9GrGwzE8Hr./CcilCWTZkYeI0QcDuw6LYW5or1`
```

Here, when the algorithm is not supported, the result is `NULL`.

Same on Fedora 27:

```bash
Got `(null)`
 $2y$: Failed with `Invalid argument`
Got `(null)`
 $2a$: Failed with `Invalid argument`
Got `$5$aaaabbbbccccdddd$itDgeJQSL4W3BHZ2Bi0rQ1Igzi3C/qg9QauzcnYI8k5`
  $5$: Got `$5$aaaabbbbccccdddd$itDgeJQSL4W3BHZ2Bi0rQ1Igzi3C/qg9QauzcnYI8k5`
Got `$6$aaaabbbbccccdddd$wQh87anrgaL9BYj7EVzezHiMF/D1XJNeF1mnN8kh4jAwvtHI9GrGwzE8Hr./CcilCWTZkYeI0QcDuw6LYW5or1`
  $6$: Got `$6$aaaabbbbccccdddd$wQh87anrgaL9BYj7EVzezHiMF/D1XJNeF1mnN8kh4jAwvtHI9GrGwzE8Hr./CcilCWTZkYeI0QcDuw6LYW5or1`
```

*However*, on Fedora 28:

```bash
Got `*0`
 $2y$: Failed with `Invalid argument`
Got `*0`
 $2a$: Failed with `Invalid argument`
Got `$5$aaaabbbbccccdddd$itDgeJQSL4W3BHZ2Bi0rQ1Igzi3C/qg9QauzcnYI8k5`
  $5$: Got `$5$aaaabbbbccccdddd$itDgeJQSL4W3BHZ2Bi0rQ1Igzi3C/qg9QauzcnYI8k5`
Got `$6$aaaabbbbccccdddd$wQh87anrgaL9BYj7EVzezHiMF/D1XJNeF1mnN8kh4jAwvtHI9GrGwzE8Hr./CcilCWTZkYeI0QcDuw6LYW5or1`
  $6$: Got `$6$aaaabbbbccccdddd$wQh87anrgaL9BYj7EVzezHiMF/D1XJNeF1mnN8kh4jAwvtHI9GrGwzE8Hr./CcilCWTZkYeI0QcDuw6LYW5or1`
```

Therefore, the cause of the bug is **not** that bcrypt was previously supported (it never was, as far as I can tell).

Instead, the issue is that failure was previously indicated by returning `NULL` (as documented in the man page), but now is not (`"*0"` is returned).

Since the authenticator code only checked for `NULL`, it assumes bcrypt is supported and thus uses the wrong hashing algorithm.
