### ISSUE TITLE
Losing PATH setting from /etc/profile.d/scylla.csh

### ISSUE THREAD

**Issue by makpcheng** [scylladb/scylla#3650]
After installing scylla, it creates /etc/profile.d/scylla.csh file. Inside this file it has:

set path = ($PATH /opt/scylladb/bin /opt/scyllabdb/sbin)

$PATH doesn't translate to valid arguments with spaces in the set path command (/sbin:/bin:/usr/sbin:...) but instead uses semicolons to separate each path folder. Thereby when I log into the server as someone  that is not root, I lose my path and cannot execute any commands after that.

Changing it to: 

set path = ($path /opt/scylladb/bin /opt/scyllabdb/sbin)

seem to fix the issue for me.

*Installation details*
Scylla version (or git commit hash): 2.2
Cluster size: 1 
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= cores= 32 hyperthreading= memory= 96GB
Disks: (SSD/HDD, count) SSD

**Comment by syuu1228** [comment]
Fixed on CentOS, new version of scylla-env uploaded on copr: https://copr.fedorainfracloud.org/coprs/scylladb/scylla-3rdparty/build/783631/

Still working on .deb version.

**Comment by slivne** [comment]
@syuu1228  / @avikivity - is this part of scylla-env - why aren;t we generating this in the build process ?

**Comment by avikivity** [comment]
We should move this file to dist/ (and see what else remains in scylla-env).

**Comment by syuu1228** [comment]
Fixed on Debian/Ubuntu.
https://launchpad.net/~scylladb/+archive/ubuntu/ppa
https://build.opensuse.org/package/binaries/home:scylladb:scylla-3rdparty-jessie/scylla-env/Debian_8.0
https://build.opensuse.org/package/binaries/home:scylladb:scylla-3rdparty-stretch/scylla-env/Debian_9.0

Now the bug fixed on all distributions, can close the issue.

**Comment by tzach** [comment]
@syuu1228 is this a fix to the build process, and apply to all future releases, like 2.3 or need to be backported?

**Comment by syuu1228** [comment]
@tzach Applied to all versions, and we don't requires rebuild.

**Comment by syuu1228** [comment]
@avikivity @slivne it's for adding /opt/scylladb/bin to $PATH, so part of scylla-3rdparties not scylla repo itself (it used for building scylla, cannot be part of scylla repo).
Initially the package was only for building scylla, but since we stop static linking libgcc/libstdc++ and added them on package dependency, now scylla-env is install on user environment, but /etc/profile.d/scylla.(csh|sh) is not really needed for users.
But we cannot drop scylla-env from the dependency since it is also provides /etc/ld.so.conf.d/scylla.x86_64.conf, is needed for users since we install scylla-libgcc73/scylla-libstdc++73 on non-standard path, /opt/scylladb/lib.

**Comment by tzach** [comment]
@syuu1228 can we close this issue?

**Comment by syuu1228** [comment]
@tzach Yes.
