### ISSUE TITLE
Support FULL secondary indexes on frozen collections

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3654]
Indexing a multi-cell set or list means indexing their values. Multi-cell maps can have their keys, values, or full entry indexed (multiple indexes can be created on the same map column). This is tracked in #2962.

For frozen collections, an index needs to be created with the `FULL` keyword, to mean we index the full collection and not its individual elements.

Example:

```
create table cf (p int primary key, v frozen<list<int>>);
create index on cf (FULL(v));
select * from cf where v = [1, 2, 3];
```

**Comment by dekimir** [comment]
Let me make sure I understand what's required to complete this:

@duarten [said](https://github.com/scylladb/scylla/issues/2962#issuecomment-410304346) previously that this issue is mainly around syntax and validation.  Then @psarna added 1b68446, which seems to successfully test the syntax.  Is it correct to presume that only validation is left?

Speaking of validation, here is a work-in-progress list of what I believe should be validated.  Please comment if it's not correct:
- disallow FULL indexes on non-frozen collections
- disallow non-FULL indexes on frozen collections
- disallow repeated creation of FULL indexes on the same collection
- disallow referencing frozen-map entries in the WHERE clause (only allow complete map values)

**Comment by psarna** [comment]
Hmm, I think most of the items from this list are already checked, especially after this patch https://github.com/scylladb/scylla/commit/2d355bdf47b49820ef1c235ce3254fc15b5a354d. Non-frozen collections are currently not supported at all with proper error message, non-full indexes on frozen collections are also disallowed, repeated creation is by default forbidden for any index too.

Also, I think that referencing frozen-map entries in WHERE clause should be allowed, at least with filtering.

**Comment by nyh** [comment]
We have in `tests/secondary_index_test.cc` a test which `test_secondary_index_collections`, which supposedly checks frozen-collection indexing. It seems to be missing a few error-path tests (e.g., that non-FULL indexing should fail), and would be good to add more checks to that test, which verify that everything works as expected including all the corner-case you mentioned. After you do that, you'll know exactly what - if anything - is left to do for this issue before it can be closed. (and of course, send a patch for the improved test).
