### ISSUE TITLE
Take HWLB into account when selecting preferred-replicas

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#3710]
We should sometimes prefer a node with a hot cache over one with a cached reader.

This was raised by @nyh on the review of the stateful singular partition queries (#1865). Here is an excerpt of the relevant discussion:

> By the way, I wonder if we shouldn't have some sort of limit to the number of
> pages we request from the same replicas. If we continue to query the same
> replicas for many pages, we're destroying the load balancing we are trying to
> do for normal one-off queries. We could, after fetching a bunch of pages from
> one set of replicas, get the next bunch from a different set, trading off a bit
> of performance for better load balancing when the query load involves just a
> few very long requests.

The discussion in its entirety can be found [here](https://groups.google.com/d/msg/scylladb-dev/WRfYltknDyU/0BARsKYVAwAJ).

**Comment by duarten** [comment]
Why is it better to prefer a node with a hot cache? A cache may be hot, but that doesn't mean it will contain the next data page. On the other hand, the read-aheads in #1865 should provide a better chance that at least some rows of the next page are in cache.

Also, there should be many concurrent queries for a given vnode, which get load balanced across its set of replicas. A single, paged query shouldn't skew the algorithm that much, should it?

**Comment by tzach** [comment]
@denesb @duarten @avikivity any update? if no clear way (or will) to push this I suggest to close this issue

**Comment by avikivity** [comment]
I agree with @duarten that the existing code is fine.

**Comment by denesb** [comment]
I think we should ask @nyh whether he has any counter argument or he accepts @avikivity 's and @duarten 's arguments that this can be closed.

**Comment by nyh** [comment]
The point wasn't just heat-based load balancing, it was load balacing in general: If we have RF replicas, and do one very long scan, the entire scan will only touch CL of the replicas and will never touch the other ones; This can mean that *other* activities the cluster is doing will be unbalanced.

That being said, if the user is doing just one very long scan, he already has a load balancing problem because such scans over the contiguous token space will necessarily access shards sequentially, instead of in parallel. A wise user (I think @avikivity even wrote a blog post about this) will split the scan to separate ranges and do them in parallel. And when he does this, and there are enough of those separate requests, each one will choose a different set of CL replicas, and the load will be balanced as usual.

So I think this issue can be closed.

**Comment by tgrabiec** [comment]
śr., 29 sie 2018 o 12:57 nyh <notifications@github.com> napisał(a):

> The point wasn't just heat-based load balancing, it was load balacing in
> general: If we have RF replicas, and do one very long scan, the entire scan
> will only touch CL of the replicas and will never touch the other ones;
> This can mean that *other* activities the cluster is doing will be
> unbalanced.
>
> That being said, if the user is doing just one very long scan, he already
> has a load balancing problem because such scans over the contiguous token
> space will necessarily access shards sequentially, instead of in parallel.
> A wise user (I think @avikivity <https://github.com/avikivity> even wrote
> a blog post about this) will split the scan to separate ranges and do them
> in parallel. And when he does this, and there are enough of those separate
> requests, each one will choose a different set of CL replicas, and the load
> will be balanced as usual.
>
> So I think this issue can be closed.
>

Splitting one large scan into multiple ranges and doing them in parallel is
no longer a scan, but a coarse-grained map-reduce. It's bad that we push
the responsibility of choosing the grain to the user, who (A) doesn't know
what is the right grain and (B) it's extra complexity for him. Also, this
method suffers from a (C) tradeoff between efficiency and parallelism. The
larger the grain, the smaller the parallelism, and thus uneven utilization,
but the smaller the grain, the more efficiency suffers due to cost of
slicing (e.g. sstable index reads), and round trips to replicas and to the
coordinator, we may become latency bound.

It would be better if we exposed instead an abstract map-reduce API in the
driver, which would provide an unordered stream to the application. On the
server side, we would have a single reader on each shard, thus keeping each
shard utilized and no slicing overhead. In case of CL != 1, we would then
have many independent coordintor-side streams combining streams for
different replica sets (to meet CL).

>

**Comment by glommer** [comment]
FWIW, I fully agree that we shouldn't push this responsability to the user and should do it ourselves.
Another example that I have already mention is aggregations.

If you do a `count(*)` on a table, this should become a map-reduce operation internally.
