### ISSUE TITLE
Minimize generated view updates for unselected column updates

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3819]
If a view doesn't contain any base regular column in its key, that is, if the liveness of a view row isn't solely determined by the liveness of a particular, regular base column, then we must consider unselected regular base columns. We do that by adding virtual cells to a view row that contain the metadata of the corresponding base regular columns. As such, updates to unselected base regular columns will generate updates to the corresponding view rows. The reason we need to this is because those unselected columns can contribute to the base row's liveness, and thus to the view's. For example, if there is no row marker, an unselected regular column can keep the base row alive. 

This is detrimental to some use cases. Consider a secondary index on a primary key column, where an unselected column is regularly updated. The view backing the index will be constantly updated without good reason. A workaround is to create an artificial, immutable regular column and add it to the view's primary key. That column's metadata must match the row marker's (that is, the user must ensure it is created when the key is created, and deleted only when the whole row is deleted). I believe we can solve this automatically.

We can avoid generating view updates in some cases where the metadata in the view's virtual cells can be allowed to become outdated. In particular:
* If a base row has a live row marker, then we can avoid generating view updates if only unselected columns change;
* If a base row has no live row marker, then we can avoid generating view updates if unselected columns are updated, unless they are newly created, deleted, or they have a TTL.

**Comment by nyh** [comment]
Some thoughts:
1. Yes, I agree that we can probably reduce the number of times we update a virtual cell, similar to what Linux does in the "relatime" mount option, i.e., we don't care about the exact time specified in a virtual cell, we just care about updating it when this update can make a difference for some decision. And indeed in some cases like you mentioned, it can't make a difference to updating it is not interesting.
2. Note that even though your suggestion can avoid the write, it will not (unless I'm missing something) be able to avoid the read (of the base row) before that write, because we need the data from this read to make the decision not to write. Obviously, it's still a benefit to avoid the write (and reduce compaction churn). 
3. Even if we do need to write an update to the view, it would be nice to write only the columns which were actually updated, and not all of them. This is issue #3594.
4. I think there's a conflict between 3 and 4 above, i.e., this issue and issue #3594... 3 suggests to write the updated cell without reading anything first. 2 suggests to read first, to (hopefully) determine writing isn't necessary.

**Comment by duarten** [comment]
> Some thoughts:
> 
> 1. Yes, I agree that we can probably reduce the number of times we update a virtual cell, similar to what Linux does in the "relatime" mount option, i.e., we don't care about the exact time specified in a virtual cell, we just care about updating it when this update can make a difference for some decision. And indeed in some cases like you mentioned, it can't make a difference to updating it is not interesting.

Cool.

> 2. Note that even though your suggestion can avoid the write, it will not (unless I'm missing something) be able to avoid the read (of the base row) before that write, because we need the data from this read to make the decision not to write. Obviously, it's still a benefit to avoid the write (and reduce compaction churn).

The idea is to avoid adding load to the view replica.

> 3. Even if we do need to write an update to the view, it would be nice to write only the columns which were actually updated, and not all of them. This is issue #3594.

Yep.

> 4. I think there's a conflict between 2 and 3 above, i.e., this issue and issue #3594... 3 suggests to write the updated cell without reading anything first. 2 suggests to read first, to (hopefully) determine writing isn't necessary.

Good point. I think reading is cheaper, especially in the case where this makes a significant difference, which is where a column for a row is updated frequently, and thus more likely to be in cache.

**Comment by duarten** [comment]
@tzach This directly impacts stability and is in the same bucket as view update backpressure.

**Comment by slivne** [comment]
@duarten I don\t disagree its important but its not in the same bucket - we will have updates that are are not needed, yet the cluster will not crash. 

So yes its high priority but only after we fix the bugs that make SI/MV not working at all.

**Comment by duarten** [comment]
@slivne What bugs are those? There's https://github.com/scylladb/scylla/issues/3452 and https://github.com/scylladb/scylla/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Asec-index+label%3Abug, but it doesn't seem like anyone's assigned.

**Comment by slivne** [comment]
We have the features that you and piotr are working on (streaming #3275 and backpressure #3756)
We have #3452
We have #2529 that nadav is checking

(and testing :)
