### ISSUE TITLE
Add ability to cancel long-standing operations

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3826]
Some operations are executed with no timeout (or equivalently, a minutes-scale timeout). These are mostly internal operations for which we've already done work that doesn't benefit from being thrown away due to a timeout, such as sending view updates.

We should add support for cancelling such operations when they are no longer relevant, for example if the failure detector marks a view replica as unavailable while there are pending view updates.

We can leverage the `seastar::abort_source` to implement such cancellation. In the particular case of view updates, a possible solution would be to associate a `seastar::abort_source` with the `gms::init_address` of the view replica we're updating, and request cancellation from a `service::endpoint_lifecycle_subscriber` when view replica is marked as unavailable.

**Comment by tzach** [comment]
@duarten does #2159 counts as such operation?

**Comment by duarten** [comment]
More or less. This is about individual, internal operations, whereas that issue is about cancelling a higher-level operation, composed of many streaming requests. Right now we can't cancel those individual streaming requests properly (I think), but using the using the mechanisms proposed they would be.

**Comment by duarten** [comment]
We don't need this for #4019, we need #3966.

**Comment by nyh** [comment]
@duarten, I'm not sure what concrete proposal #3966 is making. According to @gleb-cloudius (if I understood what he said correctly...) the write that a view build is hung on in #4019 (a write which started when we didn't know the node went down) will never stop until the timeout. So we need a way to tell a write that has already started that it needs to give up the network send immediately. This is **this** issue, no? Then, indeed, once such a write it stops, it should indeed write to a hint as #3966 suggests, but I assumed this will happen automatically anyway - because when the network send fails, the CL=ANY should try to write a hint.

**Comment by duarten** [comment]
#3966 is about completing a shutdown in a timely fashion, regardless of nodes being down or just being slow.

We can detect that there is a shutdown in progress without enlisting the gossiper. All we need to do in the `storage_proxy` is to complete any outstanding writes with an exception, which for the case of view writes (but not only), will result in a hint being stored. 

For this, it doesn't matter whether a node is down or just being slow: we can start a shutdown timer (of, say, 1 minute), after which we'll write pending writes as hints.
