### ISSUE TITLE
Auth task failed with error, rescheduling: exceptions::unavailable_exception 

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#3850]
I saw the following error from time to time with recent master: 98332de26897b6062caa16e1753fa56611453e74.

INFO  2018-10-15 12:10:13,495 [shard 0] auth - Auth task failed with error, rescheduling: exceptions::unavailable_exception (Cannot achieve consistency level for cl QUORUM. Requires 1, alive 0)

What does mean? It is in "INFO" level. Does it mean user can ignore it? How can we avoid it?

**Comment by hakuch** [comment]
The condition that results in this message being printed is an expected one.

At initialization, the auth. subsystem needs to create the default `cassandra` superuser. We need to perform a query with `QUORUM` CL in order to ensure that `cassandra` does not already exist. However, the cluster may not yet be in a state when it can satisfy `QUORUM` queries.

Since the auth. subsystem executes this process asynchronously in the background, we retry attempts with an exponentially-increasing back-off period until it is successful.

Regarding the error itself: based on my review of the Apache Cassandra code, the message is very similar (if not identical). We can certainly change it if doing so would communicate to users more effectively what is actually happening. I assume that error message compatibility is not a big concern for us.

**Comment by glommer** [comment]
I am in favor of making this DEBUG if this is a normal condition that the user can't or shouldn't act upon.
People open tickets for messages like that.

(just saw this today in the field)

**Comment by hakuch** [comment]
I'll prepare a patch to change it to a "debug" message.
