### ISSUE TITLE
Replace dead node: node fails to join cluster if it's defined as a seed

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#3889]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by tzach** [comment]
@larisau which release? what is the cluster size? please add relevant details.

**Comment by roydahan** [comment]
according which procedure of replacement?
(or what were the steps)

**Comment by slivne** [comment]
- the issue is that when we boot a node with --replace_address_first_boot, the node maybe set with itself being a seed - in this case the node currently boots and may set its token on its own instead of taking the old node tokens.

So, a node that is booted with replace address option - should not allow itself to boot when its configures as a seed

**Comment by avikivity** [comment]
Backported to 3.1, 3.0 and 2.3 need more work.

**Comment by avikivity** [comment]
Backported to 3.0, 2.3 is EOL.
