### ISSUE TITLE
Synchronize view building resharding

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3890]
Each shard starts the view builder independently, but they load the system table status of all shards. If there was no resharding, then each shard ultimately only looks at its own data. If there was resharding, on the other hand, shards do look at the status of the others and all are supposed to arrive at the same conclusion.

What happens if one of the shards is running much faster? It can even finish one build step before other shards read the system tables. That new build step will translate to a new entry in the in-progress system table, which can cause slower shards to take it into account and arrive at a different conclusion regarding what needs to be built. 

The solution is to have a cross-shard barrier, similar to what view building already uses to detect when a build finishes.

**Comment by nyh** [comment]
This bug probably explains issue #3452 where very rarely, resharding in the middle of a view build caused some view rows to be lost:

According to my analysis of the (only) two times I was able to reproduce that bug, the missing view rows were supposed to come from a base replica where a restart and resharding happened very early during the view build, such that a few shards finished one build step, but a few others didn't even finish one step. The first shards to run correctly concluded that since some of the shards made no view build progress, they need to start the view build from the minimal token. But as @duarten explained above, the last shard to start building may have its view-build reshard() see that all other shards have made a bit of progress, so it starts from that token, instead of the minimal token. The end result is that rows belonging to some very low tokens and before resharding belonged to one of the slow shards and after resharding also belonged to the new slow shard - those (very few) rows will be missing. And this is exactly what we see in  #3452.
