### ISSUE TITLE
Tombstones in Scylla

### ISSUE THREAD

**Issue by ramith** [scylladb/scylla#391]
may be this question is too early to ask (or I should have looked at the code/concepts).
Does scylla also have a concept similar tombstones?
if so do you have any material related to that (so I can read and understand).

**Comment by hastef88** [comment]
I am also interested in the same concern. Specifically, What are the anti-pattern use cases of scylla ? Cassandra was optimized for fast writes, and the read operations needed to be heavily optimized due to tombstones. 

http://www.datastax.com/dev/blog/cassandra-anti-patterns-queues-and-queue-like-datasets

Does scylla have similar limitations ? 

Thanks

**Comment by dorlaor** [comment]
ScyllaDB follows the Cassandra scheme and thus has gossip, tombstones,
maps, sstables, etc.
In case we deviate, it's either a bug, or we haven't managed to get to it
yet or a very rare case.
The Scylla status page on the web site provide additional data about the
compatibly.

Today it's an anti pattern to use Scylla as a queue. However, since the
performance is ~10X better,
you'd suffer less. Using ScyllaDB allows you actually to embrace CQL better
than the origin since
with ScyllaDB you can use more columns instead of using C* as a key/value
as many fallback to.

In the future we'll add features beyond what Cassandra offers today but
let's take one step at a time.
Cheers,
Dor
