### ISSUE TITLE
SST3: Scylla expects that whether a column is collection matches current schema

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#3924]
Scylla allows removing columns and later re-adding ones with the same name, with some minor limitations regarding allowed types. In particular, one can have a collection column, drop it and later add a column of atomic type with the same name.

However, sstable3 parser refuses to parse sstables3 that were produced in such situations. For example, if there was a column `c1` of type `set<int>` used to write an sstable and later that column was removed and re-added as `c1` of type `int`. Scylla will fail to read such sstables with an error like the following one:
```
unknown location(0): fatal error: in "test_schema_changes": sstables::malformed_sstable_exception: 73323030 definition in serialization header does not match schema. Schema collection = false, counter = false. Header collection = true, counter = false
```

**Comment by haaawk** [comment]
The question is what's best to use to determin whether sstable had been written before the column was dropped. Would that be sstable::data_file_write_time() or rather max_timestamp from statistics file? @tgrabiec @pdziepak what do you think?

**Comment by pdziepak** [comment]
`sstable::data_file_write_time()` returns a `db_clock::time_point` and we don't have anything to compare it with. Each schema has `std::unordered_map<sstring, dropped_column> _dropped_columns` so we do have a timestamp of dropped columns, but there is no guarantee that the max_timestamp of the sstable is going to be lower than the dropped_at timestamp of the column (even if we forget about server vs. client generated timestamp), due to schema change propagation delays.

Do we need to have this additional verification at all? For sstables2 we simply dropped columns that had unfrozen collection vs. atomic cell mismatch based on the assumption that such situations are caused by re-adding columns with different type. Why isn't this good enough for the mc format?

**Comment by haaawk** [comment]
I didn't know that was the solution for sstables2. I'm fine with such solution. Should we drop the mismatch both ways? collection to atomic and atomic to collection? Should we do that only when the column was dropped some time ago? I remember that @tgrabiec didn't like the idea of dropping the column on every mismatch like this. Possibly due to incompatible column type schema change.

**Comment by pdziepak** [comment]
We do allow operations that appear as incompatible column type changes by re-adding column with a different type. The sstable reader doesn't have any say in it, this either needs to be fully supported or forbidden by the ALTER TABLE statement implementation. I see no reason to do the latter.

Both collection->atomic cell and atomic cell->collection cases may be encountered and in both of them we should simply ignore the column.

Making logic depend on how long ago the column was dropped feels awfully like fixing race conditions by adding delays.

**Comment by haaawk** [comment]
Ok so that was my initial solution to just ignore the data that mismatches on collection/nocollection/counter criteria but @tgrabiec didn't like it. We need his input here.

**Comment by tgrabiec** [comment]
I think it's not safe to drop data just because there is a mismatch in metadata, because the mismatch could be due to a bug, and upon upgrade to a new Scylla version we'd be losing data during compaction. 

See https://github.com/scylladb/scylla/issues/2598 and https://github.com/scylladb/scylla/issues/2597.

I know that Cassandra refuses to read sstables which contain columns which are absent in the schema (not even marked as dropped).

In this case, I think we should parse collection cells using the type recorded in the sstable, but before adding them to the row, compare cell timestamps with the `droppedAt` for the column. If the collection cell survives, it is upgraded to the read schema, and then if there is incompatibility, we raise an error.

**Comment by pdziepak** [comment]
That will work as well and looks like there indeed is a case for this verification.
