### ISSUE TITLE
Add support for commitlog_sync batch

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#3928]
Cassandra supports two modes for commitlog_sync
```
commitlog_sync
(Default: periodic) The method that Cassandra uses to acknowledge writes in milliseconds:
periodic: (Default: 10000 milliseconds [10 seconds])
With commitlog_sync_period_in_ms, controls how often the commit log is synchronized to disk. Periodic syncs are acknowledged immediately.

batch: (Default: disabled)note
Used with commitlog_sync_batch_window_in_ms (Default: 2 ms), which is the maximum length of time that queries may be batched together.
```

add support for batch mode

**Comment by elcallio** [comment]
We have had batch support since day one. The only problem is that batch mode infers extra latency to the system, as we potentially do a write+flush for each mutation applied. 
A previous optimization of the code ensures that we "group" batches that cannot complete because already pending flushes into a single IO operation, which improves relative latency and throughput quite a bit in high volume cases. Still slower than periodic though. 

Either change the title/description of this issue to "improve batch and make it default" or close it.

**Comment by avikivity** [comment]
I'll open a new one (phrased as a bug).
