### ISSUE TITLE
Avoid populating the cache on MV read-before-write

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3965]
When generating materialized view updates, we read, for some schemas, the current state of the set of rows being updated. We read from the cache, which means we also populate it. While reading cached data is desirable, populating it with the current state is not, since we are about to overwrite it. A degenerate case is a partition deletion, which forces us to read all its rows, populate the cache with them, and then delete them all.

To fix this we need to introduce a non-populating reader for the cache.

**Comment by slivne** [comment]
We have just added BYPASS CACHE for CQL, that from what I understand bypasses the cache completely and reads from memtables and sstables. 

Maybe we should merge this two directions - e.g. add the ability to read via the cache and not populate it on miss.

**Comment by duarten** [comment]
Yes, I thought about using bypass_cache, but we would still like to read
from it, just not populate it. According to @tgrabiec, adding a
non-populating reader is not too much work.

**Comment by duarten** [comment]
The entry can be a range tombstone, and what we're reading into cache might be a large number of rows (which we won't read again, since they're going to be deleted). Even if it's a row update, it's better to have the cache be sensitive to the read workload and not so much to the write one (otherwise we would just add all updates to the cache), no?

**Comment by avikivity** [comment]
@duarten we do add all updates to the cache. What we're missing is early eviction of updates that aren't recently accessed.

There's a good chance that a write will be read soon (consider a user updating their profile and then the front-end reloads the same data to display on the next page).

**Comment by slivne** [comment]
Reading through this ...

If the cache has all the information why is CQL BYPASS CACHE not using it as well - and simply not populating ?

**Comment by avikivity** [comment]
BYPASS CACHE means BYPASS CACHE, not use the information in the cache. Looking it up is expensive too and not useful for long streams.

**Comment by duarten** [comment]
@avikivity don't we only add rows that are already in the cache? We should at least not populate the cache in case of a base deletion. I also think that if it's true that a write will soon be read, then it's best to let the memtable+cache path handle that.

**Comment by avikivity** [comment]
Why not let the cache handle the aging-out of unneeded rows?

We already have the data, it's tons cheaper to read it from cache again than from disk. It's the cache's job to throw away unneeded data (currently it doesn't do a very sophisticated job, but it's still its job).

**Comment by tgrabiec** [comment]
@duarten Are you aiming to optimize single-row reads or scans? The problem of unnecessary reads of data covered by a tombstone in the memtable should be covered by https://github.com/scylladb/scylla/issues/324. Scans could be also handled, by putting the memtable stream through the cache reader, so that the cache reader can avoid going to sstables when it notices that a range is covered.

**Comment by duarten** [comment]
@tgrabiec MV writes, which need to do a read-before-write. If the write is a deletion, such as a range deletion or partition deletion, then we have to load all afected rows into cache, just to shadow them all by that write.

**Comment by tgrabiec** [comment]
@duarten I see, that's a different problem than I thought and my suggestion doesn't apply.

**Comment by slivne** [comment]
@psarna did we fix this ?

**Comment by nyh** [comment]
@slivne we recently discussed this issue in the context of repair's writes. In the specific context of write during repair, this proposal makes sense: Indeed, there is no reason to think that after repair writes a particular row, the client will read or write it again - so caching it isn't useful.

However, in the general case, of regular user writes, I think this proposal is wrong (or at least, not always right): If the user **writes** to the same base-table row twice, the caching we do today (and which this proposal hopes to eliminate) makes the second write faster because the row can be read from cache. Whether it is worth keeping this cache to speed up the second write is the usual caching tradeoff (except it's for writes, not reads) - but there is no obvious case here that it will never be worthwhile to keep this cached data.

**Comment by nyh** [comment]
See also issue #6233, where we discussed exactly the same ideas, and again decided (and implemented) to disable caching in the context of repair, but not during general writes. So probably this issue should be closed?

**Comment by slivne** [comment]
ok closing
