### ISSUE TITLE
Mark existing views as built for bootstrapping nodes

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#4001]
When a new node is bootstrapping, it will be streamed data for its base tables. If the views for those tables are marked as built, then the bootstrapping node does nothing. On the other hand, if the views haven't been built, then the node will eventually generate and propagate the associated view updates.

In both cases the node should mark the view as built in its local system tables, to prevent the view building process from kicking in, and it should also write to the distributed system views builts table.

**Comment by slivne** [comment]
@duarten - so it will be clearer. 

if the new node does "start the view building process" - the outcome of that is that it will rebuild the vews although they are updated - it seems a performance issue not a correctness one

once the view building process ends it will write to the distributed system views built table - so again its not a correctness issue - but performance one.

**Comment by duarten** [comment]
It is a performance one, yes. Although there’s a defenerate use-case, that of successive bootstraps where the same subset of keys keeps being moved around and being built.

**Comment by nyh** [comment]
Note that as @juliayakovlev noticed, this fix is also important for correctness of several dtests, such as mv_populating_from_existing_data_during_node_decommission_test and mv_populating_from_existing_data_during_extend_test, tests where a new node is added while a view is being built:
Our wait_for_view() dtest function (scylla_tools.py) checks for all living nodes to be marked in the distributed view table as done building. But today, the new node does not get marked as finished building, so depending on timing (whether view building finished on other nodes before the new node becomes live) wait_for_view() can hang because of this issue.
