### ISSUE TITLE
sstables: update_local_deletion_time for row marker deletion_time and expiration

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4026]
For some reason sstable::maybe_write_row_marker doesn't update min_local_deletion_time in column stats, only tombstone_histogram for dead row marker; and neither for expiring row marker.
This may affect mc format delta encoding that needs to track accurate min_local_deletion_time.

**Comment by bhalevy** [comment]
Edit: currently this does not affect mc format encoding since these stats reach stats_metadata and not serialization_header.

**Comment by argenet** [comment]
`sstable::maybe_write_row_marker` is only used for writing `ka`/`la` files, `mc` files don't use it.
For `mc` files, `writer::write_liveness_info` is used (from sstables/mc/writer.cc) and it updates timestamp/ttl/local_deletion_info values as follows, same as Cassandra (src/java/org/apache/cassandra/io/sstable/metadata/MetadataCollector.java, `void update(LivenessInfo newInfo)`)

**Comment by bhalevy** [comment]
@argenet, looking at mc writer::write_liveness_info and writer::write_collection I see that we don't update the tombstone_histogram (when the cell is dead or expiring and when the collection has_complex_deletion).  What's the reason for that?

**Comment by argenet** [comment]
@bhalevy indeed, looks like that's a missing piece. I'm a bit surprised with that because we have a test in sstable_3_x_test that specifically covers a collection-wide update that generates complex deletion so Statistics.db validation should probably have caught this but it hasn't.

But looking at what Cassandra code does, we clearly need to update the tombstone histogram for the `liveness_info` and for collection-wide deletions as those represent tombstones.

**Comment by argenet** [comment]
In Cassandra, all stats collection for `local_deltion_time` is done by an `updateLocalDeletionTime()` helper that both adds it to a min value tracker and, if not a special `NO_DELETION` value, adds it to the tombstone histogram.
It looks reasonable to introduce a similar helper in our code too.
