### ISSUE TITLE
SStable reads should rule out sstables based on the query clustering range

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4042]
Currently, single-row queries which miss in the cache will have to read from all sstables which contain given partition. This is inefficient, especially for time-series workloads which produce lots of sstables containing the same partition but have non-overlapping clustering ranges.

There was already an infrastructure to do this, but it was disabled in e1efda8b0c10aa71a425e1854e1e8e3d5f0f1efe due to bugs.

Also relevant for read-before-write done for materialized views.

**Comment by bhalevy** [comment]
@xemul this is tangential to the work you're doing on the row cache.  Please look into this issue.

**Comment by avikivity** [comment]
Note that to fix this we must move to `md` format, since `mc` format sstables are generated with incorrect clustering key extremums.

**Comment by avikivity** [comment]
Increasing priority since TWCS is important for CDC.

**Comment by bhalevy** [comment]
> Note that to fix this we must move to `md` format, since `mc` format sstables are generated with incorrect clustering key extremums.

@avikivity the incorrectness of the clustering key extremums is due to https://issues.apache.org/jira/browse/CASSANDRA-14861 where updating the min/max ck components is not done properly for range tombstones.  Although we need to fix that on our write path, fixing #3553 will include considering sstables having either partition tombstones or range tombstones, regardless of their clustering range.

**Comment by bhalevy** [comment]
Fixed by 3530e80ce10fc20b178c8fbe94ab151b43cf1714
