### ISSUE TITLE
Node crashed - reading system.local with many truncation entries leads to OOM

### ISSUE THREAD

**Issue by avnerbarr** [scylladb/scylla#4083]
```
scylla --version
2.2.0-0.20180705.240b9f122
```

Node crashed at some point, no out of the ordinary interaction with cluster led to it (load was very low)

Providing systems tables per @glommer request 

Thanks Glauber!

[for-glauber.zip](https://github.com/scylladb/scylla/files/2746590/for-glauber.zip)

**Comment by slivne** [comment]
I uploaded the system.local sstable files onto a regular table using the system.local schema and the truncated_at has ~3200 values ...

**Comment by glommer** [comment]
@avikivity please note that this may mean that just getting the compactions to be more aggressive will not be enough to truly fix this. Avner doesn't have that problem and still see an issue while reading the records since it becomes a gigantic map.

Also interesting to note that this means that the bug can, theoretically, happen in any system that is up for very long and truncate tables regularly regardless of number of tables

**Comment by avikivity** [comment]
That single row is 300kB. It should not be enough to OOM.

Truncating tables will overwrite the truncation records, so it shouldn't be a problem. But if we create and delete tables all the time, it will grow without bounds. Perhaps we should delete the entires after DROP TABLE.

**Comment by avikivity** [comment]
Also, we should move the truncation records into their own table, with the partition key being the table uuid (or name) and the clustering key being the shard number, instead of concentrating all truncate activity in the cluster into a single row.

**Comment by slivne** [comment]
Good idea
- We need to verify that drivers are not using this column ... 
- We did find some ```select * from system.local``` in the java driver
