### ISSUE TITLE
Improvements for loading sstables from /upload directory: resharding and seastar::thread

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#4118]
Following the discussion here: https://groups.google.com/forum/#!topic/scylladb-dev/xQudVfqn9lE

Code for distributed loader which loads sstables from /upload directory (triggered by `nodetool refresh`) could benefit from resharding the sstables *before* incorporating them into the database. The reason is that shared sstables influence write path and loading a large number of sstables from /upload temporarily creates a large number of shared sstables.

Currently all sstables are loaded first, and then a resharding job is triggered.

Also, distributed_loader::flush_upload_dir is a good candidate for migration to threaded context in order to avoid unnecessary code complexity.

**Comment by glommer** [comment]
I disagree with your statement that we should reshard before loading the code into the database.
This is a recovery operation and should finish ASAP. Resharding can take hours and is contrary to that.

When we need to use refresh in the field, at least half the time is to fix a disaster scenario. The sooner it finishes and makes the data available, the better.

The real problem `nodetool refresh` has, if you want to take a stab at fixing it (I tried in the past but had to drop) is that it has to take locks against flushes and compactions. The result of that is that if we refresh against a long running compaction that takes forever to finish -- exactly what we *don't* want.

Turns out those locks are not really needed: we only need to lock - if at all - the creation of the generation number, not the entire compaction. But removing them have its caveats.

**Comment by avikivity** [comment]
If refresh starts causing reads to fail, it's introducing its own disaster. If the previous and current shard data are coprime, then all sstables will be needed by all shards, and we'll have read amplification of smp::count on range scans (likely much lower on partition reads because of the bloom filter). On machines like i3.metal that's read amplification of 70.

**Comment by glommer** [comment]
That is unfortunately true.
But what I said is true as well. Maybe this will be less of a problem with run-based compaction strategies, that will be able to start consuming from newer sstables faster?

Also, even assuming we change refresh behavior: if we change that and don't get rid of those locks, the whole thing now takes the lock time + refresh time. This can easily bring the process to a two-digit number of hours.

**Comment by avikivity** [comment]
We'll be able to start using some of the data sooner, but not all the data.

In case we're restoring from a backup, it will usually have the same shard count, so resharding will be a no-op.

**Comment by glommer** [comment]
As much as I hate this operation taking forever, you are right that when there is need to reshard it may be worse if it we don't do it.

Can we at least make this patchset conditional in fixing the locking issue with compactions? Otherwise we will be making the situation much worse in terms of time it takes for this operation to complete in those cases.

**Comment by avikivity** [comment]
This patchset is conditional on someone writing it, but yes we can sneak the locks in

**Comment by raphaelsc** [comment]
SSTables loaded by refresh are now only loaded into the table after resharded and reshaped, so closing this issue...
