### ISSUE TITLE
ALLOW FILTERING gives wrong result when SELECT lists specific columns

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4121]
This issue is similar to issue #3803, which was marked solved but apparently is still partly incorrect.

On the user mailing list, temple3x@gmail.com discovered that a query like
```
select block from cold where date='2019-01-22' and start <=150262 and end >=150262 ALLOW FILTERING
```
works incorrectly (returns rows which should have been filtered out), whereas the same thing with a "select *" works correctly.

I wrote a simple unit test to reproduce this:

```c++
SEASTAR_TEST_CASE(test_allow_filtering_two_clustering_columns) {
    return do_with_cql_env_thread([] (cql_test_env& e) {
        e.execute_cql("CREATE TABLE t (p int, c1 int, c2 int, data int, PRIMARY KEY (p, c1, c2));").get();

        e.execute_cql("INSERT INTO t (p, c1, c2, data) VALUES (1, 2, 3, 1)").get();
        e.execute_cql("INSERT INTO t (p, c1, c2, data) VALUES (1, 3, 4, 2)").get();
        e.execute_cql("INSERT INTO t (p, c1, c2, data) VALUES (1, 2, 5, 3)").get();
        e.execute_cql("INSERT INTO t (p, c1, c2, data) VALUES (2, 3, 4, 4)").get();

        auto res = e.execute_cql("SELECT * FROM t WHERE p = 1 and c1 < 3 and c2 > 3 ALLOW FILTERING").get0();
        assert_that(res).is_rows().with_rows({
            {
                int32_type->decompose(1),
                int32_type->decompose(2),
                int32_type->decompose(5),
                int32_type->decompose(3)
            }
        });
        res = e.execute_cql("SELECT data FROM t WHERE p = 1 and c1 < 3 and c2 > 3 ALLOW FILTERING").get0();
        std::cout << res << "\n";
        assert_that(res).is_rows().with_rows({
            {
                int32_type->decompose(3)
            }
        });
    });
}
```
The first request has "select *" with restrictions on two clustering columns, and correctly returns just one row: (1, 2, 5, 3). The second request does the same request, just with "select data" instead of "select *", and should have returned just one row with data=3. But it fails because it also returns the first row, with data=1, which doesn't match the second filtering criterion (c2 > 3 is false for it).

CC: @psarna

**Comment by nyh** [comment]
The above was a unit test (which we can use directly as a regression test), but here is a more interactive example of the same thing, in cqlsh, for the curious:
```
CREATE KEYSPACE ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
USE ks;
CREATE TABLE t (p int, c1 int, c2 int, data int, PRIMARY KEY (p, c1, c2));
INSERT INTO t (p, c1, c2, data) VALUES (1, 2, 3, 1);
INSERT INTO t (p, c1, c2, data) VALUES (1, 3, 4, 2);
INSERT INTO t (p, c1, c2, data) VALUES (1, 2, 5, 3);
INSERT INTO t (p, c1, c2, data) VALUES (2, 3, 4, 4);
SELECT * FROM t WHERE p = 1 and c1 < 3 and c2 > 3 ALLOW FILTERING;

 p | c1 | c2 | data
---+----+----+------
 1 |  2 |  5 |    3

(1 rows)

SELECT data FROM t WHERE p = 1 and c1 < 3 and c2 > 3 ALLOW FILTERING;
 
 data
------
    1
    3

(2 rows)
```

**Comment by tzach** [comment]
Just reproduce on Scylla 3.0 as well

**Comment by nyh** [comment]
I'll take a stab at solving this issue (very sad how github doesn't let me change the fields like "assigned to" myself).

**Comment by psarna** [comment]
FYI: It's in `statement_restrictions::get_column_defs_for_filtering`. The code checks if there are any clustering columns that do not form a prefix, but it's not enough - prefix in a form of `c1 = 3 and c2 > 3` is fine and doesn't need filtering, but `c1 < 3 and c2 > 3` does, because inequality relation is only accepted as the last part of the prefix.
So, `statement_restrictions::get_column_defs_for_filtering` will qualify this set of restrictions as not needing filtering (when it fact they do), and will not add these columns as needed for post filtering.

**Comment by psarna** [comment]
Also, `cql3/restrictions/single_column_primary_key_restrictions.hh` has `single_column_primary_key_restrictions<clustering_key>::needs_filtering` which performs a very similar check correctly (that's one of the reasons it works fine with `SELECT *`).

**Comment by nyh** [comment]
@psarna yes, thanks, I know that `get_column_defs_for_filtering` is the bug, I just haven't yet figure out where the actual problem is. This function doesn't check any "prefix" as far as I can see, it calls `_clustering_columns_restrictions->needs_filtering()`, I guess that's where the code is wrong?

**Comment by nyh** [comment]
Right. Thanks! I'll fix it.

**Comment by nyh** [comment]
@psarna what drives me crazy now is how to get through all the layers of templates and virtual functions to get to the information I need :-)

**Comment by psarna** [comment]
@nyh https://github.com/scylladb/scylla/issues/3815 is all about that, unfortunately filtering was much higher priority than this, so it's still in the same sorry state of virtual functions and templates everywhere.

At the very least, `single_column_primary_key_restrictions` and `primary_key_restrictions` in general should be detemplatized, since they have lots of specifications for both partition key and clustering key anyway, so it pretty much only increases compilation time. I have all these improvements somewhere very deep in my backlog.

**Comment by psarna** [comment]
Actually, after I spend some more time on view building and hints, I'll have another go at this topic, prehaps just a small step of detemplatizing these key restrictions.
