### ISSUE TITLE
Default secondary index name contains redundant suffix

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#4146]
An unnamed index is given the "idx_index" suffix, which is weird and redundant:

Given

```
create table t (p int, c int, v int, primary key (p, c));
create index on t(c);
```

The underlying MV will be named "t_c_idx_index". It should be either "t_c_idx" or "t_c_index".

**Comment by nyh** [comment]
@duarten this redundancy happens because:

1. If the index name passed in "create index" is called xyz, we create a MV called xyz_index.
2. If no index name is given, we generate a name automatically looking like "t_c_idx".

We can't change 2 because it needs to be compatible with Cassandra because that's the only way to drop an index (see issue #3403). Something we could do is to change 1, so that if if the index name is xyz, the MV name will also be xyz. I think it makes sense, but maybe @penberg can comment on why he didn't do this.

Sadly, if we want to support data written by release 3.0 and we decide to change the MV's name, we'll need to have code which will look for both old and new names...

**Comment by duarten** [comment]
On Sun, Jan 27, 2019 at 13:49 nyh <notifications@github.com> wrote:

> @duarten <https://github.com/duarten> this redundancy happens because:
>
>    1. If the index name passed in "create index" is called xyz, we create
>    a MV called xyz_index.
>    2. If no index name is given, we generate a name automatically looking
>    like "t_c_idx".
>
> We can't change 2 because it needs to be compatible with Cassandra because
> that's the only way to drop an index (see issue #3403
> <https://github.com/scylladb/scylla/issues/3403>). Something we could do
> is to change 1, so that if if the index name is xyz, the MV name will also
> be xyz. I think it makes sense, but maybe @penberg
> <https://github.com/penberg> can comment on why he didn't do this.
>
> Sadly, if we want to support data written by release 3.0 and we decide to
> change the MV's name, we'll need to have code which will look for both old
> and new names...
>

Why would this be needed?

**Comment by nyh** [comment]
@duarten because if somebody creates a secondary index with Scylla 3.0, it will create a materialized view called (for example) `t_c_idx_index`. If we change the code in ` indexed_table_select_statement::prepare()` to not add this "_index" (we also need to change `index_table_name()` in secondary_index_manager.cc), using the old index won't work. What I meant was that the code will in prepare() will need to look for both options, to support upgrades... No?

**Comment by duarten** [comment]
On Sun, Jan 27, 2019 at 14:48 nyh <notifications@github.com> wrote:

> @duarten <https://github.com/duarten> because if somebody creates a
> secondary index with Scylla 3.0, it will create a materialized view called
> (for example) t_c_idx_index. If we change the code in
> indexed_table_select_statement::prepare() to not add this "_index" (we
> also need to change index_table_name() in secondary_index_manager.cc),
> using the old index won't work. What I meant was that the code will in
> prepare() will need to look for both options, to support upgrades... No?
>

I don't see why. Users can name indexes, so changing the default name to
something else will make the previously created indexes seem like
user-named ones. At least I hope we don't have read-path code depending on
how the default name is generated 🤭

**Comment by nyh** [comment]
@duarten, as I explained in my first comment, we have two steps: First, there is the index's *name*. This has a default, but can be overridden, and we correctly have a table of index names. The **index name** is a Cassandra concept, and in your example it is `t_c_idx`. But then, we have a second translation - of that name into the view's name. This is done (see `indexed_table_select_statement::prepare()`) by adding a "_index" at the end. This step is hard-coded. We can obviously change it, but I don't see how we can support both the old and new ways without special code which just checks for the existence of both). Not impossible of course, but (I think) fairly ugly.

By the way, there's something we need to verify: Does Cassandra allow creating a table called "xyz" and also an index (of some other table, perhaps!) called "xyz"? If it does, we cannot simply name our MV "xyz" because you can't have a MV with the same name as an existing table. That could be a reason to name the MV something like we do today ("xyz_index") instead of just "xyz". However, if Cassandra doesn't allow creating an index with the same name as an existing table (and vice versa), then this is not a problem, and we could indeed call the MV "xyz".

**Comment by nyh** [comment]
I'm dropping the n00b tag - I'm not sure we really want to do this and I don't want a n00b to figure this out. Also, if we do decide to do this, as I explained above there are compatibility issues and avoiding them will require this fix to less trivial.

**Comment by nyh** [comment]
I'm closing this issue. I don't think we'll ever want to change this. This issue has some useful information on index and their backing-MV naming - but it doesn't mean it should remain open.
