### ISSUE TITLE
View building can be indefinitely paused with large partitions present

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#4213]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): master (da9628c6d)

As for now, view builder sends updates in partition granularity. With big enough partitions (bigger than commitlog's `max_mutation_size`) it won't be able to proceed, because the mutation will be too big for commitlog to handle.

The simple workaround is increasing commitlog's `max_mutation_size`, which is fortunately configurable via commitlog_segment_size_in_mb.

The solution could be increasing granularity of view building - so after reading enough rows that their size hit a soft limit, smaller than `max_mutation_size`,  view builder will generate view updates from what it has already, even if it's not the end of current partition yet.

**Comment by nyh** [comment]
@psarna is this a problem you saw in practice, or a thought experiment?

I'm probably confused, but doesn't the view builder already work in row granularity, not in partition granularity? When you read a base partition with many rows, each of these rows can need to (depending on the view's schema) be sent to a different view partition, so we cannot generally bundle all of them in one view write.

Do we have an optimization that **when** we can bundle all the base rows into one view partition (namely, view and base partition key are the same, and by the way, view write will be local on the same node), we do this, and that is the case you want to fix?

**Comment by psarna** [comment]
It was hit in practice, with view partition key the same as in base (and one additional clustering key). And yes, I think the only way it could have happened is that all rows were bundled into a single mutation, which then failed to be stored.

**Comment by nyh** [comment]
I found where the batching happens:

The view build code reads an entire base partition and at its end (consume_end_of_partition()) wraps it up in one reader "_fragments" and calls `table::populate_views()` on the entire base partition at once. `table::populate_views()` calls `db::view::generate_view_updates()` which uses a `view_update_builder` object. This object holds a vector of `view_updates` objects, one `view_updates` object per view of this base table.

The `view_updates` object has a
```c++
std::unordered_map<partition_key, mutation_partition, partition_key::hashing, partition_key::equality> _updates;
```

This is what batches up all the updates intended for one view partition key together. Although the code of `generate_view_update()` actually works on each row separately, the results are written into this `_updates`, which collect all the mutations intended for the same view partition key into one mutation.

Finally, `generate_view_updates()`  calls `view_update_builder::build()`. This function converts the map of mutations collected for each partition to a vector of mutations. The conversion is done by calling `view_updates::move_to()` - this function takes the (possibly long) mutation collected for each partition key, and converts it to one "mutation" object to be put in `build`'s output vector.

**This, view_updates::move_to(), is where we can fairly easily intervene to split up a very long mutation into several smaller mutations each for the same key**.

After all this is done, `table::populate_views()` will then call `mutate_MV()` is to send these mutations. It doesn't mind if we have several mutations for the same partition key. In our case, it doesn't even sends these mutations, it applies them locally (because when the partition key is the same in view and base, the paired replica is the local machine).

There's another very different way we can solve this problem. This second method is probably better than fix suggersted above:

As I said, the view builder code currently works on entire base partitions. There is no real reason why it needs to do this (it anyway works on a individual base rows). Reading an entire base partition into memory can also be a problem regarding memory use. Instead, what the view builder could do is to call `populate_views()` not just at `consume_end_of_partition()` but rather, each time it has read "enough" base rows. If we limit the amount to base rows we read together to X MB, then the resulting view mutation will also be smaller than X MB in size. Thus we automatically solve the problem of the view mutation, and *also* solve the (unreported yet) problem of memory use while view-building on huge base partitions.

**Comment by nyh** [comment]
By the way, we should write a unit-test to reproduce this issue - the unit test can create a base table with one partition with a large number of rows, and then create a view (with the same partition key as the base!) on top of it, and wait for the view to be built. With the current bug, this test will timeout if the number of rows in the base partition is too big.

**Comment by glommer** [comment]
@nyh your first solution is not good enough in my view (just splitting the mutation into several ones). Materializing the whole thing in memory can exhaust our shard's memory very easily, we see in practice lots of partitions that can be larger than the shard's memory.

@slivne if I understand correct the impact of this issue is that view building is impossible in practice with any partition more than 100MBs in size. Partitions in this range are extremely common - we don't even call them "large" in practice until they reach a couple of GB. Therefore this should be prioritized. Agree?

**Comment by slivne** [comment]
I agree

@nyh i think you were working on a unitest and a solution

If thats not true @psarna please handle it (wait for nyh input)

**Comment by nyh** [comment]
My analysis above was incomplete. I wrote a unit test which creates a base partition of 10,000 rows, and discovered that `view_updates::move_to()` was not given all 10,000 rows at once, but rather batches of 128 rows only!

It turns out `view_builder.hh` has a batch_size=128 variable, and the base partition consumer is already set to stop after every 128 base rows even before reaching the end of the base partition. This means that something very similar to the second solution I suggested, already existed in the code!

So the question becomes, how did @glommer have a problem with this? If commitlog_segment_size_in_mb = 32, for 128 base rows to be above 32MB, each row would need to be 256 KB in size. Glauber, do you know if the use case that had this problem had large blobs?

Maybe we need to stop the base-partition consumer not after a fixed number of rows but after some total data size, but I'd like to understand the problem better before proposing a fix.

**Comment by glommer** [comment]
I don't know for sure if that is the case but it is likely, as the schema has blobs.
It's hard to verify for sure - it would be easy if the error messages pointed at keys (although that is hard to do at the commitlog layer)
