### ISSUE TITLE
range scan WITH FILTERING return wrong rows

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4230]
Scylla version (or git commit hash): 3.0.3

```
cqlsh:mykeyspace> CREATE TABLE IF NOT EXISTS air_quality_data2 (sensor_id text,time timestamp,location text, co_ppm int,PRIMARY KEY (sensor_id));
cqlsh:mykeyspace> 
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-05 07:01:00', 'ISR', 17);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-06 07:02:01', 'ISR', 18);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-07 07:03:02', 'ISR', 19);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-08 07:04:03', 'ISR', 20);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-09 07:05:04', 'ISR', 30);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-10 07:06:04', 'ISR', 31);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-11 07:07:10', 'ISR', 20);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-12 07:01:00', 'ISR', 17);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-13 07:02:01', 'ISR', 18);
cqlsh:mykeyspace> INSERT INTO air_quality_data2(sensor_id, time, location, co_ppm) VALUES ('my_home', '2018-06-14 07:03:02', 'ISR', 19);
cqlsh:mykeyspace> select * from air_quality_data2 WHERE time>'2019-02-15 14:00:00' and time<'2019-02-15 06:00:00' allow filtering;

 sensor_id | co_ppm | location | time
-----------+--------+----------+---------------------------------
   my_home |     19 |      ISR | 2018-06-14 07:03:02.000000+0000
```

Note that the WHERE should never return info, as in the original example.
Not sure why only one element was returned in this case.

**Comment by psarna** [comment]
1. Note that in your schema `sensor_id` is the primary key, so in fact all these `INSERT` statements just overwrite one entry - hence there's only one element returned.
2. I tried with types other than dates, and same trick doesn't work with ints or strings, so it looks like a preexisting problem with date/time comparison maybe?

**Comment by psarna** [comment]
Also, I see that when I change the range to something non-empty, filtering works fine. So my educated guess is that it's because it's using wrapping range instead of nonwrapping. I'll try it in a minute and update.

**Comment by psarna** [comment]
I don't have time to create a proper patch today, but the problem is that `statement_restrictions.cc` has `single_column_restriction::slice::is_satisfied_by()`, which uses a helper function `to_range`, which transforms a slice into a **wrapping** range. That's useful for token restrictions, but harmful for regular restrictions, because non-conventional ranges like `x < 3 and x > 5` will be translated to 'x is accepted if it's anything less than 3 or bigger than 5, because the range wraps around itself'.

The solution is to prepare a non-wrapping version of `to_range` function and use it in `single_column_restriction::slice::is_satisfied_by()` + add proper test cases.

I can do it after the weekend unless there are volunteers (if there are none, somebody can just assign this one to me and it will wait in my long queue :) )

**Comment by psarna** [comment]
Also, note that it's only harmful if somebody passes a non-conventional range to the query, i.e. when range's start is larger than its end. So a quick workaround is to provide sensible restrictions to queries :) as I doubt many applications use this kind of ranges in real-life queries, because there's no need to ask the database for a range that we already know should be empty.

(and @tzach, if we indeed pass a conventional range to your repro, it returns 0 rows as it should)

**Comment by tzach** [comment]
> 1. Note that in your schema `sensor_id` is the primary key, so, in fact, all these `INSERT` statements just overwrite one entry - hence there's only one element returned.

Ouch. My example is broken

**Comment by tzach** [comment]
Closing, the reproduce example was wrong
