### ISSUE TITLE
fragmented_temporary_buffer::read_exactly() allocates huge amounts of memory on premature end-of-stream

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#4233]
`fragmented_temporary_buffer:read_exactly()`, if given a stream with not enough data, will allocate huge amounts of memory until it fails with bad_alloc.

This can happen reading from the native transport, if the connection is closed in the middle of a frame, from commitlog, and possibly other places.

**Comment by pdziepak** [comment]
I don't think the underlying problem is really fixed. We have `read_exactly()` that doesn't read exactly and there is not a single word of comment explaining this incorrect name anywhere.

As I see it `input_buffer::read_exactly()` was broken by violating the post-condition given in its name and the patch made `fragmented_temporary_buffer::read_exactly()` broken in the same way, also without adding any comments.

The alternatives seem to be to either fix `read_exactly()` behaviour to match its name and fail if end of stream prevents it from reading the requested amount of data (better solution) or to keep the wrong name and document this problematic behaviour (not so good solution).

**Comment by avikivity** [comment]
Returning an exception is possible but can make non-exceptional code use exceptions (read a frame header using read_exactly, get an exception on eof). It is common for read() to return zero on EOF, so read_exactly() did exactly that. Certainly it should at least have been documented.

Another option is to return optional<temporary_buffer>, or an optimized variant thereof.


About the underlying problem - I agree it's not solved, but this was not attempting to solve it. I looked again and I see that transport/server.cc isn't checking for eof everywhere, so even the best case (where it's just a premature socket close) isn't fixed.

**Comment by pdziepak** [comment]
`read_exactly` is not noexcept so its users are not allowed to assume that it doesn't throw.

Considering the name `read_exaclty()` I think that an EOF is definitely an error. The user was expecting an exact number of bytes, but we couldn't provide them. Right now that error is reported by returning a value that violates a post-condition strongly implied by the function name. That's not exactly the safest and best interface.

Now, the question is how to properly propagate that error. Exceptions don't really fit the requirements here, even though we are overusing them a lot. `std::optional` is okay but not very specific. I guess it is time we start using something like `std::expected` (or a custom version of it, until it gets to the standard).

**Comment by nyh** [comment]
On Mon, Feb 18, 2019 at 3:44 PM Paweł Dziepak <notifications@github.com>
wrote:

> read_exactly is not noexcept so its users are not allowed to assume that
> it doesn't throw.
>
> Considering the name read_exaclty() I think that an EOF is definitely an
> error.
>
I agree. For example commit 7b1f433aed1d227425be1b339824757ab78096fe which
introduced dma_read_exactly()
said that it throws an exception if fails to read the required number of
bytes (EOF). But sadly, this appears to be only
documented in the commit message (which is not where I like to find
documentation).


> The user was expecting an exact number of bytes, but we couldn't provide
> them. Right now that error is reported by returning a value that violates a
> post-condition strongly implied by the function name. That's not exactly
> the safest and best interface.
>
> Now, the question is how to properly propagate that error. Exceptions
> don't really fit the requirements here, even though we are overusing them a
> lot. std::optional is okay but not very specific. I guess it is time we
> start using something like std::expected (or a custom version of it,
> until it gets to the standard).
>
Why *don't* exceptions (inside the future! not throwing one!) fit the
requirements?

Our seastar::future is already very much like std::expected... it returns
(eventually) either a value, or an error.
And since read_exactly() already returns a future, what more can we ask for?

Note that to set a future to return from read_exactly(), we do not really
throw an exception, it's quick and lock free.
Our only difficulty is how to check the type of exception without a
try/catch. I'm not sure if it's something we need to solve at all. I think
that in most of our use case, we'll simply let that future's error
propagate - e.g., it may cause an entire user request to fail because one
read_exactly() failed. Isn't that exactly what we want?

>

**Comment by pdziepak** [comment]
Exception inside a future is still an exception. You need to throw it to get to it, which means that the same restrictions apply as to other uses of exceptions.

EOF in `read_exactly()`, while an error is perfectly normal thing. We may be in a middle of reading a request from the client, and while hoping for the best we don't fully trust it and expect that it may drop connection at any random point. If we throw on EOF and the server is publicly visible, that would be a perfect way to DoS it.

Futures are not a solution since:
* we may need to get to the error type and react differently, that means throwing the exception
* we need a unified and performant way of reporting errors for which exceptions are not acceptable, there are large portions of logic that do not see any futures so they cannot rely on the fact that futures make the exceptions "slightly less absolutely terrible", that code however still needs to integrate seamlessly with the futures at some point

**Comment by nyh** [comment]
On Mon, Feb 18, 2019 at 4:08 PM Paweł Dziepak <notifications@github.com>
wrote:

> Exception inside a future is still an exception. You need to throw it to
> get to it, which means that the same restrictions apply as to other uses of
> exceptions.
>
That is true if you want to "get to it", i.e., check which kind of
exception it is. If the only purpose of this exception is to cause the
current operation to fail (e.g., a request where we got an EOF in the
middle of its processing will fail), then it's fine. I think. But I guess
you don't think it's fine, because:


> EOF in read_exactly(), while an error is perfectly normal thing. We may
> be in a middle of reading a request from the client, and while hoping for
> the best we don't fully trust it and expect that it may drop connection at
> any random point. If we throw on EOF and the server is publicly visible,
> that would be a perfect way to DoS it.
>
So you're saying that if we allow one exception per request, this will
constitute a DoS?
That would be very sad. It would mean we cannot use exceptions in any of
the code which can happen on every client request.
But I think we already do this a lot. For example, we use various
invalid_request_exceptions when we see syntax errors in the CQL parser.
So the client can already send us a million requests per second with a
syntax error in each, and cause a million syntax errors per second.

If we think we can't afford exceptions, we'll need to indeed start thinking
of adding a parallel error mechanism in Scylla and Seastar. Either using
seastar::future<std::expected<V, E>> everywhere, or adding the additional
error mechanism directly into to futures (more on this idea, below).

But personally, I think that fixing exceptions to be workable for the rate
of one-per-request - as Gleb did in the past - is a safer and easier
solution.


> Futures are not a solution since:
>
>    - we may need to get to the error type and react differently, that
>    means throwing the exception
>    - we need a unified and performant way of reporting errors for which
>    exceptions are not acceptable, there are large portions of logic that do
>    not see any futures so they cannot rely on the fact that futures make the
>    exceptions "slightly less absolutely terrible", that code however still
>    needs to integrate seamlessly with the futures at some point
>
>
We could use std::expected<V, E> for immediate values and
seastar::future<std::expected<V, E>> for future values everywhere.

Alternatively we could also modify the existing future to hold either an
exception or a non-exception error. For example something like

namespace seastar {
class error {
     bool _is_exception; // chooses which of the two variants is active
     std::variant<int, std::exception_ptr> _error;
     bool is_code() const { return !_is_exception; }
     int code() const { return get<int>(_error); }
 }
}

Then have immediate<T> and future<T>.
An immediate<T> carries either the value T, or a seastar::error.
A future<T> is the same thing, but is just set in the future. future<T> may
be implemented using immediate<T>.
A code will be able to do something like

    future<int> f();
    f.then_wrapped([](immediate<int> f) {    // unrelated note:
then_wrapped can pass immediate instead of future :-)
         if (f.failed() && f.is_code() && f.code() == 7) {
             // handle error code 7, no exceptions involved.
         } else {
            return std::move(f); // just propegate other errors. should
return f or create a new error future? I don't remember :-)
         }
   });

However, it's not pretty to start having integer error codes, as in the
1970s C library... If we make the error code a template parameter, I'm
worried this will add a lot of complexity everywhere futures are used.
Although it's probably doable.

**Comment by pdziepak** [comment]
On Tue, 19 Feb 2019 at 08:57, nyh <notifications@github.com> wrote:

> On Mon, Feb 18, 2019 at 4:08 PM Paweł Dziepak <notifications@github.com>
> wrote:
>
> > Exception inside a future is still an exception. You need to throw it to
> > get to it, which means that the same restrictions apply as to other uses
> of
> > exceptions.
> >
> That is true if you want to "get to it", i.e., check which kind of
> exception it is. If the only purpose of this exception is to cause the
> current operation to fail (e.g., a request where we got an EOF in the
> middle of its processing will fail), then it's fine. I think. But I guess
> you don't think it's fine, because:
>

It is not fine. If a request processing fails an upper layer may want to
know whether the reason for that is a dropped connection, invalid data on
wire or an unsupported request and take different actions accordingly. We
need to care about catch as much as we care about throw.
In most cases when an operation fail we need to propagate that information
the the client, which means at some point the exception needs to be
converted to an error message. Often, we may also want to put something in
the logs.
Seastar makes this worse since each handle_exception() is a separate
throw-catch.


>
>
> > EOF in read_exactly(), while an error is perfectly normal thing. We may
> > be in a middle of reading a request from the client, and while hoping for
> > the best we don't fully trust it and expect that it may drop connection
> at
> > any random point. If we throw on EOF and the server is publicly visible,
> > that would be a perfect way to DoS it.
> >
> So you're saying that if we allow one exception per request, this will
> constitute a DoS?


I can't tell for sure that depends on many things (how many times the
exception is going to be rethrown by its handlers?), but in a server
environment there is no such thing as "this request failed so we don't care
about its performance". The time taken to process failed request is time
not used by those requests that are successful. That's why I think
exceptions have little place in servers. It's not just about performance,
either. They are not exactly safe and are hard to reason about.


> That would be very sad. It would mean we cannot use exceptions in any of
> the code which can happen on every client request.
> But I think we already do this a lot. For example, we use various
> invalid_request_exceptions when we see syntax errors in the CQL parser.
> So the client can already send us a million requests per second with a
> syntax error in each, and cause a million syntax errors per second.
>
> If we think we can't afford exceptions, we'll need to indeed start thinking
> of adding a parallel error mechanism in Scylla and Seastar. Either using
> seastar::future<std::expected<V, E>> everywhere, or adding the additional
> error mechanism directly into to futures (more on this idea, below).
>

Yes, I believe it was a design mistake to use exceptions in Seastar. They
are not completely and totally bad, and have their uses, but server code
has very different requirements.


>
> But personally, I think that fixing exceptions to be workable for the rate
> of one-per-request - as Gleb did in the past - is a safer and easier
> solution.
>
>
I believe that was a bad call. The time spent to fix one particular problem
with exception would be much better spent by working on moving away from
them. The stack unwinding is still slow and it is still hard to reason
about them. I don't think we are in position to fix any of those problems
and make exceptions acceptable.


>
> > Futures are not a solution since:
> >
> > - we may need to get to the error type and react differently, that
> > means throwing the exception
> > - we need a unified and performant way of reporting errors for which
> > exceptions are not acceptable, there are large portions of logic that do
> > not see any futures so they cannot rely on the fact that futures make the
> > exceptions "slightly less absolutely terrible", that code however still
> > needs to integrate seamlessly with the futures at some point
> >
> >
> We could use std::expected<V, E> for immediate values and
> seastar::future<std::expected<V, E>> for future values everywhere.
>

If we have seastar::expected<T> futures can embrace it completely, so that
we keep using std::future<T>. When we get a standard solution we will
adjust the interface.


>
> Alternatively we could also modify the existing future to hold either an
> exception or a non-exception error. For example something like
>
> namespace seastar {
> class error {
> bool _is_exception; // chooses which of the two variants is active
> std::variant<int, std::exception_ptr> _error;
> bool is_code() const { return !_is_exception; }
> int code() const { return get<int>(_error); }
> }
> }
>
> Then have immediate<T> and future<T>.
> An immediate<T> carries either the value T, or a seastar::error.
> A future<T> is the same thing, but is just set in the future. future<T> may
> be implemented using immediate<T>.
> A code will be able to do something like
>
> future<int> f();
> f.then_wrapped([](immediate<int> f) { // unrelated note:
> then_wrapped can pass immediate instead of future :-)
> if (f.failed() && f.is_code() && f.code() == 7) {
> // handle error code 7, no exceptions involved.
> } else {
> return std::move(f); // just propegate other errors. should
> return f or create a new error future? I don't remember :-)
> }
> });
>
> However, it's not pretty to start having integer error codes, as in the
> 1970s C library... If we make the error code a template parameter, I'm
> worried this will add a lot of complexity everywhere futures are used.
> Although it's probably doable.


Error codes in the form that requires the user to write `f.code() == 7` are
hostile towards programmers and are definitely not a way to do this. We can
have a type-erased seastar::error or build something on top of
std::error_code (though it may be harder to integrate with the existing
code). I'll send some draft design to the seastar mailing list soon, since
this definitely deserves its own thread (even though the root cause of this
issue that we've hijacked is an incorrectly propagated error).

Note that with [[nodiscard]] error codes are safer than exceptions since
you can miss the fact than an exception is thrown, but cannot miss an error
code.

**Comment by gleb-cloudius** [comment]
On Tue, Feb 19, 2019 at 07:03:54AM -0800, Paweł Dziepak wrote:
> > But personally, I think that fixing exceptions to be workable for the rate
> > of one-per-request - as Gleb did in the past - is a safer and easier
> > solution.
> >
> >
> I believe that was a bad call. The time spent to fix one particular problem
> with exception would be much better spent by working on moving away from
> them. The stack unwinding is still slow and it is still hard to reason
> about them. I don't think we are in position to fix any of those problems
> and make exceptions acceptable.
> 
> 
You cannot get rid of all exception. Standard library throws. IIRC there
is a flag to disable that, but do you want to check every allocation for
null? Using exceptions for timeouts was a bad call, yes, it was forced
by the fact that our future holds either value or exception. May be exception
part should have been variant<seastar_error, exception_ptr>. 

--
			Gleb.

**Comment by pdziepak** [comment]
Well, the committee appears to be slowly reaching a consensus that using exceptions in the standard library was also a bad call.

I am aware that we cannot completely get rid of exceptions, but it doesn't mean that there's nothing we can do. Arbitrary `std::bad_alloc`s (especially if an object is small) in Scylla are often bugs (in some places we outright make them abort the server), because some overload protection didn't work as expected. Allocation strategies and other mechanisms used for handling user (i.e. of unknown size) data could use `seastar::expected`.

Whatever we end up with it definitely needs to inter-operate with exceptions as seamlessly as possible, partly because the standard library is not going to stop using them anytime and partly because there is already a lot of code written that uses them. That'd be the case even if we get a production-ready implementation of [P0709](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0709r0.pdf) ("Zero-overhead deterministic exceptions: Throwing values") backported to gcc8 first thing tomorrow morning.

**Comment by nyh** [comment]
On Tue, Feb 19, 2019 at 5:03 PM Paweł Dziepak <notifications@github.com>
wrote:

> On Tue, 19 Feb 2019 at 08:57, nyh <notifications@github.com> wrote:
> > So you're saying that if we allow one exception per request, this will
> > constitute a DoS?
>
>
> I can't tell for sure that depends on many things (how many times the
> exception is going to be rethrown by its handlers?)


We already try *not* to rethrow exceptions. In the past a lot of
future-handling code incorrectly did that, but it no longer does, and the
exception_ptr is just passed unchanged. I believe that in most cases in
Scylla, the exception propagates all the way to stopping the current
request (when it's part of a request), and only there it is caught once.
If that's not the case, we should improve it.



> , but in a server
> environment there is no such thing as "this request failed so we don't care
> about its performance".


That is not what I said. It's just that if exceptions no longer have global
locks
it's not clear that their performance is that terrible. Also "terrible" is
a relative
term, something which is unacceptable if we need to call it 10,000,000 times
each second may be perfectly acceptable if we "only" need to call it 10,000
times each second (per core).

Returning to the topic of this discussion, if read_exactly() is something we
expect to fail a million times per second, it would indeed be a problem to
make it fail using an exception. But if a read_exactly() failure *always*
leads to failure of an entire request, complete with a lot of overheads
related to such failure (maybe logging, a lot of wasted work we have done,
etc.), then maybe the exception would be the least of our problems.


> The time taken to process failed request is time
> not used by those requests that are successful. That's why I think
> exceptions have little place in servers. It's not just about performance,
> either. They are not exactly safe and are hard to reason about.
>

We should probably move this discussion to seastar-dev and try to come
to some decisions if we're starting to think of deprecating exceptions in
Seastar
(or adding alternatives to them in Seastar - I suggested some ideas and you
did too).
But my wonder is, since we *are* already exceptions, whether using them
*also*
in this case (read_exactly()) will create any new problem.

Yes, I believe it was a design mistake to use exceptions in Seastar. They
> are not completely and totally bad, and have their uses, but server code
> has very different requirements.
>

Maybe it's time to start discussing Seastar 2.0, replacing, or
supplementing,
exceptions.

> But personally, I think that fixing exceptions to be workable for the rate
> > of one-per-request - as Gleb did in the past - is a safer and easier
> > solution.
> >
> >
> I believe that was a bad call. The time spent to fix one particular problem
> with exception would be much better spent by working on moving away from
> them. The stack unwinding is still slow


Is it slow?
I believe 99% of our exception catching happens in the same function (in
then(), and possibly rethrown to check their type),
so the stack unwinding should be relatively fast. But I never measured this
in practice. Did you? (with Gleb's patches,
of course).



> a
> Error codes in the form that requires the user to write `f.code() == 7` are
> hostile towards programmers and are definitely not a way to do this. We can
> have a type-erased seastar::error or build something on top of
> std::error_code (though it may be harder to integrate with the existing
> code). I'll send some draft design to the seastar mailing list soon, since
> this definitely deserves its own thread (even though the root cause of this
> issue that we've hijacked is an incorrectly propagated error).
>

Great.

**Comment by pdziepak** [comment]
On Wed, 20 Feb 2019 at 10:59, nyh <notifications@github.com> wrote:

> On Tue, Feb 19, 2019 at 5:03 PM Paweł Dziepak <notifications@github.com>
> wrote:
>
> > On Tue, 19 Feb 2019 at 08:57, nyh <notifications@github.com> wrote:
> > > So you're saying that if we allow one exception per request, this will
> > > constitute a DoS?
> >
> >
> > I can't tell for sure that depends on many things (how many times the
> > exception is going to be rethrown by its handlers?)
>
>
> We already try *not* to rethrow exceptions. In the past a lot of
> future-handling code incorrectly did that, but it no longer does, and the
> exception_ptr is just passed unchanged. I believe that in most cases in
> Scylla, the exception propagates all the way to stopping the current
> request (when it's part of a request), and only there it is caught once.
> If that's not the case, we should improve it.
>

So we acknowledge the problem with the exceptions, but still try to make
them work and in effect make everything more difficult for ourselves.
Wouldn't it be better if we had an error propagation mechanism that isn't
as easy to use incorrectly?


>
>
>
> > , but in a server
> > environment there is no such thing as "this request failed so we don't
> care
> > about its performance".
>
>
> That is not what I said. It's just that if exceptions no longer have global
> locks
> it's not clear that their performance is that terrible. Also "terrible" is
> a relative
> term, something which is unacceptable if we need to call it 10,000,000
> times
> each second may be perfectly acceptable if we "only" need to call it 10,000
> times each second (per core).
>
> Returning to the topic of this discussion, if read_exactly() is something
> we
> expect to fail a million times per second, it would indeed be a problem to
> make it fail using an exception. But if a read_exactly() failure *always*
> leads to failure of an entire request, complete with a lot of overheads
> related to such failure (maybe logging, a lot of wasted work we have done,
> etc.), then maybe the exception would be the least of our problems.
>

Perhaps, but now we need to have this reasoning every time an error can
happen. Isn't that a sign that exceptions are simply not a good choice for
our needs?


>
>
> > The time taken to process failed request is time
> > not used by those requests that are successful. That's why I think
> > exceptions have little place in servers. It's not just about performance,
> > either. They are not exactly safe and are hard to reason about.
> >
>
> We should probably move this discussion to seastar-dev and try to come
> to some decisions if we're starting to think of deprecating exceptions in
> Seastar
> (or adding alternatives to them in Seastar - I suggested some ideas and you
> did too).
> But my wonder is, since we *are* already exceptions, whether using them
> *also*
> in this case (read_exactly()) will create any new problem.
>
> Yes, I believe it was a design mistake to use exceptions in Seastar. They
> > are not completely and totally bad, and have their uses, but server code
> > has very different requirements.
> >
>
> Maybe it's time to start discussing Seastar 2.0, replacing, or
> supplementing,
> exceptions.
>

I don't think seastar 2.0 is a good idea. We should make gradual changes,
since that would make it easier to evolve the code (abandon exceptions,
make future stop being a tuple) and react if something is not working as
well as planned. Otherwise, we would just make a different set of design
mistakes than the first time and soon will need to start talking about
seastar 3.0.


>
> > But personally, I think that fixing exceptions to be workable for the
> rate
> > > of one-per-request - as Gleb did in the past - is a safer and easier
> > > solution.
> > >
> > >
> > I believe that was a bad call. The time spent to fix one particular
> problem
> > with exception would be much better spent by working on moving away from
> > them. The stack unwinding is still slow
>
>
> Is it slow?
> I believe 99% of our exception catching happens in the same function (in
> then(), and possibly rethrown to check their type),
> so the stack unwinding should be relatively fast. But I never measured this
> in practice. Did you? (with Gleb's patches,
> of course).
>
>
Did you measure that 99%? We do have synchronous logic that can throw and
produce long backtraces.
My point is that with dynamic exceptions it is hard to reason about
anything. It is hard to predict whether their slowness is going to be
acceptable (and I think there is no question that stack unwinding is going
to be slower than std::expected), it is hard to tell if a function can
fail. Their only advantage is that they truly have minimal cost when never
thrown, but that's not something we can hope for in a server code.

**Comment by elcallio** [comment]
Den 2019-02-20 kl. 12:30, skrev Paweł Dziepak:
> On Wed, 20 Feb 2019 at 10:59, nyh <notifications@github.com> wrote:
>
> > On Tue, Feb 19, 2019 at 5:03 PM Paweł Dziepak <notifications@github.com>
> > wrote:
> >
> > > On Tue, 19 Feb 2019 at 08:57, nyh <notifications@github.com> wrote:
> > > > So you're saying that if we allow one exception per request, 
> this will
> > > > constitute a DoS?
> > >
> > >
> > > I can't tell for sure that depends on many things (how many times the
> > > exception is going to be rethrown by its handlers?)
> >
> >
> > We already try *not* to rethrow exceptions. In the past a lot of
> > future-handling code incorrectly did that, but it no longer does, 
> and the
> > exception_ptr is just passed unchanged. I believe that in most cases in
> > Scylla, the exception propagates all the way to stopping the current
> > request (when it's part of a request), and only there it is caught once.
> > If that's not the case, we should improve it.
> >
>
> So we acknowledge the problem with the exceptions, but still try to make
> them work and in effect make everything more difficult for ourselves.
> Wouldn't it be better if we had an error propagation mechanism that isn't
> as easy to use incorrectly?
>
Isn't the core of that problem that you have two distint modes of error 
propagations dictated by the continuation model? It seems to me that 
solving the awkward `.then(...)` semantics (coroutines?) would in 
general be more helpful to guarantee that code does not miss handling 
errors, given that the track record is generally we've failed at 
handling both synchronous and async exception cases in code, and end up 
wrapping stuff in useless "then" calls just to get uniform handling.

And btw, even with sutters proposal, the same problem remains with 
seastar code.

Also, since I don't think anyone wants to drop stl or even stl interop, 
moving to yet another home-invented error mechanism sounds at best 
futile and perilous.

>
> >
> >
> >
> > > , but in a server
> > > environment there is no such thing as "this request failed so we don't
> > care
> > > about its performance".
> >
> >
> > That is not what I said. It's just that if exceptions no longer have 
> global
> > locks
> > it's not clear that their performance is that terrible. Also 
> "terrible" is
> > a relative
> > term, something which is unacceptable if we need to call it 10,000,000
> > times
> > each second may be perfectly acceptable if we "only" need to call it 
> 10,000
> > times each second (per core).
> >
> > Returning to the topic of this discussion, if read_exactly() is 
> something
> > we
> > expect to fail a million times per second, it would indeed be a 
> problem to
> > make it fail using an exception. But if a read_exactly() failure 
> *always*
> > leads to failure of an entire request, complete with a lot of overheads
> > related to such failure (maybe logging, a lot of wasted work we have 
> done,
> > etc.), then maybe the exception would be the least of our problems.
> >
>
> Perhaps, but now we need to have this reasoning every time an error can
> happen. Isn't that a sign that exceptions are simply not a good choice for
> our needs?
>
I think anyone who has written code _not_ using exceptions will testify 
to how using them, no matter how slow, is always better. :-/

But the same reasoning of "what do you return" is just as valid in for 
example error + error code cases. It is just the overhead associated 
that differs. Rule of thumb should always be that a valid outcome is not 
an exception. If something can except, and the potential overhead of 
said exception is intolerable in some case, maybe allow calling code to 
prevent it, by for example checking a precondition, etc.

Saying exceptions are a bad error model because it is a hard thing 
sometimes to decide what is the API semantics seems like throwing babies 
with tub water.

**Comment by pdziepak** [comment]
On Wed, 20 Feb 2019 at 11:48, Calle Wilund <notifications@github.com> wrote:

>
> Den 2019-02-20 kl. 12:30, skrev Paweł Dziepak:
> > On Wed, 20 Feb 2019 at 10:59, nyh <notifications@github.com> wrote:
> >
> > > On Tue, Feb 19, 2019 at 5:03 PM Paweł Dziepak <
> notifications@github.com>
> > > wrote:
> > >
> > > > On Tue, 19 Feb 2019 at 08:57, nyh <notifications@github.com> wrote:
> > > > > So you're saying that if we allow one exception per request,
> > this will
> > > > > constitute a DoS?
> > > >
> > > >
> > > > I can't tell for sure that depends on many things (how many times the
> > > > exception is going to be rethrown by its handlers?)
> > >
> > >
> > > We already try *not* to rethrow exceptions. In the past a lot of
> > > future-handling code incorrectly did that, but it no longer does,
> > and the
> > > exception_ptr is just passed unchanged. I believe that in most cases in
> > > Scylla, the exception propagates all the way to stopping the current
> > > request (when it's part of a request), and only there it is caught
> once.
> > > If that's not the case, we should improve it.
> > >
> >
> > So we acknowledge the problem with the exceptions, but still try to make
> > them work and in effect make everything more difficult for ourselves.
> > Wouldn't it be better if we had an error propagation mechanism that isn't
> > as easy to use incorrectly?
> >
> Isn't the core of that problem that you have two distint modes of error
> propagations dictated by the continuation model? It seems to me that
> solving the awkward `.then(...)` semantics (coroutines?) would in
> general be more helpful to guarantee that code does not miss handling
> errors, given that the track record is generally we've failed at
> handling both synchronous and async exception cases in code, and end up
> wrapping stuff in useless "then" calls just to get uniform handling.
>
> And btw, even with sutters proposal, the same problem remains with
> seastar code.
>

While this is also an issue I don't think it is the main problem. Consider
the function:

```c++
void do_something();
```

Just from the declaration it is impossible to say anything about the
exceptions it throws and the ways in which it may fail. If the programmer
needs to care about this they have to read the implementation and we end up
with the code that depends on the implementation details instead of public
interfaces and contracts.


>
> Also, since I don't think anyone wants to drop stl or even stl interop,
> moving to yet another home-invented error mechanism sounds at best
> futile and perilous.
>

I'd expect most of the recoverable errors not to originate from the
standard library but from seastar (network and storage).
`seastar::expected<T>` is going to interoperate with exceptions to allow
gradual transition so I don't really see this as a valid arguments to stick
with dynamic exceptions.


>
> >
> > >
> > >
> > >
> > > > , but in a server
> > > > environment there is no such thing as "this request failed so we
> don't
> > > care
> > > > about its performance".
> > >
> > >
> > > That is not what I said. It's just that if exceptions no longer have
> > global
> > > locks
> > > it's not clear that their performance is that terrible. Also
> > "terrible" is
> > > a relative
> > > term, something which is unacceptable if we need to call it 10,000,000
> > > times
> > > each second may be perfectly acceptable if we "only" need to call it
> > 10,000
> > > times each second (per core).
> > >
> > > Returning to the topic of this discussion, if read_exactly() is
> > something
> > > we
> > > expect to fail a million times per second, it would indeed be a
> > problem to
> > > make it fail using an exception. But if a read_exactly() failure
> > *always*
> > > leads to failure of an entire request, complete with a lot of overheads
> > > related to such failure (maybe logging, a lot of wasted work we have
> > done,
> > > etc.), then maybe the exception would be the least of our problems.
> > >
> >
> > Perhaps, but now we need to have this reasoning every time an error can
> > happen. Isn't that a sign that exceptions are simply not a good choice
> for
> > our needs?
> >
> I think anyone who has written code _not_ using exceptions will testify
> to how using them, no matter how slow, is always better. :-/
>
> But the same reasoning of "what do you return" is just as valid in for
> example error + error code cases. It is just the overhead associated
> that differs. Rule of thumb should always be that a valid outcome is not
> an exception. If something can except, and the potential overhead of
> said exception is intolerable in some case, maybe allow calling code to
> prevent it, by for example checking a precondition, etc.
>
> Saying exceptions are a bad error model because it is a hard thing
> sometimes to decide what is the API semantics seems like throwing babies
> with tub water.
>

It is true, valid outcome is not an exception, but an error may be a valid
outcome (e.g. attempting to open a non-existing file). What we lack is a
unified way of dealing with that and, as a result, we've ended up with some
functions throwing exceptions on all errors and the others, like
`read_exactly` returning a "special value" to signal failure. I think we
really should have a more consistent approach to this, which calls for
something along the lines of `std::expected`.


>

**Comment by elcallio** [comment]
Den 2019-02-20 kl. 16:14, skrev Paweł Dziepak:
> On Wed, 20 Feb 2019 at 11:48, Calle Wilund <notifications@github.com> 
> wrote:
>
> >
> > Den 2019-02-20 kl. 12:30, skrev Paweł Dziepak:
> > > On Wed, 20 Feb 2019 at 10:59, nyh <notifications@github.com> wrote:
> > >
> > > > On Tue, Feb 19, 2019 at 5:03 PM Paweł Dziepak <
> > notifications@github.com>
> > > > wrote:
> > > >
> > > > > On Tue, 19 Feb 2019 at 08:57, nyh <notifications@github.com> 
> wrote:
> > > > > > So you're saying that if we allow one exception per request,
> > > this will
> > > > > > constitute a DoS?
> > > > >
> > > > >
> > > > > I can't tell for sure that depends on many things (how many 
> times the
> > > > > exception is going to be rethrown by its handlers?)
> > > >
> > > >
> > > > We already try *not* to rethrow exceptions. In the past a lot of
> > > > future-handling code incorrectly did that, but it no longer does,
> > > and the
> > > > exception_ptr is just passed unchanged. I believe that in most 
> cases in
> > > > Scylla, the exception propagates all the way to stopping the current
> > > > request (when it's part of a request), and only there it is caught
> > once.
> > > > If that's not the case, we should improve it.
> > > >
> > >
> > > So we acknowledge the problem with the exceptions, but still try 
> to make
> > > them work and in effect make everything more difficult for ourselves.
> > > Wouldn't it be better if we had an error propagation mechanism 
> that isn't
> > > as easy to use incorrectly?
> > >
> > Isn't the core of that problem that you have two distint modes of error
> > propagations dictated by the continuation model? It seems to me that
> > solving the awkward `.then(...)` semantics (coroutines?) would in
> > general be more helpful to guarantee that code does not miss handling
> > errors, given that the track record is generally we've failed at
> > handling both synchronous and async exception cases in code, and end up
> > wrapping stuff in useless "then" calls just to get uniform handling.
> >
> > And btw, even with sutters proposal, the same problem remains with
> > seastar code.
> >
>
> While this is also an issue I don't think it is the main problem. Consider
> the function:
>
> ```c++
> void do_something();
> ```
>
> Just from the declaration it is impossible to say anything about the
> exceptions it throws and the ways in which it may fail. If the programmer
> needs to care about this they have to read the implementation and we 
> end up
> with the code that depends on the implementation details instead of public
> interfaces and contracts.
>
>
This is true, but std::expected does not really say anything about 
_which_ errors might be in the non-expected case, just that there might 
be one.

In c++, anything without noexcept similarly says "there might be 
errors". We should perhaps learn to use noexcept better.

> >
> > Also, since I don't think anyone wants to drop stl or even stl interop,
> > moving to yet another home-invented error mechanism sounds at best
> > futile and perilous.
> >
>
> I'd expect most of the recoverable errors not to originate from the
> standard library but from seastar (network and storage).
> `seastar::expected<T>` is going to interoperate with exceptions to allow
> gradual transition so I don't really see this as a valid arguments to 
> stick
> with dynamic exceptions.
>
You cannot catch a std::unexpected as I understand it, so you at least 
have two code paths for different error conditions. Maybe compilers wil 
provide glue-code here, but I have to say I really loathe the 
std::expected error handling model. It is imho a step backwards to 
if-else conditionals.


>
> >
> > >
> > > >
> > > >
> > > >
> > > > > , but in a server
> > > > > environment there is no such thing as "this request failed so we
> > don't
> > > > care
> > > > > about its performance".
> > > >
> > > >
> > > > That is not what I said. It's just that if exceptions no longer have
> > > global
> > > > locks
> > > > it's not clear that their performance is that terrible. Also
> > > "terrible" is
> > > > a relative
> > > > term, something which is unacceptable if we need to call it 
> 10,000,000
> > > > times
> > > > each second may be perfectly acceptable if we "only" need to call it
> > > 10,000
> > > > times each second (per core).
> > > >
> > > > Returning to the topic of this discussion, if read_exactly() is
> > > something
> > > > we
> > > > expect to fail a million times per second, it would indeed be a
> > > problem to
> > > > make it fail using an exception. But if a read_exactly() failure
> > > *always*
> > > > leads to failure of an entire request, complete with a lot of 
> overheads
> > > > related to such failure (maybe logging, a lot of wasted work we have
> > > done,
> > > > etc.), then maybe the exception would be the least of our problems.
> > > >
> > >
> > > Perhaps, but now we need to have this reasoning every time an 
> error can
> > > happen. Isn't that a sign that exceptions are simply not a good choice
> > for
> > > our needs?
> > >
> > I think anyone who has written code _not_ using exceptions will testify
> > to how using them, no matter how slow, is always better. :-/
> >
> > But the same reasoning of "what do you return" is just as valid in for
> > example error + error code cases. It is just the overhead associated
> > that differs. Rule of thumb should always be that a valid outcome is not
> > an exception. If something can except, and the potential overhead of
> > said exception is intolerable in some case, maybe allow calling code to
> > prevent it, by for example checking a precondition, etc.
> >
> > Saying exceptions are a bad error model because it is a hard thing
> > sometimes to decide what is the API semantics seems like throwing babies
> > with tub water.
> >
>
> It is true, valid outcome is not an exception, but an error may be a valid
> outcome (e.g. attempting to open a non-existing file). What we lack is a
> unified way of dealing with that and, as a result, we've ended up with 
> some
> functions throwing exceptions on all errors and the others, like
> `read_exactly` returning a "special value" to signal failure. I think we
> really should have a more consistent approach to this, which calls for
> something along the lines of `std::expected`.
>
>
No, the error is _not_ a valid outcome for opening a file. That it the 
whole point. (Assuming something link a open_file obejct).
You throw an exception because you cannot satisfy the conditionthat the 
object is in fact an open file.

The same should apply to API:s. In the original discussion of 
'read_exactly', it is debatable of course, but I would side on that the 
API should indeed throw given the name. But otoh, you might want a 
try_read_exactly that promises to read X bytes iff possible (i.e. not 
error -> exception or EOF -> truncated). However, in the latter case, 
the short read is _not_ an error, in fact it is one of two valid 
outcomes (like a normal ::read), so having a std::expected error is 
equally wrong. It is just a more flexible call that the user needs to 
bounds-check after (result.size()).
