### ISSUE TITLE
CQL Alter Table

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#428]
It would be good if we can do it in iterations - that is first add support for adding columns to tables and only after that add support for renaming, removing columns

**Comment by penberg** [comment]
There's very little similarity between ``ALTER KEYSPACE`` and ``ALTER TABLE``  so can you please split this Github issue into two?

Completely agreed on the incremental implementation.

**Comment by lethalman** [comment]
I wonder, does it make sense to release 1.0 announced as "production ready" if it doesn't support altering the schema? Like I have scylla in production and cannot add a column to a table. It's far from being production ready.

**Comment by lethalman** [comment]
I'm looking at http://www.scylladb.com/technology/status/#cassandra-compatibility . It's not clear whether this issue will be resolved for 1.0, or for 1.1.

**Comment by tzach** [comment]
Thanks @lethalman  good input.
ALTER TABLE is indeed an important feature and It is already merged as an experimental feature [1]. However, since we are not 100% it we will be fully tested by 1.0, we currently plan to leave it for 1.1
For 1.0, we are very much focused on stability.
If you like living on the edge, and help us on the process, you are welcome to try it out. 

[1] https://groups.google.com/forum/#!searchin/scylladb-dev/flag%7Csort:date/scylladb-dev/iwcOdkTXgrs/oZrO52-SEgAJ

**Comment by tgrabiec** [comment]
The feature is in since [0.16](http://www.scylladb.com/2016/01/19/release-016/) and can be enabled by passing `--experimental` command line option. 

Known issues:
#877 "Compaction strategy changes via ALTER TABLE have no effect until node restart"

**Comment by penberg** [comment]
``ALTER TABLE`` is no longer marked as experimental as of commit https://github.com/scylladb/scylla/commit/6a3cf4ac41e17fe164a0cfd92a5fa88a005fea3f.

**Comment by tzach** [comment]
@slivne @penberg can we close this?

**Comment by penberg** [comment]
@tzach Yes, we can.
