### ISSUE TITLE
update member_of without check if target role exists

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4280]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20190122.dbc1894bd
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

In update statement, set role to non-existing role `jim_not_exist`, update will success without error.
But `list roles`, `list role of jim_not_exist`, create/drop jim_not_exist are all failed for `Unexpected empty value`.

I think we should check if `target role` exists in updating (member_of) statement.

```
cassandra@cqlsh> CREATE ROLE jim WITH LOGIN = true;
cassandra@cqlsh> list roles;

 role      | super | login | options
-----------+-------+-------+---------
 cassandra |  True |  True |        {}
       jim | False |  True |        {}

(2 rows)
cassandra@cqlsh> UPDATE system_auth.roles SET member_of = {'jim'} where role = 'jim_not_exist' ;
cassandra@cqlsh> list roles;
ServerError: Unexpected empty value
cassandra@cqlsh> list roles of jim;

 role | super | login | options
------+-------+-------+---------
  jim | False |  True |        {}

(1 rows)
cassandra@cqlsh> drop role jim_not_existing;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Role jim_not_existing doesn't exist."
cassandra@cqlsh> drop role jim_not_exist;
ServerError: Unexpected empty value
cassandra@cqlsh> CREATE ROLE jim_not_exist WITH LOGIN = true;
ServerError: Unexpected empty value
cassandra@cqlsh> 
```

@hakuch @slivne @roydahan

**Comment by jwnx** [comment]
We have more than one problem. I can create a role both by using `create role` and using `UPDATE system_auth.roles`:

```
cassandra@cqlsh> create role jim with login = true;                                                                                       
cassandra@cqlsh> list roles;                                                                                                              
                                                                                        
 role      | super | login | options                                                               
-----------+-------+-------+---------                                                                       
 cassandra |  True |  True |        {}                                                  
       jim | False |  True |        {}                                                                                    
                                                                                                   
(2 rows)                                                                                            
cassandra@cqlsh> UPDATE system_auth.roles SET member_of = {'jim'} where role = 'jim_not_exist' ;            
cassandra@cqlsh> select * from system_auth.roles;                                                                                                                   
                                                                                                                                
 role          | can_login | is_superuser | member_of | salted_hash
---------------+-----------+--------------+-----------+-------------
     cassandra |      True |         True |      null | $6$Za...
           jim |      True |        False |      null |     null
 jim_not_exist |      null |         null |   {'jim'} |     null                    
```

Then, errors arise when we try to use `role` operations and `jim_not_exist`. 

```
cassandra@cqlsh> list roles;
ServerError: Unexpected empty value
cassandra@cqlsh> drop role jim_not_exist;
ServerError: marshaling error: Cannot deserialize boolean, size mismatch (9)
cassandra@cqlsh> create role jim_not_exist with login = true;
ServerError: Unexpected empty value
```

Creating a role using `create role` is expected to work. We also allow to directly update `system_auth.roles`, so being able to create a role there is also an expected behavior. We see unexpected behavior when interacting with `list roles`, `drop roles` and `create roles` (and maybe more?), because they didn't expect a role to be created outside `create role` and therefore, return us errors. These errors happen because `can_login` and `is_superuser` are *null*. If we fix them, it works like a charm.

```
cassandra@cqlsh> UPDATE system_auth.roles SET can_login=False where role = 'jim_not_exist';
cassandra@cqlsh> UPDATE system_auth.roles SET is_superuser=False where role = 'jim_not_exist';
cassandra@cqlsh> select * from system_auth.roles;

 role          | can_login | is_superuser | member_of             | salted_hash
---------------+-----------+--------------+-----------------------+-----------
     cassandra |      True |         True |                  null | $6$Za7w...
           jim |      True |        False | {'barbara_not_exist'} |       null
 jim_not_exist |     False |        False |               {'jim'} |       null

(3 rows)
cassandra@cqlsh> list roles;

 role          | super | login | options
---------------+-------+-------+---------
     cassandra |  True |  True |        {}
           jim | False |  True |        {}
 jim_not_exist | False | False |        {}


```

So, in order to fix this, we can fix `<operation> roles` to work knowing that a role can be created outside its scope, or we can intercept `update system_auth.roles` to, if creating a role, making sure that all fields are set (`can_login` and `is_superuser` being the culprits here). One of the two would fix the errors described.

Another thing is checking if a target role exists. This is tricky because updating `member_of` through `GRANT barbara_not_exist to jim;` already does a check before updating -- which is expected, since `grant` is a `role` operation.

```
cassandra@cqlsh> grant barbara_not_exist to jim;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Role barbara_not_exist doesn't exist."

```

But checking role existence for `update system.auth` would require us to interfere with updates and inserts. When I run 

```
UPDATE system_auth.roles SET member_of = {'jim'} where role = 'jim_not_exist';
```

I'm doing an insert so, technically, `jim_not_exist` does exist. We can check if a role exists before issuing the insert by intercepting the update statement, checking if its a update on `system_auth.roles` and then read it to see if the role is there. This all seems overly specific for `system_auth` and I wonder if its the best approach.

I propose fixing `role` cql operations to consider roles created outside its scope instead of checking if a role exists before issuing inserts on `system_auth.roles`.

**Comment by avikivity** [comment]
Aged out.
