### ISSUE TITLE
Will scylla have unique index in future / in roadmap?

### ISSUE THREAD

**Issue by hiqbn** [scylladb/scylla#4307]
Will scylla ever have unique index in the near future / in roadmap? I would like to have secondary indexes as unique.

**Comment by tzach** [comment]
Can you please elaborate on what do you mean by unique sec index here? (example?) Thanks

**Comment by slivne** [comment]
@hiqbn - please provide more info and then we will reopen as an enhancement

**Comment by hiqbn** [comment]
create unique index if not exist

https://docs.yugabyte.com/latest/api/ysql/commands/ddl_create_index/

**Comment by nyh** [comment]
A "unique index" is a column to be indexed (as in secondary index) which forbids entering another row into the base table with the same value for the indexed column as already appears in another row.

However, this concept doesn't work well with Scylla's  existing consistency model. If two clients write to two different rows concurrently, if both writes write the same value into the unique-indexed column, someone would need to serialize these writes and allow one of them to succeed but the other one to fail. We don't have such a mechanism. The base writes would need to wait until the index write succeeds, and if it fails (because the same value is already in use), fail the base write. Moreover the index write will need to be serialized across replicas, so only one of the write succeeds (on all replicas) and the other one fails (on all replicas).

**Comment by bhalevy** [comment]
Once we have LWT (Light Weight Transactions) we should have the facilities to implement this.
