### ISSUE TITLE
High write latency time

### ISSUE THREAD

**Issue by fggarcia** [scylladb/scylla#4354]
*Installation details*
Scylla version (or git commit hash): 3.0.4
Cluster size: 11 (8 dc1 - 3 dc2)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04.4 LTS 

Hi

I have high write latency time (4 seconds) since i upgrade to 3.0.4 from 3.0.2
Read latency is ok.

I also see that I have "throttled base writes" but i don't have any materialized views.

![image](https://user-images.githubusercontent.com/1306596/54802360-aff67900-4c49-11e9-986b-0ba9078af97d.png)
![image](https://user-images.githubusercontent.com/1306596/54802379-c7356680-4c49-11e9-8d5c-0d8de27724ca.png)
![image](https://user-images.githubusercontent.com/1306596/54802391-d3b9bf00-4c49-11e9-86c2-d3ae5cb5ea74.png)
![image](https://user-images.githubusercontent.com/1306596/54802425-fa77f580-4c49-11e9-9113-9d31d1f28a38.png)
![image](https://user-images.githubusercontent.com/1306596/54802451-1aa7b480-4c4a-11e9-9f9b-0b31263a68cf.png)
![image](https://user-images.githubusercontent.com/1306596/54802458-26937680-4c4a-11e9-8599-f1653f67cc1d.png)

**Comment by nyh** [comment]
This is caused by of https://github.com/scylladb/scylla/issues/4351.
@duarten sent a patch for it yesterday to the mailing list - titled "service/storage_proxy: Don't consider view hints for MV backpressure".
The bug is that the materialized-view backpressure code erroneously considers the normal hinted-handoff files to be backlog in materialized-view processing and starts to deliberately slow down requests, even those that have no materialized views at all.

**Comment by gleb-cloudius** [comment]
Probably a dup of #4351

--
			Gleb.

**Comment by veramine** [comment]
@nyh Do you have handy the checkin or (more importantly) the release that first introduced this behavior?  Has it counted since the first view back pressure functionality, or more recently?

**Comment by nyh** [comment]
The bug exists since 3.0.4, it doesn't exist in 3.0.3. The commit starting it was da54d0fc7deceb752475770b2a03bf39b2838036.

Ironically, even though 3.0 added materialized-view flow control, a typo (!) in the code zeroed the amount of flow control, so it had absolutely no effect. The aforementioned patch fixed that typo, but then bugs in the MV flow control come into full effect. The bug in question was considering hinted-handoff as a sign for a view-update backload, even in cases where there weren't any materialized views...

**Comment by veramine** [comment]
Very helpful, thank you!

**Comment by fggarcia** [comment]
Thank you. But I don't understand why the bug apply to my case, because I don't have any materialize view in the DB.

**Comment by nyh** [comment]
@fggarcia I would think it should, but one user reported that it didn't. I am guessing that during the upgrade processes, when the upgraded node was down for a while, other nodes collected hinted-handoff for it. Disabling hinted-handoff at that point probably doesn't remove the hinted-handoff files that were already collected...

**Comment by duarten** [comment]
Duplicates #4351.

**Comment by fggarcia** [comment]
Hi @duarten . 

Maybe you can explain to me why the bug affects me?
I do not have materialized views, nor do I have any dropped node. I do not understand why these "hints" are being generated (where i can see hints metrics?)

The number of writes are insignificant enough to have so much latency.

**Comment by duarten** [comment]
The bug is that the MV backpressure mechanism gets activated despite there being no views or indexes. This happens because of hints being generated. Hints are generated when a node is unavailable, to be delivered later and heal data inconsistencies without resorting to repair.

**Comment by veramine** [comment]
@duarten Does a full repair delete these hints?  Or are the files in /var/lib/scylla/hints safe to delete?  It seems like @fggarcia is looking for a way out of his current stuck situation..

**Comment by duarten** [comment]
No, hints are only deleted when they are delivered. I don't know what hint-related metrics we expose that could help figure out what's going on (cc @vladzcloudius). 

Of course, it's always possible to see the contents of the /hints directory of the instances. If these are empty (because the update has been completed), then there could be another issue, but it would also have been solved by the fix to #4351.

**Comment by fggarcia** [comment]
@veramine @duarten I understand that. But I don't know why i have these hints if i don't have any node unavailable. That is my question.


![image](https://user-images.githubusercontent.com/1306596/54843489-2e3b3580-4cb3-11e9-9462-5dd3d87a15c1.png)
![image](https://user-images.githubusercontent.com/1306596/54843530-44e18c80-4cb3-11e9-9270-69a6941e2c44.png)

**Comment by veramine** [comment]
@fggarcia do see any files in the subdirectories of /var/lib/scylla/hints ?

**Comment by duarten** [comment]
Hints can also be stored as a consequence of the write having failed for some node, including timeouts.

**Comment by fggarcia** [comment]
@veramine Yes I see files in subdirectories

**Comment by veramine** [comment]
@fggarcia what @duarten and @nyh are saying is that there is a bug in v3.0.4 that is accounting those "hints" as backlog to be processed.  That fake backlog is resulting in back pressure that introduces an artificial delay of max one second to give scylla a chance to "catch up".

**Comment by fggarcia** [comment]
@veramine it's okey. I do not consider it to be a great amount of hints I have, so that it generates so much backpressue time. 6 seconds That's why I ask: P

**Comment by vladzcloudius** [comment]
@fggarcia Hi. We have hints metrics - they are simply not exposed on our 3.0 dashboards yet. I'll open a github issue with a request to add some.

Right now you'll have to do that yourself. Got to the Prometheus console and look metrics up by typing "hint". There are two groups of hints: for views and for regular queries - you'll see a clear difference in names.

In order to see hints for views that were stored for instance you'd need to use the following Grafana "query": 
```
sum(irate(scylla_hints_for_views_manager_written{instance=~"[[node]]", shard=~"[[shard]]"}[30s])) by ([[by]])
```

As for deleting hints files: once you stopped scylla you can safely delete any hint files.

**Comment by fggarcia** [comment]
Hi @vladzcloudius, first thanks for query.

Yes, after stop scylla server, i delete hints folder and it resolve the problem.

![image](https://user-images.githubusercontent.com/1306596/54937216-bfecb200-4f02-11e9-86ce-edc792e3d8ce.png)
