### ISSUE TITLE
congrats for 5000 stars!. Should I switch from MySql?

### ISSUE THREAD

**Issue by edugrip** [scylladb/scylla#4429]
This is Scylla's bug tracker,.................

_I understand but can't resist to congratulate on 5000 stars to such a great Database and  a great and responsive team._
- [] I have read the disclaimer above, and I am reporting ** Awesome functioning** in Scylla.

**Comment by edugrip** [comment]
I don't think I need to maintain ACID that hard. But 100% CPU usage is sometimes an issue.  I am not sure if many people are considering it instead of mysql,  Is the documentation available? Do I even need such a throughput with expected around. 30,000 users for an application ?

**Comment by glommer** [comment]
Thanks for the kind words! (although I am still closing this, because this is the Scylla bug tracker, and you have read the disclaimer above... ;-) )

There are advantages and disadvantages of switching to Scylla from MySQL in your case. For one, eventual consistency do complicate architectures. While you may not need ACID, it will certainly shield you from common mistakes.

However the biggest advantage of switching is that you wouldn't have to re-architecture your application should it ever have more than 30,000 users. The same goes for having a more complex and rich model of what those users are doing (which will generate more data) and/or adding more functionality operating under the same data.

I would like to invite you to show up in our users slack channel and continue this conversation.

Have a great day!
