### ISSUE TITLE
Dropping a column from a table with materialized views could be allowed in some cases

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#4448]
Right now we unconditionally forbid dropping a column from a table if it has materialized views. Dropping a column may be complicated (or impossible), especially for columns that are selected in a view, or for ones that may determine view row's liveness.

There are cases, however, when dropping a column does not imply any problems, e.g. if a column is not selected at all and is not relevant for row liveness (a.k.a. is not view virtual). For these cases, we could allow dropping a base column.

**Comment by nyh** [comment]
I agree, and I think it's very easy to fix (before allowing to delete a base-table column, verify that it doesn't exist in any of the base's views - where "exists" includes as a virtual column). 

By the way, this is not a regression from Cassandra, because Cassandra too, since version 3.11, does not allow to drop base columns even if not selected in any view - see https://github.com/apache/cassandra/commit/e6fb8302848bc43888b0a742a9b0abce09872c45

**Comment by nyh** [comment]
A good reason to implement the relaxed test is to allow dropping a column from a table with a **secondary index** (when the index is not on a primary key and the column to drop is not the indexed one). In Cassandra, this was allowed and because of our MV-based implementation, we forbid this.
A user reported this issue in a question in stackoverflow:
https://stackoverflow.com/questions/55757273/error-while-dropping-column-from-a-table-with-secondary-index-scylladb/55776490

**Comment by tskweres** [comment]
If I have my DB configured to 'drop' in dev, I'm still getting:

```
Error while dropping materialized view on DB Table -> ResponseError: Cannot use DROP MATERIALIZED VIEW on Index +3087ms
apollo.model.tablecreation.matviewdrop: Error while dropping mater
```
How can I drop the DB & start over as I'm fleshing out the models?

**Comment by psarna** [comment]
@tskweres see https://github.com/scylladb/scylla/issues/3357#issuecomment-602159685
