### ISSUE TITLE
Schema disagreement until whole cluster is upgraded due to new view_virtual_columns table

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4457]
Scylla version (or git commit hash): master (7c874057f51762beaa95fb840b1f6b672a1adb98)

After 7c874057f51762beaa95fb840b1f6b672a1adb98, schema sync includes `system_schema.view_virtual_columns` in the schema digest. Old nodes don't know about this table and will not include it in the digest calculation. As a result, there will be schema disagreement until the whole cluster is upgraded.

**Comment by tgrabiec** [comment]
The commit 7c87405 also indirectly changed the order of schema tables during hash calculation (index table should be taken after all other tables). This shows up when there is an index created and any of {user defined type, function, or aggregate}.

**Comment by nyh** [comment]
Wow. Thanks for noticing this and fixing it.

It's good that you added the comment "This list must be kept backwards-compatible because it's used for schema digest calculation", but I'm not sure if the next person to touch this code will understand how to follow this advice in practice, and what exactly it takes for the list to be "backwards compatible". By the way, what happens if we ever want to delete one of the schema tables? We would be need to maintain the deleted schema table until the entire cluster is upgraded, and only then delete it?

I wonder if we couldn't make our lives easier by saying that during a rolling upgrade schemas can't be changed, so schema agreement is not attempted (so like in this bug, we will have schema disagreement, but it will be ignored). This will mean the partially upgraded cluster can be used, but tables cannot be created or altered. Would this make sense, or it's better to do what you did and support the schema agreement through the upgrade?

**Comment by tgrabiec** [comment]
@nyh The idea to prevent schema changes during upgrade is discussed here: https://github.com/scylladb/scylla/issues/4248
