### ISSUE TITLE
scylla_setup: use default value for disk selection

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4514]
*Installation details*
Scylla version (or git commit hash): 3.0

In scylla_setup the current RAID0, XFS parts look like:

```
Are you sure you want to setup RAID0 and XFS?
If you choose Yes, the selected drive will be reformated, erasing all existing data in the process.
[YES/no]
Please select unmounted disks from the following list: ['/dev/nvme0n1']
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []
> /dev/nvme0n1
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: ['/dev/nvme0n1']
> done
```

In the case above, and often, there is only one unmounted disk. In this case, it can be the default for the install:
```
Please select unmounted disks from the following list: ['/dev/nvme0n1']
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: [/dev/nvme0n1]
> /dev/nvme0n1
```

**Comment by syuu1228** [comment]
I guess it could be dangerous for some users who didn't read interactive message carefully, no?

**Comment by tzach** [comment]
Good point. 
AFAIK, the list only includes unmounted drives. If this is the case, is it still dangerous?

**Comment by syuu1228** [comment]
I think we are not able to know how user uses partitions / disks.
It's all depends how user uses the machine, they may have partitions / disks unmounted, it may includes important data.
Maybe they unmount backup disk when it doesn't using.
Or maybe unmounted partition is UEFI system partition (On distribution's default setting it mounts UEFI system partition on /boot/efi, but it doesn't have to be mounted since only used for booting).

**Comment by tzach** [comment]
Thanks @syuu1228 closing
