### ISSUE TITLE
allow filtering queries with aggregation that page returns intermediate aggregated results, not the full one

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4540]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Our dear and esteemed friend @ultrabug hit today what he thought was Ultra Bug, but upon closer investigation seemed like just a variation of #4156 

However, what makes his case unique is that he is doing aggregations:

```
scylla@cqlsh:test> select sum(ultra_column) as volume from ultrabug_table where ultra_column = 'some word in french' allow filtering;

 volume
--------
    476

---MORE---
 volume
--------
    496

---MORE---
 volume
--------
    496

---MORE---
 volume
--------
    480

---MORE---
 volume
--------
    488

---MORE---
 volume
--------
    496
```

The query works just fine if we disable paging, but we are both in agreement that since this is an aggregation, the sane user behavior would be that the aggregation would be done in the coordinator. In fact, since `select count(*) from table` seems to always time out, am I wrong to believe that in the case of normal queries, the aggregation happens in the coordinator already?

**Comment by nyh** [comment]
I wonder if this is related to issue #4127, which has a similar problem for `count(*)`?

**Comment by avikivity** [comment]
What's the bug? are the results incorrect?

**Comment by glommer** [comment]
The bug is that we'd both expect that when an aggregation is used, the final aggregation is returned, and not the result of the aggregation for every page.

Are our expectations wrong? Why ?

**Comment by avikivity** [comment]
Certainly a query with aggregation and without grouping should return a single result. It would be nice to state this explicitly in the report.

**Comment by glommer** [comment]
I changed the title.

**Comment by psarna** [comment]
Which Scylla version is that? I wrote a test for it on master and it passes seamlessly. Maybe it's a version pre- acf4eadf88ccd0bebfa22d05d162f82485ed6491, which, by accident, solved that problem as well?

**Comment by ultrabug** [comment]
3.0.6 @psarna

**Comment by psarna** [comment]
I just double checked on `3.0` and the test I added passes fine as well... which means the issue might still be here and it's more subtle. I'll investigate.

**Comment by psarna** [comment]
Alright, I figured it out. It's actually all about **indexing** + aggregation + paging, and the problem is as follows:
1. In the original Scylla implementation of secondary indexes, paging was not supported.
2. Later, paging support was added. It was a little bit more complicated than paging regular queries, because the paging state from the indexing query needs to be internally reforged into the paging state of the base table in order to keep fetching proper results.
3. Unfortunately, the matter of aggregation queries was not taken into account when implementing 2.

The way regular aggregation works inside Scylla is that the requests are still internally paged (in order to avoid OOM) and aggregated on coordinator side. Such a mechanism is not yet present in SI.

One simple workaround is to disable paging for aggregation queries that use indexing, but it can be detrimental for huge result sets. The other is to gather partial results and combine them client-side, but that involves action from the client and assumes that the aggregation is commutative, which is true for *sum* and *count*, but less for *avg*.

The proper solution is to implement internal paging for aggregation indexed queries, based on the existing code for regular queries.

@eliransin @slivne let me know what's the priority of this.  If it's not super high, it might be a decent n00b task to get acquainted with CQL layer.

**Comment by nyh** [comment]
If this bug also involves the secondary index, then issue #4127 (which we were never able to reproduce) is most likely a duplicate.

**Comment by avikivity** [comment]
@psarna please prepare backports against 3.1 and 3.0

( tried and failed, see my next-3.1-4540-backport branch)

**Comment by psarna** [comment]
3.1: https://github.com/psarna/scylla/commits/add_proper_aggregation_for_paged_indexing_for_3.1

**Comment by avikivity** [comment]
Queued for 3.1.

**Comment by psarna** [comment]
I also did 3.0 right after, but forgot to post it... here it is: https://github.com/psarna/scylla/tree/add_proper_aggregation_for_paged_indexing_for_3.0

**Comment by avikivity** [comment]
Queued for 3.0, 3.1
