### ISSUE TITLE
view_builder bookkeeping errors are actually warnings and aren't unique.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4600]
Seen in [dtest-release/158/artifact/logs-release.2/1561433162725_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/node2.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/158/artifact/logs-release.2/1561433162725_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/node2.log):
```
INFO  2019-06-25 03:23:42,099 [shard 0] init - stopping view builder
INFO  2019-06-25 03:23:42,099 [shard 0] view - Stopping view builder
INFO  2019-06-25 03:23:42,099 [shard 1] view - Stopping view builder
ERROR 2019-06-25 03:23:42,099 [shard 0] view - Failed to update materialized view bookkeeping (seastar::no_sharded_instance_exception (sharded instance does not exists)), continuing anyway.
```

I'm not sure if this came from `view_builder::execute` or `view_builder::calculate_shard_build_step`.

a. I think we better uniquify these two messages so we can distinguish between them.
b. Since we're continuing anyway, we better demote the log severity level from error to warn, this will also not fail the dtest.

**Comment by slivne** [comment]
@nyh / @psarna  - whats you take on this ?

**Comment by psarna** [comment]
I'll take a closer look tomorrow, but it does look like a (benign) error - wrong deinitialization order in our code - bookkeeping shouldn't be allowed to be updated once we already stopped the builder. So, it's probably better in the long term to fix it, instead of lowering its priority (although this one is indeed harmless).

**Comment by psarna** [comment]
Ok, I read the code more closely and here are my conclusions:
1. For sure, we need distinguishable messages in `view_builder::execute` and `view_builder.calculate_shard_build_step`. It's theoretically a separate issue, but it's so minor that I think it can safely stay here.
2. We already have an `abort_source`-based checking for termination in the view builder, but since the bookkeeping is waited for inside a `when_all` primitive, it might be the case that some of the ops will try to execute even after we stop the builder service. One of the solutions: store the information that we have pending bookkeeping and wait for them to finish before stopping the builder. The other one: what @bhalevy suggested, downgrade the logging level to a warning. I was initially against it, but after getting familiar with the code I think it's reasonable. In case of shutting down, it's better to kill and warn about pending bookkeeping for views than to try waiting for it. The worst that could happen is having to redo the last view building step that was executed during the shutdown, but that's exactly how it works now and it's not a high cost in my opinion, as shutting down is considered rare.

It's a n00b task, so we can mark it as such and give away to newcomers perhaps?

**Comment by bhalevy** [comment]
Cc @eliransin

**Comment by avikivity** [comment]
Minor, not backporting.
