### ISSUE TITLE
differenct cluster nodes vary dramatically in read latency

### ISSUE THREAD

**Issue by zgbgx** [scylladb/scylla#4608]
two nodes in cluster，bu one node mean  read latecy   is 2.37ms,another noe mean write latency is 15.48ms
two node has the same hardwares,and both use scylla_setup  init.

read latency compare
![readtency](http://tva1.sinaimg.cn/large/0060lm7Tly1g4etuqcc36j31v40u0gwl.jpg)
cpu compare
![cpu](http://tva1.sinaimg.cn/large/0060lm7Tly1g4etqsmy5jj31aa0u04bf.jpg)
disk compare
![disk](http://tva1.sinaimg.cn/large/0060lm7Tly1g4ettefvezj31xu0u0dpb.jpg)
ioqueue compare
![disk](http://tva1.sinaimg.cn/large/0060lm7Tly1g4etu9ghe0j31ln0u0drw.jpg)

**Comment by tzach** [comment]
Thanks for reporting
What version of Scylla?
What replication factor and CL?

**Comment by zgbgx** [comment]
version 3.0.7
RF 1

**Comment by zgbgx** [comment]
> Thanks for reporting
> What version of Scylla?
> What replication factor and CL?

version 3.0.7
RF 1

**Comment by slivne** [comment]
please check the configuration file under /etc/scylla.d/  (that are created in installation /scylla_setup)

if the HW is the same the configuration files should be the same as well - are they ?

Since you are using RF=1 it could be that the load on the nodes is different (e.g. one is hit with more requests than other)

Please provide more metrics (screenshots of all dashboards)

**Comment by tzach** [comment]
@zgbgx closing this issue as we need more info to investigate
Please reopen once you have more data. Thanks.
