### ISSUE TITLE
really_complex_repair_test: Expected [['a', 1, 1, 3.0], ['a', 2, 2, 3.0]] from SELECT * FROM ks.t_by_v WHERE v2 = 'a', but got []

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4692]
Seen starting [dtest-release/172/testReport/materialized_views_test/TestMaterializedViews/really_complex_repair_test/](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/172/testReport/materialized_views_test/TestMaterializedViews/really_complex_repair_test/):

Scylla version a0499bbd31ddcef0ac3fa8e3c4e5b8f2fc2342bd

```
Error Message
Expected [['a', 1, 1, 3.0], ['a', 2, 2, 3.0]] from SELECT * FROM ks.t_by_v WHERE v2 = 'a', but got []
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 3052, in really_complex_repair_test
    cl=ConsistencyLevel.QUORUM
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1217, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 78, in assert_all
    assert list_res == expected, "Expected %s from %s, but got %s" % (expected, query, list_res)
AssertionError: Expected [['a', 1, 1, 3.0], ['a', 2, 2, 3.0]] from SELECT * FROM ks.t_by_v WHERE v2 = 'a', but got []
```

**Comment by bhalevy** [comment]
Seen in [byo_build_tests_dtest/408](https://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/408/testReport/materialized_views_test/TestMaterializedViews/really_complex_repair_test/) at the same commit
@psarna can you please look into this?

**Comment by psarna** [comment]
I don't really follow what this test is trying to prove (original git blame just says ` Test for materialized views implementation (CASSANDRA-6477)`", which doesn't help.
The part that troubles me a little is also where the assertion fails:
~~~
        # at this point the data isn't repaired so we have an inconsistency.
        # this value should return None
        assert_all(
            session2,
            "SELECT * FROM ks.t_by_v WHERE v2 = 'a'", [['a', 1, 1, 3.0], ['a', 2, 2, 3.0]],
            cl=ConsistencyLevel.QUORUM
        ) # (1.)

        debug('Run global repair on node1')
        node1.repair()

        assert_none(session2, "SELECT * FROM ks.t_by_v WHERE v2 = 'a'", cl=ConsistencyLevel.QUORUM) # (2.)
~~~

Here, we first check in the test that we reached an inconsistency (`1.`), then we repair and ensure that after repairing we got rid of the introduced inconsistency (`2.`).

Now, for Scylla the failure just says that we failed in asserting that we introduced an inconsistency (`1.`), which means that everything is fine, just earlier than we expected. That means that the test assumes we will definitely never get rid of inconsistencies unless we run a repair. Maybe it's a true assumption now, but it seems fragile.
Now, majority of the assertions in this test case should probably be wrapped in `eventually`, because after we insert rows into the base table, we cannot be sure that they immediately reach the underlying materialized view. It might be the reason why this test "fails", but I'm not sure, and I wasn't able to reproduce it locally despite several attempts.

I would really love to push it down as a n00b task for somebody to get introduced into dtests (this issue, and generally going through materialized_views_test.py and adding missing `eventually` calls). Is it high priority enough for me to preempt and add these `eventually`'s, or can we just assign somebody?

**Comment by bhalevy** [comment]
@eliransin please prioritize.
