### ISSUE TITLE
Reduce impact of sstable compaction on throughput

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#470]
In a write-heavy workload on softlayer setup one can observe that node's throughput curve has periodically occurring troughs. They're clearly visible soon after launching the node when shards haven't desynchronized yet. There are troughs of low amplitude, which are correlated with memtable flushes, and ones with higher amplitude but 3 times less frequent. The latter were identified to come from sstable compaction. When compaction is disabled they no longer occur.

It wasn't confirmed which aspect of compaction is impacting the throughput, but CPU overhead is suspected. To remedy this, we could throttle CPU time consumed by compaction in a similar way as we throttle memtable->cache flushing, using seastar thread scheduler.

**Comment by tgrabiec** [comment]
That occurs in a cluster, with RF=3 CL=QUORUM

**Comment by raphaelsc** [comment]
We should have a global throttling mechanism for compaction. Currently, compaction manager uses a poor approach to limit the number of compaction per shard. There is an issue discussing this compaction issue: https://github.com/scylladb/scylla/issues/72

**Comment by slivne** [comment]
Also related to allowing multiple compactions at each level

[ASCII art trigger warning]

Let's imagine an insert-only workload -- no reads, no overwrites.

We have a small shared, so memtable flushes generate 1MB sstables:


    [0.0] [0.1] [0.2] [0.3] [0.4] [0.5] [0.6] [0.7] [0.8] [0.9] ...

every 4 sstables, we trigger a compaction: 0.0-0.3 -> 1.0; 0.4-0.7 -> 1.1; 0.8-0.11 -> 1.2, etc.  So we have:


    [0.0] [0.1] [0.2] [0.3] [0.4] [0.5] [0.6] [0.7] [0.8] [0.9] ...
                            [         1.0         ] [ 1.1         ] [         1.2

and this continues downwards: 1.0-1.3 will be compacted into 2.0, 1.4-1.7 will be compacted into 2.1, and 2.0-2.3 will be compacted into 3.0

It is clear that a compaction of level N must not hold down a compaction of level N-1, because that causes the number of sstables to increase rapidly, slowing down reads.  On the other hand, there is no point in compacting concurrently at the same level, because that slows down both compactions.  Ideally, we have exactly one compaction per level.

Let's see how many concurrent compactions we have.  Let's assume 10 TB/node, 30 shared/node, and 200 MB sstables at level 0.

We have: storage per shared = 10 TB / 30 shards = 300 GB

Number of levels =~ log4 (300 GB / 300 MB) = 5

So we have 5 concurrent compactions, 1 per level. This means that every mutation is getting simultaneously written 6 times and read 5 times.  That's a very high write amplification!  Fortunately overwrites reduce that a lot.  So use size-tiered if you have a lot of overwrites.

Who says we have to compact 4 L0 sstables to get one L1 sstable? Let's call that number W (for width) and examine its influence:

If it's lower, write amplification is greatly increased, since it's the base in the logarithm in the equation:

   #levels = log (base W) (total_shard_storage / level_0_sstable_size)

for our previous example, setting W=2 gives #=10, and W=16 gives #=2.5, so high W gives reduced write amplification (and therefore greater write throughput).  On the other hand there are more sstables, so lower uncached read throughput.

In general:

   non-overwrite write throughput ~ log W
   uncached read throughput       ~ 1/W

(this holds if every partition key is in every sstable; if partition keys are not reused, the bloom filter will select just one sstable and read throughput is not impacted)

Conclusions:
 - for size-tiered compaction, we need exactly one concurrent compaction per level
 - pick your W with care; I think we can increase the default

**Comment by slivne** [comment]
need to check what todo for leveled as well

**Comment by nyh** [comment]
On Mon, Dec 28, 2015 at 12:43 PM, slivne <notifications@github.com> wrote:

> Also related to allowing multiple compactions at each level
>
> [ASCII art trigger warning]
>
> Let's imagine an insert-only workload -- no reads, no overwrites.
>
> We have a small shared, so memtable flushes generate 1MB sstables:
>
> [0.0] [0.1] [0.2] [0.3] [0.4] [0.5] [0.6] [0.7] [0.8] [0.9] ...
>
> every 4 sstables, we trigger a compaction: 0.0-0.3 -> 1.0; 0.4-0.7 -> 1.1;
> 0.8-0.11 -> 1.2, etc. So we have:
>
> [0.0] [0.1] [0.2] [0.3] [0.4] [0.5] [0.6] [0.7] [0.8] [0.9] ...
>                         [         1.0         ] [ 1.1         ] [         1.2
>
> and this continues downwards: 1.0-1.3 will be compacted into 2.0, 1.4-1.7
> will be compacted into 2.1, and 2.0-2.3 will be compacted into 3.0
>
> It is clear that a compaction of level N must not hold down a compaction
> of level N-1,
>
You are mentioning "Levels" here so it sounds like you're discussing
leveled compaction strategy, and yet what you're drawing above is what
*size tiered* compaction does, not what leveled compaction does. So I'm
really confused what you are referring to here.



> So we have 5 concurrent compactions, 1 per level. This means that every
> mutation is getting simultaneously written 6 times and read 5 times. That's
> a very high write amplification!


You're correct about the write amplification in general, but I don't think
it is "simultaneous" like you said: Each compaction typically involves 13
sstables of a fixed size (see
https://github.com/scylladb/scylla/wiki/SSTable-compaction#leveled-compaction)
so 5 simultaneous compactions involve about 60 sstables of a fixed size.
This may be a tiny fraction of the entire data set, and definitely doesn't
include every mutation 5 times.

So in the long run, leveled compaction does have a higher write
amplification, because mutations from L0 need to be copied into L1 and then
L2 ... until reaching L5 they have been copied 5 times. This additional
I/O  is one of the downsides I mentioned of leveled compaction (but that
section was left as a "CONTINUE HERE" and definitely needs to be written).



> Fortunately overwrites reduce that a lot. So use size-tiered if you have a
> lot of overwrites.
>
> Who says we have to compact 4 L0 sstables to get one L1 sstable?
>
Do we even do that? Usually you merge some L0 sstables with *all* 10 L1
sstables at once, unless I'm misunderstanding something.


> Let's call that number W (for width) and examine its influence:
>
> If it's lower, write amplification is greatly increased, since it's the
> base in the logarithm in the equation:
>
> #levels = log (base W) (total_shard_storage / level_0_sstable_size)
>

As far as I know, this "W" parameter is a separate parameter of leveled
compaction (and defaults to 10?) and is not related to the "4" parameter of
size-tiered compaction.

> for our previous example, setting W=2 gives #=10, and W=16 gives #=2.5, so
> high W gives reduced write amplification (and therefore greater write
> throughput). On the other hand there are more sstables,
>
More sstables? The sstables in leveled compaction have fixed size, so given
a fixed amount of data, the number of sstables would be the same.

If you're talking about the number of sstables needed to be read for a
single request, well, this number is around the #levels above (one per
level) and usually less (Cassandra docs claim usually 1, I could never
verify this theoretically). So high W definitely doesn't result in needing
to read more sstables - if anything, it's the opposite. If W was infinity,
you'd have everything in L1 sstables, and every read can be satisfied from
just one L1 sstables (plus any sstables which remain in L0).


> so lower uncached read throughput.
>
> In general:
>
> non-overwrite write throughput ~ log W
> uncached read throughput ~ 1/W
>
> (this holds if every partition key is in every sstable; if partition keys
> are not reused, the bloom filter will select just one sstable and read
> throughput is not impacted)
>
> Conclusions:
>
>    - for size-tiered compaction, we need exactly one concurrent
>    compaction per level
>
>
I don't understand how you reached this conclusion from a discussion about
level-tierd compaction, nor what does "level" even mean in the context of
size-tiered compaction. Now I'm even more unsure from before which
compaction strategy you were talking about above....

**Comment by slivne** [comment]
@nyh 
The analysis @avikivity has written was for sizetieredcompaction - a while ago and there was some discussion on the mailing list - my understanding was that we agreed that this should be done (at least for sizetieredcompaction) - so all the algorithm code (copied from Avi's email) uses level from the context of sizetieredcompaction strategy.

My request was to think if leveledcompaction should also have multiople compactions one in each level (now in the context of leveledcompaction) running concurrently or not - I am not saying it is correct or incorrect.

**Comment by avikivity** [comment]
Fixed by cce1a2bce868d19034c2de50c1ace4546e0244ad, no?

**Comment by glommer** [comment]
Technically if you are not on SizeTiered the compactors can still use too
much resources. But I am not opposed to closing this and opening specific
bugs

**Comment by avikivity** [comment]
Let's keep it open until everything is tidied up.

**Comment by avikivity** [comment]
Do we have any compaction strategy not controlled now?

**Comment by avikivity** [comment]
(/cc @glommer)

**Comment by glommer** [comment]
DateTiered is not controlled. I am not sure we'll ever write a real controller for it, so we can close it.

**Comment by avikivity** [comment]
Agree. We should formally deprecate DateTiered in favor of TimeWindow. Closing as all non-deprecated compaction straregies are now controlled.
