### ISSUE TITLE
Internal system/local table reads should have no timeouts / Driver queries should have timeouts

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4711]
Following https://github.com/scylladb/scylla/issues/2462 we have made all system queries run without timeouts.

There are different sources for system/local table queries:
- there are scylla internal queries
- there are client side driver queries

The scylla internal queries should not timeout

The client side driver queries should timeout

**Comment by slivne** [comment]
related to #5919 

@denesb is this solved ?

**Comment by denesb** [comment]
@slivne yes, https://github.com/scylladb/scylla/commit/0c6bbc84cd30df1c46a6cd81d87170b99d5a8144 solves this, all queries coming from the driver will have timeouts regardless of what table they query.

**Comment by denesb** [comment]
@slivne actually, this was true already before https://github.com/scylladb/scylla/commit/0c6bbc84cd30df1c46a6cd81d87170b99d5a8144, since https://github.com/scylladb/scylla/commit/08a0c3714cb739a7a77c11c15fed1f1ce70f5200. We removed the timeout from internal reads by passing `db::no_timeout` to the various read methods when doing internal reads. Queries coming from the user used the configured timeout.
