### ISSUE TITLE
Scylla metrics: read timeouts of 5s are reported in 8s buffer - needs to be fixed

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4746]
copy pasting from @gleb-cloudius 

> It looks like 8s is not a real value but an artifact of how histograms
> are aggregated for Prometheus. The number of buckets is reduced from 90
> to 20 and all 5s timeouts are aggregated into 8s bucket (there is ~4s and
> ~8s buckets in the Prometheus).

**Comment by amnonh** [comment]
Problem explanation:
Histograms are collected internally in buckets with an exponential-growth factor of 1.2 and a total number of buckets of 91

To reduce message size, we sum and return a histogram with an exponential growth factor of 2.

While we can technically set a specific bucket for a known limit of 5s, it's just a number and the last bucket will always suffer from an average of 1.5 amplification (in this case, instead of 5 we get 8).

I'm not sure what is the expected result. We can use a smaller exponential factor (on the price of reporting more buckets)
We can try and use larger exponential growth on the lower number and higher on the higher ones.

Whatever we do, it should be consistent amongst all shards.

**Comment by slivne** [comment]
so what is the first bucket 1ms ?

In my view we at least need to have a bucket for every timeout value the user specifies in the config, 

```
from yaml with defaults ...

read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
range_request_timeout_in_ms: 10000
counter_write_request_timeout_in_ms: 5000
cas_contention_timeout_in_ms: 1000
truncate_request_timeout_in_ms: 60000
request_timeout_in_ms: 10000
```

crossing the user settings is an indication of a bug we need to fix.

**Comment by gleb-cloudius** [comment]
On Sun, Jul 21, 2019 at 11:50:36PM -0700, Shlomi Livne wrote:
> so what is the first bucket 1ms ?
> 
> In my view we at least need to have a bucket for every timeout value the user specifies in the config, 
> 
With user provided timeouts per op it will not be possible.

--
			Gleb.

**Comment by slivne** [comment]
True 

- User provided per query timeouts -  doesn't exist at this point.
- I still expect the default limit to be whatever is set in the config - so even in that case it would be useful.

Any better idea ?

**Comment by gleb-cloudius** [comment]
On Mon, Jul 22, 2019 at 01:23:51AM -0700, Shlomi Livne wrote:
> Any better idea ?
> 
Since the data here is a histogram and not exact statistics and number
of buckets is very limited due to message size concern I do not think
there is an ideal solution here. May we should make the panel to be more
clear about what is shown there. Instead of claiming that the latency is
X it should be more clear that the latency is between X and Y and not an
exact value.

--
			Gleb.
