### ISSUE TITLE
Differentiate between real and extraneous EEXIST errors during snapshot

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#477]
Avi says, regarding 2575a4602e174f

> While that's better than before, there is still a danger that we get EEXIST because we somehow try to override a snapshot.
> Maybe we should use sstable_deletion_manager for this?  It already has all of the information about the sharing status.
> We can merge this, and file an issue for this change."

Another option would be to have only the coordinator shard dealing with the filesystem operations. It comes with its own problems because it doesn't know about all tables, shard-local tables would have to be reopened in the coordinator shard.

But maybe the set of problems that comes with that is smaller than the ones we currently have.

One way or another, we should make it better.

**Comment by vladzcloudius** [comment]
@glommer wouldn't simply checking that the requested snapshot already exists before issuing "linking" do the job?

**Comment by glommer** [comment]
The problem is that without a coordinator, between the check and the actual creation another shard could have created it under our nose.

So we either have to live with the error - if many shards can issue the creation, as we do now, or elect a coordinator.

BTW, if we haven't seen this as a problem in practice, that is no reason for this to be marked as a bug - let alone a high prio one.

**Comment by vladzcloudius** [comment]
Since we are talking about avoidance of collisions between two processes trying to create a snapshot with the same tag - it's about verifying that a snapshot directory doesn't already exist. The check should be performed in a way that a process has to try to create it - if it fails (with EEXIST), then this means there is a collision and a corresponding error should be reported. This may be achieved by calling open() with (O_CREAT | O_EXCL) in addition to other flags for the leaf directory in the recursive_touch_directory() (called by column_family::snapshot()) and by propagating the result via the returned `future`.

This will exclude the race @glommer has described above and we will not require any `coordinator` in addition to FS. ;)

**Comment by avikivity** [comment]
Fixed by 122136c6177255cfe8fe344f66fbb07d4755d025. /cc @bhalevy
