### ISSUE TITLE
Dist Debian: should create output files under scylla/build/XXX

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#492]
script curently creates output in a directory holding scylla

```
ubuntu@ip-10-69-85-220:~/scylla$ ls -l ..
total 95504
drwxrwxr-x 30 ubuntu ubuntu     4096 Oct 25 12:30 scylla
-rw-r--r--  1 ubuntu ubuntu    34591 Oct 25 12:40 scylla-server_0.10-1_amd64.build
-rw-r--r--  1 ubuntu ubuntu     1252 Oct 25 12:40 scylla-server_0.10-1_amd64.changes
-rw-r--r--  1 ubuntu ubuntu  4337130 Oct 25 12:39 scylla-server_0.10-1_amd64.deb
-rw-r--r--  1 ubuntu ubuntu      893 Oct 25 12:29 scylla-server_0.10-1.dsc
-rw-r--r--  1 ubuntu ubuntu 93406677 Oct 25 12:29 scylla-server_0.10-1.tar.gz
```

**Comment by syuu1228** [comment]
I checked debuild command manual, there's no option to specify output directory. So I think this is debian packaging tool limitation.
Only way to do this is, just do "mv ../scylla-server_X.XX-X* ./build" after finished building.

**Comment by syuu1228** [comment]
Forgot mention, there's tool called pbuilder, it is similar to mock (chroot package build tool), it able to specify output directory like mock. We can move it http://manpages.ubuntu.com/manpages/raring/man8/pbuilder.8.html

**Comment by tzach** [comment]
@syuu1228 can we close this?

**Comment by benoit-canet** [comment]
@slivne: this is the normal behavior of the dpkg build system.

In fact moving the files inside the scylla directory would be counter productive because this directory is archived as a whole as a tarball during the build process. (see scylla-server_0.10-1.tar.gz).
So we would end up poluting this archive if the output of the build was inside the program directory.

**Comment by benoit-canet** [comment]
more over the archive would grow at each build :)
