### ISSUE TITLE
Timeouts during resharding and load failure

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#4952]
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc4-0.20190901.b3a163b959
Cluster size: 5 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-093c99515247077f1

MV and SI longevity failed because of timeouts during resharding.

Scenario:

Restart node with changing murmur3: 
```
Set current_disruption -> RestartNode with resharding Node longevity-mv-si-4d-3-1-db-node-fad413c3-3 [52.16.250.41 | 10.0.48.138] (seed: False)
```
Resharding started:
```
< t:2019-09-02 08:04:33,772 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-09-02T08:04:32+00:00  ip-10-0-48-138 !INFO    | scylla: [shard 0] compaction - Resharding [/var/lib/scylla/data/sec_index/users_initials_ind_index-ba85d861cd3711e9ace900000000000d/mc-594-big-Data.db:level=0, ]

< t:2019-09-02 08:04:33,772 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-09-02T08:04:32+00:00  ip-10-0-48-138 !INFO    | scylla: [shard 12] compaction - Resharding [/var/lib/scylla/data/sec_index/users_initials_ind_index-ba85d861cd3711e9ace900000000000d/mc-784-big-Data.db:level=0, ]

< t:2019-09-02 08:04:33,773 f:cluster.py      l:1186 c:sdcm.cluster         p:DEBUG > 2019-09-02T08:04:32+00:00  ip-10-0-48-138 !INFO    | scylla: [shard 9] compaction - Resharding [/var/lib/scylla/data/sec_index/users_initials_ind_index-ba85d861cd3711e9ace900000000000d/mc-781-big-Data.db:level=0, ]
```

Receive a lot of apply mutation failures:
```
 ip-10-0-48-138 !WARNING | scylla: [shard 6] storage_proxy - Failed to apply mutation from 10.0.212.55#6: seastar::semaphore_timed_out (Semaphore timedout)
```

And ReadTimeoutException:
```
RemoteCmdRunner [centos@10.0.109.115]: com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency QUORUM (3 responses were required but only 2 replica responded)
```

Cassandra-stress threads failed:
```
< t:2019-09-02 08:09:59,717 f:remote.py       l:662  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.109.115]: java.lang.RuntimeException: Failed to execute stress action
< t:2019-09-02 08:09:59,719 f:remote.py       l:662  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.109.115]:    at org.apache.cassandra.stress.StressAction.run(StressAction.java:100)
< t:2019-09-02 08:09:59,719 f:remote.py       l:662  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.109.115]:    at org.apache.cassandra.stress.Stress.run(Stress.java:143)
< t:2019-09-02 08:09:59,720 f:remote.py       l:662  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.109.115]:    at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

Load failed:

![Screenshot from 2019-09-03 12-39-38](https://user-images.githubusercontent.com/34435448/64162419-efa3cc80-ce47-11e9-9a4e-b12c55926fe8.png)

**Comment by juliayakovlev** [comment]
@avikivity

**Comment by avikivity** [comment]
Resharding is running in the compaction I/O priority class, so it is competing with reads and writes. Probably, it has huge backlog because it sees many more bytes (up to nr_shards*per_shard_data instead of per_shard_data). Elevated backlog means even more shares.

Our options are:
 - run resharding in the maintenance (aka streaming) group; this can cause a genuine compaction backlog since regular compactions will be delayed
 - keep as is and tolerate the performance spike
 - run resharding before the node is online; this increases downtime when resharding, and thus we run in degrated mode for longer and risk unavailability, but performance of both reads and writes will be good

I'm in favor of the last option. In a really high disk:core ratio (e.g. I3en family) resharding can take a while, but the extended downtime is better than a unpredictable performance. Resharding is a rare operation so we can plan for it.

**Comment by bhalevy** [comment]
@glommer raising `min_threshold` temporarily during resharding makes sense.
Would it be needed if resharding runs in maintenance class, and maybe regular compaction shares are reduced/limited during that time?

**Comment by slivne** [comment]
@bhalevy / @glommer  is this a regression compared to 3.0 - I assume its not - if so we will push this out

**Comment by bhalevy** [comment]
@juliayakovlev did QA run this test also against 3.0?

**Comment by glommer** [comment]
I think this is needed for efficiency, not just for shares protection. We know we'll generate a lot of SSTables...

Another issue that I see with resharding is that it tends to blow up users' disk space. Even if you are around 50%. The original SSTables take long to be deleted because all shards have to ack, and in the mean time you already have the new ones -> and the compaction of the new ones.

**Comment by slivne** [comment]
@bhalevy / @raphaelsc ping

**Comment by avikivity** [comment]
I think resharding now has priority over other compactions.

We can't run resharding in the maintenance class, because this is priority inversion. Compactions will wait for resharding, so compaction shares are effectively ignored.

I don't think resharding should be particularly slow, it is a single pass over the data. So it should be limited to a few hours in most configuration (slow SATA 10TB @ 500 MB/s = 20,000 seconds = 6 hours).

**Comment by juliayakovlev** [comment]
I run materialized view longevity test with Scylla version 3.1.0.rc6-0.20190908.2ec036f50

There are a lot of semaphore timed out exceptions during restart with resharding nemesis:
```
2019-09-09T14:05:06+00:00  ip-10-0-126-132 !WARNING | scylla: [shard 9] storage_proxy - Failed to apply mutation from 10.0.177.253#9: seastar::semaphore_timed_out (Semaphore timedout)
```

and **sstable read queue overloaded** exceptions on restarted node
```
< t:2019-09-09 14:06:08,893 f:cluster.py      l:1216 c:sdcm.cluster         p:DEBUG > 2019-09-09T14:06:06+00:00  ip-10-0-82-176 !ERR     | scylla: [shard 11] storage_proxy - Exception when communicating with 10.0.126.132: std::runtime_error (sstable read queue overloaded)

< t:2019-09-09 14:06:08,893 f:cluster.py      l:1216 c:sdcm.cluster         p:DEBUG > 2019-09-09T14:06:06+00:00  ip-10-0-82-176 !ERR     | scylla: [shard 4] storage_proxy - Exception when communicating with 10.0.126.132: std::runtime_error (sstable read queue overloaded)

< t:2019-09-09 14:06:08,893 f:cluster.py      l:1216 c:sdcm.cluster         p:DEBUG > 2019-09-09T14:06:06+00:00  ip-10-0-82-176 !ERR     | scylla: [shard 4] storage_proxy - Exception when communicating with 10.0.126.132: std::runtime_error (sstable read queue overloaded)
```

**Comment by raphaelsc** [comment]
@avikivity @glommer It also makes me think that table's compaction strategy's backlog tracker should not account for shared sstables given that they only are concerned about the unshared ones that regular compaction can work on. It seems like compaction would be like compacting at a mad speed because it thinks it's way fall behind (because tracker is tracking all shared sstables) but it's just that there are tons of resharding work to do. Shared sstables have their backlog added both to strategy's backlog tracker and also to a backlog tracker assigned to resharding ops. I think that current behavior is a bug.

**Comment by glommer** [comment]
Indeed it makes sense to me that we wouldn't account for shared SSTables.

**Comment by arunsandu1** [comment]
we noticed higher timeouts during resharding on i3en instances. can find more details here https://github.com/scylladb/scylla/issues/5260#issuecomment-643921994

**Comment by raphaelsc** [comment]
After off-strategy work, resharding runs in maintenance group. Also if resharding on boot, we wait for resharding to complete before the node is online. This coupled with the fact that resharding sstables no longer is accounted by the backlog tracker (https://github.com/bhalevy/scylla/commit/12f5eec7640ee87021905b041d1febbee682b482), I think this issue can now be closed.
