### ISSUE TITLE
Alternator: support Autherization header

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5046]
When Scylla is running in a virtual network (a.k.a. VPC) and only the user's application can reach it, no further authentication is needed. But when Scylla is running on a public network, or (in the future) used by multiple tenants, authentication and identification is necessary.

The DynamoDB API has an “Authorization” header to authenticate the originator of this request. Amazon describe this feature in [signing AWS API requests](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html) and [signature version 4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html). Because this signing process does not involve secrets that only Amazon has, we can also allow the client to use the same signing algorithm (which is already embedded in his driver.

Note that this header allows message authentication, but not encryption, so HTTPS (see issue #5042) is still recommended on a shared network so that evesdroppers cannot read your requests. However, HTTPS is not necessary or recommended in setups inside a private network or a virtual private cloud.

**Comment by psarna** [comment]
I can take a look at this one now, if there are no objections. If there are objections - feel free to unassign me.

**Comment by psarna** [comment]
This example page provides a nice Python oracle for verifying that the signatures computed by our code actually match AWS's algorithm: https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html

**Comment by psarna** [comment]
I have a pretty much working code (99% tests pass) for a hardcoded `"whatever"` secret code, but it still computes the signature differently than boto3 for a `DescribeEndpoints` request... I'm not sure why, because their code above generates exactly the same signature as mine. I guess I'll spend some quality time inspecting boto3 implementation to see what's the difference.

**Comment by nyh** [comment]
Just a wild guess: Before you compute a signature, it's important to do some "canonization" of the data - it's important which headers you include in the checksummed message (if at all), it's important if you add spurious blank lines, carriage-returns in addition to linefeeds, and so on. Maybe there's a small difference in something like this? Again just a wild guess.
But I don't understand why the issue is specific to DescribeEndpoints....
Good luck!

**Comment by psarna** [comment]
I'll check. Fortunately, `boto3` generates a canonical request already, which makes sense, since it needs to calculate it anyway, so the first version just checks again a request that is assumed to be canonical. Of course, for other drivers it may not be enough and it's certainly not enough for manual curl-generated requests (although these do not usually generate authentication at all).

Also, DescribeEndpoints happens to be a request with empty JSON body `{}`, so there's not much to canonicalize... but I'll keep digging, maybe it has a HTTP query string like `localhost:8000/?something1=a&something2=b` or other esoteric parameters that I didn't take into account.

**Comment by nyh** [comment]
On Thu, Oct 3, 2019 at 3:48 PM Piotr Sarna <notifications@github.com> wrote:

> Also, DescribeEndpoints happens to be a request with empty JSON body {},
> so there's not much to canonicalize... but I'll keep digging, maybe it has
> a HTTP query string like localhost:8000/?something1=a&something2=b or
> other esoteric parameters that I didn't take into account.
>
Another wild guess: Is an empty JSON body "{}" or "" (nothing)?

**Comment by psarna** [comment]
checked both yesterday to be sure :) but boto3 sends `{}`

**Comment by psarna** [comment]
Fortunately, boto3 has a quite readable code in `botocore/auth.py`, so I'll be able to figure everything out rather quickly by adding a storm of debug info to that.

**Comment by psarna** [comment]
Aaand here it is. There's an additional `x-amz-api-version` header that wasn't really mentioned anywhere, and yet it appears in the `DescribeEndpoints` request and no other request that we support.

**Comment by psarna** [comment]
I'll send an RFC today, which will have all the infrastructure needed to run our tests, but it will be missing one most important bit: key management. When a client runs his workload using `boto3`, the library will extract his aws secret key (from a parameter, an env variable, a file, etc) and use that to sign all the requests. Now, we're going to need to have either a mapping of these somewhere inside Scylla, or access to an external service that can give us the key. I'm not if users prefer using their AWS-generated keys for that purpose so that no change is needed to switch to alternator or should they be somehow generated by Scylla.

For now, I used our deeply confidential `"whatever"` string as a secret key, but that's not a very secure solution for the long term.

Also, until we figure out how to maintain a key store, there's one more question. Right now alternator happily ignores the `Authorization` header, so once we introduce a patch that returns an error on improper credentials, it will no longer work out of the box (well, unless users start using a secret_key that's either hardcoded on our side or configurable from scylla.yaml). Perhaps we should have a config switch in alternator, which specifies if we want to enforce authorization or not? One more advantage of turning authorization off for environments that don't need it would be not having to compute all these signatures every time a request arrives.

**Comment by psarna** [comment]
Update: the issue is partially taken care of:
1. The code that computes the signature is here, along with a test that checks its correctness.
2. There's a configuration variable that allows enabling/disabling authorization in alternator - off by default.

Still left to do:
1. Key management. Right now Scylla uses a hardcoded `"whatever"` value as a secret key, which is enough for the test environment, but not so for production. We need a key store to extract the secret key of the user that sent the request, so we can compute the signature. It's hard to assume that users will be happy to upload their secret AWS keys to Scylla, so we need to consider how to implement it properly. An external key store, a system table with keys generated by us?
2. Documentation for `1.` above. Right now authorization is off by default, but in order for it to work flawlessly with all kinds of drivers, we should ensure that there's a clear document explaining how to set  up the key store, how to interpret errors, etc.

**Comment by psarna** [comment]
Soon I'll push another series that adds compatibility with our internal Scylla key store - the `system_auth.roles` table. I have a working prototype with only one additional step needed on the driver side - instead of the AWS secret key, they should use the `salted_hash` digest value of their password, and it will work.

One more thing to consider is caching of these credentials. Without it, every single request will result in a query to `system_auth.roles`, which is expensive. We can combine it with the information that signatures for AWS are valid for 5 minutes and perhaps just cache credentials in-memory for this period (or a shorter one).

Also, one more little TODO I forgot to mention:
* we need to honour the `datestamp` part of the signature. Right now it's just ignored, but we should check if the signature is older than 5 minutes and refuse it, if it is. It's trivial to fix, but not here yet.

**Comment by psarna** [comment]
I have a working branch here: https://github.com/psarna/scylla/commits/use_system_auth_roles_for_alternator_authorization , but I still need to figure out how to hack boto3 into sending a request with a different time, so I can check if signature expiration works fine.
