### ISSUE TITLE
Alternator: support "streams" feature

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5065]
"Streams" are DynamoDB's CDC (change data capture) feature, i.e., giving a user the ability to subscribe on the stream of changes to a particular table.

This is a big feature, with complex implementation and new APIs, but we should consider it again after we have CDC in Scylla CQL (see issue #4985).

**Comment by kbr-** [comment]
Note for future us:

it looks like DynamoDB's shards, which correspond to our streams, form a tree. Due to the Dynamo cluster growing, a shard gets split into multiple shards, and the old shard is a *parent* of these new shards. A DynamoDB streams client is supposed to finish reading the parent before it starts reading the children.

This is suspiciously similar to what we do when we add new nodes to the cluster, which splits vnodes into smaller sub-vnodes, which is the reason why we change the active set of streams: the new streams correspond to the new vnodes. I guess we could also think on introducing a parent-child relationship between our stream IDs: the stream IDs corresponding to our new, smaller vnodes, would be children of stream IDs corresponding to the old, bigger vnodes, which are sums of the new smaller vnodes.

However, the fact that we have a shared-nothing thread-per-core architecture, and we don't just have a stream ID per vnode, but a stream ID per vnode and per shard (don't confuse with Dynamo's "shard"; here I'm talking about our core-shard), complicates things a bit, and it could make it hard to create such a tree structure on streams.

This might be an argument for removing the "per-vnode-per-shard" thing, and just going with "per-vnode".

**Comment by nyh** [comment]
The difference is more than the parentage ("tree" structure) of streams. There is a more fundemental issue - the very different reasons for why Scylla and DynamoDB have many separate streams (which, confusingly, DynamoDB calls "shards"):

The dynamoDB documentation https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html explains why it creates multiple streams (called shards): 
```
A shard might split in response to high levels of write activity on its parent table, so that applications can process records from multiple shards in parallel.
```

In other words, in DynamoDB separate streams are created as a convenience for the **reader**: When the write activity (and hence the CDC log activity) is low, having just one stream to read for is good enough, and convenient - having a thousand of them would just make polling so much more difficult. So DynamoDB provides a reader just one stream. Only when the write activity significantly grows, does DynamoDB split the write activity to multiple streams (which it calls "shards") - each of these is designed to be usefully read by a single reader.

Scylla uses a different approach. Streams are started at the convenience of the **writer**, not the reader. We can have 10,000 streams if there are this number of `vnodes*cores`, because it's convenient to the writing code. We'll have this huge number of streams even if there are just 10 writes per second happening.

I think we have two implementation options:

The first option is to make the DynamoDB streams a thin layer on Scylla CDC. The DynamoDB API user will be given these same 10,000 streams. However, it's not clear (and needs to be tested) whether clients can actually work this way, or how efficient this would be... Note that normally DynamoDB only allows 10 DescribeStream calls per second, each returning up to 100 streams, so client code may not expect 10,000 streams. It may also not be designed to handle the polling of so many streams with any reasonable combination of performance and latency when the table doesn't have a huge write volume. 

The second option, which may be necessary, is to build a more sophisticated layer on top of Scylla CDC which will provide DynamoDB Streams API.  This layer would read from the 10,000 streams of Scylla, and merge them into perhaps only a few streams (depending on the volume of writes happening) - and provide these streams to the DynamoDB API user.

The second option sounds complicated, but in fact it is exactly what any Scylla CDC user will need to do anyway... **Any** Scylla CDC user will have just a few consuming nodes, and need to have code to read from thousands of streams and merge them into just one output stream to be consumed by the consumer. We'll eventually need to write this sample code (or describe it in a document), and the layer of the second option will be very similar.

**Comment by slivne** [comment]
On Sun, Mar 8, 2020 at 3:40 PM nyh <notifications@github.com> wrote:

> The difference is more than the parentage ("tree" structure) of streams.
> There is a more fundemental issue - the very different reasons for why
> Scylla and DynamoDB have many separate streams (which, confusingly,
> DynamoDB calls "shards"):
>
> The dynamoDB documentation
> https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html
> explains why it creates multiple streams (called shards):
>
> A shard might split in response to high levels of write activity on its parent table, so that applications can process records from multiple shards in parallel.
>
> In other words, in DynamoDB separate streams are created as a convenience
> for the *reader*: When the write activity (and hence the CDC log
> activity) is low, having just one stream to read for is good enough, and
> convenient - having a thousand of them would just make polling so much more
> difficult. So DynamoDB provides a reader just one stream. Only when the
> write activity significantly grows, does DynamoDB split the write activity
> to multiple streams (which it calls "shards") - each of these is designed
> to be usefully read by a single reader.
>

I would put this to a test ...

I think DynamoDB collocated LSI with the Base Table for a reason - so when
partitioning needs to happen then both can be moved.

I expect that dynamodb streams also align with that partitioning - that is
I expect for a 1TB database with a very slow write rate to have more than
one stream (since 1 TB will be split at least into 10 GB chunks and spread
across multiple nodes).


> Scylla uses a different approach. Streams are started at the convenience
> of the *writer*, not the reader. We can have 10,000 streams if there are
> this number of vnodes*cores, because it's convenient to the writing code.
> We'll have this huge number of streams even if there are just 10 writes per
> second happening.
>
> I think we have two implementation options:
>
The first option is to make the DynamoDB streams a thin layer on Scylla
> CDC. The DynamoDB API user will be given these same 10,000 streams.
> However, it's not clear (and needs to be tested) whether clients can
> actually work this way, or how efficient this would be... Note that
> normally DynamoDB only allows 10 DescribeStream calls per second, each
> returning up to 100 streams, so client code may not expect 10,000 streams.
> It may also not be designed to handle the polling of so many streams with
> any reasonable combination of performance and latency when the table
> doesn't have a huge write volume.
>

We can put this to a test - the client library exists (
https://github.com/awslabs/amazon-kinesis-client/tree/master/amazon-kinesis-client
)

The second option, which may be necessary, is to build a more sophisticated
> layer on top of Scylla CDC which will provide DynamoDB Streams API. This
> layer would read from the 10,000 streams of Scylla, and merge them into
> perhaps only a few streams (depending on the volume of writes happening) -
> and provide these streams to the DynamoDB API user.
>
> The second option sounds complicated, but in fact it is exactly what any
> Scylla CDC user will need to do anyway... *Any* Scylla CDC user will have
> just a few consuming nodes, and need to have code to read from thousands of
> streams and merge them into just one output stream to be consumed by the
> consumer. We'll eventually need to write this sample code (or describe it
> in a document), and the layer of the second option will be very similar.
>
Lets test this out before we decide on creating another layer.

**Comment by nyh** [comment]
@slivne definitely, just like we did for the rest of the Alternator project, the Streams part will need to start with a short design process - we'll need to fully understand how this feature works, including experimenting with the actual DynamoDB implementation. Indeed there is the "Kinesis" client library (described here - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.KCLAdapter.html), but there's also a lower level interface in boto3, https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodbstreams.html with which we should probably start as it gives us a less obscured view of what DynamoDB really does. On the other hand it is possible that the Kinesis Client Library layer may be able to deal with a Streams implementation which made slightly different decision regarding shard counts than Amazon's - I don't know.

You're right, I can't really know if Amazon really has just one - or few - streams ("shards") on low write load, beyond that vague statement that the number of streams will increase as the write load increases (something which isn't the case in Scylla's CDC).

This - https://www.infoq.com/presentations/dynamodb-streams/ - is a 40 minute talk about how DynamoDB Streams work, given by Amazon Developers in 2016. Here is a review of this talk - https://www.infoq.com/articles/demystifying-dynamodb-streams/.

I think it is rather pointless to continue specultating here how DynamoDB Streams work. @slivne @eliransin let's officially decide to work on this - and I'll start the review and design process.

**Comment by kbr-** [comment]
> There is a more fundemental issue - the very different reasons for why Scylla and DynamoDB have many separate streams

But does the client care what the underneath reasons are? It's an implementation detail.

In DynamoDB, the client has to handle multiple shards. He's not given any choice - the database decides when/if shards are split, and the client must act accordingly. Whatever the database's reasons were.
In Scylla, ... it's the same, with shards replaced by streams.

> Note that normally DynamoDB only allows 10 DescribeStream calls per second, each returning up to 100 streams, so client code may not expect 10,000 streams. It may also not be designed to handle the polling of so many streams with any reasonable combination of performance and latency when the table doesn't have a huge write volume.

That's a real issue, I agree. But in this case we can just provide a "better" client.

---

There's another problem. If we want to map DynamoDB shards to Scylla streams, we need to preserve a tree structure on streams, which means that we can't "merge" streams: we can only split them. Today's CDC changes streams whenever a new node joins the ring, so that each vnode has at least one stream. Consider the following scenario:
1. node A joins (first node)
2. node B joins
3. node B leaves
4. node C joins
There are three different generations of streams: for 1., for 2., and for 4.
The vnodes for 1. refine the vnodes for 2., so streams for 2. can be mapped to streams for 1. to form a tree.
But the vnodes for 4. don't refine the vnodes for 2.: when node B left, it deleted some tokens from the ring, and when C joined, it inserted some different tokens into the ring. So we can't map streams for 4. to streams for 2. to form a tree.

To fix this problem we would need to remember all tokens that have ever existed in the ring and generate streams as if all those tokens formed our vnodes.

Unless DynamoDB also offers some way of merging shards or closing them and opening completely different ones.

**Comment by nyh** [comment]
@elcallio sent a pull request, https://github.com/scylladb/scylla/pull/6481, starting to add the DynamoDB Streams feature. In his implementation, the streams API is implemented on the same endpoint as the regular DynamoDB API. The initial implementation will do a one-to-one correspondence between Scylla CDC "streams" and DynamoDB Streams "shards", which can result in a very large number of shards - which supposedly doesn't happen on DynamoDB.
