### ISSUE TITLE
Unsupported DateTieredCompactionStrategy

### ISSUE THREAD

**Issue by locked** [scylladb/scylla#511]
With scylladb at commit 7254c877763268 (Sun Oct 25 19:59:45), I am getting the following error:

```
cqlsh:test> CREATE TABLE test (ownerid bigint, data text) WITH compaction = {'class': 'DateTieredCompactionStrategy'};ConfigurationException: <ErrorMessage code=2300 [Query invalid because of configuration issue] message="Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy">
```

According to the documentation (http://www.scylladb.com/kb/compaction/), "Scylla implements the same three compaction strategies as Cassandra", but looking at the "compaction_strategy.hh", it looks like it is not the case:

```
enum class compaction_strategy_type {
    null,
    major,
    size_tiered,
    leveled,
    // FIXME: Add support to DateTiered.
};
```

Would it be possible to update the documentation ?

**Comment by avikivity** [comment]
@raphaelsc

**Comment by raphaelsc** [comment]
@locked: DataTiered compaction strategy is not implemented yet. We plan to add support to it as soon as possible.

**Comment by penberg** [comment]
@dmarti @tzach Can you please update the site so other people don't trip on this before it's implemented?

**Comment by tzach** [comment]
@penberg already on it. 
A new version of www.scylladb.com/technology/status will be upload with the new rel 0.11 update.

**Comment by gwicke** [comment]
DTCS is one of two main features we need at @wikimedia. Looking forward to 1.1!

**Comment by hasmikhail** [comment]
is this feature close to being shipped?

thanks in advance!

**Comment by tzach** [comment]
@hasmikhail DateTieredCompaction is planned for 1.3, due early July

**Comment by hasmikhail** [comment]
awesome, thanks!

do you foresee any problems if we run regular cassandra hosts with DateTiered compaction, and then shut those down and start scylla on the same tables once the strategy becomes available?

**Comment by raphaelsc** [comment]
@hasmikhail No. Actually, you could start using a column family with DateTiered compaction on Scylla now, but Scylla would use Size Tiered strategy instead because it knows DateTiered isn't supported yet. However, it's indeed better to wait for DateTiered compaction to be available on Scylla which will be soon.

**Comment by cnlizg** [comment]
DTCS will be deprecated, suggest support TWCS , see https://issues.apache.org/jira/browse/CASSANDRA-9666

**Comment by raphaelsc** [comment]
On Mon, Jun 20, 2016 at 3:20 AM, cnlizg <notifications@github.com> wrote:

> DTCS will be deprecated, suggest support TWCS , see
> https://issues.apache.org/jira/browse/CASSANDRA-9666
>

DTCS will be supported soon, and given the similarities, TWCS can be easily
implemented afterwards. I quickly looked at this thread days ago, and I
still need to familiarize myself with TWCS. Thanks for sharing it!


> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla/issues/511#issuecomment-227058739>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABWAc2DKP30jtnRd2HcNTc8DGY7pAUWFks5qNjElgaJpZM4GXvMk>
> .
>



-- 
Raphael S. Carvalho

**Comment by hasmikhail** [comment]
Thanks for bringing up TWCS.  Mainly I just need a time-based strategy that will work better than default for my use-case.

**Comment by belliottsmith** [comment]
TWCS is certainly better than DTCS, but I would suggest that neither are as good as they could be.  For efficient read performance both require the assumption, that your clustering data correlates near perfectly with your timestamps, to hold.  So, any random update to a point in the past can completely ruin system behaviour.  Furthermore, tuning them is far from easy, as again they require that a proxy variable (your bucket) correlates to sensibly sized partitions.

As I originally proposed when DTCS was being considered, splitting based on the clustering data itself makes much more sense.  As does targeting a certain average partition size for a range, i.e. once you have partitions in a range on average occupying a few disk pages there's limited value to expanding the range, and it should be split.  The smaller the number, the higher the overheads of enumerating a time series, but the lower the compaction overheads, so the tradeoff is directly tunable, rather than indirectly by guessing your data density (and expecting it to be consistent across all times of day/days of week).

**Comment by avikivity** [comment]
That makes a lot of sense.   Apply a UDF to the clustering key to get the bucket?

**Comment by belliottsmith** [comment]
That might be the simplest thing to implement.  But, as I say (probably unclearly), I think for many timeseries use cases it would be better to impose the split points dynamically based on the average size of your partitions in the range.  The user can define a target partition size, and once a range hits that you start a new one.  

This permits directly trading read for write performance by tuning this target size (or target ratio to disk pages).  A small size (less than a page) means higher read costs, lower write costs; and vice versa.

There is, however, the issue of how to deal with workloads that only write very small partitions, which it would struggle to cope with.  So perhaps this is sufficient reason to stick to UDFs.

UDFs also permit easy mocking-up of TWCS for the user, so can readily be described as a superior superset of behaviour.  This would be helpful for partitions with no clustering data.

**Comment by hasmikhail** [comment]
is there an example UDF to mock-up TWCS available for review?

**Comment by belliottsmith** [comment]
Well, pretty sure the default semantics wouldn't support this as a single UDF; it requires composition with the built-in function WRITETIME.  Also, I'm not sure you can have UDFs that operate over multiple columns at once in the current semantics.  Both can be worked around to let the user manage, but there isn't a UDF you could point to in isolation to support this right now I don't think.

**Comment by cnlizg** [comment]
For  TWCS :
1>let a field with timestamp type as cluster key, for example vtime field.
2>insert data using timestamp option, value is vtime
3>update data using timestamp option, value is original vtime value

from  https://github.com/jeffjirsa/twcs/ , You should target fewer than 50 buckets per table based on your TTL. A TTL of 90 days may want 3 day buckets, where a TTL of 2 hours may want 5 minute buckets.

TWCS is clearly!

**Comment by hasmikhail** [comment]
Neat!

**Comment by hasmikhail** [comment]
Should we add a new issue for tracking the TWCS feature?

**Comment by penberg** [comment]
@hasmikhail Yes, please.
