### ISSUE TITLE
Alternator: incorrect error type returned for BEGINS_WITH

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#5141]
Commit 332ffa77ea9 fixed some cases for `BEGINS_WITH` tests, which were using the `EQ` operator by mistake. Unfortunately, once it was done, our alternator test suite stops working flawlessly on AWS (i.e. ran with `pytest --aws`) option.

The error is:
~~~
test_update_expected_1_begins_with_false:
E           AssertionError: Pattern 'ConditionalCheckFailedException' not found in 'An error occurred (ValidationException) when calling the UpdateItem operation: One or more parameter values were invalid: ComparisonOperator BEGINS_WITH is not valid for N AttributeValue type'
~~~
, which means that we should simply change the error type returned to the client.

Also, a general note, when creating/editing a test case for alternator, it's a good idea to run both `pytest` and `pytest --aws` to ensure that tests pass both for alternator and for the DynamoDB test oracle.

cc @nyh @dekimir

**Comment by nyh** [comment]
@psarna you're absolutely right about running pytest --aws (no need to do the entire thing - that takes ages - but just the tests you are modifying).

@psarna the message you saw means the test is wrong - funnily enough, I even wrote a comment on this test ("# Although BEGINS_WITH requires String or Binary type, ..."). So the test needs to be fixed to pass with "--aws" - that's the first step.

Then, the second step would be to change the Alternator code to pass the fixed test - `check_BEGINS_WITH()` should check v2's type (instead of where it now checks v1's) and throw a validation exception if not a string or binary. 
We should probably check v1's type as well (the type in the data), but we need to add a test for this case to verify what it *should* do/

**Comment by nyh** [comment]
Sent (to the mailing list) a patch for this issue, titled "alternator: fix Expected's BEGINS_WITH error handling".
@dekimir please review.

**Comment by nyh** [comment]
Removing "backport candidate" label. 3.1 does not include Alternator, and 3.2 was branched after this patch.
