### ISSUE TITLE
IOTune hang

### ISSUE THREAD

**Issue by fggarcia** [scylladb/scylla#5151]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.0.rc9-0.20191006.05272c53e
Cluster size: 14 instances (two datancer, 11-3)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-48-generic x86_64)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= 4 hyperthreading= memory= 8 GB
Disks: (SSD/HDD, count) NVME 80Gb x1 EXT4

This happen when i try to rerun iotune in:
```
/usr/lib/scylla/libexec/scylla_io_setup:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/block/vda/vda1
tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/block/vda
already tuned: /sys/devices/pci0000:00/0000:00:04.0/virtio1/block/vda/queue/nomerges
tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/block/vda/vda1
tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/block/vda/vda1
```
previously:
```
Do you want to run check your kernel version?
Yes - runs a  script to verify that the kernel for this instance qualifies to run Scylla. No - skips the kernel check.
[YES/no]
WARN  2019-10-07 14:01:51,392 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 124 MB: is less than recommended: 10 GB
```

but:
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           798M  972K  797M   1% /run
/dev/vda1        78G  4.3G   74G   6% /
tmpfs           3.9G   64K  3.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/vda15      105M  3.6M  101M   4% /boot/efi
tmpfs           798M     0  798M   0% /run/user/1001
```

I rollback to scylla 3.0.10, rerun iotune from setup and all run perfectly.

**Comment by avikivity** [comment]
Is /var/tmp/mnt the intended data directory? What filesystem is it using?

Please strace -f the iotune call and provide the trace.

**Comment by fggarcia** [comment]
Hi @avikivity 
execute:
```
sudo /usr/bin/iotune --format envfile --options-file /etc/scylla.d/io.conf --properties-file /etc/scylla.d/io_properties.yaml --evaluation-directory /home/user/data/scylla/data --evaluation-directory /home/user/data/scylla/commitlog --evaluation-directory /home/user/data/scylla/hints --default-log-level trace --log-to-syslog 0
```
output
```
DEBUG 2019-10-09 13:34:28,142 seastar - smp::count: 4
DEBUG 2019-10-09 13:34:28,143 seastar - latency_goal: 0.00075
DEBUG 2019-10-09 13:34:28,143 seastar - num_io_queues: 4
DEBUG 2019-10-09 13:34:28,164 [shard 0] seastar - generate_config dev_id: 0
DEBUG 2019-10-09 13:34:28,177 [shard 2] seastar - generate_config dev_id: 0
DEBUG 2019-10-09 13:34:28,177 [shard 1] seastar - generate_config dev_id: 0
DEBUG 2019-10-09 13:34:28,177 [shard 3] seastar - generate_config dev_id: 0
```
here hang....waiting for 30 minutes

**Comment by tzach** [comment]
> Please strace -f the iotune call and provide the trace.

@fggarcia  did you run strace?

**Comment by fggarcia** [comment]
hi @tzach @avikivity 

can i do something else?

**Comment by fggarcia** [comment]
@tzach @avikivity after upgrade to 3.1.1, same problem. can you help me?

**Comment by avikivity** [comment]
@glommer I see this sequence in the log:

```
[pid  3634] openat(AT_FDCWD, "/home/despegar/data/scylla/data", O_RDONLY|O_CLOEXEC|O_DIRECTORY <unfinished ...>
[pid  3634] <... openat resumed> )      = 19
[pid  3634] openat(AT_FDCWD, "/home/despegar/data/scylla", O_RDONLY|O_CLOEXEC|O_DIRECTORY <unfinished ...>
[pid  3634] <... openat resumed> )      = 19
[pid  3634] openat(AT_FDCWD, "/home/despegar/data", O_RDONLY|O_CLOEXEC|O_DIRECTORY <unfinished ...>
[pid  3634] <... openat resumed> )      = 19
[pid  3634] openat(AT_FDCWD, "/home/despegar", O_RDONLY|O_CLOEXEC|O_DIRECTORY <unfinished ...>
[pid  3634] <... openat resumed> )      = 19
[pid  3634] openat(AT_FDCWD, "/home", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 19
[pid  3634] openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 19
[pid  3634] openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 19
[pid  3634] openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 19
```

(endlessly repeats)

I guess iotune is trying to find a mountpoint boundary, but isn't prepared for the case where the data directory is also the root filesystem. Is that the case?

**Comment by fggarcia** [comment]
Hi @glommer @avikivity 

do you have any update about this?

**Comment by avikivity** [comment]
This is likely the problem code:

```c++
fs::path mountpoint_of(sstring filename) {
    fs::path mnt_candidate = fs::canonical(fs::path(filename));
    compat::optional<dev_t> candidate_id = {};
    auto current = mnt_candidate;
    do {
        auto f = open_directory(current.string()).get0();
        auto st = f.stat().get0();
        if ((candidate_id) && (*candidate_id != st.st_dev)) {
            return mnt_candidate;
        }
        mnt_candidate = current;
        candidate_id = st.st_dev;
        current = current.parent_path();
    } while (mnt_candidate != current);

    return mnt_candidate;
}
```

I don't see how it fails though. when current becomes "/", then mnt_candidate is also "/" and the loop should stop.

**Comment by avikivity** [comment]
I wrote a small test program to test it, and it seems to work as expected.

**Comment by glommer** [comment]
We have a lot of setups where the data is mounted in the same mountpoint as the root and they all work well. I doubt this is the issue.

**Comment by slivne** [comment]
reproducer is now available at https://github.com/scylladb/scylla/issues/5306

**Comment by siphonelee** [comment]
I have the same issue iotune appearing to be hanging forever. With strace I got endless loop like this (please pay attention to the "Inappropriate ioctl for device" message):

......
[pid 32245] openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 35
[pid 32245] read(6,  <unfinished ...>
[pid 32237] fstat(35, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 32237] ioctl(35, BLKGETSIZE, 0x7ffd70f1cce0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 32237] fcntl(35, F_GETFL)          = 0x18000 (flags O_RDONLY|O_LARGEFILE|O_DIRECTORY)
[pid 32237] ioctl(35, _IOC(_IOC_READ, 0x58, 0x1e, 0xc), 0x7ffd70f1d090) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 32237] write(6, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32246] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32246] read(4,  <unfinished ...>
[pid 32245] fstat(35, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 32245] read(6,  <unfinished ...>
[pid 32237] close(35)                   = 0
[pid 32237] write(6, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 35
[pid 32245] read(6,  <unfinished ...>
[pid 32237] fstat(35, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 32237] ioctl(35, BLKGETSIZE, 0x7ffd70f1cce0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 32237] fcntl(35, F_GETFL)          = 0x18000 (flags O_RDONLY|O_LARGEFILE|O_DIRECTORY)
[pid 32237] ioctl(35, _IOC(_IOC_READ, 0x58, 0x1e, 0xc), 0x7ffd70f1d090) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 32237] write(6, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] fstat(35, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 32237] close(35 <unfinished ...>
[pid 32245] read(6,  <unfinished ...>
[pid 32237] <... close resumed> )       = 0
[pid 32237] write(6, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 35
[pid 32245] read(6,  <unfinished ...>
[pid 32237] fstat(35, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 32237] ioctl(35, BLKGETSIZE, 0x7ffd70f1cce0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 32237] fcntl(35, F_GETFL)          = 0x18000 (flags O_RDONLY|O_LARGEFILE|O_DIRECTORY)
[pid 32237] ioctl(35, _IOC(_IOC_READ, 0x58, 0x1e, 0xc), 0x7ffd70f1d090) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 32237] write(6, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] fstat(35, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 32237] close(35 <unfinished ...>
[pid 32246] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32237] <... close resumed> )       = 0
[pid 32246] read(4,  <unfinished ...>
[pid 32237] write(6, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid 32245] read(6,  <unfinished ...>
[pid 32237] <... write resumed> )       = 8
[pid 32245] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 32245] openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 35
[pid 32245] read(6,  <unfinished ...>
[pid 32237] fstat(35, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 32237] ioctl(35, BLKGETSIZE, 0x7ffd70f1cce0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 32237] fcntl(35, F_GETFL)          = 0x18000 (flags O_RDONLY|O_LARGEFILE|O_DIRECTORY)
[pid 32237] ioctl(35, _IOC(_IOC_READ, 0x58, 0x1e, 0xc), 0x7ffd70f1d090) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 32237] write(6, "\1\0\0\0\0\0\0\0", 8) = 8
.......

Since all these are ioctl related errors, I'm suspecting if it's related to my server instance which is hosted in a cloud platform - maybe the hypervisor disables some ioctl commands? @avikivity thoughts plz?

**Comment by fggarcia** [comment]
@avikivity Sorry for ask again. Upgrade to 3.1.2, the issue still happen.

**Comment by slivne** [comment]
@bhalevy please try to see if someone in your team can look at this - please note there is a reproducer from eyal in #5306 - so my suggestion is to try and do what ever eyal did and then find the issue.

**Comment by avikivity** [comment]
The ioctl errors are benign. Seasar is checking if a file is really a block device, and it isn't (as expected).

Please repeat the strace with `-fttT` flags, and give the `--force-aio-syscalls 1` flag to iotune (in the same call).

**Comment by fggarcia** [comment]
Hi @avikivity sorry for not response until today. I didn't see your last comment.

Today, I install 3.2-rc3 in beta environment. Run iotune, I don't have any problem.

I close this issue
