### ISSUE TITLE
Alternator: Add support for ScanIndexForward

### ISSUE THREAD

**Issue by PatrykGala** [scylladb/scylla#5153]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): scylladb/scylla-nightly:alternator:02da388c4f7e
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu (docker)

When I try to find one latest element in Local Secondary Index, I use ScanIndexForward and Limit, but Scylla returns all elements in natural order. 

I use official DynamoDB client:
```java 
DynamoDBQueryExpression<DynamoEvent> queryExpression = new DynamoDBQueryExpression<DynamoEvent>()
                .withHashKeyValues("hashkey")
                .withRangeKeyCondition("lsi_index_name", new Condition().withComparisonOperator(ComparisonOperator.BEGINS_WITH).withAttributeValueList(value))
                .withIndexName("lsi_index_name")
                .withScanIndexForward(true)
                .withLimit(1);
```

Is it a bug? Or not implemented? When will Alternator support these functions?

**Comment by nyh** [comment]
First of all, turns out that we indeed did not implement Query's ScanIndexForward yet, and we forgot to document that we didn't implement it... So thanks for reminding us and opening an issue about it! And we will implement it, hopefully very soon because this is a fairly simple feature.

The "Limit" problem, is more surprising. We supposedly do support the "Limit" option correctly, but I see now that we only have tests for the Limit option for Scan case, and forgot to do them for Query as well, so I can't rule out the possibility of a bug. But before we investigate that, I want you to please rule out that you are not resuming the query yourself? DynamoDB queries are always paged - returning one page of replies and then you're supposed to redo the query to get further pages. Is it possible that your code is doing that? If it is, it doesn't matter that Limit (the page size) is - at the end you'll get all the items.

Both problems demonstrate that alternator-test/test_query.py is not extensive enough (it doesn't cover all of Query's features) and this is the first thing I want to fix.

**Comment by nyh** [comment]
I just sent to the mailing list a patch titled "alternator-test: test Query's Limit parameter" which confirms that "Limit" does work correctly (without ScanIndexForward, of course). So I still don't know what is the problem you saw with Limit. @PatrykGala if you can look into this issue for me (ignoring the wrong order, for a moment), it would be helpful. Thanks.

**Comment by PatrykGala** [comment]
Thank you. Could I implement `ScanIndexForward`? Could you give me some tips about where I can start?  Slack or mailing-list?

You are right the Limit works, when I'm debugging in IDE, debugger calls `Object#toString()` on the List object, 
the method `toString` calls `List#size()`,
the size method calls: [com.amazonaws.services.dynamodbv2.datamodeling.PaginatedList#loadAllResults()](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/PaginatedList.java#L126) 
and load all elements :)

**Comment by nyh** [comment]
Thanks. So I edited the issue's title to say that only ScanIndexForward is the problem.
To implement ScanIndexForward, you should begin in `alternator/executor.cc`, the `executor::query` function. There you need to check the `ScanIndexForward` JSON field and pass it into the `do_query()`. The `do_query()` function now needs to get a "reverse" flag, and needs to implement it somehow - and that will be the hard part. Scylla **does** support reading data in reverse (it needs to, as CQL has the "ORDER BY ... DESC" feature - see https://docs.scylladb.com/getting-started/dml/), so I don't think it will be impossible, but may not be easy either.

I already created a test for this feature (see above a reference to a patch in the mailing list) but I just realized I forgot to test one thing: paging. Not only "Limit" needs to work - we also need paging to work and be able to resume the reverse query and we need to test that case as well. I wonder what happens if a user changes the `ScanIndexForward` value in the middle of paging!

**Comment by nyh** [comment]
@PatrykGala just a clarification question: In your original bug report, you said you were using ".withScanIndexForward(true)". This doesn't match your explanation that you want the last results. Did you actually use false, not true?

**Comment by nyh** [comment]
Although Scylla does have the capability of iterating a partition in reverse order (used by the CQL "ORDER BY ... DESC" feature) several people warned me that this is implemented inefficiently and/or allocates a lot of memory for long partitions. Ideally, scanning a partition in reverse would be almost as fast as scanning it forward take O(1) memory (unrelated to the partition length), but apparently this may not happen.
So after implementing this feature, we should test its performance and will likely need to create a new issue for improving its performance. Unfortunately, the sstable format (neither version 2 nor 3) seems to have a length  field at the _end_ of a row, which makes it hard to skip to the previous row, but we can use the promoted index to at least move back in blocks of 64K which is "approximately" O(1) (it's not quite, because the promoted index length itself is O(N) but for partitions which aren't huge, it's small enough).

**Comment by nyh** [comment]
@slivne @eliransin please comment on whether we should backport the patch to branch 4.0. On one hand, this is a new feature, which we don't normally backport. On the other hand, the patch is very simple and low-risk, and this is a feature that we already had two users asking for, and release 4.0 hasn't come out yet - so it might be a good change to get this feature in as well.

**Comment by nyh** [comment]
Backported to 4.0 (commit b7328ff1e41a5fdde2f73c94731b9e396251b91b) for reasons described above. No other backports needed.

**Comment by nyh** [comment]
"Backport candidate" label was re-added after I manually removed it, @penberg do you have any idea why? Anyway, removing it again.
