### ISSUE TITLE
replicate permission on index

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#5205]
Create a table and an index on it... then grant MODIFY permission to a role on the main table.
Now when inserting, you get a permission denied because you cannot MODIFY the index.

Workaround : grant MODIFY permissions explicitly on indexes
Fix: inherit the permission on index from table?

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by tarzanek** [comment]
parent of this is https://github.com/scylladb/scylla-enterprise/issues/1074

**Comment by nyh** [comment]
We should confirm that this works as expected for both materialized view and a secondary index (which internally uses a materialized view). The Cassandra documentation https://docs.datastax.com/en/dse/5.1/cql/cql/cql_reference/cql_commands/cqlGrant.html indeed suggests that the modify permissions on the base table is all that should be required to write to that base table - even if it has materialized views.

**Comment by dekimir** [comment]
Actually, I don't think the user should have modify permissions on the view, since that would allow the user to explicitly change the view contents using CQL and thus break the link between the view and the origin table.  Instead, I think we should simply omit any permissions checks on the views when the origin table is modified.  I intend to fix this by reversing 65535b3444a5e13cbff3ed889dbce6a8307cd166.

Separately, we may want to strictly forbid GRANTing MODIFY on any view to anyone, because views should only be modified internally, in sync with the origin table.

**Comment by nyh** [comment]
This patch is already in branch 4.0. Probably needs backporting to additional branches.

**Comment by avikivity** [comment]
All active branches have it.
