### ISSUE TITLE
describe system is not working

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#525]
describe system is supposed to return a description of system keyspace. Currently, the command 'describe system' returns the following: 'system' not found in keyspaces

**Comment by tgrabiec** [comment]
Bisected to commit 2439a2a982eda399ed2066a3fe319ec02b2c264b
Author: Asias He <asias@scylladb.com>
Date:   Tue Oct 27 09:04:01 2015 +0800

    gossip: Simplify get_live_members
    
    _live_endpoints is replicated to call cores. No need to query on core 0.

**Comment by asias** [comment]
Going back more commits, I still see the issue with

```
commit 42a5c8b92ea2587ad466030adb8dbdf05bc79bb8
Merge: 3a38675 a772938
Author: Avi Kivity <avi@scylladb.com>
Date:   Tue Oct 27 15:04:44 2015 +0200

    Merge "CQL request load balancing" from Pekka
```


cqlsh> DESCRIBE system;

'system' not found in keyspaces
cqlsh> DESCRIBE tables;


It is cql related. @penberg can you take a look?

**Comment by asias** [comment]
When I connect cql to scylla, I saw:

Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.

**Comment by asias** [comment]
42a5c8b Merge "CQL request load balancing" from Pekka ---------->>>> bad
a772938 transport/server: Round-robin CQL request load balancing
ed0607c transport/server: Merge client state changes in process_request()
4641dff service: Copy client state to query state
27c678b transport/server: Use bytes_view instead of moving temporary buffer around
4482406 transport/server: Write response from process_request()
3b6eba1 transport/server: Remove _query_states from connection
3884f1c transport/server.cc: Fix formatting glitch
3a38675 tests::cql_test_env: set broadcast address
0754e9a Merge "Even more commitlog fixes" from Calle ----->>>>> works fine
f46cba7 sstable: simplify key reader

Tried the following commit without the cql load balancing series: 

```
commit 0754e9a34d81ce6e0cf28ba254a8bb8eef229b50
Merge: f46cba7 6dc6b40
Author: Avi Kivity <avi@scylladb.com>
Date:   Tue Oct 27 12:16:20 2015 +0200

    Merge "Even more commitlog fixes" from Calle
```

I see no 
```
Warning: schema version mismatch detected; check the schema versions of your nodes in system.local and system.peers.
```
and describe works fine.

```
$ cqlsh
Connected to cluster101 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh> DESCRIBE tables;

Keyspace system
---------------
peers             schema_triggers   batchlog                 local
range_xfers       sstable_activity  size_estimates           hints
schema_keyspaces  peer_events       compaction_history
schema_columns    schema_usertypes  compactions_in_progress
"IndexInfo"       paxos             schema_columnfamilies
```

**Comment by penberg** [comment]
@asias, load balancing is disabled by default, but perhaps the timestamp merging logic is broken and schema mutations receive broken timestamps:

https://github.com/scylladb/scylla/commit/4641dfff24a4bdad93403f801dee6efc6f924d8c

Ping @avikivity

**Comment by penberg** [comment]
BTW, @pdziepak fixed a timestamp issue in tests:

https://github.com/scylladb/scylla/commit/6e5916161ce65a4bcf9c60d2c4247f7f46d47456

Perhaps my initial patch missed similar case in server code.

**Comment by tgrabiec** [comment]
It's likely because `query_processor::internal_state::_cs` is not updated and `query_processor::internal_state::next_timestamp()` returns too small value. And in `save_system_keyspace_schema()` the delete still shadows data created by `make_create_keyspace_mutations()`.
