### ISSUE TITLE
CQL unit testing is a pain in the neck

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#5272]
Consider the following simple test:
```
SEASTAR_TEST_CASE(test_insert_json_null_frozen_collections) {
    return do_with_cql_env_thread([] (cql_test_env& e) {
        e.execute_cql("create type ut (a int, b int)").get();

        e.execute_cql(
            "CREATE TABLE collections ("
                "    k int primary key,"
                "    m frozen<map<int, int>>,"
                "    s frozen<set<int>>,"
                "    l frozen<list<int>>,"
                "    u frozen<ut>"
                ");").get();

        e.require_table_exists("ks", "collections").get();

        e.execute_cql("INSERT INTO collections JSON '{\"k\": 0}'").get();

        assert_that(e.execute_cql("SELECT JSON * FROM collections WHERE k = 0").get0()).is_rows().with_rows({
            {
                utf8_type->decompose(
                    "{\"k\": 0, "
                    "\"m\": null, "
                    "\"s\": null, "
                    "\"l\": null, "
                    "\"u\": null}"
                )
            }
         });
    });
}
```

Here's how it fails:
```
unknown location(0): ESC[4;31;49mfatal error: in "test_insert_json_null_frozen_collections": std::runtime_error: row 0 differs, expected [7b226b223a20302c20226d223a206e756c6c2c202273223a206e756c6c2c20226c223a206e756c6c2c202275223a206e756c6c7d] got [7b226b223a20302c20226c223a206e756c6c2c20226d223a206e756c6c2c202273223a206e756c6c2c202275223a206e756c6c7d]ESC[0;39;49m
```

very helpful. :/
(in human terms: the fields were printed in different order)

**Comment by tgrabiec** [comment]
`std::ostream& operator<<(std::ostream& os, const result_message::rows& msg)` from result_message.cc should use type info in _metadata to format cell values using `abstract_type::to_string()`.

**Comment by psarna** [comment]
And for a quick workaround before this issue is solved, `xxd -p -r` works great for text columns :)
```bash
echo 7b226b223a20302c20226d223a206e756c6c2c202273223a206e756c6c2c20226c223a206e756c6c2c202275223a206e756c6c7d | xxd -p -r
{"k": 0, "m": null, "s": null, "l": null, "u": null}
```

**Comment by kbr-** [comment]
I'd add more to this issue, because it's just not about running the tests and checking how they fail. It's also about writing them. If you try to write anything remotely complicated involving CQL, you'll soon want to kill yourself.

Consider the following example. Some time ago I was writing tests for user types. I wanted to have a simple test which inserts a bunch of rows with UDT columns where some fields are null, then updates some of these fields, and queries the DB to check if the changes were applied as expected.   Here's a part of the test:

```
        auto ut = user_type_impl::get_instance("ks", to_bytes("ut"),
                    {to_bytes("a"), to_bytes("b"), to_bytes("c")},
                    {int32_type, utf8_type, long_type}, true);

        auto int_null = data_value::make_null(int32_type);
        auto text_null = data_value::make_null(utf8_type);
        auto long_null = data_value::make_null(long_type);

        auto mk_row = [&] (int k, const std::vector<data_value>& vs) -> std::vector<bytes_opt> {
            return {int32_type->decompose(k), ut->decompose(make_user_value(ut, user_type_impl::native_type(vs)))};
        };

        auto mk_null_row = [&] (int k) -> std::vector<bytes_opt> {
            return {int32_type->decompose(k), {}};
        };

        e.execute_cql("create type ut (a int, b text, c bigint)").discard_result().get();
        e.execute_cql("create table cf (a int primary key, b ut)").discard_result().get();

        e.execute_cql("insert into cf (a, b) values (1, {a:1, b:'text1', c:1})").discard_result().get();
        e.execute_cql("insert into cf (a, b) values (2, null)").discard_result().get();
        e.execute_cql("insert into cf (a, b) values (3, {a:null})").discard_result().get();

        before_and_after_flush(e, [&] {
            assert_that(e.execute_cql("select * from cf where a = 2").get0()).is_rows().with_rows_ignore_order({
                mk_null_row(2),
            });
        });

        e.execute_cql("update cf set b.b = null where a in (2,3)").discard_result().get();

        before_and_after_flush(e, [&] {
            assert_that(e.execute_cql("select * from cf where a in (2, 3)").get0()).is_rows().with_rows_ignore_order({
                mk_null_row(2),
                mk_null_row(3),
            });
        });

        e.execute_cql("update cf set b.b = 'text' where a = 1").discard_result().get();
        e.execute_cql("update cf set b.a = 2 where a = 2").discard_result().get();
        e.execute_cql("update cf set b.c = 2 where a = 2").discard_result().get();
        e.execute_cql("update cf set b.c = 3 where a = 3").discard_result().get();

        before_and_after_flush(e, [&] {
            assert_that(e.execute_cql("select * from cf").get0()).is_rows().with_rows_ignore_order({
                mk_row(1, {1, "text", int64_t(1)}),
                mk_row(2, {2, text_null, int64_t(2)}),
                mk_row(3, {int_null, text_null, int64_t(3)}),
            });
        });
```

that's a lot of boilerplate for a simple test. Look at all those helpers I had to create to make the test readable: `int_null`, `mk_row`, `mk_null_row`. And it's a pain that I need to define the type (`auto ut = user_type_impl::get_instance(...)`). Later in the test I wanted to have another type so I had to create another bunch of helpers
```
        auto ut_inner = user_type_impl::get_instance("ks", to_bytes("ut_inner"),
                    {to_bytes("a"), to_bytes("b")},
                    {int32_type, int32_type}, false);

        auto ut_inner_null = data_value::make_null(ut_inner);

        auto mk_ut_inner_val = [&] (const std::vector<data_value>& vs) -> data_value {
            return make_user_value(ut_inner, user_type_impl::native_type(vs));
        };
```

Here's another test that I wrote:
```
        auto ut = user_type_impl::get_instance("ks", to_bytes("ut"),
                    {to_bytes("a"), to_bytes("b"), to_bytes("c")},
                    {int32_type, utf8_type, long_type}, true);

        auto execute_prepared = [&] (const sstring& cql, const std::vector<cql3::raw_value>& vs) {
            auto id = e.prepare(cql).get0();
            e.execute_prepared(id, vs).discard_result().get();
        };

        auto query_prepared = [&] (const sstring& cql, const std::vector<cql3::raw_value>& vs) {
            auto id = e.prepare(cql).get0();
            return e.execute_prepared(id, vs).get0();
        };

        auto mk_int = [] (int x) {
            return cql3::raw_value::make_value(int32_type->decompose(x));
        };

        auto mk_ut = [&] (const std::vector<data_value>& vs) {
            return cql3::raw_value::make_value(ut->decompose(make_user_value(ut, vs)));
        };

        auto mk_tuple = [&] (const std::vector<data_value>& vs) {
            auto type = static_pointer_cast<const tuple_type_impl>(ut);
            return cql3::raw_value::make_value(type->decompose(make_tuple_value(type, vs)));
        };

        auto mk_ut_list = [&] (const std::vector<std::vector<data_value>>& vss) {
            std::vector<data_value> ut_vs;
            for (const auto& vs: vss) {
                ut_vs.push_back(make_user_value(ut, vs));
            }

            const auto& ut_list_type = list_type_impl::get_instance(ut, true);
            return cql3::raw_value::make_value(
                    ut_list_type->decompose(make_list_value(ut_list_type, list_type_impl::native_type(ut_vs))));
        };

        auto text_null = data_value::make_null(utf8_type);
        auto long_null = data_value::make_null(long_type);

        auto mk_row = [&] (int k, const std::vector<data_value>& vs) -> std::vector<bytes_opt> {
            return {int32_type->decompose(k), ut->decompose(make_user_value(ut, user_type_impl::native_type(vs)))};
        };

        auto mk_null_row = [] (int k) -> std::vector<bytes_opt> {
            return {int32_type->decompose(k), {}};
        };

        e.execute_cql("create type ut (a int, b text, c bigint)").discard_result().get();
        e.execute_cql("create table cf (a int primary key, b ut)").discard_result().get();

        execute_prepared("insert into cf (a, b) values (?, ?)", {mk_int(1), mk_ut({1, "text1", long_null})});
        execute_prepared("insert into cf (a, b) values (?, ?)", {mk_int(2), mk_ut({2, text_null, int64_t(2)})});
        execute_prepared("insert into cf (a, b) values (?, ?)", {mk_int(3), mk_ut({})});

        assert_that(e.execute_cql("select * from cf").get0()).is_rows().with_rows_ignore_order({
            mk_row(1, {1, "text1", long_null}),
            mk_row(2, {2, text_null, int64_t(2)}),
            mk_null_row(3),
        });

        assert_that(query_prepared("select * from cf where b in ? allow filtering", {mk_ut_list({{1, "text1", long_null}, {}})}))
                .is_rows().with_rows_ignore_order({
            mk_row(1, {1, "text1", long_null}),
            mk_null_row(3),
        });

        execute_prepared("insert into cf (a, b) values (?, ?)", {mk_int(4), mk_tuple({4, "text4", int64_t(4)})});
        assert_that(e.execute_cql("select * from cf where a = 4").get0()).is_rows().with_rows_ignore_order({
            mk_row(4, {4, "text4", int64_t(4)}),
        });

        auto mk_longer_tuple = [&] (const std::vector<data_value>& vs) {
            auto type = tuple_type_impl::get_instance({int32_type, utf8_type, long_type, int32_type});
            return cql3::raw_value::make_value(type->decompose(make_tuple_value(type, vs)));
        };

        BOOST_REQUIRE_EXCEPTION(
            execute_prepared("insert into cf (a, b) values (?, ?)", {mk_int(4), mk_longer_tuple({4, "text4", int64_t(4), 5})}),
            exceptions::invalid_request_exception,
            exception_predicate::message_equals("User Defined Type value contained too many fields (expected 3, got 4)"));
    });

```

3/4 of the test is boilerplate!

Maybe some of the patterns here could be refactored out into some framework (like `mk_whatever` for some common `whatever`s).

But what would be much better is something that combines the ease of writing of dtests with the speed and utility of unit tests. Maybe tests written in python that execute on one node and are ran from the test.py script.

**Comment by avikivity** [comment]
@kostja had a nice tool that had tests written in .cql (and compared against cqlsh output). Those are certainly more fun to write.

Perhaps we can have a lua adapter (once that's merged) that allows interacting with the server via lua, but in-process and bypassing the transport layer.

**Comment by kostja** [comment]
Yes, I'm working on moving http://github.com/kostja/yacht to python ./test.py (which is not easy since I need to be careful to not break things).

**Comment by dekimir** [comment]
@kbr- I've been adding some sporadic improvements that make test-writing considerably less painful:
https://github.com/dekimir/scylla/blob/restrictions-rewrite-v7/test/boost/restrictions_test.cc#L799

**Comment by nyh** [comment]
This is an old issue. Since then two developments happened which make the C++ CQL unit tests feel modern almost as much as the Flintstone's cars:

1. @kostja's textual CQL tests (test/cql) where a test is just a CQL request, and its expected output.
2. Alternator's tests, written in Python and run against an actual real-life Scylla executable. These tests currently use the DynamoDB API, not CQL, but can easily be extended to also do CQL tests in Python.

I personally prefer the second approach, but opinions differ, and both of these new testing frameworks really make testing great again! We wrote 10,000 lines of test code for Alternator, and it didn't feel more than 1,000 ;-)

**Comment by dekimir** [comment]
> Since then two developments happened which make the C++ CQL unit tests feel modern

Actually, three developments happened.  Thank you for mentioning the other two.

The downside of test/cql is that it doesn't do prepared statements.  The downside of alternator-test for CQL is that it doesn't exist. :)

**Comment by nyh** [comment]
@dekimir what is the third one - your "sporadic improvements"? Your use of the word "sporadic" made me think you did not think it was a satisfactory solution?

Anyway, it's actually **very easy** to add CQL testing in Python like alternator-test, I can probably jumpstart this approach in just a few hours. The run script (test/alternator/run) already exists, and all you need to do is to write tests in Python using the CQL driver and pytest. I never ended up doing this because I'm not currently writing CQL tests, but if you are interested in using this approach I'll be happy to create the first test for you and let you expand it from there.

**Comment by dekimir** [comment]
> @dekimir what is the third one - your "sporadic improvements"? Your use of the word "sporadic" made me think you did not think it was a satisfactory solution?

I just meant that I've been adding improvements incrementally, while working on other stuff.  But it should be obvious how much easier it is today to add a CQL unit test because of `cquery_nofail`, `require_rows`, one-letter decomposer functions, etc.  Just see my link above and contrast it to the examples given upthread.  It's nowhere near as bad today as it was a year ago.

> Anyway, it's actually **very easy** to add CQL testing in Python like alternator-test,

IOW, I am correct in saying that it doesn't exist (today).  I'm sure it can be jumpstarted quickly, though without parallel execution and with notable challenges to debuggability that I've outlined in a previous discussion.  That discussion hasn't concluded (to my knowledge) and perhaps we should endeavour to conclude it instead of reigniting it in many divergent places.

**Comment by kbr-** [comment]
@dekimir 

Looks better indeed, but still, the most painful thing for me, which is defining all these types and defining helpers for value decomposition, is still there :(
```
        auto bound_tuples = [] (std::vector<std::tuple<int32_t, float>> tuples) {
            const auto tuple_type = tuple_type_impl::get_instance({int32_type, float_type});
            const auto list_type = list_type_impl::get_instance(tuple_type, true);
            const auto tvals = tuples | transformed([&] (const std::tuple<int32_t, float>& t) {
                return make_tuple_value(tuple_type, tuple_type_impl::native_type({std::get<0>(t), std::get<1>(t)}));
            });
            return list_type->decompose(
                    make_list_value(list_type, std::vector<data_value>(tvals.begin(), tvals.end())));
        };
```

The nicest thing IMO is if we had dtest-like tests in Python, so each retrieved row is a list/tuple of values, each of the appropriate type (according to the table specification). Which is what @nyh suggests, if I understand correctly. I think dynamic typing helps a lot here.

Comparing CQL output with expected text simply won't do. In almost every test I wrote, I needed to do some computation. For example, I would like to take the current clock time and perform a `using timestamp` insert. Or I would like to generate (huge) input randomly, and then take the output of a `select` and perform an aggregation to calculate some statistics, or simply check whether some invariant is satisfied on each row.

**Comment by dekimir** [comment]
> the most painful thing for me, which is defining all these types and defining helpers

Agreed, though a lot of the helper code can be generalized and factored out into cql_assertions.hh.  I do a bit of that almost every time I touch the testing code.

> Which is what @nyh suggests, if I understand correctly.

Yes, our views are slowly converging on an email thread.  I might send out an RFC for it one of these days, when I catch a spare moment.

> Comparing CQL output with expected text simply won't do.

... for your usecase.  But it seems to work well enough for a lot of other Scylla usecases _and_ most other database/compiler projects.  I'm envisioning a solution with query results coming back as Python lists, but with a mixin class that does blind comparison; you can build a custom comparator if you need it, but the default makes it as simple as cql_repl is today.

**Comment by nyh** [comment]
> > Comparing CQL output with expected text simply won't do.
> 
> ... for your usecase. But it seems to work well enough for a lot of other Scylla usecases _and_ most other database/compiler projects. I'm envisioning a solution with query results coming back as Python lists, but with a mixin class that does blind comparison; you can build a custom comparator if you need it, but the default makes it as simple as cql_repl is today.

I strongly agree with Kamil, though since some people (such as @kostja and you) prefer the textual method, I don't think it should be outlawed. I just don't understand why you or anyone *prefers* it.

The benefits of a writing tests in a programming language - in Python or the C++ tests which started this thread - go beyond just being able to do calculations. In my view, the biggest benefit of writing tests in a programming language is **readability**.  Readability means your ability to go back to a test you wrote a month ago (or someone else wrote a month ago), and understand why this test fails today - or fix or expand the test.

Here are just a few reasons why programming languages make more readable tests than than text-diffing:

1. If we have several related tests - e.g., testing the same feature with 10 different parameters - they may be a loop inside one test, or even if not a loop, they may be tested in one function. So the reader will see all of them together in one loop and understand they are all testing the same thing. With text files, you may see 10 different tests and not realize they are in fact testing the same feature with 10 different parameters. (comments in the text file might help, but they can only go as far when you have hundreds of tests which are variants of the same thing with different parameters).

2. Many tests require setting up some data. It doesn't have to be a huge amount like Kamil said, it can even be just 20 items with consecutive indexes. With a programming language, this is a loop - it's clear what it does, and easy to change - e.g., maybe a month from now I'll discover this test needs 30 items instead of 20, or that item needs another column. With text files, the reader has no idea how the twenty random-looking INSERT statements in the text file were created, and it's not easy to change them.

3. When a test fails, it's much easier to understand why it failed when there is an assert in a programming language than understand a diff. Let me give you one small example to make it clear. Imagine I have a test for the "BEGINS_WITH" operator. I write a bunch of rows to the table,  and then do the BEGINS_WITH("x") query. The check whether this test was successful is easy: the response should contain all and only the items which begin with "x". This is what I would do in code. But in text files? The test author will run it once, **manually** check that all the results with x were returned, and "canonize" (save) this output. If a month from now, I get an error - a diff saying that the output now contains the word "zebra", I have no idea what's wrong with this. I need to really understand what the test does until I can figure out - oh, "zebra" is wrong because it doesn't start with an "x". Which is exactly what an assert() in a programming language would have told me immediately.

**Comment by dekimir** [comment]
> I strongly agree with Kamil, though since some people (such as @kostja and you) prefer the textual method, I don't think it should be outlawed. I just don't understand why you or anyone _prefers_ it.

Actually, I don't prefer it.  I just keep seeing it again and again across many projects, so I conclude that a) it's clearly valid, and b) it's worth my while to understand why.  I suspect those who rely on it would agree with you that readability is paramount, but they consider loops, test harnesses, intricate asserts, and all other collars around the actual input and output to be readability-reducing noise.

**Comment by kbr-** [comment]
By saying "won't do", I meant "it's not sufficient". I agree that it's necessary.
But it's also necessary to have more complex tests written in a general programming language to perform calculations.
So we need both options, and use whichever's better for the use case at hand.

**Comment by tzach** [comment]
@kbr- UX is for **User** Experience not Developer Experience (DX?)

**Comment by kbr-** [comment]
What I had in mind is that developers are users of the testing framework. But yeah, the label is probably for "end-user" experience only.

**Comment by nyh** [comment]
A lot of improvements made CQL unit testing less a pain in the neck. We have some better functions for use in the C++ unit tests (@dekimir is the expert on those), we have @kostja's textual "cql tests", and my Python-based cql-pytest. I hope you'll find at least one of these to be less of a "pain in the neck" than it used to be, and we can close this issue?

**Comment by kbr-** [comment]
It looks like it. Thanks to everyone who improved the CQL unit testing experience!
