### ISSUE TITLE
Question about Partition Range

### ISSUE THREAD

**Issue by fanvanzh** [scylladb/scylla#5293]
Hi:
   I am trying to make Scylla support geospatial data, which is geopoint<x double, y double>.
   Because the geopoint is random double value, I use geohash(geopoint) which is an int64 as the pk token.

   This is my table:
```
   create type geopoint(x double, y double);
   create table point( id int, geom frozen<geopoint>, primary key( geom, id));
```

What my problem is :
```
   auto bound0 = dht::ring_position::starting_at(_token); 
   auto bound1 = dht::ring_position::ending_at(_token); 
   // _token is int64 token, without key value
   auto rp = dht::partition_range::make(bound0,bound1)
   partition_range.push(rp)
```
  this code can`t work correctly, as It does not read the correct records. 

  So I want to know:
  If I only has the token value( int64 type), can I read data from the storage?

**Comment by avikivity** [comment]
It's better to use the developer mailing list for questions, not the bug tracker.

The code you wrote is correct, but note that the token is a hash (murmur3) of the partition key, it's not the geohash of the partition key.

To achieve what you want we'll need per-table partitioners instead of a global partitioner (`dht::global_partitioner()`). Even that is not perfect because geohash doesn't distribute things as well as murmur3 so we'll get hot shards.

**Comment by fanvanzh** [comment]
thanks，avikivity 。
I will move this question to mailing list soon。

so scylla do not have "per-table partitioners" yet?
