### ISSUE TITLE
The configration items related to Redis API should be described clearly

### ISSUE THREAD

**Issue by fastio** [scylladb/scylla#5335]
The configuration items related to redis are as follows:

    redis_transport_port;
    redis_transport_port_ssl;
    enable_redis_protocol;
    redis_read_consistency_level;
    redis_write_consistency_level;
    redis_default_database_count;
    redis_keyspace_options;

These should be described clearly.

#5132

**Comment by nyh** [comment]
Some questions I had while reading the code, and should probably be answered as code comments or in redis.md - or resolved by modifying the code (all of these are from my previous comments on your original pull request):

1. "enable_redis_protocol" - What does this "enable"? The transport_port? The transport_port_ssl? Both?
Because of this ambiguity, in Alternator we decided to have have "--alternator_port" and "--alternator_https_port", which need to be set (no default value) to enable the specific listener - and we don't have a separate "--enable-alternator" option because it's not needed.

2. "redis_transport_port_ssl" - is this actually in use? Isn't its default (9142) a mistake because Scylla already does something else on this port?

3. "redis_read/write_consistency_level" - mention its default, and why. I wonder if the current default (ANY/ONE) is a great idea, or a safer default should be LOCAL_QUORUM.

4. "redis_default_database_count" - maybe this is the "max" database count, not "default" database count? Or maybe I'm misunderstand what you mean here by "default" (can it be modified later to be different from this "default"?)

5.  "redis_keyspace_option" - the description string for this option isn't clear - it is currently "Enable redis protocol, list of properties of replication of redis keyspace." - but does it actually "enable redis protocol"? we have a different option with that name. Also, we need to spell out when does this option to change keyspace options takes effect - the very first node to boot, probably, and the others' options will have to be ignored, because the keyspace already exists? If so, I think this should be said explicitly somewhere.

**Comment by fastio** [comment]
@nyh Thanks for your reply.

> 1. "enable_redis_protocol" - What does this "enable"? The transport_port? The transport_port_ssl? Both?
> Because of this ambiguity, in Alternator we decided to have have "--alternator_port" and "--alternator_https_port", which need to be set (no default value) to enable the specific listener - and we don't have a separate "--enable-alternator" option because it's not needed.

Indeed, the `enable_redis_protocol is unnecessary. I think it's better to replace them with`--redis_port and `--redis_ssl_port.

> 2. "redis_transport_port_ssl" - is this actually in use? Isn't its default (9142) a mistake because Scylla already does something else on this port?

Redis does not natively support SSL, but the Redis service in the public cloud does. And it's important feature for users. So we should support it.

[Redis encryption] (https://redis.io/topics/encryption)

The default port's value 9142 is totally wrong. We should use anther one. I'll fix it.

> 3. "redis_read/write_consistency_level" - mention its default, and why. I wonder if the current default (ANY/ONE) is a great idea, or a safer default should be LOCAL_QUORUM.

The current default value （ANY/ONE）is not a grreat idea. It should be LOCAL_QUORUM.
I'll fix it. 

> "redis_default_database_count" - maybe this is the "max" database count, not "default" database count? Or maybe I'm misunderstand what you mean here by "default" (can it be modified later to be different from this "default"?)

In Redis, the count of databases is configurable, and the default value is 16.  
We should rename the `redis_default_database_count to `redis_database_count.

> "redis_keyspace_option" - the description string for this option isn't clear - it is currently "Enable redis protocol, list of properties of replication of redis keyspace." - but does it actually "enable redis protocol"? we have a different option with that name. Also, we need to spell out when does this option to change keyspace options takes effect - the very first node to boot, probably, and the others' options will have to be ignored, because the keyspace already exists? If so, I think this should be said explicitly somewhere.

Yes, this option is used by the first node in the boot phase when the keyspace is not exists to create 
keyspaces for Redis.

It should be described explicitly. I'm working arond it.
