### ISSUE TITLE
case-sensitive of role name is not consistent 

### ISSUE THREAD

**Issue by wuzm2k05** [scylladb/scylla#5383]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details* 1 node cluster
Scylla version (or git commit hash): 3.1.1
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL

I created a role:
cassandra@cqlsh> create ROLE   AAA   WITH PASSWORD = '123456' and LOGIN = true;

However I cannot login with this role.
$ cqlsh -u AAA -p 123456
Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="Username and/or password are incorrect"',)})

$cqlsh -u aaa -p 123456
success!!

From my understanding, scylla store the role name as lower case internally, but when login it would be case sensitive.
I think from user's perspective, if I create a role name with upper case, then I hope I can login with exactly same name which is upper case. 

Thanks!
Zhaoming

**Comment by eliransin** [comment]
@wuzm2k05 , the behavior you see is intentional. This is to achieve parity with Cassandra that
behave in the exact same way. If you would like to preserve the case of your login, you need to quote your login like so:
`create ROLE 'AAA' WITH PASSWORD = '123456' and LOGIN = true;`
Please notice the quotes surrounding the user name.
You can also read about it [here](https://docs.datastax.com/en/archived/cql/3.3/cql/cql_reference/cqlCreateRole.html) (role_name) section.

**Comment by eliransin** [comment]
@wuzm2k05  i am closing the issue since it is not a bug.
If you have any more questions about this, you are welcome to comment
or reopen the issue.
