### ISSUE TITLE
scylla-3rdparty for debian10 doesn't exist

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5548]
*Installation details*
Scylla version (or git commit hash): master
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 10

### Description

scylla-3rdparty for debian10 (buster) doesn't exist.
Expected: http://download.opensuse.org/repositories/home:/scylladb:/scylla-3rdparty-buster/Debian_10.0/

http://download.opensuse.org/repositories/home:/scylladb:/

![image](https://user-images.githubusercontent.com/309708/71669959-6080d400-2da9-11ea-92af-a845f8435b16.png)

@syuu1228  @hagitsegev @avikivity

**Comment by syuu1228** [comment]
3rdparty repo is not used from Scylla-3.1 and above, since we merged relocated package.
Why we still haven't deleted the repo from our .repo/.list file is because we need it to use gdb-7 (scylla-gdb) on older distributions.
Since Debian 10 is new enough and has gdb-8, so I think we can just use distribution provided gdb.
