### ISSUE TITLE
The following signatures were invalid: EXPKEYSIG 17723034C56D4B19 ScyllaDB Package Signing Key 2018 <security@scylladb.com>

### ISSUE THREAD

**Issue by vquintin** [scylladb/scylla#5549]
_Installation details_
Scylla version (or git commit hash): 2.3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 9

This [key](https://keyserver.ubuntu.com/pks/lookup?search=0x17723034c56d4b19&fingerprint=on&op=index) used to signed the `scylladb-2.3` package has expired on 2020/01/01.

Could you please update it ?

**Comment by vquintin** [comment]
It seems a new key with ID `5E08FBD8B5D6EC9C` was published on [ubunte keyserver](http://keyserver.ubuntu.com/pks/lookup?search=security%40scylladb.com&fingerprint=on&op=index).
The package signature should be updated anytime soon.

**Comment by slivne** [comment]
@vquintin thanbks for reporting, indeed we had an issue. We have extended the key lifetime you should be able to use the existing key - please update if there is an issue 

I am closing this issue AFAIK the issue has been resolved

**Comment by thedim-witted** [comment]
Hey, I am getting a similar error where it's saying that the public key is not available

 GPG error: https://downloads.scylladb.com/downloads/scylla/deb/debian-ubuntu/scylladb-6.0 stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 87722433EBB454AE

I tried the official key provided on the website and also the above stated. Both seems to be expired. Where can I find a new key?

**Comment by thedim-witted** [comment]
Nvm. Found the latest one on the ubuntu keyserver: [491c93b9de7496a7](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x491c93b9de7496a7)
