### ISSUE TITLE
Scylla fails to store (or retrieve) values if static columns are involved

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#556]
Reproducer:

    CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    CREATE TABLE lmr_test_keyspace.table_foo ( k int, p int, s int static, v int, PRIMARY KEY (k, p));
    INSERT INTO lmr_test_keyspace.table_foo (k, s) VALUES (0, 42);
    SELECT * FROM lmr_test_keyspace.table_foo;

Expected result:

    cqlsh> SELECT * FROM lmr_test_keyspace.table_foo;

    k | p | s | v
    ---+---+---+---
    0, null, 42, null

    (1 row)

Actual result:

    cqlsh> SELECT * FROM lmr_test_keyspace.table_foo;

     k | p | s | v
    ---+---+---+---

    (0 rows)

**Comment by tgrabiec** [comment]
It's probably because of 13189c317605498a2b830cd5bcf1ab772959a626, I saw during review something which might lead to this.

**Comment by dbathgate** [comment]
Also if a static column is created on a collection then it completely bricks cqlsh

```
[root@ip-10-0-0-206 ~]# cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.

cqlsh> use test;
cqlsh:test> drop table table1;
cqlsh:test> CREATE TABLE table1 (
        ... key text,
        ... column1 text,
        ... column2 text,
        ... column3 set<text> static,
        ... PRIMARY KEY (key, column1));

cqlsh:test>
cqlsh:test> quit

[root@ip-10-0-0-206 ~]# cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': ValueError("Don't know how to parse type string u'org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType))': list index out of range",)})
```

**Comment by avikivity** [comment]
Most likely, it killed the server

**Comment by slivne** [comment]
In the case of the set<text> static column

1. We do not crash

2. the issue is that we have a bad entry in the system.schma_columnfamilies
it seems that for the set we do not write all the info.

Scylla info is

                ks |                  table1 |                   0.01 |
{"keys":"ALL","rows_per_partition":"ALL"} |
b659a4a0-8b79-11e5-9f7a-000000000000 |
["column1"] |                                              |
SizeTieredCompactionStrategy |                          {}
|
org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType))
| {"sstable_compression":"org.apache.cassandra.io.compress.LZ4Compressor"}
|                    0 | org.apache.cassandra.db.marshal.BytesType
|            null |           864000 |           null |    False
|                                            ["key"]
|
org.apache.cassandra.db.marshal.UTF8Type |                      0.1
|                       32 |               2048 |
0 |                        4 |                128 |                  0 |
99.0PERCENTILE |          null | Standard |        null



Cassandra 2.1.8 has:

            ks |                  table1 |                   0.01 |
{"keys":"ALL", "rows_per_partition":"NONE"} |
308f3230-8b7a-11e5-912a-494a6a685fc9 |
["column1"] |                                        |
org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy
|                          {}
|
org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(636f6c756d6e33:org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)))
| {"sstable_compression":"org.apache.cassandra.io.compress.LZ4Compressor"}
|                    0 | org.apache.cassandra.db.marshal.BytesType
|            null |           864000 |           null |    False
|                                            ["key"]
|
org.apache.cassandra.db.marshal.UTF8Type |                      0.1
|                       32 |               2048 |
0 |                        4 |                128 |                  0 |
99.0PERCENTILE |          null | Standard |        null

Scylla is missing all the info on the

org.apache.cassandra.db.marshal.ColumnToCollectionType(636f6c756d6e33:org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type))

So the issues seem to be non related. I'll create a seperate bug to track
this.
