### ISSUE TITLE
cdc - cannot insert into cdc-enabled tables when running Scylla with > 1 shards

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#5582]
```
cqlsh> create keyspace ks with replication = {'class':'SimpleStrategy', 'replication_factor': 1};
cqlsh> use ks;
cqlsh:ks> create table t (a int primary key, b int) with cdc = {'enabled':'true'};
cqlsh:ks> insert into t (a, b) values (0, 0);
ServerError: Can't find a column family t_scylla_cdc_desc in keyspace ks 
```

in cdc/cdc.cc, `cdc_service::impl`, I uncommented `if (engine().cpu_id() == 0)`:
```
    impl(db_context ctxt)
        : _ctxt(std::move(ctxt))
    {
        //if (engine().cpu_id() == 0) {
            _ctxt._migration_manager.register_listener(this);
        //}
    }
```
and it started working.

Tests are probably passing because they do everything on shard 0.

I'm 99,5% sure the regression was introduced in cb0117eb44979255c18005058888c2ddef19398f.

**Comment by elcallio** [comment]
Ah. Funny. This worked fine for me in manual testing, but obviously because I still managed to get "create table..." cql processed on main shard. 
However, if removing the subscription check like you did, it needs to be added instead to "on_create_column_family", since that callback is run on every shard, and we don't want to populate the desc table more than once.

**Comment by kbr-** [comment]
Can you fix it?

**Comment by elcallio** [comment]
Sure.

**Comment by nyh** [comment]
This is an ancient commit, already in all recent branches. Removing the spurious "Backport candidate" label.
