### ISSUE TITLE
new node silently fails to join when disk usage is very high within the cluster

### ISSUE THREAD

**Issue by schybbkoh** [scylladb/scylla#5602]
Hi there

**The environment:**

*Installation details*
- Scylla version: 3.0.7
- Cluster size: 23 nodes + 1 joining
- OS: Ubuntu 18.04.3 LTS

*Hardware details* 
- Platform: Azure VM
- Hardware: Standard L16s_v2 (16 vcpus, 128 GiB memory)
- Disks: 30 GB Premium SSD for the OS; 2x1.8 TB NVMe SSD for data (RAID0, 3.5 TB effectively)

**The problem:**

A new node is unable to join the cluster when the average disk usage is high within the cluster (~85%+).
The problem does not occur with lower disk usages (ie. 70%).
This has also occured before when the cluster was smaller (10-15 nodes or so).
The joining process starts as it should, but after about 5% disk being filled on the joining node (~180 GB) it stops. It does not do so momentarily, the process simply slows until there is no progress. 
The same goes for CPU usage (100% on most of the cores, then almost idle).
By tracing traffic on the network interface one can also see something similar - the joining process starts with the new node being connected to all nodes and actively streaming data from about 16 of them. And then slows down, by the end the transfers are of magnitude of Bps / kBps.
There are no failure-related logs on the joining node.
A way to restart the joining process is to look at `nodetool netstats` on the joining node and then restart scylla processes and all nodes displayed within until `nodetool netstats` shows no streams. Then the joining process runs for another 5% (ie. 5% --> 10%) and then the story repeats itself.

**The expected behaviour:**

I understand that this particular case is stretching recommended operational conditions in terms of free disk space, but I still think one of two outcomes should happen:
- new node joins with no issues
- new node does not join, but fails explicitly, instead of going in loops without a clearly logged errors

**Comment by slivne** [comment]
I do not see a reason as to why the disk space would matter - streaming should work (unless you run out of diskspace on the original cluster nodes somehow)

The version you are using is missing a fix related to streaming scylladb/scylla@cc0b4d249b95aca0d69966e8a29b2a7927869653 - this is part of later 3.0.X releases this could be the bug that causes streaming to get stuck instead of being retried on errors.

This fix is part of the 3.1 releases

Please note that 3.0 is not supported anymore 

If you still have issues post the upgrade please post a new issue and we will be happy to help.
