### ISSUE TITLE
USING TIMESTAMP value range is not checked

### ISSUE THREAD

**Issue by martin-sucha** [scylladb/scylla#5619]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2019.1.2-0.20190814.2772d525c

*Description*

CQL allows to specify `USING TIMESTAMP` clause or to specify optional default timestamp for a query in the cql protocol (that might be set using client drivers). The value for either of these is documented as microseconds since UNIX epoch.

When issuing CQL statements with `USING TIMESTAMP` clause, Scylla should return a query error in case the value is too far in the future. This can catch bugs when a client uses wrong units.

For example, if a single client uses nanosecond timestamp instead of microsecond timestamp as other clients (or Scylla coordinators) use, the client would overwrite even future updates by other clients, as the timestamps by the misbehaving client would be more than 50000 years in the future. Reverting the misbehaving client to use microseconds does not fix the issue, since data with the far-future timestamps has already been written, so to recover from that kind of client mistake, one has to either build a new table from scratch with the current timestamps or switch all other clients to use timestamp in nanoseconds.

I'm not sure what the limit value should be, but updates more than a few days in the future seem suspicious. If update timestamps in the future are a supported feature, the limit might need to be configurable.

**Comment by bhalevy** [comment]
I'm not sure a application-provided timestamp can or should be checked.

CQL allows one to use arbitrary, pure numbers as timestamps and they are compared relative to each other.

It's true that the server or client-driver do assign timestamps that are based on the current time in microseconds (and this REALLY confusing since the CQL `timestamp` data type is in milliseconds), but an application may correctly use arbitrary timestamp values if the application cares to add `USING TIMESTAMP` to all queries, so there is no true "valid range" for the query timestamp.

**Comment by bhalevy** [comment]
Also, 2150c0f7a2d56b9ea2a5607a4066c4c1c3aba40f constraints the custom timestamp to 3 days into the future.
This seems overly restrictive.  I'd understand a restriction on the timestamp value that it must be convertible to a valid timeuuid, for example, since the latter has fewer bits (and has a 10 nanoseconds resolution :)), but why can't I provisionally insert data with a timestamp in microseconds that is 1 month or 1 year into the future?

**Comment by haaawk** [comment]
Why would you need timestamp 1 month in the future @bhalevy? It seems that most of the time it's just a bug when it happens.

**Comment by bhalevy** [comment]
> Why would you need timestamp 1 month in the future @bhalevy? It seems that most of the time it's just a bug when it happens.

We need not question the application intent if we don't absolutely have to.
The point is that if 1 day into the future is acceptable, why not 1 week, or 1 month?

Why do we restrict only future timestamps and not past timestamps?

This arbitrary 3-days-into-the-future restriction just doesn't make sense....

**Comment by haaawk** [comment]
It seems that the restriction is valuable for users. It certainly makes sense in a safe mode.

Timestamps in the future seem wrong in general. I'm wondering whether we're handling them correctly at all. Data inserted with a timestamp in the future shouldn't be visible in queries until the time of that timestamp. I'm curious whether compactions and query engine handle that correctly.

**Comment by bhalevy** [comment]
> It seems that the restriction is valuable for users. It certainly makes sense in a safe mode.
> 
> Timestamps in the future seem wrong in general. I'm wondering whether we're handling them correctly at all. 

We can't avoid timestamps into the future since we don't have a global synchronized clock so the client or coordinator- generated timestamp could be larger than the replica local time.

> Data inserted with a timestamp in the future shouldn't be visible in queries until the time of that timestamp.

Not with the CQL works at the moment.  Read queries return any non-expired data, including data with future timestamps.
In theory we can extend cql to support SELECT queries USING TIMESTAMP that could use the timestamp to filter out future changes.

> I'm curious whether compactions and query engine handle that correctly.

They must.
tombstones only mask/delete data with older timestamps, and you must support keeping tombstones around while there's data written after the tombstone, so they need to coexist.

**Comment by bhalevy** [comment]
I think that the right restriction should be that the given timestamp must be convertible into a timeuuid.
We must support that for various functions and it will reject timestamps representing the current time, but wrongly given in nanoseconds.

**Comment by bhalevy** [comment]
Note that we even use pure numbers for timestamp in our unit tests.
See for example https://github.com/scylladb/scylla/blob/edd54a946350689a5032395cbdd799d21481ec39/test/boost/cql_query_test.cc#L975-L1057

They don't fit the model that the query (api) timestamp should be related to the wall clock.

**Comment by haaawk** [comment]
> > It seems that the restriction is valuable for users. It certainly makes sense in a safe mode.
> > Timestamps in the future seem wrong in general. I'm wondering whether we're handling them correctly at all.
> 
> We can't avoid timestamps into the future since we don't have a global synchronized clock so the client or coordinator- generated timestamp could be larger than the replica local time.

Yes but the assumption is all the timestamps are relatively close to the current time. Timestamps are suppose to represent real time. Using timestamp should only be used to enable reliable reties. Of course network delays and clock desynchronizations make it impossible for timestamps to be perfectly in sync but the idea is that they are close to each other.

My understanding is that if servers and clients get their clocks too much out of sync everything will go to hell anyway.

> 
> > Data inserted with a timestamp in the future shouldn't be visible in queries until the time of that timestamp.
> 
> Not with the way CQL works at the moment. Read queries return any non-expired data, including data with future timestamps.
> In theory we can extend cql to support SELECT queries USING TIMESTAMP that could use the timestamp to filter out future changes.
> 



> > I'm curious whether compactions and query engine handle that correctly.
> 
> They must.
> tombstones only mask/delete data with older timestamps, and you must support keeping tombstones around while there's data written after the tombstone, so they need to coexist.

It's not only about tombstones but any updates to the data. As the issue description points out, a single client using wrong timestamps far in the future will override all the correct clients even though the wrong timestamps are milleniums after we're all dead ;).

**Comment by haaawk** [comment]
> Note that we even use pure numbers for timestamp in our unit tests.
> See for example
> 
> https://github.com/scylladb/scylla/blob/edd54a946350689a5032395cbdd799d21481ec39/test/boost/cql_query_test.cc#L975-L1057
> 
> They don't fit the model that the query (api) timestamp should be related to the wall clock.

I think we do that just to make the tests deterministic.

**Comment by haaawk** [comment]
> I think that the right restriction should be that the given timestamp must be convertible into a timeuuid.
> We must support that for various functions and it will reject timestamps representing the current time, but wrongly given in nanoseconds.

I guess it may work.

**Comment by bhalevy** [comment]
> I think we do that just to make the tests deterministic.

This is an example of an application that (ab)uses the cql semantics in a different way than your intention, and it proves that the following is not necessarily true, if the application cares to specify the timestamp on all inserts/updates/deletes:

> My understanding is that if servers and clients get their clocks too much out of sync everything will go to hell anyway.

> > I think that the right restriction should be that the given timestamp must be convertible into a timeuuid.
> > We must support that for various functions and it will reject timestamps representing the current time, but wrongly given in nanoseconds.
> 
> I guess it may work.

See related issue #5552 72e2ea47c1f085f9da65e79336bff06ded3bb488

**Comment by nyh** [comment]
Let me begin by saying that I was against the idea of this issue and its fix but not in this discussions (we had other discussions on this in the past), but several people were involved in documenting, patching and committing this fix and they do agree with its idea, so obviously there is some disagreement.

As you said (and I said in the past), Cassandra originally did not attach any units to the timestamps - the only thing that matters that is that higher numbers win: If you write some cell with timestamp=7 and later write the same cell with timestamp=8, the second write wins. There is no sense in asking whether "7" is "in the future" or things like that. Timestamps are just relative to other timestamps.

However, somehow in Scylla we came into the conclusion (which was later canonized by the authors, reviewers and committers of this patch) that timestamp **must** be a real time in microsecond resolution since the Unix epoch. I'm not sure why we came to this conclusion, or if we ever documented it (it's definitely not in https://docs.scylladb.com/getting-started/dml/). Maybe it happened because this is what server-side timestamps do. Or because this is what LWT does.

If you're wondering why this patch singles out very-far-into-the-future timestamps, well it's because we saw in more than one (though not many) cases where users **accidentally** wrote data with some very high timestamps, and then were unable to delete it and didn't understand why. The problem is that if you write some data with a timestamp 10 years into the future, and later try to delete or overwrite it with a timestamp of today, the delete or overwrite will be mysteriously ignored. This error can happen because of a misconfigured clock (I saw one such report) or a mistaken calculation in nanoseconds instead of microseconds, etc.

The other possibilities, like using small timestamps or negative timestamps, are less worrying - because they can be overwritten by any write with now's timestamp. And because Cassandra does allow these small and even negative timestamps (and our tests use small timestamps heavily), we want to keep allowing them.

**Comment by bhalevy** [comment]
If the application generates timestamps that need to compare against other client-generated or server-generated timestamps, then it needs to synchronize the cluster hosts` clocks to a reasonable degree (ntp will do).  Failing to do so is really not the database's business.

Getting the units wrong, as nanoseconds, can be safely caught with the method I proposed (checking the given timestamp is convertible to timeuuid).

If the units are wrong and are given in milliseconds or seconds, for example, we can't do much about it, given the way CQL defines the query USING TIMESTAMP.

**Comment by nyh** [comment]
@bhalevy I agree with you, but don't understand why even the "getting the units wrong as nanoseconds" is an interesting case to guard against, especially since, as you said, if we get it wrong as milliseconds it we will not be able to detect it.

The question about what happens when the timestamp is so high it cannot be represented as a timeuuid is interesting, but it doesn't prevent Cassandra from allowing even `2^63-1` as a timestamp. I'm not saying it's useful, of course.

**Comment by bhalevy** [comment]
Enforcing convertability to timeuuid is not about being interesting, but about protecting self-consistency of the metadata over CQL.

In general, If the application chose to provided timestamps into the future, I don't think it's our business to restrict it.
Certainly not to an arbitrary restriction of 3 days, that is undocumented.
I can understand a warning, or a configurable restriction, but I disagree with a hard coded, arbitrary restriction.

**Comment by nyh** [comment]
> In general, If the application chose to provided timestamps into the future, I don't think it's our business to restrict it.
> Certainly not to an arbitrary restriction of 3 days, that is undocumented.
> I can understand a warning, or a configurable restriction, but I disagree with a hard coded, arbitrary restriction.

+1

By the way, I can make this into a configurable restriction ("safe mode"), if there is interest. But I'm not sure how it should be configured - just say "true" that this restriction is enabled? Should the number "3 days" itself be configurable? Who cares if it's 3 days or 17 days? :-(

**Comment by bhalevy** [comment]
> Who cares if it's 3 days or 17 days?

Exactly.  Therefore if we offer such a configuration option it could be set by default to the current one (using a 3-days duration in microseconds - to make sure that anyone who changes it understands what it means). Allowing anyone whe cares about it to decrease or increase it if needed.

A value of `0` can be reserved to disable the restriction all together in an easy way.

**Comment by martin-sucha** [comment]
> However, somehow in Scylla we came into the conclusion (which was later canonized by the authors, reviewers and committers of this patch) that timestamp must be a real time in microsecond resolution since the Unix epoch. I'm not sure why we came to this conclusion, or if we ever documented it (it's definitely not in https://docs.scylladb.com/getting-started/dml/). Maybe it happened because this is what server-side timestamps do. Or because this is what LWT does.

It is documented for default timestamp in CQL protocol: https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L373-L378

The for `USING TIMESTAMP` in CQL, there is only [mention that the default value is in microseconds](https://cassandra.apache.org/doc/latest/cql/dml.html#update-parameters): 

> TIMESTAMP: sets the timestamp for the operation. If not specified, the coordinator will use the current time (in microseconds) at the start of statement execution as the timestamp. This is usually a suitable default.
