### ISSUE TITLE
Get the index type from the schema when creating the schema.cql file

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#5659]
When creating a snapshot, scylla generates a schema.cql file as part of the snapshot.

If the table is a view, the implementation looks in the base table to determine what type of index/view this table is.
This has a problem when dropping a table, the base table can be deleted before the snapshot if the view table and the view table will not be able to determine the index type.

An alternative is to add the index type to the schema (similar to is_view() method).
This will remove that dependency

**Comment by slivne** [comment]
@amnonh I don't understand the race condition.

You can't drop a table that has active views/indexes - you are required to remove first the views/indexes and then you can drop the base table.

Is this related to another open issue / failing dtest / unitest ?

**Comment by amnonh** [comment]
Yes but then, no.
When removing a table the implementation does parallel for each on the table and its views.
During that time, it's possible that the base table will be deleted first.
It fails https://github.com/scylladb/scylla/issues/5614

**Comment by slivne** [comment]
@nyh please review this and approve - you will be asked to review later :)

**Comment by nyh** [comment]
@slivne approve an issue? I'll try to explain this issue in my own words.

First, some background for the problem: As you know, it is not legal in CQL to delete a base table before deleting its materialized views. Nevertheless, Cassandra decided to make it **legal** to delete a base table which still has an index - and in that case the view implementing the index is automatically dropped as well. The way this happens in practice is that the node that decided to drop the base table not only sends to the whole cluster a mutation to the schema tables to drop the base table, it also sends a second schema-table mutation to drop the index view table. These two mutations are sent together, and other nodes do not receive it in any particular order. Other nodes might start deleting both base and index-view in parallel, or delete them in any order.

For most purposes, none of the above poses a problem. A user request that needs either the base or the view will fail with an exception if it is already gone, and that is perfectly fine. We just have one specific problem with table snapsots:

Table snapshot starts *when* the table is being deleted. In the current implementation, the view table's snapshot code needs to check the base table to figure out if this view is an index, a local index, or none of the above. Because, as explained above, the view deletion can happen in parallel or even after the base table deletion, this information might be missing. This doesn't cause a crash - it is handled in the code. The snapshotting continues normally. The only bug we have is because we don't know if this view is an index or not, we don't write the snapshot's "schema file". This is what the test detects.

I think the solution is fairly simple, even though @amnonh says that Duarte was opposed to it in the past (I don't remember the history): In `schema`, we already remember whether this table is a view, and a bunch of other information about the view's properties, in a "view_info" structure, and a `is_view()` method. I suggest that similarly, we should have a schema->is_global_index(), schema->is_local_index(), and don't think this is a layering violation any more than `is_view()` is.

What is true, however, is that "view_info" actually comes from separate data stored on disk, not from the base table. However, I believe not all of it does. We have a method `initialize_base_dependent_fields()` which if I remember correctly (@amnonh please investigate) adds to view_info another piece of information that needs to be deduced from the base table. Similarly we can deduce the is_local/global_index status from the base table, without needing to save anything more to disk.  I am hoping (but didn't try to to code it) that same code which calls `initialize_base_dependent_fields()` - i.e., `table::add_or_update_view()` - could also update the indexness flags.

**Comment by denesb** [comment]
On Sun, 2020-02-02 at 14:49 -0800, nyh wrote:
> @slivne approve an issue? I'll try to explain this issue in my own
> words.
> 
> First, some background for the problem: As you know, it is not legal
> in CQL to delete a base table before deleting its materialized views.
> Nevertheless, Cassandra decided to make it legal to delete a base
> table which still has an index - and in that case the view
> implementing the index is automatically dropped as well. The way this
> happens in practice is that the node that decided to drop the base
> table not only sends to the whole cluster a mutation to the schema
> tables to drop the base table, it also sends a second schema-table
> mutation to drop the index view table. These two mutations are sent
> together, and other nodes do not receive it in any particular order.
> Other nodes might start deleting both base and index-view in
> parallel, or delete them in any order.
> 
> For most purposes, none of the above poses a problem. A user request
> that needs either the base or the view will fail with an exception if
> it is already gone, and that is perfectly fine. We just have one
> specific problem with table snapsots:
> 
> Table snapshot starts when the table is being deleted. In the current
> implementation, the view table's snapshot code needs to check the
> base table to figure out if this view is an index, a local index, or
> none of the above. Because, as explained above, the view deletion can
> happen in parallel or even after the base table deletion, this
> information might be missing. This doesn't cause a crash - it is
> handled in the code. The snapshotting continues normally. The only
> bug we have is because we don't know if this view is an index or not,
> we don't write the snapshot's "schema file". This is what the test
> detects.
> 
> I think the solution is fairly simple, even though @amnonh says that
> Duarte was opposed to it in the past (I don't remember the history):
> In schema, we already remember whether this table is a view, and a
> bunch of other information about the view's properties, in a
> "view_info" structure, and a is_view() method. I suggest that
> similarly, we should have a schema->is_global_index(), schema-
> >is_local_index(), and don't think this is a layering violation any
> more than is_view() is.


Why not have an enum instead of a dozen bools?
What is true, however, is that "view_info" actually comes from separate data stored on disk, not from the base table. However, I believe not all of it does. We have a method initialize_base_dependent_fields() which if I remember correctly (@amnonh please investigate) adds to view_info another piece of information that needs to be deduced from the base table. Similarly we can deduce the is_local/global_index status from the base table, without needing to save anything more to disk.  I am hoping (but didn't try to to code it) that same code which calls initialize_base_dependent_fields() - i.e., table::add_or_update_view() - could also update the indexness flags.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/scylladb/scylla/issues/5659?email_source=notifications\u0026email_token=AAKTFWKOZCA7VYZST4LZYILRA5EX5A5CNFSM4KMPFW32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKSDHGA#issuecomment-581186456",
"url": "https://github.com/scylladb/scylla/issues/5659?email_source=notifications\u0026email_token=AAKTFWKOZCA7VYZST4LZYILRA5EX5A5CNFSM4KMPFW32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKSDHGA#issuecomment-581186456",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by amnonh** [comment]
I actually started with an enum implementation, realized that I'll get the same comment this way or the other and just stash it locally, so I can send it with the next version.

**Comment by slivne** [comment]
@amnonh / @nyh was this resolved - if so please close if not please clarify what should be done and we can assign, there is a long description with multiple options - yet no decision at the end.

AFAIK we fixed the order of deletion / views/index and only then base so there should not be an issue anymore

**Comment by slivne** [comment]
@amnonh / @nyh ping

**Comment by nyh** [comment]
@slivne I think this was "resolved" in a different way, by making sure that when a node handles schema changes it received from other nodes, it handles view deletions *before* handling other deletions. This was done in commit 923a46030b2c09ed105f903cb3247a567c479120 by @eliransin to fix issue #5614.
After that fix, theoretically the current code to get the index type - which assumes that if the view table is alive the base is still alive as well - should be fine, and doesn't need to be fixed and this issue can be closed. Byt @amnonh please confirm.

**Comment by slivne** [comment]
Closing the issue
