### ISSUE TITLE
Allow to configure which allocator to use

### ISSUE THREAD

**Issue by thedrow** [scylladb/scylla#570]
jemalloc or tcmalloc might help improve the performance of scylla.
In order to check that we need to allow to configure different allocators during build time.
These can be used when they are available on the platform scylla is being compiled on.

**Comment by thedrow** [comment]
Seems like it already exists in the runtime configuration: https://github.com/scylladb/scylla/blob/master/conf/scylla.yaml#L362 but I could not find it in the documentation.

**Comment by nyh** [comment]
Scylla uses Seastar, which already includes its own highly tuned memory allocator, and doesn't suffer from locking issues because memory is allocated separately per thread (it has a sharded design). So I think this issue should be closed (I can't do it myself because on github, only committers can close bugs).

The comment you found in Scylla.yaml was probably copied from some Cassandra configuration file, and is, as far as I know, irrelevant to Scylla.

**Comment by avikivity** [comment]
Scylla requires that the allocator provide notification when memory is running low, and only the seastar allocator is capable of doing that.

**Comment by thedrow** [comment]
Good to know. Thanks.
