### ISSUE TITLE
Drop system_schema.scylla_tables.cdc in favour of the existing schema extension

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#5737]
While cdc is still experimental, let's use the cdc schema extension (https://github.com/scylladb/scylla/pull/5729) instead of a special column named `cdc` added to `system_schema.scylla_tables`.

The column is fortunately created only if `--experimental cdc` is enabled, so it's still fine to drop it in a backward incompatible way.

Pros:
* CDC-related data will no longer be duplicated in the schema extension and this special column
* All complicated code used to ensure schema agreement can be reverted (including the schema feature), because no column will be added to `system_schema.scylla_tables`

@haaawk @kbr- @elcallio

**Comment by slivne** [comment]
@avikivity / @tgrabiec any view on this ?

If we want todo this we have todo it for 3.4

**Comment by piodul** [comment]
Correction: unfortunately it turns out that the `cdc` column is added even if `--experimental cdc` option is not set. PR https://github.com/scylladb/scylla/pull/5908 will not remove this column. CDC metadata will still be written to both cdc column and cdc schema extension, but only the latter will be ever read and treated as a "source of truth" on cdc metadata.

Related: https://github.com/scylladb/scylla/issues/5894

**Comment by haaawk** [comment]
Fixed with https://github.com/scylladb/scylla/pull/5908
