### ISSUE TITLE
reader_concurrency_semaphore::signal() can fail

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5741]
It allocates, which can fail, but it is called from `noexcept` environments, like `reader_permit::memory_units::~memory_units()`. Make it noexcept, so that we don't convert `std::bad_alloc` to crash.

**Comment by denesb** [comment]
Additionally a failed `signal()` can result reads blocked until they either time out, or a successful signal.

**Comment by denesb** [comment]
Should be backported to all live branches.

**Comment by avikivity** [comment]
This isn't a really dangerous bug. It's a small allocation so it should usully succeed, and when it doesn't, the caller will call std::terminate() (afte the patch, signal() will call std::terminate). So the patch is just moving the point-of-call to std::terminate().

**Comment by denesb** [comment]
After the patch there is no need to call `std::terminate` as the
`std::bad_alloc` is simply forwarded to the read waiting for admission.
This will even free up memory, so as we iterate over the queue we might
succeed the allocation after having failed some of the reads.

Of course in the case when the `schedule()` triggered by `set_exception()`
fails too, you are right. Maybe that is what you meant.

**Comment by avikivity** [comment]
That is what I meant. What's the other case? This can be important.

**Comment by denesb** [comment]
Imagine a situation where we run out of memory so `signal()` fails. Currently this means we fail to admit the next queued reads. If all the currently executing reads finish, but fail to `signal()` we might end up with enough resources on the semaphore to admit the queued reads, but having failed to do so due to `std::bad_alloc`. The reads will stay in the queue until they time out, or some read finishing manages to do a successful `signal()`. Highly unlikely scenario, because reads finishing will also free up memory.

**Comment by avikivity** [comment]
(actually that was not what I meant)

signal() can only fail if we so run out of memory that we can't allocate a 32-byte (or so) objects. These situations are already fatal to us, since future::then() and friends also have to allocate small objects for the continuation (and in fact they abort in those cases). We have no way to ensure a .then() won't be called between the failure to allocate a reader_permit::impl and the actual memory release, so we're likely to die anyway. The patch is still good, since if we ever implement a reserve for continuations, the reserve changes "we're going to die anyway" to "the failure to handle reader_permit::impl allocation failure is all that stood between us and survival", but currently it just defers the point where we die.

Note that small objects are likely to successfully allocate even in OOM situations, because they come from pools, so unless the pool is exhausted AND there is no small block for extending the pool, the allocation will succeed. The large allocations made by the readers "protect" the small pool objects.

An exception is when all of the allocations are for small objects, in that case we're sure to exhaust memory one way or another, but with readers that's unlikely because they have associated large allocations that are likely to fail first.

**Comment by denesb** [comment]
Yes, so I think we need not backport this.

**Comment by avikivity** [comment]
As the conclusion was not to backport, removing the backport candidate label.
