### ISSUE TITLE
Misleading error from CDC preimage when RF > # of nodes

### ISSUE THREAD

**Issue by jul-stas** [scylladb/scylla#5746]
Operations on table with `'preimage':'true'` throw `NoHostAvailable` when `replication_factor` is greater than number of nodes. E.g. with a 1-node cluster:
```
cqlsh> create keyspace ks with replication = {'class':'SimpleStrategy', 'replication_factor': 3};
cqlsh> use ks;
cqlsh:ks> create table t1 (a int primary key, b int) with cdc = {'enabled':true, 'preimage':'true'};
cqlsh:ks> insert into t1 (a,b) values (1,1);
NoHostAvailable: 
```

**Comment by slivne** [comment]
NoHostAvilable is not the correct response - yet its not clear what is,

The reason we are failing is because of the quorum read prior to fetch the pre_image.

What does Scylla return on a QUORUM read in this case (RF=3 only one node) I don;t think its NoHostAvilable - can you please check.

Overall I think it would be better to fail the write as if it required a higher consistency level, yet I think we need others view on this as well.

**Comment by haaawk** [comment]
I agree with @slivne here. Failing the write is the safest. An alternative would be to fetch preimage with CL=ONE if CL=QUORUM fails. This would lead to a less consistent preimage but won't fail the write.

**Comment by kbr-** [comment]
@slivne 

```
cqlsh> create keyspace ks with replication = {'class':'SimpleStrategy', 'replication_factor': 3};
cqlsh> create table ks.t (pk int primary key);
cqlsh> consistency quorum;
Consistency level set to QUORUM.
cqlsh> insert into ks.t (pk) values (0);
NoHostAvailable: 
cqlsh> select * from ks.t;
NoHostAvailable: 
cqlsh> consistency one;
Consistency level set to ONE.
cqlsh> insert into ks.t (pk) values (0);
cqlsh> select * from ks.t;

 pk
----
  0

(1 rows)
cqlsh> 
```

**Comment by kbr-** [comment]
> Overall I think it would be better to fail the write as if it required a higher consistency level, yet I think we need others view on this as well.

If there really is only one replica containing the partition we're interested in, _it is safe to query with consistency ONE_. "Safe" means that the query will return consistent data (whatever "consistent" means; we'll at least have read monotonicity and _read your writes_).

And we can check whether there is just one replica, it's pretty easy:
```
ss->get_token_metadata().count_normal_token_owners() <= 1
```
where `ss` is a pointer to the local `storage_service`.

Of course there is a race here, where the above check would pass but there are >= 2 replicas already because a node has joined and jumped to normal status but the gossip didn't reach us yet. In that case the preimage could miss some data which lies only on the new replica. But considering that the preimage doesn't satisfy any serious consistency properties anyway, I wouldn't say it's a problem.

**Comment by kbr-** [comment]
Also @avikivity suggested in my topology change PR that we could introduce another consistency level, `EFFECTIVE_QUORUM`, which would do something like that (check if there's only one replica and in that case, query just that replica). https://github.com/scylladb/scylla/pull/5485/#discussion_r369468456

So now we have two potential uses for `EFFECTIVE_QUORUM` and we should seriously consider introducing such thing.

Note however that there are also DC-aware versions of QUORUM and the pre-image query actually uses such a level, `LOCAL_QUORUM` in this case. So we would probably also need to introduce `LOCAL_EFFECTIVE_QUORUM` and `EACH_EFFECTIVE_QUORUM` or something.

**Comment by haaawk** [comment]
What was the conclusion here @jul-stas?

**Comment by jul-stas** [comment]
> What was the conclusion here @jul-stas?

There wasn't any. So far, we only agreed to start an email thread about this.
(wasn't it you who volunteered to start it? :) )

**Comment by nyh** [comment]
This is already in 4.1 and 4.2, and is also a relatively minor change in a non-GAed feature, so not backporting to 4.0.
