### ISSUE TITLE
alternator write_isolation configuration is too terse

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5758]
From https://github.com/scylladb/scylla/commit/abdbb70ad9458833df312a1f9a5db47d35e7bb02:

> {
>   'Key': 'system:write_isolation',
>   'Value': X
> },
> where X is one of the following implemented levels:
>  * 'f' - forbid RMW
>  * 'a' - always enforce RMW
>  * 'o' - only RMW writes will go through LWT
>  * 'u' - unsafe RMW (to be deprecated/eradicated)
> 

write_isolation is very informative, but f/a/o/u are too terse IMO. Should use more understandable names instead.

**Comment by nyh** [comment]
@avikivity I also had this feeling when I first read @psarna patch, but then I noticed that his code actually checks for the first letter, not the entire name, so a user can write "forbid" or even "forbid_rmw" or "forbid RMW" as the value, not just "f".

I wonder if we should keep the code as-is and just change the document, to recommend the words "forbid", "always", etc., instead of just one letter?

**Comment by psarna** [comment]
On Sun, Feb 9, 2020, 15:18 nyh <notifications@github.com> wrote:

> @avikivity <https://github.com/avikivity> I also had this feeling when I
> first read @psarna <https://github.com/psarna> patch, but then I noticed
> that his code actually checks for the first letter, not the entire name, so
> a user can write "forbid" or even "forbid_rmw" or "forbid RMW" as the
> value, not just "f".
>
> I wonder if we should keep the code as-is and just change the document, to
> recommend the words "forbid", "always", etc., instead of just one letter?
>
Actually, checking only the first letter in order to allow more expressive
keywords (e.g. forbid, forbid_rmw, etc.) was my intention from the start.
It was a mistake on my part not to document it anywhere. One unlikely
pitfall is that people may try non-obvious keywords and ending up with
wrong levels, e.g. "always_forbid_rmw" will not work as expected at all.
Still, perhaps I should just explicitly document all the officially allowed
keywords (e.g. "setting write isolation level to f, forbid, or forbid_rmw
will result in not allowing rmw requests"), and leave the fact that we only
check the first letter as an implementation detail, which it is - in order
to mitigate full string comparison each time.

**Comment by fruch** [comment]
I think that an external API like that should be a bit more strict on what are the valid inputs.
how you store it internally doesn't matter, but we should be a more clear for a user if the tags he's using are correct or not.

I would fail the tagging api on unfamiliar tags, or at least supply some warning

**Comment by psarna** [comment]
I sent `[PATCH 0/5] alternator: Make write isolation config less terse` to scylladb-dev@.

**Comment by avikivity** [comment]
Not a regression, not backporting.
