### ISSUE TITLE
some background_read counters are underflow

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#5797]
*Installation details*
Scylla version (or git commit hash): a8a4e584ec3332067b6b9e1756ba1bf2392e1424
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

`scylla_storage_proxy_coordinator_background_reads{scheduling_group_name="main",shard="0",type="queue_length"} 18446744073709551616.000000`

caused by 971711a5461c09421f1c9b1b3b2d9f6209a425da

**Comment by eliransin** [comment]
This commit specifically has a comment:

>One thing this commit doesn't handle is validating that an individual
statistic didn't "cross a scheduling group boundary", such validation
is possible but it can easily be added in the future. There is a
subtlety to doing so since if the operation did cross to other
scheduling group two connected statistics can lose balance
for example written bytes and completed write transactions.

Nevertheless there is a quick fix for restoring the balance, this will "hide" the fact that stats are
increased and decreased in different scheduling groups, which means that some operations are
done outside the correct/native scheduling group.

**Comment by eliransin** [comment]
@gleb-cloudius do you have a reproducer for this?

**Comment by gleb-cloudius** [comment]
At the commit provided it happened after the fresh boot for me.

**Comment by eliransin** [comment]
Doesn't reproduce, even though it is a known issue. I think it is better to preserve the balance at the price of "correctness" in this case.
An underflow counter is not an option. For solving the actual issue of performing operations from
the incorrect scheduling group I have opened: #6180

**Comment by slivne** [comment]
@eliransin ping

**Comment by eliransin** [comment]
@slivne I have sent a patch a long time ago that was even reviewed and was approved, I simply forgot to push for merge.
The title of this patch is: `[PATCH] Storage Proxy: Maintain metrics in response handler classes`
I will adjust it since it has been such a long time and revive the thread.

**Comment by slivne** [comment]
@eliransin was this fixed ?

**Comment by avikivity** [comment]
May have been fixed by bc77939ada60c2bfbdb42f9ed93df8b9fbfd3689 (#7117). @denesb IIRC there were other mis-grouped task bugs fixed, do you remember them?

**Comment by denesb** [comment]
@avikivity there was this> https://github.com/scylladb/scylla/issues/6908.

**Comment by avikivity** [comment]
So it's probably fixed. @gleb-cloudius please confirm.

**Comment by gleb-cloudius** [comment]
It does not reproduce for me lately. Will reopen if will see again.
