### ISSUE TITLE
scylla_alternator_total_operations stats isn't being updated

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#5836]
the initial implementation of stats for alternator had `scylla_alternator_total_operations` but now it's zero all the time 
See the Total Actions panel
![image](https://user-images.githubusercontent.com/340979/74737626-e673b400-525d-11ea-8f6b-5c9f243b2500.png)
  
if this is not used anymore, we should remove it and update the scylla-monitoring to include the correct one

**Comment by fruch** [comment]
@nyh @psarna @eliransin, is that on purpose ? or by mistake ?

**Comment by nyh** [comment]
Interesting question. I have a vague recollection that @amnonh at some point said we don't need a total operations count, because we now have multiple operation counters with different labels for the different operations, and one trivial sum can produce the total of all operations. But I don't remember ever making the decision to drop this counter, and of course it's silly to keep it while not updating it. I'll look into this now.

**Comment by nyh** [comment]
Looks like this wasn't dropped deliberately, it was mistakenly dropped in commit 388b492040b6f7d9b8eeb6f5336f0d5c5e09ee76 by @psarna who was just hoping to move code around, and there is no indication he wanted to drop the count (Piotr, please confirm). I'll submit a patch to reverse this part of the change.

**Comment by psarna** [comment]
Yup, my mistake. I'll enqueue the fix today, thanks

**Comment by fruch** [comment]
@psarna I do agree to the comment, that we could drop it completely.
and it's one change to scylla-monitoring to drop it too.

**Comment by nyh** [comment]
Already in 4.0. Backported also to 3.3 since this is a trivial bugfix.
