### ISSUE TITLE
Alternator server auth cache is erroneously cross-shard

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#5913]
Due to how Seastar http server is implemented, `alternator_server` is not a sharded service, but instead holds a non-sharded `server_control`, which in turn keeps a sharded http server instance.

It's easy to mistake the `alternator_server` to be sharded however, as I did, when implementing auth routines. As a result, the auth code uses a single instance of credentials cache created on shard0, regardless of the fact that the code may run on a different shard - which makes the whole structure unsafe to use.

The proper fix is either to make the credentials cache directly sharded, or to go one step further and make the whole `alternator_server` sharded - by instantiating `server_control` only on shard0, which I'm going to do tomorrow, with this issue being a reminder for it.

**Comment by nyh** [comment]
Already in 4.0 so no need to backport there.
Backporting to 3.3 will be complicated because of a lot of unrelated changes to function signatures since 3.3, so because Alternator was experimental in 3.3 anyway, I'm choosing not to backport and dropping the "Backport candidate" tag. @psarna, if you disagree please return the "Backport candidate" tag.
