### ISSUE TITLE
Reduce unncessary VIEW_BACKLOG updates in gossip

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#5970]
The blacklog of current and max in VIEW_BACKLOG is not update but the nodes are updating it all the time.  For example: 

```
INFO  2020-03-06 17:13:46,761 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486026590,718)
INFO  2020-03-06 17:13:46,821 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486026531,742)
INFO  2020-03-06 17:13:47,765 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486027590,721)                                       
INFO  2020-03-06 17:13:47,825 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486027531,745)
INFO  2020-03-06 17:13:48,772 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486028590,726)
INFO  2020-03-06 17:13:48,833 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486028531,750)
INFO  2020-03-06 17:13:49,772 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.3, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486029590,729)
INFO  2020-03-06 17:13:49,832 [shard 0] storage_service - Update system.peers table: endpoint=127.0.0.2, app_state=VIEW_BACKLOG, versioned_value=Value(0:18446744073709551615:1583486029531,753)
```

The code in question is:

```
246 future<> view_update_backlog_broker::start() {
247     _gossiper.register_(shared_from_this());
248     if (engine().cpu_id() == 0) {
249         // Gossiper runs only on shard 0, and there's no API to add multiple, per-shard application states.
250         // Also, right now we aggregate all backlogs, since the coordinator doesn't keep per-replica shard backlogs.
251         _started = seastar::async([this] {
252             while (!_as.abort_requested()) {
253                 auto backlog = _sp.local().get_view_update_backlog();
254                 auto now = api::timestamp_type(std::chrono::duration_cast<std::chrono::milliseconds>(
255                         std::chrono::system_clock::now().time_since_epoch()).count());
256                 //FIXME: discarded future.
257                 (void)_gossiper.add_local_application_state(
258                         gms::application_state::VIEW_BACKLOG,
259                         gms::versioned_value(seastar::format("{}:{}:{}", backlog.current, backlog.max, now)));
260                 sleep_abortable(gms::gossiper::INTERVAL, _as).get();
261             }
262         }).handle_exception_type([] (const seastar::sleep_aborted& ignored) { });
263     }
264     return make_ready_future<>();
265 }
```

The time `now` is update. I am wondering if we could avoid sending if the blacklog current and max do not change. 

The downside of such updates:

- Introduces more gossip exchange traffic

- Updates system.peers all the time

**Comment by asias** [comment]
@nyh @psarna What do you think?

**Comment by psarna** [comment]
@asias, looks like the timestamp itself isn't useful anywhere in the storage proxy, so it sounds like a good idea to only produce updates if the state changed.

**Comment by asias** [comment]
> @asias, looks like the timestamp itself isn't useful anywhere in the storage proxy, so it sounds like a good idea to only produce updates if the state changed.

That is good news!

**Comment by nyh** [comment]
@asias your main observation - that if the view backlog estimate doesn't change we don't need to get it again from the gossiper - is correct. We don't expire backlog estimates even if they are very old. We always use the latest view backlog estimate we have - either from a gossip or piggybacked on a response - no matter how old is this latest estimate. The only purpose these timestamps serve is to avoid an old estimate (received by gossip) from replacing a newer estimate we got piggybacked on a response (see `view_update_backlog_broker::on_change()`).

However, I'm not sure what you're actually proposing to change. Unless I'm misunderstanding something (please correct me if I'm wrong), gossip always resends the entire application state, because the sender doesn't know what state the receiver thinks it has. So what does it matter if the sender sends the same states every time or it's a slightly different state each time?

@asias is right that the current code, in  `view_update_backlog_broker::start()`, does update the state every `gms::gossiper::INTERVAL`. But is there a penalty of doing this, even if we re-update to the same value every time? I thought that the `_gossiper.add_local_application_state()` call once every few seconds has tiny overhead - is this not true?

Finally, even if we do want to start calling `_gossiper.add_local_application_state()` less, we'll need to be clever about when we say the backlog has "changed". For no-materialized-views this is easy (the backlog will always be 0, and never changes). But when materialized views *are* used, these numbers will fluctuate, and we we'll need some sort of hysteresis - e.g., anything until a 10% difference from the previous value is considered the same and not sent again - otherwise we'll never see the optimization of not setting the state.

**Comment by asias** [comment]
> However, I'm not sure what you're actually proposing to change. Unless I'm misunderstanding something (please correct me if I'm wrong), gossip always resends the entire application state, because the sender doesn't know what state the receiver thinks it has. So what does it matter if the sender sends the same states every time or it's a slightly different state each time?

No, gossip sends the difference only. If an application state does not change, gossip will not exchange them at all.  So, I am proposing to send VIEW_BACKLONG only when it really changes.

**Comment by asias** [comment]
> @asias is right that the current code, in `view_update_backlog_broker::start()`, does update the state every `gms::gossiper::INTERVAL`. But is there a penalty of doing this, even if we re-update to the same value every time? I thought that the `_gossiper.add_local_application_state()` call once every few seconds has tiny overhead - is this not true?

The overhead of calling add_local_application_state per second is tiny but it causes the updated VIEW_BACKLONG to be propagated in the whole cluster while the value does not really change. Number of nodes in the cluster - 1 nodes will receive this information.

**Comment by asias** [comment]
> Finally, even if we do want to start calling `_gossiper.add_local_application_state()` less, we'll need to be clever about when we say the backlog has "changed". For no-materialized-views this is easy (the backlog will always be 0, and never changes). But when materialized views _are_ used, these numbers will fluctuate, and we we'll need some sort of hysteresis - e.g., anything until a 10% difference from the previous value is considered the same and not sent again - otherwise we'll never see the optimization of not setting the state.

This is a good idea. I am wondering what is the impact if we do not send, say 10%, view_backlog.

**Comment by asias** [comment]
I wanted to revive this work. The extra unnecessary traffic is fine to a cluster in a good shape but when some of the node or shards are loaded, such messages and the handling of such messages can make the system even busy.

**Comment by nyh** [comment]
https://github.com/scylladb/scylla/pull/7283 was already committed marking this issue fixed, but note that it checks strict equality of the old and new backlogs, so (as I explained above) it will only make a difference when MV is not used.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
