### ISSUE TITLE
Scylla is not starting if cdc configured and all nodes marked as seed on startup.

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#6005]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): Scylla version 666.development-0.20200309.d895f5e1
Cluster size:3
OS (RHEL/CentOS/Ubuntu/AWS AMI): dtest on ubuntu
Thanks to @fruch who found this issue. 
dtest try to start cluster with 3 nodes and configured cdc feature. One option is that all nodes configured as seed node.
Scylla couldn't start with next error:
```
('node1',
 ["ERROR 2020-03-11 12:11:46,549 [shard 0] init - Startup failed: std::runtime_error (Can't boot this node because we weren't able to retrieve other nodes' tokens, which is required for CDC to work. Make sure that:"]),
('node2',
 ["ERROR 2020-03-11 12:11:47,626 [shard 0] init - Startup failed: std::runtime_error (Can't boot this node because we weren't able to retrieve other nodes' tokens, which is required for CDC to work. Make sure that:"]),
('node3',
 ["ERROR 2020-03-11 12:11:49,697 [shard 0] init - Startup failed: std::runtime_error (Can't boot this node because we weren't able to retrieve other nodes' tokens, which is required for CDC to work. Make sure that:"])
```

Simple dtest allow to reproduce the issue attached

[test_repo_error_with_cdc.py.txt](https://github.com/scylladb/scylla/files/4318347/test_repo_error_with_cdc.py.txt)
[system.log](https://github.com/scylladb/scylla/files/4318363/system.log)

**Comment by slivne** [comment]
blocks testing in dtest

**Comment by slivne** [comment]
maybe related to to token / stream generations

**Comment by kbr-** [comment]
> maybe related to to token / stream generations

Yes, and it's expected.
@fruch @aleksbykov why are you using this configuration? Most dtests use a different configuration, where node N configures nodes {1, ..., N} as seeds. (so node 1 configures {1}, node 2 configures {1, 2} etc.). And this other configuration is a hack anyway, because Scylla doesn't support joining nodes as seeds safely (only the first node should be joined as a seed).

The only safe and recommended way to join nodes is to bootstrap them, and if you want to join many nodes, you should bootstrap them sequentially.
However, because CCM by default uses the configuration I described above, it's allowed (still doesn't mean it's completely safe, but if you have to, use it).

**Comment by fruch** [comment]
> > maybe related to to token / stream generations
> 
> Yes, and it's expected.
> @fruch @aleksbykov why are you using this configuration? Most dtests use a different configuration, where node N configures nodes {1, ..., N} as seeds. (so node 1 configures {1}, node 2 configures {1, 2} etc.). And this other configuration is a hack anyway, because Scylla doesn't support joining nodes as seeds safely (only the first node should be joined as a seed).
> 
> The only safe and recommended way to join nodes is to bootstrap them, and if you want to join many nodes, you should bootstrap them sequentially.
> However, because CCM by default uses the configuration I described above, it's allowed (still doesn't mean it's completely safe, but if you have to, use it).

I'm running the python-driver integration tests. 
And seems there are places where we stop all the nodes. 
And then start them all again, all of the nodes are configured as seeds. seems like it's the default ccm behavior, and it works in Cassandra and works fine if we disable CDC.

So what you are saying, we have to start seeds one by one if CDC is enabled ?

**Comment by kbr-** [comment]
The error messages described in the issue should only show up when you're
**joining** a node to the cluster, not after you've already joined and then
restarted a node which was previously UN.

Did they show up after the node was joined and restarted or when you tried
to start it for the first time (hence join the cluster)?

**Comment by kostja** [comment]
Affects my local setup too.

**Comment by slivne** [comment]
@fruch can you provide a simple reproducer outside of python matrix using CCM so @kbr- can look at whats going on and fix it if needed.

**Comment by fruch** [comment]
@slivne @kbr- 

@aleksbykov supplied a example dtest in the bug description.

In CCM, when using `cluster.populate(3)` nodes go one by one. but when calling `cluster.stop(); cluster.start()` all nodes starts at the same time, and they are all seeds, hence we run into this problem.

**Comment by kbr-** [comment]
@fruch 

First: this is not what happens in the script provided by Aleks, nor in the test log.
The script configures all nodes to use all nodes as seeds, and then tries to **join** them (start them for the first  time) using this configuration:
```
def prepare(self, nodes=1, permissions_validity=0, enable_auth=True, wait_for_superuser=False, cdc=False):
        config = {'permissions_validity_in_ms': permissions_validity,
                  'permissions_update_interval_in_ms': int(permissions_validity / 2),
                  'seed_provider': [{'class_name': 'org.apache.cassandra.locator.SimpleSeedProvider',
                                     'parameters': [{'seeds': '127.0.0.1, 127.0.0.2, 127.0.0.3'}]
                                     }]
                  }

        ...

        self.cluster.set_configuration_options(values=config)
        self.cluster.populate(nodes).start(wait_other_notice=True, wait_for_binary_proto=True, verbose=True)
```

```
    def init_cluster_auth_disabled_cdc_enable_on_table_test(self):
        self.prepare(nodes=3, enable_auth=False, cdc=True)
```

The test log provided by Aleks confirms that the **first** start failed. Even better, the test doesn't even have a `cluster.stop()` call.

Second: I wrote a little dtest which actually does what you described: starts a 3-node cluster and then restarts it:
```
class Test(Tester):
    def __init__(self, *args, **kwargs):
        CASSANDRA_DIR = os.environ.get('CASSANDRA_DIR')

        ring_delay_sec = 5
        kwargs['cluster_options'] = {'experimental_features': ['cdc'],
                                     'ring_delay_ms': ring_delay_sec * 1000}
        Tester.__init__(self, *args, **kwargs)

    def test(self):
        debug('Populate')
        cluster = self.cluster
        cluster.populate(3)
        debug('start')
        cluster.start(wait_for_binary_proto=True, wait_other_notice=True)
        debug('stop')
        cluster.stop()
        debug('restart')
        cluster.start(wait_for_binary_proto=True, wait_other_notice=True)
        debug('Test finished')
```
The test works.

So let me ask my previous question again: why are you using this configuration?

**Comment by fruch** [comment]
Again, I was just using the code in python-driver integration tests. and assuming the configuration worked for Cassandra  should work for scylla, I've enabled experimental flag months cause of other option enabled by default in those tests, and it was working until CDC was introduced.

here is the exact sequence that the test were doing: 
```python
class Test(Tester):
    def test(self):
        debug('Populate')
        cluster = self.cluster
        cluster.set_configuration_options({'start_native_transport': True})
        cluster.set_configuration_options({'experimental': True})
        cluster.set_configuration_options({'enable_user_defined_functions': True})
        cluster.set_configuration_options({'enable_scripted_user_defined_functions': True})
        cluster.set_configuration_options({})
        cluster.populate([3], ipformat=None)
        # debug('start')
        # cluster.start(wait_for_binary_proto=True, wait_other_notice=True)
        debug('stop')
        cluster.stop()
        debug('restart')
        config_options = {'write_request_timeout_in_ms': '20000'}
        cluster.set_configuration_options(config_options)  # calling this after populate configure all the nodes as seeds
        cluster.start(wait_for_binary_proto=True, wait_other_notice=True)
        debug('Test finished')
```

seem like the call to `set_configuration_options()` after populate, causes all nodes to be configured as seed, as there are configured default, seems like the bug in CCM that it wasn't the case in the first call to `set_configuration_options()` since not all nodes were configured yet.

Anyhow booting a cluster multiple seeds, at the same time is something that was working before, both in Cassandra and in Scylla. I don't think we should break it.

**Comment by slivne** [comment]
Ok its clear there is a change that is not compatible and we need to either ok it and leave with it or say its not acceptable and find a different solution.

In the past we had issues with customers complaining that they do not want to change the seeds and would rather have 3 nodes always configured at bootstrap. 

So the question in my view - can a node bootstrap as seed if it is not able to connect to other seeds - it used to be able todo that with a timeout of 5 minutes or so (if I recall correctly). If that works I think its fine. I do not think clusters are bootstrapped in a random order with all nodes as seeds.

Yes this change may cause issues to users as well yet I think its for the users that expect simply to start 10 nodes at once - its not something that most users do or should do.

@avikivity / @tzach  please review

@kbr- / @haaawk please check what happens when we boot a single node that has himself and another node as a seed - can it start.

**Comment by kbr-** [comment]
@fruch 

Indeed this `set_configuration_options` changes the lists of seeds, which is weird.
But this test has commented out the first `cluster.start(...)` call, so you're calling `cluster.stop()` without first calling `cluster.start(...)`.

If you let the nodes start the first time, then you will be able to restart the cluster even after changing the configuration to use all nodes as seeds. Just make sure to use the default configuration when the nodes are joining the cluster.

**Comment by kbr-** [comment]
> Anyhow booting a cluster multiple seeds, at the same time is something that was working before, both in Cassandra and in Scylla. I don't think we should break it.

I'll assume that by "booting" you mean "bootstrapping" (joining new nodes to the cluster), because restarting works as before.

The problem with joining nodes is as follows. When a node joins the cluster, this requires some serious reconfiguration of the cluster -- of every other node that already is in the cluster. If we don't do this reconfiguration, we break some important invariants and it is highly probable that data will be lost (among other problems).

So when a node joins the cluster, it somehow has to contact other nodes and inform them about the fact it's joining, so they can react and perform the reconfiguration.

If we join nodes concurrently, they can't react properly. This would require some coordination between multiple nodes that are joining, i.e. they would have to know that other nodes are also joining and wait with the reconfiguration until every node knows the state of every other joining node. *We don't have this functionality implemented yet*. Neither does Cassandra.

If someone somewhere on the internet says that it's safe to join nodes concurrently today, either in Scylla or Cassandra, they are either unaware of the problems, or they are not being honest.

**Comment by kbr-** [comment]
@slivne 

> can a node bootstrap as seed if it is not able to connect to other seeds

With CDC enabled, it won't. But it's not CDC-specific. I added this check not only because CDC requires nodes to be aware of a joining node; the entire replication mechanism depends on token rings being synchronized to work properly. If they are not synchronized, writes will be sent to wrong nodes, and data will be lost.

And for token rings to synchronize when a new node is joining (and inserting new tokens), the nodes *must contact*. We can't bend the laws of physics.

> please check what happens when we boot a single node that has himself and another node as a seed - can it start

If you mean bootstrapping/joining, then no, as explained above. If you mean restarting (after it's already joined), then yes, after trying to contact another seed for `shadow_round_ms` (300 seconds by default).

**Comment by kostja** [comment]
> If someone somewhere on the internet says that it's safe to join nodes concurrently today, either in Scylla or Cassandra, then they are either unaware of the problems, or they are not being honest.

Kamil, I agree that joining nodes concurrently is known to be unsafe. However, AFAIK it's common to boot all seeds concurrently. Is it possible to fix it? Are there issues with distinguishing a fresh cluster boot from joining?

**Comment by kbr-** [comment]
@kostja 
There's the Elasticity plan:
https://docs.google.com/document/d/18jNNj0U6Q2ikyedknH5LGHYpCxu0_Vsx5TmnEdgvtKw/

I'm also working on a draft design for multi-node bootstrap (including the case where we start from 0 nodes), I'm hoping it will be ready by Friday.

**Comment by slivne** [comment]
@avikivity please review the additional limitation on bootstrap - its indeed safer but it was possible to bootstrap unsafe before and it mostly worked

**Comment by slivne** [comment]
With regards to 4.0 the decision is: since the additional limitation (bootstrap of seeds in parallel) is only applied if experimental is set - this is not a blocker and will be pushed out to 4.1

With regards to 4.1: this has to be fixed to get CDC out of experimental mode
