### ISSUE TITLE
test.py uses tmpfs

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#6062]
In regular developer workstations /tmp is a tmpfs and that is where tests runs by test.py store their files. We had a few bugs in the past that would reproduce on real filesystems, but not tmpfs.

We should evaluate changing test.py so that TMPDIR points to somewhere in testlog/

**Comment by avikivity** [comment]
Internals, not backporting.

**Comment by nyh** [comment]
@avikivity note that I backported a similar patch for the Alternator tests, because I was worried about the **testing** of the other branches with faulty /tmp setups like we used to have. But if QA fixed the slow /tmp the test machines, I agree it doesn't matter and everything will just work with /tmp and there's no need to backport.
