### ISSUE TITLE
All SCT artifacts failed on cassandra-env.sh

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla#6095]
`/tmp/tmp.7XHx5kzWiC/cassandra-env.sh: line 90: [: -ge: unary operator expected
mkdir: cannot create directory '/opt/scylladb/share/cassandra/logs': Permission denied
/opt/scylladb/share/cassandra/bin/nodetool: line 96: : command not found`

**Comment by yaronkaikov** [comment]
@syuu1228 @penberg  FYI

**Comment by eliransin** [comment]
@takuya It looks like several issues during the run of nodetool:
1. There is no $JAVA_VERSION variable in the environment which I can't easily explain.
2. The cassandra-emv.sh file is trying to make a log directory for the garbage collector and
it fails on permissions. 
The below code is the problematic code, it was introduced in scylladb/scylla-tools-java@afd40c7273

https://github.com/scylladb/scylla-tools-java/blob/d3e5bbe208e1fd3dea7f4bdf82489c14b2f3e210/conf/cassandra-env.sh#L89-L108

Two possibilities are:
1. The command should be run differently (because of the change or something else)
2. The artifact tests found a real bug in scylla-tools-java

Either way we should open this in the scylla-tools-java repo.

**Comment by eliransin** [comment]
This looks like scylla-tools-java issue so I have opened:
scylladb/scylla-tools-java#147
