### ISSUE TITLE
scylla AMI should have a larger ProcessSizeMax in coredump.conf

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#612]
Default of 16G in `/etc/systemd/coredump.conf` is too small.
Should be at 100GB
```
ProcessSizeMax=100G
ExternalSizeMax=100G
```

**Comment by dorlaor** [comment]
Note that the target directory should have enough room (not the tiny rootfs
most use).
It would be the best to set it dynamically (funny Linux doesn't do it for
us)

**Comment by avikivity** [comment]
Should be the machine's memory size + some spare.

**Comment by syuu1228** [comment]
Since I merged following commit(https://github.com/scylladb/scylla/commit/9b4d0592fa69e9f7debbb916e3e2660916c1f1b5),  we stopped using systemd-coredump, we moved to scylla_save_coredump.
New script is distribution independent, saves coredump at /var/lib/scylla/coredump.
So we don't have this limitation anymore.
