### ISSUE TITLE
CL=1 writes concurrent with a bootstrap of a new node may be lost 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#6126]
When adding a node, the coordinator increases CL by 1 to make sure that CL=QUORUM writes will keep the quorum in both the old and the new replica set.

For RF>1 and CL=1, this doesn't make sure that CL is met in both the old and the new replica sets. As a result such writes may be lost after bootstrapping finishes.

**Comment by tgrabiec** [comment]
This can be solved by changing the coordinator to require CL to be achieved in both old and new replica sets if there is an active topology change.

This can improve availability a bit in the CL=QUORUM case as well because we wouldn't always require an extra replica (in case the 2 replicas which responded are shared between the old and new replica sets).

This generalization will also allow us to make arbitrary replica set changes as part of topology changes (like adding many nodes at a time), where old and new replica sets may not overlap at all.

**Comment by gleb-cloudius** [comment]
I do not see why. Can you be a little bit more verbose?

--
			Gleb.

**Comment by tgrabiec** [comment]
I don't see why now as well.

**Comment by slivne** [comment]
Sorry I am missing something, don't we increase the CL in writes to be +1 during bootstrap CL=ONE ? 

I think we should

**Comment by kbr-** [comment]
> For RF>1 and CL=1, this doesn't make sure that CL is met in both the old and the new replica sets. As a result such writes may be lost after bootstrapping finishes.

It does. The reason why the trick works is that at most one node may leave the natural replica set, and at most one node may join the natural replica set.

Suppose that the old replica set is X and the new replica set (due to a node bootstrapping or decommissioning) is Y. Since at most one node can bootstrap or decommission at a time, one of the following is true:
1. Y = X + {A}, for some A not in X.
2. Y = X - {A}, for some A in X.
3. Y = X - {A} + {B}, for some A in X and some B not in X.

CL=1 write made during the topology change requires **2** replicas to answer for the write to be considered successful.
- in case 1. above, those 2 replicas that answered are either both in X, or one of them is in X and the other is A. In any case, we know that the write is saved on 2 replicas in Y.
- in case 2. above, those 2 replicas that answer are either both in Y, or one of them is in Y and the other is A. In the first case the write is saved on 2 replicas in Y, and in the second case it is saved on 1 replica in Y. Thus the write is not lost.
- in case 3. above, those 2 replicas that answered are either both in X, or one of them is X and the other is B. In the second case the replica is saved on B, i.e. at least 1 replica in Y. In the first case we have two subcases: either one of the two replicas is A or not. If one of them is A, then we still have the other replica which will also be in Y. If not, then we have 2 replicas which will store the write in Y.


But yes, indeed, if we want multiple nodes to add/remove tokens at the same time, then we will have to implement a generalized solution, e.g. by
> changing the coordinator to require CL to be achieved in both old and new replica sets if there is an active topology change
