### ISSUE TITLE
Need a feature bit for alternator

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#6228]
Alternator is enabled when --alternator-port is set.

Alternator is a cross cluster feature, thus nodes should be added into the cluster only if they have this feature set, and alternator should be enabled only when all nodes in the cluster support it. 

@avikivity  thoughts ?

**Comment by tzach** [comment]
AFAIU, the internal communication is standard, so everything will work, except only the enable nodes will support the Alternator REST API. Since REST drivers can not "jump" from one IP to the other, its not a problem.

**Comment by tzach** [comment]
So not urgent for 4.0

**Comment by psarna** [comment]
@tzach true, we technically only need the alternator server for the node which contacts the client, but for load-balancing purposes it should be recommended for all nodes anyway.

Also, other features were introduced in 4.0 (for instance: LWT), which will be enough to ensure that we don't add a too-old node to the cluster - if it supports LWT, it also has alternator.

P.S. That's another example of why I think that our feature tracking is too fine-grained :) With a more coarse-grained system, a "v4.0" version flag could handle everything we introduced (and when backporting, e.g. to hypothetical 3.3.9, a newly introduced "v3.3.9" version flag could serve the same purpose).

**Comment by gleb-cloudius** [comment]
On Sat, Apr 18, 2020 at 11:40:42PM -0700, Piotr Sarna wrote:
> P.S. That's another example of why I think that our feature tracking is too fine-grained :) With a more coarse-grained system, a "v4.0" version flag could handle everything we introduced (and when backporting, e.g. to hypothetical 3.3.9, a newly introduced "v3.3.9" version flag could serve the same purpose).
> 
And that some other subset gets backported to 3.2.11-custom.version and how do you
know if you can upgrade from it to 3.3.9?

--
			Gleb.

**Comment by nyh** [comment]
As @tzach said, Alternator nodes don't have any special way of communicating with each other. It's even fine for just one node to be Alternator - i.e., parse the DynamoDB API - while all other nodes aren't.

@psarna has a good point about the special load-balancing request ("GET /localnodes") but I think this is a separate and somewhat bigger issue. This request simply returns the list of nodes - there is no guarantee whether Alternator is enabled on all of them, and moreover - that Alternator is enabled on the same port on all of them (because each node may theoretically enable Alternator on a different port!). I don't think anybody will expect such mixed setups to work, and nobody will start to use Alternator without enabling it on the entire cluster.

**Comment by eliransin** [comment]
@nyh just to be sure I understand, your recommendation is to leave this as is, right?

**Comment by psarna** [comment]
@gleb-cloudius I'm assuming that versions have strict ordering, so that if a feature was in 3.2.11, then it's guaranteed to be in 3.3.9 too. If we allow backporting from 4.0 to 3.2, but not 3.3, then the system indeed makes no sense and we wouldn't know if the upgrade was possible - but was there ever a precedent to backport something to 3.x, but not 3.y, where x < y?

**Comment by gleb-cloudius** [comment]
On Sun, Apr 19, 2020 at 12:10:39AM -0700, Piotr Sarna wrote:
> @gleb-cloudius I'm assuming that versions have strict ordering, so that if a feature was in 3.2.11, then it's guaranteed to be in 3.3.9 too. If we allow backporting from 4.0 to 3.2, but not 3.3, then the system indeed makes no sense and we wouldn't know if the upgrade was possible - but was there ever a precedent to backport something to 3.x, but not 3.y, where x < y?
> 
To a custom version like I pointed? I am sure there were. Non strict
ordering is exactly what fine grained features allow and you may not
appreciate it until you need it.

--
			Gleb.

**Comment by nyh** [comment]
@eliransin yes, I would close this issue. We can open (if you want) a different issue about the "/localnodes" request not being powerful enough, and maybe needs to list only nodes which support Alternator, and maybe the Alternator port for each. But I think even that is overkill, I don't think we need to support such mixed installations. Since we don't want to support mixed CQL and DynamoDB API on the same installation, nobody is likely to do a rolling upgrade to Alternator anyway.

**Comment by slivne** [comment]
closing the issue, no need for feature bit - avi approved it.
