### ISSUE TITLE
Streaming view updates use incorrect io priority class

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#6231]
The io_priority parameter used when generating view updates from
streaming is used by the sstable reader, so it should use the I/O priority
for streaming read operations, not streaming write operations.

**Comment by nyh** [comment]
@slivne @avikivity @psarna this issue - and its patch - seems very strange to me.

First, why do we need this separate "streaming read" and "streaming write" at all? Do we have anything of this sort for compaction, for example? Do we ever plan to give them different amount of shares - and why? Or is this just for the sake of monitoring - i.e., so we see a count for the bytes used for reads and writes separately? @asias maybe you know why these are two separate IO classes?

Second, what does "streaming write" even mean? When MV exist, the "write part" of the streaming (the part writing the received mutations) can invoke read I/O (since MV writes do read-before-write) - should that I/O be counted as part of the "write part of the streaming" (as before this patch) or as "reads" (as after this patch)? Neither interpretation makes too much sense :-( I.e., after this patch, during a repair the "streaming read" count will include both the reading of the data to send to the other node, and the read-before-write of materialized views in the receiving side of the repair.

I'm reopening this issue, feel free to re-close it if you don't agree with my worries.

**Comment by psarna** [comment]
@nyh As for the first question - I'm not the expert, but I can quote an expert that we in fact want to remove this separation: https://github.com/scylladb/scylla/pull/6217#issuecomment-615558086


And second - I think the most important thing to better grasp why `read priority` is a more fitting choice is to acknowledge that `do_push_view_replica_updates` uses this `io_priority` parameter **only** to feed it to the sstable reader - which is not obvious from the call site at all. Now, since monitoring presents total bytes read/written based on scheduling groups, putting a reader in a `write` scheduling group would result in having gigabytes of memory "written" to disk, when it was in fact read. Given that, we don't really have a choice but to use a reading io_priority - or, after unifying the two priority groups, we can also update the monitoring code to distinguish how many bytes were written and how many were read within this one joint group.

**Comment by slivne** [comment]
@nyh can we close this ?

**Comment by nyh** [comment]
I still don't understand exactly the goal of this issue or the patch, but I don't know what to suggest either, so I'll re-close it.

**Comment by avikivity** [comment]
@nyh I agree we should merge streaming read and streaming write. Especially as they aren't isolated from the cpu perspective.

**Comment by avikivity** [comment]
Minor issue, not backporting.
