### ISSUE TITLE
config: Do not enable repair based node operations by default

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#6305]
Give it some more time to mature. Use the old stream plan based node operations by default.

**Comment by tgrabiec** [comment]
Did we encounter any issues which led us to this decision?

**Comment by tgrabiec** [comment]
This exposes us to https://github.com/scylladb/scylla/issues/4208

This can result in violation of LWT linearizability after topology changes due to the fact that the old streaming will stream only from a single replica and not from a quorum. So a CL=QUORUM write before the topology change may no longer be present on a quorum after the change. 

\cc @kostja

**Comment by kostja** [comment]
Correctness shouldn't be a configuration option. LWT correctness depends on repair-based streaming. Shall we document now that node operations may lead to violation of LWT linerizability unless this option is enabled? 

I agree with @tgrabiec this ticket provides very little insight into why we need an option at all.

**Comment by asias** [comment]
Disabling it by default (suggested by Avi) is a release decision which was discuss in the other thread. 

QA found issues like #6272 #6248 #6232.

**Comment by avikivity** [comment]
Not a bug, so not backporting.
