### ISSUE TITLE
lwt: relax pruning criteria from ALL to QUORUM

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6330]
Now that pruning still keeps the ballot, we should relax the pruning criteria (i.e. how we decide whether to run PRUNE round or not) from ALL to QUORUM. Already with QUORUM any possible future majority will be aware of the value, and will learn it through read repair. 

Relaxing the criteria would allow to avoid having to complete unfinished rounds (repair system.paxos) after a routine maintenance, such as replacing a single node.

**Comment by gleb-cloudius** [comment]
That is a very bad idea. Prune now forgets learnt commit and prepare
returns empty commit instead since it can be sure the commit will never be
used (because we know that all nodes have the same or higher most recently
committed ballot). But we can be sure only because we are waiting for ALL,
not QUORUM.

--
			Gleb.

**Comment by tgrabiec** [comment]
@gleb-cloudius I don't see the problem. The paxos repair may need the commit mutation to replicate it in order to make sure that at least a quorum of the nodes knows about the previously committed value.  But if we pruned it, it means that a quorum already knows it, and this repair doesn't have to do anything.

**Comment by gleb-cloudius** [comment]
The code always repair since it does not know if quorum has it, so it
will repair with an empty mutation which will not repair the data.
Regular read repair will, but why do two rounds of repair.

We can skip paxos repair round for empty mutations, but to know that a
mutation is empty we will need to unfreeze it.

--
			Gleb.

**Comment by tgrabiec** [comment]
But does this change make the situation worse? Repairing with an empty mutation is not more expensive than repairing with a non-empty one, and pruning doesn't affect whether we will need to repair or not.

**Comment by tgrabiec** [comment]
I see it, read-repair will make it more expensive. Maybe it's not that bad, since it will happen only once for a given key after the node is back. Skipping repair is better as you say.

For skipping, we could add a flag to paxos table which tells whether MRC is empty to avoid unfreezeing.

**Comment by gleb-cloudius** [comment]
On Wed, May 06, 2020 at 07:40:38AM -0700, Tomasz Grabiec wrote:
> But does this change make the situation worse? Repairing with an empty mutation is not more expensive than repairing with a non-empty one, and pruning doesn't affect whether we will need to repair or not.
> 
If we do not prune we will repair base table at paxos time and then
reading from base table will not do read repair (since data will be the
same). If we prune we will run repair at paxos time, but this repair
will not repair base table, it will only update the commit entry in the
node that missed it. Then, when the data will be read from the base
table, read will detect mismatch and will repair once more.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Wed, May 06, 2020 at 07:45:11AM -0700, Tomasz Grabiec wrote:
> I see it, read-repair will make it more expensive. Maybe it's not that bad, since it will happen only once for a given key after the node is back. Skipping repair is better as you say.
> 
> For skipping, we could add a flag to paxos table which tells whether MRC is empty to avoid unfreezeing.
> 
This is incompatible change, we will also need to change the protocol to
propagate the flag. All possible to do, the question is if the
complication worth it?

--
			Gleb.
