### ISSUE TITLE
NULL counters treated as 0

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#6382]
A query WHERE counter=0 will also return rows where the counter is non-existent.  This differs from Cassandra.

Scylla:
```cql
cqlsh:ks> CREATE TABLE t(p int PRIMARY KEY, c1 counter, c2 counter);
cqlsh:ks> UPDATE t SET c1 = c1 + 1 WHERE p=1;
cqlsh:ks> SELECT * FROM t WHERE c2=0 ALLOW FILTERING ;

 p | c1 | c2
---+----+------
 1 |  1 | null

(1 rows)
```

Cassandra:
```cql
cqlsh:ks> CREATE TABLE t(p int PRIMARY KEY, c1 counter , c2 counter );
cqlsh:ks> UPDATE t SET c1 = c1 + 1 WHERE p=1;
cqlsh:ks> SELECT * FROM t WHERE c2=0 ALLOW FILTERING ;

 p | c1 | c2
---+----+----

(0 rows)
```

/cc @jul-stas

**Comment by avikivity** [comment]
It's possible to view Scylla's behavior as correct.

```
UPDATE tab SET counter = counter + 1
WHERE pk = 'did not exist before'
```

will result in the counter being 1. This implies it was zero before. If it was NULL, it should remain NULL, since NULL + 1 = NULL.

A different way to achieve the same is to consider what a counter is: it counts events that happened. If no events happened, the counter is zero. Should the result be different for these two histories?

1.

```
UPDATE tab SET counter1 = counter1 + 1, counter2 = counter2 + 1
UPDATE tab SET counter1 = counter1 - 1, counter2 = counter2 - 1
```

vs.

```
UPDATE tab SET counter1 = counter1 + 1
UPDATE tab SET counter1 = counter1 - 1
```
?

In a non-counter column, NULL means we never wrote something (or we later deleted it). But counters don't reflect the last write, they reflect the entire history of writes, so a counter that was never written is positive information.

**Comment by dekimir** [comment]
> It's possible to view Scylla's behavior as correct.

That would imply that Cassandra's behaviour is not correct, wouldn't it?  And that means we should file a bug against Cassandra and test this argument there.

**Comment by avikivity** [comment]
It's also possible to view Cassandra's behavior as correct. It's not clear cut here.

**Comment by dekimir** [comment]
When c1c7fc0 hits master, the promoter will close this issue automatically.  Please feel free to reopen if you strongly believe Scylla shouldn't match Cassandra on this.

**Comment by jul-stas** [comment]
I can ask on the C* group and reopen if they decide to change this behavior on their side.
