### ISSUE TITLE
alternator: make http server elb-aware - idea for research 

### ISSUE THREAD

**Issue by rjeczalik** [scylladb/scylla#6514]
During today's cloud meeting we had an idea for an improvement to eliminate one hop on the typical network call path.

With LB-enabled Alternator cluster the call path looks like the following:

client -> load balancer -> coordinator -> replica

There's was an idea worth researching of using AppCookies for ELB (stickiness features): if the backend (scylla-server) sets proper session cookie, then ALB using it can route requests directly to the replica, eliminating one hop:

client -> load balancer -> replica

What would be needed is to research on how complex app cookie policies are - if ELB can do conditional routing - being able to decode & understand token:host map or entry supplied with cookie - then it could have a chance to work.

**Comment by rjeczalik** [comment]
cc @tzach @nyh

**Comment by nyh** [comment]
This will be very complicated to implement, for several reasons:

First, it's important to realize that usually, when we're talking about a "sticky session", the idea is send many requests from the same client to the same server. But here, you want to do something completely different: If a single client reads first partition "A" and then reads partition "B", you do **not** want both requests to arrive to the same Scylla server - you want to send the request to partition "A" to one Scylla node, and the request to partition "B" to a difference Scylla node - there is no stickiness whatsoever here.

The second problem is how would the ALB know which Scylla node to send the request to. This would require the ALB to, first, parse the JSON request and figure out which partition is being read, and second - to somehow learn from the Scylla cluster the ring, and which partition belongs to which node. Both of these needs are beyond what normal ALB solutions are capable of.

Finally, the situation you describe may differ from what we already have less than you might think. Let me explain:

DynamoDB has exactly what you are proposing. It's called a "frontend" node (they describe it in their video) - it parses the requests and passes them directly to the right node. In Scylla, the "frontend" nodes aren't separate nodes - each node can serve as a frontend node. BUT, if we really wanted, we could have separate frontend nodes - those will just parse requests, and as it already does today, forward the actual reads and writes to other nodes (via RPC) - it will send those requests directly to the right node, exactly as you wanted.
But the thing is - you will still need to load-balance these "frontend" nodes, because one isn't scalable enough or highly available enough. So whatever method you choose to load-balance them (dns+virtual ips, or a TCP load balancer) you could have also used to load-balance the load in the current case - where every node is a frontend node.

Therefore, I think we should close this issue, or you should explain it better why it's a valid idea. I'm starting to think more and more that a DNS based solution - plus additional trickery like virtual IP addresses - is the way to go, as it avoids exactly the hop you want to avoid (the request will arrive directly at the coordinator, without going through a "load balancer"). I don't think it's a coincidence that Amazon also use the DNS server the way that they do.

If my understanding is correct, I think we should close this issue.

**Comment by slivne** [comment]
closing this issue
