### ISSUE TITLE
Long bootstrap due to pagefaults from logalloc segment pool initialization

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#660]
When I start scylla with `-m1G` it boots almost instantly, but with default settings (I have `64G`) it takes about 30 seconds and the core is busy in the page fault handler inside `compact_zone`, see the flame graph below.

In both cases I use 2 cores: `-c2`.

![compact_zone](https://cloud.githubusercontent.com/assets/283695/11826504/1055c92e-a386-11e5-808c-0e893fd2e94b.png)

**Comment by avikivity** [comment]
It's an artifact of memory being fragmented. On a fresh boot it should not
happen.

Regardless, it would be nice to have empty segment constructors.

**Comment by pdziepak** [comment]
When a new zone is allocated a free list of segments is created and that's where all these page faults come from. The solution may be to create free list lazily by splitting the zone into two parts:

* in use – this would contain both used and used-and-freed segments, the free list will contain only segments in that 
* never used before – only free segments that's never been used before, obviously, there is no need to have free list for segments in this part the information where it begins is sufficient.

This should make bootstrap quick again and move all page faults from zone initialization to the moment when Scylla is already running. However, if it takes a significant amount of time for the kernel to get us a free page maybe it is better to have most of it done during bootstrap?

**Comment by avikivity** [comment]
Why not store the links in `segment_descriptor`? It wastes a bit of space but avoids the problem completely.

In general you are right about doing work up-front, but in this case, slow bootup is both annoying, and also these page faults cause a lot of memory to be consumed, which is bad for a developer machine.

Note that this is due to transparent hugepages, with small pages the problem would be smaller by a factor of 64.  But hugepages are worth 10-20%, so we keep them.

**Comment by pdziepak** [comment]
On 16 December 2015 at 10:10, Avi Kivity <notifications@github.com> wrote:

> Why not store the links in segment_descriptor? It wastes a bit of space
> but avoids the problem completely.
>

Yes, that's another option and since segment_descriptor has fields (namely,
pointer to the region owning the segment) that make no sense for free
segments this can be even done without wasting any more space.
Lazy construction of the free list wastes less cpu time when we are
shrinking zones that do not need defragmenting but I don't think these will
be very common cases as the space available for the lsa is expected to be
almost full most of the time and when they are not they free space is
likely to be fragmented.

**Comment by tzach** [comment]
@avikivity @tgrabiec look like this can be optimize post GA.
Let me know of you object

**Comment by avikivity** [comment]
It can give a bad first impression on a node with a lot of memory, if first start up takes a long time.

I'd tag it as nice to have for GA.  We can ship without it.

**Comment by avikivity** [comment]
Fixed by 252c5dfa5209a9bd83cc55b9ea15fbd4f32f870b.
