### ISSUE TITLE
compare_unsigned() passes null to memcmp

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#6797]
The function `compare_unsigned` [passes](https://github.com/scylladb/scylla/blob/branch-4.0/bytes.hh#L87) the result of `bytes_view::begin()` to `memcpy` without first checking whether that `bytes_view` is empty.  But when `bytes_view` is empty, this result is not a valid pointer, [violating](https://stackoverflow.com/questions/16362925/can-i-pass-a-null-pointer-to-memcmp) the C++ standard.

Under UBSAN, this results in the following error:
```
bytes.hh:87:20: runtime error: null pointer passed as argument 2, which is declared to never be null
```

**Comment by nyh** [comment]
I think this is a UBSAN **false positive**.
Unless I'm misunderstanding something, you are indeed passing an invalid pointer to memcmp(), but - the size parameter of this memcmp() is 0, and the memcmp(3) manual page guarantees that such a comparison always returns 0 (equality). I think the stackoverflow answer you found is wrong.

**Comment by dekimir** [comment]
> the memcmp(3) manual page guarantees that such a comparison always returns 0

1. The standard (which the stackoverflow link quotes) trumps any man pages.
2. The man page doesn't say nullptr argument value is valid; it makes an orthogonal claim about what happens when the third argument is zero.

**Comment by nyh** [comment]
@dekimir I wrote what I think in a new comment in that stackoverflow page https://stackoverflow.com/questions/16362925/can-i-pass-a-null-pointer-to-memcmp/62784620#62784620.

I think this is a "bug" in the standard: they wrote something like "0 is forbidden except in special cases" and then simply forgot to list memcmp as such a special case. There is no good reason why this case needs to be disallowed. Now you'll need to add a null check to your code just to avoid this perfectly reasonable call. And as I noted, all the manual pages (Linux and BSD) agree that memcmp() should always succeed for zero length. Other than quoting standard texts, I didn't hear any explanation of why memcmp(0,0,0) should be outlawed.

The sad thing is that instead of correcting the standard's text, gcc went and "enshrined" this bug by adding a useless _nonnull() attributes on memcmp (which can affect some obscure optimizations and the UBSAN warnings you saw).  I think they made a mistake, but it's done.

All that being said, clearly gcc thinks like you - that memcmp(0,0,0) is illegal. So I guess we have no choice but to avoid using this case, so you are absolutely right in that sense. It doesn't matter if this really violates the standard or just a gcc bug - we still need to work around it, just the same. You're right.

**Comment by avikivity** [comment]
test-only, not backporting.
