### ISSUE TITLE
alternator AttributesToGet breaks QueryFilter

### ISSUE THREAD

**Issue by brackxm** [scylladb/scylla#6951]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.2.rc1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker

A query with a QueryFilter gives incorrect results if AttributesToGet is used.
This may be due to the filtering being applied in the alternator layer.
Adding the filtered upon attributes to the AttributesToGet list makes the query return the correct results.

**Comment by slivne** [comment]
@brackxm thanks can you provide an example ?

**Comment by nyh** [comment]
Oops, good spot... As you suspected AttributesToGet returns only some of the attributes, but then the filter expression might require additional attributes to evaluate on... We should write a test reproducing this (easy) and then fix it (not hard, but need to figure out the least ugly way to do it).

**Comment by nyh** [comment]
I just sent a **test** patch to the mailing list, to reproduce this bug. The mail is titled "_alternator test: tests for combination of query filter and projection_". It demonstrates that indeed as @brackxm said, a combination of `QueryFilter` and `AttributesToGet` does not do the right thing. It also demonstrates that the newer variants of these two parameters - `FilterExpression` and `ProjectionExpression` - also work together incorrectly.

The new tests are:
```
test_query_filter.py::test_query_filter_and_projection_expression
test_query_filter.py::test_query_filter_and_attributes_to_get
test_filter_expression.py::test_query_filter_and_projection_expression
test_filter_expression.py::test_query_filter_and_attributes_to_get
```

Now that we have clear reproducing test (succeeding on DynamoDB, xfailing on Alternator), all that remains is to fix the bug :-)

**Comment by psarna** [comment]
We had an identical issue in the CQL layer :) Which resulted in https://github.com/scylladb/scylla/blob/c4cb3817cf44ce9f884e0f8791e095d9b7d1dede/cql3/statements/select_statement.cc#L1579 
, and a similar trick should be applied to alternator.

**Comment by nyh** [comment]
If we do use the trick which you proposed (adding the filtered columns to the list of columns to fetch), we also need to remember to remove these extra attributes from the JSON response at the end. My test even verifies that we don't forget that - it filters on column 'x', asks for column 'y', and then verifies that only column 'y' was actually returned, nothing else.

However, there might be an alternative, simpler implementation: An important observation is that in Alternator, all (or most, in case of LSI) attributes are in a single map column - ":attrs". So the lower Scylla levels forces us (unless I'm misremembering?) anyway to fetch all of attributes (well, except when the user asks to project just the key columns...). So if we already read all these columns, we can create the JSON with all of them, pass the filter function on the complete result first - and only then pass the "projection" function which will remove some of the attributes from the result.

Or, do you think the small amount of extra work of converting a few attributes to JSON only to then remove them, should be avoided? Note that O(...) wise, it's the same amount of work - we still need to read and process all the attributes - we just avoid one specific bit of work (putting into the JSON) for these unprojected attributes. So I wonder if it's worth optimizing for this case? @psarna what do you think?

**Comment by psarna** [comment]
Yes, we do need to fetch all attributes from `:attrs`, at least until Scylla exposes a way of fetching only specific elements from collections (or, until we change the backing implementation to use something else than collections).

Regarding the alternative solution, we do still need to implement the pessimistic case when LSI are present, right? So relying on the fact that `:attrs` is always fetched is not enough, since some columns may be instantiated outside of `:attrs`. Also, if we ever implement a `JSON` document type in Scylla and decide to move alternator to it, the trick would stop working anyway. So perhaps adding filtered columns to the list of columns to fetch, and then removing them from the response is the way to go? That's how CQL works too (in a way). And I think it's quite easy to obtain a set of all identifiers used by alternator-side filtering (e.g. by making the `filter` class from `executor.cc` track them) - and from there we can count a set of identifiers used for "filtering only", and just remove it later.

**Comment by nyh** [comment]
> Yes, we do need to fetch all attributes from `:attrs`, at least until Scylla exposes a way of fetching only specific elements from collections (or, until we change the backing implementation to use something else than collections). 
> Regarding the alternative solution, we do still need to implement the pessimistic case when LSI are present, right? So relying on the fact that `:attrs` is always fetched is not enough, since some columns may be instantiated outside of `:attrs`.

My point wasn't about "relying" on all the columns being fetched - it's about deliberately Scylla asking to fetch all of them, and not trying to be clever and dropping some of them half-way as we do today - after reading them already, and instead only drop them at the end (a step which we will need to have in any case).

But if we don't want to give up any shred of potential performance, what we can indeed do is:

1. Calculate which columns we need Scylla to read. In 99% of the use cases, it will be *all* columns. It can be not all columns only when there is LSI (or today, GSI) and the SI keys (regular columns) which are not need for neither filtering nor projection.
2. After reading what Scylla gave us, we create a JSON - but we can drop some of the attributes before putting them in the JSON. Specifically, we can drop attributes that aren't projected - but only if they aren't used in filter.
3. Finally, after the filtering goes over this JSON, the final step is to remove specific attributes that we kept just for filtering, but weren't required for the projection.

I'm just wondering whether we really need or want to make such efforts to improve performance in esoteric cases. But maybe it's worth it to just do "the right thing" (performance-wise) instead of trying to shave off a few lines of code. If we do implement this "optimal" solution, we'll probably need to write a couple of more test cases for additional corner cases, specifically checking LSI keys for example.

**Comment by psarna** [comment]
Oh, ok, now I get the idea. I'm fine with unconditionally fetching all columns and then only projecting the needed attributes. If it ever becomes a problem, we would only need to *add* some lines to fetch less than necessary, while the projecting part likely remains the same, so there debt we create by not optimizing all cases is really small.

**Comment by nyh** [comment]
I sent a pull request for this issue, https://github.com/scylladb/scylla/pull/7328, but want to comment on something I said above.

The current code always fetches the entire item from Scylla - regardless of which parts are projected - even if just the key columns are wanted, `:attrs` is nevertheless fetched anyway. We did not have this optimization at all (it's a TODO for GetItem, not even mentioned for Query or Scan).

The pull request does NOT add this optimization. That's not the purpose of this issue - which was to fix a functional bug (which we fix), not to optimize the performance.

However, the pull request does add tests designed so that if we ever add this optimization, its special cases (i.e., wanting to not fetch `:attrs`)  will be tested.

**Comment by nyh** [comment]
@penberg any idea why this issue did not automatically get tagged as a "backport candidate"?
Anyway, tagged it now. We should backport it to 4.3 and 4.2 - earlier versions did not yet have the filtering support.

**Comment by nyh** [comment]
Backported to next-4.3 (commit 4857116688ff08a8d7711c470ea44c8fe8889b2a) and to next-4.2 (commit abaf6c192a394ed55103052e6e561bdf9fc66da3).
