### ISSUE TITLE
nodetool won't fail in refreshing in main SSTable directory, no db error raised

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7022]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200810.52ec0c683  & 4.2.rc2-0.20200810.0ce3799187c
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Loding SSTable files from main directory isn't supported by Scylla from 4.1
We disabled it by https://github.com/scylladb/scylla/commit/70e5252a5d5183a51635154b3aa602a4812c67ce

In my test result, it's only unsupported with Scylla 4.1 (4.1.4-0.20200809.442d7bf9ff), `Nodetool refresh` will fail and we can find error in nodetool output and db log.

```
### Nodetool error:

Nodetool command '/home/amos/.ccm/scylla-repository/unstable/branch-4.1/2020-08-09T22_10_12Z/scylla-tools-java/bin/nodetool -h 127.0.91.1 -p 7191 refresh -- keyspace1 standard1' failed;
exit status: 1;
stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/sstables/keyspace1' failed:
 Failed to load new sstables: std::runtime_error (Loading SSTables from the main SSTable directory is unsafe and no longer supported. 
You will find a directory called upload/ inside the table directory that can be used to load new SSTables into the system)
See 'nodetool help' or 'nodetool help <command>'.
```

```
### DB errors

INFO  2020-08-12 01:53:53,532 [shard 0] storage_service - Loading new SSTables for keyspace1.standard1...
INFO  2020-08-12 01:53:53,533 [shard 0] table - Reshuffling SSTables in /home/amos/.dtest/dtest-b9p2ejqn/test/node1
/data/keyspace1/standard1-9bb25460dc3e11eaa510000000000001...
ERROR 2020-08-12 01:53:53,533 [shard 0] storage_service - Loading of new tables failed to keyspace1.standard1 due to Loading SSTables from the main SSTable directory is unsafe and no longer supported.
 You will find a directory called upload/ inside the table directory that can be used to load new SSTables into the system
INFO  2020-08-12 01:53:53,533 [shard 0] storage_service - CF keyspace1.standard1 at shard 0 had SSTables writes disabled for 793 usec
INFO  2020-08-12 01:53:53,533 [shard 1] storage_service - CF keyspace1.standard1 at shard 1 had SSTables writes disabled for 772 usec
```

#### Problem

The refreshing in main directory will still succeed with Scylla master and 4.2, the snapshot won't be loaded, but nodetool won't fail, and no db error raised.

/CC @raphaelsc @roydahan

**Comment by raphaelsc** [comment]
refresh is now ignoring the SSTables placed in the main table dir. The question is: was the period of deprecation long enough? it's been only 3 months since we deprecated the feature.

I think we unintentionally did this after the off-strategy changes for refresh. Not sure.


@slivne @avikivity @bhalevy

**Comment by bhalevy** [comment]
> refresh is now ignoring the SSTables placed in the main table dir. The question is: was the period of deprecation long enough? it's been only 3 months since we deprecated the feature.
> 
> I think we unintentionally did this after the off-strategy changes for refresh. Not sure.
> 
> @slivne @avikivity @bhalevy

I think we should fail refresh like we did before rather than just ignore sstables in the main directory since those may cause errors due to clash of generation numbers, or will seem to appear out of nowhere after restart.

**Comment by avikivity** [comment]
I think it's fine not to support it. We added upload/ many years ago.

**Comment by amoskong** [comment]
> I think it's fine not to support it. We added upload/ many years ago.

We don't expect refreshing in main directory is re-supported, but raise error when user try to do that, 'nodetool refresh' command should fail.

**Comment by raphaelsc** [comment]
> > I think it's fine not to support it. We added upload/ many years ago.
> 
> We don't expect refreshing in main directory is re-supported, but raise error when user try to do that, 'nodetool refresh' command should fail.

scylla really should never touch table's dir when scylla is up. we no longer lock writes for table on refresh, so detecting new sstables placed in main dir by user is now susceptible to races. we're deciding not to fix this, and all users should always place their new sstables in upload dir. closing this issue with a wontfix tag.

**Comment by bhalevy** [comment]
We also need to disable the dtest that was added.

To add some details on top of what @raphaelsc said above: we used to lock the table files for writes during refresh so no new sstables were created (or deleted) during the operation. Although this allowed us to detect sstables added by the user, we really don't want to stop writes during refresh.  With offstrategy compaction we don't lock the main table directory and don't even examine it since the sstables in the upload dir are preprocessed before adding the to the main dir.  So regular operations like memtable flush or compaction will keep creating sstables in that dir.

Note that in steady state operation this happens too so it's unreasonable for any user to copy sstables into the base table directory while the node is up and running.  They must be copied only into the upload dir.
