### ISSUE TITLE
 compaction_manager - compaction failed: read exception

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#712]
ERROR [shard 7] compaction_manager - compaction failed: read exception: seastar::broken_pipe_exception (Broken pipe), write_exception: std::system_error (error system:17, File exists)
ERROR [shard 7] compaction_manager - compaction failed: read exception: std::system_error (error system:17, File exists)

**Comment by avikivity** [comment]
Did we not recover from this error?

**Comment by nyh** [comment]
"recovering" from this error not only means not crashing, but also trying compaction again later. We do have code to do this (see "retry" in compaction_manager.cc) but we need to verify that indeed compaction eventually happens so this "retry" code is actually working as expected.

**Comment by benoit-canet** [comment]
Avi: no It does not crash but it look nasty when you see it in the log.

I think I will write a patch with a human readable error message to signal to the user that everything is fine.

**Comment by nyh** [comment]
On Sun, Dec 27, 2015 at 6:01 PM, Benoît Canet <notifications@github.com>
wrote:

> Avi: no It does not crash but it look nasty when you see it in the log.
>
I think that every error you inject with your random-error-injector should
end up as an "ERROR" in the log, saying what broke because of this injected
error.
So we shouldn't really be surprised when this happens.

> I think I will write a patch with a human readable error message to signal
> to the user that everything is fine.
>

This makes sense. If you can add "will retry compaction later" or something
along that lines, perhaps it will make the user feel more easy. But then
again, if we ever have this problem - because of a hardware problem or a
bug in our code - I'm not sure the user should feel more easy ;-)

**Comment by avikivity** [comment]
How can you tell that everything is fine?  Maybe it isn't.

**Comment by slivne** [comment]
related to #705, #706

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.

**Comment by avikivity** [comment]
Do we have an automatic test with Ch*FS?
