### ISSUE TITLE
'scylla' systemd unit encompassing both scylla-server and scylla-jmx

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#726]
`systemd start scylla`

  starts scylla-server and scylla-jmx

`systemd stop scylla`

  stops both of them

**Comment by lmr** [comment]
The second behavior is easy to understand by looking at the systemd documentation:

http://www.freedesktop.org/software/systemd/man/systemd.service.html

Excerpt: "Unless DefaultDependencies= is set to false, service units will implicitly have dependencies of type Requires= and After= on sysinit.target, a dependency of type After= on basic.target as well as dependencies of type Conflicts= and Before= on shutdown.target. These ensure that normal service units pull in basic system initialization, and are terminated cleanly prior to system shutdown. Only services involved with early boot or late system shutdown should disable this option."

Looking at the unit config file for both services:

    cat scylla/dist/redhat/systemd/scylla-server.service 
    [Unit]
    Description=Scylla Server
    After=network.target libvirtd.service

    [Service]
    Type=simple
    LimitMEMLOCK=infinity
    LimitNOFILE=100000
    LimitAS=infinity
    LimitNPROC=8096
    EnvironmentFile=/etc/sysconfig/scylla-server
    ExecStartPre=/usr/lib/scylla/scylla_prepare
    ExecStart=/usr/lib/scylla/scylla_run
    ExecStopPost=/usr/lib/scylla/scylla_stop
    KillMode=process
    Restart=no

    [Install]
    WantedBy=multi-user.target

    cat scylla-jmx/dist/redhat/systemd/scylla-jmx.service 
    [Unit]
    Description=Scylla JMX
    Requires=scylla-server.service
    After=scylla-server.service

    [Service]
    Type=simple
    EnvironmentFile=/etc/sysconfig/scylla-jmx
    User=scylla
    Group=scylla
    ExecStart=/usr/lib/scylla/jmx/scylla-jmx -l /usr/lib/scylla/jmx
    KillMode=process
    Restart=always

    [Install]
    WantedBy=multi-user.target

Then the behavior is as told to systemd, and they're following the docs recommendation that "Only services involved with early boot or late system shutdown should disable this option (that is, set DefaultDependencies to false)".

I'm assuming you opened this bug because you want to do some testing with jmx turned off or something. But for the regular user, the unit files configuration seem appropriate.

**Comment by tzach** [comment]
@avikivity @syuu1228 this is already working.
Can we close this?

**Comment by tzach** [comment]
@avikivity @syuu1228 this is already working.
Can we close this?
