### ISSUE TITLE
redis 'exists' command fails with lots of keys

### ISSUE THREAD

**Issue by locked** [scylladb/scylla#7273]
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 6438c7cc2de49fe6c48bedd81a7b75e36ec00a7f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

When trying to add a test case for the 'exists' command using lots of keys, I found that it was passing with redis but failing with scylla, returning always the same (wrong) number of keys. This number varies depending on the size of the keys, so it seems linked with the size of the network packet, or something of fixed size.

The test:
```
def test_exists_lots_of_keys(redis_host, redis_port):
    r = connect(redis_host, redis_port)
    keys = []
    for i in range(0, 30):
        k = random_string(11)
        v = random_string(10)
        r.set(k, v)
        keys.append(k)
    assert r.exists(*keys) == len(keys)
```

Failing with:
```
>       assert r.exists(*keys) == len(keys)
E       AssertionError: assert 27 == 30
E        +  where 27 = <bound method Redis.exists of Redis<ConnectionPool<Connection<host=127.0.0.1,port=6973,db=0>>>>(*['zmmwvzovtad', 'ssyddizbwtd', 'wxuhojewfcj', 'tgayovfytgx', 'kotpccwkzls', 'ahbcaequbec', ...])
E        +    where <bound method Redis.exists of Redis<ConnectionPool<Connection<host=127.0.0.1,port=6973,db=0>>>> = Redis<ConnectionPool<Connection<host=127.0.0.1,port=6973,db=0>>>.exists
E        +  and   30 = len(['zmmwvzovtad', 'ssyddizbwtd', 'wxuhojewfcj', 'tgayovfytgx', 'kotpccwkzls', 'ahbcaequbec', ...])

```

If I increase the size of the keys, it fails with a smaller number of existing keys and vice versa.

**Comment by nyh** [comment]
@syuu1228 noticed on https://github.com/scylladb/scylla/pull/7903 that if we increase the connection's input stream buffer size, this problem goes away. That's an easy workaround, but I suspect that with a bigger buffer, the problem is still there - it just needs an even larger buffer to happen.
My guess is that the real bug is that our `redis_protocol_parser` doesn't correctly support parsing over multiple buffers with some pieces of the protocol crossing buffer boundery. I don't know why, though.

**Comment by avikivity** [comment]
Redis is not production ready, so not backporting.
