### ISSUE TITLE
Possible live lock: Timed out reads are not retired once got passed the read concurrency semphore

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#7340]
Once a read get passed the read concurrency semaphore it will be run to completion even though it's corresponding cql
request has been timed out.
If the I/O back-end is slow enough, this can cause a live lock where each new query times out since the queue for the
read concurrency is filled with stale request that will be run to completion and by the time a new query gets served it times out
too.
 
/cc @vladzcloudius @denesb

**Comment by denesb** [comment]
@eliransin note that the read is still not timeout-out when it is dequeued from the semaphore, as the semaphore's queue is an expiring one, so reads will time out while doing I/O. So technically the reads in the semaphore's queue are not stale, but this doesn't change the end result, we can still arrive at a live-lock as you described.

**Comment by denesb** [comment]
We need to implement timeout for I/O, which needs I/O cancellation implemented in seastar. AFAIK @bhalevy was looking at this at some point.

**Comment by bhalevy** [comment]
> We need to implement timeout for I/O, which needs I/O cancellation implemented in seastar. AFAIK @bhalevy was looking at this at some point.

@xemul how hard would that be?

**Comment by xemul** [comment]
@bhalevy , depends on the desired API. Current `file::read/write_dma` returns a future on which the caller can wait. We may want `file::read_dma_with_timeout(pos, buffer, len, prio, timeout)` so that the engine will resolve the future into exception after a timeout. Or we may want `file::read_dma_with_timeout(pos, buffer, len, prio, &handle)` with the ability to call `handle::abort()` or alike. Nonetheless, this will only work for requests that are in queue, the kernel `io_submit` doesn't have any timeout options, submitted IO will sit in the kernel up to its finish.

As far as I understand, the beneficiary of the expiration is the cql request, so when it times out, both -- the read concurrency semaphore and IO (if any) should be aborted or canceled, at least eventually. Right now the read concurrency semaphore seems to have the API of the 1st kind -- when the waiting starts it accepts a timeout and resolves the future to exception if timeout expires. Also in this case no IO is (should be) started. This in turn means, that we're in trouble when cql request times out _after_ the read concurrency semaphore had passed and queued the request. And what we want is to somehow withdraw the request from the stack without doing any real IO.

Right?

If yes, then the similar API for IO -- with the timeout argument -- seems to fit.

**Comment by avikivity** [comment]
@xemul the trick is to use a cancellation handle. The caller creates a cancellation handle and passes it to all the I/O it generates. If the caller wants to abort, they pull the cancellation handle. I/O that is queued will not be submitted, and I/O that is in the kernel can be cancelled (with io_cancel or the equivalent io_uring call).

**Comment by avikivity** [comment]
A cancellation handle can be similar to abort_source.

**Comment by xemul** [comment]
@avikivity , AFAIK `io_cancel()` doesn't really work, and can only be used to abort `IO_CMD_POLL` (oh, grepping also found some fancy USB stuff).

But anyway, the API with abort_source-like handler seems better to me too, should the read concurrency semaphore use it as well, or is there any other reason for independent wait timeout on it?

**Comment by denesb** [comment]
@xemul it doesn't have to be tied to the semaphore. We pass the timeout all the way down to the sstable reader. I think it'd be best to initiate the timeout there.

**Comment by denesb** [comment]
In fact we should implement timeouts in all leaf readers: sstable reader, memtable reader and cache reader.

**Comment by xemul** [comment]
@denesb , the question is -- why should every component have its own timeout instead of shared abort handle that's triggered from the top of this tree?

**Comment by denesb** [comment]
Because then we'd have to change all our existing code to pass down an abort handle. And we can't get rid of the timeout either, as the high level readers need it to pass it to the semaphore. So we'd end up with two parameters being passed around, one of which is used in the high layers, and one which is used in the low layers.

**Comment by denesb** [comment]
Although.... an abort handle passed around can be useful for [OOM killing reads] (https://github.com/scylladb/scylla/issues/4296).

**Comment by xemul** [comment]
> And we can't get rid of the timeout either, as the high level readers need it to pass it to the semaphore

They can use the abort handle too, can't they?

**Comment by denesb** [comment]
Actually we have another "thing" we pass around all the way to the bottom, the reader permit. We can tie aborting and timeout to it.

**Comment by xemul** [comment]
I guess we need to be careful not to wrap all this stuff into an abstract "read_context" thing passed _everywhere_ by reference and having all the diverse zoo onboard :D Gophers, btw, [had already come to this](https://golang.org/pkg/context/).

**Comment by denesb** [comment]
After considering this some more I think it *would* be better to handle abort/timeout on the semaphore level, though the reader permit. It would make the timeout parameter superfluous, but it kinda already is because nobody uses it past the restricted reader layer. Once we move the semaphore to the front, we can remove the timeout from the reader interface (still need to figure out how to pass it across shards).

**Comment by tgrabiec** [comment]
Duplicate of https://github.com/scylladb/scylla/issues/2927 ?

**Comment by denesb** [comment]
> Duplicate of #2927 ?

Yes.

**Comment by avikivity** [comment]
> I guess we need to be careful not to wrap all this stuff into an abstract "read_context" thing passed _everywhere_ by reference and having all the diverse zoo onboard :D Gophers, btw, [had already come to this](https://golang.org/pkg/context/).

There's the read_permit that's everywhere, and is shared by all readers serving the same read.

**Comment by slivne** [comment]
@eliransin please consolidate the info into a single ticket #2927 and close the other)

**Comment by avikivity** [comment]
> Because then we'd have to change all our existing code to pass down an abort handle. And we can't get rid of the timeout either, as the high level readers need it to pass it to the semaphore. So we'd end up with two parameters being passed around, one of which is used in the high layers, and one which is used in the low layers.

We have reader_permit, where we can stuff the abort handle (and the timeout?)

**Comment by avikivity** [comment]
In fact we don't need the timeout of we have the abort handle. We set a timer (for the entire query) that expires on the timeout, and when it expires, we pull the abort handle. So the abort handle replaces the timeout.

**Comment by eliransin** [comment]
@xemul just FYI, I moved this issue to #2927
