### ISSUE TITLE
Repair-based streaming is "best effort" which leads to linearizability violation during nodetool removenode

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#7359]
Recently Scylla introduced repair-based streaming - a feature which allows to stream a token range from all available replicas, thus increasing consistency of the new node during streaming. However, repair-based streaming does not insist on using at least a QUORUM of replicas, which leads to lost data if streaming is accompanied with temporary or permanent network failure.

How to repeat:

1. Create a cluster of 5 nodes.
2. Create a table with replication factor = 3
3. Stop or partition away node 1.
4. Insert 100 records into the table, ensuring all nodes store data ranges using QUORUM or LWT.
5. Start the stopped node or resolve the network partitioning.
6. Kill and remove with nodetool removenode node 2 concurrently with stopping or partioning away node 3. This leads to node 1 being used exclusively to stream some ranges, thus replicating missing ranges to a quorum of nodes.
7. Observe removenode passes successfully, even though some token ranges have lost quorum. The linearizability is permanently violated, since once removenode completes the troubled ranges will begin accepting new QUORUM or LWT writes, based on empty history, which corrupts data even if node 2 later rejoins the cluster.
8. Read data with SERIAL or QUORUM and observe linearizability violation. Some keys are missing.

Suggested fix:
- nodetool removenode should block or retry until networking partition heals and not continue in absence of quorum.
- the current behavior should be moved behind a switch, something like --best-effort

Please note that once we begin streaming from a quorum, we do not need the concept of "mandatory" node,
i.e. removenode becomes less different from decommission, and https://github.com/scylladb/scylla/issues/7087 could be fixed by reverting the change that broke it.

**Comment by kostja** [comment]
Dtest test case: https://github.com/kostja/scylla-dtest/tree/gh-7359

**Comment by slivne** [comment]
nodetool remoenode supports flags today: force, status - we should add another option aligned with that (I am not sure we support the other flags - but lets not override them).

I am not sure weshould insist for ever on removenode - its better to fail at some point and return failure in my view

**Comment by asias** [comment]
In your procedure above, both n2 and n3 are down. With RF = 3, consider a range is owned by n1, n2, n3 before the removenode, and is owned by n1, n5, n3 after the removenode ops. n1 is the only live replica. The problem is not we do not stream from quorum replicas, we actually ask to stream from all possible replicas. The problem is there is only one live replica.

We should reject the removenode ops if we want to be safe. But currently removenode ops is designed to be "best-effort", it favours to  remove  the node from the cluster even if some of nodes failed to stream the data. There is a lot of work to do if we want to make removenode to be 100% safe. 

On the operation side, we should not perform remvoenode ops when a node is temporarily down. A much safer option would be running replace node operation or replace + decommission ops.

**Comment by asias** [comment]
I do agree we should be safe by default and allow user to continue with best effort flag explicitly.

**Comment by asias** [comment]
I do not like the idea to block or retry until networking is healed though. It is asking for trouble (We had a lot of retry logic for streaming and repair and it is painful to debug and reason about). We should fail fast and allow user to fix the network or the node and retry the operation.

**Comment by asias** [comment]
Alternatively, we might consider to drop the remvenode command completely. It is much more complicated operation than all the others. It can be replaced by a replace + decommission operation.

**Comment by kostja** [comment]
Verified that #7243 does not reproduce with the fix.

**Comment by kostja** [comment]
Could we expedite reviewing & merging this pull request?

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
