### ISSUE TITLE
coredumps are not generated on AMI 0.13

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#736]
AMI:

sl-scylla-development-20151229.ebebaa5 (ami-08988169)

machine type i2.xlarge

1. the directory for coredumps is not created at boot / reboot of an instance and as such no coredumps are written

2. the coredumps are created with gzip and on a large machine this will take forever

3. need to validate that coredumps can be created as a post install step

the machine was started with cassandra-test-and-deploy

**Comment by penberg** [comment]
@slivne Is this fixed by https://github.com/scylladb/scylla/commit/6316fedc0a3f9f4e05cbec1d84cf6f9a47a8182d?

**Comment by slivne** [comment]
no its not a complete fix its a workaround - theere is code to create this
directory in the same part that creates the XFS raid - not sure why it is
not doing that.

In addition @avikiviy requested additional changes and had additional
comments (e.g. no gzip) I think he may also want to go back and use
coredumpctl were available - yet he needs to comment on this issue.

**Comment by penberg** [comment]
Ping @avikivity

**Comment by avikivity** [comment]
I think on a machine that was taken over by systemd we want `coredumpctl` to work, users will expect it.  It will also be in ubuntu 16.04 LTS so we can converge when we switch to it.

No gzip because it indeed takes a very long time and the machine is out of memory while it is compressing.

(btw pigz is better than gzip for this).

Validation should be as part of testing, no need for every machine to generate a core and alarm the operator.

**Comment by syuu1228** [comment]
I changed coredump handler on Fedora/CentOS/Ubuntu for following reasons:
- To dump on RAID disk on AMI, since fewer space on root disk (use /var/lib/scylla/coredump instead of /var/lib/systemd/coredump)
- To handle coredump on Ubuntu
- Use same settings on all distributions

(The commit was https://github.com/scylladb/scylla/commit/9b4d0592fa69e9f7debbb916e3e2660916c1f1b5)

We can switch back to systemd-coredump, but we don't able to use /var/lib/scylla/coredump unless creating symlink on /var/lib/systemd/coredump, and Ubuntu 14.04 doesn't have systemd-coredump (they have Apport, but it's more like abrt, desktop centric bug reporter)

We can skip gzip if we have enough disk space, and we won't need handler script if we don't gzip the coredump, we can specify coredump directory directly on sysctl.
(If we want to hook the crash and send a bug report in future, better to have a handler script but maybe it is another topic)

**Comment by syuu1228** [comment]
If decide to back to systemd-coredump on Fedora/CentOS, what do we do for Ubuntu?
Probably keep using current settings but don't use gzip, directly dump unzipped core?

**Comment by syuu1228** [comment]
Fixed at 8886fe739375bee501b6e57f34bf0510da108f5c
