### ISSUE TITLE
Compaction - Deletion of obsolete sstables on startup

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#74]
On startup, recognize already compacted sstables that haven't been deleted, ignore them and delete them. One way to do this is to use the list of parent sstables in the compaction metadata. This has a problem with leveled compaction, where the output of a compaction is split across several sstables. The other option, used in newer Cassandra, is to remember ongoing compactions in a separate table. See https://issues.apache.org/jira/browse/CASSANDRA-5137 (pre 2.0) and
https://issues.apache.org/jira/browse/CASSANDRA-5151 (Cassandra 2.0)

**Comment by slivne** [comment]
@raphaelsc whats the status of this ?

**Comment by slivne** [comment]
@raphaelsc - do we have code for this ?

In any case I think we can move it to post GA

**Comment by avikivity** [comment]
I don't think we need this. For non-leveled compactions, there is a a tiny window between the sealing of a new sstable and the deletion of old sstables where this can happen. For leveled compactions, the window is larger (since multiple sstables are written) but the impact is low, since the sstable size is small.

**Comment by raphaelsc** [comment]
On Thu, Jun 15, 2017 at 11:11 AM, Avi Kivity <notifications@github.com>
wrote:

> I don't think we need this. For non-leveled compactions, there is a a tiny
> window between the sealing of a new sstable and the deletion of old
> sstables where this can happen. For leveled compactions, the window is
> larger (since multiple sstables are written) but the impact is low, since
> the sstable size is small.
>
the only problem is overlapping after a failed compaction. For example, if
L0->L1 compaction fails in the middle, it may happen that partially created
sstables in L1 will overlap with existing L1 ones. @gleb-cloudius
<https://github.com/gleb-cloudius> reported it in #2416. The problem can be
easily fixed by deferring sealing to the very end.

**Comment by raphaelsc** [comment]
On Thu, Jun 15, 2017 at 11:27 AM, Raphael S. Carvalho <
raphaelsc@scylladb.com> wrote:

>
>
> On Thu, Jun 15, 2017 at 11:11 AM, Avi Kivity <notifications@github.com>
> wrote:
>
>> I don't think we need this. For non-leveled compactions, there is a a
>> tiny window between the sealing of a new sstable and the deletion of old
>> sstables where this can happen. For leveled compactions, the window is
>> larger (since multiple sstables are written) but the impact is low, since
>> the sstable size is small.
>>
> the only problem is overlapping after a failed compaction. For example, if
> L0->L1 compaction fails in the middle, it may happen that partially created
> sstables in L1 will overlap with existing L1 ones. @gleb-cloudius
> <https://github.com/gleb-cloudius> reported it in #2416. The problem can
> be easily fixed by deferring sealing to the very end.
>

@avikivity This issue can be closed, I think.

**Comment by raphaelsc** [comment]
@slivne i think this can be closed.

**Comment by glommer** [comment]
@raphaelsc claims this issue can be closed, but it is still open (I don't have closing permissions)
