### ISSUE TITLE
release 0.14: installing on ubuntu requires configuration of postfix if not previously done

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#741]
Installing scylla-server from https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/branch-0.14/33/scylla.list on a clean ubuntu 14.04 AWS server 

![screenshot from 2016-01-02 22 46 11](https://cloud.githubusercontent.com/assets/3465480/12076044/c06ba052-b1a2-11e5-97b8-6b7112869990.png)

Once configuration is done / skipped the installation completes ok

**Comment by tzach** [comment]
The following install postfix on Ubuntu without prompt.
We can add it as a temp bypass to Ubuntu install till the issue is solved.

```
sudo debconf-set-selections <<< "postfix postfix/mailname string my.hostname.com"
sudo debconf-set-selections <<< "postfix postfix/main_mailer_type string 'No configuration'"
sudo apt-get install -y postfix
```

**Comment by syuu1228** [comment]
Do we really need 'default-mta' or 'postfix' package for scylla-server/jmx/tools? I'm wondering which package depends on it (I don't think ours, but probably our dependency)
And I think it is normal to shows up such prompt when you installing MTA at first time on debian based systems.

**Comment by slivne** [comment]
The issue did not exist in 0.13 as far as I know - so this was introduced by some change that we did or some change in a package we depend on - you can check the diff between the version to find the source.

You can also install 0.13 from the s3 drive holding the packages (deb/ubuntu/dists/trusty/scylladb/multiverse/binary-amd64)

**Comment by syuu1228** [comment]
This comes from 'dist: provide generic scylla setup script', because I added mdadm on scylla-server dependency. (mdadm may sends notification mail of RAID status)
I will add defconf-set-selections on scripts/scylla_install_pkg which @tzach mentioned here, but it only mute the messages when user use the script to install scylla-server.

User may manually downloads scylla.list then run apt-get install scylla-server, debconf still shows up to ask postfix configuration.
It is distribution default behavior, always happen when we run 'apt-get install mdadm', so we have no choice.

**Comment by avikivity** [comment]
Can we remove the mdadm dependency?  And then if we need to set up RAID and mdadm is not installed, error out and ask for it.

**Comment by syuu1228** [comment]
Ah, we can install mdadm in scylla_raid_setup script, and we can do silently using 'defconf-set-selections'. Probably it's better solution than my previous patch.
