### ISSUE TITLE
scylla service fail silently if XFS is not used and developer-mode not set 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#743]
Starting from
https://github.com/scylladb/scylla/commit/c26689f32588d69d4a6b4844a3caa38eb2e8c530 scylla service fail if XFS is not used and developer-mode not set.
This is a good feature, as running without XFS is not recommended.
However, as most users does not use XFS, installing from packages and running scylla will often fail.
The error in the log is clear, but not every users will know to look in the log.

A better UX will be for the `service scylla-server start` command to fail, and return the error to the terminal foreground.

**Comment by avikivity** [comment]
@syuu1228 I think we can implement this with `sd_notify()` and `Type=notify`, see http://www.freedesktop.org/software/systemd/man/sd_notify.html.

**Comment by nyh** [comment]
@avikivity is this "sd_notify()" thing enough for the behavior which tzach asked for (and I agree with him)? I.e., that running "service scylla-server start" (or systemctl start scylla-server.service) will immediately notify the person running it of the problem. Does "systemctl start" wait for this notification? I assume it doesn't because we didn't have such a notification until now, as far as I understand, and still "systemctl start ..." didn't hang forever.

Traditionally, before systemd, there were two solutions to this problem:

1. The application starts in the foreground, read its configuration file and does some quick checking, and when everything is in order, and the application is sure it can start serving requests, it forks and the original process returns, so the startup script finishes quickly but can show failure. I'm not sure how easy this would be to do in Seastar's multi-threaded context, but we can definitely have some rudemantary tests (like XFS filesystem) in main() before ever starting any threads, and fork-and-return at that point.

2. An alternative solution is for the application to never fork itself (i.e., what scylla does now) and instead the /etc/init.d *script* put it in the background, and then polls the application via its log (or whatever) to wait until it started up correctly, or failed to start up.

I don't know how any of this, if at all, translates to systemd.

**Comment by avikivity** [comment]
`sd_notify()` is similar to 2 (it is part of systemd).

**Comment by avikivity** [comment]
@nyh you tell systemd to wait for it in the .service file (Type=notify)

**Comment by syuu1228** [comment]
Avi, can we use the code calling sd_notify() on Ubuntu 14.04? Or maybe we should do "#ifdef systemd" for sucn distributions?

**Comment by syuu1228** [comment]
Ah, you already merged the code, just realized that

**Comment by avikivity** [comment]
Can use `supervisor_notify` with a check for upstart

**Comment by syuu1228** [comment]
@tzach This is fixed, please close

**Comment by tzach** [comment]
@syuu1228 is this fix on Ubuntu as well?
