### ISSUE TITLE
Local secondary index syntax error

### ISSUE THREAD

**Issue by chitti457** [scylladb/scylla#7446]
I am trying to create local secondary index 

`CREATE INDEX ON test((version,id),t_id)`  but I am keep getting error `<stdin>:1:SyntaxException: line 1:42 missing ')' at '<missing '`

[Here is the documentation](https://docs.scylladb.com/using-scylla/local-secondary-indexes/)

Scylla version (or git commit hash): scylla-enterprise 2019.1.17

**Comment by nyh** [comment]
As the documentation you pointed to says, the Local Secondary Index was added in Scylla open-source version 3.1.
Scylla Enterprise 2019.1 was based on on Scylla open-source version 3.0 (see https://www.scylladb.com/product/release-notes/scylla-enterprise-release-2019-1-0/), so this feature was not yet available there.

So I'm closing this issue here, but @tzach or @lauranovich - please consider whether documentation such as https://docs.scylladb.com/using-scylla/local-secondary-indexes/ should also mention Scylla Enterprise versions which introduced certain features, not just open-source versions.
