### ISSUE TITLE
ami: increase journal space allocation

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#750]
See journald.conf SystemKeepFree, SystemMaxUse.  AMIs have small root filesystems so we need to increase them.

**Comment by syuu1228** [comment]
@avikivity What size would be enough for journal space?
SystemMaxUse seems 10% of root disk size by default, so it is 600MB on our AMI default root disk size (6GB), is it still not enough?
Ι suppose real problem is our too small default root disk size, maybe we should increase it to 10GB or something (then SystemMaxUse will be 1GB)

**Comment by slivne** [comment]
fixed by 7479cde28bc87d7169e3c24df779a3661a3344a3

**Comment by avikivity** [comment]
On 01/13/2016 12:11 PM, Takuya ASADA wrote:
>
> @avikivity <https://github.com/avikivity> What size would be enough 
> for journal space?
> SystemMaxUse seems 10% of root disk size by default, so it is 600MB on 
> our AMI default root disk size (6GB), is it still not enough?
> Ι suppose real problem is our too small default root disk size, maybe 
> we should increase it to 10GB or something (then SystemMaxUse will be 1GB)
>
>

We can also bump that 10% to 20%.
