### ISSUE TITLE
Disk to RAM ratio for GCE is not set correctly

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#7587]
*Installation details*
Scylla version (or git commit hash): 4.4.dev-0.20201109.8bcdf39a1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 8

According to [Google](https://cloud.google.com/compute/docs/machine-types#n1_standard_machine_types) n1-standard-2 has 7.5Gb RAM 
But actually the number is ~7.3 GB:
```
>>> psutil.virtual_memory().total/1024/1024/1024
7.280799865722656
```

and when adding one 375Gb NVMe device `dist.common.scripts.scylla_util.gcp_instance.is_recommended_instance` doesn't 
return True
hence `dist/common/scripts/scylla_io_setup` runs iotune instead of using the predefined values

```
Nov 09 23:59:33 artifacts-gce-image-jenkins-db-node-38e42086-0-1 systemd[1]: Mounted Scylla data directory.
Nov 09 23:59:33 artifacts-gce-image-jenkins-db-node-38e42086-0-1 scylla_image_setup[740]: Created symlink /etc/systemd/system/multi-user.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
Nov 09 23:59:33 artifacts-gce-image-jenkins-db-node-38e42086-0-1 systemd[1]: Reloading.
Nov 09 23:59:33 artifacts-gce-image-jenkins-db-node-38e42086-0-1 scylla_image_setup[740]: Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
Nov 09 23:59:34 artifacts-gce-image-jenkins-db-node-38e42086-0-1 scylla_image_setup[740]: ERROR:root:This is not a recommended Google Cloud instance setup for auto tuning, running manual iotune.
Nov 09 23:59:35 artifacts-gce-image-jenkins-db-node-38e42086-0-1 scylla_image_setup[740]: INFO  2020-11-09 23:59:35,253 [shard 0] iotune - /var/lib/scylla/saved_caches passed sanity checks
Nov 09 23:59:35 artifacts-gce-image-jenkins-db-node-38e42086-0-1 scylla_image_setup[740]: Starting Evaluation. This may take a while...
```

We should probably increase the disk to RAM ratio to 53.
@tarzanek WUT?

**Comment by avikivity** [comment]
The disk to ram ratio we support is 100:1.

**Comment by tarzanek** [comment]
if Avi says it can be 100, then let's make 
https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_util.py#L313
100 instead of 50

@bentsi 
But that said in AWS the ratio is only 30 ! (so we already relaxed it when compared to AWS which is more stable cloud provider imho)
(and despite that it sometimes causes trouble)

how about we set it to 60?

**Comment by tarzanek** [comment]
( ... I wanted to suggest 52, since the plum spirit ( slivovica ) here in Moravia is burnt to 52 % of alc. , but some burn it to 56, some even to 64 or 73 and some people don't burn it properly and get blind ... :-D (have fun) )

**Comment by tarzanek** [comment]
ah ... and now I know why I didn't hit this in testing - n2-standard-2 has 8G :-D
https://cloud.google.com/compute/docs/machine-types#n2_standard_machine_types
expect unexpected!

**Comment by avikivity** [comment]
> ( ... I wanted to suggest 52, since the plum spirit ( slivovica ) here in Moravia is burnt to 52 % of alc. , but some burn it to 56, some even to 64 or 73 and some people don't burn it properly and get blind ... :-D (have fun) )

Why not 52.8 or 67.3 or -1/12?

**Comment by tarzanek** [comment]
I filed for 60, but I can switch it to 100 ... but that would allow 2 nvmes for n1-standard-2 
do we want to do it?

**Comment by avikivity** [comment]
Do you want to revisit this every time a cloud provider adds a new instance type?

**Comment by tarzanek** [comment]
no, but the numbers we have tuned for IO will be definitely bigger than what the machine will be able to do, so our recommendations will be bogus, I vote for 60
also this is about our recommendation, if it will fail, iotune will count some numbers which they will use

**Comment by tarzanek** [comment]
(and this just slipped in my tests, since I didn't verify/notice that n1 unlike n2 has 7.5 instead of 8 GB)

**Comment by tarzanek** [comment]
and slivovica is a matter of taste, I am quite sure some people do it 52.8 ... after all the stuff is burnt to really like 74-80% and then you make the final product(water it down) by adding clean water (ideally baby water from some natural spring)
so the % will oscillate based on how good you can look at the measurement tools

that's why you always do it the next day after burning, so you see proper results and numbers clearly :-D 
(for some unknown reason there is a tradition of trying out other spirits during 2. or 3. round of burning so until the distillation is done it's hard to see exact objects :-) )

at least when we measure the cloud speed we can see clearly (when google doesn't have a bug of course as with old nvme cards which when they are too much utilized can suddenly behave non-deterministically)

**Comment by avikivity** [comment]
Already in 4.3, earlier versions require iotune.
