### ISSUE TITLE
Deletion of large data records is overzealous

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7668]
As @raphaelsc noted in https://github.com/scylladb/scylla/issues/7562#issuecomment-731739849,
the way we decide whether to delete a large data record is by comparing the sstable data_size to each large data (partitions / rows / cells) threshold.  This will create unneeded tombstones, especially for the low order records - for large cells and large rows, as sstables bigger than 1MB or 10MB, respectively, are very common.

**Comment by raphaelsc** [comment]
this problem triggers the range tombstone issue we have in the read path, so querying large_cells table on a particular table is timing out to me:
select * from system.large_cells where keyspace_name='cdc_test' and table_name='test_table_scylla_cdc_log';
ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for system.large_cells - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}

**Comment by raphaelsc** [comment]
for a single partition in large_cells, there are hundreds of range tombstones, so fixing this problem is really important. otherwise i have to manually inspect large_cells content using sstabledump, because scylla can't return the partition to me without timing out.

**Comment by slivne** [comment]
closing this issue  - its still not great since we will generate range-tombstones in the case we do have large partitions - and range-tombstones have multiple issues

**Comment by bhalevy** [comment]
@slivne why did you reopen this issue?

**Comment by slivne** [comment]
maybe I reopenned the incorrect one - but the base issue of getting range tombstones into the cache because we have large partitions is not fixed. 

So we have reduced the issue and are not generating a range tombstone for files that don;t have large partitions - but in the case a customer has large partitions - we are going to create a real issue for him (and us) with generating range tombstones that can't be evicted out of the cache and only accumulate - those range tombstones are going to keep pilling up since a compaction of such a table ends up usually with another table that has a large partition as well ...

I think we need to mark the system_large* tables as tables that should not be cached to make sure we do not cause an issue and once we have range tombstones handling made better  (and we are working on that) consider removing that.

**Comment by slivne** [comment]
@bhalevy ^^

**Comment by bhalevy** [comment]
> maybe I reopenned the incorrect one - but the base issue of getting range tombstones into the cache because we have large partitions is not fixed.
> 
> So we have reduced the issue and are not generating a range tombstone for files that don;t have large partitions - but in the case a customer has large partitions - we are going to create a real issue for him (and us) with generating range tombstones that can't be evicted out of the cache and only accumulate - those range tombstones are going to keep pilling up since a compaction of such a table ends up usually with another table that has a large partition as well ...
> 
> I think we need to mark the system_large* tables as tables that should not be cached to make sure we do not cause an issue and once we have range tombstones handling made better (and we are working on that) consider removing that.

So let's open a different issue for that rather than hijacking this one, because the deletion of large data records is accurate now (since 4.5).

**Comment by bhalevy** [comment]
Closing this issue.  Work will continue on #8874
