### ISSUE TITLE
Not receiving callback from scylla driver when Primary DC bring UP

### ISSUE THREAD

**Issue by rahulMonu** [scylladb/scylla#7756]
Hi Scylla Team,

I have facing one issue in below scenario.

1 - Primary DC was DOWN, Secondary DC was UP When my application start 
      executed "cass_cluster_set_host_listener_callback" for both DC.

2 - Query execution going through Secondary DC. 

3 - In between when Primary DC came UP, then Not getting callback function registered while calling "cass_cluster_set_host_listener_callback". I need callback to switch query to Primary DC

Expected: callback function should be called with event "CASS_HOST_LISTENER_EVENT_UP" for Primary DC

*Installation details*
Scylla version : cpp-driver-2.11.0
Cluster size: 2 (Primary DC , Secondry DC)
OS (RHEL): rhel_7_2_x86_64

**Comment by jul-stas** [comment]
@rahulMonu Can you post your code sample? That would be very helpful - I just want to make sure we're thinking the same thing.

**Comment by jul-stas** [comment]
C* and Scylla work under the assumption that client apps are distributed and reside in DCs alongside DB clusters. If the whole DC fails it's OK for the driver to also fail (i.e. the driver is not expected to contact another DCs). Cross-DC traffic between the driver and cluster is avoided by default. Although it's possible to setup such a failover, it's deprecated and generates a warning.

Driver, depending on the load-balancing policy and specified contact points, determines which DC to connect. In your case, it's very likely that the "remote" (i.e. non-local) DC is not contacted at all and hence no events from it are received. That's why @rahulMonu I need to see your exact code. If you cannot share it, you can make an experiment to verify my theory: you can set round-robin load balancing and disable DC-aware one, so the driver connects to all the nodes in the cluster. If you start receiving events that would mean that it's the correct behavior.

Here's some code you can experiment with: https://gist.github.com/jul-stas/0ed32c0fe806f572f2ab71763da9b21c

**Comment by jul-stas** [comment]
@slivne I'm proposing to close this - we have a sensible explanation why this is the expected behavior.
If we want cpp-driver to follow java-driver (i.e. connect to all DCs) then let's start a separate thread (?)

**Comment by haaawk** [comment]
@rahulMonu would you like to verify @jul-stas hypothesis before we close this issue?
