### ISSUE TITLE
Possible schema discrepancy while updating secondary index computed column

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#7857]
17c323c096585835f9b3cc8e72917c5ea15e6ec1 (3.2) added a schema change that marks the token column of a materialized view implementing a secondary index as a computed column. It had two bugs: it does not propagate the schema change to the entire cluster (announce_locally is true) and it did not actually trigger unless the cluster was already 3.2+. This means that it only took effect after a rolling restart, after the cluster was fully upgraded.

b66c285f9449933486488d2cde7006c3c738e9b8 (4.1+) fixed the second problem, so now the fix triggers on nodes as they are upgraded, but still does not propagate the fix globally. The change can still be propagated if unrelated events cause schema propagation, or if the entire cluster is eventually updated. However, if there is no such unrelated event, there is a window where the schema is not synchronized. It could still be that schema pulls will fix it.

**Comment by avikivity** [comment]
@psarna we need to evaluate this for a backport. I'm not sure that a problematic scenario really exists.

**Comment by psarna** [comment]
I **think** that the scenario is unreachable - it still made sense to drop `announce_locally`, but I don't think it's a backport candidate. Please review my rationale:
1. Computed columns are guarded with a cluster feature, so they do not participate in the schema digest until each node understands them. Proof: https://github.com/scylladb/scylla/blob/d3aa17591c7eaf00ffdcc8738789cf4f8b5f3feb/db/schema_tables.cc#L3028-L3030
2. If a new node sends computed column information to older nodes, which do not expect to get it, the older nodes simply ignore the extraneous mutations, because that's how schema propagation works wrt. backward compatibility.

Given these two points, even if a node upgrades the schema only locally, the change will not get propagated until the whole cluster understands what computed columns are, which also means that the upgrade procedure is complete. The question is if the last upgraded node can cause any issues. Given that we don't upgrade multiple nodes at the same time and that the schema fixing happens very early in the process during the initial schema load, it should be safe. If I understand correctly, the schema digest on this node will never be computed *before* the initial schema is loaded, because that would make little sense and return empty digests.

**Comment by avikivity** [comment]
Given the evaluation, not backporting.
