### ISSUE TITLE
Master: Artifact tests fail

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#7900]
On Scylla/master: Artifact tests are failing.
Seastar issue that was expected to fix it: https://github.com/scylladb/seastar/pull/852 but didn't (it was merged before last artifact tests were running - based on next 3012).
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/artifacts/job/artifacts-centos7-test/326/
(other CentOS tests run only if CentOS 7 passes, so they didn't start).
All last runs of ubuntu and debian on https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/artifacts/

**Comment by amoskong** [comment]
This issue is duplicated with https://github.com/scylladb/scylla/issues/7895 (I mentioned two regression bugs there)


There are two regression bugs, first (scylla_setup fail) is fixed by https://github.com/scylladb/seastar/pull/852, the second (scylla_prepare fail) is fixed by https://github.com/scylladb/seastar/pull/853/  (https://github.com/scylladb/seastar/commit/ed345cdbe6a44b86ba8b6b1c75981ed565f10f4a)



@penberg we also need to update seastar commit in scylla repo for applying the fix.

**Comment by hagitsegev** [comment]
Looks like the needed commit entered later.
Most tests passed a few minutes ago.
I close the issue.
