### ISSUE TITLE
scylla failes to boot after interrupted compaction

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#802]
HEAD: 19e275be1fd36f49554e14fa141e4a4247290f8f
During the execution of the dtest [failure_durring_snapshot_no_corrupt_data](https://github.com/cloudius-systems/scylla-dtest/issues/113) case scylla crashed during the restart with the following symptom:
```
Scylla version development-20160110.d7b403d starting ...
WARN  [shard 0] config - Option truncate_request_timeout_in_ms is not (yet) used.
WARN  [shard 0] config - Option partitioner is not (yet) used.
WARN  [shard 0] config - Option request_timeout_in_ms is not (yet) used.
WARN  [shard 0] config - Option saved_caches_directory is not (yet) used.
WARN  [shard 0] config - Option hinted_handoff_enabled is not (yet) used.
WARN  [shard 0] config - Option range_request_timeout_in_ms is not (yet) used.
Scylla API server listening on 127.0.0.1:10000 ...
INFO  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
WARN  [shard 0] init - /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/commitlogs is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is strongly recommended
WARN  [shard 0] init - /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is strongly recommended
INFO  [shard 0] database - Populating Keyspace system
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF compaction_history
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF schema_keyspaces
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF sstable_activity
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF schema_triggers
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF peer_events
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF hints
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF size_estimates
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF schema_columnfamilies
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF paxos
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF batchlog
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF schema_usertypes
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF schema_columns
INFO  [shard 0] database - Keyspace /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system: Reading CF local
WARNING: exceptional future ignored of type 'sstables::malformed_sstable_exception': At directory: /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377: no TOC found for SSTable with generation 4!. Refusing to boot
Exiting on unhandled exception of type 'sstables::malformed_sstable_exception': At directory: /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377: no TOC found for SSTable with generation 4!. Refusing to boot
INFO  [shard 0] compaction_manager - compaction task handler stopped due to shutdown
INFO  [shard 0] compaction_manager - compaction task handler stopped due to shutdown
```

The contents of the corresponding data directory is
```
$ll /home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377
total 196K
drwx------.  3 vladz vladz 4.0K Jan 14 14:50 .
drwx------. 19 vladz vladz 4.0K Jan 14 14:49 ..
drwx------.  3 vladz vladz 4.0K Jan 14 14:50 snapshots
-rwx------.  2 vladz vladz    8 Jan 14 14:49 system-local-ka-1-CRC.db
-rwx------.  2 vladz vladz  561 Jan 14 14:49 system-local-ka-1-Data.db
-rwx------.  2 vladz vladz   10 Jan 14 14:49 system-local-ka-1-Digest.sha1
-rwx------.  2 vladz vladz   16 Jan 14 14:49 system-local-ka-1-Filter.db
-rwx------.  2 vladz vladz   19 Jan 14 14:49 system-local-ka-1-Index.db
-rwx------.  2 vladz vladz 4.4K Jan 14 14:49 system-local-ka-1-Statistics.db
-rwx------.  2 vladz vladz   59 Jan 14 14:49 system-local-ka-1-Summary.db
-rwx------.  2 vladz vladz    8 Jan 14 14:49 system-local-ka-2-CRC.db
-rwx------.  2 vladz vladz  126 Jan 14 14:49 system-local-ka-2-Data.db
-rwx------.  2 vladz vladz   10 Jan 14 14:49 system-local-ka-2-Digest.sha1
-rwx------.  2 vladz vladz   16 Jan 14 14:49 system-local-ka-2-Filter.db
-rwx------.  2 vladz vladz   19 Jan 14 14:49 system-local-ka-2-Index.db
-rwx------.  2 vladz vladz 4.4K Jan 14 14:49 system-local-ka-2-Statistics.db
-rwx------.  2 vladz vladz   59 Jan 14 14:49 system-local-ka-2-Summary.db
-rwx------.  2 vladz vladz    8 Jan 14 14:49 system-local-ka-3-CRC.db
-rwx------.  2 vladz vladz  12K Jan 14 14:49 system-local-ka-3-Data.db
-rwx------.  2 vladz vladz   10 Jan 14 14:49 system-local-ka-3-Digest.sha1
-rwx------.  2 vladz vladz   16 Jan 14 14:49 system-local-ka-3-Filter.db
-rwx------.  2 vladz vladz   19 Jan 14 14:49 system-local-ka-3-Index.db
-rwx------.  2 vladz vladz 4.5K Jan 14 14:49 system-local-ka-3-Statistics.db
-rwx------.  2 vladz vladz   59 Jan 14 14:49 system-local-ka-3-Summary.db
-rwx------.  2 vladz vladz    8 Jan 14 14:50 system-local-ka-4-CRC.db
-rwx------.  2 vladz vladz   87 Jan 14 14:50 system-local-ka-4-Data.db
-rwx------.  2 vladz vladz    9 Jan 14 14:50 system-local-ka-4-Digest.sha1
-rwx------.  2 vladz vladz   16 Jan 14 14:50 system-local-ka-4-Filter.db
-rwx------.  2 vladz vladz   19 Jan 14 14:50 system-local-ka-4-Index.db
-rwx------.  2 vladz vladz 4.4K Jan 14 14:50 system-local-ka-4-Statistics.db
-rwx------.  2 vladz vladz   59 Jan 14 14:50 system-local-ka-4-Summary.db
-rwx------.  1 vladz vladz    8 Jan 14 14:50 system-local-ka-5-CRC.db
-rwx------.  1 vladz vladz  13K Jan 14 14:50 system-local-ka-5-Data.db
-rwx------.  1 vladz vladz    9 Jan 14 14:50 system-local-ka-5-Digest.sha1
-rwx------.  1 vladz vladz 1.3K Jan 14 14:50 system-local-ka-5-Filter.db
-rwx------.  1 vladz vladz   19 Jan 14 14:50 system-local-ka-5-Index.db
-rwx------.  1 vladz vladz 4.5K Jan 14 14:50 system-local-ka-5-Statistics.db
-rwx------.  1 vladz vladz   59 Jan 14 14:50 system-local-ka-5-Summary.db
-rwx------.  1 vladz vladz   79 Jan 14 14:50 system-local-ka-5-TOC.txt
```
The last log message before scylla was killed in the step4 of the test was:
```
INFO  [shard 0] compaction - Compacted 4 sstables to [/home/vladz/.dtest/dtest-Zp_qkJ/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-5-Data.db:level=0, ]. 12716 bytes to 12503 (~98% of original) in 199ms = 0.0597023MB/s. ~1024 total partitions merged to 1.
```

So, probably the compaction process hasn't completed the `cleanup` stage and hasn't deleted all `old` sstables files before scylla was killed, which caused issues in the consequent boot.

**Comment by nyh** [comment]
We've discussed this issue heavily earlier today, and here is my summary of our conclusions (as I understood them). This will be pretty long, but I hope useful in planning the fixing of this issue and related issues:

Cleanup, as well as compaction, after having successfully written the new sstable (5 in your example), marks the old ones for deletion, and eventually deletes them. Each sstable has several files, which can't be deleted atomicly; So we delete the TOC file first, and if scylla is killed at this point, the TOC is gone but the rest of the files were left behind.

The *intention* behind this deletion order was that when we boot, if we see the TOC gone, we should consider this entire sstable to have been deleted (and can even delete the old left-behind files). But instead of removing the half-left-behind sstable, the code now complains and refuses to boot. This can be fixed as a first step of fixing this bug.

As a second step, let's go back to why the code currently complains when it sees a missing TOC. The thinking which led to this buggy behavior was that a file could also be missing because of random disk corruption. In that case, we want to report the error - not silently ignore this sstable! We can fix this case, without introducing the bug reported in this issue, in the following manner:
To delete an sstable, first rename the TOC file to ".toc.del" (or whatever), then delete the rest of the files, and finally (after fsync) delete .toc.del. During boot, if we find sstable files with a missing .toc, we check whether the .toc.del file exists. If it does, we know we were in the middle of a deletion, and need to delete the entire sstable (again, with .toc.del deleted last). But if it doesn't, then the .toc got deleted as part of a corruption, and we should complain and perhaps refuse to boot (as we do now).

Perhaps we don't need a new ".del" suffix as in the example above, because we already have a suffix which does (or should have done) more or less the same thing - ".tmp": When we write a new sstable, the TOC is named "TOC.txt.tmp" until renamed "TOC.txt" as a last step. If we boot and find an sstable with a TOC.txt.tmp, it means this sstable was half-written and should be deleted - just like I said above should happen in the ".del" case. So the same suffix, ".tmp", can probably be used for both cases, if handled correctly.

As a third step, we have an additional problem with the "cleanup" operation: We need to know when the files have been deleted, to let the user know when the cleanup can be considered done. The actual deletion may be delayed for a long time because a reader is using this sstable - so we'd prefer to return earlier, as soon as all shards marked this sstable for deletion. BUT, we need to make sure that the files are really deleted if a reboot occurs after this point. For this, we can use the same ".del" (or ".tmp") suffix as above: As soon as all shards agree to delete this sstable, we can rename its toc to toc.tmp; Existing readers can still use this sstable (we didn't touch the data files), but new readers can't find it (they don't need to), and if we reboot at this point, the ".toc.tmp" file will cause the boot process to delete this sstable.

**Comment by tgrabiec** [comment]
Related issue: #797

**Comment by nyh** [comment]
@tgrabiec, indeed, the "third step" in my comment above is about solving #797.
