### ISSUE TITLE
Gossip messages slowed down by RPC congestion

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#812]
Gossip messages need to be received in a timely manner, but RPC resource control can cause them to be blocked behind normal mutation verbs.

Can be fixed by separating gossip to a separate RPC resource control domain (and TCP connection).

See also #811.

**Comment by avikivity** [comment]
@gleb-cloudius

**Comment by slivne** [comment]
I thought this is already the state

I remember vaguely that @tgrabiec brought it up on schema migration and we
said that schema should be on the same channel as gossip

Can we do thios a bit more general instead of item by item

1 channel for mutations, query, query_result, streaming, repair

1 channel for mutation done

1 channel for gossip, schema

anything else ?

**Comment by avikivity** [comment]
I think we have a separate client, but they share a server.

**Comment by tgrabiec** [comment]
@avikivity It was assumed that throttling, if added, will be per-connection. If it's per-server, schema fetch may deadlock. Could we just exclude gossip and schema messages from throttling?

**Comment by avikivity** [comment]
We might add a per-client SLA (accept at least one message from each client).

We have to have a global SLA, because otherwise the total memory consumption is (client SLA) * (number of clients), which can grow without bounds as the number of connections can grow.

We can't simply exclude gossip and schema mesages, because if they block for some reason, the server may run out of memory.

**Comment by gleb-cloudius** [comment]
On Mon, Jan 18, 2016 at 04:21:16AM -0800, Avi Kivity wrote:
> We might add a per-client SLA (accept at least one message from each client).
> 
> We have to have a global SLA, because otherwise the total memory consumption is (client SLA) * (number of clients), which can grow without bounds as the number of connections can grow.
> 
> We can't simply exclude gossip and schema mesages, because if they block for some reason, the server may run out of memory.
> 
We cannot exclude then because to know message type we need to read it
fist and for that we need recourses. Not having limit for gossip and
schema messages would have been OK otherwise IMO. Gossip messages are
small and rare and if they block cluster will not function anyway and
schema messages a bounded by mutation messages which are bounded by a
limit. Since schema messages are small even if all mutation messages
will result in schema messages be sent to one shard it should still be
OK.

--
			Gleb.

**Comment by tgrabiec** [comment]
@gleb-cloudius gossip and schema messages are on their own connection, so we could exclude on per-connection basis, then we don't need to decide after reading, we know before we reading based on from which connection we read.

**Comment by avikivity** [comment]
But we need to identify the connection and match it with the SLA.  We could have an SLA identifier negotiated when the connection is established and then associate the connection with an SLA domain (each SDA domain has its own _resources_available semaphore).

**Comment by tgrabiec** [comment]
@avikivity Yes, for per-connection SLAs we would have to have some way of telling the other side what we expect from it.

**Comment by gleb-cloudius** [comment]
On Mon, Jan 18, 2016 at 04:45:42AM -0800, Avi Kivity wrote:
> But we need to identify the connection and match it with the SLA.  We could have an SLA identifier negotiated when the connection is established and then associate the connection with an SLA domain (each SDA domain has its own _resources_available semaphore).
> 
Well, this is better then having two servers.

--
			Gleb.

**Comment by avikivity** [comment]
Three, times two (TLS and plain) = 6

**Comment by avikivity** [comment]
I will prepare seastar patches.

**Comment by slivne** [comment]
@asias / @gleb-cloudius / @avikivity - are we using dedicated connections for gossip - in which case is this still relevant ?

**Comment by asias** [comment]
We use dedicated connection for gossip.
