### ISSUE TITLE
cas_statement_timeout_test: assert res.response_future._query_retries == combination_len failed

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8128]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/728/console
Scylla version d7f202f9008ce312a8d0b71b41d073db7923ce1c
```
07:02:58  FAIL: cas_statement_timeout_test (paxos_tests.TestPaxos)
07:02:58  ----------------------------------------------------------------------
07:02:58  Traceback (most recent call last):
07:02:58    File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/paxos_tests.py", line 378, in cas_statement_timeout_test
07:02:58      assert res.response_future._query_retries == combination_len
07:02:58  AssertionError
```

FWIW, node logs are here: https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/728/artifact/logs-debug.2/1613705054723_paxos_tests.TestPaxos.cas_statement_timeout_test

**Comment by bhalevy** [comment]
Cc @kostja

**Comment by slivne** [comment]
started being flaky ... and there is more then one error 
history https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/727/testReport/paxos_tests/TestPaxos/cas_statement_timeout_test/history/

**Comment by bhalevy** [comment]
First time I see this failure happening is https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/716/testReport/junit/paxos_tests/TestPaxos/cas_statement_timeout_test/

**Comment by kostja** [comment]
The test can be impacted by smp count and the load on the node (the timeout is set to 1 second). I would try to relax the assert a b it (>= combination_len), but @ManManson is the author. The test scenario itself doesn't seem to be part of any test plan I know, could it be an original cassandra test rewritten by us?

**Comment by ManManson** [comment]
@kostja Since both `smp` setting and the load on the nodes are fixed (that is, `smp=2` in the test setup and the test executes exactly 8 statements throughout the test, it's not a load test), it's mostly dependent on the performance of test servers, which execute the test.

What this test effectively does: it checks that `paxos_prepare_timeout`, `paxos_accept_proposal_timeout` and `paxos_state_learn_timeout` injections work as expected. But since there is one more test that uses these (`lwt_test.py:LwtReadLinearizabilityTest.read_linearizability_test`), this test becomes redundant. 

I suggest to remove the test altogether since if the custom write timeout value is removed, then the test would take too much time to finish (I expect no less than 10 minutes, not counting test cluster startup procedure).
