### ISSUE TITLE
Implement Hinted Handoff

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#819]
From https://wiki.apache.org/cassandra/HintedHandoff:

"Cassandra uses hinted handoff as a way to (1) reduce the time required for a temporarily failed node to become consistent again with live ones and (2) provide extreme write availability when consistency is not required."

In Scylla `storage_proxy::submit_hint()` is currently stubbed.

**Comment by gleb-cloudius** [comment]
On Mon, Jan 18, 2016 at 09:08:52AM -0800, Tomasz Grabiec wrote:
> From https://wiki.apache.org/cassandra/HintedHandoff:
> 
> "Cassandra uses hinted handoff as a way to (1) reduce the time required for a temporarily failed node to become consistent again with live ones and (2) provide extreme write availability when consistency is not required."
> 
> In Scylla `storage_proxy::submit_hint()` is currently stubbed.
> 
> 
We did not decided yet whether we are going to implement it at all or
will implement continuous repair.

--
			Gleb.

**Comment by tgrabiec** [comment]
How would this "continuous repair" work?

Wouldn't repair be much more expensive than hinted-handoff in terms of time required to achieve consistency and IO resources? Repair doesn't know which data the nodes missed, so it needs to scan the whole data set to at least calculate the hash.

**Comment by gleb-cloudius** [comment]
On Mon, Jan 18, 2016 at 09:17:53AM -0800, Tomasz Grabiec wrote:
> How would this "continuous repair" work?
> 
> Wouldn't repair be much more expensive than hinted-handoff in terms of time required to achieve consistency and IO resources? Repair doesn't know which data the nodes missed, so it needs to scan the whole data set to at least calculate the hash.
> 
I'll let Nadav answer that.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Mon, Jan 18, 2016 at 07:30:28PM +0200, Gleb Natapov wrote:
> On Mon, Jan 18, 2016 at 09:17:53AM -0800, Tomasz Grabiec wrote:
> > How would this "continuous repair" work?
> > 
> > Wouldn't repair be much more expensive than hinted-handoff in terms of time required to achieve consistency and IO resources? Repair doesn't know which data the nodes missed, so it needs to scan the whole data set to at least calculate the hash.
> > 
> I'll let Nadav answer that.
> 
BTW hinted handoff does not eliminate a need for repair, it tries to
alleviate it for small hiccups, but ultimately it was a hack around repair
operation been heavy.

--
			Gleb.

**Comment by nyh** [comment]
On Mon, Jan 18, 2016 at 7:17 PM, Tomasz Grabiec <notifications@github.com>
wrote:

> How would this "continuous repair" work?
>

I think Gleb meant "incremental repair", and using that continuously (i.e.,
frequently).

If incremental repair is very frequent (and each time it is very fast),
there isn't much need for hinted handoff.

Wouldn't repair be much more expensive than hinted-handoff in terms of time
> required to achieve consistency and IO resources? Repair doesn't know which
> data the nodes missed, so it needs to scan the whole data set to at least
> calculate the hash.
>
With incremental repair, the point is that you only need to scan the new
data since the last repair, and not the entire data set (as with regular
repair).

This is clearly slower than hinted handoff (which can simply look and see,
"hey, there is nothing to do because there is nothing in the hint table"),
but it solves many more problems than hinted handoff does, so if we already
will have incremental repair, there is less reason to *also* have hinted
handoff.

Of course, if implementing hinted handoff is easy (we already have calls
for it at the right places, for examples), maybe we should also implement
that. I don't know.

**Comment by tgrabiec** [comment]
@nyh Would incremental repair be run automatically or would it require human intervention?

**Comment by dorlaor** [comment]
We'd like to run incremental repair automatically but it has potential
caveats, mainly
between DCs (due to limited bandwidth). Judging from the hinted handoff
history of origin,
we either shouldn't implement it or do it for much more limited amount of
time/data.
Recently they moved the data out of separate tables into files (commit log
style per destination node)

**Comment by tzach** [comment]
In C* 3.x hints are stored in files to improve replay
https://docs.datastax.com/en/cassandra/3.0/cassandra/features.html
https://issues.apache.org/jira/browse/CASSANDRA-6230

**Comment by tzach** [comment]
related nodetool commands:

* nodetool enable/disablehandoff
* nodetool pausehandoff
* nodetool truncatehints- nodetool command to purge hints https://issues.apache.org/jira/browse/CASSANDRA-6158
* Make hinted_handoff_throttle_in_kb configurable via nodetool https://issues.apache.org/jira/browse/CASSANDRA-4750

**Comment by tzach** [comment]
related cassandra.yaml fix https://issues.apache.org/jira/browse/CASSANDRA-9035

**Comment by tzach** [comment]
related C* feature: compressing the hint files
https://issues.apache.org/jira/browse/CASSANDRA-9428

**Comment by avikivity** [comment]
On-disk compression for logs and hints makes sense for spinning disks, where the bandwidth is limited by the disk and controller.

For modern SSDs, it makes less sense since compression will be the bottleneck (esp. for logs that are only written, not read).

**Comment by slivne** [comment]
f6a461c7a44a1fb05375d33aff2f9926e691b84b

will be part of 2.2  - we are still working to close some gaps

- decommission
- resharding
