### ISSUE TITLE
Queries that are triggered via Alternator API support neither Slow Query Logging nor explicit Tracing enabling 

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#8292]
*Installation details*
HEAD: a49c4ab754dce26be708cad35141be5819c7a507

*Description*
Today you can only enable Tracing with the Alternator API using the Probabilistic Tracing.

For the regular CQL queries tracing can also be triggered using:
 * Slow Query Logging
 * Using a Trace bit on the CQL frame

I don't know if there is a way to request tracing for a specific operation with the DynamoDB API but Slow Query Logging should definitely be supported.

(Found by a code review)

**Comment by vladzcloudius** [comment]
@nyh @sitano FYI

**Comment by nyh** [comment]
Enabling tracing on a specific request is not part of the DynamoDB API, so it is unlikely we'll want to add such a feature at this stage, because clients who are using standard DynamoDB libraries (AWS SDK) would not be able to enable this feature.

But you're right that if "slow query tracing" is a global Scylla configuration, outside the DynamoDB API, then Alternator should indeed honor this configuration. I guess we need to figure how how it works in CQL and copy that implementation.

CC @psarna who did the original probabilistic tracing implementation in Alternator.

**Comment by psarna** [comment]
@vladzcloudius please let me know if I understand the implementation correctly - in order to allow slow query logging for alternator, a prelude similar to this one from CQL should be performed before creating a trace state pointer, right? If so, it sounds like a fairly quick patch.
https://github.com/scylladb/scylla/blob/f2ecb4617e479c9803e589ffd1b1e92abc47f472/transport/server.cc#L467-L479

And as for tracing a specific request, Nadav summed it up perfectly.

**Comment by psarna** [comment]
Ok, I confirmed via a simple experiment, it's indeed sufficient to just add slow query logging to `trace_state_props` and it works. I'll still need to experiment a little bit because currently the alternator query consists of just its JSON payload, while the operation name (e.g. CreateTable) is part of the HTTP header and doesn't get into the query string, which makes the log entry rather obfuscated - it's possible to guess what type of query it is, but it would be better if we knew it from the start. On the other hand, we don't want to create big strings which cause big allocations, so I'll need to figure out a copy-eliding way of putting everything into the trace. In any case, it's quite a simple change and I'll provide it soon.

**Comment by psarna** [comment]
Oh, actually I might be overengineering it all. The node_slow_log table will not consist of the type of alternator operation, but it contains the session id for the tracing session, which has all the information. It would perhaps not be good enough for slow query light mode (https://github.com/scylladb/scylla/issues/2572), but since it's not here yet, we can just rely on the session id for now. And the queries are really easy to distinguish anyway, since a GetItem request always contains a different set of parameters than UpdateItem, etc.

**Comment by vladzcloudius** [comment]
> @vladzcloudius please let me know if I understand the implementation correctly - in order to allow slow query logging for alternator, a prelude similar to this one from CQL should be performed before creating a trace state pointer, right? If so, it sounds like a fairly quick patch.
> 
> https://github.com/scylladb/scylla/blob/f2ecb4617e479c9803e589ffd1b1e92abc47f472/transport/server.cc#L467-L479

Correct, @psarna

**Comment by vladzcloudius** [comment]
> Oh, actually I might be overengineering it all. The node_slow_log table will not consist of the type of alternator operation, but it contains the session id for the tracing session, which has all the information. It would perhaps not be good enough for slow query light mode (#2572), but since it's not here yet, we can just rely on the session id for now. And the queries are really easy to distinguish anyway, since a GetItem request always contains a different set of parameters than UpdateItem, etc.

@psarna Not sure I understand your point above: `node_slow_log` contains all interesting information (and some more) that is in `sessions`. Things that are missing are `request/response_size` and `command` which is always `QUERY`.

**Comment by vladzcloudius** [comment]
> Ok, I confirmed via a simple experiment, it's indeed sufficient to just add slow query logging to `trace_state_props` and it works. I'll still need to experiment a little bit because currently the alternator query consists of just its JSON payload, while the operation name (e.g. CreateTable) is part of the HTTP header and doesn't get into the query string, which makes the log entry rather obfuscated - it's possible to guess what type of query it is, but it would be better if we knew it from the start. On the other hand, we don't want to create big strings which cause big allocations, so I'll need to figure out a copy-eliding way of putting everything into the trace. In any case, it's quite a simple change and I'll provide it soon.

You are definitely not overengineering it at all and, actually, there are a few places in the current Alternator code that may be improved in this regards.
For instance this one: https://github.com/scylladb/scylla/blob/master/alternator/server.cc#L355

Note how you always (!!!) formatting the string even if tracing is not enabled.

So, here are a few rules of thumb when it comes to Tracing:
* Avoid strings allocation/copying/formatting when Tracing is disabled. Example above is exactly such a case. You should have used a seastar::value_of() like we do here: https://github.com/scylladb/scylla/blob/master/transport/server.cc#L1038
* Try to avoid formatting everywhere except for tracing::trace(...) calls. This is related to #2572.

Please, let me know if you have more questions.

**Comment by psarna** [comment]
> > Ok, I confirmed via a simple experiment, it's indeed sufficient to just add slow query logging to `trace_state_props` and it works. I'll still need to experiment a little bit because currently the alternator query consists of just its JSON payload, while the operation name (e.g. CreateTable) is part of the HTTP header and doesn't get into the query string, which makes the log entry rather obfuscated - it's possible to guess what type of query it is, but it would be better if we knew it from the start. On the other hand, we don't want to create big strings which cause big allocations, so I'll need to figure out a copy-eliding way of putting everything into the trace. In any case, it's quite a simple change and I'll provide it soon.
> 
> You are definitely not overengineering it at all and, actually, there are a few places in the current Alternator code that may be improved in this regards.
> For instance this one: https://github.com/scylladb/scylla/blob/master/alternator/server.cc#L355
> 
> Note how you always (!!!) formatting the string even if tracing is not enabled: note that formatting is not only formatting but also dynamic allocation and a copy of the whole resulting string. VERY BAD!

This whole snippet is wrapped around in a condition: `if (tracing::tracing::get_local_tracing_instance().trace_next_query()) {`, and I understood that this condition is false if tracing is not enabled. Is it not the case?

> 
> So, here are a few rules of thumb when it comes to Tracing:
> 
>     * Avoid strings allocation/copying/formatting when Tracing is disabled. Example above is exactly such a case. You should have used a seastar::value_of() like we do here: https://github.com/scylladb/scylla/blob/master/transport/server.cc#L1038
> 
>     * Try to avoid formatting everywhere except for tracing::trace(...) calls. This is related to #2572.
> 
> 
> Please, let me know if you have more questions.

**Comment by vladzcloudius** [comment]
> > > Ok, I confirmed via a simple experiment, it's indeed sufficient to just add slow query logging to `trace_state_props` and it works. I'll still need to experiment a little bit because currently the alternator query consists of just its JSON payload, while the operation name (e.g. CreateTable) is part of the HTTP header and doesn't get into the query string, which makes the log entry rather obfuscated - it's possible to guess what type of query it is, but it would be better if we knew it from the start. On the other hand, we don't want to create big strings which cause big allocations, so I'll need to figure out a copy-eliding way of putting everything into the trace. In any case, it's quite a simple change and I'll provide it soon.
> > 
> > 
> > You are definitely not overengineering it at all and, actually, there are a few places in the current Alternator code that may be improved in this regards.
> > For instance this one: https://github.com/scylladb/scylla/blob/master/alternator/server.cc#L355
> > Note how you always (!!!) formatting the string even if tracing is not enabled: note that formatting is not only formatting but also dynamic allocation and a copy of the whole resulting string. VERY BAD!
> 
> This whole snippet is wrapped around in a condition: `if (tracing::tracing::get_local_tracing_instance().trace_next_query()) {`, and I understood that this condition is false if tracing is not enabled. Is it not the case?

You are right. I missed that external `if`. Then it's fine indeed. 
However, in the light of #2572 I'd recommend avoiding formatting in `trace::begin(...)`.
We are going to deprecate the `trace::begin(...)` specification that supports formatting and switch to an enum based version.

In your particular case you want to implement an enum that maps to string per Alternator `OP`.

**Comment by avikivity** [comment]
This is not a regression, and more of a feature than a bug, so not backporting for now.
