### ISSUE TITLE
Retire la/ka writer

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8352]
Now that all supported versions write mc/md sstables, we can deprecate the
MC_SSTABLE feature bit and consider it implicitly true, and with it the ability
to write la/ka sstables.

We still need to support reading them, e.g. from restoring old snapshots or migrating data from legacy clusters.

**Comment by haaawk** [comment]
We can't deprecate MC_SSTABLES at the moment because there's a enable_sstables_mc_format config flag that makes it possible to disable the feature. To safely remove MC_SSTABLES and UNBOUNDED_RANGE_TOMBSTONES features we need to first stop using enable_sstables_mc_format config flag and then we will be able to retire those features in the release following the  removal of the enable_sstables_mc_format config flag.

I prepared a PR that removes the config flag here -> https://github.com/scylladb/scylla/pull/8360
@avikivity if we could get it into 4.4 then it would be possible for us to remove la/ka writing in 4.5. Would you still accept such a harmless PR to 4.4?

**Comment by avikivity** [comment]
We can do nothing to 4.4.

**Comment by slivne** [comment]
merged into 4.5

we can consider this for 4.6

**Comment by haaawk** [comment]
I have a patch for this. Once I fix all the tests, I will post it.
