### ISSUE TITLE
Node cannot recover after crash

### ISSUE THREAD

**Issue by thirstycrow** [scylladb/scylla#8491]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.3.2
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.6

All 3 nodes in the cluster crashed and cannot recover, reporting the following error on restart:

```
Apr 15 17:43:25 my.hostname scylla[56218]:  [shard 0] init - loading system sstables
Apr 15 17:43:25 my.hostname scylla[56218]:  [shard 0] init - loading non-system sstables
Apr 15 17:43:25 my.hostname scylla[56218]: scylla: schema.cc:374: schema::schema(const schema::raw_schema&, std::optional<raw_view_info>): Assertion `!def.id || def.id == id - column_offset(def.kind)' failed.
Apr 15 17:43:25 my.hostname scylla[56218]: Aborting on shard 13.
Apr 15 17:43:25 my.hostname scylla[56218]: Backtrace:
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002b5b002
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002b5b690
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002b5b935
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002b5b980
Apr 15 17:43:25 my.hostname scylla[56218]: 0x00007f8a7c776a8f
Apr 15 17:43:25 my.hostname scylla[56218]: /opt/scylladb/libreloc/libc.so.6+0x000000000003c9e4
Apr 15 17:43:25 my.hostname scylla[56218]: /opt/scylladb/libreloc/libc.so.6+0x0000000000025894
Apr 15 17:43:25 my.hostname scylla[56218]: /opt/scylladb/libreloc/libc.so.6+0x0000000000025768
Apr 15 17:43:25 my.hostname scylla[56218]: /opt/scylladb/libreloc/libc.so.6+0x0000000000034e75
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000000edd6fe
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000000edd9cb
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000001b342df
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000001b6cf01
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002b59447
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002b596fe
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002b98fe5
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002baa79a
Apr 15 17:43:25 my.hostname scylla[56218]: 0x0000000002b2336d
Apr 15 17:43:25 my.hostname scylla[56218]: /opt/scylladb/libreloc/libpthread.so.0+0x0000000000009431
Apr 15 17:43:25 my.hostname scylla[56218]: /opt/scylladb/libreloc/libc.so.6+0x0000000000101912
```

Here's the error log when the node crashed for the first time. There's an altering and a dropping operation right before the crash.

```
Apr 15 16:54:39 my.hostname scylla[151614]:  [shard 28] schema_tables - Altering test.vip_travel_table id=349b11d0-9dc8-11eb-afbf-00000000001d version=cd313af8-a985-3d0e-92e4-a95d866aa5a8
Apr 15 16:54:39 my.hostname scylla[151614]:  [shard 28] schema_tables - Dropping test.idx_expire_at_index id=04634a21-8e17-11eb-9e11-00000000001c version=633d8932-0af5-338f-9f8e-0d2524c834a7
Apr 15 16:54:39 my.hostname scylla[151614]: scylla: schema.cc:374: schema::schema(const schema::raw_schema&, std::optional<raw_view_info>): Assertion `!def.id || def.id == id - column_offset(def.kind)' failed.
Apr 15 16:54:39 my.hostname scylla[151614]: Aborting on shard 28.
Apr 15 16:54:39 my.hostname scylla[151614]: Backtrace:
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000002b5b002
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000002b5b690
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000002b5b935
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000002b5b980
Apr 15 16:54:39 my.hostname scylla[151614]: 0x00007f4bbb25ca8f
Apr 15 16:54:39 my.hostname scylla[151614]: /opt/scylladb/libreloc/libc.so.6+0x000000000003c9e4
Apr 15 16:54:39 my.hostname scylla[151614]: /opt/scylladb/libreloc/libc.so.6+0x0000000000025894
Apr 15 16:54:39 my.hostname scylla[151614]: /opt/scylladb/libreloc/libc.so.6+0x0000000000025768
Apr 15 16:54:39 my.hostname scylla[151614]: /opt/scylladb/libreloc/libc.so.6+0x0000000000034e75
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000000edd6fe
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000000edd9cb
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000001b342df
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000001b34e32
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000001b18e1e
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000001b58cec
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000001b63810
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000001b64363
Apr 15 16:54:39 my.hostname scylla[151614]: 0x0000000002df702c
```

**Comment by raphaelsc** [comment]
please share schema of your tables, and also your alter statement on vip_travel_table. a coredump would be very helpful for debugging this issue, please find instructions on how to upload it here: https://docs.scylladb.com/troubleshooting/report_scylla_problem/#core-dump.

**Comment by thirstycrow** [comment]
@raphaelsc The table is created with the following CQL statement:
```
CREATE TABLE IF NOT EXISTS hikv_demo.vip_travel_table ( id text, node_code text, unique_code text, expire_at bigint, PRIMARY KEY (id));
```
and an index is created with:
```
CREATE INDEX IF NOT EXISTS idx_expire_at ON hikv_demo.vip_travel_table ( expire_at );
```

A compressed coredump is uploaded with the report uuid of 4bcb1dee-7ba6-4d8e-be73-68c83de3f3ef

**Comment by slivne** [comment]
schema related to MV / SI I suspect you may have seen this in the past

**Comment by eliransin** [comment]
@thirstycrow was the data/schema created with an older version?
Can you describe the test process, for example:
1. Start a new cluster
2. Populate (how? using a snapshot? or using some script and cql, maybe cassandra stress?)
3. etc...

**Comment by nyh** [comment]
This assertion is a very old one (added in commit 54268889a1, in 2015), and basically says that columns in a schema are ordered by type (e.g., all the regular columns together) and then numerically. If this assertion fails, something really weird happened, like perhaps one column went missing. @thirstycrow what change did your "ALTER" do? Also, was this something which happened to you once or something you can reproduce it? If you can reproduce this problem does it depend on doing both ALTER and DROP or perhaps DROP is enough?

I wonder how the **dropping the index**, like you did, might be related to this problem. Dropping an index is not supposed to change the list of columns in the base table at all, so was not supposed to trigger this assertion for the base table... But could this be some sort of race, were despite dropping the index someone tried to modify its schema? Could it be that because the index was already disabled at that time, the code didn't know that this schema was actually an index and prehaps it missed one of the columns (e.g., the computed token column, the first clustering key column) and the result was a missing column? @psarna does this guess make any sense to you?

It is unfortunate that the assertion doesn't give more information on what went wrong: Which schema (table) is this in, and its full list of columns where we detected this problem. I can provide a source patch which improves the message, but not sure if @thirstycrow compiles or can compile Scylla. The other alternative is to try to extract more such information from the core file, but I don't know how to do it... @eliransin can you point me to a document on how to download the core file and the executable?

**Comment by thirstycrow** [comment]
> @thirstycrow was the data/schema created with an older version?
It is possible but I'm not sure. The cluster is shared by many users for testing. I upgraded it from 3.1.2 several months ago. I have no idea the schema is created before or after that.

> Can you describe the test process
I asked the guy who was using the table. He said he did not submit an ALTER statement. No idea what's happening before the crash.

> Also, was this something which happened to you once or something you can reproduce it?
It happened only once, and I cannot reproduce it.

**Comment by nyh** [comment]
> > Can you describe the test process
> 
> I asked the guy who was using the table. He said he did not submit an ALTER statement.

But he did deliberate `DROP INDEX`, right?

If the answer is yes then I guess the `ALTER` of the base table is just a red herring - we need to `ALTER` the base table to say it no longer has an index - but this automatic `ALTER` shouldn't change anything in its list of columns (what this assertion checks) - the computed column should exist in the view (which is being dropped), not in the base table.

**Comment by thirstycrow** [comment]
> But he did deliberate DROP INDEX, right?
The base table is dropped at the end of the test. I expect the index being dropped as well, but `DROP INDEX` is not manually triggered.

**Comment by eliransin** [comment]
The only thing I can think of is creating the schema in 3.1 and then upgrading. My biggest suspicion is the computed column but I will need to try and reproduce it before being sure.
@thirstycrow just to make sure, when upgrading the cluster, did you do it incrementally passing through all of the versions between 3.1 to 4.3 or just one shot? The later case is not supported and a lot of bad stuff can happen since it is not tested.

**Comment by nyh** [comment]
> > But he did deliberate DROP INDEX, right?
> 
> The base table is dropped at the end of the test. I expect the index being dropped as well, but `DROP INDEX` is not manually triggered.

Interesting. So the first crash happened when the user deleted the table (and as part of that - its index), and this appears to have left the schemas on disk in such a state that booting up again fails again when reading it.

**Comment by thirstycrow** [comment]
> @thirstycrow just to make sure, when upgrading the cluster, did you do it incrementally passing through all of the versions between 3.1 to 4.3 or just one shot? The later case is not supported and a lot of bad stuff can happen since it is not tested.

I not sure, it's been a long time. The versions we use includes 3.1.2, 4.1.9 and 4.3.2, so it might be upgraded to 4.1.9 before 4.3.2, but I can't remember exactly.

**Comment by eliransin** [comment]
@thirstycrow if the upgrades were not incremental it is hard to tell what problems might occur. I am afraid it will be hard to
eliminate a problem in the upgrade path. However, if you can provide us with reproducer we will be more than happy to investigate. If the issue is not reproducible, I am afraid there is not much more we can do.
