### ISSUE TITLE
Mismatched types for base and view columns id: timeuuid and timeuuid

### ISSUE THREAD

**Issue by Phara0h** [scylladb/scylla#8666]
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.3
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

I have a global secondary index and it returns back 1020 results and if I try to retrieve anymore it throws this error ('Unable to complete the operation against any hosts', {<Host: 10.0.21.10:9042 us-east>: <Error from server: code=0000 [Server error] message="Mismatched types for base and view columns id: timeuuid and timeuuid">})

**Comment by psarna** [comment]
Could you provide the schemas for your base table and the offending index (with sensitive column names mangled)?

**Comment by psarna** [comment]
Also, if these schemas were ever changed (e.g. some columns were added or removed), that information would also help.

**Comment by psarna** [comment]
And one more helper question - does the base table or the index contain a non-standard ordering? In particular, is the indexed column a clustering column in the base table with descending order defined? That could explain my suspicion.

**Comment by psarna** [comment]
Ok, managed to reproduce myself - it's exactly that. The indexing code contains some additional checks if all the types match, but the checks don't work properly if the clustering order differs. Thanks for reporting, I'll create a reproducing test case and a fix.

**Comment by psarna** [comment]
Here's the fix and the new test case: #8667

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.

**Comment by avikivity** [comment]
@psarna something is missing in the 4.4/4.5 backport, and cql-pytest fails on the new test. Can you please figure out what it is?

**Comment by avikivity** [comment]
(I suspect it's in the test harness, not the fix)

**Comment by psarna** [comment]
checking

**Comment by psarna** [comment]
cql-pytest ran fine for me, **but** perhaps I see the problem. There was a conflict in `test_secondary_index.py` when cherry-picking to 4.5 that looked trivial, but simply accepting the incoming changes resulted in incidentally importing test cases from https://github.com/scylladb/scylla/pull/8632, which was not backported. Now, https://github.com/scylladb/scylla/pull/8632 is not really a showstopper, so I think we can skip backporting it, even though it's technically a bug. If you'd prefer to backport it anyway, let me know. Otherwise, I can enqueue this issue's fix to 4.4 and 4.5 manually, removing the stray test cases.

**Comment by avikivity** [comment]
Ah, for cleanliness I'll remove that unwanted change. We can decide on #8632 separately.
