### ISSUE TITLE
DOCS: Add an Alternator Getting Started Guide

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla#8771]
RE: https://github.com/scylladb/scylla-docs/issues/3156 
Moving the issue here
We need a Getting Started Guide for Alternator

**Comment by nyh** [comment]
We have one, https://github.com/scylladb/scylla/blob/master/docs/alternator/getting-started.md, written originally  by @eliransin (and since updated to match changing realities).
If thas document has the wrong focus, then we should change it - or replace it entirely - but we probably shouldn't have two different documents titled "getting started with Alternator".

**Comment by lauranovich** [comment]
@nyh - correct, I will close this and if something else comes up, we'll address it then
