### ISSUE TITLE
Handle physical devices under bond

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#891]
From @vladzcloudius 

```
ifconfig -a | egrep ^"\S" | cut -d":" -f1 | while read iface; do if ethtool -i $iface  &> /dev/null; then  if ethtool -i $iface | grep bus-info | egrep  "[[:xdigit:]]+\:[[:xdigit:]]+\:[[:xdigit:]]+\.[[:xdigit:]]"  &> /dev/null; then  if [[ `ls -1 /sys/class/net/$iface/device/msi_irqs/ |  wc -l` -gt 1 ]]; then sudo ./posix_net_conf.sh $iface -mq; else ./posix_net_conf.sh $iface; fi; fi; fi; done
```

**Comment by slivne** [comment]
does this work on ubuntu as well ?

**Comment by vladzcloudius** [comment]
@slivne Yes. This will work on Ubuntu as well (verified on Ubuntu 14.04)

**Comment by slivne** [comment]
not clear to me what we are looking for - 

are we going to run the posix_net_conf on all the interfaces on the machine - or are going to limit that to specific interfaces the user selects ?

**Comment by vladzcloudius** [comment]
On 02/14/2016 11:02 PM, slivne wrote:
>
> not clear to me what we are looking for -
>
> are we going to run the posix_net_conf on all the interfaces on the 
> machine - or are going to limit that to specific interfaces the user 
> selects ?
>

I think the right solution would be to have a user running the 
/posix_net_conf.sh /on the relevant interfaces with the correct 
parameter. We may help a user with finding all  physical interfaces in 
his/her box. The command to do so would be:

echo "Physical interfaces are:"; echo "------------------------"; ifconfig -a | egrep ^"\S" | cut -d":" -f1 | while read iface; do if ethtool -i $iface  &> /dev/null; then  if ethtool -i $iface | grep bus-info | egrep  "[[:xdigit:]]+\:[[:xdigit:]]+\:[[:xdigit:]]+\.[[:xdigit:]]"  &> /dev/null; then echo $iface; fi;  fi; done

**Comment by slivne** [comment]
we have in /etc/sysconfig/scylla-server a param IFNAME

we have code in scylla_prepare that uses this info 

```
else # NETWORK_MODE = posix
    if [ "$SET_NIC" = "yes" ]; then
        /usr/lib/scylla/posix_net_conf.sh $IFNAME
    fi
fi
```

To support bonding interfaces should we extend this support and allow specifying a single bond interface and then figure out all its physical ones and run on all of them in scylla_prepare - or should we allow specifying a list of IFNAME(s) that will have this script run on all

**Comment by vladzcloudius** [comment]
@avikivity @slivne @gleb-cloudius @tgrabiec 
First, I'd like to comment the current posix_net_conf.sh invocation mode. Let me remind that if '-mq' is not given it'll configure the so called "Gleb's" mode, when all HW IRQs are bound to CPU0 and RPS is enabled and distributed among all CPUs apart from CPU0. However, at least for me, it's not clear that this approach is always the best approach and AFAIR we haven't reached a definite conclusion on the relevant thread, where we discussed the (let's call it a "Tomek's mode") alternative configuration that is relevant for multi-queue devices, where RPS is disabled and HW IRQs are distributed equally among all CPUs. 

Let me also remind u that Tomek has performed all his performance testings using the later configuration. He used the strong setup with the 10G Intel's physical functions as networking interfaces. Physical functions have a lot more HW queues than SR-IOV virtual functions that we have on (the best) AWS instances, which Gleb has used. So, the main difference between Gleb's and Tomek's setups was the actual number of HW queues: Gleb had 1 or 2, while Tomek had 16 RSS queues and more (32 or 128 depending on the specific NIC model).

The main problem with the VFs (or any "weakly-multi-queue" networking device) Gleb saw was that heavy networking processing on a specific CPU caused the shard of this CPU to become a bottleneck due to limited processing power it had left and as a result degrade the whole Node's performance. To overcome this Gleb proposed to let all networking to be be processed on some specific CPU (CPU0) and take this CPU out of the Node's CPUs pool. This way Scylla looses one CPU but gains the more balanced processing power of the left shards thus eliminating or at least minimizing the imbalance he had before. We also loose the "locality" in this approach since L2 driver always handles the packet on the "wrong" CPU while we'd prefer it to be handled on the same CPU where its data is going to be used. But despite all negative effects this approach had proved to improve the performance on the setup Gleb was using. 

Tomek, on the other hand was given the much stronger setup with NICs having a lot more queues. And although Tomek had missed the fact that only 16 cores were handling Rx had all setup's cores to handle the Tx and as a result the total performance of the Node(s) was quite acceptable and he didn't try to analyze it further so we don't know if Gleb's approach would benefit us on Tomek's setup like it did on a setup. We'd also have some imbalance in this case as well since scylla's logic picks the shard according to the RSS configuration so that the received packets arrive to the chosen CPU. However the negative effect of this is expected to be much less pronounced than on the Gleb's setup since the whole NIC's Rx load would spread among 16 cores and wouldn't choke a single core as in Gleb's case. There would also be some "locality" "sub-optimality" on the Tx side since outbound packets would be send not from the cores that had handled the sent data in some cases. 

Having said all that IMHO the question about which approach is going to be better on a strong setup like Tomek's remains open. However based on the data we have in hand right now we may only say that Gleb's approach is beneficial on the setups with few HW queues (say where CPU cores to HW queues ratio is more or equal than 2) and Tomek's approach is beneficial on setups where NICs have enough HW queues. However the script above would always configure the Gleb's mode on any setup regardless the NIC's multi-queue capabilities which doesn't look like a best option to me.

I propose we do the following:

1. Add a capability to define a `posix_net_config.sh` mode in `scylla_prepare` so that a user may override an automatic (default) configuration mode.
2. Extend `scylla_prepare` to detect a NIC MQ capability and choose an appropriate `posix_net_config.sh` mode if user hasn't overridden it.

**Comment by vladzcloudius** [comment]
@slivne By the way, what our plans to support bridging interfaces used in VM environments? They resemble bonding interfaces in the way they don't have their own IRQ but rather have some underlying interfaces that sometimes do have their IRQs. "some times" is because VMs are allowed to work on top of a loopback interface. 
The bottom line is that if we want to start supporting VM environments we'd rather consider our further steps in regard their networking scylla-specific configuration. 

In any case I've opened an issue #1063 for tracking purposes.

**Comment by vladzcloudius** [comment]
@slivne By the way, what our plans to support bridging interfaces used in VM environments? They resemble bonding interfaces in the way they don't have their own IRQ but rather have some underlying interfaces that sometimes do have their IRQs. "some times" is because VMs are allowed to work on top of a loopback interface. 
The bottom line is that if we want to start supporting VM environments we'd rather consider our further steps in regard their networking scylla-specific configuration. 

In any case I've opened an issue #1063 for tracking purposes.
