### ISSUE TITLE
keyspace can become immortal after DROP KEYSPACE

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#8968]
Steps:
1. Start scylla: `docker run -d scylladb/scylla:4.4.1`
2. On console N1 run: `docker exec -i <docker_id> bash -c "while true; do sleep 1; cqlsh -e 'DROP KEYSPACE drop_table_during_repair_ks_9' || true ; done"`
3. On console N2 run: `docker exec -i <docker_id> bash -c "while true; do cassandra-stress write no-warmup cl=QUORUM -port jmx=6868 -mode native cql3  user=cassandra password=cassandra -schema keyspace=drop_table_during_repair_ks_9 'replication(factor=1)' -log interval=5 -node 172.17.0.11 -rate threads=100 fixed=1000/s -errors skip-unsupported-columns || true; done"`
4. After some time console N1 will stop reporting '<stdin>:1:ConfigurationException: Cannot drop non existing keyspace 'drop_table_during_repair_ks_9'.'
5. Stop both scripts
6. Run twice: `docker exec -i <docker_id> cqlsh -e 'DROP KEYSPACE drop_table_during_repair_ks_9'`

As you can see you can't drop this keyspace now.

!! IT BECOME IMMORTAL !!

**Comment by nyh** [comment]
Hi, we are well aware that our current implmentation of schema change operations (such as creating and dropping keyspace) is not safe against concurrent conflicting operations from different nodes - we're planning to use Raft to address this. 
However, if I understand your scenario correctly it is worse for two reasons:
1. Only one node is involved, so we should have been able to do the right locking on this single node without needing Raft.
2. Creating and dropping a keyspace with the same parameters every time should have been (?) easy to reconcile one way or the other, and end up with the keyspace either existing or not existing, but not something in the middle.

Since you are reporting this failure with a single node, I wanted to create a simple cql-pytest test to reproduce it, but so far not managing to. Maybe you can help me understand the problem you're seeing better by explaining in more detail the problem at the end: When you do the DROP KEYSPACE at the end, what error do you see? If you do DESCRIBE KEYSPACE for this keyspace, does it exist?

**Comment by nyh** [comment]
Unfortunately (or fortunately), I was finally able to reproduce this in a cql-pytest. It is apparently not enough to have a race of CREATE KEYSPACE and DROP KEYSPACE - it is also necessary to CREATE TABLE inside this keyspace in parallel with it being deleted. What I see in the end of this space is that "DROP KEYSPACE" succeeds but attempting "DROP KEYSPACE" again succeeds again (!) and attempting a "CREATE KEYSPACE" after the successful drop fails with "Keyspace 'cql_test_1625389979878' already exists".

I'll clean up my reproducer and post it here.

**Comment by nyh** [comment]
Here is a reproducing single-node test, use the cql-pytest framework:

```python
# Test reproducing issue #8968: We have two threads, one thread loops trying to
# create a keyspace and a table in it, and the other thread loops trying to
# delete this keyspace. Obviously some of these operations should fail - we
# can't create an already-existing keyspace if its deletion hasn't yet
# finished, and we can't create a table in a keyspace which was just deleted.
# But we expect to remain at the end of the test in some valid state - the
# keyspace should either exist or not exist. It shouldn't be in some broken
# immortal state are reported in issue #8968.
from threading import Thread
def test_concurrent_create_and_drop_keyspace(cql):
    ksdef = "WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'replication_factor' : 1 }"
    cfdef = "(a int PRIMARY KEY)"
    with new_test_keyspace(cql, ksdef) as keyspace:
        def drops(count):
            for i in range(count):
                try:
                    cql.execute(f"DROP KEYSPACE {keyspace}")
                except Exception as e: print(e)
                else: print("drop successful")
        def creates(count):
            for i in range(count):
                try:
                    cql.execute(f"CREATE KEYSPACE {keyspace} {ksdef}")
                    print("create keyspace successful")
                    # Create a table in this keyspace. This creation may
                    # race with deletion of the entire keyspace by the
                    # parallel thread. Reproducing #8968 requires this
                    # operation - just creating and deleting the keyspace
                    # without anything in it did not reproduce the problem.
                    cql.execute(f"CREATE TABLE {keyspace}.xyz {cfdef}")
                except Exception as e: print(e)
                else: print("create table successful")
        t1 = Thread(target=drops, args=[100])
        t2 = Thread(target=creates, args=[100])
        t1.start()
        t2.start()
        t1.join()
        t2.join()
        # At this point, the table should either exist, or not exist.
        # So CREATE KEYSPACE IF NOT EXIST should ensure it does exist,
        # and then one DROP KEYSPACE should succeed (not two!) and finally
        # we can recreate the keyspace as new_test_keyspace expects it.
        # If any of the following statements fail, it means we reached an
        # invalid state. This is issue #8968.
        cql.execute(f"CREATE KEYSPACE IF NOT EXISTS {keyspace} {ksdef}")
        cql.execute(f"DROP KEYSPACE {keyspace}")
        # See explanation above how different versions of Cassandra and
        # Scylla produce different errors when dropping a non-existent
        # keyspace:
        with pytest.raises( (InvalidRequest, ConfigurationException) ):
            cql.execute(f"DROP KEYSPACE {keyspace}")
        cql.execute(f"CREATE KEYSPACE {keyspace} {ksdef}")
```

The test passes on Cassandra, but fails on Scylla - after the two creation and deletion threads are done, the schema is left in an inconsistent state, and some one of the four operations we have the end fails. Usually it is the second DROP KEYSPACE that doesn't fail as it should (in fact, we can do 50 DROP KEYSPACE and they will all succeed), but in one case I saw the first DROP KEYSPACE fails saying "Can't find a column family with UUID 14347150-dcb3-11eb-b058-59a788a0520a".

Also even before end of the test (by which time we know the schema state is already corrupt), as far as I can tell every time we see in the log one earlier operation that failed with "Can't find a column family with UUID 1430a0c0-dcb3-11eb-b058-59a788a0520a" and it seems (but I'm not 100% sure) that the corruption starts at that point.

**Comment by nyh** [comment]
I sent a patch with a reproducing test to the mailing list, titled "[PATCH] cql-pytest: add reproducer for concurrent DROP KEYSPACE bug"
After that patch is applied, to run the test and see how it fails run:
```
test/cql-pytest/run --runxfail test_keyspace.py::test_concurrent_create_and_drop_keyspace
```

**Comment by nyh** [comment]
@kostja I can still reproduce this error with
```
test/cql-pytest/run --runxfail test_keyspace.py::test_concurrent_create_and_drop_keyspace
```
It doesn't fail every time - you can either try it multiple times or increase the "count" in the test. But it still fails.

Is this perhaps because cql-pytest doesn't use the new experimental Raft code? Should I enable it (in test/cql-pytest/run.py) so that we start testing the new Raft code instead of the older stuff?

**Comment by kostja** [comment]
Yes.

**Comment by nyh** [comment]
I'm happy to confirm that `--experimental-features=raft`, this test no longer fails.

I can produce a patch that will switch test/cql-ptest/run.py (used by test/cql-pytest and test/alternator and others) to use the upcoming raft-based schema changes instead of the up-till-now default approach.

However, we need to remember that the raft mode is not yet enabled by default - so this bug will continue to exist until it is. So I am not sure what's the best approach for testing and bug-tracking until then... Should we keep this issue open until it's solved by default? Should the regression tests check the default schema code (and say there are still bugs) or the new and upcoming raft-based schema code? If it's the latter - we switch the tests to checking the Raft version, how will we guard against regressions in the currently-**default** mode (i.e., we break something in the old code, but won't notice because we're testing with Raft).

**Comment by avikivity** [comment]
Patch just adds a test that verifies that raft fixes it. Not backporting.
