### ISSUE TITLE
HWLB overrides DC-based replica choice

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9068]
HWLB (Heat Weighted Load Balancing, see [this blog post](https://www.scylladb.com/2017/09/21/scylla-heat-weighted-load-balancing/), may change the replicas that a read request uses, after those replicas were already chosen by some other logic.  As can be seen in `db/consistency_level.cc`, the HWLB code is only avoided if all replicas' hit ratios are above 0.95 (`max_hit_rate`), or if they are lower but close to each other within 0.01 (`ht_max - ht_min > 0.01`). But in other cases, the HWLB code may be used.

When HWLB is used, it considers all replicas in the cluster, ignoring their placement into DCs. This can cause it to pick a node in a remote DC with a hot cache over a node in the local DC with a cold cache.

The problem with this is that Scylla might have had a good reason to choose a replica in a specific DC. Some consistency levels (`LOCAL_ONE`, `LOCAL_QUORUM`) explicitly request that only replicas in this DC be used, and will not expect replicas in other DCs to be used at all. Other consistency levels, though do not insist on a specific DC, still **prefer** (via a _snitch_) nodes in the local DC, because they will experience very high latencies if using a remote DC. So if HWLB thinks that by sending a request to a hot-cache node on a remote DC it will reduce latency, the reality will often be opposite, especially in a modern setup where disks have very low latency but cross-DC traffic has high latency.

We should consider changing HWLB to be aware of DCs. Perhaps if the selected replicas are all from one DC, don't consider replicas in other DCs.

CC @gleb-cloudius @vladzcloudius

**Comment by vladzcloudius** [comment]
Thanks, @nyh.

My initial feeling is that the part where non-local nodes are considered when a LOCAL_XX CLs is requested is a plain bug. @gleb-cloudius WDYT?

As to non-LOCAL-CLs I agree that it would be great if HWLB would have some logic that would consider "closeness" of nodes. However I'm not sure how to implement this is a good way.

To remind HWLB was implemented "instead" of a Dynamic Snitch which measures latency and thereby prioritizes "closer" nodes using a latency as a "distance".

And the decision of NOT implementing a Dynamic Snitch was made because we believed (we still do) that response loop algorithms (Dynamic Snitch is such an algorithm) were prone to resonance effect.

Therefore I don't see how we can identify in a reliable way if it's worth choosing a node from a remote DC with a hotter cache or going to a local DC node with a colder cache.

**Comment by gleb-cloudius** [comment]
On Wed, Jul 21, 2021 at 08:04:36AM -0700, Vladislav Zolotarov wrote:
> Thanks, @nyh.
> 
> My initial feeling is that the part where non-local nodes are considered when a LOCAL_XX CLs is requested is a plain bug. @gleb-cloudius WDYT?
> 
They do not. Local filtering happens before HWLB.

--
			Gleb.

**Comment by vladzcloudius** [comment]
> On Wed, Jul 21, 2021 at 08:04:36AM -0700, Vladislav Zolotarov wrote: Thanks, @nyh. My initial feeling is that the part where non-local nodes are considered when a LOCAL_XX CLs is requested is a plain bug. @gleb-cloudius WDYT?
> They do not. Local filtering happens before HWLB.

Right. It's done here, @nyh: https://github.com/scylladb/scylla/blob/scylla-4.5.rc5/db/consistency_level.cc#L176

**Comment by nyh** [comment]
You guys are right. I'll close this issue and open a new one without the errors.

**Comment by nyh** [comment]
Opened #9077 instead
