### ISSUE TITLE
install Scylla with curl https://install.scylladb.com | bash

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#908]
As @dorlaor  suggested in #801 we should have the entire install process starting from a single command:

```
curl https://install.scylladb.com | bash
```

the install script will install the RPM, and than run #801 
The script itself is not be part of the RPM and should be minimal, and work on RHEL and Debian base OS.

Here is google sdk example: https://sdk.cloud.google.com/

**Comment by tzach** [comment]
probably be easier to maintain as
```
curl https://docs.scylladb.com/install | bash
```

**Comment by avikivity** [comment]
How about a web page that allows you to prepare a scylla.yaml file with all needed settings (moving some of the install dialog to JavaScript). At the end you get a customized shortlink `https://scyl.la/deploy/f64mdy3d`, and you install by running curl `https://scyl.la/deploy/f64mdy3d | bash`

That removes repetitive actions that need to be taken on each node, by doing them once on the web page.

**Comment by tzach** [comment]
@avikivity this is a reflector++ service

I suggest opening a new issue for it, its orthogonal to this suggestion can be a follow-up

**Comment by amnonh** [comment]
On Wed, Jan 31, 2018 at 10:50 AM, Avi Kivity <notifications@github.com>
wrote:

> How about a web page that allows you to prepare a scylla.yaml file with
> all needed settings (moving some of the install dialog to JavaScript). At
> the end you get a customized shortlink https://scyl.la/deploy/f64mdy3d,
> and you install by running curl https://scyl.la/deploy/f64mdy3d | bash
>
> That removes repetitive actions that need to be taken on each node, by
> doing them once on the web page.
>
What I love about the idea, I can add the user ID to the yaml file and have
scylla report it.

**Comment by penberg** [comment]
You can now install Scylla server with:

```
curl -sSf get.scylladb.com/server | sudo bash
```

**Comment by nyh** [comment]
@penberg where do we have a document **pointing** to this installation method?
I think it's very important to have such a document which exactly what will happen when running this command - it's too scary to use otherwise. I can see in the script it (on Fedora for example) installs a new yum repo, and installs one RPM. Does it also modify something in the host's configuration (kernel parameters, etc.)? Are you supposed to run some sort of IO setup afterwards or something? If later you do "yum update", will you get Scylla updates? At all? Just patch releases? Even bigger upgrades? I also see this script has parameters, they should be documented.
All of this should be documented - nobody can guess the answers to this.

**Comment by dorlaor** [comment]
Really exciting! I have an error though. Btw, I have fedora32,  python3 and
not 2

curl -sSf get.scylladb.com/server | sudo bash
Installing Scylla version 4.3.1 for Fedora ...
Error:
 Problem: package scylla-4.3.1-0.20210210.46650adcd.x86_64 requires
scylla-tools-core = 4.3.1, but none of the providers can be installed
  - conflicting requests
  - nothing provides /usr/lib64/python2.7/site-packages/_yaml.so needed by
scylla-tools-core-4.3.1-0.20210210.46650adcd.noarch

**Comment by fgelcer** [comment]
maybe this is the time to move to python3, as python2 EOL more than 1 year ago
