### ISSUE TITLE
Memtable: support reverse queries efficiently

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9133]
Add efficient support for reverse queries to the memtable reader.

@enedil has started working on memtable

Refs #9130
Refs #9131

**Comment by nyh** [comment]
@bhalevy what's the point of having these individual issues? They don't have any information, and it will not be useful for backporting because all those changes will probably depend on one another - it's not like we can backport only the changes to memtable but not the changes to sstable and so on...

**Comment by bhalevy** [comment]
> @bhalevy what's the point of having these individual issues? They don't have any information, and it will not be useful for backporting because all those changes will probably depend on one another - it's not like we can backport only the changes to memtable but not the changes to sstable and so on...

1. @slivne asked for them.
2. They are useful in tracking the progress of individual tasks out of the bigger plan.

**Comment by bhalevy** [comment]
Refs #1413

**Comment by bhalevy** [comment]
Closing with #9174
