### ISSUE TITLE
Empty strings are not indexed properly leading to false negatives when querying for empty values  

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#9364]
```
CREATE TABLE cf ( name text PRIMARY KEY, val1 text, val2 text ); 
INSERT INTO cf (name, val1, val2) VALUES ('dmeyer', 'testval', '');
CREATE INDEX cf_val2_idx ON cf (val2);
```

```
cqlsh:ks> select * from cf;

 name    | val1    | val2
---------+---------+------
  dmeyer | testval |     


(1 row)

cqlsh:ks> select * from cf where val2 = '' allow filtering;

 name | val1 | val2
------+------+------

(0 rows)
```

After dropping the index the query works:

```
cqlsh:ks> drop index cf_val2_idx ;
```

```
cqlsh:ks> select * from cf where val2 = '' allow filtering;

 name   | val1    | val2
--------+---------+------
 dmeyer | testval |     

```

Refs #9352

**Comment by nyh** [comment]
@tgrabiec I think this issue is different from #9352 - if I understand correctly that issue is about a null key (which @kbr- rightly said is not allowed), but your issue is about an empty string - which should be allowed. I'll write tests for both cases to have a better understanding of what problems we have (or don't have) there.

**Comment by psarna** [comment]
@nyh issue #9352 is different, but it has similar roots - restrictions we place on primary keys for tables. We cannot use NULL as a primary key, which is the root cause of #9352, but we also cannot use **empty** values, e.g. a `''` string. I was quite surprised that it's the case, but it is. Because of that, we have an issue with materialized views and indexes - a regular column in the base table can contain an empty string without issues, but once we create a materialized view (or an index) on it, we make it a primary key in a different table. And that table still cannot tolerate empty values for keys, which causes the view to be incomplete - it does not contain entries which would use an empty value for a key column.

**Comment by nyh** [comment]
> @nyh issue #9352 is different, but it has similar roots - restrictions we place on primary keys for tables. We cannot use NULL as a primary key, which is the root cause of #9352, but we also cannot use **empty** values, e.g. a `''` string. I was quite surprised that it's the case, but it is. 

Wow, I absolutely didn't know that. Does an empty string and null have the same representation internally for us?

> Because of that, we have an issue with materialized views and indexes - a regular column in the base table can contain an empty string without issues, but once we create a materialized view (or an index) on it, we make it a primary key in a different table. And that table still cannot tolerate empty values for keys, which causes the view to be incomplete - it does not contain entries which would use an empty value for a key column.

Because null primary keys are not allowed, a materialized view explicitly has "IS NOT NULL" in its deceleration - to tell the user they should be aware that when an item's view-key has a null value it will not appear in the view. I never realized that we consider an empty string to be IS NULL. Is this true for Cassandra as well? I'll start writing tests for this :-(

**Comment by psarna** [comment]
> > @nyh issue #9352 is different, but it has similar roots - restrictions we place on primary keys for tables. We cannot use NULL as a primary key, which is the root cause of #9352, but we also cannot use **empty** values, e.g. a `''` string. I was quite surprised that it's the case, but it is.
> 
> Wow, I absolutely didn't know that. Does an empty string and null have the same representation internally for us?

No, regular columns are perfectly capable of distinguishing null from an empty string. I suppose an empty string is encoded as something with size 0. Still, for some historical reason we don't allow keys with size 0 at all.

Unrelated: I know that we don't have such a distinction with unfrozen collections, which I found surprising after I joined - an empty collection is undistinguishable from null.

> 
> > Because of that, we have an issue with materialized views and indexes - a regular column in the base table can contain an empty string without issues, but once we create a materialized view (or an index) on it, we make it a primary key in a different table. And that table still cannot tolerate empty values for keys, which causes the view to be incomplete - it does not contain entries which would use an empty value for a key column.
> 
> Because null primary keys are not allowed, a materialized view explicitly has "IS NOT NULL" in its deceleration - to tell the user they should be aware that when an item's view-key has a null value it will not appear in the view. I never realized that we consider an empty string to be IS NULL. Is this true for Cassandra as well? I'll start writing tests for this :-(

We don't consider an empty string to be null. I actually checked and Cassandra is capable of using empty key values for views, while it still does not alllow them for regular tables:

```cql
cassandra@cqlsh> CREATE KEYSPACE IF NOT EXISTS ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1}; use ks;
cassandra@cqlsh:ks> create table t (id text primary key, v text);
cassandra@cqlsh:ks> create MATERIALIZED VIEW mv as select id,v from t where v is not null and id is not null primary key (v, id);

Warnings :
Materialized views are experimental and are not recommended for production use.

cassandra@cqlsh:ks> insert into t(id,v) values ('a','b');
cassandra@cqlsh:ks> select * from mv;

 v | id
---+----
 b |  a

(1 rows)
cassandra@cqlsh:ks> insert into t(id,v) values ('empty','');
cassandra@cqlsh:ks> select * from mv;

 v | id
---+-------
   | empty
 b |     a

cassandra@cqlsh:ks> insert into t(id, v) values ('', 'empty');
InvalidRequest: Error from server: code=2200 [Invalid query] message="Key may not be empty"
```

**Comment by nyh** [comment]
Here is a simple test (cql-pytest framework) for this issue. It fails on Scylla and passes on Cassandra. Note that cql-pytest is a single node, so index updates are synchronous so no need for retry loops in the read:

```python3
def test_index_empty_string(cql, test_keyspace):
    schema = 'p int, v text, primary key (p)'
    # Searching for v='' without an index (with ALLOW FILTERING), works
    # as expected:
    with new_test_table(cql, test_keyspace, schema) as table:
        cql.execute(f"INSERT INTO {table} (p, v) VALUES (1, 'hello')")
        cql.execute(f"INSERT INTO {table} (p, v) VALUES (2, '')")
        assert_rows(cql.execute(f"SELECT p FROM {table} WHERE v='' ALLOW FILTERING"), [2])
    # Now try the same thing with an index on v. ALLOW FILTERING should
    # no longer be needed, and the result should be correct (issue #9364
    # is about wrong results here). We create here a new table instead of
    # adding an index to the existing table to avoid the question of how
    # will we know when the new index is ready (CREATE INDEX does not
    # wait for the indexing to be complete).
    with new_test_table(cql, test_keyspace, schema) as table:
        cql.execute(f"CREATE INDEX ON {table}(v)")
        cql.execute(f"INSERT INTO {table} (p, v) VALUES (1, 'hello')")
        cql.execute(f"INSERT INTO {table} (p, v) VALUES (2, '')")
        # The following assert fails in #9364:
        assert_rows(cql.execute(f"SELECT p FROM {table} WHERE v=''"), [2])
```

This demonstrates that this is a bona-fide Scylla bug - not some intentional CQL limitation.

**Comment by nyh** [comment]
> No, regular columns are perfectly capable of distinguishing null from an empty string. I suppose an empty string is encoded as something with size 0. Still, for some historical reason we don't allow keys with size 0 at all.

I'll create tests for this - both for regular tables and for MV.

> Unrelated: I know that we don't have such a distinction with unfrozen collections, which I found surprising after I joined - an empty collection is undistinguishable from null.

Yes, but this is both documented and I know its reason: A "collection" is nothing more than a bunch of sstable cells with a common prefix in their names. So an empty collection is nothing more than **no cells**, and this can't be distinguished from absolutely nothing. For CQL rows we have the "cql row marker" to distinguish a deliberately empty row from nothing, but collections don't have such a thing.

**Comment by avikivity** [comment]
Somewhat esoteric, not backporting.
