### ISSUE TITLE
repair: given_range_complement should not be a wrapping range

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#9560]
The range::subtract() was used as a trick to implement
range::intersection() when intersection was not available at that time.

The following code is problematic:

dht::token_range given_range_complement(tok_end, tok_start);

because dht::token_range should be non-wrapping range.

**Comment by nyh** [comment]
@asias would be useful to explain in the issue what is the scope or implication of this issue. Can it cause a user-visible bug (if so, please add the label "bug")? What sort of bug - what won't work in which conditions?

This information will be important when later we need to decide whether to backport this patch.

**Comment by nyh** [comment]
@asias explained in https://github.com/scylladb/scylla/pull/9561 that this is **not** a user-facing bug, but rather a code cleanup. The code uses a wrapping interval in a nonwrapping-interval variable, and everything works by accident (because apparently some of our nonwrapping-interval code still allows a wrapping interval) but might break in the future.

**Comment by avikivity** [comment]
Not a bug, not backporting.
