### ISSUE TITLE
Missing packages when installing on Debian 7.9

### ISSUE THREAD

**Issue by andreasanta** [scylladb/scylla#985]
root@mysql1:~# cat /etc/debian_version 
7.9
root@mysql1:~# apt-get install scylla-server
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 scylla-server : Depends: libboost-filesystem1.55.0 but it is not installable
                 Depends: libboost-program-options1.55.0 but it is not installable
                 Depends: libboost-system1.55.0 but it is not installable
                 Depends: libboost-test1.55.0 but it is not installable
                 Depends: libboost-thread1.55.0 but it is not installable
                 Depends: libc6 (>= 2.18) but 2.13-38+deb7u10 is to be installed
                 Depends: libgnutls28 (>= 3.2.10-0) but it is not installable
                 Depends: libgnutlsxx28 (>= 3.2.10-0) but it is not installable
                 Depends: liblz4-1 (>= 0.0~r113) but it is not installable
                 Depends: libthrift0 but it is not going to be installed
                 Depends: libyaml-cpp0.5 but it is not installable
                 Depends: hugepages but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by syuu1228** [comment]
@andreasanta First of all you cannot use Ubuntu package on Debian since it's different distribution (you won't be able to resolve dependencies), you have to build Scylla from source.

We cannot build Scylla on Debian 7.9 (oldstable), since there is no g++-4.9 or g++-5 packages.
I tried to build Scylla on Debian 8.3 (stable), it needed to few fixes, but able to produce .deb package for it.
Here's patches:
https://groups.google.com/forum/#!topic/scylladb-dev/EDutiJ57fAY

After merged the patch, you can build .deb like this:
```
git clone https://github.com/scylladb/scylla.git
git submodule update --init --recursive
./dist/ubuntu/build_deb.sh
```

**Comment by andreasanta** [comment]
Many thanks, will try and get back to you!

**Comment by avikivity** [comment]
Debian 7 will not be supported. Debian 8 is now formally supported.
