### ISSUE TITLE
It's not possible to run scylladb inside lxc-container.

### ISSUE THREAD

**Issue by hypnofrogme** [scylladb/scylla#989]
ScyllaDB upstart script requires dmidecode call which doesn't work inside LXC container.

root@scylla-lxc:~# dmidecode
# dmidecode 2.12
/dev/mem: Operation not permitted

**Comment by tzach** [comment]
There are more qualified virtualization experts on this project, but have you try Scylla on Docker?
http://www.scylladb.com/download/#docker

**Comment by syuu1228** [comment]
@hypnofrogme I'm not sure our scripts works in containers, but for dmidecode error you can modify "is_ami()" function on /usr/lib/scylla/scylla_io_setup to
```
is_ami() {
    echo 0
}
```
for temporary solution.
But it still may returns error since scylla checks you are using XFS, if not returns error.
You can append --developer-mode to tail of SCYLLA_ARGS on /etc/sysconfig/scylla-server, but it is just for testing, not for performance evaluation.

**Comment by hypnofrogme** [comment]
@syuu1228 
Thank you si much. I was not sure If I can remove the function.

**Comment by avikivity** [comment]
We should change is_ami to return false if there is no dmi data, instead of requiring users to change it.

**Comment by syuu1228** [comment]
@avikivity I realized that it actually returns 0 already, since -e does not applied to eval.
I guess real problem is not on this line of the script.

**Comment by syuu1228** [comment]
@avikivity We don't call scylla_io_setup on upstart script and also is_ami() function was dropped, so please close this.
