### ISSUE TITLE
Assertion failure if both alternator-port and alternator-https-port are provided

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#9914]
If you specify both alternator-port and alternator-https-port are provided, there is an assertion failure:

INFO  2022-01-14 18:22:59,915 [shard 0] cql_server_controller - Starting listening for CQL clients on 127.0.0.3:19042 (unencrypted, shard-aware)
scylla: ./seastar/include/seastar/core/sharded.hh:563: seastar::sharded<alternator::server>::~sharded() [Service = alternator::server]: Assertion `_instances.empty()' failed.
Aborting on shard 0.
Backtrace:
  0x23bc718
  0x23e47b2
  0x7f4884e333bf
  /lib/x86_64-linux-gnu/libc.so.6+0x4618a
  /lib/x86_64-linux-gnu/libc.so.6+0x25858
  /lib/x86_64-linux-gnu/libc.so.6+0x25728
  /lib/x86_64-linux-gnu/libc.so.6+0x36f35
  0xbe5159
  0xbd5098
  0xbd5088
  0xbd5078
  0xbd4f93
  0x2427954

**Comment by nyh** [comment]
The issue is slightly different from what you described - my personal run script has always done "--alternator-port=8000 --alternator-https-port=8043" and this has always worked, and still works on master today.

It turns out that I can reproduce this issue if not only both options are provided (which should be fine, and is fine) but if both options are given the **same port number**. Giving both options the same port number is obviously wrong (because the port number would be taken) but should result in a nice clean error message - not an assertion failure. I'll fix it.

**Comment by avikivity** [comment]
Minor, not backporting.

**Comment by nyh** [comment]
This problem is less minor than we hoped. Users are seeing crashes on various Alternator configuration mistakes (e.g., see #11520 discovered by @fee-mendes), instead of being given clear information on what the mistake is.

So I want to backport this fix after checking that it also fixes #11520.

**Comment by nyh** [comment]
On second thought, the buggy version in #11520 was 5.0.1, and that supposedly already contains this fix! So maybe it's not this patch that needs backporting. I'll keep looking for missing backports.
