### ISSUE TITLE
alternator: BatchGetItems should set UnprocessedKeys if any read failed

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#9984]
DynamoDB protocol specifies that when getting items in a batch
failed only partially, unprocessed keys can be returned so that
the user can perform a retry.

Refs #5650, which suggests a corresponding change for BatchWriteItems

**Comment by avikivity** [comment]
@nyh please evaluate for backport

**Comment by nyh** [comment]
I'm voting not to backport this, which is more an improvement than a bug fix.
Read failures should be very rare, and it's not a terrible loss to lose an entire batch of up to 20 reads instead of just one of them. In any case, even before the patch the read error of the entire batch was reported correctly and would lead to the client retrying the entire batch, so I think it wasn't a big loss.
